export const SHORTCUTS: Record<string, { key: string; ctrl?: boolean; shift?: boolean; alt?: boolean; description: string }> = {
  undo: { key: 'z', ctrl: true, description: 'Undo' },
  redo: { key: 'z', ctrl: true, shift: true, description: 'Redo' },
  saveProject: { key: 's', ctrl: true, description: 'Save project file' },
  loadProject: { key: 'o', ctrl: true, shift: true, description: 'Load/import project file' },
  reopenClosedDocument: { key: 't', ctrl: true, shift: true, description: 'Reopen closed document tab' },
  showShortcutHelp: { key: '? / F1', description: 'Open keyboard shortcuts panel' },
  copyPixels: { key: 'c', ctrl: true, description: 'Copy selection (or active layer)' },
  cutPixels: { key: 'x', ctrl: true, description: 'Cut active selection' },
  pastePixels: { key: 'v', ctrl: true, description: 'Paste from clipboard' },
  select: { key: 'm', description: 'Selection tool (marquee + move)' },
  deselect: { key: 'd', ctrl: true, description: 'Clear active selection' },
  brush: { key: 'b', description: 'Brush tool' },
  eraser: { key: 'e', description: 'Eraser tool' },
  fill: { key: 'g', description: 'Fill tool' },
  colorPicker: { key: 'i', description: 'Color picker tool' },
  line: { key: 'l', description: 'Line tool' },
  rect: { key: 'r', description: 'Rectangle tool' },
  togglePixelPerfect: { key: 'p', description: 'Toggle pixel perfect freehand mode' },
  toggleTracePolicy: { key: 't', description: 'Toggle freehand trace policy (Accumulate/UpdateLast)' },
  toggleSymmetryHorizontal: { key: 'h', description: 'Toggle horizontal symmetry component' },
  toggleSymmetryVertical: { key: 'v', description: 'Toggle vertical symmetry component' },
  moveSymmetryAxisX: { key: 'ArrowLeft / ArrowRight', alt: true, description: 'Move symmetry X axis by 1px' },
  moveSymmetryAxisY: { key: 'ArrowUp / ArrowDown', alt: true, description: 'Move symmetry Y axis by 1px' },
  moveSelection: { key: 'Arrow keys', description: 'Move selected pixels by 1px' },
  moveSelectionFast: { key: 'Shift + Arrow keys', description: 'Move selected pixels by 10px' },
  constrainLine: { key: 'Shift', description: 'Constrain freehand stroke to straight line' },
  quickColorPicker: { key: 'Click', alt: true, description: 'Quick color picker (while using brush/eraser)' },
  zoomIn: { key: '=', ctrl: true, description: 'Zoom in' },
  zoomOut: { key: '-', ctrl: true, description: 'Zoom out' },
  toggleGrid: { key: 'g', ctrl: true, description: 'Toggle grid' },
  toggleGhostFrames: { key: 'o', ctrl: true, description: 'Toggle ghost frames (echo view)' },
  playPause: { key: ' ', description: 'Play/Pause animation' },
  nextFrame: { key: '.', description: 'Next frame' },
  prevFrame: { key: ',', description: 'Previous frame' },
  swapColors: { key: 'x', description: 'Swap FG/BG colors' },
  decreaseStabilizer: { key: '[', description: 'Decrease stroke stabilizer' },
  increaseStabilizer: { key: ']', description: 'Increase stroke stabilizer' },
  deleteLayer: { key: 'Delete', description: 'Delete layer' },
  toggleSpriteLibrary: { key: 'l', ctrl: true, shift: true, description: 'Toggle Sprite Library' },
};
