/**
 * 16x16 cozy templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-01.
 * 5 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// KNITTING_BASKET — Woven basket overflowing with colorful yarn balls and knitting needles poking out.
// ════════════════════════════════════════════════════════════
export const KNITTING_BASKET_16: SpriteTemplate = {
  name: 'knitting_basket_16',
  width: 16,
  height: 16,
  description: 'Woven basket overflowing with colorful yarn balls and knitting needles poking out.',
  regions: [
    { name: 'basket_rim', role: 'head', pixels: [
      [1,7], [14,7],
      [1,8], [14,8],
      [1,9], [2,9], [13,9], [14,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [13,11],
      [2,12], [12,12], [13,12],
      [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13], [13,13],
    ]},
    { name: 'basket_weave', role: 'body', pixels: [
      [4,11], [6,11], [8,11], [10,11], [12,11],
      [3,12], [5,12], [7,12], [9,12], [11,12],
    ]},
    { name: 'basket_weave_alt', role: 'belt', pixels: [
      [10,5],
      [5,6],
      [9,8],
      [3,11], [5,11], [7,11], [9,11], [11,11],
      [4,12], [6,12], [8,12], [10,12],
    ]},
    { name: 'yarn_balls', role: 'arm', pixels: [
      [4,4], [5,4], [6,4], [7,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [11,5], [12,5],
      [3,6], [4,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [10,8], [11,8], [12,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'yarn_accent', role: 'eye', pixels: [
      [4,3], [5,3], [6,3], [7,3], [9,3], [10,3], [11,3],
      [3,4], [8,4], [12,4],
      [2,5], [13,5],
      [2,6], [13,6],
      [2,7], [13,7],
      [2,8], [13,8],
      [3,9], [12,9],
    ]},
    { name: 'needles', role: 'accessory', pixels: [
      [6,1], [7,1], [9,1], [10,1],
      [5,2], [8,2], [11,2],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// RECIPE_BOOK — Open recipe book with handwritten text lines, ingredient doodle, and ribbon bookmark.
// ════════════════════════════════════════════════════════════
export const RECIPE_BOOK_16: SpriteTemplate = {
  name: 'recipe_book_16',
  width: 16,
  height: 16,
  description: 'Open recipe book with handwritten text lines, ingredient doodle, and ribbon bookmark.',
  regions: [
    { name: 'cover', role: 'head', pixels: [
      [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1],
      [2,2], [13,2],
      [2,3], [13,3],
      [2,4], [13,4],
      [2,5], [13,5],
      [2,6], [13,6],
      [2,7], [13,7],
      [2,8], [13,8],
      [2,9], [13,9],
      [2,10], [13,10],
      [2,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
    ]},
    { name: 'pages', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3],
      [3,4],
      [3,5],
      [3,6],
      [3,7],
      [3,8],
      [3,9],
      [3,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'text_lines', role: 'belt', pixels: [
      [4,3], [5,3], [6,3], [7,3], [9,3], [10,3], [11,3], [12,3],
      [4,4], [5,4], [6,4], [7,4], [9,4], [10,4], [11,4], [12,4],
      [9,5], [10,5], [11,5], [12,5],
      [9,6], [10,6], [11,6], [12,6],
      [9,7], [10,7], [11,7], [12,7],
      [4,9], [5,9], [6,9], [7,9], [9,9], [10,9], [11,9], [12,9],
      [4,10], [5,10], [6,10], [7,10], [9,10], [10,10], [11,10], [12,10],
    ]},
    { name: 'ingredient_doodle', role: 'arm', pixels: [
      [4,6], [5,6], [6,6],
      [4,7], [6,7],
      [4,8], [5,8], [6,8],
    ]},
    { name: 'doodle_center', role: 'eye', pixels: [
      [5,7],
    ]},
    { name: 'ribbon', role: 'accessory', pixels: [
      [3,13],
      [3,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PICNIC_BLANKET — Checkered picnic blanket spread on grass with corner folded up.
// ════════════════════════════════════════════════════════════
export const PICNIC_BLANKET_16: SpriteTemplate = {
  name: 'picnic_blanket_16',
  width: 16,
  height: 16,
  description: 'Checkered picnic blanket spread on grass with corner folded up.',
  regions: [
    { name: 'check_dark', role: 'body', pixels: [
      [2,3], [4,3], [6,3], [8,3], [10,3], [12,3], [13,3],
      [3,4], [5,4], [7,4], [9,4], [11,4], [13,4],
      [2,5], [4,5], [6,5], [8,5], [10,5], [12,5], [13,5],
      [3,6], [5,6], [7,6], [9,6], [11,6], [13,6],
      [2,7], [4,7], [6,7], [8,7], [10,7], [12,7], [13,7],
      [3,8], [5,8], [7,8], [9,8], [11,8], [13,8],
      [2,9], [4,9], [6,9], [8,9], [10,9], [12,9], [13,9],
      [3,10], [5,10], [7,10], [9,10], [11,10], [13,10],
      [2,11], [4,11], [6,11], [8,11], [10,11], [12,11], [13,11],
      [3,12], [5,12], [7,12], [9,12],
      [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13],
    ]},
    { name: 'check_light', role: 'head', pixels: [
      [3,3], [5,3], [7,3], [9,3], [11,3],
      [2,4], [4,4], [6,4], [8,4], [10,4], [12,4],
      [3,5], [5,5], [7,5], [9,5], [11,5],
      [2,6], [4,6], [6,6], [8,6], [10,6], [12,6],
      [3,7], [5,7], [7,7], [9,7], [11,7],
      [2,8], [4,8], [6,8], [8,8], [10,8], [12,8],
      [3,9], [5,9], [7,9], [9,9], [11,9],
      [2,10], [4,10], [6,10], [8,10], [10,10], [12,10],
      [3,11], [5,11], [7,11], [9,11], [11,11],
      [2,12], [4,12], [6,12], [8,12], [10,12],
    ]},
    { name: 'fold_underside', role: 'arm', pixels: [
      [11,12], [12,12],
      [10,13], [11,13], [12,13],
    ]},
    { name: 'fold_shadow', role: 'belt', pixels: [
      [13,12],
      [13,13],
      [13,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WALL_CLOCK_COZY — Round wall clock with wooden frame, white face, hour/minute hands, and pendulum.
// ════════════════════════════════════════════════════════════
export const WALL_CLOCK_COZY_16: SpriteTemplate = {
  name: 'wall_clock_cozy_16',
  width: 16,
  height: 16,
  description: 'Round wall clock with wooden frame, white face, hour/minute hands, and pendulum.',
  regions: [
    { name: 'frame', role: 'head', pixels: [
      [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [4,2], [5,2], [10,2], [11,2],
      [3,3], [12,3],
      [3,4], [12,4],
      [3,5], [12,5],
      [3,6], [12,6],
      [3,7], [12,7],
      [3,8], [12,8],
      [4,9], [5,9], [10,9], [11,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
    ]},
    { name: 'clock_face', role: 'body', pixels: [
      [6,2], [7,2], [8,2], [9,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [4,4], [5,4], [6,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [6,9], [7,9], [8,9], [9,9],
      [7,11], [8,11],
      [6,12], [9,12],
      [6,14], [9,14],
    ]},
    { name: 'hour_hand', role: 'eye', pixels: [
      [7,5],
      [7,6],
      [7,7], [8,7],
    ]},
    { name: 'minute_hand', role: 'arm', pixels: [
      [9,7],
    ]},
    { name: 'hour_mark', role: 'accessory', pixels: [
      [11,5],
    ]},
    { name: 'pendulum', role: 'belt', pixels: [
      [7,12], [8,12],
      [7,13], [8,13],
      [7,14], [8,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// FLOWER_VASE — Ceramic vase with colorful flower bouquet — tulips, daisies, and leaves.
// ════════════════════════════════════════════════════════════
export const FLOWER_VASE_16: SpriteTemplate = {
  name: 'flower_vase_16',
  width: 16,
  height: 16,
  description: 'Ceramic vase with colorful flower bouquet — tulips, daisies, and leaves.',
  regions: [
    { name: 'vase_rim', role: 'head', pixels: [
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [10,8], [11,8],
      [4,9], [10,9], [11,9],
      [4,10], [11,10],
      [4,11], [10,11], [11,11],
      [4,12], [5,12], [10,12], [11,12],
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
    { name: 'vase_body', role: 'body', pixels: [
      [6,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9], [9,9],
      [5,10], [6,10], [8,10], [9,10], [10,10],
      [5,11], [6,11], [7,11], [8,11], [9,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'vase_pattern', role: 'belt', pixels: [
      [7,10],
    ]},
    { name: 'flower_red', role: 'arm', pixels: [
      [5,1], [6,1],
      [4,2], [5,2], [6,2],
      [4,3], [5,3], [7,3],
      [7,4],
    ]},
    { name: 'flower_yellow', role: 'eye', pixels: [
      [8,1], [9,1],
      [8,2], [9,2], [10,2],
      [8,3], [9,3],
      [9,4],
      [9,5],
    ]},
    { name: 'leaves', role: 'accessory', pixels: [
      [11,3],
      [4,4], [5,4], [8,4], [11,4],
      [5,5], [6,5], [8,5], [11,5],
      [5,6], [6,6], [8,6], [9,6],
    ]},
    { name: 'leaf_dark', role: 'leg', pixels: [
      [3,3], [6,3], [10,3],
      [3,4], [6,4], [10,4],
      [4,5], [10,5],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const KNITTING_BASKET_COLORS: ColorScheme = {
  name: 'knitting_basket_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
  },
};

export const RECIPE_BOOK_COLORS: ColorScheme = {
  name: 'recipe_book_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const PICNIC_BLANKET_COLORS: ColorScheme = {
  name: 'picnic_blanket_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const WALL_CLOCK_COZY_COLORS: ColorScheme = {
  name: 'wall_clock_cozy_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
    body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const FLOWER_VASE_COLORS: ColorScheme = {
  name: 'flower_vase_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
    arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    leg:       { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const COZY_BATCH4_TEMPLATES: Record<string, SpriteTemplate> = {
  knitting_basket_16: KNITTING_BASKET_16,
  recipe_book_16: RECIPE_BOOK_16,
  picnic_blanket_16: PICNIC_BLANKET_16,
  wall_clock_cozy_16: WALL_CLOCK_COZY_16,
  flower_vase_16: FLOWER_VASE_16,
};

export const COZY_BATCH4_COLOR_SCHEMES: Record<string, ColorScheme> = {
  knitting_basket_default: KNITTING_BASKET_COLORS,
  recipe_book_default: RECIPE_BOOK_COLORS,
  picnic_blanket_default: PICNIC_BLANKET_COLORS,
  wall_clock_cozy_default: WALL_CLOCK_COZY_COLORS,
  flower_vase_default: FLOWER_VASE_COLORS,
};
