/**
 * 16x16 food templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-05.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// DRAGON_FRUIT_FARM — Pink dragon fruit with scale protrusions, cut showing white flesh and seeds.
// ════════════════════════════════════════════════════════════
export const DRAGON_FRUIT_FARM_16: SpriteTemplate = {
  name: 'dragon_fruit_farm_16',
  width: 16,
  height: 16,
  description: 'Pink dragon fruit with scale protrusions, cut showing white flesh and seeds.',
  regions: [
    { name: 'scale_tip', role: 'accessory', pixels: [
      [6,0], [7,0], [8,0], [9,0],
      [5,1], [10,1],
      [3,3], [12,3],
      [2,4], [13,4],
      [1,6], [14,6],
      [2,8], [13,8],
      [3,9], [12,9],
    ]},
    { name: 'pink_skin', role: 'body', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [4,3], [5,3], [10,3], [11,3],
      [3,4], [4,4], [11,4], [12,4],
      [2,5], [3,5], [12,5], [13,5],
      [2,6], [3,6], [12,6], [13,6],
      [2,7], [3,7], [12,7], [13,7],
      [3,8], [4,8], [11,8], [12,8],
      [4,9], [5,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
    { name: 'white_flesh', role: 'head', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [8,5], [9,5], [11,5],
      [4,6], [5,6], [6,6], [8,6], [9,6], [11,6],
      [4,7], [5,7], [7,7], [8,7], [9,7], [11,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'seeds', role: 'arm', pixels: [
      [7,5], [10,5],
      [10,6],
      [6,7], [10,7],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,6],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,12], [7,12], [8,12], [9,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// STARFRUIT_FARM — Yellow star-shaped cross section of starfruit with five points.
// ════════════════════════════════════════════════════════════
export const STARFRUIT_FARM_16: SpriteTemplate = {
  name: 'starfruit_farm_16',
  width: 16,
  height: 16,
  description: 'Yellow star-shaped cross section of starfruit with five points.',
  regions: [
    { name: 'flesh', role: 'body', pixels: [
      [7,1], [8,1],
      [6,2], [9,2],
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [0,6], [1,6], [2,6], [3,6], [7,6], [8,6], [12,6], [13,6], [14,6], [15,6],
      [1,7], [2,7], [3,7], [4,7], [6,7], [9,7], [11,7], [12,7], [13,7], [14,7],
      [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [1,10], [2,10], [3,10], [4,10], [5,10], [10,10], [11,10], [12,10], [13,10], [14,10],
      [0,11], [1,11], [2,11], [3,11], [12,11], [13,11], [14,11], [15,11],
      [0,12], [1,12], [2,12], [13,12], [14,12], [15,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,2], [8,2],
    ]},
    { name: 'ridge', role: 'head', pixels: [
      [4,6], [6,6], [9,6], [11,6], [5,7], [10,7],
    ]},
    { name: 'core', role: 'accessory', pixels: [
      [7,7], [8,7], [7,8], [8,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PAPAYA_HALF — Elongated oval papaya half showing cavity with dark round seeds.
// ════════════════════════════════════════════════════════════
export const PAPAYA_HALF_16: SpriteTemplate = {
  name: 'papaya_half_16',
  width: 16,
  height: 16,
  description: 'Elongated oval papaya half showing cavity with dark round seeds.',
  regions: [
    { name: 'green_skin', role: 'accessory', pixels: [
      [7,1], [8,1], [9,1],
      [6,2], [7,2], [8,2], [9,2], [10,2],
      [5,3], [6,3], [10,3], [11,3],
      [4,4], [5,4], [11,4], [12,4],
      [3,5], [4,5], [11,5], [12,5], [13,5],
      [3,6], [11,6], [12,6], [13,6],
      [2,7], [3,7], [13,7],
      [2,8], [3,8], [13,8], [14,8],
      [2,9], [3,9], [13,9], [14,9],
      [3,10], [4,10], [11,10], [12,10], [13,10],
      [4,11], [5,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'orange_flesh', role: 'body', pixels: [
      [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4], [10,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [10,6],
      [4,7], [5,7], [6,7], [11,7], [12,7],
      [4,8], [5,8], [6,8], [7,8], [11,8], [12,8],
      [4,9], [5,9], [6,9], [10,9], [11,9], [12,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [6,11], [7,11], [8,11],
    ]},
    { name: 'seeds', role: 'head', pixels: [
      [8,6], [9,6],
      [8,7], [9,7], [10,7],
      [8,8], [9,8], [10,8],
      [7,9], [8,9], [9,9],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// LYCHEE_FARM — Red/pink rough-skinned lychee with white inside peeking out.
// ════════════════════════════════════════════════════════════
export const LYCHEE_FARM_16: SpriteTemplate = {
  name: 'lychee_farm_16',
  width: 16,
  height: 16,
  description: 'Red/pink rough-skinned lychee with white inside peeking out.',
  regions: [
    { name: 'stem', role: 'arm', pixels: [
      [8,1], [9,1],
      [7,2], [10,2],
    ]},
    { name: 'leaf', role: 'accessory', pixels: [
      [8,2], [9,2],
    ]},
    { name: 'rough_skin', role: 'body', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'white_flesh', role: 'head', pixels: [
      [8,5], [9,5],
      [7,6], [8,6], [9,6],
      [7,7], [9,7], [10,7],
      [6,8], [7,8], [8,8], [9,8],
      [7,9], [8,9],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GUAVA_FARM — Wide oval guava cut in half showing pink interior flesh.
// ════════════════════════════════════════════════════════════
export const GUAVA_FARM_16: SpriteTemplate = {
  name: 'guava_farm_16',
  width: 16,
  height: 16,
  description: 'Wide oval guava cut in half showing pink interior flesh.',
  regions: [
    { name: 'green_skin', role: 'body', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [2,4], [3,4], [4,4], [5,4], [10,4], [11,4], [12,4], [13,4],
      [1,5], [2,5], [3,5], [4,5], [5,5], [11,5], [12,5], [13,5], [14,5],
      [1,6], [2,6], [3,6], [4,6], [11,6], [12,6], [13,6], [14,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [11,7], [12,7], [13,7], [14,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'pink_flesh', role: 'head', pixels: [
      [6,4], [7,4], [8,4], [9,4],
      [6,5], [7,5], [8,5], [9,5], [10,5],
      [5,6], [6,6], [7,6], [9,6], [10,6],
      [6,7], [7,7], [8,7], [9,7], [10,7],
      [7,8], [8,8],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,6],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PERSIMMON_FARM — Wide flat persimmon with large spreading green leaf calyx.
// ════════════════════════════════════════════════════════════
export const PERSIMMON_FARM_16: SpriteTemplate = {
  name: 'persimmon_farm_16',
  width: 16,
  height: 16,
  description: 'Wide flat persimmon with large spreading green leaf calyx.',
  regions: [
    { name: 'leaf_calyx', role: 'accessory', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,5],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// RAMBUTAN_FARM — Red hairy rambutan fruit with spiky tendrils.
// ════════════════════════════════════════════════════════════
export const RAMBUTAN_FARM_16: SpriteTemplate = {
  name: 'rambutan_farm_16',
  width: 16,
  height: 16,
  description: 'Red hairy rambutan fruit with spiky tendrils.',
  regions: [
    { name: 'hair_tendril', role: 'accessory', pixels: [
      [6,0], [8,0], [9,0],
      [5,1], [7,1], [8,1], [10,1],
      [4,2], [11,2],
      [3,3], [12,3],
      [2,4], [13,4],
      [2,5], [13,5],
      [1,6], [14,6],
      [1,7], [14,7],
      [1,8], [14,8],
      [2,9], [12,9], [13,9],
      [2,10], [13,10],
      [3,11], [12,11],
      [4,12], [11,12],
      [5,13], [10,13],
      [6,14], [7,14], [8,14], [9,14],
    ]},
    { name: 'red_skin', role: 'body', pixels: [
      [6,2], [7,2], [8,2], [9,2],
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [9,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,5],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// JACKFRUIT_CHUNK — Yellow jackfruit segment/pod with visible seed.
// ════════════════════════════════════════════════════════════
export const JACKFRUIT_CHUNK_16: SpriteTemplate = {
  name: 'jackfruit_chunk_16',
  width: 16,
  height: 16,
  description: 'Yellow jackfruit segment/pod with visible seed.',
  regions: [
    { name: 'flesh', role: 'body', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [10,9], [11,9], [12,9], [13,9],
      [4,10], [5,10], [6,10], [9,10], [10,10], [11,10], [12,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'seed', role: 'head', pixels: [
      [7,8], [8,8],
      [6,9], [7,9], [8,9], [9,9],
      [7,10], [8,10],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,6],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// KUMQUAT_FARM — Tiny orange oval kumquat with small leaf at top.
// ════════════════════════════════════════════════════════════
export const KUMQUAT_FARM_16: SpriteTemplate = {
  name: 'kumquat_farm_16',
  width: 16,
  height: 16,
  description: 'Tiny orange oval kumquat with small leaf at top.',
  regions: [
    { name: 'leaf', role: 'accessory', pixels: [
      [7,3], [8,3],
      [7,4], [8,4],
    ]},
    { name: 'stem', role: 'arm', pixels: [
      [6,4], [9,4],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [7,5], [8,5],
      [6,6], [7,6], [8,6], [9,6],
      [5,7], [6,7], [7,7], [9,7], [10,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,11], [7,11], [8,11], [9,11],
      [7,12], [8,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BLOOD_ORANGE — Orange half showing deep red interior with segment lines.
// ════════════════════════════════════════════════════════════
export const BLOOD_ORANGE_16: SpriteTemplate = {
  name: 'blood_orange_16',
  width: 16,
  height: 16,
  description: 'Orange half showing deep red interior with segment lines.',
  regions: [
    { name: 'rind', role: 'arm', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [11,4], [12,4],
      [2,5], [3,5], [12,5], [13,5],
      [2,6], [3,6], [12,6], [13,6],
      [2,7], [3,7], [12,7], [13,7],
      [2,8], [3,8], [12,8], [13,8],
      [2,9], [3,9], [12,9], [13,9],
      [3,10], [4,10], [11,10], [12,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'red_flesh', role: 'body', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [7,5], [8,5], [10,5], [11,5],
      [4,6], [5,6], [7,6], [8,6], [10,6], [11,6],
      [4,7], [5,7], [7,7], [8,7], [10,7], [11,7],
      [4,8], [5,8], [7,8], [8,8], [10,8], [11,8],
      [4,9], [5,9], [7,9], [8,9], [10,9], [11,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
    ]},
    { name: 'segment_wall', role: 'head', pixels: [
      [6,5], [9,5],
      [6,6], [9,6],
      [6,8], [9,8],
      [6,9], [9,9],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [6,7], [9,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TANGERINE_FARM — Small orange tangerine with green leaf at stem.
// ════════════════════════════════════════════════════════════
export const TANGERINE_FARM_16: SpriteTemplate = {
  name: 'tangerine_farm_16',
  width: 16,
  height: 16,
  description: 'Small orange tangerine with green leaf at stem.',
  regions: [
    { name: 'leaf', role: 'accessory', pixels: [
      [7,2], [8,2],
      [7,3], [8,3],
    ]},
    { name: 'stem', role: 'arm', pixels: [
      [6,3], [9,3],
      [7,4], [8,4],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [6,5], [7,5], [8,5], [9,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
      [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CANTALOUPE_SLICE — Cantaloupe wedge with green rind and orange flesh.
// ════════════════════════════════════════════════════════════
export const CANTALOUPE_SLICE_16: SpriteTemplate = {
  name: 'cantaloupe_slice_16',
  width: 16,
  height: 16,
  description: 'Cantaloupe wedge with green rind and orange flesh.',
  regions: [
    { name: 'orange_flesh', role: 'body', pixels: [
      [7,3], [8,3],
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [1,9], [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,6],
    ]},
    { name: 'pale_rind', role: 'head', pixels: [
      [1,10], [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10], [14,10],
      [1,11], [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11], [14,11],
    ]},
    { name: 'green_rind', role: 'accessory', pixels: [
      [1,12], [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12], [14,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13], [13,13], [14,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HONEYDEW_SLICE — Wide crescent honeydew slice with pale green flesh and rind.
// ════════════════════════════════════════════════════════════
export const HONEYDEW_SLICE_16: SpriteTemplate = {
  name: 'honeydew_slice_16',
  width: 16,
  height: 16,
  description: 'Wide crescent honeydew slice with pale green flesh and rind.',
  regions: [
    { name: 'pale_flesh', role: 'body', pixels: [
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [0,6], [1,6], [2,6], [3,6], [4,6], [5,6], [6,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6], [14,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7], [14,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,6],
    ]},
    { name: 'white_rind', role: 'head', pixels: [
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'green_rind', role: 'accessory', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GOOSEBERRY_FARM — Small green gooseberry with papery husk leaves.
// ════════════════════════════════════════════════════════════
export const GOOSEBERRY_FARM_16: SpriteTemplate = {
  name: 'gooseberry_farm_16',
  width: 16,
  height: 16,
  description: 'Small green gooseberry with papery husk leaves.',
  regions: [
    { name: 'papery_husk', role: 'accessory', pixels: [
      [4,2], [5,2], [10,2], [11,2],
      [5,3], [6,3], [9,3], [10,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'berry_skin', role: 'body', pixels: [
      [6,5], [7,5], [8,5], [9,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,7],
    ]},
    { name: 'stripe', role: 'head', pixels: [
      [7,9],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,12], [7,12], [8,12], [9,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CRANBERRY_BUNCH — Cluster of small red cranberries with tiny stems.
// ════════════════════════════════════════════════════════════
export const CRANBERRY_BUNCH_16: SpriteTemplate = {
  name: 'cranberry_bunch_16',
  width: 16,
  height: 16,
  description: 'Cluster of small red cranberries with tiny stems.',
  regions: [
    { name: 'stems', role: 'arm', pixels: [
      [6,1], [7,1], [9,1], [10,1],
      [5,2], [6,2], [8,2], [9,2], [11,2],
      [4,3], [5,3], [6,3], [7,3], [9,3], [10,3], [11,3],
    ]},
    { name: 'berry', role: 'body', pixels: [
      [4,4], [5,4], [6,4], [7,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [7,5], [8,5], [9,5], [10,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [3,11], [4,11], [5,11], [6,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [6,5], [11,5],
      [3,8], [11,8],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,13], [6,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DATE_FRUIT — Brown dried date fruit, oblong and wrinkled.
// ════════════════════════════════════════════════════════════
export const DATE_FRUIT_16: SpriteTemplate = {
  name: 'date_fruit_16',
  width: 16,
  height: 16,
  description: 'Brown dried date fruit, oblong and wrinkled.',
  regions: [
    { name: 'stem_nub', role: 'arm', pixels: [
      [7,3], [8,3],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [5,6], [6,6], [7,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [6,8], [7,8], [8,8], [9,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [7,10], [8,10], [9,10], [11,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,6],
    ]},
    { name: 'wrinkle', role: 'head', pixels: [
      [5,8], [10,8],
      [6,10], [10,10],
    ]},
    { name: 'base_tip', role: 'boot', pixels: [
      [7,13], [8,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TAMARIND_FARM — Brown tamarind pod, curved bean-like shape.
// ════════════════════════════════════════════════════════════
export const TAMARIND_FARM_16: SpriteTemplate = {
  name: 'tamarind_farm_16',
  width: 16,
  height: 16,
  description: 'Brown tamarind pod, curved bean-like shape.',
  regions: [
    { name: 'stem_end', role: 'arm', pixels: [
      [4,3], [5,3],
      [3,4], [4,4],
      [2,5], [3,5],
    ]},
    { name: 'pod_shell', role: 'body', pixels: [
      [5,4], [6,4], [7,4],
      [4,5], [5,5], [6,5], [7,5], [8,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [2,7], [3,7], [4,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9], [14,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10], [14,10],
      [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [5,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [7,12], [8,12], [9,12], [10,12], [11,12],
      [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CACTUS_FRUIT_FARM — Pink/magenta prickly pear cactus fruit with tiny spines.
// ════════════════════════════════════════════════════════════
export const CACTUS_FRUIT_FARM_16: SpriteTemplate = {
  name: 'cactus_fruit_farm_16',
  width: 16,
  height: 16,
  description: 'Pink/magenta prickly pear cactus fruit with tiny spines.',
  regions: [
    { name: 'tiny_spines', role: 'accessory', pixels: [
      [7,2], [8,2],
      [5,4], [10,4],
      [12,5],
      [3,6],
      [13,7],
      [2,8],
      [12,9],
      [3,10],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [5,12], [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,6],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,13], [7,13], [8,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PLANTAIN_FARM — Green plantain, banana-like shape but greener and straighter.
// ════════════════════════════════════════════════════════════
export const PLANTAIN_FARM_16: SpriteTemplate = {
  name: 'plantain_farm_16',
  width: 16,
  height: 16,
  description: 'Green plantain, banana-like shape but greener and straighter.',
  regions: [
    { name: 'stem', role: 'arm', pixels: [
      [12,1], [13,1],
      [10,2], [11,2], [12,2],
    ]},
    { name: 'skin', role: 'body', pixels: [
      [9,3], [10,3], [11,3],
      [8,4], [9,4], [10,4], [11,4],
      [7,5], [8,5], [9,5], [10,5], [11,5],
      [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [5,7], [6,7], [7,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11],
      [4,12], [5,12], [6,12], [7,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [8,7],
    ]},
    { name: 'tip_shadow', role: 'boot', pixels: [
      [2,12], [3,12],
      [3,13], [4,13], [5,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DURIAN_FARM — Spiky yellow-green durian fruit, large and intimidating.
// ════════════════════════════════════════════════════════════
export const DURIAN_FARM_16: SpriteTemplate = {
  name: 'durian_farm_16',
  width: 16,
  height: 16,
  description: 'Spiky yellow-green durian fruit, large and intimidating.',
  regions: [
    { name: 'spiky_shell', role: 'accessory', pixels: [
      [7,0], [8,0],
      [6,1], [7,1], [8,1], [9,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [3,3], [4,3], [11,3], [12,3],
      [2,4], [3,4], [12,4], [13,4],
      [2,5], [12,5],
      [1,6], [2,6], [13,6], [14,6],
      [1,7], [13,7],
      [1,8], [2,8], [13,8], [14,8],
      [2,9], [12,9],
      [2,10], [3,10], [12,10], [13,10],
      [3,11], [4,11], [11,11], [12,11],
      [4,12], [5,12], [10,12], [11,12],
      [5,13], [6,13], [9,13], [10,13],
      [6,14], [7,14], [8,14], [9,14],
    ]},
    { name: 'inner_skin', role: 'body', pixels: [
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'shine', role: 'eye', pixels: [
      [7,5],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [7,13], [8,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const DRAGON_FRUIT_FARM_COLORS: ColorScheme = {
  name: 'dragon_fruit_farm_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
    arm:       { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
    accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
  },
};

export const STARFRUIT_FARM_COLORS: ColorScheme = {
  name: 'starfruit_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const PAPAYA_HALF_COLORS: ColorScheme = {
  name: 'papaya_half_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const LYCHEE_FARM_COLORS: ColorScheme = {
  name: 'lychee_farm_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const GUAVA_FARM_COLORS: ColorScheme = {
  name: 'guava_farm_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const PERSIMMON_FARM_COLORS: ColorScheme = {
  name: 'persimmon_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const RAMBUTAN_FARM_COLORS: ColorScheme = {
  name: 'rambutan_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const JACKFRUIT_CHUNK_COLORS: ColorScheme = {
  name: 'jackfruit_chunk_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const KUMQUAT_FARM_COLORS: ColorScheme = {
  name: 'kumquat_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const BLOOD_ORANGE_COLORS: ColorScheme = {
  name: 'blood_orange_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const TANGERINE_FARM_COLORS: ColorScheme = {
  name: 'tangerine_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const CANTALOUPE_SLICE_COLORS: ColorScheme = {
  name: 'cantaloupe_slice_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const HONEYDEW_SLICE_COLORS: ColorScheme = {
  name: 'honeydew_slice_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#6daa2c', base: '#6dc2ca', highlight: '#deeed6' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const GOOSEBERRY_FARM_COLORS: ColorScheme = {
  name: 'gooseberry_farm_default',
  mapping: {
    head:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
    accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const CRANBERRY_BUNCH_COLORS: ColorScheme = {
  name: 'cranberry_bunch_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const DATE_FRUIT_COLORS: ColorScheme = {
  name: 'date_fruit_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const TAMARIND_FARM_COLORS: ColorScheme = {
  name: 'tamarind_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const CACTUS_FRUIT_FARM_COLORS: ColorScheme = {
  name: 'cactus_fruit_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
    accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const PLANTAIN_FARM_COLORS: ColorScheme = {
  name: 'plantain_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#346524', base: '#854c30', highlight: '#854c30' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const DURIAN_FARM_COLORS: ColorScheme = {
  name: 'durian_farm_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const FRUITS_BATCH2_TEMPLATES: Record<string, SpriteTemplate> = {
  dragon_fruit_farm_16: DRAGON_FRUIT_FARM_16,
  starfruit_farm_16: STARFRUIT_FARM_16,
  papaya_half_16: PAPAYA_HALF_16,
  lychee_farm_16: LYCHEE_FARM_16,
  guava_farm_16: GUAVA_FARM_16,
  persimmon_farm_16: PERSIMMON_FARM_16,
  rambutan_farm_16: RAMBUTAN_FARM_16,
  jackfruit_chunk_16: JACKFRUIT_CHUNK_16,
  kumquat_farm_16: KUMQUAT_FARM_16,
  blood_orange_16: BLOOD_ORANGE_16,
  tangerine_farm_16: TANGERINE_FARM_16,
  cantaloupe_slice_16: CANTALOUPE_SLICE_16,
  honeydew_slice_16: HONEYDEW_SLICE_16,
  gooseberry_farm_16: GOOSEBERRY_FARM_16,
  cranberry_bunch_16: CRANBERRY_BUNCH_16,
  date_fruit_16: DATE_FRUIT_16,
  tamarind_farm_16: TAMARIND_FARM_16,
  cactus_fruit_farm_16: CACTUS_FRUIT_FARM_16,
  plantain_farm_16: PLANTAIN_FARM_16,
  durian_farm_16: DURIAN_FARM_16,
};

export const FRUITS_BATCH2_COLOR_SCHEMES: Record<string, ColorScheme> = {
  dragon_fruit_farm_default: DRAGON_FRUIT_FARM_COLORS,
  starfruit_farm_default: STARFRUIT_FARM_COLORS,
  papaya_half_default: PAPAYA_HALF_COLORS,
  lychee_farm_default: LYCHEE_FARM_COLORS,
  guava_farm_default: GUAVA_FARM_COLORS,
  persimmon_farm_default: PERSIMMON_FARM_COLORS,
  rambutan_farm_default: RAMBUTAN_FARM_COLORS,
  jackfruit_chunk_default: JACKFRUIT_CHUNK_COLORS,
  kumquat_farm_default: KUMQUAT_FARM_COLORS,
  blood_orange_default: BLOOD_ORANGE_COLORS,
  tangerine_farm_default: TANGERINE_FARM_COLORS,
  cantaloupe_slice_default: CANTALOUPE_SLICE_COLORS,
  honeydew_slice_default: HONEYDEW_SLICE_COLORS,
  gooseberry_farm_default: GOOSEBERRY_FARM_COLORS,
  cranberry_bunch_default: CRANBERRY_BUNCH_COLORS,
  date_fruit_default: DATE_FRUIT_COLORS,
  tamarind_farm_default: TAMARIND_FARM_COLORS,
  cactus_fruit_farm_default: CACTUS_FRUIT_FARM_COLORS,
  plantain_farm_default: PLANTAIN_FARM_COLORS,
  durian_farm_default: DURIAN_FARM_COLORS,
};
