/**
 * 16x16 items templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-07.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// ASSAULT_RIFLE_GN — Modern assault rifle with picatinny rail, polymer furniture, and detachable magazine.
// ════════════════════════════════════════════════════════════
export const ASSAULT_RIFLE_GN_16: SpriteTemplate = {
  name: 'assault_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Modern assault rifle with picatinny rail, polymer furniture, and detachable magazine.',
  regions: [
    { name: 'receiver_barrel', role: 'body', pixels: [
      [10,2], [11,2], [12,2], [13,2], [14,2],
      [8,3], [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [7,4], [8,4], [9,4], [10,4], [11,4],
      [6,5], [7,5], [8,5], [9,5], [10,5],
      [5,6], [6,6], [7,6], [8,6], [9,6],
      [4,7], [5,7], [6,7], [7,7], [8,7],
      [3,8], [4,8], [5,8],
      [4,9], [5,9],
      [5,10], [6,10],
    ]},
    { name: 'rail_system', role: 'head', pixels: [
      [10,1], [11,1], [12,1],
      [9,2],
    ]},
    { name: 'polymer_stock', role: 'leg', pixels: [
      [1,11], [2,11],
      [1,12], [2,12], [3,12], [4,12],
      [0,13], [1,13], [2,13], [3,13], [4,13],
      [0,14], [1,14], [2,14], [3,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [2,9], [3,9],
      [2,10], [3,10], [4,10],
      [3,11], [4,11], [5,11],
    ]},
    { name: 'magazine', role: 'arm', pixels: [
      [6,8], [7,8], [8,8],
      [6,9], [7,9],
    ]},
    { name: 'accessories', role: 'accessory', pixels: [
      [15,2],
      [12,4],
      [10,6],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// AK47_RIFLE_GN — Iconic AK-47 with curved banana magazine, wooden stock and handguard.
// ════════════════════════════════════════════════════════════
export const AK47_RIFLE_GN_16: SpriteTemplate = {
  name: 'ak47_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Iconic AK-47 with curved banana magazine, wooden stock and handguard.',
  regions: [
    { name: 'metal_receiver', role: 'body', pixels: [
      [11,1], [12,1], [13,1],
      [10,2], [11,2], [12,2], [13,2], [14,2],
      [9,3], [13,3], [14,3],
      [8,4], [12,4], [13,4],
      [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [7,7], [8,7],
      [4,8], [5,8], [6,8],
      [5,9],
      [6,10], [7,10],
    ]},
    { name: 'wood_handguard', role: 'arm', pixels: [
      [10,3], [11,3], [12,3],
      [9,4], [10,4], [11,4],
    ]},
    { name: 'wood_stock', role: 'leg', pixels: [
      [2,11], [3,11], [4,11],
      [2,12], [3,12], [4,12], [5,12],
      [1,13], [2,13], [3,13], [4,13], [5,13],
      [1,14], [2,14], [3,14], [4,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [3,9], [4,9],
      [3,10], [4,10], [5,10],
      [5,11], [6,11],
    ]},
    { name: 'curved_magazine', role: 'head', pixels: [
      [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9],
    ]},
    { name: 'front_sight', role: 'accessory', pixels: [
      [14,1],
      [9,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SNIPER_RIFLE_GN — Long-barrel bolt-action sniper rifle with magnified scope and bipod legs.
// ════════════════════════════════════════════════════════════
export const SNIPER_RIFLE_GN_16: SpriteTemplate = {
  name: 'sniper_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Long-barrel bolt-action sniper rifle with magnified scope and bipod legs.',
  regions: [
    { name: 'rifle_body', role: 'body', pixels: [
      [13,1], [14,1], [15,1],
      [12,2], [13,2], [14,2],
      [11,3], [12,3], [13,3], [14,3],
      [9,4], [10,4], [11,4], [12,4], [13,4],
      [7,5], [8,5], [9,5], [10,5], [11,5],
      [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [7,7], [8,7],
      [4,8], [5,8], [6,8],
      [5,9], [6,9],
      [5,10], [6,10],
    ]},
    { name: 'scope', role: 'head', pixels: [
      [10,2], [11,2],
      [9,3], [10,3],
      [8,4],
    ]},
    { name: 'tactical_stock', role: 'leg', pixels: [
      [1,11], [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12],
      [0,13], [1,13], [2,13], [3,13], [4,13],
      [0,14], [1,14], [2,14], [3,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [3,9], [4,9],
      [2,10], [3,10], [4,10],
      [4,11], [5,11],
    ]},
    { name: 'magazine', role: 'arm', pixels: [
      [7,8], [8,8], [9,8],
      [7,9], [8,9],
    ]},
    { name: 'bipod', role: 'accessory', pixels: [
      [11,6],
      [9,7], [11,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HUNTING_RIFLE_GN — Classic wooden stock hunting rifle with blued barrel, iron sights, and trigger guard.
// ════════════════════════════════════════════════════════════
export const HUNTING_RIFLE_GN_16: SpriteTemplate = {
  name: 'hunting_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Classic wooden stock hunting rifle with blued barrel, iron sights, and trigger guard.',
  regions: [
    { name: 'blued_barrel', role: 'body', pixels: [
      [14,1], [15,1],
      [12,2], [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [9,5], [10,5], [11,5], [12,5], [13,5],
      [8,6], [11,6], [12,6],
      [7,7], [10,7], [11,7],
    ]},
    { name: 'walnut_stock', role: 'leg', pixels: [
      [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13],
      [1,14], [2,14], [3,14], [4,14],
    ]},
    { name: 'barrel_band', role: 'arm', pixels: [
      [9,6], [10,6],
      [8,7], [9,7],
    ]},
    { name: 'trigger_guard', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
    { name: 'iron_sight', role: 'accessory', pixels: [
      [13,1],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MUSKET_GN — Historical flintlock musket with fixed bayonet, brass fittings, and wooden stock.
// ════════════════════════════════════════════════════════════
export const MUSKET_GN_16: SpriteTemplate = {
  name: 'musket_gn_16',
  width: 16,
  height: 16,
  description: 'Historical flintlock musket with fixed bayonet, brass fittings, and wooden stock.',
  regions: [
    { name: 'barrel_body', role: 'body', pixels: [
      [14,1], [15,1],
      [12,2], [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [10,5], [11,5],
      [9,6], [10,6],
      [7,7], [8,7], [9,7],
      [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9],
    ]},
    { name: 'wooden_stock', role: 'leg', pixels: [
      [6,10], [7,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13],
      [1,14], [2,14], [3,14], [4,14], [5,14],
      [1,15], [2,15], [3,15], [4,15],
    ]},
    { name: 'bayonet_blade', role: 'accessory', pixels: [
      [14,0], [15,0],
      [13,1],
    ]},
    { name: 'brass_fittings', role: 'belt', pixels: [
      [9,5], [12,5],
      [8,6], [11,6],
      [10,7],
    ]},
    { name: 'flintlock', role: 'arm', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// LEVER_ACTION_GN — Winchester-style lever-action rifle with octagonal barrel and brass receiver.
// ════════════════════════════════════════════════════════════
export const LEVER_ACTION_GN_16: SpriteTemplate = {
  name: 'lever_action_gn_16',
  width: 16,
  height: 16,
  description: 'Winchester-style lever-action rifle with octagonal barrel and brass receiver.',
  regions: [
    { name: 'octagonal_barrel', role: 'body', pixels: [
      [13,1], [14,1], [15,1],
      [12,2], [13,2], [14,2], [15,2],
      [12,3], [13,3], [14,3],
      [13,4], [14,4],
      [12,5], [13,5],
    ]},
    { name: 'brass_receiver', role: 'head', pixels: [
      [11,3],
      [10,4], [11,4], [12,4],
      [9,5], [10,5], [11,5],
      [8,6], [9,6], [10,6], [11,6],
      [7,7], [8,7], [9,7],
    ]},
    { name: 'walnut_stock', role: 'leg', pixels: [
      [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13],
      [1,14], [2,14], [3,14], [4,14],
    ]},
    { name: 'lever_action', role: 'arm', pixels: [
      [12,6],
      [10,7], [11,7],
      [10,8],
    ]},
    { name: 'trigger_guard', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BOLT_ACTION_GN — WW2-era bolt-action rifle with turned-down bolt handle and full wood stock.
// ════════════════════════════════════════════════════════════
export const BOLT_ACTION_GN_16: SpriteTemplate = {
  name: 'bolt_action_gn_16',
  width: 16,
  height: 16,
  description: 'WW2-era bolt-action rifle with turned-down bolt handle and full wood stock.',
  regions: [
    { name: 'blued_receiver', role: 'body', pixels: [
      [13,1], [14,1], [15,1],
      [12,2], [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [13,4], [14,4],
      [9,5], [10,5], [11,5], [13,5],
      [8,6], [9,6], [10,6], [11,6], [12,6],
      [7,7], [8,7], [9,7], [10,7], [11,7],
    ]},
    { name: 'beech_stock', role: 'leg', pixels: [
      [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13],
      [1,14], [2,14], [3,14], [4,14], [5,14],
      [1,15], [2,15], [3,15], [4,15],
    ]},
    { name: 'bolt_handle', role: 'arm', pixels: [
      [12,4],
      [12,5],
    ]},
    { name: 'trigger_guard', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BATTLE_RIFLE_GN — Heavy battle rifle with bipod, large magazine, and picatinny rail.
// ════════════════════════════════════════════════════════════
export const BATTLE_RIFLE_GN_16: SpriteTemplate = {
  name: 'battle_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Heavy battle rifle with bipod, large magazine, and picatinny rail.',
  regions: [
    { name: 'rifle_receiver', role: 'body', pixels: [
      [9,2], [10,2], [11,2], [12,2], [13,2], [14,2],
      [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [3,7], [4,7], [5,7], [6,7], [7,7],
      [4,8], [5,8],
      [5,9], [6,9],
    ]},
    { name: 'rail_optic', role: 'head', pixels: [
      [9,1], [10,1], [11,1],
      [8,2],
    ]},
    { name: 'heavy_stock', role: 'leg', pixels: [
      [1,10], [2,10], [3,10],
      [1,11], [2,11], [3,11], [4,11], [5,11],
      [0,12], [1,12], [2,12], [3,12], [4,12], [5,12],
      [0,13], [1,13], [2,13], [3,13], [4,13],
      [0,14], [1,14], [2,14], [3,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [2,8], [3,8],
      [2,9], [3,9], [4,9],
      [4,10], [5,10],
    ]},
    { name: 'large_magazine', role: 'arm', pixels: [
      [8,7], [9,7],
      [6,8], [7,8], [8,8],
    ]},
    { name: 'bipod_legs', role: 'accessory', pixels: [
      [12,4], [14,4],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CARBINE_SHORT_GN — Compact tactical carbine with folding stock, short barrel, and red dot sight.
// ════════════════════════════════════════════════════════════
export const CARBINE_SHORT_GN_16: SpriteTemplate = {
  name: 'carbine_short_gn_16',
  width: 16,
  height: 16,
  description: 'Compact tactical carbine with folding stock, short barrel, and red dot sight.',
  regions: [
    { name: 'short_receiver', role: 'body', pixels: [
      [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [5,6], [6,6], [7,6], [8,6], [9,6],
      [4,7], [5,7], [6,7], [7,7], [8,7],
      [3,8], [4,8], [5,8],
      [4,9], [5,9],
      [5,10], [6,10],
    ]},
    { name: 'red_dot_sight', role: 'head', pixels: [
      [9,2], [10,2],
      [8,3],
    ]},
    { name: 'folding_stock', role: 'leg', pixels: [
      [1,11], [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12],
      [0,13], [1,13], [2,13], [3,13],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [2,9], [3,9],
      [2,10], [3,10], [4,10],
      [4,11], [5,11],
    ]},
    { name: 'magazine', role: 'arm', pixels: [
      [6,8], [7,8], [8,8],
      [6,9], [7,9],
    ]},
    { name: 'flashlight', role: 'accessory', pixels: [
      [9,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DMR_RIFLE_GN — Designated marksman rifle with variable scope, long barrel, and ergonomic stock.
// ════════════════════════════════════════════════════════════
export const DMR_RIFLE_GN_16: SpriteTemplate = {
  name: 'dmr_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Designated marksman rifle with variable scope, long barrel, and ergonomic stock.',
  regions: [
    { name: 'match_barrel', role: 'body', pixels: [
      [14,1],
      [12,2], [13,2], [14,2],
      [11,3], [12,3], [13,3], [14,3],
      [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [7,5], [8,5], [9,5], [10,5], [11,5],
      [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8],
      [5,9], [6,9],
      [5,10], [6,10],
    ]},
    { name: 'variable_scope', role: 'head', pixels: [
      [11,1], [12,1], [13,1],
      [10,2], [11,2],
      [9,3], [10,3],
    ]},
    { name: 'ergo_stock', role: 'leg', pixels: [
      [1,11], [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12], [5,12],
      [0,13], [1,13], [2,13], [3,13], [4,13], [5,13],
      [0,14], [1,14], [2,14], [3,14], [4,14],
    ]},
    { name: 'angled_grip', role: 'belt', pixels: [
      [3,9], [4,9],
      [2,10], [3,10], [4,10],
      [4,11], [5,11],
    ]},
    { name: 'long_magazine', role: 'arm', pixels: [
      [7,8], [8,8], [9,8],
      [7,9], [8,9],
    ]},
    { name: 'muzzle_brake', role: 'accessory', pixels: [
      [12,5],
      [12,6],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BULLPUP_RIFLE_GN — Bullpup assault rifle with magazine behind trigger, integrated carry handle.
// ════════════════════════════════════════════════════════════
export const BULLPUP_RIFLE_GN_16: SpriteTemplate = {
  name: 'bullpup_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Bullpup assault rifle with magazine behind trigger, integrated carry handle.',
  regions: [
    { name: 'polymer_body', role: 'body', pixels: [
      [10,2], [11,2], [12,2], [13,2], [14,2],
      [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [7,7], [8,7], [9,7],
      [3,8], [4,8], [5,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9], [9,9],
      [5,10], [6,10],
    ]},
    { name: 'carry_handle', role: 'head', pixels: [
      [9,2],
      [8,3],
    ]},
    { name: 'buttpad', role: 'leg', pixels: [
      [4,11], [5,11], [6,11], [7,11],
      [3,12], [4,12], [5,12], [6,12],
      [2,13], [3,13], [4,13], [5,13],
    ]},
    { name: 'trigger_grip', role: 'belt', pixels: [
      [6,7],
      [6,8],
    ]},
    { name: 'rear_magazine', role: 'arm', pixels: [
      [2,9], [3,9], [4,9],
      [2,10], [3,10], [4,10],
      [1,11], [2,11], [3,11],
      [1,12], [2,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ANTI_MATERIAL_GN — Massive anti-material rifle with oversized barrel, muzzle brake, and bipod.
// ════════════════════════════════════════════════════════════
export const ANTI_MATERIAL_GN_16: SpriteTemplate = {
  name: 'anti_material_gn_16',
  width: 16,
  height: 16,
  description: 'Massive anti-material rifle with oversized barrel, muzzle brake, and bipod.',
  regions: [
    { name: 'heavy_receiver', role: 'body', pixels: [
      [14,1], [15,1],
      [12,2], [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [9,6], [10,6], [11,6], [12,6],
      [8,7], [9,7], [10,7],
      [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9],
      [6,10], [7,10],
    ]},
    { name: 'scope_rail', role: 'head', pixels: [
      [8,6],
      [7,7],
    ]},
    { name: 'padded_stock', role: 'leg', pixels: [
      [3,11], [4,11], [5,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13],
      [1,14], [2,14], [3,14], [4,14], [5,14],
      [0,15], [1,15], [2,15], [3,15], [4,15],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
      [6,11], [7,11],
    ]},
    { name: 'box_magazine', role: 'arm', pixels: [
      [8,9], [9,9], [10,9],
      [8,10], [9,10],
    ]},
    { name: 'muzzle_bipod', role: 'accessory', pixels: [
      [14,0], [15,0],
      [13,1],
      [11,7], [13,7],
      [11,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SCIFI_RIFLE_GN — Futuristic energy rifle with glowing power cell, holographic sight, and plasma barrel.
// ════════════════════════════════════════════════════════════
export const SCIFI_RIFLE_GN_16: SpriteTemplate = {
  name: 'scifi_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Futuristic energy rifle with glowing power cell, holographic sight, and plasma barrel.',
  regions: [
    { name: 'composite_body', role: 'body', pixels: [
      [10,2], [11,2], [12,2], [13,2], [14,2],
      [8,3], [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [9,7],
      [3,8], [4,8],
      [4,9], [5,9],
      [5,10], [6,10],
    ]},
    { name: 'holo_sight', role: 'head', pixels: [
      [10,1], [11,1],
      [9,2],
    ]},
    { name: 'ergo_stock', role: 'leg', pixels: [
      [1,11], [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12], [5,12],
      [0,13], [1,13], [2,13], [3,13], [4,13],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [8,7],
      [2,9], [3,9],
      [2,10], [3,10], [4,10],
      [4,11], [5,11],
    ]},
    { name: 'power_cell', role: 'arm', pixels: [
      [5,8], [6,8],
    ]},
    { name: 'energy_mag', role: 'arm', pixels: [
      [7,8], [8,8],
      [6,9], [7,9],
    ]},
    { name: 'energy_emitter', role: 'accessory', pixels: [
      [13,4], [14,4],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// STEAMPUNK_RIFLE_GN — Victorian steampunk long gun with brass pipes, copper receiver, and steam vents.
// ════════════════════════════════════════════════════════════
export const STEAMPUNK_RIFLE_GN_16: SpriteTemplate = {
  name: 'steampunk_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Victorian steampunk long gun with brass pipes, copper receiver, and steam vents.',
  regions: [
    { name: 'copper_receiver', role: 'body', pixels: [
      [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [10,5], [11,5],
      [11,6], [12,6],
      [10,7],
    ]},
    { name: 'brass_fittings', role: 'head', pixels: [
      [9,5],
      [8,6], [9,6], [10,6],
      [7,7], [8,7], [9,7],
      [6,8], [7,8], [8,8], [9,8], [10,8],
    ]},
    { name: 'mahogany_stock', role: 'leg', pixels: [
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13],
      [1,14], [2,14], [3,14], [4,14], [5,14],
    ]},
    { name: 'trigger_mech', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
    { name: 'brass_pipes', role: 'arm', pixels: [
      [13,1], [14,1], [15,1],
      [12,2],
    ]},
    { name: 'steam_vents', role: 'accessory', pixels: [
      [12,5], [13,5],
      [11,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BLUNDERBUSS_GN — Wide flared muzzle blunderbuss with brass bell, wooden stock, and flintlock mechanism.
// ════════════════════════════════════════════════════════════
export const BLUNDERBUSS_GN_16: SpriteTemplate = {
  name: 'blunderbuss_gn_16',
  width: 16,
  height: 16,
  description: 'Wide flared muzzle blunderbuss with brass bell, wooden stock, and flintlock mechanism.',
  regions: [
    { name: 'flared_muzzle', role: 'head', pixels: [
      [9,1], [10,1], [11,1], [12,1], [13,1], [14,1],
      [8,2], [9,2], [10,2], [11,2], [12,2], [13,2], [14,2],
      [9,3], [10,3], [11,3], [12,3], [13,3],
    ]},
    { name: 'barrel_body', role: 'body', pixels: [
      [10,4], [11,4], [12,4], [13,4],
      [9,5], [10,5], [11,5], [12,5], [13,5],
      [8,6], [9,6], [10,6], [11,6], [12,6],
      [9,7], [10,7],
      [8,8], [9,8],
      [7,9], [8,9],
    ]},
    { name: 'wooden_stock', role: 'leg', pixels: [
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12], [6,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13],
      [1,14], [2,14], [3,14], [4,14], [5,14],
    ]},
    { name: 'brass_bands', role: 'arm', pixels: [
      [7,7], [8,7], [11,7],
      [6,8], [7,8], [10,8],
      [6,9], [9,9],
    ]},
    { name: 'flintlock', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CROSSBOW_MODERN_GN — Modern tactical crossbow with cam limbs, scope, and bolt rail.
// ════════════════════════════════════════════════════════════
export const CROSSBOW_MODERN_GN_16: SpriteTemplate = {
  name: 'crossbow_modern_gn_16',
  width: 16,
  height: 16,
  description: 'Modern tactical crossbow with cam limbs, scope, and bolt rail.',
  regions: [
    { name: 'rail_body', role: 'body', pixels: [
      [9,4], [10,4],
      [8,5], [9,5], [10,5], [11,5],
      [7,6], [8,6], [9,6], [10,6],
      [6,7], [7,7], [8,7], [9,7],
      [5,8], [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9], [9,9],
      [5,10], [6,10], [7,10],
    ]},
    { name: 'cam_limbs', role: 'head', pixels: [
      [9,0], [10,0], [11,0],
      [8,1], [9,1], [10,1], [11,1],
      [9,2],
      [0,14], [1,14], [2,14], [3,14],
      [1,15], [2,15], [3,15],
    ]},
    { name: 'bolt_string', role: 'arm', pixels: [
      [10,2], [11,2], [12,2],
      [10,3], [11,3], [12,3], [13,3],
      [11,4], [12,4], [13,4],
      [12,5],
    ]},
    { name: 'tactical_stock', role: 'leg', pixels: [
      [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12], [5,12],
      [1,13], [2,13], [3,13], [4,13],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [4,9], [5,9],
      [3,10], [4,10],
      [4,11], [5,11], [6,11],
    ]},
    { name: 'scope_mount', role: 'accessory', pixels: [
      [11,6], [12,6],
      [10,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GAUSS_RIFLE_GN — Electromagnetic accelerator rifle with visible coil rings and power conduit.
// ════════════════════════════════════════════════════════════
export const GAUSS_RIFLE_GN_16: SpriteTemplate = {
  name: 'gauss_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Electromagnetic accelerator rifle with visible coil rings and power conduit.',
  regions: [
    { name: 'rifle_housing', role: 'body', pixels: [
      [12,1], [13,1], [14,1], [15,1],
      [11,2], [12,2], [13,2], [14,2],
      [10,3], [11,3], [13,3], [14,3],
      [9,4], [10,4], [11,4], [13,4],
      [8,5], [9,5], [10,5], [11,5],
      [7,6], [8,6], [9,6], [10,6], [11,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [6,8],
      [5,9],
      [4,10], [5,10], [6,10],
    ]},
    { name: 'em_coils', role: 'head', pixels: [
      [11,1],
      [10,2],
      [9,3], [12,3],
      [8,4], [12,4],
      [7,5],
      [6,6],
    ]},
    { name: 'tech_stock', role: 'leg', pixels: [
      [1,11], [2,11], [3,11],
      [1,12], [2,12], [3,12], [4,12], [5,12],
      [0,13], [1,13], [2,13], [3,13], [4,13],
      [0,14], [1,14], [2,14], [3,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [3,9], [4,9],
      [2,10], [3,10],
      [4,11], [5,11],
    ]},
    { name: 'power_conduit', role: 'arm', pixels: [
      [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ICE_RIFLE_GN — Fantasy ice-themed rifle with crystal barrel, frozen stock, and frost accents.
// ════════════════════════════════════════════════════════════
export const ICE_RIFLE_GN_16: SpriteTemplate = {
  name: 'ice_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Fantasy ice-themed rifle with crystal barrel, frozen stock, and frost accents.',
  regions: [
    { name: 'ice_metal_body', role: 'body', pixels: [
      [14,1], [15,1],
      [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [9,5], [10,5], [11,5],
      [8,6], [9,6], [10,6],
      [7,7], [8,7], [9,7], [10,7], [11,7],
    ]},
    { name: 'ice_crystals', role: 'head', pixels: [
      [14,0], [15,0],
      [13,1],
      [12,2],
      [6,12],
      [4,13], [5,13],
      [3,14], [4,14],
      [2,15], [3,15],
    ]},
    { name: 'frozen_stock', role: 'leg', pixels: [
      [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12],
      [1,13], [2,13], [3,13],
      [1,14], [2,14],
    ]},
    { name: 'frost_grip', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
    { name: 'frost_accents', role: 'accessory', pixels: [
      [12,5], [13,5],
      [11,6],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// FIRE_RIFLE_GN — Fantasy fire-themed rifle with flame barrel, ember stock, and molten accents.
// ════════════════════════════════════════════════════════════
export const FIRE_RIFLE_GN_16: SpriteTemplate = {
  name: 'fire_rifle_gn_16',
  width: 16,
  height: 16,
  description: 'Fantasy fire-themed rifle with flame barrel, ember stock, and molten accents.',
  regions: [
    { name: 'heated_metal', role: 'body', pixels: [
      [14,1], [15,1],
      [13,2], [14,2], [15,2],
      [11,3], [12,3], [13,3], [14,3], [15,3],
      [10,4], [11,4], [12,4], [13,4], [14,4],
      [9,5], [10,5], [11,5],
      [8,6], [9,6], [10,6],
      [7,7], [8,7], [9,7], [10,7], [11,7],
    ]},
    { name: 'flame_elements', role: 'head', pixels: [
      [14,0], [15,0],
      [13,1],
      [12,2],
      [6,12],
      [4,13], [5,13],
      [3,14], [4,14],
      [2,15], [3,15],
    ]},
    { name: 'charred_stock', role: 'leg', pixels: [
      [6,8], [7,8], [8,8], [9,8], [10,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10],
      [3,11], [4,11], [5,11], [6,11], [7,11],
      [2,12], [3,12], [4,12], [5,12],
      [1,13], [2,13], [3,13],
      [1,14], [2,14],
    ]},
    { name: 'ember_grip', role: 'belt', pixels: [
      [5,9],
      [4,10], [5,10],
    ]},
    { name: 'molten_accents', role: 'accessory', pixels: [
      [12,5], [13,5],
      [11,6],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// RAILGUN_GN — Heavy electromagnetic railgun with parallel rails, power pack, and capacitor banks.
// ════════════════════════════════════════════════════════════
export const RAILGUN_GN_16: SpriteTemplate = {
  name: 'railgun_gn_16',
  width: 16,
  height: 16,
  description: 'Heavy electromagnetic railgun with parallel rails, power pack, and capacitor banks.',
  regions: [
    { name: 'main_housing', role: 'body', pixels: [
      [14,1],
      [13,2], [14,2],
      [12,3], [13,3], [14,3],
      [10,4], [11,4], [12,4], [13,4],
      [8,5], [9,5], [10,5], [11,5], [12,5],
      [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [7,8], [8,8], [9,8], [10,8],
      [8,9], [9,9],
      [8,10],
    ]},
    { name: 'conductive_rails', role: 'head', pixels: [
      [12,1], [13,1], [15,1],
      [11,2], [12,2], [15,2],
      [10,3], [11,3],
      [9,4],
      [13,5],
    ]},
    { name: 'heavy_stock', role: 'leg', pixels: [
      [2,11], [3,11], [4,11], [5,11],
      [1,12], [2,12], [3,12], [4,12], [5,12],
      [0,13], [1,13], [2,13], [3,13], [4,13], [5,13],
      [0,14], [1,14], [2,14], [3,14], [4,14],
    ]},
    { name: 'pistol_grip', role: 'belt', pixels: [
      [6,9], [7,9],
      [6,10], [7,10],
      [6,11],
    ]},
    { name: 'power_pack', role: 'arm', pixels: [
      [5,8], [6,8],
      [4,9], [5,9],
      [3,10], [4,10], [5,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const ASSAULT_RIFLE_GN_COLORS: ColorScheme = {
  name: 'assault_rifle_gn_default',
  mapping: {
    head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const AK47_RIFLE_GN_COLORS: ColorScheme = {
  name: 'ak47_rifle_gn_default',
  mapping: {
    head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
  },
};

export const SNIPER_RIFLE_GN_COLORS: ColorScheme = {
  name: 'sniper_rifle_gn_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
  },
};

export const HUNTING_RIFLE_GN_COLORS: ColorScheme = {
  name: 'hunting_rifle_gn_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
  },
};

export const MUSKET_GN_COLORS: ColorScheme = {
  name: 'musket_gn_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
  },
};

export const LEVER_ACTION_GN_COLORS: ColorScheme = {
  name: 'lever_action_gn_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const BOLT_ACTION_GN_COLORS: ColorScheme = {
  name: 'bolt_action_gn_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const BATTLE_RIFLE_GN_COLORS: ColorScheme = {
  name: 'battle_rifle_gn_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
  },
};

export const CARBINE_SHORT_GN_COLORS: ColorScheme = {
  name: 'carbine_short_gn_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const DMR_RIFLE_GN_COLORS: ColorScheme = {
  name: 'dmr_rifle_gn_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
  },
};

export const BULLPUP_RIFLE_GN_COLORS: ColorScheme = {
  name: 'bullpup_rifle_gn_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ANTI_MATERIAL_GN_COLORS: ColorScheme = {
  name: 'anti_material_gn_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
  },
};

export const SCIFI_RIFLE_GN_COLORS: ColorScheme = {
  name: 'scifi_rifle_gn_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#6dc2ca', highlight: '#dad45e' },
  },
};

export const STEAMPUNK_RIFLE_GN_COLORS: ColorScheme = {
  name: 'steampunk_rifle_gn_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const BLUNDERBUSS_GN_COLORS: ColorScheme = {
  name: 'blunderbuss_gn_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CROSSBOW_MODERN_GN_COLORS: ColorScheme = {
  name: 'crossbow_modern_gn_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
  },
};

export const GAUSS_RIFLE_GN_COLORS: ColorScheme = {
  name: 'gauss_rifle_gn_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#dad45e' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ICE_RIFLE_GN_COLORS: ColorScheme = {
  name: 'ice_rifle_gn_default',
  mapping: {
    head:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    leg:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
  },
};

export const FIRE_RIFLE_GN_COLORS: ColorScheme = {
  name: 'fire_rifle_gn_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const RAILGUN_GN_COLORS: ColorScheme = {
  name: 'railgun_gn_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const GUNS_BATCH2_TEMPLATES: Record<string, SpriteTemplate> = {
  assault_rifle_gn_16: ASSAULT_RIFLE_GN_16,
  ak47_rifle_gn_16: AK47_RIFLE_GN_16,
  sniper_rifle_gn_16: SNIPER_RIFLE_GN_16,
  hunting_rifle_gn_16: HUNTING_RIFLE_GN_16,
  musket_gn_16: MUSKET_GN_16,
  lever_action_gn_16: LEVER_ACTION_GN_16,
  bolt_action_gn_16: BOLT_ACTION_GN_16,
  battle_rifle_gn_16: BATTLE_RIFLE_GN_16,
  carbine_short_gn_16: CARBINE_SHORT_GN_16,
  dmr_rifle_gn_16: DMR_RIFLE_GN_16,
  bullpup_rifle_gn_16: BULLPUP_RIFLE_GN_16,
  anti_material_gn_16: ANTI_MATERIAL_GN_16,
  scifi_rifle_gn_16: SCIFI_RIFLE_GN_16,
  steampunk_rifle_gn_16: STEAMPUNK_RIFLE_GN_16,
  blunderbuss_gn_16: BLUNDERBUSS_GN_16,
  crossbow_modern_gn_16: CROSSBOW_MODERN_GN_16,
  gauss_rifle_gn_16: GAUSS_RIFLE_GN_16,
  ice_rifle_gn_16: ICE_RIFLE_GN_16,
  fire_rifle_gn_16: FIRE_RIFLE_GN_16,
  railgun_gn_16: RAILGUN_GN_16,
};

export const GUNS_BATCH2_COLOR_SCHEMES: Record<string, ColorScheme> = {
  assault_rifle_gn_default: ASSAULT_RIFLE_GN_COLORS,
  ak47_rifle_gn_default: AK47_RIFLE_GN_COLORS,
  sniper_rifle_gn_default: SNIPER_RIFLE_GN_COLORS,
  hunting_rifle_gn_default: HUNTING_RIFLE_GN_COLORS,
  musket_gn_default: MUSKET_GN_COLORS,
  lever_action_gn_default: LEVER_ACTION_GN_COLORS,
  bolt_action_gn_default: BOLT_ACTION_GN_COLORS,
  battle_rifle_gn_default: BATTLE_RIFLE_GN_COLORS,
  carbine_short_gn_default: CARBINE_SHORT_GN_COLORS,
  dmr_rifle_gn_default: DMR_RIFLE_GN_COLORS,
  bullpup_rifle_gn_default: BULLPUP_RIFLE_GN_COLORS,
  anti_material_gn_default: ANTI_MATERIAL_GN_COLORS,
  scifi_rifle_gn_default: SCIFI_RIFLE_GN_COLORS,
  steampunk_rifle_gn_default: STEAMPUNK_RIFLE_GN_COLORS,
  blunderbuss_gn_default: BLUNDERBUSS_GN_COLORS,
  crossbow_modern_gn_default: CROSSBOW_MODERN_GN_COLORS,
  gauss_rifle_gn_default: GAUSS_RIFLE_GN_COLORS,
  ice_rifle_gn_default: ICE_RIFLE_GN_COLORS,
  fire_rifle_gn_default: FIRE_RIFLE_GN_COLORS,
  railgun_gn_default: RAILGUN_GN_COLORS,
};
