/**
 * 16x16 liberal_arts templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-07.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// QUILL_PEN — Feathered quill pen angled for writing with ink-tipped nib.
// ════════════════════════════════════════════════════════════
export const QUILL_PEN_16: SpriteTemplate = {
  name: 'quill_pen_16',
  width: 16,
  height: 16,
  description: 'Feathered quill pen angled for writing with ink-tipped nib.',
  regions: [
    { name: 'feather_vane', role: 'body', pixels: [
      [10,1], [11,1], [12,1], [13,1],
      [9,2], [10,2], [11,2], [12,2], [13,2],
      [8,3], [9,3], [10,3], [11,3], [12,3],
      [7,4], [8,4], [9,4], [10,4],
      [6,5], [7,5],
      [5,6], [6,6],
    ]},
    { name: 'shaft', role: 'head', pixels: [
      [8,5], [9,5],
      [7,6], [8,6],
      [4,7], [5,7], [6,7], [7,7],
      [3,8], [4,8], [5,8], [6,8],
      [2,9], [3,9],
      [1,10], [2,10],
    ]},
    { name: 'nib', role: 'arm', pixels: [
      [4,9], [5,9],
      [3,10], [4,10],
      [1,11], [2,11], [3,11],
    ]},
    { name: 'ink_tip', role: 'eye', pixels: [
      [1,12], [2,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// INKWELL_QUILL — Round ceramic inkwell with quill pen resting inside.
// ════════════════════════════════════════════════════════════
export const INKWELL_QUILL_16: SpriteTemplate = {
  name: 'inkwell_quill_16',
  width: 16,
  height: 16,
  description: 'Round ceramic inkwell with quill pen resting inside.',
  regions: [
    { name: 'quill', role: 'accessory', pixels: [
      [8,1], [9,1],
      [7,2], [8,2],
      [6,3], [7,3],
      [5,4], [6,4],
    ]},
    { name: 'pot_rim', role: 'head', pixels: [
      [7,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [10,6], [11,6],
      [3,7], [4,7], [11,7], [12,7],
      [3,8], [4,8], [11,8], [12,8],
      [3,9], [4,9], [11,9], [12,9],
      [4,10], [5,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'ink_surface', role: 'eye', pixels: [
      [6,6], [7,6], [8,6], [9,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'pot_base', role: 'body', pixels: [
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OPEN_CODEX — Open leather-bound codex with visible text on both pages.
// ════════════════════════════════════════════════════════════
export const OPEN_CODEX_16: SpriteTemplate = {
  name: 'open_codex_16',
  width: 16,
  height: 16,
  description: 'Open leather-bound codex with visible text on both pages.',
  regions: [
    { name: 'cover', role: 'body', pixels: [
      [1,2], [2,2], [11,2], [12,2],
      [1,3], [2,3], [11,3], [12,3],
      [1,4], [2,4], [11,4], [12,4],
      [1,5], [2,5], [11,5], [12,5],
      [1,6], [2,6], [11,6], [12,6],
      [1,7], [2,7], [11,7], [12,7],
      [1,8], [2,8], [11,8], [12,8],
      [1,9], [2,9], [11,9], [12,9],
      [1,10], [2,10], [11,10], [12,10],
      [1,11], [2,11], [11,11], [12,11],
      [1,12], [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'pages', role: 'head', pixels: [
      [3,2], [4,2], [5,2], [6,2], [8,2], [9,2], [10,2],
      [3,3], [4,3], [5,3], [6,3], [8,3], [9,3], [10,3],
      [3,4], [6,4], [8,4], [9,4], [10,4],
      [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5],
      [3,6], [6,6], [8,6], [10,6],
      [3,7], [4,7], [5,7], [6,7], [8,7], [9,7], [10,7],
      [3,8], [6,8], [8,8], [9,8], [10,8],
      [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9],
      [3,10], [4,10], [5,10], [6,10], [8,10], [9,10], [10,10],
      [3,11], [4,11], [5,11], [6,11], [8,11], [9,11], [10,11],
    ]},
    { name: 'spine', role: 'belt', pixels: [
      [7,2],
      [7,3],
      [7,4],
      [7,5],
      [7,6],
      [7,7],
      [7,8],
      [7,9],
      [7,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ROLLED_SCROLL — Tightly rolled parchment scroll tied with a red ribbon.
// ════════════════════════════════════════════════════════════
export const ROLLED_SCROLL_16: SpriteTemplate = {
  name: 'rolled_scroll_16',
  width: 16,
  height: 16,
  description: 'Tightly rolled parchment scroll tied with a red ribbon.',
  regions: [
    { name: 'rollers', role: 'arm', pixels: [
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [7,7], [8,7],
      [7,8], [8,8],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'knobs', role: 'belt', pixels: [
      [2,4], [13,4],
      [2,5], [13,5],
      [2,6], [13,6],
      [2,9], [13,9],
      [2,10], [13,10],
      [2,11], [13,11],
    ]},
    { name: 'parchment', role: 'body', pixels: [
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// UNFURLED_SCROLL — Partially unrolled scroll with visible writing and wax seal.
// ════════════════════════════════════════════════════════════
export const UNFURLED_SCROLL_16: SpriteTemplate = {
  name: 'unfurled_scroll_16',
  width: 16,
  height: 16,
  description: 'Partially unrolled scroll with visible writing and wax seal.',
  regions: [
    { name: 'rollers', role: 'arm', pixels: [
      [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'knobs', role: 'belt', pixels: [
      [2,2], [11,2],
      [2,12], [11,12],
    ]},
    { name: 'parchment', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [3,4], [4,4], [6,4], [7,4], [9,4], [10,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [3,6], [4,6], [7,6], [9,6], [10,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [3,8], [4,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [3,10], [4,10], [5,10], [6,10], [9,10], [10,10],
      [3,11], [4,11], [5,11], [6,11], [9,11], [10,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'wax_seal', role: 'eye', pixels: [
      [7,10], [8,10],
      [7,11], [8,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WAX_TABLET — Hinged wooden wax tablet with etched writing marks.
// ════════════════════════════════════════════════════════════
export const WAX_TABLET_16: SpriteTemplate = {
  name: 'wax_tablet_16',
  width: 16,
  height: 16,
  description: 'Hinged wooden wax tablet with etched writing marks.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [1,1], [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [1,2], [12,2],
      [1,3], [12,3],
      [1,4], [12,4],
      [1,5], [12,5],
      [1,6], [12,6],
      [1,7], [12,7],
      [1,8], [12,8],
      [1,9], [12,9],
      [1,10], [12,10],
      [1,11], [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
      [1,14], [2,14], [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
    { name: 'wax_surface', role: 'head', pixels: [
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [2,4], [3,4], [5,4], [6,4], [7,4], [9,4], [10,4], [11,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [2,6], [3,6], [6,6], [7,6], [9,6], [10,6], [11,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [3,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'hinge', role: 'belt', pixels: [
      [1,12], [2,12], [12,12], [13,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ILLUMINATED_LETTER — Ornate illuminated capital letter on parchment with vine detail.
// ════════════════════════════════════════════════════════════
export const ILLUMINATED_LETTER_16: SpriteTemplate = {
  name: 'illuminated_letter_16',
  width: 16,
  height: 16,
  description: 'Ornate illuminated capital letter on parchment with vine detail.',
  regions: [
    { name: 'parchment', role: 'head', pixels: [
      [1,1], [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [1,2], [12,2],
      [1,3], [12,3],
      [1,4], [12,4],
      [1,5], [12,5],
      [1,6], [12,6],
      [1,7], [12,7],
      [1,8], [12,8],
      [1,9], [12,9],
      [1,10], [12,10],
      [1,11], [12,11],
      [1,12], [12,12],
      [1,13], [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
    ]},
    { name: 'letter_body', role: 'body', pixels: [
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [2,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [2,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [2,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [2,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [2,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [2,11], [3,11], [5,11], [6,11], [7,11], [9,11], [10,11], [11,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'vine_detail', role: 'eye', pixels: [
      [3,3], [4,3],
      [3,4], [5,4],
      [3,5], [4,5], [5,5],
      [3,6], [5,6],
      [3,7], [5,7],
      [11,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// LEATHER_TOME — Thick leather-bound tome with metal clasp and visible page edges.
// ════════════════════════════════════════════════════════════
export const LEATHER_TOME_16: SpriteTemplate = {
  name: 'leather_tome_16',
  width: 16,
  height: 16,
  description: 'Thick leather-bound tome with metal clasp and visible page edges.',
  regions: [
    { name: 'spine', role: 'arm', pixels: [
      [2,1], [3,1],
      [2,2], [3,2],
      [2,3], [3,3],
      [2,4], [3,4],
      [2,5], [3,5],
      [2,6], [3,6],
      [2,7], [3,7],
      [2,8], [3,8],
      [2,9], [3,9],
      [2,10], [3,10],
      [2,11], [3,11],
      [2,12], [3,12],
      [2,13], [3,13],
    ]},
    { name: 'cover', role: 'body', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
      [4,4], [5,4], [6,4], [7,4], [10,4], [11,4], [12,4], [13,4],
      [4,5], [5,5], [6,5], [7,5], [10,5], [11,5], [12,5], [13,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13], [13,13],
    ]},
    { name: 'page_edge', role: 'head', pixels: [
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
    ]},
    { name: 'gold_emboss', role: 'accessory', pixels: [
      [8,4], [9,4],
      [8,5], [9,5],
    ]},
    { name: 'clasp', role: 'belt', pixels: [
      [12,10], [13,10],
      [12,11], [13,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PARCHMENT_SHEET — Single parchment page with writing and one curled corner.
// ════════════════════════════════════════════════════════════
export const PARCHMENT_SHEET_16: SpriteTemplate = {
  name: 'parchment_sheet_16',
  width: 16,
  height: 16,
  description: 'Single parchment page with writing and one curled corner.',
  regions: [
    { name: 'parchment', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [3,4], [4,4], [6,4], [7,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [7,10], [8,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'red_ink', role: 'eye', pixels: [
      [9,10], [10,10],
      [9,11], [10,11],
    ]},
    { name: 'curl_shadow', role: 'arm', pixels: [
      [11,11], [12,11],
      [11,12], [12,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GRAMMAR_PRIMER — Small chalk slate with ABC letters and wooden frame.
// ════════════════════════════════════════════════════════════
export const GRAMMAR_PRIMER_16: SpriteTemplate = {
  name: 'grammar_primer_16',
  width: 16,
  height: 16,
  description: 'Small chalk slate with ABC letters and wooden frame.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [1,2], [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [1,3], [12,3],
      [1,4], [12,4],
      [1,5], [12,5],
      [1,6], [12,6],
      [1,7], [12,7],
      [1,8], [12,8],
      [1,9], [12,9],
      [1,10], [12,10],
      [1,11], [12,11],
      [1,12], [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'slate', role: 'head', pixels: [
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [2,5], [3,5], [6,5], [9,5], [11,5],
      [2,6], [3,6], [6,6], [9,6], [11,6],
      [2,7], [3,7], [6,7], [9,7], [11,7],
      [2,8], [3,8], [6,8], [9,8], [11,8],
      [2,9], [3,9], [6,9], [9,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'chalk_letters', role: 'arm', pixels: [
      [4,5], [5,5], [7,5], [8,5], [10,5],
      [4,6], [7,6], [10,6],
      [4,7], [5,7], [7,7], [10,7],
      [4,8], [7,8], [8,8], [10,8],
      [4,9], [7,9], [10,9],
    ]},
    { name: 'handle', role: 'belt', pixels: [
      [1,1], [2,1],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SCRIBES_LECTERN — Angled scribe lectern with open book resting on surface.
// ════════════════════════════════════════════════════════════
export const SCRIBES_LECTERN_16: SpriteTemplate = {
  name: 'scribes_lectern_16',
  width: 16,
  height: 16,
  description: 'Angled scribe lectern with open book resting on surface.',
  regions: [
    { name: 'book_cover', role: 'accessory', pixels: [
      [3,2], [4,2], [5,2], [6,2],
      [3,3], [4,3], [5,3], [6,3],
      [4,4], [5,4], [6,4], [7,4],
      [4,5], [5,5], [6,5], [7,5],
      [5,6], [6,6], [7,6], [8,6],
      [5,7], [6,7], [7,7], [8,7],
    ]},
    { name: 'book_pages', role: 'head', pixels: [
      [7,2], [8,2], [9,2], [10,2],
      [7,3], [8,3], [9,3], [10,3],
      [8,4], [9,4], [10,4], [11,4],
      [8,5], [9,5], [10,5], [11,5],
      [9,6], [10,6], [11,6], [12,6],
      [9,7], [10,7], [11,7],
    ]},
    { name: 'post', role: 'body', pixels: [
      [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10], [9,10],
      [6,11], [7,11], [8,11], [9,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
    { name: 'base_foot', role: 'arm', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// INK_POT — Small round ceramic ink pot with dark ink visible inside.
// ════════════════════════════════════════════════════════════
export const INK_POT_16: SpriteTemplate = {
  name: 'ink_pot_16',
  width: 16,
  height: 16,
  description: 'Small round ceramic ink pot with dark ink visible inside.',
  regions: [
    { name: 'ink_surface', role: 'eye', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
    ]},
    { name: 'rim_wall', role: 'head', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [11,7],
      [3,8], [4,8], [11,8],
      [3,9], [4,9], [11,9],
      [3,10], [4,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'pot_body', role: 'body', pixels: [
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
    ]},
    { name: 'base_foot', role: 'arm', pixels: [
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// REED_PEN — Simple bamboo reed pen with cut nib for calligraphy.
// ════════════════════════════════════════════════════════════
export const REED_PEN_16: SpriteTemplate = {
  name: 'reed_pen_16',
  width: 16,
  height: 16,
  description: 'Simple bamboo reed pen with cut nib for calligraphy.',
  regions: [
    { name: 'shaft', role: 'body', pixels: [
      [11,1], [12,1],
      [10,2], [11,2],
      [9,3], [10,3],
      [8,4], [9,4],
      [7,5], [8,5],
      [6,6], [7,6],
      [5,7], [6,7],
      [4,8], [5,8],
      [3,9], [4,9],
    ]},
    { name: 'nib_cut', role: 'head', pixels: [
      [2,10], [3,10],
      [2,11], [3,11],
    ]},
    { name: 'ink_tip', role: 'eye', pixels: [
      [1,12], [2,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SCROLL_RACK — Small wooden shelf with rolled scrolls and standing books.
// ════════════════════════════════════════════════════════════
export const SCROLL_RACK_16: SpriteTemplate = {
  name: 'scroll_rack_16',
  width: 16,
  height: 16,
  description: 'Small wooden shelf with rolled scrolls and standing books.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [2,0], [3,0], [4,0], [5,0], [6,0], [7,0], [8,0], [9,0], [10,0], [11,0], [12,0], [13,0],
      [2,1], [13,1],
      [2,2], [13,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
      [2,4], [13,4],
      [2,5], [13,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [2,7], [13,7],
      [2,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [2,10], [13,10],
      [2,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
      [2,13], [3,13], [12,13], [13,13],
      [2,14], [3,14], [12,14], [13,14],
    ]},
    { name: 'scrolls', role: 'head', pixels: [
      [3,1], [4,1], [5,1], [6,1],
      [3,2], [4,2], [5,2], [6,2],
      [7,4], [8,4], [9,4], [10,4],
      [7,5], [8,5], [9,5], [10,5],
      [5,7], [6,7], [11,7], [12,7],
      [5,8], [6,8], [11,8], [12,8],
      [3,10], [4,10], [11,10], [12,10],
      [3,11], [4,11], [11,11], [12,11],
    ]},
    { name: 'red_books', role: 'accessory', pixels: [
      [7,1], [8,1], [9,1], [10,1],
      [7,2], [8,2], [9,2], [10,2],
      [3,4], [4,4],
      [3,5], [4,5],
      [7,7], [8,7], [9,7], [10,7],
      [7,8], [8,8], [9,8], [10,8],
      [5,10], [6,10], [9,10], [10,10],
      [5,11], [6,11], [9,11], [10,11],
    ]},
    { name: 'blue_books', role: 'arm', pixels: [
      [11,1], [12,1],
      [11,2], [12,2],
      [5,4], [6,4], [11,4], [12,4],
      [5,5], [6,5], [11,5], [12,5],
      [3,7], [4,7],
      [3,8], [4,8],
      [7,10], [8,10],
      [7,11], [8,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BALANCE_SCALE — Two-pan balance scale for weighing arguments and truth.
// ════════════════════════════════════════════════════════════
export const BALANCE_SCALE_16: SpriteTemplate = {
  name: 'balance_scale_16',
  width: 16,
  height: 16,
  description: 'Two-pan balance scale for weighing arguments and truth.',
  regions: [
    { name: 'crown_pivot', role: 'eye', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'chains_beam', role: 'arm', pixels: [
      [1,3], [2,3], [3,3], [4,3], [5,3], [6,3], [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [2,4], [3,4], [12,4], [13,4],
      [2,5], [3,5], [12,5], [13,5],
      [1,6], [2,6], [3,6], [4,6], [11,6], [12,6], [13,6], [14,6],
    ]},
    { name: 'post', role: 'body', pixels: [
      [7,3], [8,3],
      [7,4], [8,4],
      [7,5], [8,5],
      [7,6], [8,6],
      [7,7], [8,7],
      [7,8], [8,8],
      [7,9], [8,9],
      [7,10], [8,10],
      [7,11], [8,11],
      [7,12], [8,12],
    ]},
    { name: 'pans', role: 'head', pixels: [
      [1,7], [2,7], [3,7], [4,7], [11,7], [12,7], [13,7], [14,7],
      [1,8], [2,8], [3,8], [4,8], [11,8], [12,8], [13,8], [14,8],
    ]},
    { name: 'base', role: 'belt', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// LOGIC_WHEEL — Patterned circular wheel of logical relationships and categories.
// ════════════════════════════════════════════════════════════
export const LOGIC_WHEEL_16: SpriteTemplate = {
  name: 'logic_wheel_16',
  width: 16,
  height: 16,
  description: 'Patterned circular wheel of logical relationships and categories.',
  regions: [
    { name: 'outer_ring', role: 'body', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [2,4], [3,4], [12,4], [13,4],
      [2,5], [13,5],
      [2,6], [13,6],
      [2,7], [13,7],
      [2,8], [13,8],
      [2,9], [3,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
    { name: 'quadrant_fill', role: 'head', pixels: [
      [4,4], [5,4], [6,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [9,5], [10,5], [11,5], [12,5],
      [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8],
      [4,9], [5,9], [6,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'cross_spokes', role: 'arm', pixels: [
      [7,4], [8,4],
      [7,5], [8,5],
      [3,6], [4,6], [5,6], [6,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [9,7], [10,7], [11,7], [12,7],
      [7,8], [8,8],
      [7,9], [8,9],
    ]},
    { name: 'center_hub', role: 'eye', pixels: [
      [7,6], [8,6],
      [7,7], [8,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CHESS_KING — Ornate chess king piece symbolizing strategic logical thinking.
// ════════════════════════════════════════════════════════════
export const CHESS_KING_16: SpriteTemplate = {
  name: 'chess_king_16',
  width: 16,
  height: 16,
  description: 'Ornate chess king piece symbolizing strategic logical thinking.',
  regions: [
    { name: 'cross_top', role: 'eye', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
      [7,3], [8,3],
    ]},
    { name: 'crown', role: 'accessory', pixels: [
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
    ]},
    { name: 'piece_body', role: 'head', pixels: [
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9], [9,9],
      [6,10], [7,10], [8,10], [9,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'base', role: 'body', pixels: [
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SKELETON_KEY — Ornate medieval skeleton key symbolizing unlocking truth.
// ════════════════════════════════════════════════════════════
export const SKELETON_KEY_16: SpriteTemplate = {
  name: 'skeleton_key_16',
  width: 16,
  height: 16,
  description: 'Ornate medieval skeleton key symbolizing unlocking truth.',
  regions: [
    { name: 'bow_handle', role: 'body', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [9,2], [10,2],
      [5,3], [6,3], [9,3], [10,3],
      [5,4], [6,4], [9,4], [10,4],
      [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'shaft', role: 'head', pixels: [
      [7,6], [8,6],
      [7,7], [8,7],
      [7,8], [8,8],
      [7,9], [8,9],
      [7,10], [8,10],
      [7,11], [8,11],
      [7,12], [8,12],
      [7,13], [8,13],
    ]},
    { name: 'teeth_bit', role: 'arm', pixels: [
      [9,11], [10,11],
      [10,12], [11,12],
      [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OIL_LANTERN — Medieval oil lantern representing the light of reason.
// ════════════════════════════════════════════════════════════
export const OIL_LANTERN_16: SpriteTemplate = {
  name: 'oil_lantern_16',
  width: 16,
  height: 16,
  description: 'Medieval oil lantern representing the light of reason.',
  regions: [
    { name: 'handle', role: 'arm', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [9,2], [10,2],
      [6,3], [7,3], [8,3], [9,3],
    ]},
    { name: 'frame', role: 'body', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [10,5], [11,5],
      [4,6], [5,6], [10,6], [11,6],
      [4,7], [5,7], [10,7], [11,7],
      [4,8], [5,8], [10,8], [11,8],
      [4,9], [5,9], [10,9], [11,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'glass_flame', role: 'eye', pixels: [
      [6,5], [7,5], [8,5], [9,5],
      [6,6], [7,6], [8,6], [9,6],
      [6,7], [7,7], [8,7], [9,7],
      [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'base', role: 'belt', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HOURGLASS — Wooden-framed hourglass with golden sand flowing through.
// ════════════════════════════════════════════════════════════
export const HOURGLASS_16: SpriteTemplate = {
  name: 'hourglass_16',
  width: 16,
  height: 16,
  description: 'Wooden-framed hourglass with golden sand flowing through.',
  regions: [
    { name: 'frame_posts', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [12,2],
      [4,3], [11,3],
      [5,4], [10,4],
      [6,5], [9,5],
      [6,6], [9,6],
      [7,7], [8,7],
      [7,8], [8,8],
      [6,9], [9,9],
      [6,10], [9,10],
      [5,11], [11,11],
      [4,12], [12,12],
      [3,13], [13,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
    { name: 'glass_bulb', role: 'head', pixels: [
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [5,3], [6,3], [9,3], [10,3],
      [6,4], [9,4],
      [6,11], [7,11], [10,11],
      [5,12], [6,12], [11,12],
      [4,13], [5,13], [12,13],
    ]},
    { name: 'sand', role: 'eye', pixels: [
      [7,3], [8,3],
      [7,4], [8,4],
      [7,5], [8,5],
      [7,6], [8,6],
      [7,9], [8,9],
      [7,10], [8,10],
      [8,11], [9,11],
      [7,12], [8,12], [9,12], [10,12],
      [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const QUILL_PEN_COLORS: ColorScheme = {
  name: 'quill_pen_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const INKWELL_QUILL_COLORS: ColorScheme = {
  name: 'inkwell_quill_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const OPEN_CODEX_COLORS: ColorScheme = {
  name: 'open_codex_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ROLLED_SCROLL_COLORS: ColorScheme = {
  name: 'rolled_scroll_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const UNFURLED_SCROLL_COLORS: ColorScheme = {
  name: 'unfurled_scroll_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const WAX_TABLET_COLORS: ColorScheme = {
  name: 'wax_tablet_default',
  mapping: {
    head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ILLUMINATED_LETTER_COLORS: ColorScheme = {
  name: 'illuminated_letter_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const LEATHER_TOME_COLORS: ColorScheme = {
  name: 'leather_tome_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const PARCHMENT_SHEET_COLORS: ColorScheme = {
  name: 'parchment_sheet_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const GRAMMAR_PRIMER_COLORS: ColorScheme = {
  name: 'grammar_primer_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SCRIBES_LECTERN_COLORS: ColorScheme = {
  name: 'scribes_lectern_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const INK_POT_COLORS: ColorScheme = {
  name: 'ink_pot_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const REED_PEN_COLORS: ColorScheme = {
  name: 'reed_pen_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SCROLL_RACK_COLORS: ColorScheme = {
  name: 'scroll_rack_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const BALANCE_SCALE_COLORS: ColorScheme = {
  name: 'balance_scale_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const LOGIC_WHEEL_COLORS: ColorScheme = {
  name: 'logic_wheel_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CHESS_KING_COLORS: ColorScheme = {
  name: 'chess_king_default',
  mapping: {
    head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const SKELETON_KEY_COLORS: ColorScheme = {
  name: 'skeleton_key_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const OIL_LANTERN_COLORS: ColorScheme = {
  name: 'oil_lantern_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const HOURGLASS_COLORS: ColorScheme = {
  name: 'hourglass_default',
  mapping: {
    head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const LIBERAL_ARTS_BATCH1_TEMPLATES: Record<string, SpriteTemplate> = {
  quill_pen_16: QUILL_PEN_16,
  inkwell_quill_16: INKWELL_QUILL_16,
  open_codex_16: OPEN_CODEX_16,
  rolled_scroll_16: ROLLED_SCROLL_16,
  unfurled_scroll_16: UNFURLED_SCROLL_16,
  wax_tablet_16: WAX_TABLET_16,
  illuminated_letter_16: ILLUMINATED_LETTER_16,
  leather_tome_16: LEATHER_TOME_16,
  parchment_sheet_16: PARCHMENT_SHEET_16,
  grammar_primer_16: GRAMMAR_PRIMER_16,
  scribes_lectern_16: SCRIBES_LECTERN_16,
  ink_pot_16: INK_POT_16,
  reed_pen_16: REED_PEN_16,
  scroll_rack_16: SCROLL_RACK_16,
  balance_scale_16: BALANCE_SCALE_16,
  logic_wheel_16: LOGIC_WHEEL_16,
  chess_king_16: CHESS_KING_16,
  skeleton_key_16: SKELETON_KEY_16,
  oil_lantern_16: OIL_LANTERN_16,
  hourglass_16: HOURGLASS_16,
};

export const LIBERAL_ARTS_BATCH1_COLOR_SCHEMES: Record<string, ColorScheme> = {
  quill_pen_default: QUILL_PEN_COLORS,
  inkwell_quill_default: INKWELL_QUILL_COLORS,
  open_codex_default: OPEN_CODEX_COLORS,
  rolled_scroll_default: ROLLED_SCROLL_COLORS,
  unfurled_scroll_default: UNFURLED_SCROLL_COLORS,
  wax_tablet_default: WAX_TABLET_COLORS,
  illuminated_letter_default: ILLUMINATED_LETTER_COLORS,
  leather_tome_default: LEATHER_TOME_COLORS,
  parchment_sheet_default: PARCHMENT_SHEET_COLORS,
  grammar_primer_default: GRAMMAR_PRIMER_COLORS,
  scribes_lectern_default: SCRIBES_LECTERN_COLORS,
  ink_pot_default: INK_POT_COLORS,
  reed_pen_default: REED_PEN_COLORS,
  scroll_rack_default: SCROLL_RACK_COLORS,
  balance_scale_default: BALANCE_SCALE_COLORS,
  logic_wheel_default: LOGIC_WHEEL_COLORS,
  chess_king_default: CHESS_KING_COLORS,
  skeleton_key_default: SKELETON_KEY_COLORS,
  oil_lantern_default: OIL_LANTERN_COLORS,
  hourglass_default: HOURGLASS_COLORS,
};
