/**
 * 16x16 modernTech templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-01.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// OXYGEN_TANK — Portable oxygen supply tank with gauge.
// ════════════════════════════════════════════════════════════
export const OXYGEN_TANK_16: SpriteTemplate = {
  name: 'oxygen_tank_16',
  width: 16,
  height: 16,
  description: 'Portable oxygen supply tank with gauge.',
  regions: [
    { name: 'tank', role: 'body', pixels: [
      [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [4,7], [5,7],
      [4,8], [5,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12],
      [5,13], [6,13], [7,13], [8,13],
    ]},
    { name: 'gauge', role: 'eye', pixels: [
      [6,7], [7,7], [8,7], [9,7],
      [6,8], [7,8], [8,8], [9,8],
    ]},
    { name: 'valve', role: 'arm', pixels: [
      [6,1], [7,1],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SCI_MEDKIT — Futuristic medical kit with healing nanobots.
// ════════════════════════════════════════════════════════════
export const SCI_MEDKIT_16: SpriteTemplate = {
  name: 'sci_medkit_16',
  width: 16,
  height: 16,
  description: 'Futuristic medical kit with healing nanobots.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [2,4], [3,4], [4,4], [5,4], [8,4], [9,4], [10,4],
      [2,5], [3,5], [4,5], [9,5], [10,5],
      [2,6], [3,6], [4,6], [5,6], [8,6], [9,6], [10,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
    { name: 'cross', role: 'eye', pixels: [
      [6,4], [7,4],
      [5,5], [6,5], [7,5], [8,5],
      [6,6], [7,6],
    ]},
    { name: 'bottom', role: 'arm', pixels: [
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GRAVITY_WELL — Gravity distortion field generator.
// ════════════════════════════════════════════════════════════
export const GRAVITY_WELL_16: SpriteTemplate = {
  name: 'gravity_well_16',
  width: 16,
  height: 16,
  description: 'Gravity distortion field generator.',
  regions: [
    { name: 'distortion', role: 'accessory', pixels: [
      [6,1], [7,1],
      [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [3,4], [4,4], [5,4], [6,4], [9,4], [10,4],
      [2,5], [3,5], [4,5], [5,5], [10,5], [11,5],
      [2,6], [3,6], [4,6], [10,6], [11,6],
      [2,7], [3,7], [4,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [10,8], [11,8],
      [3,9], [4,9], [5,9], [6,9], [9,9], [10,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
      [5,11], [6,11], [7,11], [8,11],
      [6,12], [7,12],
    ]},
    { name: 'core', role: 'body', pixels: [
      [7,4], [8,4],
      [6,5], [7,5], [8,5], [9,5],
      [5,6], [6,6], [9,6],
      [5,7], [6,7], [9,7],
      [6,8], [7,8], [8,8], [9,8],
      [7,9], [8,9],
    ]},
    { name: 'singularity', role: 'eye', pixels: [
      [7,6], [8,6],
      [7,7], [8,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TELEPORTER_PAD — Ground teleportation platform with ring lights.
// ════════════════════════════════════════════════════════════
export const TELEPORTER_PAD_16: SpriteTemplate = {
  name: 'teleporter_pad_16',
  width: 16,
  height: 16,
  description: 'Ground teleportation platform with ring lights.',
  regions: [
    { name: 'platform', role: 'body', pixels: [
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [2,12], [3,12], [4,12], [5,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
    { name: 'ring_light', role: 'eye', pixels: [
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [2,9], [11,9],
      [2,10], [12,10],
      [1,11], [12,11],
      [1,12], [6,12], [12,12],
      [1,13], [12,13],
      [2,14], [11,14],
      [3,15], [4,15], [5,15], [6,15], [7,15], [8,15], [9,15], [10,15],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MAGNETIC_MINE — Deployable magnetic proximity mine.
// ════════════════════════════════════════════════════════════
export const MAGNETIC_MINE_16: SpriteTemplate = {
  name: 'magnetic_mine_16',
  width: 16,
  height: 16,
  description: 'Deployable magnetic proximity mine.',
  regions: [
    { name: 'shell', role: 'body', pixels: [
      [6,4], [7,4],
      [5,5], [6,5], [7,5], [8,5],
      [4,6], [5,6], [8,6], [9,6],
      [4,7], [5,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9],
      [6,10], [7,10],
    ]},
    { name: 'sensor', role: 'eye', pixels: [
      [6,6], [7,6],
      [6,7], [7,7],
    ]},
    { name: 'spikes', role: 'arm', pixels: [
      [5,3], [6,3], [7,3], [8,3],
      [4,4], [5,4], [8,4], [9,4],
      [3,5], [4,5], [9,5], [10,5],
      [2,6], [3,6], [10,6],
      [2,7], [3,7], [10,7],
      [2,8], [3,8], [10,8], [11,8],
      [3,9], [4,9], [9,9], [10,9],
      [4,10], [5,10], [8,10], [9,10],
      [5,11], [6,11], [7,11], [8,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HACKING_TOOL — Cyberpunk hacking multitool device.
// ════════════════════════════════════════════════════════════
export const HACKING_TOOL_16: SpriteTemplate = {
  name: 'hacking_tool_16',
  width: 16,
  height: 16,
  description: 'Cyberpunk hacking multitool device.',
  regions: [
    { name: 'head', role: 'body', pixels: [
      [6,2], [7,2],
      [5,3], [6,3], [7,3], [8,3],
      [4,4], [5,4], [8,4], [9,4],
      [4,5], [5,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [5,7], [6,7], [7,7], [8,7],
      [6,8], [7,8],
    ]},
    { name: 'display', role: 'eye', pixels: [
      [6,4], [7,4],
      [6,5], [7,5],
    ]},
    { name: 'shaft', role: 'belt', pixels: [
      [6,9], [7,9],
      [6,10], [7,10],
      [6,11], [7,11],
      [6,12], [7,12],
    ]},
    { name: 'grip', role: 'arm', pixels: [
      [5,13], [6,13], [7,13], [8,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CLOAKING_DEVICE — Personal cloaking / invisibility generator.
// ════════════════════════════════════════════════════════════
export const CLOAKING_DEVICE_16: SpriteTemplate = {
  name: 'cloaking_device_16',
  width: 16,
  height: 16,
  description: 'Personal cloaking / invisibility generator.',
  regions: [
    { name: 'core', role: 'body', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [8,5], [9,5],
      [4,6], [5,6], [8,6], [9,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
    ]},
    { name: 'crystal', role: 'eye', pixels: [
      [6,5], [7,5],
      [6,6], [7,6],
    ]},
    { name: 'field', role: 'accessory', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [2,3], [11,3],
      [2,4], [11,4],
      [2,5], [11,5],
      [2,6], [11,6],
      [2,7], [11,7],
      [2,8], [11,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
    ]},
    { name: 'base', role: 'arm', pixels: [
      [5,10], [6,10], [7,10], [8,10],
      [6,11], [7,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// POWER_CELL_PACK — Pack of three power cells in a carrier.
// ════════════════════════════════════════════════════════════
export const POWER_CELL_PACK_16: SpriteTemplate = {
  name: 'power_cell_pack_16',
  width: 16,
  height: 16,
  description: 'Pack of three power cells in a carrier.',
  regions: [
    { name: 'cell', role: 'body', pixels: [
      [2,2], [3,2], [4,2], [6,2], [7,2], [8,2], [10,2], [11,2], [12,2],
      [2,3], [4,3], [6,3], [8,3], [10,3], [12,3],
      [2,4], [4,4], [6,4], [8,4], [10,4], [12,4],
      [2,5], [4,5], [6,5], [8,5], [10,5], [12,5],
      [2,6], [4,6], [6,6], [8,6], [10,6], [12,6],
      [2,7], [3,7], [4,7], [6,7], [7,7], [8,7], [10,7], [11,7], [12,7],
    ]},
    { name: 'charge', role: 'eye', pixels: [
      [3,3], [7,3], [11,3],
      [3,4], [7,4], [11,4],
      [3,5], [7,5], [11,5],
      [3,6], [7,6], [11,6],
    ]},
    { name: 'carrier', role: 'arm', pixels: [
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// REPAIR_DRONE — Small autonomous repair bot.
// ════════════════════════════════════════════════════════════
export const REPAIR_DRONE_16: SpriteTemplate = {
  name: 'repair_drone_16',
  width: 16,
  height: 16,
  description: 'Small autonomous repair bot.',
  regions: [
    { name: 'chassis', role: 'body', pixels: [
      [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [3,4], [4,4], [5,4], [9,4], [10,4],
      [3,5], [4,5], [5,5], [9,5], [10,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [6,9], [7,9],
    ]},
    { name: 'welder', role: 'eye', pixels: [
      [6,4], [7,4], [8,4],
      [6,5], [7,5], [8,5],
    ]},
    { name: 'arms', role: 'arm', pixels: [
      [2,7], [3,7], [10,7], [11,7],
      [2,8], [3,8], [10,8], [11,8],
      [3,9], [4,9], [5,9], [8,9], [9,9], [10,9],
    ]},
    { name: 'thruster', role: 'leg', pixels: [
      [6,10], [7,10],
      [5,11], [6,11], [7,11], [8,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// STIM_INJECTOR — Medical stimulant auto-injector.
// ════════════════════════════════════════════════════════════
export const STIM_INJECTOR_16: SpriteTemplate = {
  name: 'stim_injector_16',
  width: 16,
  height: 16,
  description: 'Medical stimulant auto-injector.',
  regions: [
    { name: 'body', role: 'body', pixels: [
      [6,2], [7,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [3,5], [4,5], [5,5], [8,5], [9,5],
      [3,6], [4,6], [5,6], [8,6], [9,6],
      [3,7], [4,7], [5,7], [8,7], [9,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11],
    ]},
    { name: 'liquid', role: 'eye', pixels: [
      [6,5], [7,5],
      [6,6], [7,6],
      [6,7], [7,7],
    ]},
    { name: 'plunger', role: 'arm', pixels: [
      [5,1], [6,1], [7,1], [8,1],
      [4,2], [5,2], [8,2], [9,2],
    ]},
    { name: 'needle', role: 'leg', pixels: [
      [5,12], [6,12], [7,12], [8,12],
      [5,13], [6,13], [7,13], [8,13],
      [6,14], [7,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CIRCUIT_BOARD — Circuit board component with chips.
// ════════════════════════════════════════════════════════════
export const CIRCUIT_BOARD_16: SpriteTemplate = {
  name: 'circuit_board_16',
  width: 16,
  height: 16,
  description: 'Circuit board component with chips.',
  regions: [
    { name: 'board', role: 'body', pixels: [
      [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [2,2], [3,2], [6,2], [7,2], [10,2], [11,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [2,4], [3,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [2,5], [3,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [2,7], [3,7], [4,7], [5,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [6,10], [7,10], [10,10], [11,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'chip', role: 'eye', pixels: [
      [4,2], [5,2], [8,2], [9,2],
      [4,10], [5,10], [8,10], [9,10],
    ]},
    { name: 'trace', role: 'arm', pixels: [
      [4,4], [5,4],
      [4,5], [5,5],
      [6,7], [7,7],
      [6,8], [7,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ANTENNA_TOWER — Communication antenna tower.
// ════════════════════════════════════════════════════════════
export const ANTENNA_TOWER_16: SpriteTemplate = {
  name: 'antenna_tower_16',
  width: 16,
  height: 16,
  description: 'Communication antenna tower.',
  regions: [
    { name: 'mast', role: 'body', pixels: [
      [7,1],
      [6,2], [7,2], [8,2],
      [7,3],
      [6,4], [7,4], [8,4],
      [6,5], [7,5], [8,5],
      [7,6],
      [6,7], [7,7], [8,7],
      [6,8], [7,8], [8,8],
      [7,9],
      [6,10], [7,10], [8,10],
      [6,11], [7,11], [8,11],
    ]},
    { name: 'dish', role: 'eye', pixels: [
      [7,0],
      [6,1], [8,1],
    ]},
    { name: 'cross_beam', role: 'arm', pixels: [
      [5,3], [6,3], [8,3], [9,3],
      [5,6], [6,6], [8,6], [9,6],
      [5,9], [6,9], [8,9], [9,9],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [5,12], [6,12], [7,12], [8,12], [9,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BIOSCANNER — Handheld biological scanning device.
// ════════════════════════════════════════════════════════════
export const BIOSCANNER_16: SpriteTemplate = {
  name: 'bioscanner_16',
  width: 16,
  height: 16,
  description: 'Handheld biological scanning device.',
  regions: [
    { name: 'housing', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2],
      [2,3], [3,3], [10,3],
      [2,4], [3,4], [10,4],
      [2,5], [3,5], [10,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
    ]},
    { name: 'display', role: 'eye', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'grip', role: 'belt', pixels: [
      [4,8], [5,8], [6,8], [7,8],
      [4,9], [5,9], [6,9], [7,9],
      [4,10], [5,10], [6,10], [7,10],
      [5,11], [6,11],
    ]},
    { name: 'antenna', role: 'arm', pixels: [
      [6,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SHIELD_BATTERY — Rechargeable energy shield battery.
// ════════════════════════════════════════════════════════════
export const SHIELD_BATTERY_16: SpriteTemplate = {
  name: 'shield_battery_16',
  width: 16,
  height: 16,
  description: 'Rechargeable energy shield battery.',
  regions: [
    { name: 'casing', role: 'body', pixels: [
      [5,3], [6,3], [7,3], [8,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [4,5], [9,5],
      [4,6], [9,6],
      [4,7], [9,7],
      [4,8], [9,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
      [5,10], [6,10], [7,10], [8,10],
    ]},
    { name: 'charge', role: 'eye', pixels: [
      [5,5], [6,5], [7,5], [8,5],
      [5,6], [6,6], [7,6], [8,6],
      [5,7], [6,7], [7,7], [8,7],
      [5,8], [6,8], [7,8], [8,8],
    ]},
    { name: 'terminal', role: 'arm', pixels: [
      [6,2], [7,2],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// THERMAL_SCOPE — Thermal vision scope / monocular.
// ════════════════════════════════════════════════════════════
export const THERMAL_SCOPE_16: SpriteTemplate = {
  name: 'thermal_scope_16',
  width: 16,
  height: 16,
  description: 'Thermal vision scope / monocular.',
  regions: [
    { name: 'housing', role: 'body', pixels: [
      [2,3], [3,3], [4,3], [5,3], [6,3],
      [1,4], [2,4], [3,4], [4,4], [5,4], [6,4], [7,4],
      [1,5], [2,5], [7,5], [8,5],
      [1,6], [2,6], [7,6], [8,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [6,10], [7,10], [8,10],
    ]},
    { name: 'lens', role: 'eye', pixels: [
      [3,5], [4,5], [5,5], [6,5],
      [3,6], [4,6], [5,6], [6,6],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MINING_LASER — Industrial mining laser tool.
// ════════════════════════════════════════════════════════════
export const MINING_LASER_16: SpriteTemplate = {
  name: 'mining_laser_16',
  width: 16,
  height: 16,
  description: 'Industrial mining laser tool.',
  regions: [
    { name: 'barrel', role: 'body', pixels: [
      [4,3], [5,3], [6,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7],
      [7,8], [8,8],
    ]},
    { name: 'emitter', role: 'eye', pixels: [
      [2,2], [3,2],
      [2,3], [3,3],
    ]},
    { name: 'grip', role: 'belt', pixels: [
      [4,8], [5,8], [6,8],
      [4,9], [5,9], [6,9], [7,9],
      [4,10], [5,10], [6,10], [7,10],
    ]},
    { name: 'battery', role: 'arm', pixels: [
      [5,11], [6,11], [7,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HOLO_MAP — Portable holographic map projector.
// ════════════════════════════════════════════════════════════
export const HOLO_MAP_16: SpriteTemplate = {
  name: 'holo_map_16',
  width: 16,
  height: 16,
  description: 'Portable holographic map projector.',
  regions: [
    { name: 'hologram', role: 'accessory', pixels: [
      [4,0], [5,0], [6,0], [7,0], [8,0], [9,0], [10,0],
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
    ]},
    { name: 'projector', role: 'body', pixels: [
      [6,6], [7,6],
      [5,7], [6,7], [7,7], [8,7],
      [4,8], [5,8], [8,8], [9,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'lens', role: 'eye', pixels: [
      [6,8], [7,8],
    ]},
    { name: 'base', role: 'arm', pixels: [
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TRACTOR_BEAM — Tractor beam emitter device.
// ════════════════════════════════════════════════════════════
export const TRACTOR_BEAM_16: SpriteTemplate = {
  name: 'tractor_beam_16',
  width: 16,
  height: 16,
  description: 'Tractor beam emitter device.',
  regions: [
    { name: 'body', role: 'body', pixels: [
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'beam', role: 'eye', pixels: [
      [6,2], [7,2],
      [5,3], [6,3], [7,3], [8,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'grip', role: 'belt', pixels: [
      [5,10], [6,10], [7,10], [8,10],
      [5,11], [6,11], [7,11], [8,11],
    ]},
    { name: 'control', role: 'arm', pixels: [
      [6,12], [7,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// THERMAL_DETONATOR — Compact thermal explosive device.
// ════════════════════════════════════════════════════════════
export const THERMAL_DETONATOR_16: SpriteTemplate = {
  name: 'thermal_detonator_16',
  width: 16,
  height: 16,
  description: 'Compact thermal explosive device.',
  regions: [
    { name: 'shell', role: 'body', pixels: [
      [5,4], [6,4], [7,4], [8,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [3,7], [4,7], [5,7], [7,7], [8,7], [10,7],
      [3,8], [4,8], [5,8], [7,8], [8,8], [10,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
      [5,11], [6,11], [7,11], [8,11],
    ]},
    { name: 'trigger', role: 'eye', pixels: [
      [6,7],
      [6,8],
    ]},
    { name: 'pin', role: 'arm', pixels: [
      [6,3], [7,3],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// QUANTUM_COMPUTER — Miniature quantum computing unit.
// ════════════════════════════════════════════════════════════
export const QUANTUM_COMPUTER_16: SpriteTemplate = {
  name: 'quantum_computer_16',
  width: 16,
  height: 16,
  description: 'Miniature quantum computing unit.',
  regions: [
    { name: 'chassis', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [2,3], [3,3], [6,3], [7,3], [10,3], [11,3],
      [2,4], [3,4], [6,4], [7,4], [10,4], [11,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [2,6], [3,6], [6,6], [7,6], [10,6], [11,6],
      [2,7], [3,7], [6,7], [7,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'qubit', role: 'eye', pixels: [
      [4,3], [5,3], [8,3], [9,3],
      [4,4], [5,4], [8,4], [9,4],
      [4,6], [5,6], [8,6], [9,6],
      [4,7], [5,7], [8,7], [9,7],
    ]},
    { name: 'base', role: 'arm', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const OXYGEN_TANK_COLORS: ColorScheme = {
  name: 'oxygen_tank_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SCI_MEDKIT_COLORS: ColorScheme = {
  name: 'sci_medkit_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const GRAVITY_WELL_COLORS: ColorScheme = {
  name: 'gravity_well_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const TELEPORTER_PAD_COLORS: ColorScheme = {
  name: 'teleporter_pad_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const MAGNETIC_MINE_COLORS: ColorScheme = {
  name: 'magnetic_mine_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const HACKING_TOOL_COLORS: ColorScheme = {
  name: 'hacking_tool_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CLOAKING_DEVICE_COLORS: ColorScheme = {
  name: 'cloaking_device_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
  },
};

export const POWER_CELL_PACK_COLORS: ColorScheme = {
  name: 'power_cell_pack_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const REPAIR_DRONE_COLORS: ColorScheme = {
  name: 'repair_drone_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const STIM_INJECTOR_COLORS: ColorScheme = {
  name: 'stim_injector_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CIRCUIT_BOARD_COLORS: ColorScheme = {
  name: 'circuit_board_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ANTENNA_TOWER_COLORS: ColorScheme = {
  name: 'antenna_tower_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const BIOSCANNER_COLORS: ColorScheme = {
  name: 'bioscanner_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SHIELD_BATTERY_COLORS: ColorScheme = {
  name: 'shield_battery_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const THERMAL_SCOPE_COLORS: ColorScheme = {
  name: 'thermal_scope_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const MINING_LASER_COLORS: ColorScheme = {
  name: 'mining_laser_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const HOLO_MAP_COLORS: ColorScheme = {
  name: 'holo_map_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
  },
};

export const TRACTOR_BEAM_COLORS: ColorScheme = {
  name: 'tractor_beam_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const THERMAL_DETONATOR_COLORS: ColorScheme = {
  name: 'thermal_detonator_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const QUANTUM_COMPUTER_COLORS: ColorScheme = {
  name: 'quantum_computer_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
    arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const MODERN_TECH_BATCH3_TEMPLATES: Record<string, SpriteTemplate> = {
  oxygen_tank_16: OXYGEN_TANK_16,
  sci_medkit_16: SCI_MEDKIT_16,
  gravity_well_16: GRAVITY_WELL_16,
  teleporter_pad_16: TELEPORTER_PAD_16,
  magnetic_mine_16: MAGNETIC_MINE_16,
  hacking_tool_16: HACKING_TOOL_16,
  cloaking_device_16: CLOAKING_DEVICE_16,
  power_cell_pack_16: POWER_CELL_PACK_16,
  repair_drone_16: REPAIR_DRONE_16,
  stim_injector_16: STIM_INJECTOR_16,
  circuit_board_16: CIRCUIT_BOARD_16,
  antenna_tower_16: ANTENNA_TOWER_16,
  bioscanner_16: BIOSCANNER_16,
  shield_battery_16: SHIELD_BATTERY_16,
  thermal_scope_16: THERMAL_SCOPE_16,
  mining_laser_16: MINING_LASER_16,
  holo_map_16: HOLO_MAP_16,
  tractor_beam_16: TRACTOR_BEAM_16,
  thermal_detonator_16: THERMAL_DETONATOR_16,
  quantum_computer_16: QUANTUM_COMPUTER_16,
};

export const MODERN_TECH_BATCH3_COLOR_SCHEMES: Record<string, ColorScheme> = {
  oxygen_tank_default: OXYGEN_TANK_COLORS,
  sci_medkit_default: SCI_MEDKIT_COLORS,
  gravity_well_default: GRAVITY_WELL_COLORS,
  teleporter_pad_default: TELEPORTER_PAD_COLORS,
  magnetic_mine_default: MAGNETIC_MINE_COLORS,
  hacking_tool_default: HACKING_TOOL_COLORS,
  cloaking_device_default: CLOAKING_DEVICE_COLORS,
  power_cell_pack_default: POWER_CELL_PACK_COLORS,
  repair_drone_default: REPAIR_DRONE_COLORS,
  stim_injector_default: STIM_INJECTOR_COLORS,
  circuit_board_default: CIRCUIT_BOARD_COLORS,
  antenna_tower_default: ANTENNA_TOWER_COLORS,
  bioscanner_default: BIOSCANNER_COLORS,
  shield_battery_default: SHIELD_BATTERY_COLORS,
  thermal_scope_default: THERMAL_SCOPE_COLORS,
  mining_laser_default: MINING_LASER_COLORS,
  holo_map_default: HOLO_MAP_COLORS,
  tractor_beam_default: TRACTOR_BEAM_COLORS,
  thermal_detonator_default: THERMAL_DETONATOR_COLORS,
  quantum_computer_default: QUANTUM_COMPUTER_COLORS,
};
