/**
 * 16x16 retroTech templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-01.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// TUBE_RADIO — Art deco style vintage tube radio with dial.
// ════════════════════════════════════════════════════════════
export const TUBE_RADIO_16: SpriteTemplate = {
  name: 'tube_radio_16',
  width: 16,
  height: 16,
  description: 'Art deco style vintage tube radio with dial.',
  regions: [
    { name: 'cabinet', role: 'body', pixels: [
      [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1],
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2],
      [2,3], [7,3], [8,3], [12,3], [13,3],
      [2,4], [7,4], [8,4], [12,4], [13,4],
      [2,5], [7,5], [8,5], [12,5], [13,5],
      [2,6], [7,6], [8,6], [12,6], [13,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'speaker_grille', role: 'eye', pixels: [
      [3,3], [4,3], [5,3], [6,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [9,6], [10,6], [11,6],
    ]},
    { name: 'dial', role: 'head', pixels: [
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SCIENTIFIC_CALC — Vintage scientific calculator with LCD display.
// ════════════════════════════════════════════════════════════
export const SCIENTIFIC_CALC_16: SpriteTemplate = {
  name: 'scientific_calc_16',
  width: 16,
  height: 16,
  description: 'Vintage scientific calculator with LCD display.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [11,2], [12,2],
      [3,3], [11,3], [12,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [12,5],
      [3,6], [12,6],
      [3,7], [12,7],
      [3,8], [12,8],
      [3,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'display', role: 'eye', pixels: [
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
    ]},
    { name: 'keys', role: 'head', pixels: [
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TRANSISTOR_RADIO — Pocket transistor radio with round speaker.
// ════════════════════════════════════════════════════════════
export const TRANSISTOR_RADIO_16: SpriteTemplate = {
  name: 'transistor_radio_16',
  width: 16,
  height: 16,
  description: 'Pocket transistor radio with round speaker.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3], [4,3], [10,3], [11,3], [12,3],
      [3,4], [12,4],
      [3,5], [12,5],
      [3,6], [12,6],
      [3,7], [4,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [7,9], [8,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'speaker', role: 'eye', pixels: [
      [5,3], [6,3], [7,3], [8,3], [9,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [5,7], [6,7], [7,7], [8,7], [9,7],
    ]},
    { name: 'dials', role: 'head', pixels: [
      [5,9], [6,9], [9,9],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ANALOG_CLOCK — Wall-mounted analog clock with roman numerals.
// ════════════════════════════════════════════════════════════
export const ANALOG_CLOCK_16: SpriteTemplate = {
  name: 'analog_clock_16',
  width: 16,
  height: 16,
  description: 'Wall-mounted analog clock with roman numerals.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [2,3], [3,3], [12,3], [13,3],
      [2,4], [13,4],
      [2,5], [12,5], [13,5],
      [2,6], [12,6], [13,6],
      [2,7], [13,7],
      [2,8], [12,8], [13,8],
      [2,9], [3,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'face', role: 'eye', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'hands', role: 'head', pixels: [
      [7,5],
      [7,6],
      [7,7], [8,7], [9,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// LIGHT_BULB — Classic incandescent light bulb with filament.
// ════════════════════════════════════════════════════════════
export const LIGHT_BULB_16: SpriteTemplate = {
  name: 'light_bulb_16',
  width: 16,
  height: 16,
  description: 'Classic incandescent light bulb with filament.',
  regions: [
    { name: 'glass', role: 'eye', pixels: [
      [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [3,4], [4,4], [5,4], [6,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [5,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
    { name: 'filament', role: 'head', pixels: [
      [7,4], [8,4],
      [6,5], [7,5], [8,5], [9,5],
      [7,6], [8,6],
    ]},
    { name: 'base_ring', role: 'body', pixels: [
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'screw_base', role: 'leg', pixels: [
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [6,12], [7,12], [8,12], [9,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COMPASS — Vintage brass compass with cardinal directions.
// ════════════════════════════════════════════════════════════
export const COMPASS_16: SpriteTemplate = {
  name: 'compass_16',
  width: 16,
  height: 16,
  description: 'Vintage brass compass with cardinal directions.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [2,3], [3,3], [12,3], [13,3],
      [2,4], [13,4],
      [2,5], [12,5], [13,5],
      [2,6], [12,6], [13,6],
      [2,7], [12,7], [13,7],
      [2,8], [13,8],
      [2,9], [3,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'dial', role: 'eye', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [5,5], [6,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'needle', role: 'head', pixels: [
      [7,5],
      [6,6], [7,6], [8,6],
      [7,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SLIDE_RULE — Analog slide rule calculation instrument.
// ════════════════════════════════════════════════════════════
export const SLIDE_RULE_16: SpriteTemplate = {
  name: 'slide_rule_16',
  width: 16,
  height: 16,
  description: 'Analog slide rule calculation instrument.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [2,5], [12,5], [13,5],
      [2,6], [12,6], [13,6],
      [2,7], [12,7], [13,7],
      [2,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'slider', role: 'eye', pixels: [
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
    ]},
    { name: 'scales', role: 'head', pixels: [
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CASSETTE_WALKMAN — Portable cassette Walkman player with headphone jack.
// ════════════════════════════════════════════════════════════
export const CASSETTE_WALKMAN_16: SpriteTemplate = {
  name: 'cassette_walkman_16',
  width: 16,
  height: 16,
  description: 'Portable cassette Walkman player with headphone jack.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3], [4,3], [11,3], [12,3],
      [3,4], [4,4], [11,4], [12,4],
      [3,5], [4,5], [11,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
    { name: 'reels', role: 'eye', pixels: [
      [5,3], [6,3], [9,3], [10,3],
      [5,4], [6,4], [9,4], [10,4],
      [5,5], [6,5], [9,5], [10,5],
    ]},
    { name: 'window', role: 'head', pixels: [
      [7,3], [8,3],
      [7,4], [8,4],
      [7,5], [8,5],
      [7,9],
    ]},
    { name: 'buttons', role: 'accessory', pixels: [
      [4,7], [5,7], [6,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DARKROOM_ENLARGER — Photographic darkroom enlarger for print development.
// ════════════════════════════════════════════════════════════
export const DARKROOM_ENLARGER_16: SpriteTemplate = {
  name: 'darkroom_enlarger_16',
  width: 16,
  height: 16,
  description: 'Photographic darkroom enlarger for print development.',
  regions: [
    { name: 'lamp_head', role: 'head', pixels: [
      [7,0], [8,0],
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
    ]},
    { name: 'lens', role: 'eye', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'column', role: 'body', pixels: [
      [7,5], [8,5],
      [7,6], [8,6],
      [7,7], [8,7],
      [7,8], [8,8],
      [7,9], [8,9],
      [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'baseboard', role: 'leg', pixels: [
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GRAMOPHONE_HORN — Gramophone with large horn speaker.
// ════════════════════════════════════════════════════════════
export const GRAMOPHONE_HORN_16: SpriteTemplate = {
  name: 'gramophone_horn_16',
  width: 16,
  height: 16,
  description: 'Gramophone with large horn speaker.',
  regions: [
    { name: 'horn', role: 'head', pixels: [
      [8,0], [9,0], [10,0], [11,0], [12,0], [13,0],
      [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1],
      [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [5,3], [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4],
    ]},
    { name: 'tonearm', role: 'eye', pixels: [
      [4,4],
      [3,5], [4,5],
      [3,6], [4,6],
    ]},
    { name: 'cabinet', role: 'body', pixels: [
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SEXTANT — Navigation sextant instrument.
// ════════════════════════════════════════════════════════════
export const SEXTANT_16: SpriteTemplate = {
  name: 'sextant_16',
  width: 16,
  height: 16,
  description: 'Navigation sextant instrument.',
  regions: [
    { name: 'arc', role: 'head', pixels: [
      [6,1], [7,1],
      [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [8,3], [9,3],
      [3,4], [4,4], [11,4], [12,4],
      [2,5], [3,5], [12,5], [13,5],
    ]},
    { name: 'telescope', role: 'eye', pixels: [
      [6,3], [7,3],
      [7,4], [8,4],
      [7,5], [8,5],
    ]},
    { name: 'frame', role: 'body', pixels: [
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [2,8], [9,8], [10,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'scale', role: 'accessory', pixels: [
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MAGIC_LANTERN — Early projection magic lantern / slide projector.
// ════════════════════════════════════════════════════════════
export const MAGIC_LANTERN_16: SpriteTemplate = {
  name: 'magic_lantern_16',
  width: 16,
  height: 16,
  description: 'Early projection magic lantern / slide projector.',
  regions: [
    { name: 'chimney', role: 'head', pixels: [
      [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [4,2], [5,2], [10,2], [11,2],
      [4,3], [11,3],
      [4,4], [11,4],
      [4,5], [5,5], [10,5], [11,5],
    ]},
    { name: 'lens', role: 'eye', pixels: [
      [6,2], [7,2], [8,2], [9,2],
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'box', role: 'body', pixels: [
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [3,8], [4,8], [5,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
    { name: 'slide_slot', role: 'accessory', pixels: [
      [6,8],
    ]},
    { name: 'legs', role: 'leg', pixels: [
      [3,11], [4,11], [5,11], [6,11], [9,11], [10,11], [11,11], [12,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TELEGRAPH_MACHINE — Morse code telegraph machine with key arm.
// ════════════════════════════════════════════════════════════
export const TELEGRAPH_MACHINE_16: SpriteTemplate = {
  name: 'telegraph_machine_16',
  width: 16,
  height: 16,
  description: 'Morse code telegraph machine with key arm.',
  regions: [
    { name: 'base', role: 'body', pixels: [
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5],
      [2,6], [3,6], [12,6], [13,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [6,8], [7,8], [8,8], [9,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'key_arm', role: 'head', pixels: [
      [6,2], [7,2], [8,2],
      [5,3], [6,3], [7,3], [8,3], [9,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
    ]},
    { name: 'mechanism', role: 'eye', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
    ]},
    { name: 'contacts', role: 'accessory', pixels: [
      [4,8], [5,8], [10,8],
    ]},
    { name: 'platform', role: 'leg', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OIL_LAMP — Vintage kerosene oil lamp with glass chimney.
// ════════════════════════════════════════════════════════════
export const OIL_LAMP_16: SpriteTemplate = {
  name: 'oil_lamp_16',
  width: 16,
  height: 16,
  description: 'Vintage kerosene oil lamp with glass chimney.',
  regions: [
    { name: 'chimney', role: 'head', pixels: [
      [7,0], [8,0],
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [5,3], [10,3],
      [5,4], [10,4],
      [5,5], [10,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
    ]},
    { name: 'flame', role: 'eye', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
      [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'reservoir', role: 'body', pixels: [
      [6,7], [7,7], [8,7], [9,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HOURGLASS — Classic hourglass sand timer.
// ════════════════════════════════════════════════════════════
export const HOURGLASS_16: SpriteTemplate = {
  name: 'hourglass_16',
  width: 16,
  height: 16,
  description: 'Classic hourglass sand timer.',
  regions: [
    { name: 'frame', role: 'body', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'sand_top', role: 'eye', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [6,5], [7,5], [8,5], [9,5],
      [7,6], [8,6],
    ]},
    { name: 'sand_bottom', role: 'head', pixels: [
      [7,7], [8,7],
      [6,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SPYGLASS — Brass spyglass / pirate telescope.
// ════════════════════════════════════════════════════════════
export const SPYGLASS_16: SpriteTemplate = {
  name: 'spyglass_16',
  width: 16,
  height: 16,
  description: 'Brass spyglass / pirate telescope.',
  regions: [
    { name: 'eyepiece', role: 'eye', pixels: [
      [2,5], [3,5], [4,5],
      [2,6], [3,6], [4,6], [5,6],
      [2,7], [3,7], [4,7], [5,7],
      [2,8], [3,8], [4,8],
    ]},
    { name: 'tube', role: 'body', pixels: [
      [6,5], [7,5], [8,5], [9,5], [10,5],
      [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [6,8], [7,8], [8,8], [9,8], [10,8],
    ]},
    { name: 'objective', role: 'head', pixels: [
      [11,5], [12,5], [13,5],
      [12,6], [13,6],
      [12,7], [13,7],
      [11,8], [12,8], [13,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// POCKET_WATCH — Vintage pocket watch with chain.
// ════════════════════════════════════════════════════════════
export const POCKET_WATCH_16: SpriteTemplate = {
  name: 'pocket_watch_16',
  width: 16,
  height: 16,
  description: 'Vintage pocket watch with chain.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [6,2], [7,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [3,4], [4,4], [9,4], [10,4],
      [3,5], [10,5],
      [3,6], [10,6],
      [3,7], [10,7],
      [3,8], [10,8],
      [3,9], [4,9], [9,9], [10,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'face', role: 'eye', pixels: [
      [5,4], [6,4], [7,4], [8,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [7,6], [8,6], [9,6],
      [4,7], [5,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9],
    ]},
    { name: 'crown', role: 'head', pixels: [
      [6,1], [7,1],
      [5,2], [8,2],
    ]},
    { name: 'hands', role: 'accessory', pixels: [
      [6,6],
      [6,7], [7,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MICROFICHE_READER — Library microfiche reader with screen.
// ════════════════════════════════════════════════════════════
export const MICROFICHE_READER_16: SpriteTemplate = {
  name: 'microfiche_reader_16',
  width: 16,
  height: 16,
  description: 'Library microfiche reader with screen.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [2,0], [3,0], [4,0], [5,0], [6,0], [7,0], [8,0], [9,0], [10,0], [11,0], [12,0], [13,0],
      [2,1], [12,1], [13,1],
      [2,2], [12,2], [13,2],
      [2,3], [12,3], [13,3],
      [2,4], [12,4], [13,4],
      [2,5], [12,5], [13,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [7,7], [8,7],
      [7,8], [8,8],
      [6,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'screen', role: 'eye', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [6,11], [7,11], [8,11], [9,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'tray', role: 'head', pixels: [
      [3,11], [4,11], [5,11], [10,11], [11,11], [12,11], [13,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// METRONOME — Wooden metronome for music tempo.
// ════════════════════════════════════════════════════════════
export const METRONOME_16: SpriteTemplate = {
  name: 'metronome_16',
  width: 16,
  height: 16,
  description: 'Wooden metronome for music tempo.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [6,3], [7,3],
      [5,4], [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7],
      [3,8], [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [11,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
    ]},
    { name: 'pendulum', role: 'eye', pixels: [
      [7,5],
      [7,6],
      [7,7],
      [7,8],
    ]},
    { name: 'weight', role: 'head', pixels: [
      [6,1], [7,1],
      [7,2], [8,2],
      [8,3], [9,3],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PENDULUM_CLOCK — Grandfather-style pendulum wall clock.
// ════════════════════════════════════════════════════════════
export const PENDULUM_CLOCK_16: SpriteTemplate = {
  name: 'pendulum_clock_16',
  width: 16,
  height: 16,
  description: 'Grandfather-style pendulum wall clock.',
  regions: [
    { name: 'case', role: 'body', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [4,3], [10,3], [11,3],
      [4,4], [10,4], [11,4],
      [4,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'face', role: 'eye', pixels: [
      [5,3], [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'hands', role: 'head', pixels: [
      [7,4],
    ]},
    { name: 'pendulum', role: 'accessory', pixels: [
      [7,8],
      [6,9], [7,9], [8,9],
      [7,10],
    ]},
    { name: 'base', role: 'leg', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const TUBE_RADIO_COLORS: ColorScheme = {
  name: 'tube_radio_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SCIENTIFIC_CALC_COLORS: ColorScheme = {
  name: 'scientific_calc_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const TRANSISTOR_RADIO_COLORS: ColorScheme = {
  name: 'transistor_radio_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const ANALOG_CLOCK_COLORS: ColorScheme = {
  name: 'analog_clock_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const LIGHT_BULB_COLORS: ColorScheme = {
  name: 'light_bulb_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const COMPASS_COLORS: ColorScheme = {
  name: 'compass_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SLIDE_RULE_COLORS: ColorScheme = {
  name: 'slide_rule_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CASSETTE_WALKMAN_COLORS: ColorScheme = {
  name: 'cassette_walkman_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
  },
};

export const DARKROOM_ENLARGER_COLORS: ColorScheme = {
  name: 'darkroom_enlarger_default',
  mapping: {
    head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const GRAMOPHONE_HORN_COLORS: ColorScheme = {
  name: 'gramophone_horn_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#595652', highlight: '#854c30' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SEXTANT_COLORS: ColorScheme = {
  name: 'sextant_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
  },
};

export const MAGIC_LANTERN_COLORS: ColorScheme = {
  name: 'magic_lantern_default',
  mapping: {
    head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
  },
};

export const TELEGRAPH_MACHINE_COLORS: ColorScheme = {
  name: 'telegraph_machine_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#595652', highlight: '#854c30' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const OIL_LAMP_COLORS: ColorScheme = {
  name: 'oil_lamp_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const HOURGLASS_COLORS: ColorScheme = {
  name: 'hourglass_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SPYGLASS_COLORS: ColorScheme = {
  name: 'spyglass_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const POCKET_WATCH_COLORS: ColorScheme = {
  name: 'pocket_watch_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
  },
};

export const MICROFICHE_READER_COLORS: ColorScheme = {
  name: 'microfiche_reader_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const METRONOME_COLORS: ColorScheme = {
  name: 'metronome_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const PENDULUM_CLOCK_COLORS: ColorScheme = {
  name: 'pendulum_clock_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const RETRO_TECH_BATCH3_TEMPLATES: Record<string, SpriteTemplate> = {
  tube_radio_16: TUBE_RADIO_16,
  scientific_calc_16: SCIENTIFIC_CALC_16,
  transistor_radio_16: TRANSISTOR_RADIO_16,
  analog_clock_16: ANALOG_CLOCK_16,
  light_bulb_16: LIGHT_BULB_16,
  compass_16: COMPASS_16,
  slide_rule_16: SLIDE_RULE_16,
  cassette_walkman_16: CASSETTE_WALKMAN_16,
  darkroom_enlarger_16: DARKROOM_ENLARGER_16,
  gramophone_horn_16: GRAMOPHONE_HORN_16,
  sextant_16: SEXTANT_16,
  magic_lantern_16: MAGIC_LANTERN_16,
  telegraph_machine_16: TELEGRAPH_MACHINE_16,
  oil_lamp_16: OIL_LAMP_16,
  hourglass_16: HOURGLASS_16,
  spyglass_16: SPYGLASS_16,
  pocket_watch_16: POCKET_WATCH_16,
  microfiche_reader_16: MICROFICHE_READER_16,
  metronome_16: METRONOME_16,
  pendulum_clock_16: PENDULUM_CLOCK_16,
};

export const RETRO_TECH_BATCH3_COLOR_SCHEMES: Record<string, ColorScheme> = {
  tube_radio_default: TUBE_RADIO_COLORS,
  scientific_calc_default: SCIENTIFIC_CALC_COLORS,
  transistor_radio_default: TRANSISTOR_RADIO_COLORS,
  analog_clock_default: ANALOG_CLOCK_COLORS,
  light_bulb_default: LIGHT_BULB_COLORS,
  compass_default: COMPASS_COLORS,
  slide_rule_default: SLIDE_RULE_COLORS,
  cassette_walkman_default: CASSETTE_WALKMAN_COLORS,
  darkroom_enlarger_default: DARKROOM_ENLARGER_COLORS,
  gramophone_horn_default: GRAMOPHONE_HORN_COLORS,
  sextant_default: SEXTANT_COLORS,
  magic_lantern_default: MAGIC_LANTERN_COLORS,
  telegraph_machine_default: TELEGRAPH_MACHINE_COLORS,
  oil_lamp_default: OIL_LAMP_COLORS,
  hourglass_default: HOURGLASS_COLORS,
  spyglass_default: SPYGLASS_COLORS,
  pocket_watch_default: POCKET_WATCH_COLORS,
  microfiche_reader_default: MICROFICHE_READER_COLORS,
  metronome_default: METRONOME_COLORS,
  pendulum_clock_default: PENDULUM_CLOCK_COLORS,
};
