/**
 * 16x16 vehicles templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-01.
 * 17 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// GRIFFIN_MOUNT — Mythical griffin flying mount.
// ════════════════════════════════════════════════════════════
export const GRIFFIN_MOUNT_16: SpriteTemplate = {
  name: 'griffin_mount_16',
  width: 16,
  height: 16,
  description: 'Mythical griffin flying mount.',
  regions: [
    { name: 'head', role: 'head', pixels: [
      [5,1], [6,1], [7,1],
      [4,2], [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [8,3],
      [4,4], [5,4], [6,4], [7,4], [8,4],
    ]},
    { name: 'eyes', role: 'eye', pixels: [
      [6,3], [7,3],
    ]},
    { name: 'body', role: 'body', pixels: [
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9],
      [3,10], [4,10], [5,10], [6,10], [8,10], [9,10], [10,10],
    ]},
    { name: 'wings', role: 'accessory', pixels: [
      [2,6], [3,6], [11,6],
      [2,7], [3,7], [11,7],
      [2,8], [3,8],
    ]},
    { name: 'claws', role: 'leg', pixels: [
      [3,11], [4,11], [6,11], [8,11], [10,11], [11,11],
      [3,12], [4,12], [6,12], [8,12], [10,12], [11,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WAR_MECH — Bipedal combat mech suit.
// ════════════════════════════════════════════════════════════
export const WAR_MECH_16: SpriteTemplate = {
  name: 'war_mech_16',
  width: 16,
  height: 16,
  description: 'Bipedal combat mech suit.',
  regions: [
    { name: 'cockpit', role: 'head', pixels: [
      [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [5,2], [10,2],
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
    ]},
    { name: 'visor', role: 'eye', pixels: [
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'torso', role: 'body', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
    { name: 'arms', role: 'accessory', pixels: [
      [2,5], [3,5], [12,5], [13,5],
      [2,6], [3,6], [12,6], [13,6],
      [2,7], [3,7],
    ]},
    { name: 'legs', role: 'leg', pixels: [
      [4,9], [5,9], [6,9], [8,9], [9,9], [10,9],
      [4,10], [5,10], [6,10], [8,10], [9,10], [10,10],
      [3,11], [4,11], [5,11], [9,11], [10,11], [11,11],
      [2,12], [3,12], [4,12], [5,12], [9,12], [10,12], [11,12], [12,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GIANT_TURTLE_MOUNT — Rideable giant sea turtle.
// ════════════════════════════════════════════════════════════
export const GIANT_TURTLE_MOUNT_16: SpriteTemplate = {
  name: 'giant_turtle_mount_16',
  width: 16,
  height: 16,
  description: 'Rideable giant sea turtle.',
  regions: [
    { name: 'head', role: 'head', pixels: [
      [3,2], [4,2], [5,2],
      [2,3], [3,3], [6,3],
      [2,4], [3,4], [4,4], [5,4], [6,4],
    ]},
    { name: 'shell_pattern', role: 'eye', pixels: [
      [4,3], [5,3],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
    ]},
    { name: 'shell', role: 'body', pixels: [
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [1,6], [2,6], [10,6], [11,6],
      [1,7], [2,7], [10,7], [11,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
    ]},
    { name: 'flippers', role: 'leg', pixels: [
      [2,10], [3,10], [9,10], [10,10],
      [2,11], [3,11], [4,11], [8,11], [9,11], [10,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HOVER_TANK — Futuristic hovering battle tank.
// ════════════════════════════════════════════════════════════
export const HOVER_TANK_16: SpriteTemplate = {
  name: 'hover_tank_16',
  width: 16,
  height: 16,
  description: 'Futuristic hovering battle tank.',
  regions: [
    { name: 'cannon', role: 'accessory', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'hull', role: 'body', pixels: [
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [2,6], [3,6], [9,6], [10,6], [11,6], [12,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
    ]},
    { name: 'viewport', role: 'eye', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6],
    ]},
    { name: 'hover_pad', role: 'head', pixels: [
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PARAGLIDER — Hang glider / paraglider wing.
// ════════════════════════════════════════════════════════════
export const PARAGLIDER_16: SpriteTemplate = {
  name: 'paraglider_16',
  width: 16,
  height: 16,
  description: 'Hang glider / paraglider wing.',
  regions: [
    { name: 'canopy', role: 'head', pixels: [
      [1,1], [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1], [14,1],
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
    ]},
    { name: 'lines', role: 'eye', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [5,5], [6,5], [7,5], [8,5], [9,5],
    ]},
    { name: 'harness', role: 'body', pixels: [
      [6,6], [7,6], [8,6],
      [6,7], [7,7], [8,7],
      [6,8], [7,8], [8,8],
    ]},
    { name: 'pilot', role: 'leg', pixels: [
      [6,9], [7,9], [8,9],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CARGO_SHIP — Large cargo container ship.
// ════════════════════════════════════════════════════════════
export const CARGO_SHIP_16: SpriteTemplate = {
  name: 'cargo_ship_16',
  width: 16,
  height: 16,
  description: 'Large cargo container ship.',
  regions: [
    { name: 'hull', role: 'body', pixels: [
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [1,9], [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'mast', role: 'head', pixels: [
      [7,3], [8,3],
      [7,4], [8,4],
      [7,5], [8,5],
    ]},
    { name: 'containers', role: 'accessory', pixels: [
      [2,6], [3,6], [4,6],
      [2,7], [3,7], [4,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MAGIC_BROOM — Witch/wizard flying broomstick with sparkles.
// ════════════════════════════════════════════════════════════
export const MAGIC_BROOM_16: SpriteTemplate = {
  name: 'magic_broom_16',
  width: 16,
  height: 16,
  description: 'Witch/wizard flying broomstick with sparkles.',
  regions: [
    { name: 'sparkles', role: 'accessory', pixels: [
      [2,5], [3,5],
      [2,6], [3,6],
      [2,9], [3,9],
      [2,10], [3,10],
    ]},
    { name: 'handle', role: 'body', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'bristles', role: 'head', pixels: [
      [11,7], [12,7], [13,7],
      [11,8], [12,8], [13,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// HOVER_SCOOTER — Futuristic hover scooter / space vespa.
// ════════════════════════════════════════════════════════════
export const HOVER_SCOOTER_16: SpriteTemplate = {
  name: 'hover_scooter_16',
  width: 16,
  height: 16,
  description: 'Futuristic hover scooter / space vespa.',
  regions: [
    { name: 'windshield', role: 'head', pixels: [
      [5,4], [6,4], [7,4], [8,4],
      [4,5], [5,5], [8,5], [9,5],
    ]},
    { name: 'body', role: 'body', pixels: [
      [6,5], [7,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
    { name: 'hover_pads', role: 'eye', pixels: [
      [2,9], [3,9], [4,9], [5,9], [9,9], [10,9], [11,9], [12,9],
      [2,10], [3,10], [4,10], [5,10], [9,10], [10,10], [11,10], [12,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WAR_GALLEON — Armored war galleon with cannons.
// ════════════════════════════════════════════════════════════
export const WAR_GALLEON_16: SpriteTemplate = {
  name: 'war_galleon_16',
  width: 16,
  height: 16,
  description: 'Armored war galleon with cannons.',
  regions: [
    { name: 'mast', role: 'head', pixels: [
      [7,1], [8,1],
      [7,2], [8,2],
      [6,3], [7,3], [8,3],
      [6,4], [7,4], [8,4],
    ]},
    { name: 'sails', role: 'accessory', pixels: [
      [3,3], [4,3], [5,3], [9,3], [10,3],
      [3,4], [4,4], [5,4], [9,4], [10,4],
      [2,6], [3,6], [11,6], [12,6],
    ]},
    { name: 'hull', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MONSTER_TRUCK — Huge monster truck with oversized wheels.
// ════════════════════════════════════════════════════════════
export const MONSTER_TRUCK_16: SpriteTemplate = {
  name: 'monster_truck_16',
  width: 16,
  height: 16,
  description: 'Huge monster truck with oversized wheels.',
  regions: [
    { name: 'body', role: 'body', pixels: [
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
    ]},
    { name: 'cabin', role: 'head', pixels: [
      [6,2], [7,2], [8,2], [9,2],
      [5,3], [6,3], [9,3], [10,3],
    ]},
    { name: 'window', role: 'eye', pixels: [
      [7,3], [8,3],
    ]},
    { name: 'wheels', role: 'leg', pixels: [
      [1,7], [2,7], [3,7], [4,7], [5,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [1,9], [2,9], [3,9], [4,9], [5,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [1,10], [2,10], [3,10], [4,10], [5,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [10,11], [11,11], [12,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DRAGON_BOAT — Ornate dragon boat with dragon head prow.
// ════════════════════════════════════════════════════════════
export const DRAGON_BOAT_16: SpriteTemplate = {
  name: 'dragon_boat_16',
  width: 16,
  height: 16,
  description: 'Ornate dragon boat with dragon head prow.',
  regions: [
    { name: 'dragon_head', role: 'head', pixels: [
      [3,2], [4,2],
      [2,3], [3,3], [4,3], [5,3],
      [2,4], [5,4],
      [3,5], [4,5],
    ]},
    { name: 'eyes', role: 'eye', pixels: [
      [3,4], [4,4],
    ]},
    { name: 'hull', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [1,6], [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'tail', role: 'accessory', pixels: [
      [14,7],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SPACE_POD — Small single-person escape pod / shuttle pod.
// ════════════════════════════════════════════════════════════
export const SPACE_POD_16: SpriteTemplate = {
  name: 'space_pod_16',
  width: 16,
  height: 16,
  description: 'Small single-person escape pod / shuttle pod.',
  regions: [
    { name: 'canopy', role: 'head', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [4,3], [5,3], [10,3], [11,3],
      [4,4], [5,4], [10,4], [11,4],
    ]},
    { name: 'viewport', role: 'eye', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'hull', role: 'body', pixels: [
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'thrusters', role: 'leg', pixels: [
      [3,10], [4,10], [5,10], [6,10], [9,10], [10,10], [11,10], [12,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OX_CART — Medieval ox-drawn wooden cart.
// ════════════════════════════════════════════════════════════
export const OX_CART_16: SpriteTemplate = {
  name: 'ox_cart_16',
  width: 16,
  height: 16,
  description: 'Medieval ox-drawn wooden cart.',
  regions: [
    { name: 'ox', role: 'head', pixels: [
      [2,4], [3,4], [4,4],
      [2,5], [3,5], [4,5], [5,5], [6,5],
      [2,6], [5,6],
      [2,7], [3,7], [4,7], [5,7],
    ]},
    { name: 'ox_eyes', role: 'eye', pixels: [
      [3,6], [4,6],
    ]},
    { name: 'cart', role: 'body', pixels: [
      [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [7,9], [9,9], [10,9], [11,9], [13,9],
      [10,10],
    ]},
    { name: 'wheels', role: 'leg', pixels: [
      [8,9], [12,9],
      [7,10], [8,10], [9,10], [11,10], [12,10], [13,10],
      [7,11], [8,11], [9,11], [11,11], [12,11], [13,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SNOWPLOW — Snow plow truck for clearing roads.
// ════════════════════════════════════════════════════════════
export const SNOWPLOW_16: SpriteTemplate = {
  name: 'snowplow_16',
  width: 16,
  height: 16,
  description: 'Snow plow truck for clearing roads.',
  regions: [
    { name: 'body', role: 'body', pixels: [
      [4,6], [5,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [4,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [13,9],
      [7,10], [8,10], [10,10],
    ]},
    { name: 'cabin', role: 'head', pixels: [
      [5,4], [6,4], [7,4], [8,4],
      [4,5], [5,5], [8,5], [9,5],
    ]},
    { name: 'window', role: 'eye', pixels: [
      [6,5], [7,5],
      [6,6], [7,6],
    ]},
    { name: 'plow', role: 'accessory', pixels: [
      [2,6], [3,6],
      [2,7], [3,7],
      [2,8], [3,8],
      [2,9], [3,9],
    ]},
    { name: 'wheels', role: 'leg', pixels: [
      [5,9], [12,9],
      [4,10], [5,10], [6,10], [11,10], [12,10], [13,10],
      [4,11], [5,11], [6,11], [11,11], [12,11], [13,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MAGIC_CARPET_DELUXE — Ornate flying carpet with tassels.
// ════════════════════════════════════════════════════════════
export const MAGIC_CARPET_DELUXE_16: SpriteTemplate = {
  name: 'magic_carpet_deluxe_16',
  width: 16,
  height: 16,
  description: 'Ornate flying carpet with tassels.',
  regions: [
    { name: 'border', role: 'body', pixels: [
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [1,6], [12,6], [13,6],
      [1,7], [12,7], [13,7],
      [1,8], [12,8], [13,8],
      [1,9], [12,9], [13,9],
      [1,10], [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10], [14,10],
    ]},
    { name: 'pattern', role: 'eye', pixels: [
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [2,7], [3,7], [5,7], [8,7], [10,7], [11,7],
      [2,8], [3,8], [5,8], [8,8], [10,8], [11,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'tassels', role: 'head', pixels: [
      [4,7], [6,7], [7,7], [9,7],
      [4,8], [6,8], [7,8], [9,8],
      [1,11], [2,11], [4,11], [5,11], [10,11], [11,11], [13,11], [14,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MECHABIRD_MOUNT — Steampunk mechanical bird mount.
// ════════════════════════════════════════════════════════════
export const MECHABIRD_MOUNT_16: SpriteTemplate = {
  name: 'mechabird_mount_16',
  width: 16,
  height: 16,
  description: 'Steampunk mechanical bird mount.',
  regions: [
    { name: 'head', role: 'head', pixels: [
      [5,1], [6,1], [7,1], [8,1],
      [4,2], [5,2], [6,2], [7,2], [8,2],
      [4,3], [5,3], [8,3],
      [4,4], [5,4], [6,4], [7,4], [8,4],
    ]},
    { name: 'eyes', role: 'eye', pixels: [
      [6,3], [7,3],
    ]},
    { name: 'body', role: 'body', pixels: [
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [3,9], [4,9], [5,9], [7,9], [8,9], [9,9],
    ]},
    { name: 'wings', role: 'accessory', pixels: [
      [2,6], [3,6], [11,6],
      [2,7], [3,7], [11,7],
    ]},
    { name: 'legs', role: 'leg', pixels: [
      [3,10], [4,10], [8,10], [9,10],
      [3,11], [4,11], [8,11], [9,11],
      [2,12], [3,12], [4,12], [7,12], [8,12], [9,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SAND_WORM_MOUNT — Giant desert sand worm mount.
// ════════════════════════════════════════════════════════════
export const SAND_WORM_MOUNT_16: SpriteTemplate = {
  name: 'sand_worm_mount_16',
  width: 16,
  height: 16,
  description: 'Giant desert sand worm mount.',
  regions: [
    { name: 'head', role: 'head', pixels: [
      [2,2], [3,2], [4,2], [5,2],
      [1,3], [2,3], [3,3], [4,3], [5,3], [6,3],
      [1,4], [4,4], [5,4], [6,4],
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5],
    ]},
    { name: 'eyes', role: 'eye', pixels: [
      [2,4], [3,4],
    ]},
    { name: 'body', role: 'body', pixels: [
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'tail', role: 'leg', pixels: [
      [8,12], [9,12], [10,12], [11,12], [12,12],
      [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const GRIFFIN_MOUNT_COLORS: ColorScheme = {
  name: 'griffin_mount_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const WAR_MECH_COLORS: ColorScheme = {
  name: 'war_mech_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
  },
};

export const GIANT_TURTLE_MOUNT_COLORS: ColorScheme = {
  name: 'giant_turtle_mount_default',
  mapping: {
    head:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const HOVER_TANK_COLORS: ColorScheme = {
  name: 'hover_tank_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
  },
};

export const PARAGLIDER_COLORS: ColorScheme = {
  name: 'paraglider_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const CARGO_SHIP_COLORS: ColorScheme = {
  name: 'cargo_ship_default',
  mapping: {
    head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const MAGIC_BROOM_COLORS: ColorScheme = {
  name: 'magic_broom_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d04648', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const HOVER_SCOOTER_COLORS: ColorScheme = {
  name: 'hover_scooter_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const WAR_GALLEON_COLORS: ColorScheme = {
  name: 'war_galleon_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const MONSTER_TRUCK_COLORS: ColorScheme = {
  name: 'monster_truck_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const DRAGON_BOAT_COLORS: ColorScheme = {
  name: 'dragon_boat_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const SPACE_POD_COLORS: ColorScheme = {
  name: 'space_pod_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const OX_CART_COLORS: ColorScheme = {
  name: 'ox_cart_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const SNOWPLOW_COLORS: ColorScheme = {
  name: 'snowplow_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
  },
};

export const MAGIC_CARPET_DELUXE_COLORS: ColorScheme = {
  name: 'magic_carpet_deluxe_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const MECHABIRD_MOUNT_COLORS: ColorScheme = {
  name: 'mechabird_mount_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
  },
};

export const SAND_WORM_MOUNT_COLORS: ColorScheme = {
  name: 'sand_worm_mount_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const VEHICLE_BATCH4_TEMPLATES: Record<string, SpriteTemplate> = {
  griffin_mount_16: GRIFFIN_MOUNT_16,
  war_mech_16: WAR_MECH_16,
  giant_turtle_mount_16: GIANT_TURTLE_MOUNT_16,
  hover_tank_16: HOVER_TANK_16,
  paraglider_16: PARAGLIDER_16,
  cargo_ship_16: CARGO_SHIP_16,
  magic_broom_16: MAGIC_BROOM_16,
  hover_scooter_16: HOVER_SCOOTER_16,
  war_galleon_16: WAR_GALLEON_16,
  monster_truck_16: MONSTER_TRUCK_16,
  dragon_boat_16: DRAGON_BOAT_16,
  space_pod_16: SPACE_POD_16,
  ox_cart_16: OX_CART_16,
  snowplow_16: SNOWPLOW_16,
  magic_carpet_deluxe_16: MAGIC_CARPET_DELUXE_16,
  mechabird_mount_16: MECHABIRD_MOUNT_16,
  sand_worm_mount_16: SAND_WORM_MOUNT_16,
};

export const VEHICLE_BATCH4_COLOR_SCHEMES: Record<string, ColorScheme> = {
  griffin_mount_default: GRIFFIN_MOUNT_COLORS,
  war_mech_default: WAR_MECH_COLORS,
  giant_turtle_mount_default: GIANT_TURTLE_MOUNT_COLORS,
  hover_tank_default: HOVER_TANK_COLORS,
  paraglider_default: PARAGLIDER_COLORS,
  cargo_ship_default: CARGO_SHIP_COLORS,
  magic_broom_default: MAGIC_BROOM_COLORS,
  hover_scooter_default: HOVER_SCOOTER_COLORS,
  war_galleon_default: WAR_GALLEON_COLORS,
  monster_truck_default: MONSTER_TRUCK_COLORS,
  dragon_boat_default: DRAGON_BOAT_COLORS,
  space_pod_default: SPACE_POD_COLORS,
  ox_cart_default: OX_CART_COLORS,
  snowplow_default: SNOWPLOW_COLORS,
  magic_carpet_deluxe_default: MAGIC_CARPET_DELUXE_COLORS,
  mechabird_mount_default: MECHABIRD_MOUNT_COLORS,
  sand_worm_mount_default: SAND_WORM_MOUNT_COLORS,
};
