/**
 * 16x16 food templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-06.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// MANEKI_NEKO_YT — Lucky beckoning cat with raised paw, red collar and gold bell.
// ════════════════════════════════════════════════════════════
export const MANEKI_NEKO_YT_16: SpriteTemplate = {
  name: 'maneki_neko_yt_16',
  width: 16,
  height: 16,
  description: 'Lucky beckoning cat with raised paw, red collar and gold bell.',
  regions: [
    { name: 'white_fur', role: 'body', pixels: [
      [3,1], [4,1], [9,1], [10,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [2,3], [3,3], [5,3], [6,3], [7,3], [8,3], [10,3], [11,3],
      [2,4], [3,4], [5,4], [6,4], [7,4], [9,4], [10,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [3,6], [4,6], [5,6], [8,6], [9,6],
      [3,7], [8,7], [12,7],
      [3,8], [8,8], [12,8],
      [3,9], [8,9], [11,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [10,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [9,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12],
      [5,13], [6,13],
    ]},
    { name: 'ear_tips', role: 'head', pixels: [
      [2,1], [11,1],
      [2,2], [11,2],
    ]},
    { name: 'face_mark', role: 'hair', pixels: [
      [4,3], [9,3],
    ]},
    { name: 'eyes_nose', role: 'eye', pixels: [
      [4,4], [8,4],
    ]},
    { name: 'collar', role: 'belt', pixels: [
      [4,7], [5,7], [6,7], [7,7],
      [4,8], [6,8], [7,8],
      [4,9], [5,9], [6,9], [7,9],
    ]},
    { name: 'bell', role: 'accessory', pixels: [
      [5,8],
    ]},
    { name: 'raised_arm', role: 'arm', pixels: [
      [11,6], [12,6],
      [11,7],
      [11,8],
      [10,9],
      [9,10],
      [8,11],
    ]},
    { name: 'mouth', role: 'hand', pixels: [
      [6,6], [7,6],
    ]},
    { name: 'paws', role: 'boot', pixels: [
      [3,13], [4,13], [7,13], [8,13],
      [3,14], [4,14], [7,14], [8,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DARUMA_DOLL_YT — Red daruma wish doll, round body with one eye filled in.
// ════════════════════════════════════════════════════════════
export const DARUMA_DOLL_YT_16: SpriteTemplate = {
  name: 'daruma_doll_yt_16',
  width: 16,
  height: 16,
  description: 'Red daruma wish doll, round body with one eye filled in.',
  regions: [
    { name: 'gold_trim', role: 'accessory', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [11,4], [12,4],
      [3,5], [10,5], [12,5],
      [2,6], [3,6], [4,6], [11,6], [12,6], [13,6],
      [2,7], [13,7],
    ]},
    { name: 'face_area', role: 'head', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [8,5], [9,5], [11,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
    ]},
    { name: 'eye_dot', role: 'eye', pixels: [
      [7,5],
    ]},
    { name: 'red_body', role: 'body', pixels: [
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [2,9], [3,9], [4,9], [5,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'belly_kanji', role: 'belt', pixels: [
      [6,9], [7,9],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,14], [7,14], [8,14], [9,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// FURIN_CHIME_YT — Glass wind chime with clapper and paper strip hanging below.
// ════════════════════════════════════════════════════════════
export const FURIN_CHIME_YT_16: SpriteTemplate = {
  name: 'furin_chime_yt_16',
  width: 16,
  height: 16,
  description: 'Glass wind chime with clapper and paper strip hanging below.',
  regions: [
    { name: 'string_hook', role: 'accessory', pixels: [
      [7,1], [8,1],
      [7,2], [8,2],
    ]},
    { name: 'glass_bell', role: 'body', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
    ]},
    { name: 'painted_design', role: 'head', pixels: [
      [6,6], [7,6],
    ]},
    { name: 'clapper', role: 'belt', pixels: [
      [7,9], [8,9],
      [7,10], [8,10],
    ]},
    { name: 'paper_strip', role: 'arm', pixels: [
      [6,11], [7,11], [8,11], [9,11],
      [6,12], [8,12], [9,12],
      [6,13], [7,13], [8,13], [9,13],
      [6,14], [7,14], [8,14], [9,14],
      [7,15], [8,15],
    ]},
    { name: 'strip_kanji', role: 'eye', pixels: [
      [7,12],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MINI_TORII_YT — Small red torii gate decoration, two pillars with crossbeams.
// ════════════════════════════════════════════════════════════
export const MINI_TORII_YT_16: SpriteTemplate = {
  name: 'mini_torii_yt_16',
  width: 16,
  height: 16,
  description: 'Small red torii gate decoration, two pillars with crossbeams.',
  regions: [
    { name: 'red_beams', role: 'body', pixels: [
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [4,5], [5,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [9,7], [10,7], [11,7], [12,7],
    ]},
    { name: 'pillars', role: 'head', pixels: [
      [4,8], [5,8], [10,8], [11,8],
      [4,9], [5,9], [10,9], [11,9],
      [4,10], [5,10], [10,10], [11,10],
      [4,11], [5,11], [10,11], [11,11],
      [4,12], [5,12], [10,12], [11,12],
      [4,13], [5,13], [10,13], [11,13],
    ]},
    { name: 'pillar_base', role: 'boot', pixels: [
      [3,14], [4,14], [5,14], [6,14], [9,14], [10,14], [11,14], [12,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BAMBOO_FENCE_YT — Bamboo fence section with vertical poles and horizontal ties.
// ════════════════════════════════════════════════════════════
export const BAMBOO_FENCE_YT_16: SpriteTemplate = {
  name: 'bamboo_fence_yt_16',
  width: 16,
  height: 16,
  description: 'Bamboo fence section with vertical poles and horizontal ties.',
  regions: [
    { name: 'bamboo_poles', role: 'body', pixels: [
      [2,1], [3,1], [6,1], [7,1], [10,1], [11,1], [13,1],
      [2,2], [3,2], [6,2], [7,2], [10,2], [11,2], [13,2],
      [2,3], [3,3], [6,3], [7,3], [10,3], [11,3], [13,3],
      [2,4], [3,4], [6,4], [7,4], [10,4], [11,4], [13,4],
      [2,6], [3,6], [6,6], [7,6], [10,6], [11,6], [13,6],
      [2,7], [3,7], [6,7], [7,7], [10,7], [11,7], [13,7],
      [2,8], [3,8], [6,8], [7,8], [10,8], [11,8], [13,8],
      [2,9], [3,9], [6,9], [7,9], [10,9], [11,9], [13,9],
      [2,11], [3,11], [6,11], [7,11], [10,11], [11,11], [13,11],
      [2,12], [3,12], [6,12], [7,12], [10,12], [11,12], [13,12],
      [2,13], [3,13], [6,13], [7,13], [10,13], [11,13], [13,13],
      [2,14], [3,14], [6,14], [7,14], [10,14], [11,14], [13,14],
    ]},
    { name: 'rope_ties', role: 'belt', pixels: [
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [1,10], [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10], [14,10],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// ISHI_DORO_YT — Stone garden lantern with cap, fire box and pedestal.
// ════════════════════════════════════════════════════════════
export const ISHI_DORO_YT_16: SpriteTemplate = {
  name: 'ishi_doro_yt_16',
  width: 16,
  height: 16,
  description: 'Stone garden lantern with cap, fire box and pedestal.',
  regions: [
    { name: 'cap_finial', role: 'head', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
    ]},
    { name: 'roof_cap', role: 'hair', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
    ]},
    { name: 'stone_frame', role: 'body', pixels: [
      [4,5], [5,5], [10,5], [11,5],
      [4,6], [5,6], [10,6], [11,6],
      [4,7], [5,7], [12,7],
      [4,8], [5,8], [12,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
    ]},
    { name: 'fire_box', role: 'accessory', pixels: [
      [6,5], [7,5], [9,5],
      [6,6], [7,6], [9,6],
      [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
    ]},
    { name: 'fire_glow', role: 'eye', pixels: [
      [8,5],
      [8,6],
    ]},
    { name: 'pedestal', role: 'leg', pixels: [
      [6,10], [7,10], [8,10], [9,10],
      [6,11], [7,11], [8,11], [9,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'base_stone', role: 'boot', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
      [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SAKURA_BRANCH_YT — Cherry blossom branch with pink flowers and dark bark.
// ════════════════════════════════════════════════════════════
export const SAKURA_BRANCH_YT_16: SpriteTemplate = {
  name: 'sakura_branch_yt_16',
  width: 16,
  height: 16,
  description: 'Cherry blossom branch with pink flowers and dark bark.',
  regions: [
    { name: 'branch_bark', role: 'body', pixels: [
      [2,4], [3,4],
      [3,5], [4,5], [5,5], [6,5],
      [4,6], [5,6], [6,6], [7,6], [8,6],
      [5,7], [6,7], [7,7], [8,7],
      [6,8], [7,8], [8,8],
      [7,9], [8,9], [9,9],
      [8,10], [9,10], [10,10],
      [9,11], [10,11], [11,11],
      [10,12], [11,12],
      [11,13], [12,13],
    ]},
    { name: 'blossom_petals', role: 'head', pixels: [
      [2,1], [3,1],
      [1,2], [3,2], [4,2], [8,2], [9,2],
      [1,3], [2,3], [3,3], [7,3], [9,3], [10,3],
      [6,4], [7,4], [8,4], [9,4],
      [8,5], [9,5],
      [11,7], [12,7],
      [10,8], [12,8], [13,8],
      [10,9], [11,9], [12,9], [13,9],
      [12,10], [13,10],
    ]},
    { name: 'flower_center', role: 'accessory', pixels: [
      [2,2],
      [8,3],
      [11,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MATSURI_BANNER_YT — Festival banner on a pole, fabric with kanji lettering.
// ════════════════════════════════════════════════════════════
export const MATSURI_BANNER_YT_16: SpriteTemplate = {
  name: 'matsuri_banner_yt_16',
  width: 16,
  height: 16,
  description: 'Festival banner on a pole, fabric with kanji lettering.',
  regions: [
    { name: 'pole', role: 'body', pixels: [
      [2,0], [3,0],
      [2,1], [3,1],
      [2,2], [3,2],
      [2,3], [3,3],
      [2,4], [3,4],
      [2,5], [3,5],
      [2,6], [3,6],
      [2,7], [3,7],
      [2,8], [3,8],
      [2,9], [3,9],
      [2,10], [3,10],
      [2,11], [3,11],
      [2,12], [3,12],
      [2,13], [3,13],
      [2,14], [3,14],
    ]},
    { name: 'banner_fabric', role: 'head', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1], [14,1],
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2], [14,2],
      [4,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3], [14,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4], [14,4],
      [4,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5], [14,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6], [14,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7], [14,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8], [14,8],
      [4,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9], [14,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10], [14,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [13,11], [14,11],
    ]},
    { name: 'kanji_text', role: 'eye', pixels: [
      [5,3], [6,3],
      [5,5], [6,5],
      [5,9], [6,9],
    ]},
    { name: 'crest_emblem', role: 'accessory', pixels: [
      [11,11], [12,11],
    ]},
    { name: 'pole_base', role: 'boot', pixels: [
      [2,15], [3,15],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// EMA_PLAQUE_YT — Wooden wish plaque with pentagonal shape and hanging string.
// ════════════════════════════════════════════════════════════
export const EMA_PLAQUE_YT_16: SpriteTemplate = {
  name: 'ema_plaque_yt_16',
  width: 16,
  height: 16,
  description: 'Wooden wish plaque with pentagonal shape and hanging string.',
  regions: [
    { name: 'hanging_string', role: 'accessory', pixels: [
      [6,1], [7,1],
      [6,2], [7,2],
    ]},
    { name: 'roof_shape', role: 'head', pixels: [
      [7,3], [8,3],
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
    ]},
    { name: 'wood_body', role: 'body', pixels: [
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'written_wish', role: 'eye', pixels: [
      [5,9], [6,9],
      [5,11], [6,11],
    ]},
    { name: 'bottom_edge', role: 'boot', pixels: [
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OMAMORI_YT — Protection charm amulet, small embroidered fabric pouch with tassel.
// ════════════════════════════════════════════════════════════
export const OMAMORI_YT_16: SpriteTemplate = {
  name: 'omamori_yt_16',
  width: 16,
  height: 16,
  description: 'Protection charm amulet, small embroidered fabric pouch with tassel.',
  regions: [
    { name: 'loop_string', role: 'accessory', pixels: [
      [6,1], [7,1],
      [6,2], [7,2],
    ]},
    { name: 'gold_knot', role: 'head', pixels: [
      [5,3], [6,3], [7,3], [8,3],
    ]},
    { name: 'fabric_body', role: 'body', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [8,6], [9,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [4,9], [5,9], [8,9], [9,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11],
      [5,12], [6,12], [7,12], [8,12],
    ]},
    { name: 'kanji_embroidery', role: 'eye', pixels: [
      [6,6], [7,6],
      [6,9], [7,9],
    ]},
    { name: 'tassel', role: 'belt', pixels: [
      [6,13], [7,13],
      [5,14], [6,14], [7,14], [8,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SENSU_FAN_YT — Partially open folding fan with decorative pattern and bamboo ribs.
// ════════════════════════════════════════════════════════════
export const SENSU_FAN_YT_16: SpriteTemplate = {
  name: 'sensu_fan_yt_16',
  width: 16,
  height: 16,
  description: 'Partially open folding fan with decorative pattern and bamboo ribs.',
  regions: [
    { name: 'fan_paper', role: 'body', pixels: [
      [3,2], [4,2], [5,2], [6,2], [7,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [1,5], [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [1,6], [2,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6], [14,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7], [14,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [13,8], [14,8],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [13,10],
    ]},
    { name: 'fan_design', role: 'head', pixels: [
      [3,6],
      [7,7],
    ]},
    { name: 'bamboo_ribs', role: 'accessory', pixels: [
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [13,9],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
    ]},
    { name: 'handle', role: 'belt', pixels: [
      [12,12], [13,12],
      [13,13], [14,13],
      [14,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WAGASA_YT — Paper umbrella seen from above, circular with radiating ribs.
// ════════════════════════════════════════════════════════════
export const WAGASA_YT_16: SpriteTemplate = {
  name: 'wagasa_yt_16',
  width: 16,
  height: 16,
  description: 'Paper umbrella seen from above, circular with radiating ribs.',
  regions: [
    { name: 'paper_panels', role: 'body', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [2,3], [3,3], [4,3], [6,3], [7,3], [8,3], [9,3], [11,3], [12,3], [13,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [1,5], [2,5], [3,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [12,5], [13,5], [14,5],
      [1,6], [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [1,7], [2,7], [3,7], [4,7], [5,7], [6,7], [9,7], [10,7], [11,7], [12,7], [13,7], [14,7],
      [1,8], [2,8], [3,8], [4,8], [5,8], [6,8], [9,8], [10,8], [11,8], [12,8], [13,8], [14,8],
      [1,9], [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [1,10], [2,10], [3,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [12,10], [13,10], [14,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [2,12], [3,12], [4,12], [6,12], [7,12], [8,12], [9,12], [11,12], [12,12], [13,12],
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
      [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14],
    ]},
    { name: 'bamboo_ribs', role: 'accessory', pixels: [
      [5,3], [10,3],
      [4,5], [11,5],
      [4,10], [11,10],
      [5,12], [10,12],
    ]},
    { name: 'center_hub', role: 'head', pixels: [
      [7,7], [8,7],
      [7,8], [8,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OKE_BUCKET_YT — Wooden bucket with metal bands and rope handle.
// ════════════════════════════════════════════════════════════
export const OKE_BUCKET_YT_16: SpriteTemplate = {
  name: 'oke_bucket_yt_16',
  width: 16,
  height: 16,
  description: 'Wooden bucket with metal bands and rope handle.',
  regions: [
    { name: 'rope_handle', role: 'accessory', pixels: [
      [3,2], [4,2], [11,2], [12,2],
      [4,3], [5,3], [10,3], [11,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
    ]},
    { name: 'wood_staves', role: 'body', pixels: [
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'metal_bands', role: 'belt', pixels: [
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
    ]},
    { name: 'bottom_base', role: 'boot', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MENU_BOARD_YT — Chalk menu board with wooden frame and written items.
// ════════════════════════════════════════════════════════════
export const MENU_BOARD_YT_16: SpriteTemplate = {
  name: 'menu_board_yt_16',
  width: 16,
  height: 16,
  description: 'Chalk menu board with wooden frame and written items.',
  regions: [
    { name: 'wood_frame', role: 'body', pixels: [
      [2,1], [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1], [13,1],
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2],
      [2,3], [3,3], [12,3], [13,3],
      [2,4], [3,4], [12,4], [13,4],
      [2,5], [3,5], [12,5], [13,5],
      [2,6], [3,6], [12,6], [13,6],
      [2,7], [3,7], [12,7], [13,7],
      [2,8], [3,8], [12,8], [13,8],
      [2,9], [3,9], [12,9], [13,9],
      [2,10], [3,10], [12,10], [13,10],
      [2,11], [3,11], [12,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
      [2,13], [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13], [13,13],
    ]},
    { name: 'chalkboard', role: 'head', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [4,4], [5,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'chalk_text', role: 'eye', pixels: [
      [6,4], [7,4],
      [6,6], [7,6], [8,6], [9,6],
      [6,8], [7,8],
      [6,10], [7,10], [8,10], [9,10],
    ]},
    { name: 'chalk_piece', role: 'accessory', pixels: [
      [6,14], [7,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// KOBAN_COIN_YT — Oval gold koban coin with stamped markings.
// ════════════════════════════════════════════════════════════
export const KOBAN_COIN_YT_16: SpriteTemplate = {
  name: 'koban_coin_yt_16',
  width: 16,
  height: 16,
  description: 'Oval gold koban coin with stamped markings.',
  regions: [
    { name: 'coin_edge', role: 'body', pixels: [
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [4,4], [5,4], [10,4], [11,4],
      [3,5], [11,5], [12,5],
      [3,6], [12,6],
      [3,7], [12,7],
      [3,8], [12,8],
      [3,9], [12,9],
      [3,10], [11,10], [12,10],
      [4,11], [5,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'gold_face', role: 'head', pixels: [
      [6,4], [7,4], [8,4], [9,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [6,11], [7,11], [8,11], [9,11],
    ]},
    { name: 'stamp_mark', role: 'eye', pixels: [
      [7,7], [8,7],
      [7,8], [8,8],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TANUKI_STATUE_YT — Tanuki raccoon dog statue with straw hat and big belly.
// ════════════════════════════════════════════════════════════
export const TANUKI_STATUE_YT_16: SpriteTemplate = {
  name: 'tanuki_statue_yt_16',
  width: 16,
  height: 16,
  description: 'Tanuki raccoon dog statue with straw hat and big belly.',
  regions: [
    { name: 'straw_hat', role: 'hair', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
    ]},
    { name: 'fur_body', role: 'body', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4],
      [3,5], [4,5], [5,5], [7,5], [8,5], [9,5], [10,5],
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [3,7], [4,7], [9,7], [10,7],
      [3,8], [4,8], [9,8], [10,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [3,11], [4,11], [9,11], [10,11],
      [3,12], [4,12], [9,12], [10,12],
    ]},
    { name: 'eyes', role: 'eye', pixels: [
      [6,5],
    ]},
    { name: 'belly_patch', role: 'head', pixels: [
      [5,7], [6,7], [7,7], [8,7],
      [5,8], [6,8], [7,8], [8,8],
    ]},
    { name: 'sake_bottle', role: 'accessory', pixels: [
      [10,6], [11,6],
      [11,7],
    ]},
    { name: 'legs_base', role: 'boot', pixels: [
      [5,11], [6,11], [7,11], [8,11],
      [5,12], [6,12], [7,12], [8,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// KOINOBORI_YT — Carp wind sock streamer on a pole, fish body with open mouth.
// ════════════════════════════════════════════════════════════
export const KOINOBORI_YT_16: SpriteTemplate = {
  name: 'koinobori_yt_16',
  width: 16,
  height: 16,
  description: 'Carp wind sock streamer on a pole, fish body with open mouth.',
  regions: [
    { name: 'pole', role: 'accessory', pixels: [
      [0,0], [1,0],
      [0,1], [1,1],
      [0,2], [1,2],
      [0,3], [1,3],
      [0,4], [1,4],
      [0,5], [1,5],
      [0,6], [1,6],
      [0,7], [1,7],
      [0,8], [1,8],
      [0,9], [1,9],
      [0,10], [1,10],
      [0,11], [1,11],
      [0,12], [1,12],
      [0,13], [1,13],
      [0,14], [1,14],
    ]},
    { name: 'fish_head', role: 'head', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
    ]},
    { name: 'eye_mouth', role: 'eye', pixels: [
      [3,2], [4,2],
      [3,3],
      [3,4], [4,4],
      [3,5],
    ]},
    { name: 'fish_body', role: 'body', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
    ]},
    { name: 'tail_fin', role: 'arm', pixels: [
      [13,3],
      [13,4], [14,4],
      [14,5], [15,5],
      [14,6],
      [14,7],
      [13,8], [14,8],
      [13,9], [14,9],
      [14,10],
    ]},
    { name: 'lower_fin', role: 'belt', pixels: [
      [3,8],
      [3,9], [4,9],
      [3,10], [4,10],
      [3,11],
    ]},
    { name: 'pole_base', role: 'boot', pixels: [
      [0,15], [1,15],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SHAMISEN_YT — Three-stringed traditional instrument with long neck and square body.
// ════════════════════════════════════════════════════════════
export const SHAMISEN_YT_16: SpriteTemplate = {
  name: 'shamisen_yt_16',
  width: 16,
  height: 16,
  description: 'Three-stringed traditional instrument with long neck and square body.',
  regions: [
    { name: 'tuning_pegs', role: 'head', pixels: [
      [1,0], [2,0],
      [2,1], [3,1],
      [3,2], [4,2],
      [4,3],
      [5,4],
      [5,5],
      [5,6],
      [6,7],
      [6,8],
    ]},
    { name: 'neck_wood', role: 'body', pixels: [
      [2,2],
      [2,3],
      [3,4],
      [3,5],
      [3,6],
      [4,7],
      [4,8],
      [4,9],
      [3,10],
    ]},
    { name: 'strings', role: 'accessory', pixels: [
      [3,3],
      [4,4],
      [4,5],
      [4,6],
      [5,7],
      [5,8],
      [5,9],
      [4,10],
      [3,11], [4,11],
      [3,12], [4,12],
      [4,13], [5,13],
      [5,14], [6,14],
      [6,15], [7,15], [8,15],
    ]},
    { name: 'body_resonator', role: 'arm', pixels: [
      [6,9], [7,9],
      [5,10], [6,10], [7,10], [8,10], [9,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
      [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
      [7,14], [8,14], [9,14], [10,14], [11,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// GETA_SANDALS_YT — Pair of wooden geta clogs seen from above with fabric straps.
// ════════════════════════════════════════════════════════════
export const GETA_SANDALS_YT_16: SpriteTemplate = {
  name: 'geta_sandals_yt_16',
  width: 16,
  height: 16,
  description: 'Pair of wooden geta clogs seen from above with fabric straps.',
  regions: [
    { name: 'wood_platform', role: 'body', pixels: [
      [2,3], [3,3], [4,3], [5,3], [6,3], [8,3], [9,3], [10,3], [11,3], [12,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [2,5], [4,5], [5,5], [6,5], [8,5], [10,5], [11,5], [12,5],
      [5,6], [6,6], [11,6], [12,6],
      [2,7], [3,7], [5,7], [6,7], [8,7], [9,7], [11,7], [12,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [2,12], [3,12], [4,12], [5,12], [6,12], [8,12], [9,12], [10,12], [11,12], [12,12],
    ]},
    { name: 'fabric_strap', role: 'head', pixels: [
      [3,5], [9,5],
      [2,6], [3,6], [4,6], [8,6], [9,6], [10,6],
      [4,7], [10,7],
    ]},
    { name: 'base_teeth', role: 'boot', pixels: [
      [2,11], [3,11], [4,11], [5,11], [6,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TEA_SET_YT — Tea ceremony set with teapot and cup on a wooden tray.
// ════════════════════════════════════════════════════════════
export const TEA_SET_YT_16: SpriteTemplate = {
  name: 'tea_set_yt_16',
  width: 16,
  height: 16,
  description: 'Tea ceremony set with teapot and cup on a wooden tray.',
  regions: [
    { name: 'pot_lid_knob', role: 'accessory', pixels: [
      [6,3], [7,3],
    ]},
    { name: 'teapot', role: 'body', pixels: [
      [5,4], [6,4], [7,4], [8,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8],
      [5,9], [6,9], [7,9], [8,9],
    ]},
    { name: 'pot_handle', role: 'arm', pixels: [
      [3,6],
      [3,7],
    ]},
    { name: 'pot_spout', role: 'hand', pixels: [
      [10,7],
    ]},
    { name: 'tray_surface', role: 'head', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [5,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [2,12], [3,12], [4,12], [5,12], [8,12], [9,12], [10,12], [11,12], [12,12],
      [2,13], [3,13], [4,13], [5,13], [8,13], [9,13], [10,13], [11,13], [12,13], [13,13],
    ]},
    { name: 'tea_cup', role: 'belt', pixels: [
      [6,11], [7,11],
      [6,12], [7,12],
      [6,13], [7,13],
    ]},
    { name: 'tray_base', role: 'boot', pixels: [
      [2,14], [3,14], [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14], [12,14], [13,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const MANEKI_NEKO_YT_COLORS: ColorScheme = {
  name: 'maneki_neko_yt_default',
  mapping: {
    head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
    body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
    belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const DARUMA_DOLL_YT_COLORS: ColorScheme = {
  name: 'daruma_doll_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const FURIN_CHIME_YT_COLORS: ColorScheme = {
  name: 'furin_chime_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
  },
};

export const MINI_TORII_YT_COLORS: ColorScheme = {
  name: 'mini_torii_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const BAMBOO_FENCE_YT_COLORS: ColorScheme = {
  name: 'bamboo_fence_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const ISHI_DORO_YT_COLORS: ColorScheme = {
  name: 'ishi_doro_yt_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
    accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
  },
};

export const SAKURA_BRANCH_YT_COLORS: ColorScheme = {
  name: 'sakura_branch_yt_default',
  mapping: {
    head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const MATSURI_BANNER_YT_COLORS: ColorScheme = {
  name: 'matsuri_banner_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const EMA_PLAQUE_YT_COLORS: ColorScheme = {
  name: 'ema_plaque_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
  },
};

export const OMAMORI_YT_COLORS: ColorScheme = {
  name: 'omamori_yt_default',
  mapping: {
    head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
  },
};

export const SENSU_FAN_YT_COLORS: ColorScheme = {
  name: 'sensu_fan_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const WAGASA_YT_COLORS: ColorScheme = {
  name: 'wagasa_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const OKE_BUCKET_YT_COLORS: ColorScheme = {
  name: 'oke_bucket_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const MENU_BOARD_YT_COLORS: ColorScheme = {
  name: 'menu_board_yt_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#346524', highlight: '#4e4a4e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
  },
};

export const KOBAN_COIN_YT_COLORS: ColorScheme = {
  name: 'koban_coin_yt_default',
  mapping: {
    head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const TANUKI_STATUE_YT_COLORS: ColorScheme = {
  name: 'tanuki_statue_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const KOINOBORI_YT_COLORS: ColorScheme = {
  name: 'koinobori_yt_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const SHAMISEN_YT_COLORS: ColorScheme = {
  name: 'shamisen_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
  },
};

export const GETA_SANDALS_YT_COLORS: ColorScheme = {
  name: 'geta_sandals_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const TEA_SET_YT_COLORS: ColorScheme = {
  name: 'tea_set_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
    arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const YATAI_BATCH5_TEMPLATES: Record<string, SpriteTemplate> = {
  maneki_neko_yt_16: MANEKI_NEKO_YT_16,
  daruma_doll_yt_16: DARUMA_DOLL_YT_16,
  furin_chime_yt_16: FURIN_CHIME_YT_16,
  mini_torii_yt_16: MINI_TORII_YT_16,
  bamboo_fence_yt_16: BAMBOO_FENCE_YT_16,
  ishi_doro_yt_16: ISHI_DORO_YT_16,
  sakura_branch_yt_16: SAKURA_BRANCH_YT_16,
  matsuri_banner_yt_16: MATSURI_BANNER_YT_16,
  ema_plaque_yt_16: EMA_PLAQUE_YT_16,
  omamori_yt_16: OMAMORI_YT_16,
  sensu_fan_yt_16: SENSU_FAN_YT_16,
  wagasa_yt_16: WAGASA_YT_16,
  oke_bucket_yt_16: OKE_BUCKET_YT_16,
  menu_board_yt_16: MENU_BOARD_YT_16,
  koban_coin_yt_16: KOBAN_COIN_YT_16,
  tanuki_statue_yt_16: TANUKI_STATUE_YT_16,
  koinobori_yt_16: KOINOBORI_YT_16,
  shamisen_yt_16: SHAMISEN_YT_16,
  geta_sandals_yt_16: GETA_SANDALS_YT_16,
  tea_set_yt_16: TEA_SET_YT_16,
};

export const YATAI_BATCH5_COLOR_SCHEMES: Record<string, ColorScheme> = {
  maneki_neko_yt_default: MANEKI_NEKO_YT_COLORS,
  daruma_doll_yt_default: DARUMA_DOLL_YT_COLORS,
  furin_chime_yt_default: FURIN_CHIME_YT_COLORS,
  mini_torii_yt_default: MINI_TORII_YT_COLORS,
  bamboo_fence_yt_default: BAMBOO_FENCE_YT_COLORS,
  ishi_doro_yt_default: ISHI_DORO_YT_COLORS,
  sakura_branch_yt_default: SAKURA_BRANCH_YT_COLORS,
  matsuri_banner_yt_default: MATSURI_BANNER_YT_COLORS,
  ema_plaque_yt_default: EMA_PLAQUE_YT_COLORS,
  omamori_yt_default: OMAMORI_YT_COLORS,
  sensu_fan_yt_default: SENSU_FAN_YT_COLORS,
  wagasa_yt_default: WAGASA_YT_COLORS,
  oke_bucket_yt_default: OKE_BUCKET_YT_COLORS,
  menu_board_yt_default: MENU_BOARD_YT_COLORS,
  koban_coin_yt_default: KOBAN_COIN_YT_COLORS,
  tanuki_statue_yt_default: TANUKI_STATUE_YT_COLORS,
  koinobori_yt_default: KOINOBORI_YT_COLORS,
  shamisen_yt_default: SHAMISEN_YT_COLORS,
  geta_sandals_yt_default: GETA_SANDALS_YT_COLORS,
  tea_set_yt_default: TEA_SET_YT_COLORS,
};
