/**
 * 16x16 food templates — generated batch.
 * Generated by templateGenerator.ts on 2026-04-06.
 * 20 templates.
 */

import { SpriteRegion, SpriteTemplate, ColorScheme } from './humanoid16.js';

// ════════════════════════════════════════════════════════════
// SAKE_TOKKURI_YT — Traditional ceramic sake tokkuri bottle with narrow neck and round body.
// ════════════════════════════════════════════════════════════
export const SAKE_TOKKURI_YT_16: SpriteTemplate = {
  name: 'sake_tokkuri_yt_16',
  width: 16,
  height: 16,
  description: 'Traditional ceramic sake tokkuri bottle with narrow neck and round body.',
  regions: [
    { name: 'neck', role: 'head', pixels: [
      [6,1], [7,1], [8,1], [9,1],
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'body_ceramic', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'glaze_shine', role: 'eye', pixels: [
      [7,9],
    ]},
    { name: 'base_rim', role: 'arm', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SAKE_OCHOKO_YT — Small ceramic sake cup (ochoko) filled with clear sake.
// ════════════════════════════════════════════════════════════
export const SAKE_OCHOKO_YT_16: SpriteTemplate = {
  name: 'sake_ochoko_yt_16',
  width: 16,
  height: 16,
  description: 'Small ceramic sake cup (ochoko) filled with clear sake.',
  regions: [
    { name: 'sake_liquid', role: 'head', pixels: [
      [6,5], [7,5], [8,5], [9,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
    ]},
    { name: 'cup_inner', role: 'body', pixels: [
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'liquid_shine', role: 'eye', pixels: [
      [7,9],
    ]},
    { name: 'cup_outer', role: 'arm', pixels: [
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'cup_base', role: 'boot', pixels: [
      [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BEER_MUG_YT — Draft beer mug with golden beer and thick foam head.
// ════════════════════════════════════════════════════════════
export const BEER_MUG_YT_16: SpriteTemplate = {
  name: 'beer_mug_yt_16',
  width: 16,
  height: 16,
  description: 'Draft beer mug with golden beer and thick foam head.',
  regions: [
    { name: 'foam_head', role: 'head', pixels: [
      [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
      [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3],
    ]},
    { name: 'beer_body', role: 'body', pixels: [
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [5,6], [6,6], [8,6], [9,6], [10,6], [11,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'beer_shine', role: 'eye', pixels: [
      [7,6],
    ]},
    { name: 'mug_handle', role: 'accessory', pixels: [
      [13,5],
      [12,6],
      [13,7],
      [13,8],
      [12,9],
    ]},
    { name: 'glass_base', role: 'arm', pixels: [
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// RAMUNE_BOTTLE_YT — Marble soda bottle with distinctive pinched waist and glass marble.
// ════════════════════════════════════════════════════════════
export const RAMUNE_BOTTLE_YT_16: SpriteTemplate = {
  name: 'ramune_bottle_yt_16',
  width: 16,
  height: 16,
  description: 'Marble soda bottle with distinctive pinched waist and glass marble.',
  regions: [
    { name: 'neck_glass', role: 'head', pixels: [
      [6,0], [7,0], [8,0], [9,0],
      [5,1], [6,1], [7,1], [8,1], [9,1], [10,1],
      [6,2], [7,2], [8,2], [9,2],
      [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
    ]},
    { name: 'marble', role: 'eye', pixels: [
      [6,3], [7,3],
    ]},
    { name: 'bottle_body', role: 'body', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'liquid_shine', role: 'accessory', pixels: [
      [7,11],
    ]},
    { name: 'bottle_base', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// YUNOMI_TEA_YT — Green tea in traditional yunomi cup with painted band.
// ════════════════════════════════════════════════════════════
export const YUNOMI_TEA_YT_16: SpriteTemplate = {
  name: 'yunomi_tea_yt_16',
  width: 16,
  height: 16,
  description: 'Green tea in traditional yunomi cup with painted band.',
  regions: [
    { name: 'tea_liquid', role: 'head', pixels: [
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
      [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4],
      [3,5], [4,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
    ]},
    { name: 'tea_shine', role: 'eye', pixels: [
      [5,5],
    ]},
    { name: 'cup_ceramic', role: 'body', pixels: [
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'painted_band', role: 'accessory', pixels: [
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
    ]},
    { name: 'cup_base', role: 'boot', pixels: [
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MATCHA_BOWL_YT — Matcha tea in wide chawan bowl with frothy surface.
// ════════════════════════════════════════════════════════════
export const MATCHA_BOWL_YT_16: SpriteTemplate = {
  name: 'matcha_bowl_yt_16',
  width: 16,
  height: 16,
  description: 'Matcha tea in wide chawan bowl with frothy surface.',
  regions: [
    { name: 'matcha_froth', role: 'head', pixels: [
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [2,5], [3,5], [4,5], [6,5], [7,5], [8,5], [10,5], [11,5], [12,5],
    ]},
    { name: 'froth_bubble', role: 'eye', pixels: [
      [5,5], [9,5],
    ]},
    { name: 'matcha_liquid', role: 'accessory', pixels: [
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
    ]},
    { name: 'bowl_ceramic', role: 'body', pixels: [
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'bowl_base', role: 'boot', pixels: [
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SOY_SAUCE_YT — Shoyu dispensing bottle with narrow spout and red cap.
// ════════════════════════════════════════════════════════════
export const SOY_SAUCE_YT_16: SpriteTemplate = {
  name: 'soy_sauce_yt_16',
  width: 16,
  height: 16,
  description: 'Shoyu dispensing bottle with narrow spout and red cap.',
  regions: [
    { name: 'red_cap', role: 'accessory', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'bottle_neck', role: 'head', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
    ]},
    { name: 'soy_body', role: 'body', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'label_mark', role: 'eye', pixels: [
      [7,9],
    ]},
    { name: 'bottle_base', role: 'arm', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// TONKATSU_SAUCE_YT — Brown tonkatsu sauce bottle with yellow label band.
// ════════════════════════════════════════════════════════════
export const TONKATSU_SAUCE_YT_16: SpriteTemplate = {
  name: 'tonkatsu_sauce_yt_16',
  width: 16,
  height: 16,
  description: 'Brown tonkatsu sauce bottle with yellow label band.',
  regions: [
    { name: 'bottle_cap', role: 'accessory', pixels: [
      [6,1], [7,1], [8,1], [9,1],
    ]},
    { name: 'bottle_neck', role: 'head', pixels: [
      [6,2], [7,2], [8,2], [9,2],
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
    ]},
    { name: 'sauce_body', role: 'body', pixels: [
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'label_band', role: 'arm', pixels: [
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'sauce_shine', role: 'eye', pixels: [
      [7,11],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// KEWPIE_MAYO_YT — Kewpie mayonnaise squeeze bottle with red net pattern and star tip.
// ════════════════════════════════════════════════════════════
export const KEWPIE_MAYO_YT_16: SpriteTemplate = {
  name: 'kewpie_mayo_yt_16',
  width: 16,
  height: 16,
  description: 'Kewpie mayonnaise squeeze bottle with red net pattern and star tip.',
  regions: [
    { name: 'squeeze_tip', role: 'head', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'cap_ring', role: 'accessory', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
    ]},
    { name: 'red_net', role: 'arm', pixels: [
      [4,5], [11,5],
      [4,6], [11,6],
      [4,7], [12,7],
      [4,8], [11,8],
      [4,9], [11,9],
      [4,10], [11,10],
      [4,11], [11,11],
    ]},
    { name: 'mayo_body', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [8,7], [9,7], [10,7], [11,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
    { name: 'label_shine', role: 'eye', pixels: [
      [7,7],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,14], [7,14], [8,14], [9,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CHILI_OIL_YT — Rayu chili oil jar with red oil and chili flakes visible.
// ════════════════════════════════════════════════════════════
export const CHILI_OIL_YT_16: SpriteTemplate = {
  name: 'chili_oil_yt_16',
  width: 16,
  height: 16,
  description: 'Rayu chili oil jar with red oil and chili flakes visible.',
  regions: [
    { name: 'jar_lid', role: 'head', pixels: [
      [5,2], [6,2], [7,2], [8,2], [9,2], [10,2],
      [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3],
    ]},
    { name: 'lid_band', role: 'accessory', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
    ]},
    { name: 'chili_oil', role: 'body', pixels: [
      [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [3,8], [4,8], [5,8], [7,8], [8,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9],
      [3,10], [4,10], [6,10], [7,10], [8,10], [9,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
    ]},
    { name: 'chili_flake', role: 'eye', pixels: [
      [6,8], [9,8],
      [5,10], [10,10],
    ]},
    { name: 'jar_glass', role: 'arm', pixels: [
      [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// WASABI_PASTE_YT — Wasabi paste tube with green body and white cap.
// ════════════════════════════════════════════════════════════
export const WASABI_PASTE_YT_16: SpriteTemplate = {
  name: 'wasabi_paste_yt_16',
  width: 16,
  height: 16,
  description: 'Wasabi paste tube with green body and white cap.',
  regions: [
    { name: 'tube_cap', role: 'head', pixels: [
      [1,2], [2,2],
      [1,3], [2,3], [3,3],
      [2,4], [3,4],
    ]},
    { name: 'tube_neck', role: 'accessory', pixels: [
      [4,4], [5,4],
      [3,5], [4,5], [5,5], [6,5], [7,5],
    ]},
    { name: 'tube_body', role: 'body', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [4,9], [5,9], [6,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9], [14,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'label_shine', role: 'eye', pixels: [
      [7,9],
    ]},
    { name: 'tube_crimp', role: 'boot', pixels: [
      [5,13], [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// PICKLED_GINGER_YT — Gari pickled ginger pile on a small ceramic plate.
// ════════════════════════════════════════════════════════════
export const PICKLED_GINGER_YT_16: SpriteTemplate = {
  name: 'pickled_ginger_yt_16',
  width: 16,
  height: 16,
  description: 'Gari pickled ginger pile on a small ceramic plate.',
  regions: [
    { name: 'ginger_slice', role: 'head', pixels: [
      [5,4], [6,4], [7,4], [8,4], [9,4], [10,4],
      [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5],
      [3,6], [4,6], [5,6], [7,6], [8,6], [9,6], [11,6], [12,6], [13,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8], [14,8],
      [2,9], [3,9], [4,9], [6,9], [7,9], [8,9], [9,9], [11,9], [12,9], [13,9],
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
    { name: 'ginger_fold', role: 'eye', pixels: [
      [6,6], [10,6],
      [5,9], [10,9],
    ]},
    { name: 'plate', role: 'body', pixels: [
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
    ]},
    { name: 'plate_base', role: 'boot', pixels: [
      [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// RICE_VINEGAR_YT — Rice vinegar bottle with pale yellow liquid and label.
// ════════════════════════════════════════════════════════════
export const RICE_VINEGAR_YT_16: SpriteTemplate = {
  name: 'rice_vinegar_yt_16',
  width: 16,
  height: 16,
  description: 'Rice vinegar bottle with pale yellow liquid and label.',
  regions: [
    { name: 'bottle_cap', role: 'accessory', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'bottle_neck', role: 'head', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'vinegar_body', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'label_band', role: 'arm', pixels: [
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [7,9], [8,9], [9,9], [10,9], [11,9],
    ]},
    { name: 'label_mark', role: 'eye', pixels: [
      [6,9],
    ]},
    { name: 'bottle_base', role: 'belt', pixels: [
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// MIRIN_BOTTLE_YT — Mirin cooking wine bottle with amber liquid and traditional label.
// ════════════════════════════════════════════════════════════
export const MIRIN_BOTTLE_YT_16: SpriteTemplate = {
  name: 'mirin_bottle_yt_16',
  width: 16,
  height: 16,
  description: 'Mirin cooking wine bottle with amber liquid and traditional label.',
  regions: [
    { name: 'bottle_cap', role: 'head', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'bottle_neck', role: 'accessory', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
    ]},
    { name: 'mirin_body', role: 'body', pixels: [
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'label_area', role: 'arm', pixels: [
      [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8],
      [4,9], [5,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10],
    ]},
    { name: 'kanji_mark', role: 'eye', pixels: [
      [6,9],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// DASHI_STOCK_YT — Dashi stock pot with lid and steam rising, kelp visible inside.
// ════════════════════════════════════════════════════════════
export const DASHI_STOCK_YT_16: SpriteTemplate = {
  name: 'dashi_stock_yt_16',
  width: 16,
  height: 16,
  description: 'Dashi stock pot with lid and steam rising, kelp visible inside.',
  regions: [
    { name: 'steam', role: 'accessory', pixels: [
      [4,0], [5,0], [6,0], [7,0],
      [3,1], [4,1], [5,1], [6,1],
    ]},
    { name: 'pot_lid', role: 'head', pixels: [
      [2,2], [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2], [13,2],
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
    ]},
    { name: 'dashi_liquid', role: 'body', pixels: [
      [2,4], [3,4], [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5],
      [2,6], [3,6], [4,6], [6,6], [7,6], [9,6], [10,6], [11,6], [12,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'kelp_piece', role: 'eye', pixels: [
      [5,6], [8,6],
      [7,8],
    ]},
    { name: 'pot_body', role: 'arm', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
    ]},
    { name: 'pot_base', role: 'boot', pixels: [
      [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// SENBEI_YT — Round rice cracker with soy sauce glaze and sesame seeds.
// ════════════════════════════════════════════════════════════
export const SENBEI_YT_16: SpriteTemplate = {
  name: 'senbei_yt_16',
  width: 16,
  height: 16,
  description: 'Round rice cracker with soy sauce glaze and sesame seeds.',
  regions: [
    { name: 'cracker_surface', role: 'head', pixels: [
      [5,3], [6,3], [7,3], [8,3], [9,3], [10,3],
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [2,6], [3,6], [4,6], [6,6], [7,6], [8,6], [9,6], [11,6], [12,6], [13,6], [14,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [4,8], [5,8], [7,8], [8,8], [9,8], [10,8], [12,8], [13,8], [14,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
    ]},
    { name: 'sesame_seed', role: 'eye', pixels: [
      [5,6], [10,6],
      [6,8], [11,8],
    ]},
    { name: 'cracker_edge', role: 'body', pixels: [
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [5,12], [6,12], [7,12], [8,12], [9,12], [10,12],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [6,13], [7,13], [8,13], [9,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// AMAZAKE_CUP_YT — Sweet sake (amazake) in traditional cup with ginger garnish.
// ════════════════════════════════════════════════════════════
export const AMAZAKE_CUP_YT_16: SpriteTemplate = {
  name: 'amazake_cup_yt_16',
  width: 16,
  height: 16,
  description: 'Sweet sake (amazake) in traditional cup with ginger garnish.',
  regions: [
    { name: 'ginger_garnish', role: 'accessory', pixels: [
      [6,2], [7,2],
      [5,3], [6,3], [7,3],
    ]},
    { name: 'amazake_liquid', role: 'head', pixels: [
      [4,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4],
      [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5],
      [3,6], [4,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6],
      [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7],
    ]},
    { name: 'liquid_shine', role: 'eye', pixels: [
      [5,6],
    ]},
    { name: 'cup_ceramic', role: 'body', pixels: [
      [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8],
      [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
      [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10],
      [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'cup_base', role: 'boot', pixels: [
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// CALPIS_BOTTLE_YT — Calpis/Calpico bottle with blue polka dot label and white body.
// ════════════════════════════════════════════════════════════
export const CALPIS_BOTTLE_YT_16: SpriteTemplate = {
  name: 'calpis_bottle_yt_16',
  width: 16,
  height: 16,
  description: 'Calpis/Calpico bottle with blue polka dot label and white body.',
  regions: [
    { name: 'bottle_cap', role: 'head', pixels: [
      [7,1], [8,1],
      [6,2], [7,2], [8,2], [9,2],
    ]},
    { name: 'bottle_neck', role: 'accessory', pixels: [
      [6,3], [7,3], [8,3], [9,3],
      [6,4], [7,4], [8,4], [9,4],
    ]},
    { name: 'bottle_body', role: 'body', pixels: [
      [5,5], [6,5], [7,5], [8,5], [9,5], [10,5],
      [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6],
      [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
      [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13],
    ]},
    { name: 'label_white', role: 'arm', pixels: [
      [4,7], [5,7], [6,7], [8,7], [9,7], [10,7], [11,7],
      [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [11,8],
      [4,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9],
      [4,10], [5,10], [6,10], [7,10], [8,10], [10,10], [11,10],
    ]},
    { name: 'polka_dot', role: 'eye', pixels: [
      [7,7],
      [10,8],
      [5,9],
      [9,10],
    ]},
    { name: 'base_shadow', role: 'boot', pixels: [
      [5,14], [6,14], [7,14], [8,14], [9,14], [10,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// OOLONG_TEA_YT — Oolong tea in tall glass with ice cubes visible.
// ════════════════════════════════════════════════════════════
export const OOLONG_TEA_YT_16: SpriteTemplate = {
  name: 'oolong_tea_yt_16',
  width: 16,
  height: 16,
  description: 'Oolong tea in tall glass with ice cubes visible.',
  regions: [
    { name: 'glass_wall', role: 'accessory', pixels: [
      [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2],
      [4,3], [7,3], [8,3], [11,3],
      [4,4], [7,4], [8,4], [11,4],
      [4,5], [7,5], [8,5], [11,5],
      [4,6], [11,6],
      [4,7], [11,7],
      [4,8], [11,8],
      [4,9], [11,9],
      [4,10], [11,10],
      [4,11], [11,11],
      [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12],
    ]},
    { name: 'ice_cube', role: 'eye', pixels: [
      [5,3], [6,3], [9,3], [10,3],
      [5,4], [6,4],
    ]},
    { name: 'tea_liquid', role: 'body', pixels: [
      [9,4], [10,4],
      [5,5], [6,5], [9,5], [10,5],
      [5,6], [6,6], [7,6], [8,6], [9,6], [10,6],
      [5,7], [6,7], [7,7], [8,7], [9,7], [10,7],
      [5,8], [6,8], [7,8], [8,8], [9,8], [10,8],
      [5,9], [6,9], [7,9], [8,9], [9,9], [10,9],
      [5,10], [6,10], [7,10], [8,10], [9,10], [10,10],
      [5,11], [6,11], [7,11], [8,11], [9,11], [10,11],
    ]},
    { name: 'glass_stem', role: 'arm', pixels: [
      [5,13], [6,13], [7,13], [8,13], [9,13], [10,13],
    ]},
    { name: 'glass_base', role: 'boot', pixels: [
      [6,14], [7,14], [8,14], [9,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// BARLEY_TEA_YT — Mugicha barley tea pitcher with handle and amber liquid.
// ════════════════════════════════════════════════════════════
export const BARLEY_TEA_YT_16: SpriteTemplate = {
  name: 'barley_tea_yt_16',
  width: 16,
  height: 16,
  description: 'Mugicha barley tea pitcher with handle and amber liquid.',
  regions: [
    { name: 'pitcher_rim', role: 'head', pixels: [
      [3,1], [4,1], [5,1], [6,1], [7,1], [8,1], [9,1], [10,1], [11,1], [12,1],
      [3,2], [4,2], [5,2], [6,2], [7,2], [8,2], [9,2], [10,2], [11,2], [12,2],
    ]},
    { name: 'tea_liquid', role: 'body', pixels: [
      [2,3], [3,3], [4,3], [5,3], [6,3], [7,3], [8,3], [9,3], [10,3], [11,3], [12,3], [13,3],
      [2,4], [3,4], [5,4], [6,4], [7,4], [8,4], [9,4], [10,4], [11,4], [12,4], [13,4],
      [2,5], [3,5], [4,5], [5,5], [6,5], [7,5], [8,5], [9,5], [10,5], [11,5], [12,5], [13,5],
      [2,6], [3,6], [4,6], [5,6], [6,6], [7,6], [8,6], [9,6], [10,6], [11,6], [12,6], [13,6],
      [2,7], [3,7], [4,7], [5,7], [6,7], [7,7], [8,7], [9,7], [10,7], [11,7], [12,7], [13,7],
      [2,8], [3,8], [4,8], [5,8], [6,8], [7,8], [8,8], [9,8], [10,8], [11,8], [12,8], [13,8],
      [2,9], [3,9], [4,9], [5,9], [6,9], [7,9], [8,9], [9,9], [10,9], [11,9], [12,9], [13,9],
    ]},
    { name: 'tea_shine', role: 'eye', pixels: [
      [4,4],
    ]},
    { name: 'pitcher_handle', role: 'accessory', pixels: [
      [14,5],
      [14,6],
      [14,7],
      [14,8],
    ]},
    { name: 'pitcher_body', role: 'arm', pixels: [
      [2,10], [3,10], [4,10], [5,10], [6,10], [7,10], [8,10], [9,10], [10,10], [11,10], [12,10], [13,10],
      [2,11], [3,11], [4,11], [5,11], [6,11], [7,11], [8,11], [9,11], [10,11], [11,11], [12,11], [13,11],
      [2,12], [3,12], [4,12], [5,12], [6,12], [7,12], [8,12], [9,12], [10,12], [11,12], [12,12], [13,12],
      [3,13], [4,13], [5,13], [6,13], [7,13], [8,13], [9,13], [10,13], [11,13], [12,13],
    ]},
    { name: 'pitcher_base', role: 'boot', pixels: [
      [4,14], [5,14], [6,14], [7,14], [8,14], [9,14], [10,14], [11,14],
    ]},
  ],
};

// ════════════════════════════════════════════════════════════
// COLOR SCHEMES
// ════════════════════════════════════════════════════════════

export const SAKE_TOKKURI_YT_COLORS: ColorScheme = {
  name: 'sake_tokkuri_yt_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const SAKE_OCHOKO_YT_COLORS: ColorScheme = {
  name: 'sake_ochoko_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const BEER_MUG_YT_COLORS: ColorScheme = {
  name: 'beer_mug_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const RAMUNE_BOTTLE_YT_COLORS: ColorScheme = {
  name: 'ramune_bottle_yt_default',
  mapping: {
    head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    accessory: { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
  },
};

export const YUNOMI_TEA_YT_COLORS: ColorScheme = {
  name: 'yunomi_tea_yt_default',
  mapping: {
    head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
  },
};

export const MATCHA_BOWL_YT_COLORS: ColorScheme = {
  name: 'matcha_bowl_yt_default',
  mapping: {
    head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const SOY_SAUCE_YT_COLORS: ColorScheme = {
  name: 'soy_sauce_yt_default',
  mapping: {
    head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    arm:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const TONKATSU_SAUCE_YT_COLORS: ColorScheme = {
  name: 'tonkatsu_sauce_yt_default',
  mapping: {
    head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
    accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
  },
};

export const KEWPIE_MAYO_YT_COLORS: ColorScheme = {
  name: 'kewpie_mayo_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#d2aa99' },
    accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
  },
};

export const CHILI_OIL_YT_COLORS: ColorScheme = {
  name: 'chili_oil_yt_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
    arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const WASABI_PASTE_YT_COLORS: ColorScheme = {
  name: 'wasabi_paste_yt_default',
  mapping: {
    head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
  },
};

export const PICKLED_GINGER_YT_COLORS: ColorScheme = {
  name: 'pickled_ginger_yt_default',
  mapping: {
    head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
    body:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const RICE_VINEGAR_YT_COLORS: ColorScheme = {
  name: 'rice_vinegar_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
    body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
  },
};

export const MIRIN_BOTTLE_YT_COLORS: ColorScheme = {
  name: 'mirin_bottle_yt_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const DASHI_STOCK_YT_COLORS: ColorScheme = {
  name: 'dashi_stock_yt_default',
  mapping: {
    head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
    body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
    arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
    accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
  },
};

export const SENBEI_YT_COLORS: ColorScheme = {
  name: 'senbei_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const AMAZAKE_CUP_YT_COLORS: ColorScheme = {
  name: 'amazake_cup_yt_default',
  mapping: {
    head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
    accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
  },
};

export const CALPIS_BOTTLE_YT_COLORS: ColorScheme = {
  name: 'calpis_bottle_yt_default',
  mapping: {
    head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
    body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#d2aa99' },
    accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
  },
};

export const OOLONG_TEA_YT_COLORS: ColorScheme = {
  name: 'oolong_tea_yt_default',
  mapping: {
    head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
    arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
  },
};

export const BARLEY_TEA_YT_COLORS: ColorScheme = {
  name: 'barley_tea_yt_default',
  mapping: {
    head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
    body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
    hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
    belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
    leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
    boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
    accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
  },
};

// ════════════════════════════════════════════════════════════
// EXPORTS
// ════════════════════════════════════════════════════════════

export const YATAI_BATCH3_TEMPLATES: Record<string, SpriteTemplate> = {
  sake_tokkuri_yt_16: SAKE_TOKKURI_YT_16,
  sake_ochoko_yt_16: SAKE_OCHOKO_YT_16,
  beer_mug_yt_16: BEER_MUG_YT_16,
  ramune_bottle_yt_16: RAMUNE_BOTTLE_YT_16,
  yunomi_tea_yt_16: YUNOMI_TEA_YT_16,
  matcha_bowl_yt_16: MATCHA_BOWL_YT_16,
  soy_sauce_yt_16: SOY_SAUCE_YT_16,
  tonkatsu_sauce_yt_16: TONKATSU_SAUCE_YT_16,
  kewpie_mayo_yt_16: KEWPIE_MAYO_YT_16,
  chili_oil_yt_16: CHILI_OIL_YT_16,
  wasabi_paste_yt_16: WASABI_PASTE_YT_16,
  pickled_ginger_yt_16: PICKLED_GINGER_YT_16,
  rice_vinegar_yt_16: RICE_VINEGAR_YT_16,
  mirin_bottle_yt_16: MIRIN_BOTTLE_YT_16,
  dashi_stock_yt_16: DASHI_STOCK_YT_16,
  senbei_yt_16: SENBEI_YT_16,
  amazake_cup_yt_16: AMAZAKE_CUP_YT_16,
  calpis_bottle_yt_16: CALPIS_BOTTLE_YT_16,
  oolong_tea_yt_16: OOLONG_TEA_YT_16,
  barley_tea_yt_16: BARLEY_TEA_YT_16,
};

export const YATAI_BATCH3_COLOR_SCHEMES: Record<string, ColorScheme> = {
  sake_tokkuri_yt_default: SAKE_TOKKURI_YT_COLORS,
  sake_ochoko_yt_default: SAKE_OCHOKO_YT_COLORS,
  beer_mug_yt_default: BEER_MUG_YT_COLORS,
  ramune_bottle_yt_default: RAMUNE_BOTTLE_YT_COLORS,
  yunomi_tea_yt_default: YUNOMI_TEA_YT_COLORS,
  matcha_bowl_yt_default: MATCHA_BOWL_YT_COLORS,
  soy_sauce_yt_default: SOY_SAUCE_YT_COLORS,
  tonkatsu_sauce_yt_default: TONKATSU_SAUCE_YT_COLORS,
  kewpie_mayo_yt_default: KEWPIE_MAYO_YT_COLORS,
  chili_oil_yt_default: CHILI_OIL_YT_COLORS,
  wasabi_paste_yt_default: WASABI_PASTE_YT_COLORS,
  pickled_ginger_yt_default: PICKLED_GINGER_YT_COLORS,
  rice_vinegar_yt_default: RICE_VINEGAR_YT_COLORS,
  mirin_bottle_yt_default: MIRIN_BOTTLE_YT_COLORS,
  dashi_stock_yt_default: DASHI_STOCK_YT_COLORS,
  senbei_yt_default: SENBEI_YT_COLORS,
  amazake_cup_yt_default: AMAZAKE_CUP_YT_COLORS,
  calpis_bottle_yt_default: CALPIS_BOTTLE_YT_COLORS,
  oolong_tea_yt_default: OOLONG_TEA_YT_COLORS,
  barley_tea_yt_default: BARLEY_TEA_YT_COLORS,
};
