/**
 * Bakery batch 2 — 20 cake & cupcake templates.
 * Covers: layer cake, wedding cake, chocolate cake, carrot cake, pound cake,
 *         angel food cake, red velvet cake, bundt cake, birthday cake, lava cake,
 *         vanilla cupcake, chocolate cupcake, strawberry cupcake, red velvet cupcake,
 *         lemon cupcake, cake pop, petit four, swiss roll, tres leches, fruit cake.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'BAKERY_BATCH2_TEMPLATES', schemes: 'BAKERY_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. LAYER CAKE ────────────────────────────────────────────
    {
      id: 'layer_cake_16',
      description: 'Three-layer cake with frosting between layers and drip icing on top.',
      grid: [
        '................',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '...FFFFFFFFFF...',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '...FFFFFFFFFF...',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frosting', role: 'head' },
        L: { name: 'cake_layer', role: 'body' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head: { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 2. WEDDING CAKE ──────────────────────────────────────────
    {
      id: 'wedding_cake_16',
      description: 'Tiered wedding cake with decorative piping and flower accent on top.',
      grid: [
        '................',
        '.......AA.......',
        '......FFFF......',
        '......TTTT......',
        '......TTTT......',
        '.....FFFFFF.....',
        '....FMMMMMMF....',
        '....MMMMMMMM....',
        '....MMMMMMMM....',
        '...FFFFFFFFFF...',
        '..FBBBBBBBBBBF..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'flower_top', role: 'accessory' },
        F: { name: 'frosting_pipe', role: 'head' },
        T: { name: 'top_tier', role: 'eye' },
        M: { name: 'mid_tier', role: 'arm' },
        B: { name: 'bottom_tier', role: 'body' },
        P: { name: 'cake_board', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 3. CHOCOLATE CAKE ────────────────────────────────────────
    {
      id: 'chocolate_cake_16',
      description: 'Rich dark chocolate cake with ganache drip and shiny glaze.',
      grid: [
        '................',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '...GDGGGGGDGG...',
        '...GDDGGGGDDG...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...GGGGGGGGGG...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'ganache_glaze', role: 'head' },
        D: { name: 'ganache_drip', role: 'accessory' },
        C: { name: 'chocolate_body', role: 'body' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. CARROT CAKE ───────────────────────────────────────────
    {
      id: 'carrot_cake_16',
      description: 'Orange-speckled carrot cake with cream cheese frosting and carrot decoration.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '...FFFFFFFFFF...',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..SSBBSSBBBSS...',
        '..BBBBBBBBBBBB..',
        '..BSBBBBBBSBBB..',
        '..BBBBBBBBBBBB..',
        '..FFFFFFFFFFFF..',
        '..SSBBSSBBBSS...',
        '..BBBBBBBBBBBB..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'carrot_topper', role: 'accessory' },
        F: { name: 'cream_frosting', role: 'head' },
        B: { name: 'cake_body', role: 'body' },
        S: { name: 'carrot_speck', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 5. POUND CAKE ────────────────────────────────────────────
    {
      id: 'pound_cake_16',
      description: 'Dense golden pound cake loaf with crackled top crust.',
      grid: [
        '................',
        '................',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '...CCHCCCHCCC...',
        '...CCCCCCCCCC...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...TTTTTTTTTT...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crust_top', role: 'head' },
        H: { name: 'crust_crack', role: 'accessory' },
        B: { name: 'cake_body', role: 'body' },
        T: { name: 'bottom_crust', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 6. ANGEL FOOD CAKE ───────────────────────────────────────
    {
      id: 'angel_food_cake_16',
      description: 'Tall light angel food cake, very pale with airy texture and dusted top.',
      grid: [
        '................',
        '....DDDDDDDD....',
        '...DDDDDDDDDD...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCECCCCECC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCECCCCECC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...BBBBBBBBBB...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        D: { name: 'sugar_dust', role: 'accessory' },
        C: { name: 'cake_body', role: 'head' },
        E: { name: 'air_pocket', role: 'eye' },
        B: { name: 'cake_base', role: 'body' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#d2aa99' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 7. RED VELVET CAKE ───────────────────────────────────────
    {
      id: 'red_velvet_cake_16',
      description: 'Deep red cake with white cream cheese layers exposed on the side.',
      grid: [
        '................',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...FFFFFFFFFF...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...FFFFFFFFFF...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'cream_cheese', role: 'head' },
        R: { name: 'red_cake', role: 'body' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 8. BUNDT CAKE ────────────────────────────────────────────
    {
      id: 'bundt_cake_16',
      description: 'Ring-shaped bundt cake with glaze drizzle flowing down ridges.',
      grid: [
        '................',
        '................',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '..GGGGG..GGGGG..',
        '..BBBB....BBBB..',
        '..BBBB....BBBB..',
        '..BBBBB..BBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'glaze_drip', role: 'head' },
        B: { name: 'cake_body', role: 'body' },
        T: { name: 'cake_base', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 9. BIRTHDAY CAKE ─────────────────────────────────────────
    {
      id: 'birthday_cake_16',
      description: 'Colorful birthday cake with lit candles on top and sprinkle decorations.',
      grid: [
        '................',
        '..L..L..L..L....',
        '..C..C..C..C....',
        '..C..C..C..C....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '...FSFFSFFFSF...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BSBBSBBSBB...',
        '...FFFFFFFFFF...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'candle_flame', role: 'accessory' },
        C: { name: 'candle_stick', role: 'eye' },
        F: { name: 'frosting', role: 'head' },
        B: { name: 'cake_body', role: 'body' },
        S: { name: 'sprinkles', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 10. LAVA CAKE ────────────────────────────────────────────
    {
      id: 'lava_cake_16',
      description: 'Dark chocolate lava cake with molten center flowing out from a split top.',
      grid: [
        '................',
        '................',
        '......MMM.......',
        '.....MMMMM......',
        '....MMMMMM......',
        '...MMMMMMMMM....',
        '...CCCCCCCCCC...',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '...BBBBBBBBBB...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'molten_center', role: 'accessory' },
        C: { name: 'chocolate_body', role: 'body' },
        B: { name: 'cake_base', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 11. VANILLA CUPCAKE ──────────────────────────────────────
    {
      id: 'vanilla_cupcake_16',
      description: 'Classic cupcake with swirled vanilla frosting and a cherry on top.',
      grid: [
        '................',
        '................',
        '.......CC.......',
        '......CCCC......',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cherry', role: 'accessory' },
        F: { name: 'vanilla_frosting', role: 'head' },
        W: { name: 'wrapper', role: 'arm' },
        B: { name: 'cake_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 12. CHOCOLATE CUPCAKE ────────────────────────────────────
    {
      id: 'chocolate_cupcake_16',
      description: 'Dark cupcake with rich chocolate frosting swirl and cocoa dust.',
      grid: [
        '................',
        '................',
        '................',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFDDFF...',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'choco_frosting', role: 'head' },
        D: { name: 'cocoa_dust', role: 'accessory' },
        W: { name: 'wrapper', role: 'arm' },
        B: { name: 'cake_base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 13. STRAWBERRY CUPCAKE ───────────────────────────────────
    {
      id: 'strawberry_cupcake_16',
      description: 'Pink frosted cupcake with a strawberry perched on top.',
      grid: [
        '................',
        '......SS........',
        '.....SSSS.......',
        '.....TTTT.......',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'strawberry_leaf', role: 'accessory' },
        T: { name: 'strawberry_body', role: 'eye' },
        F: { name: 'pink_frosting', role: 'head' },
        W: { name: 'wrapper', role: 'arm' },
        B: { name: 'cake_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 14. RED VELVET CUPCAKE ───────────────────────────────────
    {
      id: 'red_velvet_cupcake_16',
      description: 'Red cupcake with cream cheese frosting swirl on top.',
      grid: [
        '................',
        '................',
        '................',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '.....RRRRRR.....',
        '.....RRRRRR.....',
        '.....RRRRRR.....',
        '......RRRR......',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'cream_frosting', role: 'head' },
        W: { name: 'wrapper', role: 'arm' },
        R: { name: 'red_cake', role: 'body' },
      },
      colors: {
        head: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. LEMON CUPCAKE ────────────────────────────────────────
    {
      id: 'lemon_cupcake_16',
      description: 'Yellow cupcake with lemon frosting and a tiny lemon wedge garnish.',
      grid: [
        '................',
        '................',
        '.........LL.....',
        '........LLLL....',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lemon_wedge', role: 'accessory' },
        F: { name: 'lemon_frosting', role: 'head' },
        W: { name: 'wrapper', role: 'arm' },
        B: { name: 'cake_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 16. CAKE POP ─────────────────────────────────────────────
    {
      id: 'cake_pop_16',
      description: 'Round cake pop on a stick with candy coating and sprinkle details.',
      grid: [
        '................',
        '................',
        '.....CCCCCC.....',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '...CCSCCSCCC....',
        '...CCCCCCCCCC...',
        '...CCSCCSCCCC...',
        '...CCCCCCCCCC...',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '.......SS.......',
        '.......SS.......',
        '.......SS.......',
        '.......SS.......',
        '................',
      ],
      chars: {
        C: { name: 'candy_coating', role: 'head' },
        S: { name: 'sprinkle_dot', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. PETIT FOUR ───────────────────────────────────────────
    {
      id: 'petit_four_16',
      description: 'Small square petit four with pastel glaze and delicate flower on top.',
      grid: [
        '................',
        '................',
        '................',
        '.....FF.........',
        '....FFFF........',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...BBBBBBBBBB...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flower_decor', role: 'accessory' },
        G: { name: 'pastel_glaze', role: 'head' },
        C: { name: 'cake_body', role: 'body' },
        B: { name: 'cake_base', role: 'arm' },
        P: { name: 'doily', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 18. SWISS ROLL ───────────────────────────────────────────
    {
      id: 'swiss_roll_16',
      description: 'Spiral swiss roll cross-section showing cream swirl inside chocolate sponge.',
      grid: [
        '................',
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '..SSSSSSSSSSSS..',
        '..SSCCCCCCCCSS..',
        '..SSCCSSSSCCSM..',
        '..SSCSSCCSSCSM..',
        '..SSCSSCCSSCSM..',
        '..SSCCSSSSCCSM..',
        '..SSCCCCCCCCSS..',
        '..SSSSSSSSSSSS..',
        '...SSSSSSSSSS...',
        '....SSSSSSSS....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'chocolate_sponge', role: 'body' },
        C: { name: 'cream_swirl', role: 'head' },
        M: { name: 'sponge_shadow', role: 'arm' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 19. TRES LECHES ──────────────────────────────────────────
    {
      id: 'tres_leches_16',
      description: 'Soaked tres leches cake with cream topping and cinnamon sprinkle.',
      grid: [
        '................',
        '................',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCDCCDCCDC...',
        '...CCCCCCCCCC...',
        '...SSSSSSSSSS...',
        '...SSSSSSSSSS...',
        '...SSSSSSSSSS...',
        '...SSSSSSSSSS...',
        '...SSSSSSSSSS...',
        '...SSSSSSSSSS...',
        '...BBBBBBBBBB...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cream_top', role: 'head' },
        D: { name: 'cinnamon_dust', role: 'accessory' },
        S: { name: 'soaked_sponge', role: 'body' },
        B: { name: 'milk_pool', role: 'arm' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 20. FRUIT CAKE ───────────────────────────────────────────
    {
      id: 'fruit_cake_16',
      description: 'Dense fruitcake with visible colorful fruit pieces and nut chunks.',
      grid: [
        '................',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '...BBRBBGBBFRB..',
        '...BBBFBBRBBBBB.',
        '...BRBBBBBFBBBB.',
        '...BBBFBBRBBFRB.',
        '...BBBBBFBBBBB..',
        '...BRFBBBBRBBB..',
        '...BBBBRBBFBBB..',
        '...BFBBBBBBRBB..',
        '...TTTTTTTTTT...',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'glaze_top', role: 'head' },
        B: { name: 'cake_body', role: 'body' },
        R: { name: 'cherry_piece', role: 'accessory' },
        F: { name: 'citrus_piece', role: 'arm' },
        T: { name: 'cake_base', role: 'belt' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
