/**
 * Bakery batch 1 — 20 bread & dough templates.
 * Covers: sourdough loaf, rye bread, focaccia, dinner roll, bagel,
 *         english muffin, challah bread, brioche, ciabatta, cornbread,
 *         pumpernickel, flatbread, naan bread, tortilla, bread roll basket,
 *         breadstick, toast slice, banana bread, marble rye, whole wheat loaf.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'BAKERY_BATCH1_TEMPLATES', schemes: 'BAKERY_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SOURDOUGH LOAF ─────────────────────────────────────
    {
      id: 'sourdough_loaf_16',
      description: 'Round sourdough loaf with scored top and flour dusting.',
      grid: [
        '................',
        '......FFFF......',
        '.....FFFFFF.....',
        '....FHHHHHFF....',
        '...FHHHHHHHFF...',
        '...HHSHHHSHHHF..',
        '..HHHHHHHHHHHH..',
        '..HHHSHHHHSHHHH.',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flour_dust', role: 'accessory' },
        H: { name: 'top_crust', role: 'head' },
        S: { name: 'score_marks', role: 'eye' },
        B: { name: 'side_crust', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 2. RYE BREAD ──────────────────────────────────────────
    {
      id: 'rye_bread_16',
      description: 'Dark rye bread loaf with dense crumb visible on cut face.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..CCCCCCCHHHHHH.',
        '..CCCCCCCHHHHHH.',
        '..CCSCCSCCHHHH..',
        '..CCCCCCCCHHH...',
        '..CCCSCCSCCBB...',
        '..CCCCCCCCCCBB..',
        '...BBBBBBBBBBB..',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        H: { name: 'dark_crust', role: 'head' },
        C: { name: 'crumb_face', role: 'body' },
        S: { name: 'seed_specks', role: 'accessory' },
        B: { name: 'bottom_crust', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 3. FOCACCIA ───────────────────────────────────────────
    {
      id: 'focaccia_16',
      description: 'Flat focaccia slab with herb spots, olive oil sheen, and dimpled surface.',
      grid: [
        '................',
        '................',
        '................',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HGHHDHHGHDHH..',
        '..HDHHHHHHDHHH..',
        '..HHHHGHHHHGHH..',
        '..HGHHHDHHHHDHH.',
        '..BBBBBBBBBBBBH.',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...CCCCCCCCCC...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_surface', role: 'head' },
        G: { name: 'herb_spot', role: 'accessory' },
        D: { name: 'dimple', role: 'eye' },
        B: { name: 'side_crust', role: 'body' },
        C: { name: 'bottom_edge', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 4. DINNER ROLL ────────────────────────────────────────
    {
      id: 'dinner_roll_16',
      description: 'Small round dinner roll with golden crust and soft highlight.',
      grid: [
        '................',
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '...HHHHHEHHHH...',
        '...HHHHHHHHHHH..',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_crust', role: 'head' },
        E: { name: 'shine_spot', role: 'eye' },
        B: { name: 'bottom_crust', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 5. BAGEL ──────────────────────────────────────────────
    {
      id: 'bagel_16',
      description: 'Ring-shaped bagel with sesame seed dots and golden baked surface.',
      grid: [
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHSHHSHHHH...',
        '..HHHH....HHHH..',
        '..HHH......HHH..',
        '..HHH......HHH..',
        '..HHHH....HHHH..',
        '...BBBSBBSBBBB..',
        '....BBBBBBBBBB..',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_crust', role: 'head' },
        S: { name: 'sesame_seeds', role: 'accessory' },
        B: { name: 'bottom_crust', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 6. ENGLISH MUFFIN ─────────────────────────────────────
    {
      id: 'english_muffin_16',
      description: 'Split English muffin showing nooks and crannies texture inside.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...CCNCNCNCCC...',
        '...CCCCNCCCCC...',
        '...CNCCCNCNCC...',
        '...CCNCNCCCCC...',
        '................',
        '...CCNCNCNCCC...',
        '...CCCCNCCCCC...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'outer_crust', role: 'head' },
        C: { name: 'crumb_surface', role: 'body' },
        N: { name: 'nook_hole', role: 'eye' },
        B: { name: 'bottom_half', role: 'arm' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        arm:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 7. CHALLAH BREAD ──────────────────────────────────────
    {
      id: 'challah_bread_16',
      description: 'Braided challah loaf with shiny egg wash top and golden weave pattern.',
      grid: [
        '................',
        '................',
        '....EEEEEEEE....',
        '...EHHBBHHBBE...',
        '..EHBBHHBBHHBE..',
        '..EBBHHBBHHBBE..',
        '..EHHBBHHBBHHE..',
        '..EBBHHBBHHBBE..',
        '..EHHBBHHBBHHE..',
        '..EBBHHBBHHBBE..',
        '..EHHBBHHBBHHE..',
        '...EBBHHBBBBE...',
        '....EEEEEEEE....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'egg_wash', role: 'accessory' },
        H: { name: 'braid_strand_a', role: 'head' },
        B: { name: 'braid_strand_b', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 8. BRIOCHE ────────────────────────────────────────────
    {
      id: 'brioche_16',
      description: 'Tall brioche bun with rich golden color and puffy top knob.',
      grid: [
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHEHHH.....',
        '......HHHH......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBEBBBBEBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....CCCCCCCC....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_knob', role: 'head' },
        E: { name: 'shine_spot', role: 'eye' },
        B: { name: 'bun_body', role: 'body' },
        C: { name: 'bottom_rim', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 9. CIABATTA ───────────────────────────────────────────
    {
      id: 'ciabatta_16',
      description: 'Flat rustic ciabatta with flour-dusted crust and irregular shape.',
      grid: [
        '................',
        '................',
        '................',
        '..FFFFFFFFFFF...',
        '.FHHHHHHHHHHHF..',
        '.FHHHHHHHHHHHHF.',
        '.HHHHHHHHHHHHH..',
        '.HHHHHHHHHHHHH..',
        '.HHHHHHHHHHHHHH.',
        '.BBBBBBBBBBBBBH.',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '...CCCCCCCCCCC..',
        '....TTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flour_dust', role: 'accessory' },
        H: { name: 'top_crust', role: 'head' },
        B: { name: 'side_crust', role: 'body' },
        C: { name: 'bottom_edge', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 10. CORNBREAD ─────────────────────────────────────────
    {
      id: 'cornbread_16',
      description: 'Square cornbread piece with golden yellow interior and browned top.',
      grid: [
        '................',
        '................',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBEBBBBEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'browned_top', role: 'head' },
        B: { name: 'corn_crumb', role: 'body' },
        E: { name: 'corn_speck', role: 'eye' },
        C: { name: 'bottom_crust', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d27d2c' },
        arm:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 11. PUMPERNICKEL ──────────────────────────────────────
    {
      id: 'pumpernickel_16',
      description: 'Very dark pumpernickel loaf, nearly black-brown with dense texture.',
      grid: [
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '...HHHHHHHHHHH..',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBSBBBSBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBSBBBSBBBB..',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dark_crust', role: 'head' },
        B: { name: 'loaf_body', role: 'body' },
        S: { name: 'seed_speck', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 12. FLATBREAD ─────────────────────────────────────────
    {
      id: 'flatbread_16',
      description: 'Thin round flatbread with char spots and slightly uneven edges.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHHHHH....',
        '....HHHHHHHHH...',
        '...HHCHHHHCHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHHHCHHHHHHH.',
        '..HHCHHHHHCHHHH.',
        '...HHHHHHHHHHH..',
        '....HHHHHHHHH...',
        '.....BBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bread_surface', role: 'head' },
        C: { name: 'char_spot', role: 'accessory' },
        B: { name: 'bottom_edge', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 13. NAAN BREAD ────────────────────────────────────────
    {
      id: 'naan_bread_16',
      description: 'Teardrop-shaped naan with bubbled char marks and golden surface.',
      grid: [
        '................',
        '................',
        '.......HHH......',
        '......HHHHH.....',
        '.....HHHHHH.....',
        '....HHHCHHHH....',
        '...HHHHHHHHH....',
        '...HHHHHCHHHH...',
        '..HHHCHHHHHHH...',
        '..HHHHHHHHCHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHCHHHHCHHH..',
        '...BBBBBBBBBBB..',
        '....BBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'naan_surface', role: 'head' },
        C: { name: 'char_bubble', role: 'accessory' },
        B: { name: 'bottom_edge', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. TORTILLA ──────────────────────────────────────────
    {
      id: 'tortilla_16',
      description: 'Thin round tortilla stack of three, slightly offset.',
      grid: [
        '................',
        '................',
        '................',
        '...SSSSSSSSS....',
        '..SSSSSSSSSSS...',
        '..SSSSSSSSSSS...',
        '..MMMMMMMMMMM...',
        '..MMMMMMMMMMMM..',
        '..MMMMMMMMMMMM..',
        '...HHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '....HHHHHHHHHH..',
        '......BBBBBB....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'top_tortilla', role: 'head' },
        M: { name: 'mid_tortilla', role: 'body' },
        H: { name: 'bottom_tortilla', role: 'arm' },
        B: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 15. BREAD ROLL BASKET ─────────────────────────────────
    {
      id: 'bread_roll_basket_16',
      description: 'Woven basket filled with assorted round bread rolls.',
      grid: [
        '................',
        '....RRRRRRRR....',
        '...RRRRRRRRRRR..',
        '..RREERREERRRR..',
        '..RRRRRRRRRRRRR.',
        '..RREERRRREERR..',
        '.WWWWWWWWWWWWWW.',
        '.WBWBWBWBWBWBWW.',
        '.WBWBWBWBWBWBWW.',
        '.WWWWWWWWWWWWWW.',
        '.WBWBWBWBWBWBWW.',
        '.WBWBWBWBWBWBWW.',
        '.WWWWWWWWWWWWWW.',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bread_rolls', role: 'head' },
        E: { name: 'roll_shine', role: 'eye' },
        W: { name: 'basket_weave', role: 'body' },
        B: { name: 'weave_gap', role: 'accessory' },
        T: { name: 'basket_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 16. BREADSTICK ────────────────────────────────────────
    {
      id: 'breadstick_16',
      description: 'Long thin breadstick with seeds sprinkled on top.',
      grid: [
        '................',
        '................',
        '................',
        '..HH............',
        '...HHH..........',
        '....HSHH........',
        '.....HHSHH......',
        '......HHHSHH....',
        '.......HHHHSHH..',
        '........HHHHHH..',
        '.........BBBBB..',
        '..........BBBB..',
        '...........BBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'stick_body', role: 'head' },
        S: { name: 'seed_dot', role: 'accessory' },
        B: { name: 'dark_end', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. TOAST SLICE ───────────────────────────────────────
    {
      id: 'toast_slice_16',
      description: 'Toasted bread slice with golden-brown gradient from edges to center.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHCCCCCCCCHH..',
        '..HCCCCCCCCCCCH.',
        '..HCCCCCCCCCCCH.',
        '..HCCCEECCCCCCH.',
        '..HCCCCCCCCCCCH.',
        '..HCCCCCCCECCH..',
        '..HCCCCCCCCCCCH.',
        '..HHCCCCCCCCHH..',
        '..HHHHHHHHHHHHH.',
        '...HHHHHHHHHHH..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'toasted_crust', role: 'head' },
        C: { name: 'bread_center', role: 'body' },
        E: { name: 'air_bubble', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d27d2c' },
      },
    },

    // ─── 18. BANANA BREAD ──────────────────────────────────────
    {
      id: 'banana_bread_16',
      description: 'Loaf of banana bread with visible banana chunks and cracked top.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHKHHHKHHH...',
        '..HHHHHHHHHHHHH.',
        '..HHHKHHHHHKHH..',
        '..CCCCCCCCCCCC..',
        '..CCCKCCCCCKCC..',
        '..CCCCCCCCCCCC..',
        '..BBBBBBBBBBBB..',
        '..BBBKBBBBBKBB..',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cracked_top', role: 'head' },
        K: { name: 'banana_chunk', role: 'accessory' },
        C: { name: 'bread_crumb', role: 'body' },
        B: { name: 'bottom_crust', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 19. MARBLE RYE ────────────────────────────────────────
    {
      id: 'marble_rye_16',
      description: 'Marbled rye slice showing swirl pattern of light and dark dough.',
      grid: [
        '................',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '..CLLLDDDLLLLC..',
        '..CLLDDDDDLLLC..',
        '..CDDDLLLLDDDC..',
        '..CDDDDLLLDDC...',
        '..CLLLLDDDDLLC..',
        '..CLLLLDDDLLLC..',
        '..CDDDDLLLDDDC..',
        '..CDDDDDLLDDDC..',
        '..CLLLLDDDLLLC..',
        '...CCCCCCCCCC...',
        '....CCCCCCCC....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crust_rim', role: 'arm' },
        L: { name: 'light_dough', role: 'head' },
        D: { name: 'dark_dough', role: 'body' },
      },
      colors: {
        arm:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 20. WHOLE WHEAT LOAF ──────────────────────────────────
    {
      id: 'whole_wheat_loaf_16',
      description: 'Dense whole wheat loaf with seeds on top and hearty brown color.',
      grid: [
        '................',
        '.....SSSSSS.....',
        '....SHSHSHSS....',
        '...SHSHSHSHSH...',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'seed_top', role: 'accessory' },
        H: { name: 'top_crust', role: 'head' },
        B: { name: 'loaf_body', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

  ],
};

export default batch;
