/**
 * Bakery batch 5 — 20 bakery equipment & decor templates.
 * Category: furniture (uses PRESET_WOOD warm defaults).
 * Steel grays for metal, warm browns for wood, whites for ceramic/fabric.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'furniture',
  exportNames: { templates: 'BAKERY_BATCH5_TEMPLATES', schemes: 'BAKERY_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ─── 1. STAND MIXER ────────────────────────────────────────────
    {
      id: 'stand_mixer_16',
      description: 'Kitchen stand mixer with tilting head, paddle arm, and mixing bowl.',
      grid: [
        '................',
        '....HHHHHH......',
        '....HHHHHHH.....',
        '....HHAAAH......',
        '....HH.AAA......',
        '....HH..AA......',
        '....HHHHHH......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '...GGGGGGGG.....',
        '..GGGGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'motor_housing', role: 'head' },
        A: { name: 'paddle_arm', role: 'arm' },
        B: { name: 'mixing_bowl', role: 'body' },
        G: { name: 'base_plate', role: 'leg' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        leg:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 2. PASTRY BAG ─────────────────────────────────────────────
    {
      id: 'pastry_bag_16',
      description: 'Cloth piping bag with metal decorating tip, squeezing out frosting.',
      grid: [
        '................',
        '......BB........',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....HHHHHH......',
        '.....HHHH.......',
        '......AA........',
        '......FF........',
        '.....FFFF.......',
        '................',
      ],
      chars: {
        B: { name: 'bag_fabric', role: 'body' },
        H: { name: 'coupler_ring', role: 'head' },
        A: { name: 'metal_tip', role: 'arm' },
        F: { name: 'frosting', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 3. WHISK ──────────────────────────────────────────────────
    {
      id: 'whisk_16',
      description: 'Wire whisk with wooden handle and looping tines.',
      grid: [
        '................',
        '......HH........',
        '......HH........',
        '......HH........',
        '......HH........',
        '......HH........',
        '......AA........',
        '.....ABBA.......',
        '....AB..BA......',
        '...AB....BA.....',
        '...AB....BA.....',
        '...AB....BA.....',
        '....AB..BA......',
        '.....ABBA.......',
        '......BB........',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'head' },
        A: { name: 'wire_tines', role: 'arm' },
        B: { name: 'wire_center', role: 'body' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. MEASURING CUPS ─────────────────────────────────────────
    {
      id: 'measuring_cups_16',
      description: 'Nested set of measuring cups in graduated sizes on a ring.',
      grid: [
        '................',
        '................',
        '................',
        '..AHHH.BBBB.....',
        '..AHHH.BBBBB....',
        '..AHHH.BBBBB....',
        '...HHH.BBBBB....',
        '..AHHH..EEEEEE..',
        '..AHHH..EEEEEEE.',
        '..AHHH..EEEEEEE.',
        '...HHH..EEEEEEE.',
        '...HHH...EEEEEE.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'small_cup', role: 'head' },
        A: { name: 'small_handle', role: 'arm' },
        B: { name: 'medium_cup', role: 'body' },
        E: { name: 'large_cup', role: 'eye' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. BAKING SHEET ───────────────────────────────────────────
    {
      id: 'baking_sheet_16',
      description: 'Flat metal baking sheet with raised rim and cookies on top.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBBAAABBBBBBH.',
        '..HBBBBBBAAABBH.',
        '..HBBBBBBBBBBH..',
        '..HBBAAABBBBBBH.',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'tray_rim', role: 'head' },
        B: { name: 'tray_surface', role: 'body' },
        A: { name: 'cookies', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 6. COOKIE CUTTER ──────────────────────────────────────────
    {
      id: 'cookie_cutter_16',
      description: 'Star-shaped cookie cutter in shiny metal.',
      grid: [
        '................',
        '......BBB.......',
        '......BBB.......',
        '.....BBBBB......',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '...BBB...BBB....',
        '..BBBB...BBBB...',
        '..BBB.....BBB...',
        '..BB.......BB...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'metal_edge', role: 'body' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 7. CAKE STAND ─────────────────────────────────────────────
    {
      id: 'cake_stand_16',
      description: 'Pedestal cake stand with wide plate and ornate stem.',
      grid: [
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '..HHHHHHHHHHHH..',
        '......AABB......',
        '......AABB......',
        '......AABB......',
        '......AABB......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'plate_rim', role: 'head' },
        B: { name: 'plate_surface', role: 'body' },
        A: { name: 'stem_left', role: 'arm' },
        G: { name: 'pedestal_base', role: 'leg' },
      },
      colors: {
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:  { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        leg:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 8. BREAD BOX ──────────────────────────────────────────────
    {
      id: 'bread_box_16',
      description: 'Wooden bread box with roll-top lid and front handle.',
      grid: [
        '................',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBAAABBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid_top', role: 'head' },
        B: { name: 'box_body', role: 'body' },
        A: { name: 'handle', role: 'accessory' },
        G: { name: 'base_trim', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. DOUGH SCRAPER ──────────────────────────────────────────
    {
      id: 'dough_scraper_16',
      description: 'Bench scraper tool with metal blade and wooden grip handle.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..AAAAAAAAAAAA..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..EEEEEEEEEEEE..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wood_handle', role: 'head' },
        A: { name: 'handle_edge', role: 'arm' },
        B: { name: 'metal_blade', role: 'body' },
        E: { name: 'blade_edge', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 10. FLOUR SACK ────────────────────────────────────────────
    {
      id: 'flour_sack_16',
      description: 'Cloth sack of flour with tied top and printed label.',
      grid: [
        '................',
        '.....AAHAA......',
        '......HHH.......',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..GGGGGGGGGGG...',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'tied_top', role: 'accessory' },
        H: { name: 'knot', role: 'head' },
        B: { name: 'sack_fabric', role: 'body' },
        E: { name: 'label', role: 'eye' },
        G: { name: 'sack_base', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 11. SUGAR JAR ─────────────────────────────────────────────
    {
      id: 'sugar_jar_16',
      description: 'Glass jar with sugar visible inside, cork lid and label.',
      grid: [
        '................',
        '......HHHH......',
        '......HHHH......',
        '.....AAAAAA.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBGGGGBB....',
        '....BBGGGGBB....',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cork_lid', role: 'head' },
        A: { name: 'jar_neck', role: 'arm' },
        B: { name: 'glass_body', role: 'body' },
        E: { name: 'label', role: 'eye' },
        G: { name: 'sugar_fill', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 12. BUTTER DISH ───────────────────────────────────────────
    {
      id: 'butter_dish_16',
      description: 'Ceramic butter dish with domed lid and butter block inside.',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAAAAABB..',
        '..BBAAAAAAAABB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dome_lid', role: 'head' },
        B: { name: 'dish_base', role: 'body' },
        A: { name: 'butter_block', role: 'accessory' },
        G: { name: 'dish_foot', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 13. EGG CARTON ────────────────────────────────────────────
    {
      id: 'egg_carton_16',
      description: 'Open egg carton showing six eggs nestled in cardboard wells.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBEEBBEEBBB...',
        '..BEEEBEEEBEEB..',
        '..BBEEBBEEBBEEB.',
        '..BBBBBBBBBBBB..',
        '..BBEEBBEEBBB...',
        '..BEEEBEEEBEEB..',
        '..BBEEBBEEBBEEB.',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid_open', role: 'head' },
        B: { name: 'carton', role: 'body' },
        E: { name: 'eggs', role: 'eye' },
      },
      colors: {
        head: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 14. COOLING RACK ──────────────────────────────────────────
    {
      id: 'cooling_rack_16',
      description: 'Wire cooling rack with grid pattern and cookies resting on top.',
      grid: [
        '................',
        '................',
        '................',
        '....AA..AA......',
        '..AAAAAA..AA....',
        '..BBBBBBBBBBBB..',
        '..B.BB.BB.BB.B..',
        '..BBBBBBBBBBBB..',
        '..B.BB.BB.BB.B..',
        '..BBBBBBBBBBBB..',
        '..B.BB.BB.BB.B..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'cookies', role: 'accessory' },
        B: { name: 'wire_grid', role: 'body' },
        G: { name: 'rack_feet', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. CAKE TOPPER ───────────────────────────────────────────
    {
      id: 'cake_topper_16',
      description: 'Decorative triangular cake topper flag on a stick.',
      grid: [
        '................',
        '......BB........',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '..BBEEEEEEBB....',
        '.BBEEEEEEEEBB...',
        '.HHHHHHHHHHHHH..',
        '......AA........',
        '......AA........',
        '......AA........',
        '......AA........',
        '......AA........',
        '......AA........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'flag_border', role: 'body' },
        E: { name: 'flag_face', role: 'eye' },
        H: { name: 'flag_bottom', role: 'head' },
        A: { name: 'stick', role: 'arm' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. PASTRY DISPLAY ────────────────────────────────────────
    {
      id: 'pastry_display_16',
      description: 'Glass pastry display case with shelves showing baked goods.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBAABBAAABBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBAABBAAABBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GG........GG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        B: { name: 'glass_panel', role: 'body' },
        A: { name: 'pastries', role: 'accessory' },
        G: { name: 'base_cabinet', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. BAKERY SIGN ───────────────────────────────────────────
    {
      id: 'bakery_sign_16',
      description: 'Hanging wooden bakery shop sign with iron bracket and bread icon.',
      grid: [
        '................',
        '..AA............',
        '..AAAAAA........',
        '..AA..AA........',
        '......HHHHHHHH..',
        '......HBBBBBBH..',
        '......HBBBBBBH..',
        '......HBBEEBB...',
        '......HBBBBBBH..',
        '......HBBBBBBH..',
        '......HHHHHHHH..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'iron_bracket', role: 'arm' },
        H: { name: 'sign_frame', role: 'head' },
        B: { name: 'sign_board', role: 'body' },
        E: { name: 'bread_icon', role: 'eye' },
      },
      colors: {
        arm:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. BREAD KNIFE ───────────────────────────────────────────
    {
      id: 'bread_knife_16',
      description: 'Long serrated bread knife with wood handle and wavy blade edge.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHHHH.........',
        '..HHHHH.........',
        '..HHHHH.........',
        '...AABBBBBBBBBB.',
        '...AABBBBBBBBBB.',
        '....EEEEEEEEEE..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wood_handle', role: 'head' },
        A: { name: 'bolster', role: 'arm' },
        B: { name: 'blade_flat', role: 'body' },
        E: { name: 'serrated_edge', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. BRICK OVEN ────────────────────────────────────────────
    {
      id: 'brick_oven_16',
      description: 'Traditional brick bread oven with arched opening and fire glow.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHBBBBBBHH...',
        '...HHBBBBBBHH...',
        '...HHBBBBBBHH...',
        '...HHB.EE.BHH...',
        '...HHBBEEBBHH...',
        '...HHBBEEBBHH...',
        '...HHBBBBBBHH...',
        '...HHBBBBBBHH...',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'brick_shell', role: 'head' },
        B: { name: 'inner_wall', role: 'body' },
        E: { name: 'fire_glow', role: 'eye' },
        G: { name: 'hearth_base', role: 'leg' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 20. BAKER APRON ───────────────────────────────────────────
    {
      id: 'baker_apron_16',
      description: 'Baker apron with neck loop, waist ties, and front pocket.',
      grid: [
        '................',
        '.....AA..AA.....',
        '....AA....AA....',
        '....AABBBBAA....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '..HBBBBBBBBBBH..',
        '..HHBBBBBBBBHH..',
        '.....BBBBBB.....',
        '.....BBEEBB.....',
        '.....BBEEBB.....',
        '.....BBBBBB.....',
        '.....GGGGGG.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'neck_strap', role: 'arm' },
        B: { name: 'apron_body', role: 'body' },
        H: { name: 'waist_ties', role: 'head' },
        E: { name: 'front_pocket', role: 'eye' },
        G: { name: 'apron_hem', role: 'leg' },
      },
      colors: {
        arm:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:  { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
