/**
 * Bakery batch 3 — 20 pastry & pie templates.
 * Covers: eclair, cannoli, danish pastry, scone, macaron,
 *         churro, palmier, cream puff, strudel, baklava,
 *         apple pie, berry pie, pumpkin pie, pecan pie,
 *         lemon meringue pie, cream pie, quiche, pot pie,
 *         hand pie, tart shell.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'BAKERY_BATCH3_TEMPLATES', schemes: 'BAKERY_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. ECLAIR ─────────────────────────────────────────────────
    {
      id: 'eclair_16',
      description: 'Long eclair with chocolate glaze on top and cream filling visible at the ends.',
      grid: [
        '................',
        '................',
        '................',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '..CCBBBBBBBBCC..',
        '..CCBBBBBBBBCC..',
        '..CCBBBBBBBBCC..',
        '..CCBBBBBBBBCC..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'chocolate_glaze', role: 'head' },
        B: { name: 'pastry_body', role: 'body' },
        C: { name: 'cream_filling', role: 'accessory' },
        T: { name: 'plate_edge', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 2. CANNOLI ────────────────────────────────────────────────
    {
      id: 'cannoli_16',
      description: 'Crispy cannoli shell with ricotta cream piped at both ends and chocolate chips.',
      grid: [
        '................',
        '................',
        '................',
        '..CCC...........',
        '..CCCSSSSSSCCC..',
        '..CCCSSSSSSCCC..',
        '..CDDSSSSSSDDC..',
        '..CDDSSSSSSDDC..',
        '..CDDSSSSSSDDC..',
        '..CDDSSSSSSDDC..',
        '..CCCSSSSSSCCC..',
        '..CCCSSSSSSCCC..',
        '..CCC...........',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'shell', role: 'body' },
        C: { name: 'ricotta_cream', role: 'head' },
        D: { name: 'chocolate_chip', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. DANISH PASTRY ──────────────────────────────────────────
    {
      id: 'danish_pastry_16',
      description: 'Swirled danish pastry with fruit jam center and golden flaky layers.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHBBBBBBHHHH..',
        '..HHBBJJBBHHHH..',
        '..HHBBJJJBHHHH..',
        '..HHBBJJBBHHHH..',
        '..HHBBBBBBHHHH..',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '....TTTTTTTT....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'pastry_layers', role: 'head' },
        B: { name: 'inner_swirl', role: 'body' },
        J: { name: 'jam_center', role: 'accessory' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. SCONE ──────────────────────────────────────────────────
    {
      id: 'scone_16',
      description: 'Triangular scone with cranberry bits and a golden crumbly surface.',
      grid: [
        '................',
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHRHHH.....',
        '....HHHHHHHH....',
        '....HHRHHHRHH...',
        '...HHHHHHHHHH...',
        '...HHRHHHHRHHH..',
        '..HHHHHHHHHHHH..',
        '..HHRHHHHHRHHHH.',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'scone_body', role: 'head' },
        R: { name: 'cranberry_bits', role: 'accessory' },
        B: { name: 'bottom_crust', role: 'body' },
        T: { name: 'napkin', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 5. MACARON ────────────────────────────────────────────────
    {
      id: 'macaron_16',
      description: 'Colorful French macaron sandwich with smooth shell halves and cream filling.',
      grid: [
        '................',
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '..FFFFFFFFFFFF..',
        '..CCCCCCCCCCCC..',
        '..FFFFFFFFFFFF..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_shell', role: 'head' },
        F: { name: 'foot_ruffle', role: 'arm' },
        C: { name: 'cream_filling', role: 'body' },
        B: { name: 'bottom_shell', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 6. CHURRO ─────────────────────────────────────────────────
    {
      id: 'churro_16',
      description: 'Ridged churro with sugar coating and cinnamon-brown fried dough.',
      grid: [
        '................',
        '.SSSSS..........',
        '.SHHHSS.........',
        '.SSHHHSS........',
        '..SSHHHSS.......',
        '...SSHHHSS......',
        '....SSHHHSS.....',
        '.....SSHHHSS....',
        '......SSHHHSS...',
        '.......SSHHHSS..',
        '........SSHHHS..',
        '.........SSHHS..',
        '..........SSSS..',
        '...........TT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dough_body', role: 'head' },
        S: { name: 'sugar_ridge', role: 'body' },
        T: { name: 'dipping_sauce', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. PALMIER ────────────────────────────────────────────────
    {
      id: 'palmier_16',
      description: 'Heart-shaped palmier pastry with caramelized golden-brown edges.',
      grid: [
        '................',
        '................',
        '..HHHH..HHHH....',
        '..HHSSHHHSSSHH..',
        '..HSSSSHSSSSSH..',
        '..HSSSSHSSSSSH..',
        '..HHSSSSSSSSHH..',
        '...HHSSSSSSSH...',
        '...HHSSSSSSSH...',
        '....HHSSSSHH....',
        '.....HHSSHH.....',
        '......HHHH......',
        '.......HH.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'caramel_edge', role: 'head' },
        S: { name: 'pastry_swirl', role: 'body' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 8. CREAM PUFF ────────────────────────────────────────────
    {
      id: 'cream_puff_16',
      description: 'Round cream puff with powdered sugar dusting and pastry shell.',
      grid: [
        '................',
        '................',
        '.....PPPPPP.....',
        '....PPPPPPPP....',
        '...PHHHHHHHPP...',
        '...HHHHHHHHHHP..',
        '..HHHHHHHHHHHP..',
        '..HHHHHHHHHHHP..',
        '..HHHHHHHHHHH...',
        '..CCCCCCCCCCC...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'powdered_sugar', role: 'accessory' },
        H: { name: 'choux_shell', role: 'head' },
        C: { name: 'cream_layer', role: 'body' },
        T: { name: 'doily', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 9. STRUDEL ────────────────────────────────────────────────
    {
      id: 'strudel_16',
      description: 'Sliced apple strudel showing flaky layers, apple filling, and dusted top.',
      grid: [
        '................',
        '................',
        '...PPPPPPPPPP...',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHFFAFFAHHHH..',
        '..HHFAFFAFHHHHF.',
        '..HHFFAFFAFFFFF.',
        '..HHHFAFAFFAAFF.',
        '..HHHHHHHFFAFFF.',
        '...HHHHHHFFFFFF.',
        '...BBBBBBBBBBB..',
        '....TTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'sugar_dust', role: 'accessory' },
        H: { name: 'pastry_layers', role: 'head' },
        F: { name: 'apple_filling', role: 'body' },
        A: { name: 'apple_chunks', role: 'arm' },
        B: { name: 'bottom_crust', role: 'belt' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 10. BAKLAVA ───────────────────────────────────────────────
    {
      id: 'baklava_16',
      description: 'Diamond-shaped baklava piece with golden phyllo layers, honey glaze, and pistachio bits.',
      grid: [
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHGGGGHHH...',
        '...HHHGNNGHHH...',
        '..HHHHGNNGGHHHH.',
        '..HHHHGGGGGHHHH.',
        '...HHHGGGGHHH...',
        '....HHHHHHHHH...',
        '.....HHHHHH.....',
        '......HHHH......',
        '.......HH.......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'phyllo_layers', role: 'head' },
        G: { name: 'honey_glaze', role: 'body' },
        N: { name: 'pistachio_nuts', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 11. APPLE PIE ─────────────────────────────────────────────
    {
      id: 'apple_pie_16',
      description: 'Lattice-top apple pie in a dish with golden crust and apple filling peeking through.',
      grid: [
        '................',
        '................',
        '...LLHLLHLLHL...',
        '..LHLLHLLHLLHL..',
        '..HLLHLLHLLHLL..',
        '..LHLLHLLHLLHL..',
        '..LLHLLHLLHLLH..',
        '..LHLLHLLHLLHL..',
        '..HLLHLLHLLHLL..',
        '..LHLLHLLHLLHL..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lattice_crust', role: 'head' },
        H: { name: 'apple_filling', role: 'body' },
        C: { name: 'crust_rim', role: 'arm' },
        D: { name: 'dish_side', role: 'belt' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 12. BERRY PIE ─────────────────────────────────────────────
    {
      id: 'berry_pie_16',
      description: 'Berry pie with crimped crust edges and dark berry filling visible in the center.',
      grid: [
        '................',
        '................',
        '...CCCCCCCCCC...',
        '..CCCCCCCCCCCC..',
        '..CCBBBBBBBBCC..',
        '..CCBBBEBBBBCC..',
        '..CCBBBBBBBKCC..',
        '..CCBBBKBBBBCC..',
        '..CCBBBBBBEBCC..',
        '..CCBBBBBBBBCC..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'pie_crust', role: 'head' },
        B: { name: 'berry_filling', role: 'body' },
        E: { name: 'berry_shine', role: 'eye' },
        K: { name: 'berry_seed', role: 'accessory' },
        D: { name: 'dish_side', role: 'belt' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. PUMPKIN PIE ───────────────────────────────────────────
    {
      id: 'pumpkin_pie_16',
      description: 'Orange pumpkin pie with a dollop of whipped cream on one slice.',
      grid: [
        '................',
        '......WW........',
        '.....WWWW.......',
        '......WW........',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'whipped_cream', role: 'accessory' },
        P: { name: 'pumpkin_filling', role: 'head' },
        C: { name: 'pie_crust', role: 'body' },
        D: { name: 'dish_side', role: 'arm' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 14. PECAN PIE ─────────────────────────────────────────────
    {
      id: 'pecan_pie_16',
      description: 'Pecan pie showing pecan halves arranged on glossy caramel filling.',
      grid: [
        '................',
        '................',
        '...CCCCCCCCCC...',
        '..CCCCCCCCCCCC..',
        '..CCNNNNNNNNCC..',
        '..CCNGGNGGNCC...',
        '..CCNNNNNNNNCC..',
        '..CCNGGNGGNCC...',
        '..CCNNNNNNNNCC..',
        '..CCNGGNGGNCC...',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'pie_crust', role: 'head' },
        N: { name: 'caramel_fill', role: 'body' },
        G: { name: 'pecan_halves', role: 'accessory' },
        D: { name: 'dish_side', role: 'arm' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. LEMON MERINGUE PIE ────────────────────────────────────
    {
      id: 'lemon_meringue_pie_16',
      description: 'Pie with tall white meringue peaks over bright yellow lemon curd.',
      grid: [
        '................',
        '.....MM..MM.....',
        '....MMMMMMMM....',
        '...MMMMMMMMMM...',
        '..MMMMMMMMMMMMM.',
        '..MMMMMMMMMMMM..',
        '..LLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'meringue_peaks', role: 'head' },
        L: { name: 'lemon_curd', role: 'body' },
        C: { name: 'pie_crust', role: 'arm' },
        D: { name: 'dish_side', role: 'belt' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 16. CREAM PIE ─────────────────────────────────────────────
    {
      id: 'cream_pie_16',
      description: 'Cream pie with swirled whipped topping and golden graham crust.',
      grid: [
        '................',
        '................',
        '....WWWWWWWW....',
        '...WWWWWWWWWW...',
        '..WWWWWWWWWWWW..',
        '..WWWWWWWWWWWW..',
        '..FFFFFFFFFFFL..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'whipped_top', role: 'head' },
        F: { name: 'cream_filling', role: 'body' },
        L: { name: 'filling_shine', role: 'eye' },
        C: { name: 'graham_crust', role: 'arm' },
        D: { name: 'dish_side', role: 'belt' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 17. QUICHE ────────────────────────────────────────────────
    {
      id: 'quiche_16',
      description: 'Savory quiche with golden egg custard, red pepper bits, and green herb flecks.',
      grid: [
        '................',
        '................',
        '...CCCCCCCCCC...',
        '..CCCCCCCCCCCC..',
        '..CCEEEEEEECC...',
        '..CCERREEEEECC..',
        '..CCEEEGEEECC...',
        '..CCEEEEEREECC..',
        '..CCEEGEEEEECC..',
        '..CCEEEEEEECC...',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'pie_crust', role: 'head' },
        E: { name: 'egg_custard', role: 'body' },
        R: { name: 'red_pepper', role: 'accessory' },
        G: { name: 'herb_fleck', role: 'arm' },
        D: { name: 'dish_side', role: 'belt' },
        T: { name: 'dish_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 18. POT PIE ───────────────────────────────────────────────
    {
      id: 'pot_pie_16',
      description: 'Golden pot pie with flaky dome crust, steam vent, and ceramic ramekin.',
      grid: [
        '................',
        '.....SS..SS.....',
        '......SSSS......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHVHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..CCCCCCCCCCCC..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        H: { name: 'dome_crust', role: 'head' },
        V: { name: 'steam_vent', role: 'eye' },
        C: { name: 'crust_rim', role: 'body' },
        R: { name: 'ramekin', role: 'arm' },
        T: { name: 'ramekin_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. HAND PIE ──────────────────────────────────────────────
    {
      id: 'hand_pie_16',
      description: 'Semi-circular hand pie with crimped edge and golden baked crust.',
      grid: [
        '................',
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHFFFFFFHHH..',
        '..HHFFFEFFFHHH..',
        '..HHFFFFFFHHHH..',
        '..HHHFFFFFFHHH..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '...CCCCCCCCCC...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'crust_shell', role: 'head' },
        F: { name: 'fruit_filling', role: 'body' },
        E: { name: 'filling_shine', role: 'eye' },
        C: { name: 'crimped_edge', role: 'arm' },
        T: { name: 'napkin', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 20. TART SHELL ────────────────────────────────────────────
    {
      id: 'tart_shell_16',
      description: 'Empty tart shell showing fluted edges and smooth golden interior.',
      grid: [
        '................',
        '................',
        '................',
        '..FHHHHHHHHHF...',
        '..FHHHHHHHHHF...',
        '..FHHIIIIIIHHF..',
        '..FHIIIIIIIIHF..',
        '..FHIIIIIIIIIF..',
        '..FHIIIEIIIIHF..',
        '..FHIIIIIIIIIF..',
        '..FHIIIIIIIIHF..',
        '..FHHIIIIIIHHF..',
        '..FFHHHHHHHHFF..',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'fluted_edge', role: 'head' },
        H: { name: 'crust_wall', role: 'body' },
        I: { name: 'interior', role: 'arm' },
        E: { name: 'interior_shine', role: 'eye' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
