/**
 * Bakery batch 4 — 20 cookie, muffin & small bake templates.
 * Covers: sugar cookie, chocolate chip cookie, oatmeal cookie, shortbread,
 *         biscotti, macaroon, thumbprint cookie, snickerdoodle,
 *         blueberry muffin, chocolate muffin, bran muffin, lemon poppy muffin,
 *         corn muffin, cranberry scone, buttermilk biscuit, donut holes,
 *         bear claw, rugelach, madeleine, profiterole.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'BAKERY_BATCH4_TEMPLATES', schemes: 'BAKERY_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SUGAR COOKIE ───────────────────────────────────────────
    {
      id: 'sugar_cookie_16',
      description: 'Round sugar cookie with pastel sprinkles and golden baked edge.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHHHHHH....',
        '...HHHHSHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHSHHHHHSHH...',
        '..HHHHHHHHHHH...',
        '..HHHSHHSHHHHH..',
        '..HHHHHHHHHHH...',
        '..HHSHHHHSHHHH..',
        '..HHHHHHHHHHHH..',
        '...HHHSHHHHH....',
        '....HHHHHHHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cookie_dough', role: 'head' },
        S: { name: 'sprinkle', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#dad45e' },
      },
    },

    // ─── 2. CHOCOLATE CHIP COOKIE ──────────────────────────────────
    {
      id: 'chocolate_chip_cookie_16',
      description: 'Classic round cookie with dark chocolate chips scattered across golden dough.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHCHHCH....',
        '...HHHHHHHHHHH..',
        '..HHCHHHHHCHH...',
        '..HHHHHCHHHHHH..',
        '..HHHHHHHHCHHH..',
        '..HCHHHHHHHHHH..',
        '..HHHHHCHHHCHH..',
        '..HHCHHHHHHHHH..',
        '..HHHHHHHCHHH...',
        '...HHCHHHHHH....',
        '....HHHHHHHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cookie_dough', role: 'head' },
        C: { name: 'chocolate_chip', role: 'body' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. OATMEAL COOKIE ─────────────────────────────────────────
    {
      id: 'oatmeal_cookie_16',
      description: 'Textured oatmeal cookie with dark raisins and rough surface.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHTHHTHH...',
        '...HTHHHHHHTHH..',
        '..HHTHRHHHHTHH..',
        '..HTHHHHRHTHH...',
        '..HTHHTHHHHTHH..',
        '..HHTHHHRTHHH...',
        '..HTHHRHHHTHH...',
        '..HHTHHHHHTHHH..',
        '..HTHHTHHRHTH...',
        '...HTHHHHTHH....',
        '....HHTHHTHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'oatmeal_dough', role: 'head' },
        T: { name: 'oat_texture', role: 'body' },
        R: { name: 'raisin', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 4. SHORTBREAD ─────────────────────────────────────────────
    {
      id: 'shortbread_16',
      description: 'Rectangular shortbread finger with fork-prick marks and golden surface.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HFHFHFHFHFHH..',
        '..HHHHHHHHHHHH..',
        '..HFHFHFHFHFHH..',
        '..HHHHHHHHHHHH..',
        '..HFHFHFHFHFHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'shortbread_top', role: 'head' },
        F: { name: 'fork_marks', role: 'accessory' },
        B: { name: 'shortbread_side', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 5. BISCOTTI ───────────────────────────────────────────────
    {
      id: 'biscotti_16',
      description: 'Twice-baked biscotti showing cross-section with almond slices visible.',
      grid: [
        '................',
        '..HH............',
        '..HHH...........',
        '..HHHHH.........',
        '..HHHHHH........',
        '..HAHHHHH.......',
        '..BBAHHHHH......',
        '..BBBAHHHHHH....',
        '..BBBBAHHHHHH...',
        '..BBBBBAHHHHHH..',
        '..BBBBBBAHHHH...',
        '..BBBABBBAHHH...',
        '..BBBBBBBBBHH...',
        '..BBBBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'crust_top', role: 'head' },
        B: { name: 'cross_section', role: 'body' },
        A: { name: 'almond_slice', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 6. COCONUT MACAROON ───────────────────────────────────────
    {
      id: 'macaroon_16',
      description: 'Rounded coconut macaroon with shredded texture and toasted golden top.',
      grid: [
        '................',
        '................',
        '.....TTTTTTT....',
        '....TTTTTTTTTT..',
        '...TTTTTTTTTTT..',
        '..TTTTTTTTTTTT..',
        '..SSHSHSHHSHSS..',
        '..SHSHSHSHSHSS..',
        '..SSHSHSHHSHSS..',
        '..SHSHSHSHSHSS..',
        '..SSHSHSHHSHSS..',
        '...SHSHSHSHSHS..',
        '....SSSSSSSSSS..',
        '.....BBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'toasted_top', role: 'head' },
        S: { name: 'shredded_coconut', role: 'body' },
        H: { name: 'coconut_highlight', role: 'accessory' },
        B: { name: 'chocolate_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 7. THUMBPRINT COOKIE ──────────────────────────────────────
    {
      id: 'thumbprint_cookie_16',
      description: 'Round butter cookie with a jam-filled center indent.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHHHHHH....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHH...',
        '..HHHHJJJJHHH...',
        '.HHHJJJJJJJHHH..',
        '.HHHJJJJSJJHHH..',
        '.HHHJJJJJJJHHH..',
        '..HHHHJJJJHHH...',
        '..HHHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'butter_dough', role: 'head' },
        J: { name: 'jam_filling', role: 'body' },
        S: { name: 'jam_shine', role: 'eye' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 8. SNICKERDOODLE ──────────────────────────────────────────
    {
      id: 'snickerdoodle_16',
      description: 'Cracked-surface snickerdoodle with cinnamon sugar coating.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHHHHHH....',
        '...CHHCHHCHHHH..',
        '..CHHHHHHHCHH...',
        '..HHHCHHHHHHCH..',
        '..HCHHHHCHHHHH..',
        '..HHHHHHHHHCHH..',
        '..HHCHHHHHHHH...',
        '..HHHHHCHHHCHH..',
        '..HHCHHHHHHHH...',
        '...HHHCHHCHH....',
        '....HHHHHHHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cookie_surface', role: 'head' },
        C: { name: 'crack_line', role: 'body' },
      },
      colors: {
        head: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 9. BLUEBERRY MUFFIN ───────────────────────────────────────
    {
      id: 'blueberry_muffin_16',
      description: 'Domed blueberry muffin in paper wrapper with visible blueberry spots.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HBHHHHHH....',
        '...HHHHHBHHHH...',
        '...HHBHHHHHBH...',
        '...HHHHHBHHHH...',
        '...HHHHHHHHHH...',
        '...WWWWWWWWWW...',
        '...WMMMMMMMW....',
        '...WMMMBMMMW....',
        '...WMMMMMMMW....',
        '....WMMMMWW.....',
        '.....WWWWW......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'muffin_dome', role: 'head' },
        B: { name: 'blueberry', role: 'accessory' },
        W: { name: 'paper_wrapper', role: 'body' },
        M: { name: 'muffin_body', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 10. CHOCOLATE MUFFIN ──────────────────────────────────────
    {
      id: 'chocolate_muffin_16',
      description: 'Dark chocolate muffin with chocolate chips and cracked domed top.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHCHHHHH....',
        '...HHHHHCHHHHH..',
        '...HHCHHHHHCHH..',
        '...HHHHHCHHHH...',
        '...HHHHHHHHHH...',
        '...WWWWWWWWWW...',
        '...WBBBBBBBBW...',
        '...WBBCBBBBCW...',
        '...WBBBBBBBW....',
        '....WBBBBWW.....',
        '.....WWWWW......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'choc_dome', role: 'head' },
        C: { name: 'choc_chip', role: 'accessory' },
        W: { name: 'paper_liner', role: 'body' },
        B: { name: 'choc_body', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 11. BRAN MUFFIN ───────────────────────────────────────────
    {
      id: 'bran_muffin_16',
      description: 'Dense bran muffin with rough textured top and brown paper wrapper.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HTHHHTHH....',
        '...HHHHTHHHTH...',
        '...HTHHHHHHTH...',
        '...HHTHHHTHH....',
        '...HHHHHHHHHH...',
        '...WWWWWWWWWW...',
        '...WBBBBBBBBW...',
        '...WBBBBBBBW....',
        '...WBBBBBBBW....',
        '....WBBBWWW.....',
        '.....WWWWW......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bran_dome', role: 'head' },
        T: { name: 'bran_texture', role: 'accessory' },
        W: { name: 'brown_wrapper', role: 'body' },
        B: { name: 'bran_body', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. LEMON POPPY MUFFIN ────────────────────────────────────
    {
      id: 'lemon_poppy_muffin_16',
      description: 'Bright yellow lemon muffin dotted with tiny poppy seeds.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HPHHHPHH....',
        '...HHHPHHHHPH...',
        '...HPHHHHPHPH...',
        '...HHPHPHHHHH...',
        '...HHHHHHHHHH...',
        '...WWWWWWWWWW...',
        '...WMMMMMMMMW...',
        '...WMPMMMPMW....',
        '...WMMMMMMW.....',
        '....WMMMWWW.....',
        '.....WWWWW......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lemon_dome', role: 'head' },
        P: { name: 'poppy_seed', role: 'accessory' },
        W: { name: 'paper_cup', role: 'body' },
        M: { name: 'lemon_body', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 13. CORN MUFFIN ───────────────────────────────────────────
    {
      id: 'corn_muffin_16',
      description: 'Golden yellow corn muffin with a crumbly textured dome.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '...HHHHSHHHHHH..',
        '...HHHHHHHSHH...',
        '...HHSHHHHHHHH..',
        '...HHHHHHHHHH...',
        '...WWWWWWWWWW...',
        '...WBBBBBBBBW...',
        '...WBBBBBBBW....',
        '...WBBBBBBBW....',
        '....WBBBWWW.....',
        '.....WWWWW......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'corn_dome', role: 'head' },
        S: { name: 'crumb_highlight', role: 'eye' },
        W: { name: 'paper_wrap', role: 'body' },
        B: { name: 'corn_body', role: 'arm' },
      },
      colors: {
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:  { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        body: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. CRANBERRY SCONE ───────────────────────────────────────
    {
      id: 'cranberry_scone_16',
      description: 'Triangular scone wedge with red cranberry bits and golden glaze.',
      grid: [
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HRHHHH.....',
        '....HHHHRHHH....',
        '....HHHHHHHH....',
        '...HHRHHHHRHHH..',
        '...HHHHHHHHHHH..',
        '..HHRHHHHHHRHH..',
        '..HHHHHHRHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'scone_body', role: 'head' },
        R: { name: 'cranberry_bit', role: 'accessory' },
        B: { name: 'scone_base', role: 'body' },
        G: { name: 'sugar_glaze', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 15. BUTTERMILK BISCUIT ────────────────────────────────────
    {
      id: 'buttermilk_biscuit_16',
      description: 'Fluffy split biscuit showing layered flaky interior with golden top.',
      grid: [
        '................',
        '................',
        '....TTTTTTTT....',
        '...TTTTTTTTTT...',
        '..TTTTTTTTTTTT..',
        '..TTTTTTTTTTTT..',
        '..LLLLLLLLLLLL..',
        '..HHHHHHHHHHHH..',
        '..LLLLLLLLLLLL..',
        '..HHHHHHHHHHHH..',
        '..LLLLLLLLLLLL..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'golden_top', role: 'head' },
        H: { name: 'biscuit_layer', role: 'body' },
        L: { name: 'layer_line', role: 'arm' },
        B: { name: 'biscuit_base', role: 'boot' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 16. DONUT HOLES ───────────────────────────────────────────
    {
      id: 'donut_hole_16',
      description: 'Three round donut holes coated in sugar, arranged in a triangle.',
      grid: [
        '................',
        '................',
        '.....SSSHHHH....',
        '....SSSSHHHHHH..',
        '....SSSSHHHHHH..',
        '....SSSSHHHHHH..',
        '.....SSSHHHH....',
        '................',
        '....BBBBBB......',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'hole_left', role: 'head' },
        H: { name: 'hole_right', role: 'body' },
        B: { name: 'hole_bottom', role: 'arm' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 17. BEAR CLAW ─────────────────────────────────────────────
    {
      id: 'bear_claw_16',
      description: 'Bear claw pastry with sliced almond top and sugar glaze.',
      grid: [
        '................',
        '................',
        '....AAAAAAAAAA..',
        '...AHHAHHAHHAA..',
        '..HHHHHHHHHHHHH.',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HBBHBBHBBHHH..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBB....',
        '....BB..BB.BB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'almond_slices', role: 'accessory' },
        H: { name: 'pastry_body', role: 'head' },
        B: { name: 'pastry_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. RUGELACH ──────────────────────────────────────────────
    {
      id: 'rugelach_16',
      description: 'Crescent-shaped rugelach with chocolate filling peeking out.',
      grid: [
        '................',
        '................',
        '................',
        '..........HH....',
        '.........HHHH...',
        '........HHHHHH..',
        '.......HHHFHHH..',
        '......HHHFFHHH..',
        '.....HHHHFFHHHH.',
        '....HHHHFHHHHH..',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '..BBBBBBBBBB....',
        '...BBBBBBB......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'pastry_dough', role: 'head' },
        F: { name: 'chocolate_fill', role: 'body' },
        B: { name: 'sugar_base', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 19. MADELEINE ─────────────────────────────────────────────
    {
      id: 'madeleine_16',
      description: 'Shell-shaped madeleine cookie with scalloped edge and golden surface.',
      grid: [
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HRHRHH.....',
        '....HRHRHRHH....',
        '...HRHRHRHRHH...',
        '...HRHRHRHRHH...',
        '..HRHRHRHRHRHH..',
        '..HRHRHRHRHRHH..',
        '..HRHRHRHRHRHH..',
        '..HHHHHHHHHHHHH.',
        '...BBBBBBBBBBB..',
        '....BBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'madeleine_body', role: 'head' },
        R: { name: 'shell_ridge', role: 'body' },
        B: { name: 'golden_base', role: 'arm' },
      },
      colors: {
        head: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. PROFITEROLE ───────────────────────────────────────────
    {
      id: 'profiterole_16',
      description: 'Cream puff profiterole with chocolate drizzle on top and cream filling visible.',
      grid: [
        '................',
        '................',
        '.....CCCCCC.....',
        '....CCCCCCCC....',
        '...CCHCCCHCCC...',
        '..CCCCCCCCCCCC..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHHHHHHHHHH..',
        '..HFFFFFFFFFFH..',
        '..HHFFSFFSFFHH..',
        '..HHFFFFFFFFHH..',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'chocolate_drizzle', role: 'accessory' },
        H: { name: 'choux_pastry', role: 'head' },
        F: { name: 'cream_filling', role: 'body' },
        S: { name: 'cream_shine', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
