/**
 * Bosses batch 1 — 20 unique boss templates.
 * Diverse genres: RPG dragons, sci-fi mechs, horror abominations, puzzle guardians.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'bosses',
  exportNames: { templates: 'BOSS_BATCH1_TEMPLATES', schemes: 'BOSS_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. DRAGON LORD — classic RPG winged dragon ───────────────
    {
      id: 'dragon_lord_16',
      description: 'Large winged dragon boss with horns, spread wings, thick tail.',
      grid: [
        '..XX............',
        '..XHHH..........',
        '...HEHH.........',
        '...HHFH.........',
        'WWWWBBBBWWWW....',
        '.WWWBBBBWWW.....',
        '..WWBBBBWW......',
        '...WBBBBW.......',
        '....BBBB........',
        '....BBBB........',
        '...AABBBA.......',
        '...LLLLLL.......',
        '...L....L.......',
        '..TT....TT......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        X: { name: 'horns', role: 'accessory' },
        F: { name: 'snout', role: 'face' },
        B: { name: 'body', role: 'body' },
        W: { name: 'wings', role: 'arm' },
        A: { name: 'belly', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'claws', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        face:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. MECHA TITAN — sci-fi giant robot boss ─────────────────
    {
      id: 'mecha_titan_16',
      description: 'Giant bipedal mech with armored torso, glowing eye visor, cannons.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HEEEHH......',
        '....HHHHHH......',
        '...XBBBBBBX.....',
        '..XXBBBBBBXX....',
        '..X.BBBBBB.X....',
        '....BBAABB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....LLLL.......',
        '....LL..LL......',
        '...LL....LL.....',
        '...TT....TT.....',
        '..TTT....TTT....',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        B: { name: 'chassis', role: 'body' },
        X: { name: 'cannons', role: 'arm' },
        A: { name: 'core', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#8595a1' },
      },
    },

    // ─── 3. LICH KING — undead sorcerer with crown ────────────────
    {
      id: 'lich_king_16',
      description: 'Skeletal lich wearing tattered robes and glowing crown.',
      grid: [
        '....XXXXXX......',
        '....XHHHHX......',
        '.....HEHEH......',
        '.....HHFFH......',
        '.....HHHH.......',
        '....ABBBBA......',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....LLLLLL......',
        '....TT..TT......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'skull', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'jaw', role: 'face' },
        X: { name: 'crown', role: 'accessory' },
        B: { name: 'robes', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 4. KRAKEN — sea monster with tentacles ───────────────────
    {
      id: 'kraken_16',
      description: 'Giant squid/kraken with bulbous head, large eyes, reaching tentacles.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHHEHHEH.....',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..LBBBBBBBBR....',
        '.LL.BBBBBB.RR...',
        'L...LLLLLL...R..',
        '...LL.LL.LL.....',
        '..L...LL...L....',
        '.L....LL....L...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        L: { name: 'tentacles_l', role: 'arm' },
        R: { name: 'tentacles_r', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        arm:       { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 5. DEMON PRINCE — horned winged demon ────────────────────
    {
      id: 'demon_prince_16',
      description: 'Muscular demon with curved horns, bat wings, cloven hooves.',
      grid: [
        '.X........X.....',
        '..X.HHHH.X......',
        '...HHEEHH.......',
        '...HHFFHH.......',
        'WW..BBBB..WW....',
        '.WW.BBBB.WW.....',
        '..WWBBBBWW......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BBBB........',
        '....LLLL........',
        '...LL..LL.......',
        '...L....L.......',
        '..TT....TT......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        X: { name: 'horns', role: 'accessory' },
        B: { name: 'torso', role: 'body' },
        W: { name: 'wings', role: 'arm' },
        A: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'hooves', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 6. SLIME KING — huge gelatinous blob with crown ──────────
    {
      id: 'slime_king_16',
      description: 'Massive slime blob wearing a tiny crown, with a smiling face.',
      grid: [
        '................',
        '......XX........',
        '.....XXXX.......',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHHH....',
        '..HHHHHFFHHH....',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        'BBBBBBBBBBBBBB..',
        'BBBBBBBBBBBBBB..',
        '.BBBBBBBBBBBB...',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crown', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'body', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 7. SPIDER MATRIARCH — horror giant spider ────────────────
    {
      id: 'spider_matriarch_16',
      description: 'Giant armored spider boss with fangs and glowing eyes.',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHEEEHH......',
        '...HHHFFHH......',
        '...HHHHHHH......',
        'L.LHBBBBHR.R....',
        '.LL.BBBBBB.RR...',
        'L..BBBBBBBB..R..',
        '...BBBBBBBB.....',
        '.L.BBBBBBBB.R...',
        'L...BBBBBB...R..',
        '.....BBBB.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'fangs', role: 'face' },
        B: { name: 'abdomen', role: 'body' },
        L: { name: 'legs_left', role: 'arm' },
        R: { name: 'legs_right', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 8. GOLEM GUARDIAN — stone/puzzle boss ────────────────────
    {
      id: 'golem_guardian_16',
      description: 'Massive stone golem with glowing rune core, heavy arms.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HEEHEH......',
        '....HHHHHH......',
        '..AABBBBBBAA....',
        '.AA.BBXBBB.AA...',
        '.A..BBBBBB..A...',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....LLLL.......',
        '....LL..LL......',
        '...LL....LL.....',
        '...TT....TT.....',
        '..TTT....TTT....',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        X: { name: 'rune_core', role: 'accessory' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 9. PHOENIX BOSS — fire bird ──────────────────────────────
    {
      id: 'phoenix_boss_16',
      description: 'Majestic fire phoenix with spread wings, flowing tail feathers.',
      grid: [
        '......HH........',
        '.....HHHH.......',
        '....HHEHH.......',
        '....HHFHH.......',
        '..WWBBBBWW......',
        '.WWWBBBBWWW.....',
        'WWWWBBBBWWWW....',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....LLLL.......',
        '.....L..L.......',
        '....TT..TT......',
        '....XXXXX.......',
        '...XXXXXXX......',
        '..XXXXXXXXX.....',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'beak', role: 'face' },
        B: { name: 'body', role: 'body' },
        W: { name: 'wings', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'talons', role: 'boot' },
        X: { name: 'tail', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. HYDRA — multi-headed serpent ─────────────────────────
    {
      id: 'hydra_16',
      description: 'Three-headed hydra with serpentine necks and scaled body.',
      grid: [
        '.HH..HH..HH.....',
        '.HEH.HEH..HEH...',
        '..HH..HH..HH....',
        '...N..NN..N.....',
        '....NNNNNN......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....BBBB.......',
        '....LLLLLL......',
        '...TT....TT.....',
        '..TT......TT....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'heads', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        N: { name: 'necks', role: 'face' },
        B: { name: 'body', role: 'body' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'tail', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#442434', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 11. SHADOW LORD — dark ethereal boss ─────────────────────
    {
      id: 'shadow_lord_16',
      description: 'Dark shadowy figure with glowing eyes, flowing dark robes.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HEEHEH......',
        '....HHHHHH......',
        '...AABBBBA......',
        '..AA.BBBB.AA....',
        '.AA..BBBB..AA...',
        '.A...BBBB...A...',
        '.....BBBB.......',
        '....LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '.LLLLLLLLLLLL...',
        'LLLLLLLLLLLLLL..',
        '................',
      ],
      chars: {
        H: { name: 'hood', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'robes', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        leg:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 12. ICE QUEEN — frost boss ──────────────────────────────
    {
      id: 'ice_queen_16',
      description: 'Elegant ice queen with crystal crown, flowing frost gown.',
      grid: [
        '....XXXXXX......',
        '....XHHHHX......',
        '.....RRHH.......',
        '....HHEEHH......',
        '....HHFFHH......',
        '...AABBBBAA.....',
        '..AA.BBBB.AA....',
        '.A...GGBB...A...',
        '.....BBBB.......',
        '....LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '.LLLLLLLLLLLL...',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crown', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        R: { name: 'hair', role: 'hair' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'torso', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'gown', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        face:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
      },
    },

    // ─── 13. WORM BOSS — giant tunnel worm ────────────────────────
    {
      id: 'worm_boss_16',
      description: 'Massive segmented worm boss emerging from ground with open maw.',
      grid: [
        '....HHHHHH......',
        '...HHFFFFHH.....',
        '..HHFFFFFFHH....',
        '..HHEEFFEEHHH...',
        '..HHFFFFFFHH....',
        '...HHHHHHHH.....',
        '....BBBBBB......',
        '...BXBBBBXB.....',
        '....BBBBBB......',
        '...BXBBBBXB.....',
        '....BBBBBB......',
        '.....BBBB.......',
        '......BB........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head_shell', role: 'head' },
        F: { name: 'maw', role: 'face' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'segments', role: 'body' },
        X: { name: 'spikes', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        face:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 14. DARK KNIGHT — armored boss ──────────────────────────
    {
      id: 'dark_knight_boss_16',
      description: 'Imposing armored knight with massive sword and horned helm.',
      grid: [
        '.X...HH..X......',

        '....HHHH........',
        '....HEHEH.......',
        '....HHHHHH......',
        '...AABBBBBB.....',
        '..AA.BBGGBB.....',
        '..A..BBBBBB.S...',
        '.....BBBBBB.S...',
        '.....BBBBBBSS...',
        '.....BBBBBB.....',
        '....LLLLLL......',
        '....LL..LL......',
        '...LL....LL.....',
        '...TT....TT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'horns', role: 'accessory' },
        H: { name: 'helm', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        A: { name: 'shield_arm', role: 'arm' },
        S: { name: 'sword', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 15. MUSHROOM KING — farming/RPG boss ─────────────────────
    {
      id: 'mushroom_king_16',
      description: 'Giant sentient mushroom king with spotted crown-cap, angry face.',
      grid: [
        '...XXXXXXXXX....',
        '..XXHHHHHHHXX...',
        '.XXHXHHHHHXHXX..',
        '.XHHHHHHHHHHXX..',
        '..HHHHHHHHHH....',
        '...HHHEEHHHH....',
        '...HHHHFFHH.....',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '....LLLLLL......',
        '...TT....TT.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'cap_spots', role: 'accessory' },
        H: { name: 'cap', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'stem', role: 'body' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'roots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. WARSHIP — sci-fi ship boss ──────────────────────────
    {
      id: 'warship_boss_16',
      description: 'Alien warship boss with cannons and engine glow.',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHEHHEHH....',
        '...BHHHHHHHB....',
        '..BBBBBBBBBBB...',
        '.XBBBBBBBBBBX...',
        '.XBBBBGBBBBBX...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....AAAAAAA.....',
        '.....AAAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cockpit', role: 'head' },
        E: { name: 'windows', role: 'eye' },
        B: { name: 'hull', role: 'body' },
        X: { name: 'cannons', role: 'arm' },
        G: { name: 'core', role: 'accessory' },
        A: { name: 'engines', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#8595a1' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 17. TREANT ELDER — nature boss ──────────────────────────
    {
      id: 'treant_elder_16',
      description: 'Ancient tree boss with glowing eyes, branch arms, thick trunk.',
      grid: [
        '..XXXX.XXXX.....',
        '..XHHHHHHHX.....',
        '...HHHHHHHH.....',
        '...HHHEHHEH.....',
        '...HHHHHHHH.....',
        'AA..BBBBBB..AA..',
        '.AAA.BBBB.AAA...',
        '..AA.BBBB.AA....',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....LLLLLL......',
        '...LLLLLLLL.....',
        '..TTTTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'canopy', role: 'accessory' },
        H: { name: 'face_bark', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'trunk', role: 'body' },
        A: { name: 'branches', role: 'arm' },
        L: { name: 'roots', role: 'leg' },
        T: { name: 'root_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 18. VAMPIRE LORD — gothic horror boss ───────────────────
    {
      id: 'vampire_lord_16',
      description: 'Vampire lord with cape, fangs, slicked back hair, pale face.',
      grid: [
        '................',
        '.....RRRR.......',
        '....RRHHRR......',
        '....HHEEHH......',
        '....HHFFHH......',
        '..CCBBBBBBCC....',
        '.CC.BBGGBB.CC...',
        '.C..ABBBBA..C...',
        '.C..BBBBBB..C...',
        '.CC.BBBBBB.CC...',
        '..CCLLLLLLCC....',
        '....LL..LL......',
        '...TT....TT.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'suit', role: 'body' },
        G: { name: 'vest', role: 'belt' },
        A: { name: 'arms', role: 'arm' },
        C: { name: 'cape', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 19. CRYSTAL COLOSSUS — puzzle/RPG gem boss ──────────────
    {
      id: 'crystal_colossus_16',
      description: 'Towering crystal creature with prismatic facets and inner glow.',
      grid: [
        '......XX........',
        '.....XHHX.......',
        '....XHHHHX......',
        '...XHHEHHEX.....',
        '...XHHHHHX......',
        '..AXBBBBBBXA....',
        '.AA.BBBBBB.AA...',
        '.A..BBXXBB..A...',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....LLLL.......',
        '....LL..LL......',
        '...TT....TT.....',
        '..TT......TT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crystal_tips', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. PLAGUE DOCTOR — horror/action boss ──────────────────
    {
      id: 'plague_doctor_boss_16',
      description: 'Giant plague doctor with beak mask, tattered coat, scythe.',
      grid: [
        '................',
        '.....XHHHH......',
        '....XHHHHHH.....',
        '...XXHEHHH......',
        '.....HHHH.......',
        '...AABBBBBB.....',
        '..AA.BBGGBB.....',
        '.AA..BBBBBB.S...',
        '.A...BBBBBB.S...',
        '.....BBBBBBSS...',
        '.....BBBBBB.....',
        '....LLLLLL......',
        '....LL..LL......',
        '...TT....TT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'beak', role: 'face' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        A: { name: 'arms', role: 'arm' },
        S: { name: 'scythe', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
