/**
 * Buildings batch 1 — 20 new building/structure templates.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'buildings',
  exportNames: { templates: 'BUILDING_BATCH1_TEMPLATES', schemes: 'BUILDING_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TAVERN ──────────────────────────────────────────────
    {
      id: 'tavern_16',
      description: 'Small tavern with pitched roof, wooden walls, hanging sign, door.',
      grid: [
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BXXB....BXXB..',
        '..BXXB.GG.BXXB..',
        '..BBBB.GG.BXXB..',
        '..BXXB.GG.BBBB..',
        '..BXXB....BXXB..',
        '..BBBBBBBBBBBB..',
        '..TTTTTTTTTTTT..',
        '................',
        '......AA........',
        '......AA........',
      ],
      chars: {
        H: { name: 'roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        X: { name: 'windows', role: 'eye' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
        A: { name: 'sign', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. CASTLE TOWER ────────────────────────────────────────
    {
      id: 'castle_tower_16',
      description: 'Castle watchtower with battlements, arrow slit, stone walls.',
      grid: [
        '..HH.HH..HH.HH..',
        '..HHHHHHHHHHHH..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBXXBBBB...',
        '...BBBBXXBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBGGBBBB...',
        '...BBBBGGBBBB...',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        H: { name: 'battlements', role: 'head' },
        B: { name: 'stone_walls', role: 'body' },
        X: { name: 'arrow_slit', role: 'eye' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 3. WINDMILL ────────────────────────────────────────────
    {
      id: 'windmill_16',
      description: 'Windmill with rotating blades, stone base, wooden top.',
      grid: [
        '........XXXX....',
        '.....HH.XXXX....',
        '....HHHH.XX.....',
        '...HHHHHH.......',
        'XXXHHHHHHH......',
        'XXXXBBBBB.......',
        '.XXXBBBBB.......',
        '..XXBBBBB.......',
        '....BBBBB.......',
        '....BBBBB.......',
        '....BXXBB.......',
        '....BXXBB.......',
        '...BBBBBBB......',
        '..BBBGGBBBB.....',
        '..TTTTTTTTTT....',
        '................',
      ],
      chars: {
        X: { name: 'blades', role: 'accessory' },
        H: { name: 'top', role: 'head' },
        B: { name: 'body', role: 'body' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 4. SHOP ────────────────────────────────────────────────
    {
      id: 'shop_16',
      description: 'Small RPG shop with awning, display window, hanging sign.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BXXXXXXXXXXB..',
        '..BXXXXXXXXXXB..',
        '..BBBBBBBBBBBB..',
        '..BBBB.GG.BBBB..',
        '..BBBB.GG.BBBB..',
        '..BBBB....BBBB..',
        '..TTTTTTTTTTTT..',
        '................',
        '..AA............',
        '..AA............',
        '................',
      ],
      chars: {
        H: { name: 'awning', role: 'head' },
        B: { name: 'walls', role: 'body' },
        X: { name: 'display_window', role: 'eye' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'step', role: 'boot' },
        A: { name: 'sign', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. CHURCH ──────────────────────────────────────────────
    {
      id: 'church_16',
      description: 'Small church with steeple, cross, stained glass window, wooden door.',
      grid: [
        '.......XX.......',
        '......XXXX......',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBXXXXBBB...',
        '...BBBXXXXBBB...',
        '...BBBBBBBBBB...',
        '...BBBB..BBBB...',
        '...BBBBGGBBBB...',
        '...BBBBGGBBBB...',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        X: { name: 'cross_window', role: 'accessory' },
        H: { name: 'roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. BLACKSMITH ──────────────────────────────────────────
    {
      id: 'blacksmith_16',
      description: 'Blacksmith forge with chimney, anvil sign, open front.',
      grid: [
        '..XX............',
        '..XX............',
        '..XXHHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BB..........B.',
        '..BB.AAAA...BB..',
        '..BB.AAAA...BB..',
        '..BB........BB..',
        '..BBBBBBBBBBBB..',
        '..BBBBGGGGBBBB..',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'chimney', role: 'accessory' },
        H: { name: 'roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        A: { name: 'anvil', role: 'arm' },
        G: { name: 'opening', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 7. WELL ────────────────────────────────────────────────
    {
      id: 'well_16',
      description: 'Stone well with wooden roof, rope, bucket.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '....AA....AA....',
        '....AA.XX.AA....',
        '....AA.XX.AA....',
        '....AA....AA....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'roof', role: 'head' },
        A: { name: 'posts', role: 'arm' },
        X: { name: 'rope_bucket', role: 'accessory' },
        B: { name: 'stone_wall', role: 'body' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 8. LIGHTHOUSE ──────────────────────────────────────────
    {
      id: 'lighthouse_16',
      description: 'Tall lighthouse with beacon light, striped walls, rocky base.',
      grid: [
        '.......XX.......',
        '......XEEX......',
        '......XEEX......',
        '.......HH.......',
        '......HHHH......',
        '......BBBB......',
        '......BXXB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BXXBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...TTTTTTTTTT...',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        X: { name: 'light_windows', role: 'accessory' },
        E: { name: 'beacon', role: 'eye' },
        H: { name: 'gallery', role: 'head' },
        B: { name: 'tower', role: 'body' },
        T: { name: 'rocky_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. TENT ────────────────────────────────────────────────
    {
      id: 'tent_16',
      description: 'Canvas tent with peaked top, flap opening, guy ropes.',
      grid: [
        '................',
        '................',
        '.......XX.......',
        '......XHHX......',
        '.....XHHHHX.....',
        '....XHHHHHHX....',
        '...XBBBBBBBBX...',
        '..XBBBBBBBBBBX..',
        '.XBBBBBBBBBBBBX.',
        'XBBBBB.GG.BBBBBX',
        'XBBBBB.GG.BBBBBX',
        '.BBBBB....BBBBB.',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'frame_ropes', role: 'accessory' },
        H: { name: 'peak', role: 'head' },
        B: { name: 'canvas', role: 'body' },
        G: { name: 'flap', role: 'belt' },
        T: { name: 'ground', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. BARN ───────────────────────────────────────────────
    {
      id: 'barn_16',
      description: 'Red barn with hayloft, double doors, silo.',
      grid: [
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBXXBBBBXXBB..',
        '..BBXXBBBBXXBB..',
        '..BBBBBBBBBBBB..',
        '..BBBGGGGGGBBB..',
        '..BBBGG..GGBBB..',
        '..BBBGG..GGBBB..',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        X: { name: 'windows', role: 'eye' },
        G: { name: 'barn_doors', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 11. WIZARD TOWER ───────────────────────────────────────
    {
      id: 'wizard_tower_16',
      description: 'Wizard tower with pointed hat-roof, magical window, crystal top.',
      grid: [
        '.......XX.......',
        '......XAAX......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBXXXXBB....',
        '....BBXXXXBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBGGGGBBB...',
        '...BBBGGGGBBB...',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        X: { name: 'crystal_window', role: 'accessory' },
        A: { name: 'crystal_top', role: 'eye' },
        H: { name: 'roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 12. RUINS ──────────────────────────────────────────────
    {
      id: 'ruins_16',
      description: 'Crumbled stone ruins with broken columns, overgrown vines.',
      grid: [
        '..BB........BB..',
        '..BB...XX...BB..',
        '..BB...XX...BB..',
        '..BB........BB..',
        '..BB........BB..',
        '..BB........BB..',
        '..BBBB..BBBBBB..',
        '..BBBB..BBBB....',
        '..BBBBBBBBB.....',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '..TTTTTTTTTT....',
        '..TTTTTTTTTT....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'stone', role: 'body' },
        X: { name: 'vines', role: 'accessory' },
        T: { name: 'rubble', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 13. COTTAGE ────────────────────────────────────────────
    {
      id: 'cottage_16',
      description: 'Cozy cottage with thatched roof, chimney, flower box.',
      grid: [
        '..XX............',
        '..XX.HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BXXBB..BXXBB..',
        '..BXXBB..BXXBB..',
        '..BBBB.GG.BBBB..',
        '..BBBB.GG.BBBB..',
        '..BBBB....BBBB..',
        '..TTTTTTTTTTTT..',
        '..AAAAAAAAAAAA..',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'chimney_windows', role: 'accessory' },
        H: { name: 'thatch_roof', role: 'head' },
        B: { name: 'walls', role: 'body' },
        G: { name: 'door', role: 'belt' },
        T: { name: 'foundation', role: 'boot' },
        A: { name: 'flower_box', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. WATCHTOWER ─────────────────────────────────────────
    {
      id: 'watchtower_16',
      description: 'Wooden watchtower with platform, ladder, torch.',
      grid: [
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...HH......HH...',
        '...AABBBBBBAA...',
        '...AA.BBBB.AA...',
        '...AA.BBBB.AA...',
        '....AABBBBAA....',
        '....AA.BB.AA....',
        '....AA.BB.AA....',
        '.....AABBAA.....',
        '.....AA.BAA.....',
        '.....AA.BAA.....',
        '......AABA......',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'platform', role: 'head' },
        B: { name: 'supports', role: 'body' },
        A: { name: 'frame', role: 'arm' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. GATE ───────────────────────────────────────────────
    {
      id: 'gate_16',
      description: 'Castle gate with portcullis, stone arch, iron bars.',
      grid: [
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHHH.',
        '..BBBB.XX.BBBBB.',
        '..BBBB.XX.BBBBB.',
        '..BBB..XX..BBBB.',
        '..BBB..XX..BBBB.',
        '..BB...XX...BBB.',
        '..BB...XX...BBB.',
        '..BB...XX...BBB.',
        '..BBB..XX..BBBB.',
        '..BBB.XXXX.BBBB.',
        '..BBBBXXXXBBBBB.',
        '..TTTTTTTTTTTT..',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'arch_top', role: 'head' },
        B: { name: 'stone_walls', role: 'body' },
        X: { name: 'portcullis', role: 'accessory' },
        T: { name: 'ground', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. MARKET STALL ───────────────────────────────────────
    {
      id: 'market_stall_16',
      description: 'Open market stall with colorful canopy, display counter, wares.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '.HHHHHHHHHHHHHH.',
        'HHHHHHHHHHHHHHHH',
        '..AA........AA..',
        '..AA........AA..',
        '..AA........AA..',
        '..AABBBBBBBBAA..',
        '..BBBBBBBBBBBB..',
        '..BXXXXXXXXXXB..',
        '..BXXXXXXXXXXB..',
        '..BBBBBBBBBBBB..',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'canopy', role: 'head' },
        A: { name: 'poles', role: 'arm' },
        B: { name: 'counter', role: 'body' },
        X: { name: 'wares', role: 'accessory' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 17. BRIDGE ─────────────────────────────────────────────
    {
      id: 'bridge_16',
      description: 'Stone arch bridge over water, railings, cobblestone surface.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        'HH............HH',
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'TTBBBBBBBBBBBBTT',
        'TT.BBBBBBBBBB.TT',
        'TT..BBBBBBBB..TT',
        'TT....BBBB....TT',
        'TT............TT',
        'TT............TT',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'railings', role: 'head' },
        B: { name: 'arch_stones', role: 'body' },
        T: { name: 'pillars', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 18. FOUNTAIN ───────────────────────────────────────────
    {
      id: 'fountain_16',
      description: 'Ornate fountain with water basin, central pillar, water spray.',
      grid: [
        '................',
        '.......XX.......',
        '......XXXX......',
        '.......XX.......',
        '......AAAA......',
        '......AAAA......',
        '......AAAA......',
        '....XXXXXXXX....',
        '...XXXXXXXXXX...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '...TTTTTTTTTT...',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        X: { name: 'water_spray', role: 'accessory' },
        A: { name: 'pillar', role: 'arm' },
        B: { name: 'basin', role: 'body' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 19. TREEHOUSE ──────────────────────────────────────────
    {
      id: 'treehouse_16',
      description: 'Treehouse built into a large tree, wooden platform, rope ladder.',
      grid: [
        '...XXXXXXXXX....',
        '..XXXXXXXXXXXX..',
        '..XXXXXXXXXXXX..',
        '...XHHHHHHHX....',
        '...HHHHHHHHHH...',
        '...HHXXHHXXHH...',
        '...HHXXHHXXHH...',
        '...HHHHHHHHHH...',
        '....AABBBBA.....',
        '.....ABBBA......',
        '......BBB.......',
        '..GG..BBB.......',
        '..GG..BBB.......',
        '..GG..BBB.......',
        '.....TTTTT......',
        '................',
      ],
      chars: {
        X: { name: 'canopy', role: 'accessory' },
        H: { name: 'house', role: 'head' },
        B: { name: 'trunk', role: 'body' },
        A: { name: 'platform', role: 'arm' },
        G: { name: 'ladder', role: 'belt' },
        T: { name: 'roots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 20. SHRINE ─────────────────────────────────────────────
    {
      id: 'shrine_16',
      description: 'Small roadside shrine with stone torii gate, offerings, lantern.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '...HH......HH...',
        '..HHHHHHHHHHHH..',
        '...AA......AA...',
        '...AA......AA...',
        '...AA.BBBB.AA...',
        '...AA.BEEB.AA...',
        '...AA.BBBB.AA...',
        '...AA......AA...',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '....XXXXXXXX....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'torii', role: 'head' },
        A: { name: 'pillars', role: 'arm' },
        B: { name: 'altar', role: 'body' },
        E: { name: 'lantern_glow', role: 'eye' },
        X: { name: 'offerings', role: 'accessory' },
        T: { name: 'steps', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

  ],
};

export default batch;
