/**
 * Character Variants batch — 20 new RPG class/race variants
 * Replaces the old 8-template characterVariants with proper 3/4 view skeleton
 * SILHOUETTE-FIRST: each must have unique recognizable shape
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'characters',
  exportNames: { templates: 'CHAR_VARIANT_BATCH1_TEMPLATES', schemes: 'CHAR_VARIANT_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SAMURAI — tall top-knot, layered armor, katana ───
    {
      id: 'samurai_16',
      description: 'Samurai warrior with top-knot, layered plate armor, katana at hip.',
      grid: [
        '......RR........',
        '.....RRRR.......',
        '....RHHHR.......',
        '....HEEHH.......',
        '....HFFHH.......',
        '.....HHH........',
        '...XABBBAX......',
        '..XXABBBAX......',
        '..XXABBBAX......',
        '...XGBBBGX......',
        '....GBBGG.......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        R: { name: 'topknot', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        X: { name: 'shoulder_plates', role: 'accessory' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'sash', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'sandals', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. GOBLIN SHAMAN — big ears, skull staff, tribal markings ───
    {
      id: 'goblin_shaman_16',
      description: 'Small goblin shaman with oversized ears, tribal skull staff.',
      grid: [
        '..............S.',
        '..............S.',
        'W...HHHHHH..SSS.',
        'WW.HHHHHHHH.S...',
        '..HHHEHHEHH.....',
        '..HHHFFHHHH.....',
        '...HHHHHH.......',
        '...ABBBBA.......',
        '..AABBBBA.......',
        '..AAGGGGA.......',
        '...ABBBBA.......',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        W: { name: 'ears', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'loincloth', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 3. DARK ELF — pointed ears, white hair, slim build ───
    {
      id: 'dark_elf_16',
      description: 'Dark elf with pointed ears, white hair, slim dark armor.',
      grid: [
        '................',
        '....RRRRRR......',
        'W..RRHHHHRR.....',
        'WW..HEEHH.......',
        '....HFFHH.......',
        '.....HHH........',
        '....ABBBBA......',
        '...AABBBBA......',
        '...AABBBBA......',
        '....AGBBGA......',
        '.....BBBB.......',
        '.....LLLL.......',
        '....LL..LL......',
        '....LL..LL......',
        '...TTT..TTT.....',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        W: { name: 'ears', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        face:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 4. WITCH DOCTOR — bone mask, feathers, rattles ───
    {
      id: 'witch_doctor_16',
      description: 'Tribal witch doctor with bone mask, feather headdress, rattles.',
      grid: [
        '....X..X.X......',
        '...XXXXXXX......',
        '...XHHHHHX......',
        '...HHEEHHH......',
        '...HHFFHHH......',
        '....HHHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAABBBA.......',
        '...AGBBGA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        X: { name: 'mask', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. ROBOT — boxy head, antenna, metal body ───
    {
      id: 'robot_hero_16',
      description: 'Friendly robot hero with antenna, boxy head, metal chassis.',
      grid: [
        '.....XX.........',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '...HHEEHHHH.....',
        '...HHFFHHHH.....',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '...AABBBBA......',
        '..AAABBBBA......',
        '..AAABBBBA......',
        '...AABBBBA......',
        '....GBBBBG......',
        '....LLLLLL......',
        '....LL..LL......',
        '...LLL..LLL.....',
        '..TTTT..TTTT....',
      ],
      chars: {
        X: { name: 'antenna', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'waist', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        face:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 6. CATFOLK — cat ears, tail, lithe build ───
    {
      id: 'catfolk_16',
      description: 'Agile catfolk rogue with pointed ears, visible tail.',
      grid: [
        '...R....R.......',
        '...RRRRRR.......',
        '...RHHHHR.......',
        '...HHEEHH.......',
        '...HHFFHH.......',
        '....HHHH........',
        '...ABBBBA.......',
        '..AABBBBA.......',
        '..AABBBBA.......',
        '...AGBBGA...T...',
        '....BBBB...TT...',
        '....LLLL..TT....',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        R: { name: 'ears', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'tail_boots', role: 'boot' },
      },
      colors: {
        hair:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:  { shadow: '#442434', base: '#442434', highlight: '#854c30' },
        leg:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 7. NECROMANCER — skull ornament, long dark robes, green glow ───
    {
      id: 'necromancer_v2_16',
      description: 'Necromancer with skull ornament, flowing dark robes, green magic aura.',
      grid: [
        '......XX........',
        '.....XXXX.......',
        '....RHHHRR......',
        '....HEEHH.......',
        '....HFFHH.......',
        '.....HHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAABBBA.......',
        '...ABBBBA.......',
        '...LLLLLL.......',
        '..LLLLLLLL......',
        '..LLLLLLLL......',
        '.LLLLLLLLLL.....',
        '.TTTT...TTTT....',
        '................',
      ],
      chars: {
        X: { name: 'skull_crown', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        L: { name: 'robes', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 8. AMAZON WARRIOR — feathered circlet, spear, minimal armor ───
    {
      id: 'amazon_warrior_16',
      description: 'Amazon warrior with feathered circlet, spear, leather armor.',
      grid: [
        '................',
        '....XXXXXX......',
        '...XRRHHRX......',
        '...RHHEEHR......',
        '....HFFHH.......',
        '.....HHH........',
        '...AABBBA.S.....',
        '..AAABBBA.S.....',
        '..AAAGBBA.S.....',
        '...AGBBGA.S.....',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        X: { name: 'circlet', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'spear', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 9. ALCHEMIST — goggles, potion belt, apron ───
    {
      id: 'alchemist_16',
      description: 'Alchemist with goggles, potion-laden belt, leather apron.',
      grid: [
        '................',
        '.....RRRR.......',
        '....RHHHRR......',
        '...XXEEHXX......',
        '....HFFHH.......',
        '.....HHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAAGBBA.......',
        '...AGGGGGA......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        X: { name: 'goggles', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'potion_belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. KNIGHT TEMPLAR — crusader cross, greathelm, cape ───
    {
      id: 'knight_templar_16',
      description: 'Holy knight with greathelm, crusader cross tabard, cape.',
      grid: [
        '.....XXXX.......',
        '....XXXXXX......',
        '...XXEXXEXX.....',
        '...XXXXXXXXX....',
        '....XXXXXX......',
        '.....HHHH.......',
        '..CCABBBBCC.....',
        '..CCABBBBACC....',
        '..CCABBBBCC.....',
        '...CGBBBBG......',
        '....GBBBBG......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '..TTTT.TTTT.....',
        '................',
      ],
      chars: {
        X: { name: 'helm', role: 'accessory' },
        E: { name: 'visor', role: 'eye' },
        H: { name: 'neck', role: 'head' },
        C: { name: 'cape', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'tabard', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        hair:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        boot:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 11. MUSHROOM FOLK — mushroom cap head, short, stubby ───
    {
      id: 'mushroom_folk_16',
      description: 'Tiny mushroom person with spotted cap head, stubby limbs.',
      grid: [
        '................',
        '....XXXXXX......',
        '...XXXXXXXX.....',
        '..XSXXXXXXSX....',
        '..XXXXXXXXXXX...',
        '...XXXXXXXXX....',
        '.....HEEH.......',
        '.....HFFH.......',
        '....ABBBBA......',
        '...AABBBBAA.....',
        '...AABBBBAA.....',
        '....ABBBBA......',
        '.....BBBB.......',
        '....LL..LL......',
        '...LLL..LLL.....',
        '................',
      ],
      chars: {
        X: { name: 'mushroom_cap', role: 'accessory' },
        S: { name: 'spots', role: 'hand' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        L: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        hand:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. LIZARDFOLK — scaled skin, crest, tail ───
    {
      id: 'lizardfolk_16',
      description: 'Scaly lizardfolk warrior with head crest, muscular tail.',
      grid: [
        '.....XX.........',
        '....XHHX........',
        '...XHHHHHX......',
        '...HHEEHHH......',
        '...HHFFHHH......',
        '....HHHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAAGBBA.......',
        '...AGBBGA..T....',
        '....BBBB..TT....',
        '....LLLL.TT.....',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
        '................',
      ],
      chars: {
        X: { name: 'crest', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'tail', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. DWARVEN SMITH — huge beard, hammer, thick build ───
    {
      id: 'dwarven_smith_16',
      description: 'Stocky dwarf blacksmith with massive beard and hammer.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHEEHHH......',
        '...RRRRRRR......',
        '...RRRRRRRR.....',
        '...RRRRRRR......',
        '..AAABBBBA......',
        '..AAABBBBA......',
        '..AAAGBBGA......',
        '...AGBBBGA......',
        '....BBBB........',
        '....LLLL........',
        '...LLLLLL.......',
        '..TTTTTTTT......',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        R: { name: 'beard', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'apron', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        hair:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. FAIRY — wings, tiny, glowing ───
    {
      id: 'fairy_folk_16',
      description: 'Tiny fairy with translucent wings, glowing aura.',
      grid: [
        '................',
        '................',
        '.......HHHH.....',
        '......HHHH......',
        '......HEEH......',
        '......HFFH......',
        '..WW..ABBA..WW..',
        '.WWWW.ABBA.WWWW.',
        '.WWWW.ABBA.WWWW.',
        '..WW..ABBA..WW..',
        '.......BB.......',
        '......LLLL......',
        '......LL.L......',
        '.....LLL.LL.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        W: { name: 'wings', role: 'accessory' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        L: { name: 'legs', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. PIRATE CAPTAIN — tricorn hat, eyepatch, coat ───
    {
      id: 'pirate_captain_16',
      description: 'Pirate captain with tricorn hat, eyepatch, long coat.',
      grid: [
        '...XXXXXXX......',
        '..XXXXXXXXX.....',
        '..XXXHHHXXX.....',
        '....HHEEHH......',
        '....HFFHH.......',
        '.....HHH........',
        '..CCABBBACC.....',
        '..CCABBBACC.....',
        '..CCABBBACC.....',
        '...CGBBGA.......',
        '....GBBG........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        C: { name: 'coat', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. CYBORG — half-face metal, glowing eye, tech arm ───
    {
      id: 'cyborg_16',
      description: 'Half-human half-machine cyborg with glowing red eye, metal arm.',
      grid: [
        '................',
        '.....RRRR.......',
        '....RHHHHR......',
        '...HHEEHHX......',
        '...HHFFHXX......',
        '....HHHH........',
        '...XABBBA.......',
        '..XXABBBA.......',
        '..XXABBBA.......',
        '...XGBBGA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        X: { name: 'metal', role: 'accessory' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 17. HALFLING — short, curly hair, bare feet ───
    {
      id: 'halfling_16',
      description: 'Cheerful halfling with curly hair, bare hairy feet.',
      grid: [
        '................',
        '....RRRRRR......',
        '...RRRRRRRR.....',
        '...RRHHHRRR.....',
        '...HHEEHHH......',
        '...HHFFHHH......',
        '....HHHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAAGBBA.......',
        '...AGBBGA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...TTT.TTT......',
        '...TTT.TTT......',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'vest', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        hair:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 18. DEMON PRINCE — horns, wings, fiery ───
    {
      id: 'demon_prince_16',
      description: 'Demonic prince with curved horns, bat wings, fiery aura.',
      grid: [
        '.X........X.....',
        '.XX......XX.....',
        '..XHHHHHX.......',
        '..HHEEHHH.......',
        '..HHFFHHH.......',
        '...HHHH.........',
        'WWWABBBBAWWW....',
        '.WWABBBBAWW.....',
        '..AABBBBAA......',
        '...AGBBGA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        X: { name: 'horns', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        W: { name: 'wings', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        hair:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 19. MONK — bald, prayer beads, robes ───
    {
      id: 'monk_v2_16',
      description: 'Zen monk with shaved head, prayer beads, flowing robes.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHEEHHH......',
        '...HHFFHHH......',
        '....HHHH........',
        '...AABBBA.......',
        '..AAABBBA.......',
        '..AAABBBA.......',
        '...AABBBA.......',
        '....LLLL........',
        '...LLLLLL.......',
        '..LLLLLLLL......',
        '..LLLLLLLL......',
        '..TTT...TTT.....',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        L: { name: 'robes', role: 'leg' },
        T: { name: 'sandals', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. ANGEL KNIGHT — halo, wings, golden armor ───
    {
      id: 'angel_knight_16',
      description: 'Celestial knight with halo, wings, shining golden armor.',
      grid: [
        '....XXXX........',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHEEHHH......',
        '...HHFFHHH......',
        '....HHHH........',
        'WWWABBBBAWWW....',
        '.WWABBBBAWW.....',
        '..AABBBBAA......',
        '...AGBBGA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...TTT.TTT......',
        '................',
      ],
      chars: {
        X: { name: 'halo', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        W: { name: 'wings', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'tabard', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },
  ],
};

export default batch;
