/**
 * Characters & NPCs batch 2 — 20 game-inspired character templates.
 * Multi-genre: RPG, horror, sci-fi, sports, western, fantasy, tribal.
 * SILHOUETTE-FIRST: each character has a unique, instantly recognizable shape.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'characters',
  exportNames: { templates: 'CHARACTER_BATCH2_TEMPLATES', schemes: 'CHARACTER_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. WITCH — crooked pointy hat, dark robes, gnarled staff ───
    {
      id: 'dark_witch_16',
      description: 'Dark witch with crooked pointy hat, gnarled staff, flowing dark robes.',
      grid: [
        '.......X........',
        '......XX........',
        '.....XXXX.......',
        '....XXXXXX......',
        '....RRHHRR......',
        '.....HEEH.......',
        '.....HFFH.......',
        '....AABBBA......',
        'SS..A.BBB.......',
        '.S....BGG.......',
        '.S...LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '..TTT......TTT..',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 2. PLAGUE DOCTOR — bird beak mask, wide-brim hat, long dark coat ───
    {
      id: 'plague_doctor_16',
      description: 'Plague doctor with bird beak mask, wide-brim hat, long dark coat.',
      grid: [
        '................',
        '...XXXXXXXXX....',
        '....XXXHXXX.....',
        '.....HHHHH......',
        '....HHMMMM......',
        '....HEEMMM......',
        '....HHMMM.......',
        '.....HHH........',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '...A.BGBB.A.....',
        '.....BBBB.......',
        '.....BBBB.......',
        '....BBBBBB......',
        '...TTT..TTT.....',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        M: { name: 'beak', role: 'face' },
        E: { name: 'eyes', role: 'eye' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. GLADIATOR — crested helmet, round shield, bare chest ───
    {
      id: 'gladiator_16',
      description: 'Roman gladiator with crested helmet, round shield, minimal armor.',
      grid: [
        '.....CC.........',
        '....CCCC........',
        '....HHHH........',
        '....HEEH........',
        '....HFFH........',
        '.....FF.........',
        '..AAABBBBAA.....',
        '.SSS.BBBBBB.....',
        '.SSS.BBGGBB.....',
        '.SSS..BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crest', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'shield', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. SPACE MARINE — bulky power armor, helmet visor, gun ───
    {
      id: 'space_marine_16',
      description: 'Heavy space marine in bulky power armor with glowing visor and gun.',
      grid: [
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '.....HEEEH......',
        '.....HHHHH......',
        '......HHH.......',
        '..AAABBBBBAAA...',
        '..AA.BBBBBB.AA..',
        '..AA.BBBBBB.AA..',
        '..SS.BBGGBB.....',
        '.....BBBBBB.....',
        '.....LLLLLL.....',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        H: { name: 'helmet', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        A: { name: 'shoulders', role: 'arm' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'gun', role: 'hand' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 5. VIKING — horned helmet, fur cape, beard ───
    {
      id: 'norse_viking_16',
      description: 'Norse viking with horned helmet, fur cape trailing behind, bushy beard.',
      grid: [
        '.VV........VV...',
        '..VV.HHHH.VV....',
        '...VVHHHHVV.....',
        '.....HEEH.......',
        '.....HFFH.......',
        '.....RFFR.......',
        '......FF........',
        '...AABBBBAA.....',
        '...A.BBBB.ACCC..',
        '.....BBGGB.CCC..',
        '.....BBBBB..CC..',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        V: { name: 'horns', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        R: { name: 'beard', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        C: { name: 'cape', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 6. COWBOY — wide brim hat, vest, boots with spurs ───
    {
      id: 'cowboy_16',
      description: 'Western cowboy with wide brim hat, leather vest, and tall boots.',
      grid: [
        '................',
        '....XXXXXXXX....',
        '.....XXXXXX.....',
        '......HHHH......',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '......HFFH......',
        '.....AABBBA.....',
        '.....A.BBB.A....',
        '.....A.BBB.A....',
        '......BGGGB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'vest', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. FISHERMAN — straw hat, vest, fishing rod ───
    {
      id: 'fisherman_16',
      description: 'Fisherman with wide straw hat, vest, and long fishing rod.',
      grid: [
        '....XXXXXXXX....',
        '.....XXXXXX.....',
        '......HHHH......',
        '.....HHEEHH.....',
        '......HHFH......',
        '.......FF.......',
        '....AABBBBSS....',
        '.....ABBBBS.....',
        '......BGGG.S....',
        '......BBBB..S...',
        '......LLLL...S..',
        '.....LL..LL..S..',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'vest', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'rod', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 8. JESTER — two-pointed cap with bells, baggy outfit ───
    {
      id: 'jester_16',
      description: 'Royal jester with two-pointed cap, bells, and baggy motley outfit.',
      grid: [
        '..XX......XX....',
        '...XX....XX.....',
        '....XXXXXX......',
        '.....RRHHRR.....',
        '......HEEH......',
        '......HFFH......',
        '.......FF.......',
        '....AABBBBAA....',
        '.....ABBBBA.....',
        '.....ABBBBA.....',
        '......BGBB......',
        '.....LLLLLL.....',
        '....LLL..LLL....',
        '....LL....LL....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'cap', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. SCHOLAR — spectacles, book, long robes ───
    {
      id: 'scholar_16',
      description: 'Scholarly sage with spectacles, holding thick book, long academic robes.',
      grid: [
        '................',
        '................',
        '.......RR.......',
        '......RRRR......',
        '.....HHHHH......',
        '.....HEEHH......',
        '......HFFH......',
        '.......FF.......',
        '....AABBBBAA....',
        '.SSS.ABBBBA.....',
        '.SSS..BGBB......',
        '.SSS..BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...TTT....TTT...',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'book', role: 'hand' },
      },
      colors: {
        hair:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 10. DRUID — antler crown, nature robes, wooden staff ───
    {
      id: 'druid_16',
      description: 'Nature druid with antler headdress, leaf-green robes, wooden staff.',
      grid: [
        '..CC.....CC.....',
        '...CC...CC......',
        '....CCCCCC......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'antlers', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 11. DANCER — flowing dress, dynamic pose, ribbon ───
    {
      id: 'dancer_16',
      description: 'Graceful dancer with flowing dress and trailing ribbon, dynamic pose.',
      grid: [
        '................',
        '......RRR.......',
        '.....RHHRR......',
        '......HEEH......',
        '......HFFH......',
        '.......FF.......',
        '.....AABBBA.....',
        '....AA.BBB....SS',
        '.......BGG...SS.',
        '......LLLLLL.S..',
        '.....LLLLLLLL...',
        '....LLLLLLLLLL..',
        '...LLLLLLLLLLLL.',
        '....TTT....TTT..',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'dress', role: 'leg' },
        T: { name: 'shoes', role: 'boot' },
        S: { name: 'ribbon', role: 'hand' },
      },
      colors: {
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 12. SHAMAN — skull headdress, tribal paint, bone staff ───
    {
      id: 'shaman_16',
      description: 'Tribal shaman with skull headdress, face paint, bone staff with feathers.',
      grid: [
        '.....CCCCC......',
        '....CCCCCC......',
        '....CCEEC.......',
        '.....CCC........',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
      ],
      chars: {
        C: { name: 'skull', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 13. ANGEL — wings, halo, flowing white robes ───
    {
      id: 'angel_16',
      description: 'Heavenly angel with feathered wings, golden halo, flowing white robes.',
      grid: [
        '......CC........',
        '.....HHHH.......',
        '....HHHHHH......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '..WWABBBBAWW....',
        '..W.A.BBBB.W....',
        '..W...BGBB.W....',
        '..WW..BBBB.WW...',
        '......LLLL......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'halo', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        W: { name: 'wings', role: 'hand' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. WRESTLER — lucha mask, muscular, cape ───
    {
      id: 'wrestler_16',
      description: 'Lucha libre wrestler with colorful mask, muscular build, flowing cape.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HHEEHH......',
        '....HHFFHH......',
        '.....HHHH.......',
        '......HH........',
        '..AAABBBBBAACCC.',
        '..AA.BBBBBB.CCC.',
        '..AA.BBGGBB..CC.',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        H: { name: 'mask', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        C: { name: 'cape', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        hand:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. VAMPIRE — slicked hair, pale, dramatic cape ───
    {
      id: 'vampire_16',
      description: 'Elegant vampire with slicked hair, pale skin, dramatic spreading cape.',
      grid: [
        '................',
        '......RRR.......',
        '.....RRRRR......',
        '.....RHHRR......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.CC.A.BBBB.A.CC.',
        '.CC...BGBB...CC.',
        '..CC..BBBB..CC..',
        '...CC.LLLL.CC...',
        '....CCLLCC......',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'suit', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        C: { name: 'cape', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 16. CULTIST — hooded dark robe, mysterious ───
    {
      id: 'cultist_16',
      description: 'Mysterious cultist in deep hooded dark robe, face hidden in shadow.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '....XXHHHXX.....',
        '.....HEEH.......',
        '.....HHFHH......',
        '......HHH.......',
        '....AABBBBAA....',
        '.....ABBBBA.....',
        '.....ABBBBA.....',
        '......BGBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robe', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robe_lower', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 17. MECHANIC — jumpsuit, wrench, goggles on forehead ───
    {
      id: 'mechanic_16',
      description: 'Mechanic in oil-stained jumpsuit with goggles on forehead and wrench.',
      grid: [
        '................',
        '......CC........',
        '......HHHH......',
        '.....CCHHH......',
        '.....HHEEH......',
        '.....HHFHH......',
        '......HHH.......',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '.....BBGGBB.....',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.SS..LL..LL.....',
        '.S.TTT..TTT.....',
        '................',
      ],
      chars: {
        C: { name: 'goggles', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'jumpsuit', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'wrench', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. BOXER — boxing gloves, shorts, athletic build ───
    {
      id: 'boxer_16',
      description: 'Athletic boxer with oversized boxing gloves, shorts, fighting stance.',
      grid: [
        '................',
        '................',
        '......RRR.......',
        '......HHHH......',
        '.....HHEEHH.....',
        '......HFFH......',
        '.......FF.......',
        '....AABBBBAA....',
        '...SS.BBBB.SS...',
        '...SS.BBBB.SS...',
        '......BGBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'shorts', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'gloves', role: 'hand' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 19. PIRATE DECKHAND — bandana, striped shirt, cutlass ───
    {
      id: 'pirate_deckhand_16',
      description: 'Pirate deckhand with bandana, striped shirt, and cutlass at side.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '.....BBGGBB.....',
        '.SS..BBBBBB.....',
        '.S....LLLL......',
        '......LL.LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'bandana', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'shirt', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'pants', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'cutlass', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 20. SNOW RANGER — fur-lined hood, winter gear, bow ───
    {
      id: 'snow_ranger_16',
      description: 'Arctic ranger with fur-lined hood, heavy winter coat, and longbow.',
      grid: [
        '....XXXXXXXX....',
        '...XXXXXXXXXX...',
        '....XXHHHHXX....',
        '.....HHEEH......',
        '.....HHFFHH.....',
        '......HFFH......',
        '.......FF.......',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'bow', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
