/**
 * Characters & NPCs batch 1 — 20 character templates.
 * SILHOUETTE-FIRST design: each character has a unique, instantly recognizable shape.
 * Varied proportions, poses, and defining features.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'characters',
  exportNames: { templates: 'CHARACTER_BATCH1_TEMPLATES', schemes: 'CHARACTER_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. BARBARIAN — massive build, tiny head, axe overhead ───
    // Silhouette: wide inverted-triangle torso, oversized arms, weapon up
    {
      id: 'barbarian_16',
      description: 'Hulking barbarian with tiny head, massive shoulders, axe raised overhead.',
      grid: [
        '..........SS....',
        '.........SSS....',
        '.....HH..S......',
        '....HHHH........',
        '....HEHH........',
        '...BBBBBB.......',
        '..AABBBBBBAA....',
        '.AA.BBBBBB.AA...',
        '.AA.BBBBBB.AA...',
        '....BBGGBB......',
        '....BBBBBB......',
        '.....LLLL.......',
        '....LL..LL......',
        '...LL....LL.....',
        '..TTT....TTT....',
        '................',
      ],
      chars: {
        S: { name: 'axe', role: 'hand' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 2. MAGE — huge pointy hat dominates, thin body, wide robe ──
    // Silhouette: tall triangle hat (5 rows), skinny middle, flared pyramid robe
    {
      id: 'wizard_mage_16',
      description: 'Wizard with towering pointy hat, thin frame, wide flowing robes at bottom.',
      grid: [
        '.......X........',
        '......XXX.......',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '....RRHHHH......',
        '.....HHEEH......',
        '.....HHFHH......',
        '....AABBAA......',
        '.S...BBBB.......',
        '.S...BBBB.......',
        '.S..LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '.LLLLLLLLLLLL...',
        'LLLLLLLLLLLLLLLL',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'torso', role: 'body' },
        S: { name: 'staff', role: 'hand' },
        L: { name: 'robes', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
      },
    },

    // ─── 3. ROGUE — crouched, cape flowing back, asymmetric ──────
    // Silhouette: low center of gravity, cape trails right, dagger forward
    {
      id: 'rogue_thief_16',
      description: 'Crouched rogue with flowing cape behind, dagger extended forward.',
      grid: [
        '................',
        '................',
        '................',
        '....RRRR........',
        '...RRHHRR.......',
        '...HHEEHH.......',
        'SS.HHFFHH.CC....',
        '.S.ABBBBA..CC...',
        '...ABBBBACCCC...',
        '...BBGGBB.CCC...',
        '..BBBBBBBB.CC...',
        '..LLLL.LLLL.....',
        '.LLLL...LLLL....',
        '.TT.......TT....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'hood', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        S: { name: 'dagger', role: 'hand' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'tunic', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        C: { name: 'cape', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 4. ARCHER — bow drawn to side, quiver on back ───────────
    // Silhouette: diagonal bow line + arm triangle = unique shape
    {
      id: 'ranger_archer_16',
      description: 'Ranger drawing a bow to the left, quiver visible on back.',
      grid: [
        '................',
        '.....RRRR.......',
        '....RRHHRR......',
        '....HHEEHH......',
        '..S.HHFFHH.Q....',
        '.SS.ABBBBB.Q....',
        'S.AAABBBBB.Q....',
        '..AA.BBGGBB.....',
        '..A..BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....LLLL.......',
        '....LL..LL......',
        '...LL....LL.....',
        '...TT....TT.....',
        '................',
      ],
      chars: {
        R: { name: 'hood', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        S: { name: 'bow', role: 'hand' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'tunic', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        Q: { name: 'quiver', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. DWARF — very short, huge beard, wide axe ─────────────
    // Silhouette: compact square, beard = 1/3 of body, no visible neck, wide
    {
      id: 'dwarf_16',
      description: 'Stocky dwarf with enormous beard, helmet with horns, battle axe.',
      grid: [
        '................',
        '................',
        '................',
        '.X..HHHH..X.....',
        '....HHHHHH......',
        '....HHEEHH......',
        '...FFFFFFHH.....',
        '..SFFFFFFBB.....',
        '..SAFFFFFFBB....',
        '..S.AABBBBBB....',
        '..S.AABBGGBB....',
        '....AABBBBBB....',
        '.....LLLLLL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'horns', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'beard', role: 'face' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        A: { name: 'arms', role: 'arm' },
        S: { name: 'axe', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 6. PRINCESS — tiny upper, HUGE pyramid gown ─────────────
    // Silhouette: small head → extremely wide triangle dress filling bottom
    {
      id: 'princess_16',
      description: 'Princess with small tiara, delicate frame, and enormous bell-shaped gown.',
      grid: [
        '................',
        '.....XXXX.......',
        '.....RRHH.......',
        '....RRHHHHR.....',
        '.....HHEEH......',
        '.....HHFFH......',
        '....AABBBBAA....',
        '....A.BBBB.A....',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '.LLLLLLLLLLLLLL.',
        'LLLLLLLLLLLLLLLL',
        '.TTTTTTTTTTTTTT.',
        '................',
      ],
      chars: {
        X: { name: 'tiara', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'bodice', role: 'body' },
        L: { name: 'gown', role: 'leg' },
        T: { name: 'gown_hem', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 7. ROBOT — boxy, non-humanoid proportions, antenna ──────
    // Silhouette: rectangular head, square body, cylinder legs
    {
      id: 'robot_npc_16',
      description: 'Boxy helper robot with antenna, square head, cylindrical limbs.',
      grid: [
        '......XX........',
        '......XX........',
        '...HHHHHHHH.....',
        '...HHHHHHHH.....',
        '...HHEEHHHH.....',
        '...HHFFHHHH.....',
        '...HHHHHHHH.....',
        '.AABBBBBBBBAA...',
        '.AA.BBXXBB.AA...',
        '.AA.BBXXBB.AA...',
        '.AA.BBBBBB.AA...',
        '....BBBBBB......',
        '....LLLLLL......',
        '...LLLL.LLLL....',
        '..TTTT...TTTT...',
        '................',
      ],
      chars: {
        X: { name: 'antenna_core', role: 'accessory' },
        H: { name: 'head_block', role: 'head' },
        E: { name: 'eye_lights', role: 'eye' },
        F: { name: 'mouth_grill', role: 'face' },
        B: { name: 'chassis', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        face:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 8. NECROMANCER — floating, tattered, skull orb ──────────
    // Silhouette: no legs visible, ragged robe bottom, glowing orb in hand
    {
      id: 'necromancer_16',
      description: 'Floating necromancer with tattered robes, no visible legs, skull orb in hand.',
      grid: [
        '................',
        '....RRRRR.......',
        '...RRHHHHRR.....',
        '....HHEEHH......',
        '....HHFFHH......',
        '...AABBBBAA.....',
        '..AA.BBBB.AA....',
        '.AA..BBBB..SS...',
        '.A...BBBB.SSSS..',
        '.....BBBB..SS...',
        '...LLLLLLLL.....',
        '..LL.LLLL.LL....',
        '.LL...LL...LL...',
        '.L....LL....L...',
        '......LL........',
        '................',
      ],
      chars: {
        R: { name: 'hood', role: 'hair' },
        H: { name: 'skull_face', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'jaw', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        S: { name: 'skull_orb', role: 'accessory' },
        L: { name: 'tattered_robe', role: 'leg' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        eye:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 9. PIRATE CAPTAIN — tricorn hat, hook hand, peg leg ─────
    // Silhouette: wide tricorn hat, asymmetric (hook + normal hand, peg + normal leg)
    {
      id: 'pirate_captain_16',
      description: 'Pirate captain with wide tricorn hat, hook hand, and peg leg.',
      grid: [
        '................',
        '..XXXXXXXXXX....',
        '...XXXXXXXX.....',
        '....RRHHRR......',
        '....HHEEHH......',
        '....HHFFHH......',
        '...AABBBBBB.....',
        '..AA.BBGGBB.....',
        '.AA..BBBBBB.....',
        '.S...BBBBBB.....',
        '.....BBBBBB.....',
        '.....LLLL.......',
        '....LL..LP......',
        '...LL....PP.....',
        '...TT....PP.....',
        '................',
      ],
      chars: {
        X: { name: 'tricorn', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'coat_arm', role: 'arm' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'sash', role: 'belt' },
        S: { name: 'hook', role: 'hand' },
        L: { name: 'leg', role: 'leg' },
        P: { name: 'peg_leg', role: 'boot' },
        T: { name: 'boot', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. KNIGHT — full plate, shield wall, cape behind ───────
    // Silhouette: blocky solid armor, big shield on one side, cape flowing
    {
      id: 'plate_knight_16',
      description: 'Full plate knight with large tower shield and flowing cape.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HHEEHH......',
        '....HHHHHH......',
        '..AABBBBBB.CC...',
        '..AABBGGBB.CC...',
        '..AABBBBBB..CC..',
        '..AABBBBBB..CC..',
        '..AABBBBBB..CC..',
        '..AALLLLLL..CC..',
        '....LL..LL..CC..',
        '...LL....LL.C...',
        '..TTT....TTT....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'helmet', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        B: { name: 'plate', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        A: { name: 'shield', role: 'arm' },
        C: { name: 'cape', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'sabatons', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 11. FARMER — oversized straw hat, stocky, pitchfork ─────
    // Silhouette: hat wider than body, stubby proportions, tall tool
    {
      id: 'farmer_16',
      description: 'Stocky farmer with oversized straw hat, overalls, and pitchfork.',
      grid: [
        '................',
        '..XXXXXXXXXX....',
        '..XXXXXXXXXX....',
        '...XXXHHXXX.....',
        '.....HHEEH......',
        '.....HHFFH......',
        '....ABBBBBSSS...',
        '....ABBGGB..S...',
        '....ABBBBB..S...',
        '.....BBBBB..S...',
        '.....BBBBB..S...',
        '.....LLLL...S...',
        '....LL..LL......',
        '....TT..TT......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arm', role: 'arm' },
        B: { name: 'overalls', role: 'body' },
        G: { name: 'buckle', role: 'belt' },
        S: { name: 'pitchfork', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. NINJA — dynamic offset pose, trailing scarf ─────────
    // Silhouette: body angled, long scarf trails horizontally, one arm forward
    {
      id: 'ninja_16',
      description: 'Ninja in dynamic pose, long trailing scarf, arm extended with shuriken.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '....HHHHHRR.....',
        '....HHEEH.RRR...',
        '....HHMMH..RRR..',
        '..SSABBBB...RR..',
        '...SABBBBA......',
        '....BBGGBB......',
        '....BBBBBB......',
        '...LLLL.........',
        '..LLLL.LL.......',
        '.LL.....LL......',
        '.TT......TT.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        R: { name: 'scarf', role: 'accessory' },
        E: { name: 'eyes', role: 'eye' },
        M: { name: 'mask', role: 'face' },
        S: { name: 'shuriken', role: 'hand' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'suit', role: 'body' },
        G: { name: 'sash', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'tabi', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 13. WITCH DOCTOR — huge tribal mask, staff with skull ───
    // Silhouette: oversized mask dominates upper half, bone staff, grass skirt
    {
      id: 'witch_doctor_16',
      description: 'Tribal witch doctor with oversized ceremonial mask and bone staff.',
      grid: [
        '................',
        '..XXMMMMMXX.....',
        '..XMMMMMMXX.....',
        '..MMMEEMMM......',
        '..MMMFFMMM......',
        '..MMMMMMMMM.....',
        '..XXMMMMMXX.....',
        '....ABBBBA......',
        '.S..ABBBBA......',
        '.S..ABBBBA......',
        '.SS..BBBB.......',
        '.S..LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '....TT..TT......',
        '................',
      ],
      chars: {
        X: { name: 'mask_horns', role: 'accessory' },
        M: { name: 'mask', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'torso', role: 'body' },
        S: { name: 'bone_staff', role: 'hand' },
        L: { name: 'grass_skirt', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#4e4a4e', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 14. SAMURAI — wide kabuto crest, katana, hakama ─────────
    // Silhouette: distinctive wide horn crest, wide hakama pants
    {
      id: 'samurai_16',
      description: 'Samurai with dramatic kabuto horn crest, katana, and wide hakama.',
      grid: [
        '................',
        'XXXXXXXXXXXXXXX.',
        '....XHHHHHX.....',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '....AABBBBBB....',
        '...AA.BBGGBB....',
        '...A..BBBBBB.S..',
        '......BBBBBB.S..',
        '.....LLLLLL..S..',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '.LLLLLL.LLLLLLL.',
        '..TTT.....TTT...',
        '................',
      ],
      chars: {
        X: { name: 'kabuto', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'do_armor', role: 'body' },
        G: { name: 'obi', role: 'belt' },
        S: { name: 'katana', role: 'hand' },
        L: { name: 'hakama', role: 'leg' },
        T: { name: 'sandals', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 15. CHEF — tall toque hat, round belly, frying pan ──────
    // Silhouette: tall puffy hat, round midsection, pan extends to side
    {
      id: 'chef_16',
      description: 'Rotund chef with tall toque blanche, round belly, holding frying pan.',
      grid: [
        '....XXXXXX......',
        '...XXXXXXXX.....',
        '...XXXXXXXX.....',
        '...XXXHHXXX.....',
        '.....HHEEH......',
        '.....HHFFH......',
        '....ABBBBA......',
        '...AABBBBA......',
        '..AABBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.SSSBBBBBB......',
        '.....LLLL.......',
        '....LL..LL......',
        '....TT..TT......',
        '................',
      ],
      chars: {
        X: { name: 'toque', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'apron_belly', role: 'body' },
        S: { name: 'pan', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'shoes', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 16. GUNSLINGER — wide hat, poncho, guns at hips ─────────
    // Silhouette: wide-brim hat, poncho makes triangle shape, guns stick out
    {
      id: 'gunslinger_16',
      description: 'Western gunslinger with wide hat, poncho, and holstered revolvers.',
      grid: [
        '................',
        '..XXXXXXXXXX....',
        '....XXXXXX......',
        '.....RRHH.......',
        '.....HHEEH......',
        '.....HHFFH......',
        '...CCCCCCCC.....',
        '..CCCCCCCCCC....',
        '.CCCCBBBBCCCC...',
        '..CCBBGGBBCC....',
        '..SSBBBBBBSS....',
        '..S..LLLL..S....',
        '.....LL.LL......',
        '....LL...LL.....',
        '...TTT...TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        C: { name: 'poncho', role: 'arm' },
        B: { name: 'shirt', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        S: { name: 'guns', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        hand:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 17. CYBORG — one massive augmented arm, visor ───────────
    // Silhouette: strongly asymmetric, one arm much bigger than other
    {
      id: 'cyborg_16',
      description: 'Cyberpunk cyborg with one oversized mechanical arm and glowing visor.',
      grid: [
        '................',
        '.....RRRR.......',
        '....RRHHRR......',
        '....HHEEHH......',
        '....HHFFHH......',
        '....ABBBBB......',
        '...AABBBBB......',
        '..AAABBGGBB.....',
        '.AAAA.BBBB......',
        '.AAA..BBBB......',
        '.AA...LLLL......',
        '......LL.LL.....',
        '.....LL...LL....',
        '.....TT...TT....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'mech_arm', role: 'arm' },
        B: { name: 'torso', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 18. BARD — big lute dominates, feathered hat ────────────
    // Silhouette: lute body in front is the defining shape
    {
      id: 'bard_16',
      description: 'Flamboyant bard with feathered hat and large lute held in front.',
      grid: [
        '....XRRRRR......',
        '....RRRRRR......',
        '.....RRHH.......',
        '.....HHEEH......',
        '.....HHFFH......',
        '....ABBBBA......',
        '...AABBBBA......',
        '..SSSBBBB.......',
        '.SSSSSBBBB......',
        '.SSSSSBBBB......',
        '..SSSLLLL.......',
        '..SS.LL.LL......',
        '.....LL..LL.....',
        '....TT....TT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'feather', role: 'accessory' },
        R: { name: 'hat', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'tunic', role: 'body' },
        S: { name: 'lute', role: 'hand' },
        L: { name: 'pants', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        hair:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. PALADIN — broad cape + hammer + halo glow ───────────
    // Silhouette: glowing halo circle above, wide cape, hammer to side
    {
      id: 'paladin_16',
      description: 'Holy paladin with glowing halo, warhammer, and broad golden cape.',
      grid: [
        '....GGGGGG......',
        '...GG.HH.GG.....',
        '...G.HHHH.G.....',
        '.....HHEEH......',
        '.....HHFFH......',
        '..CCBBBBBBSS....',
        '.CC.BBWWBB.SS...',
        '.CC.ABBBBA..S...',
        '.CC.BBBBBB......',
        '.CC.BBBBBB......',
        '..CCLLLLLL......',
        '....LL..LL......',
        '...LL....LL.....',
        '..TTT....TTT....',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'halo', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        C: { name: 'cape', role: 'hair' },
        B: { name: 'plate', role: 'body' },
        W: { name: 'belt', role: 'belt' },
        A: { name: 'arms', role: 'arm' },
        S: { name: 'hammer', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        hand:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 20. ALCHEMIST — big goggles, flared coat, flask ─────────
    // Silhouette: oversized round goggles, coat flares at bottom, flask in hand
    {
      id: 'alchemist_16',
      description: 'Mad alchemist with huge round goggles, flared coat, and bubbling flask.',
      grid: [
        '................',
        '....RRRRRR......',
        '....RRHHRR......',
        '...EEHHEEHH.....',
        '...EEHHEEHH.....',
        '.....HHFFH......',
        '...CCBBBBCC.....',
        '..CC.BBBB.CC....',
        '.CC..ABBB..CC...',
        '.CC..BBBB..SSS..',
        '.CC.BBBBBB.SSS..',
        '..CCLLLLLLCC....',
        '..CCLL..LLCC....',
        '.CCC......CCC...',
        '....TT..TT......',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'goggles', role: 'eye' },
        F: { name: 'face', role: 'face' },
        C: { name: 'coat', role: 'accessory' },
        A: { name: 'arm', role: 'arm' },
        B: { name: 'shirt', role: 'body' },
        S: { name: 'flask', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
