/**
 * Characters & NPCs batch 3 — 20 new character variant templates.
 * Archetypes NOT yet covered: assassin, berserker, oracle, gambler, etc.
 * Multi-genre: RPG, horror, sci-fi, steampunk, martial arts, mythological.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'characters',
  exportNames: { templates: 'CHARACTER_BATCH3_TEMPLATES', schemes: 'CHARACTER_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. ASSASSIN — hooded, dual daggers, crouched ───
    {
      id: 'assassin_16',
      description: 'Hooded assassin in crouched stance with dual daggers drawn.',
      grid: [
        '................',
        '................',
        '....XXXXXX......',
        '....XXHHXX......',
        '.....HEEH.......',
        '.....HHFHH......',
        '......HHH.......',
        '...AABBBBAA.....',
        '..SS.BBBB.SS....',
        '..S..BGBB..S....',
        '.....BBBB.......',
        '......LLLL......',
        '....LLL..LL.....',
        '....LL...LL.....',
        '...TTT...TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'daggers', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. BERSERKER — wild hair, bare chest, massive axe ───
    {
      id: 'berserker_16',
      description: 'Raging berserker with wild spiked hair, bare scarred chest, huge axe.',
      grid: [
        '..R...R..R......',
        '..RR.RRR.R......',
        '...RRHHRR.......',
        '....HHHH........',
        '....HEEH........',
        '....HFFH........',
        '.....FF.........',
        '..AABBBBBBSS....',
        '..AA.BBBBB.SS...',
        '..AA.BBGGBB.S...',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'body', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'axe', role: 'hand' },
      },
      colors: {
        hair:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 3. ORACLE — blindfold, flowing ethereal robes ───
    {
      id: 'oracle_16',
      description: 'Blindfolded oracle in shimmering ethereal robes with floating crystal.',
      grid: [
        '................',
        '......SS........',
        '......RRR.......',
        '.....RRRRR......',
        '.....RHHRR......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '....AABBBBAA....',
        '.....ABBBBA.....',
        '.....ABGBBA.....',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
      ],
      chars: {
        S: { name: 'crystal', role: 'hand' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hand:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        hair:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 4. GAMBLER — top hat, cards, fancy vest ───
    {
      id: 'gambler_16',
      description: 'Dapper gambler with top hat, holding cards, fancy waistcoat.',
      grid: [
        '....XXXXXX......',
        '....XXXXXX......',
        '...XXXXXXXX.....',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '...A.BBBB.ASS...',
        '...A.BGBB..SS...',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'tophat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'vest', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'pants', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'cards', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 5. STEAM_KNIGHT — steampunk armor, goggles, gear motif ───
    {
      id: 'steam_knight_16',
      description: 'Steampunk knight with brass-plated armor, goggles, and gear emblem.',
      grid: [
        '................',
        '......CC........',
        '.....CHHHC......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '..AAABBBBBAAA...',
        '..AA.BBBBBB.AA..',
        '..AA.BBGGBB.....',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'goggles', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'gears', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 6. WITCH_HUNTER — wide hat, crossbow, long coat ───
    {
      id: 'witch_hunter_16',
      description: 'Grim witch hunter with wide-brim hat, crossbow, and long coat.',
      grid: [
        '................',
        '...XXXXXXXXXX...',
        '....XXXXXXXX....',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '..SS.BBBB.A.....',
        '..S..BGBB.A.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....LL....LL....',
        '...TTT....TTT...',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'crossbow', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 7. BATTLE_MAGE — armored wizard, staff+sword ───
    {
      id: 'battle_mage_16',
      description: 'Battle mage in plated wizard robes, wielding staff and sword.',
      grid: [
        '.......X........',
        '......XXX.......',
        '.....XXXXX......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '..AAABBBBBAAA...',
        '.SS.A.BBBB.A.WW.',
        '..S...BGBB....W.',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hat', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'pauldrons', role: 'arm' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
        W: { name: 'sword', role: 'hair' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hair:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 8. PLAGUE_RAT — ragged survivor, plague-era ───
    {
      id: 'plague_rat_16',
      description: 'Ragged plague-era survivor with tattered cloak and lantern.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '....XXHHHXX.....',
        '.....HEEH.......',
        '.....HFFH.......',
        '......HH........',
        '...AABBBBAA.....',
        '...A.BBBB.ASS...',
        '.....BGBB..S....',
        '.....BBBBB......',
        '....BBBBBBB.....',
        '....LLLLLLLL....',
        '....LL....LL....',
        '...TTT....TTT...',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'rags', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'lantern', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 9. VALKYRIE — winged helm, spear, shield maiden ───
    {
      id: 'valkyrie_16',
      description: 'Fierce valkyrie with winged helmet, golden armor, spear and shield.',
      grid: [
        '..WW.....WW.....',
        '...WW.HH.WW.....',
        '....WHHHHW......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        W: { name: 'wings', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'armor', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'spear', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 10. DARK_KNIGHT — full dark plate, horned helm ───
    {
      id: 'dark_knight_16',
      description: 'Menacing dark knight in full black plate armor with horned helmet.',
      grid: [
        '..CC.....CC.....',
        '...CC.HH.CC.....',
        '....CHHHHC......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HHHH.......',
        '......HH........',
        '..AAABBBBBAAA...',
        '..AA.BBBBBB.AA..',
        '..AA.BBGGBB.....',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'horns', role: 'accessory' },
        H: { name: 'helmet', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        A: { name: 'pauldrons', role: 'arm' },
        B: { name: 'plate', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'greaves', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 11. GEISHA — elaborate hair, kimono with obi ───
    {
      id: 'geisha_16',
      description: 'Elegant geisha with elaborate up-do hairstyle, ornate kimono with wide obi.',
      grid: [
        '......CC........',
        '.....RRRR.......',
        '....RRRRRR......',
        '....RRHHRR......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '....AABBBBAA....',
        '.....ABBBBA.....',
        '.....ABBBBA.....',
        '......BGBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'ornament', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'sleeves', role: 'arm' },
        B: { name: 'kimono', role: 'body' },
        G: { name: 'obi', role: 'belt' },
        L: { name: 'kimono_lower', role: 'leg' },
        T: { name: 'sandals', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 12. MARTIAL_ARTIST — gi, headband, fists up ───
    {
      id: 'martial_artist_16',
      description: 'Martial artist in white gi with black belt, headband, fighting stance.',
      grid: [
        '................',
        '......XXX.......',
        '......HHHH......',
        '.....XXHHHX.....',
        '.....HHEEH......',
        '.....HHFFHH.....',
        '......HHH.......',
        '..SSAABBBBAA....',
        '..SS.ABBBBA.....',
        '.....ABGBBA.....',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'headband', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'gi', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'pants', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
        S: { name: 'fists', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 13. PIRATE_QUEEN — tricorn hat, cutlass, fancy coat ───
    {
      id: 'pirate_queen_16',
      description: 'Pirate queen with feathered tricorn hat, red coat, gold trim.',
      grid: [
        '.....CC.........',
        '...XXXXXXXX.....',
        '....XXXXXX......',
        '.....RRHHRR.....',
        '.....HHEEH......',
        '.....HHFFHH.....',
        '......HHH.......',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'feather', role: 'hand' },
        X: { name: 'hat', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'coat', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'pants', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'cutlass', role: 'hand' },
      },
      colors: {
        hand:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 14. WARLOCK — demon horns, dark robe, glowing hands ───
    {
      id: 'warlock_16',
      description: 'Warlock with small demon horns, dark robes, hands crackling with energy.',
      grid: [
        '..CC.....CC.....',
        '...CC.RR.CC.....',
        '....RRHHRR......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A.SS.',
        '.SS...BGBB...SS.',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'horns', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'energy', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. DESERT_NOMAD — turban, scarf, flowing desert garb ───
    {
      id: 'desert_nomad_16',
      description: 'Desert nomad with wrapped turban, face scarf, and flowing sand-colored robes.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '....XXHHHXX.....',
        '.....HEEH.......',
        '.....HFFFH......',
        '.....FFFFF......',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '.....BGBB.......',
        '.....BBBB.......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '....LL....LL....',
        '...TTT....TTT...',
        '................',
      ],
      chars: {
        X: { name: 'turban', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'scarf', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 16. FIRE_MAGE — flame hair, red robes, fire hands ───
    {
      id: 'fire_mage_16',
      description: 'Fire mage with flaming hair, crimson robes, hands wreathed in fire.',
      grid: [
        '.....RR.R.......',
        '....RRRRR.......',
        '....RRHHRR......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A.SS.',
        '.S....BGBB....S.',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        R: { name: 'fire_hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'flames', role: 'hand' },
      },
      colors: {
        hair:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        hand:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. ICE_MAGE — frost crown, blue robes, ice crystals ───
    {
      id: 'ice_mage_16',
      description: 'Ice mage with frost crystal crown, icy blue robes, frozen aura.',
      grid: [
        '....CC..CC......',
        '.....CCCCC......',
        '.....CHHHC......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '.SS.A.BBBB.A....',
        '..S...BGBB......',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'crown', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'robes', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'robes_lower', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'staff', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        hand:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 18. LUMBERJACK — beanie, plaid shirt, big axe ───
    {
      id: 'lumberjack_16',
      description: 'Burly lumberjack with beanie, thick beard, plaid shirt, and big axe.',
      grid: [
        '................',
        '.....XXXXX......',
        '.....XXXXXX.....',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....RFFR.......',
        '......RR........',
        '..AAABBBBBAASS..',
        '..AA.BBBBBB.SS..',
        '..AA.BBGGBB..S..',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'beanie', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        R: { name: 'beard', role: 'hair' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'shirt', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'jeans', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'axe', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. HEALER — white cloak, green cross, herb pouch ───
    {
      id: 'healer_16',
      description: 'Field healer in white cloak with green cross emblem and herb pouch.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XXXXXXX.....',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HFFH.......',
        '......FF........',
        '...AABBBBAA.....',
        '...A.BBBB.A.....',
        '...A.BGBB.ASS...',
        '.....BBBBBB.....',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'cloak', role: 'body' },
        G: { name: 'cross', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'pouch', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. BEASTMASTER — fur cloak, pet on shoulder, whip ───
    {
      id: 'beastmaster_16',
      description: 'Wild beastmaster with fur cloak, animal companion on shoulder, and whip.',
      grid: [
        '....CC..........',
        '...CCC.RRR......',
        '...CC.RRHHRR....',
        '......HHHH......',
        '......HEEH......',
        '......HFFH......',
        '.......FF.......',
        '....AABBBBAA....',
        '.SS..ABBBBA.....',
        '..S...BGBB......',
        '..S...BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '....TTT..TTT....',
        '................',
      ],
      chars: {
        C: { name: 'companion', role: 'accessory' },
        R: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        A: { name: 'arms', role: 'arm' },
        B: { name: 'fur_vest', role: 'body' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
        S: { name: 'whip', role: 'hand' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
