/**
 * Cozy Life-Sim batch 2 — 20 more farming/garden/home themed sprites.
 * Stardew Valley quality: warm ambers, soft greens, earthy browns.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'cozy',
  exportNames: { templates: 'COZY_BATCH2_TEMPLATES', schemes: 'COZY_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. HERB GARDEN ──────────────────────────────────────────
    {
      id: 'herb_garden_16',
      description: 'Small herb garden planter box with three labeled herb sections.',
      grid: [
        '................',
        '..GGG..GGG..GGG.',
        '..GGGG.GGG.GGGG.',
        '...GGG.GGG.GGG..',
        '...GGG.GGG.GGG..',
        '..BBBBBBBBBBBB..',
        '..BDDDDDDDDDDB..',
        '..BDDDDDDDDDDB..',
        '..BDDDDDDDDDDB..',
        '..BHBHBHBHBHBB..',
        '..BBBBBBBBBBBB..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'herb_tops', role: 'eye' },
        B: { name: 'box_body', role: 'body' },
        D: { name: 'soil', role: 'belt' },
        H: { name: 'box_base', role: 'head' },
      },
      colors: {
        eye:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 2. JAM JAR ──────────────────────────────────────────────
    {
      id: 'jam_jar_16',
      description: 'Glass jar of fruit jam with cloth lid cover and twine tie.',
      grid: [
        '................',
        '....CCCCCCCC....',
        '...CCTTTTTTCC...',
        '...CTTTTTTTTCC..',
        '....CCCCCCCC....',
        '....JJJJJJJJ....',
        '...JJRRRRRRRJJ..',
        '...JJRRRRRRRJJ..',
        '...JJRRRRRRRJJ..',
        '...JJRRRRRRRJJ..',
        '...JJRRRRRRRJJ..',
        '...JJJJJJJJJJ...',
        '....HJJJJJJJH...',
        '....HHHHHHHHH...',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cloth_cover', role: 'head' },
        T: { name: 'twine_tie', role: 'accessory' },
        J: { name: 'jar_glass', role: 'body' },
        R: { name: 'jam_fill', role: 'eye' },
        H: { name: 'jar_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#6dc2ca', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 3. HONEY POT ────────────────────────────────────────────
    {
      id: 'honey_pot_16',
      description: 'Cute ceramic honey pot with lid, bee motif, and wooden dipper.',
      grid: [
        '..........DDD...',
        '.........DDDDD..',
        '.........DDDDD..',
        '..........DDDD..',
        '....LLLL..DDD...',
        '...LLLLLL.......',
        '..LHHHHHHHHL....',
        '..LHHHHHHHHLL...',
        '..LHBBBBBHHL....',
        '..LHBBYBBBHL....',
        '..LHHHHHHHHLL...',
        '..LLHHHHHHLL....',
        '...LLLLLLLL.....',
        '....TTTTTT......',
        '................',
        '................',
      ],
      chars: {
        D: { name: 'dipper', role: 'arm' },
        L: { name: 'pot_body', role: 'body' },
        H: { name: 'pot_surface', role: 'head' },
        B: { name: 'honey_fill', role: 'belt' },
        Y: { name: 'bee_motif', role: 'eye' },
        T: { name: 'pot_base', role: 'boot' },
      },
      colors: {
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        belt: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 4. BREAD BASKET ─────────────────────────────────────────
    {
      id: 'bread_basket_16',
      description: 'Woven wicker basket brimming with round bread rolls and cloth lining.',
      grid: [
        '................',
        '....RRRRRRRRR...',
        '...RRRRRRRRRRR..',
        '..RRRRRRRRRRRRR.',
        '...RRRRRRRRRRR..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBB..',
        '..HBWBWBWBWBBH..',
        '..HBBBBBBBBBBH..',
        '..HBWBWBWBWBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bread_rolls', role: 'head' },
        H: { name: 'basket_rim', role: 'body' },
        B: { name: 'basket_weave', role: 'belt' },
        W: { name: 'weave_accent', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. APRON ────────────────────────────────────────────────
    {
      id: 'apron_16',
      description: 'Kitchen apron hanging on a hook with bib, waist ties, and pocket.',
      grid: [
        '.......H........',
        '.......HH.......',
        '.......HH.......',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '..XBBBBBBBBBX...',
        '..XBBBPPPBBX....',
        '..XBBBBBBBBX....',
        '...BBBBBBBB.....',
        '..XBBBBBBBBX....',
        '..XBBBBBBBBX....',
        '..XBBBBBBBBX....',
        '...BBBBBBBB.....',
        '....BBBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hook', role: 'accessory' },
        B: { name: 'apron_body', role: 'body' },
        X: { name: 'waist_ties', role: 'arm' },
        P: { name: 'pocket', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 6. BUTTER CHURN ─────────────────────────────────────────
    {
      id: 'butter_churn_16',
      description: 'Old-fashioned wooden butter churn with plunger handle and barrel body.',
      grid: [
        '......PPP.......',
        '......PPP.......',
        '......PPP.......',
        '......PPP.......',
        '....HBBBBBH.....',
        '...HBBBBBBBH....',
        '..HBBBBBBBBBH...',
        '..HBBSSSSSBBH...',
        '..HBBSSSSSBBH...',
        '..HBBBBBBBBBH...',
        '..HBBBBBBBBBH...',
        '..HBBSSSSSBBH...',
        '..HBBBBBBBBBH...',
        '...HHHHHHHHHH...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        P: { name: 'plunger_handle', role: 'arm' },
        H: { name: 'barrel_stave', role: 'head' },
        B: { name: 'barrel_body', role: 'body' },
        S: { name: 'barrel_stripe', role: 'accessory' },
        T: { name: 'barrel_base', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. COOKIE JAR ───────────────────────────────────────────
    {
      id: 'cookie_jar_16',
      description: 'Ceramic cookie jar with dome lid, polka dot pattern, and cookie visible inside.',
      grid: [
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '....LLLLLLLL....',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBPBBPBBPBBH..',
        '..HBBBBBBBBBBH..',
        '..HBPBBPBBPBBH..',
        '..HBBBBBBBBBBH..',
        '..HBPBBPBBPBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHHH.',
        '...TTTTTTTTTTT..',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lid', role: 'head' },
        H: { name: 'jar_rim', role: 'accessory' },
        B: { name: 'jar_body', role: 'body' },
        P: { name: 'polka_dots', role: 'eye' },
        T: { name: 'jar_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 8. MILK PAIL ────────────────────────────────────────────
    {
      id: 'milk_pail_16',
      description: 'Metal milk pail with arched handle and foam milk top.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '....H......H....',
        '....H......H....',
        '....HHHHHHHH....',
        '...MMMMMMMMMM...',
        '..MMMMMMMMMMMM..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBBB.',
        '...BBBBBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'arm' },
        M: { name: 'milk_foam', role: 'head' },
        B: { name: 'pail_body', role: 'body' },
      },
      colors: {
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 9. EGG BASKET ───────────────────────────────────────────
    {
      id: 'egg_basket_16',
      description: 'Woven basket full of colorful spotted eggs.',
      grid: [
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '....HHHHHHH.....',
        '...EEEEEEEEE....',
        '..EEEEEEEEEEE...',
        '..ESEBEBEEESE...',
        '..EEEEEEEEEEE...',
        '..BBBBBBBBBB....',
        '..BWWWWWWWWBB...',
        '..BWWWWWWWWWB...',
        '..BWWWWWWWWWB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'basket_handle', role: 'arm' },
        E: { name: 'egg_cluster', role: 'head' },
        S: { name: 'egg_spots', role: 'eye' },
        B: { name: 'basket_body', role: 'body' },
        W: { name: 'basket_weave', role: 'accessory' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 10. GARDEN GLOVES ───────────────────────────────────────
    {
      id: 'garden_gloves_16',
      description: 'Pair of striped garden gloves with cuff, laid flat side by side.',
      grid: [
        '................',
        '..GGG....GGG....',
        '..GGGG..GGGG....',
        '..GGGGGGGGGGG...',
        '..GGGGGGGGGGG...',
        '..GGGGGSGGGGS...',
        '..GGGGGSGGGSS...',
        '..GGGGGGGGGSS...',
        '..GGGGGGGGGSS...',
        '..HHHHHHHHHHHH..',
        '..HSSSSSSSSSH...',
        '..HHHHHHHHHHHH..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'glove_body', role: 'body' },
        S: { name: 'stripe_accent', role: 'accessory' },
        H: { name: 'glove_cuff', role: 'head' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 11. BIRD BATH ───────────────────────────────────────────
    {
      id: 'bird_bath_16',
      description: 'Stone bird bath with wide shallow basin on decorative pedestal.',
      grid: [
        '................',
        '...BBBBBBBBBBB..',
        '..BBBWWWWWWBBBB.',
        '..BBWWWWWWWWBBB.',
        '..BBWWWWWWWWBBB.',
        '..BBBWWWWWWBBBB.',
        '...BBBBBBBBBBB..',
        '.....PPPPP......',
        '.....PPPPP......',
        '....PPPPPPP.....',
        '....PPPPPPP.....',
        '...PPPPPPPPP....',
        '...PPPPPPPPP....',
        '..TTTTTTTTTTT...',
        '..TTTTTTTTTTT...',
        '................',
      ],
      chars: {
        B: { name: 'basin_rim', role: 'head' },
        W: { name: 'water', role: 'eye' },
        P: { name: 'pedestal', role: 'body' },
        T: { name: 'base_slab', role: 'boot' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot: { shadow: '#4e4a4e', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 12. RAIN BARREL ─────────────────────────────────────────
    {
      id: 'rain_barrel_16',
      description: 'Wooden rain collection barrel with metal bands and spigot tap.',
      grid: [
        '....HHHHHHHH....',
        '...HHBBBBBBHH...',
        '..HHBBBBBBBBHH..',
        '..HBBBBBBBBBBH..',
        '..HMMMMMMMMMMBH.',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HMMMMMMMMMMBH.',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HMMMMMMMMMMBH.',
        '..HBBBBBBBBBBH..',
        '..HHBBBBBBBBHHH.',
        '...HHHHHHHHHHH..',
        '.......SSS......',
        '......SSSSS.....',
      ],
      chars: {
        H: { name: 'barrel_stave', role: 'head' },
        B: { name: 'barrel_body', role: 'body' },
        M: { name: 'metal_band', role: 'belt' },
        S: { name: 'spigot', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 13. COMPOST BIN ─────────────────────────────────────────
    {
      id: 'compost_bin_16',
      description: 'Wooden compost bin with slatted sides, lid, and leaf/scraps inside.',
      grid: [
        '................',
        '..LLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..LLHHHHHHHHHH..',
        '..HBBBBBBBBBHH..',
        '..HBBGGGGGBBH...',
        '..HBBGGGGGBBH...',
        '..HBBBBBBBBHH...',
        '..HBBBBBBBBBHH..',
        '..HBBGGGGGBBH...',
        '..HBBGGGGGBBH...',
        '..HBBBBBBBBBHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lid', role: 'head' },
        H: { name: 'slat_frame', role: 'body' },
        B: { name: 'slat_panel', role: 'arm' },
        G: { name: 'compost_fill', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. TOOL SHED ───────────────────────────────────────────
    {
      id: 'tool_shed_16',
      description: 'Small garden tool shed with peaked roof, door, and window.',
      grid: [
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '..RRRRRRRRRRRR..',
        '.RRRRRRRRRRRRRR.',
        '..WWWWWWWWWWWW..',
        '..WWWWWWWWWWWW..',
        '..WWWEEEWWWWWW..',
        '..WWWEEEWWWDWW..',
        '..WWWEEEWWWDWW..',
        '..WWWWWWWWWDWW..',
        '..WWWWWWWWWDWW..',
        '..WWWWWWWWWDWW..',
        '..WWWWWWWWWDWW..',
        '..WWWWWWWWWWWW..',
        '..BBBBBBBBBBBB..',
        '................',
      ],
      chars: {
        R: { name: 'roof', role: 'head' },
        W: { name: 'wall', role: 'body' },
        E: { name: 'window', role: 'eye' },
        D: { name: 'door', role: 'belt' },
        B: { name: 'foundation', role: 'boot' },
      },
      colors: {
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. MAILBOX COZY ────────────────────────────────────────
    {
      id: 'mailbox_cozy_16',
      description: 'Cute red mailbox on post with raised flag and letter slot.',
      grid: [
        '................',
        '........FFFF....',
        '........FFFF....',
        '........F.......',
        '...RRRRRRRRRR...',
        '..RHHHHHHHHHRR..',
        '..RHSSSSSSSSHR..',
        '..RHSSSSSSSSHR..',
        '..RHSSSSSSSSHR..',
        '..RHRRRRRRRHRR..',
        '..RRRRRRRRRRRR..',
        '....PPPP........',
        '....PPPP........',
        '....PPPP........',
        '...PPPPPP.......',
        '................',
      ],
      chars: {
        F: { name: 'flag', role: 'eye' },
        R: { name: 'box_body', role: 'body' },
        H: { name: 'box_highlight', role: 'head' },
        S: { name: 'box_side', role: 'accessory' },
        P: { name: 'post', role: 'leg' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 16. GARDEN FENCE ────────────────────────────────────────
    {
      id: 'garden_fence_16',
      description: 'White picket fence section with pointed tops and cross rail.',
      grid: [
        '..P..P..P..P..P.',
        '..P..P..P..P..P.',
        '.PPP.PPP.PPP.PP.',
        '.PPP.PPP.PPP.PP.',
        '..P..P..P..P..P.',
        '.RRRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRRR.',
        '..P..P..P..P..P.',
        '..P..P..P..P..P.',
        '.RRRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRRR.',
        '..P..P..P..P..P.',
        '..P..P..P..P..P.',
        '..P..P..P..P..P.',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'picket', role: 'body' },
        R: { name: 'cross_rail', role: 'head' },
      },
      colors: {
        body: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 17. STEPPING STONE ──────────────────────────────────────
    {
      id: 'stepping_stone_16',
      description: 'Garden stepping stone path with two rounded mossy stones.',
      grid: [
        '................',
        '................',
        '.SSSSSSS........',
        'SSSSSSSSSS......',
        'SSHSSSSSSSS.....',
        'SSSSSSSSSSSS....',
        'SSSSSSSSSSSSS...',
        '.SSSSSSSSSSSSSS.',
        '..SSSSSSSSSSSSS.',
        '...SSSSSSSSSSSS.',
        '....SSSSSSSSSSSS',
        '.....SSSSHSSSSS.',
        '......SSSSSSSS..',
        '.......SSSSSS...',
        '........SSSS....',
        '................',
      ],
      chars: {
        S: { name: 'stone_surface', role: 'body' },
        H: { name: 'stone_highlight', role: 'head' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head: { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 18. SUNDIAL ─────────────────────────────────────────────
    {
      id: 'sundial_16',
      description: 'Garden sundial with ornate face, gnomon fin, and stone pedestal.',
      grid: [
        '................',
        '......GGG.......',
        '.....GGGGG......',
        '.....GGGGG......',
        '....FFFFFFF.....',
        '...FFFFFFFFF....',
        '..FFFFFFFFFFF...',
        '..FFFEFFFEFFF...',
        '..FFFFFFFFFFF...',
        '..FFFFFFFFFFFF..',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '....PPPPPPPP....',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '................',
      ],
      chars: {
        G: { name: 'gnomon', role: 'arm' },
        F: { name: 'dial_face', role: 'body' },
        E: { name: 'hour_marks', role: 'eye' },
        P: { name: 'pedestal', role: 'head' },
      },
      colors: {
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. HAMMOCK ─────────────────────────────────────────────
    {
      id: 'hammock_16',
      description: 'Hammock strung between two wooden posts with rope ties and sag.',
      grid: [
        '.PP..........PP.',
        '.PP..........PP.',
        '.PP..RRRRRR..PP.',
        '.PPRRRRRRRRRRRP.',
        '.PRRRRRRRRRRRPP.',
        '.PHHHHHHHHHHHPP.',
        '.PHHHHHHHHHHHPP.',
        '.PHHHHHHHHHHHPP.',
        '.PRHHHHHHHHHRRP.',
        '.PPRRRRRRRRRRRP.',
        '.PP..RRRRRRR.PP.',
        '.PP..........PP.',
        '.PP..........PP.',
        '.PP..........PP.',
        '.PP..........PP.',
        '................',
      ],
      chars: {
        P: { name: 'post', role: 'body' },
        R: { name: 'rope_ties', role: 'arm' },
        H: { name: 'hammock_fabric', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. LANTERN POST ────────────────────────────────────────
    {
      id: 'lantern_post_16',
      description: 'Garden lantern on a post with glowing panes and decorative cap.',
      grid: [
        '.....CCCCC......',
        '....CCCCCCC.....',
        '....CGGGGGC.....',
        '....CGGGGGC.....',
        '....CBBBBBCC....',
        '....CBBYBBC.....',
        '....CBBYBBC.....',
        '....CBBBBBCC....',
        '....CGGGGGC.....',
        '....CGGGGGC.....',
        '....CCCCCCC.....',
        '.....PPPPP......',
        '.....PPPPP......',
        '.....PPPPP......',
        '....PPPPPPP.....',
        '...PPPPPPPPP....',
      ],
      chars: {
        C: { name: 'lantern_frame', role: 'head' },
        G: { name: 'glass_pane', role: 'body' },
        B: { name: 'flame_glow', role: 'eye' },
        Y: { name: 'flame_core', role: 'accessory' },
        P: { name: 'post', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
