/**
 * Cozy Life-Sim batch 1 — 20 farming/crafting/home themed sprites.
 * Stardew Valley quality: warm ambers, soft greens, earthy browns.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'cozy',
  exportNames: { templates: 'COZY_BATCH1_TEMPLATES', schemes: 'COZY_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SEED PACKET ──────────────────────────────────────────
    {
      id: 'seed_packet_16',
      description: 'Paper seed packet with flower illustration and label band.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHHB..',
        '..BHHFHHHHHHHB..',
        '..BHHFFFHHHHHB..',
        '..BHHFHHHHHHHB..',
        '..BHHHHHHHHHHB..',
        '..BXXXXXXXXXXB..',
        '..BXXXXXXXXXXB..',
        '..BBBBBBBBBBB...',
        '..BLLLLLLLLBB...',
        '..BLLLLLLLLBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'packet_body', role: 'body' },
        H: { name: 'flower_area', role: 'head' },
        F: { name: 'flower', role: 'eye' },
        X: { name: 'label_band', role: 'belt' },
        L: { name: 'label_text', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. GARDEN HOE ───────────────────────────────────────────
    {
      id: 'garden_hoe_16',
      description: 'Wooden garden hoe with wide metal blade top and long handle.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '...HHHHHHHHHH...',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XXXX......',
        '......XEXX......',
        '.....XXXXXX.....',
        '................',
      ],
      chars: {
        H: { name: 'blade_rim', role: 'head' },
        B: { name: 'blade_face', role: 'body' },
        X: { name: 'handle', role: 'arm' },
        E: { name: 'handle_knot', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 3. SPRINKLER ────────────────────────────────────────────
    {
      id: 'sprinkler_16',
      description: 'Garden sprinkler head on stake spraying water arcs.',
      grid: [
        '.W...W...W...W..',
        '..W.W.W.W.W.W...',
        '....W...W...W...',
        '...HHHHHHHH.....',
        '..HHBBBBBBHH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBXXXXXBH....',
        '..HHBBBBBBHH....',
        '...HHHHHHHH.....',
        '.....XXXX.......',
        '.....XXXX.......',
        '.....XXXX.......',
        '....XXXXXX......',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'water_spray', role: 'eye' },
        H: { name: 'head_rim', role: 'head' },
        B: { name: 'head_body', role: 'body' },
        X: { name: 'stake', role: 'arm' },
      },
      colors: {
        eye:  { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. SCARECROW ────────────────────────────────────────────
    {
      id: 'scarecrow_16',
      description: 'Cute scarecrow with straw hat, patched shirt, stick arms.',
      grid: [
        '....HHHHHHH.....',
        '...HHHHHHHHH....',
        '....HHHHHHHH....',
        '....HFEEFHHH....',
        '....HHHHHHHH....',
        '..XXXBBBBBBXXX..',
        '...BBBBBBBBBBB..',
        '...BBPBBBBPBB...',
        '...BBBBBBBBB....',
        '....LLLLLLL.....',
        '....LLLLLLL.....',
        '....LL...LL.....',
        '....LL...LL.....',
        '....BB...BB.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hat', role: 'head' },
        F: { name: 'face', role: 'eye' },
        E: { name: 'eyes', role: 'eye' },
        X: { name: 'stick_arms', role: 'arm' },
        B: { name: 'shirt', role: 'body' },
        P: { name: 'patches', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. BEEHIVE ──────────────────────────────────────────────
    {
      id: 'beehive_16',
      description: 'Straw beehive dome with bees buzzing around entrance.',
      grid: [
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHBBBBHH....',
        '...HHBBBBBBHH...',
        '..HHBBBBBBBBHH..',
        '..HHBBBBBBBBHH..',
        '..HHBBBBBBBBHH..',
        '..HHBBXXXBBHH...',
        '..HHBBBBBBBBHH..',
        '...XHHHHHHHX....',
        '.X..XXXXXXXX..X.',
        '....XXXXXXXX....',
        '..X.XXXXXXXX.X..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hive_straw', role: 'head' },
        B: { name: 'hive_body', role: 'body' },
        X: { name: 'entrance_bees', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. FLOWER POT ───────────────────────────────────────────
    {
      id: 'flower_pot_16',
      description: 'Terracotta pot with leafy plant and bright flower bloom.',
      grid: [
        '................',
        '.......FF.......',
        '......FFFF......',
        '.....GGFFGG.....',
        '....GGGGGGGG....',
        '.....GGGGGG.....',
        '...HGGGGGGGGH...',
        '....HHHHHHHH....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...HBBBBBBBBH...',
        '....HHHHHHHH....',
        '.....XXXXXX.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flower', role: 'eye' },
        G: { name: 'leaves', role: 'accessory' },
        H: { name: 'pot_rim', role: 'head' },
        B: { name: 'pot_body', role: 'body' },
        X: { name: 'saucer', role: 'boot' },
      },
      colors: {
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 7. WHEELBARROW ──────────────────────────────────────────
    {
      id: 'wheelbarrow_16',
      description: 'Wooden wheelbarrow with metal wheel, loaded with soil.',
      grid: [
        '................',
        '................',
        '...BBBBBBBBB....',
        '..BBBDDDDDBBBB..',
        '..BBDDDDDDDDBB..',
        '..BBDDDDDDDDBB..',
        '..BBBBBBBBBBBBB.',
        '...HHHHHHHHHHXX.',
        '....H.......HXX.',
        '....H.......H...',
        '....H......HH...',
        '.....HHHHHHH....',
        '......WWWW......',
        '.....WWWWWW.....',
        '......WWWW......',
        '................',
      ],
      chars: {
        B: { name: 'tray', role: 'body' },
        D: { name: 'dirt', role: 'belt' },
        H: { name: 'frame', role: 'head' },
        X: { name: 'handles', role: 'arm' },
        W: { name: 'wheel', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 8. HAY BALE ─────────────────────────────────────────────
    {
      id: 'hay_bale_16',
      description: 'Round hay bale wrapped in twine, warm golden straw.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHHBBHHHHHH.',
        '..HHHHBBBBBHHHH.',
        '..HHHHBBBBBHHHH.',
        '..HHHHBBBBBHHHH.',
        '..HHHHHBBHHHHHH.',
        '..HHHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '....HHHHHHHHHH..',
        '.....XXXXXXXX...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'straw', role: 'body' },
        B: { name: 'twine_band', role: 'belt' },
        X: { name: 'ground_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 9. MIXING BOWL ──────────────────────────────────────────
    {
      id: 'mixing_bowl_16',
      description: 'Large ceramic mixing bowl with batter and a wooden spoon.',
      grid: [
        '................',
        '................',
        '..........SSS...',
        '.........SSSSS..',
        '.........SSSSS..',
        '...HHHHHHHHHHH..',
        '..HBBBBBBBBBBHH.',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '...HBBBBBBBBBH..',
        '...HHBBBBBBBHH..',
        '....HHHHHHHH....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'spoon', role: 'arm' },
        H: { name: 'bowl_rim', role: 'head' },
        B: { name: 'batter', role: 'body' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. ROLLING PIN ─────────────────────────────────────────
    {
      id: 'rolling_pin_16',
      description: 'Wooden rolling pin with handles, resting on flat dough.',
      grid: [
        '................',
        '................',
        '...HH.......HH..',
        '..HHHH.....HHHH.',
        '..HHHH.....HHHH.',
        '..HHHBBBBBBHHHH.',
        '..HHHBBBBBBHHHH.',
        '..HHHBBBBBBHHHH.',
        '..HHHBBBBBBHHHH.',
        '..HHHH.....HHHH.',
        '..HHHH.....HHHH.',
        '...HH.......HH..',
        '................',
        '.DDDDDDDDDDDDDD.',
        '.DDDDDDDDDDDDDD.',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'arm' },
        B: { name: 'roller', role: 'body' },
        D: { name: 'dough', role: 'accessory' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 11. CUTTING BOARD ───────────────────────────────────────
    {
      id: 'cutting_board_16',
      description: 'Wooden cutting board with sliced carrot and leafy herb.',
      grid: [
        '................',
        '...HHHHHHHHHH...',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '...HBBBCCCBBH...',
        '...HBBCCCCBBH...',
        '...HBCCCCCCBH...',
        '...HBBCCCCBBH...',
        '...HBBBCCCBBH...',
        '...HBGGGGGBBH...',
        '...HBGGBGBBH....',
        '...HBBGGGBBH....',
        '...HBBBBBBBH....',
        '...HHHHHHHHHH...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'board_edge', role: 'head' },
        B: { name: 'board_surface', role: 'body' },
        C: { name: 'carrot_slices', role: 'accessory' },
        G: { name: 'herb_leaves', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 12. OVEN MITT ───────────────────────────────────────────
    {
      id: 'oven_mitt_16',
      description: 'Quilted oven mitt with thumb nub and hanging loop.',
      grid: [
        '................',
        '.......X........',
        '......XXX.......',
        '.....BBBBB......',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '...BBPBPBPBB....',
        '...BBBBBBBBB....',
        '...BBPBPBPBB....',
        '...BBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..HBBBBBBBBH....',
        '..HHHHHHHHHH....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hanging_loop', role: 'accessory' },
        B: { name: 'mitt_body', role: 'body' },
        P: { name: 'quilt_stitches', role: 'belt' },
        H: { name: 'cuff', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 13. SEWING KIT ──────────────────────────────────────────
    {
      id: 'sewing_kit_16',
      description: 'Open sewing kit tin with thread spool, needle, and buttons.',
      grid: [
        '................',
        '..BBBBBBBBBBB...',
        '..BSSSSSSSSSB...',
        '..BSSSSSSSSBB...',
        '..BBBBBBBBBBB...',
        '..BTTTTTTTTBB...',
        '..BTBBBBBBTTB...',
        '..BTBBBBBBTTB...',
        '..BBBBBBBBBBB...',
        '..BNNBBBBBBBB...',
        '..BNNNBBBBBBB...',
        '..BNNBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'tin_body', role: 'body' },
        S: { name: 'lid_interior', role: 'head' },
        T: { name: 'thread_spool', role: 'accessory' },
        N: { name: 'needle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 14. PAINT PALETTE ───────────────────────────────────────
    {
      id: 'paint_palette_16',
      description: 'Wooden artist palette with thumb hole and blobs of color.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '.HHHRHHBHHGHHH..',
        '.HH.RRRBBHGGHH..',
        '.HH.HRRBBGGGHHH.',
        '..HHHHHHHGGGHH..',
        '..HHHHHYYYYYHHH.',
        '..HHHHYYYYHHHH..',
        '...HHHYYYYHHHH..',
        '....HHHHHHHHH...',
        '.....HHHHHH.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'palette_wood', role: 'body' },
        R: { name: 'red_paint', role: 'accessory' },
        B: { name: 'blue_paint', role: 'arm' },
        G: { name: 'green_paint', role: 'eye' },
        Y: { name: 'yellow_paint', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 15. YARN BALL ───────────────────────────────────────────
    {
      id: 'yarn_ball_16',
      description: 'Fluffy yarn ball with knitting needles crossed through it.',
      grid: [
        '................',
        '..........NN....',
        '.........NNN....',
        '....BBBBBNN.....',
        '...BBBBBBBBN....',
        '..BBBBBBBBBBN...',
        '..BBBXBBBXBBB...',
        '..BBBBBBBBBBB...',
        '..BBBXBBBXBBB...',
        '..BBBBBBBBBBB...',
        '...NBBBBBBBBB...',
        '....NBBBBBBNN...',
        '.....BNBBBN.....',
        '......NNN.......',
        '.......N........',
        '................',
      ],
      chars: {
        B: { name: 'yarn_body', role: 'body' },
        X: { name: 'yarn_cross', role: 'accessory' },
        N: { name: 'needles', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 16. OPEN SIGN ───────────────────────────────────────────
    {
      id: 'open_sign_16',
      description: 'Hanging OPEN shop sign on two chains with decorative border.',
      grid: [
        '...C........C...',
        '...C........C...',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHHB..',
        '..BH........HB..',
        '..BH..OOOO..HB..',
        '..BH.O.PP.O.HB..',
        '..BH.OPPPPO.HB..',
        '..BH.O.PP.O.HB..',
        '..BH..OOOO..HB..',
        '..BH........HB..',
        '..BHHHHHHHHHHB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'chain', role: 'accessory' },
        B: { name: 'sign_board', role: 'body' },
        H: { name: 'sign_border', role: 'head' },
        O: { name: 'open_text_outline', role: 'belt' },
        P: { name: 'open_text_fill', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 17. GIFT BOX ────────────────────────────────────────────
    {
      id: 'gift_box_16',
      description: 'Wrapped gift box with ribbon, bow on top, polka dot paper.',
      grid: [
        '......BBBBB.....',
        '.....BBBBBBB....',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '..RRRRRRRRRRRR..',
        '..RBBBBBBBBBBBR.',
        '..RBBBPBPBPBBBR.',
        '..RRRRRRRRRRRR..',
        '..RBBBPBPBPBBBR.',
        '..RBBBBBBBBBBBR.',
        '..RBBBPBPBPBBBR.',
        '..RBBBBBBBBBBBR.',
        '..RRRRRRRRRRRR..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bow', role: 'head' },
        R: { name: 'ribbon', role: 'arm' },
        P: { name: 'polka_dots', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 18. WELCOME MAT ─────────────────────────────────────────
    {
      id: 'welcome_mat_16',
      description: 'Woven doormat with decorative border and greeting text.',
      grid: [
        '................',
        '................',
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BHHHHHHHHHHHHB.',
        '.BH..........HB.',
        '.BH.WWWWWWWW.HB.',
        '.BH.WWWWWWWW.HB.',
        '.BH.WWWWWWWW.HB.',
        '.BH.WWWWWWWW.HB.',
        '.BH..........HB.',
        '.BHHHHHHHHHHHHB.',
        '.BBBBBBBBBBBBBB.',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'mat_edge', role: 'body' },
        H: { name: 'inner_border', role: 'head' },
        W: { name: 'woven_text', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 19. WIND CHIME ──────────────────────────────────────────
    {
      id: 'wind_chime_16',
      description: 'Hanging wind chime with wooden top bar, metal tubes, beads.',
      grid: [
        '......HHHH......',
        '......HHHH......',
        '.X.X.HHHHHH.X.X.',
        '.X.X..HHHH..X.X.',
        '.X.X..X..X..X.X.',
        '.T.T..T..T..T.T.',
        '.T....T..T....T.',
        '.T....T..T....T.',
        '.T....T..T....T.',
        '.T....T..T....T.',
        '.T....T..T....T.',
        '..T...T..T...T..',
        '..B...B..B...B..',
        '..B...B..B...B..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_bar', role: 'head' },
        X: { name: 'string_beads', role: 'accessory' },
        T: { name: 'tubes', role: 'body' },
        B: { name: 'tube_caps', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 20. BIRD HOUSE ──────────────────────────────────────────
    {
      id: 'bird_house_16',
      description: 'Charming bird house on pole with peaked roof and entry hole.',
      grid: [
        '......HHH.......',
        '.....HHHHH......',
        '....HHBBBHH.....',
        '...HHHBBBBBHHH..',
        '..HHHBBBBBBBBH..',
        '..HHHBBBBBBBBH..',
        '..HHHBBEOOEBBH..',
        '..HHHBBBBBBBBH..',
        '..HHHBB..BBBBH..',
        '..HHHBBBBBBBBH..',
        '...HHBBBBBBBHH..',
        '....HHHHHHHHHH..',
        '.....PPPP.......',
        '.....PPPP.......',
        '.....PPPP.......',
        '....PPPPPP......',
      ],
      chars: {
        H: { name: 'roof', role: 'head' },
        B: { name: 'house_body', role: 'body' },
        E: { name: 'entry_hole', role: 'eye' },
        O: { name: 'perch', role: 'accessory' },
        P: { name: 'pole', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
