/**
 * Cozy Life-Sim batch 3 — 20 home/garden/keepsake themed sprites.
 * Stardew Valley quality: warm ambers, soft greens, earthy browns, pastel blues.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'cozy',
  exportNames: { templates: 'COZY_BATCH3_TEMPLATES', schemes: 'COZY_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TEAPOT COZY ──────────────────────────────────────────
    {
      id: 'teapot_cozy_16',
      description: 'Round teapot sitting on a knitted cozy warmer with spout and lid knob.',
      grid: [
        '................',
        '.......K........',
        '......KKK.......',
        '.....LLLLL......',
        '....LLLLLLL.....',
        'S...LBBBBBBL....',
        'SS..LBBBBBBL....',
        'SS..LBBBBBBL....',
        'S...LBBBBBBL....',
        '....LBBBBBBL....',
        '.....LLLLLLL....',
        '.....WWWWWWW....',
        '....WWWWWWWWW...',
        '....WWWWWWWWW...',
        '.....WWWWWWW....',
        '................',
      ],
      chars: {
        K: { name: 'lid_knob', role: 'head' },
        L: { name: 'lid_rim', role: 'belt' },
        B: { name: 'pot_body', role: 'body' },
        S: { name: 'spout', role: 'arm' },
        W: { name: 'cozy_warmer', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 2. PIE COOLING ──────────────────────────────────────────
    {
      id: 'pie_cooling_16',
      description: 'Fresh baked pie cooling on a windowsill ledge with steam wisps.',
      grid: [
        '....S.....S.....',
        '.....S...S......',
        '......S.S.......',
        '...CCCCCCCCCCC..',
        '..CCRRRRRRRRRCC.',
        '..CRRRRRRRRRRRC.',
        '..CRRXRXRXRRRRC.',
        '..CRRRRRRRRRRRC.',
        '..CCRRRRRRRRRCC.',
        '...CCCCCCCCCCC..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        'WWWWWWWWWWWWWWWW',
        'WWWWWWWWWWWWWWWW',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'eye' },
        C: { name: 'crust_edge', role: 'head' },
        R: { name: 'pie_filling', role: 'body' },
        X: { name: 'crust_slits', role: 'belt' },
        B: { name: 'pie_dish', role: 'accessory' },
        W: { name: 'windowsill', role: 'boot' },
      },
      colors: {
        eye:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. CAT BED ──────────────────────────────────────────────
    {
      id: 'cat_bed_16',
      description: 'Cozy round cat bed cushion with a sleeping cat curled inside.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBCCCCCCBBB..',
        '..BBCCCCCCCCBB..',
        '..BBCCTTTTCCBB..',
        '..BBCCTTTTTCBB..',
        '..BBCCTTTTTCBB..',
        '..BBCCTTTTCCBB..',
        '..BBBCCCCCCBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bed_rim', role: 'body' },
        C: { name: 'cushion', role: 'head' },
        T: { name: 'cat_fur', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 4. DOG BOWL ─────────────────────────────────────────────
    {
      id: 'dog_bowl_16',
      description: 'Pet food bowl with kibble pieces and a paw print on the side.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHKKKKKKKKHH..',
        '..HHKKKKKKKKHH..',
        '..HHKKFKFKKKHH..',
        '..HHKKKKKKKKHH..',
        '..HHKKKKKKKKHH..',
        '..HHBBBBBBBBHH..',
        '..HHHBBBBBBHHH..',
        '...HHHPPPPHHH...',
        '....HHHPPPHHH...',
        '.....HHHHHHH....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bowl_rim', role: 'head' },
        K: { name: 'kibble_fill', role: 'body' },
        F: { name: 'kibble_pieces', role: 'belt' },
        B: { name: 'bowl_base', role: 'arm' },
        P: { name: 'paw_print', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 5. FLOWER WREATH ────────────────────────────────────────
    {
      id: 'flower_wreath_16',
      description: 'Door flower wreath of green leaves with pink and yellow blooms.',
      grid: [
        '....GGGGGGGGG...',
        '...GGHHHHHHHGG..',
        '..GGHHFHHHFHHGG.',
        '..GHHHFFFHFFFHG.',
        '..GHHHFHHHFHHHG.',
        '..GHHHHHHHHFHHG.',
        '..GHHHFHHHHHHGG.',
        'G..HHHHYHYHHG...',
        '.G..GHHHHHG.....',
        '..GG.GHHHG.GG...',
        '..GG.GHHHG.GG...',
        '..GGGHHHHHGGG...',
        '..GGHHHHHHHGG...',
        '...GGYYHHYYGG...',
        '....GGGGGGGGG...',
        '................',
      ],
      chars: {
        G: { name: 'leaves', role: 'body' },
        H: { name: 'wreath_base', role: 'head' },
        F: { name: 'pink_flowers', role: 'eye' },
        Y: { name: 'yellow_flowers', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 6. BUTTERFLY JAR ────────────────────────────────────────
    {
      id: 'butterfly_jar_16',
      description: 'Glass jar with a butterfly inside, metal lid with air holes.',
      grid: [
        '................',
        '....MMMMMMMM....',
        '....MHHHHHHM....',
        '....MHHHHHHM....',
        '....GGGGGGGG....',
        '...GGBBBBBBGG...',
        '...GBB.WW.BBG...',
        '...GB.BWWB.BG...',
        '...GBB.WW.BBG...',
        '...GB.BWWB.BG...',
        '...GBB.WW.BBG...',
        '...GGBBBBBBGG...',
        '...GGGGGGGGG....',
        '....GGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'metal_lid', role: 'head' },
        H: { name: 'lid_holes', role: 'belt' },
        G: { name: 'glass_jar', role: 'body' },
        B: { name: 'butterfly_wings', role: 'accessory' },
        W: { name: 'butterfly_body', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 7. SOAP BAR ─────────────────────────────────────────────
    {
      id: 'soap_bar_16',
      description: 'Handmade artisan soap bar with a paper label and herb sprig.',
      grid: [
        '................',
        '................',
        '...HHHHHHHHHHH..',
        '..HBBBBBBBBBBBH.',
        '..HBBBBBBBBBBBH.',
        '..HBBLLLLLLLBBH.',
        '..HBBLLLLLLLBBH.',
        '..HBBLLLLLLLBBH.',
        '..HBBLLLLLLLBBH.',
        '..HBBBBBBBBBBBH.',
        '..HBBBBBBBBBBBH.',
        '..HBBBGGBBBBBHH.',
        '...HBBBGBBBHHH..',
        '....HHHHHHHHH...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'soap_edge', role: 'head' },
        B: { name: 'soap_body', role: 'body' },
        L: { name: 'paper_label', role: 'accessory' },
        G: { name: 'herb_sprig', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. CANDLE HOLDER ────────────────────────────────────────
    {
      id: 'candle_holder_16',
      description: 'Decorative candle in an ornate brass holder with dripping wax.',
      grid: [
        '.......FF.......',
        '......FFFF......',
        '......FFFF......',
        '.......CC.......',
        '......CCCC......',
        '......CCCC......',
        '......CCWW......',
        '......CCWW......',
        '......CCCC......',
        '......CCCC......',
        '......CCCC......',
        '...HHHHHHHHHH...',
        '..HHBBBBBBBBHH..',
        '..HHBBBBBBBBHH..',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
      ],
      chars: {
        F: { name: 'flame', role: 'eye' },
        C: { name: 'candle_body', role: 'body' },
        W: { name: 'wax_drip', role: 'belt' },
        H: { name: 'holder_rim', role: 'head' },
        B: { name: 'holder_dish', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 9. MUSIC BOX COZY ───────────────────────────────────────
    {
      id: 'music_box_cozy_16',
      description: 'Open ornate music box with a tiny dancer figure and gold trim.',
      grid: [
        '................',
        '......DDD.......',
        '.....DDDDD......',
        '......DDD.......',
        '...HHHHHHHHH....',
        '..HBBBBBBBBBBH..',
        '..HBBGGBBBBBBH..',
        '..HBBBGBBBBBHH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHHH.',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHHH.',
        '...XXXXXXXXXXXH.',
        '................',
      ],
      chars: {
        D: { name: 'dancer_figure', role: 'eye' },
        H: { name: 'box_frame', role: 'head' },
        B: { name: 'box_interior', role: 'body' },
        G: { name: 'gold_accent', role: 'accessory' },
        X: { name: 'box_base', role: 'boot' },
      },
      colors: {
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. SNOW GLOBE ──────────────────────────────────────────
    {
      id: 'snow_globe_16',
      description: 'Snow globe with a little house scene inside, on a wooden base.',
      grid: [
        '................',
        '.....GGGGGGG....',
        '....GGGGGGGGG...',
        '...GGGHHHHGGGG..',
        '...GGHHHHHHHGG..',
        '..GGHHSSHSSHHHG.',
        '..GGHSHHHHHSHHG.',
        '..GGHSSHHHHSHHG.',
        '..GGHHHHHHHSHHG.',
        '..GGHSHHHHHSHHG.',
        '..GGGSSSSSSSGGG.',
        '...GGGGGGGGGG...',
        '....GGGGGGGG....',
        '...BBBBBBBBBBB..',
        '..BBBBBBBBBBBBB.',
        '................',
      ],
      chars: {
        G: { name: 'glass_dome', role: 'body' },
        H: { name: 'snow_scene', role: 'head' },
        S: { name: 'snow_flakes', role: 'accessory' },
        B: { name: 'wood_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 11. QUILT SQUARE ────────────────────────────────────────
    {
      id: 'quilt_square_16',
      description: 'Patchwork quilt square with four colored fabric patches and stitching.',
      grid: [
        '................',
        '.XXXXXXXXXXXXXX.',
        '.XAAAXXXXXBBBXX.',
        '.XAAAX.XXXBBBXX.',
        '.XAAAXXXXXBBBXX.',
        '.XAAAXXXXXBBBXX.',
        '.XXXXXXXXXXXXXX.',
        '.XXXXXXXXXXXXXX.',
        '.XCCCXXXXXDDDXX.',
        '.XCCCX.XXXDDDXX.',
        '.XCCCXXXXXDDDXX.',
        '.XCCCXXXXXDDDXX.',
        '.XXXXXXXXXXXXXX.',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'stitch_lines', role: 'head' },
        A: { name: 'patch_amber', role: 'body' },
        B: { name: 'patch_blue', role: 'arm' },
        C: { name: 'patch_green', role: 'leg' },
        D: { name: 'patch_rose', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 12. HERB BUNDLE ─────────────────────────────────────────
    {
      id: 'herb_bundle_16',
      description: 'Dried herb bundle hanging upside down tied with twine.',
      grid: [
        '.......TT.......',
        '.......TT.......',
        '......TTTT......',
        '......TTTT......',
        '.....GGTTGG.....',
        '....GGGTTTGGG...',
        '....GGGTTTGGG...',
        '...GGGGTTTTGG...',
        '...GGGGTTTTGG...',
        '....GGGTTTTG....',
        '....GGGTTTGG....',
        '.....GGTTTG.....',
        '.....GGGTTG.....',
        '......GGTG......',
        '......GGGG......',
        '......GG........',
      ],
      chars: {
        T: { name: 'twine_tie', role: 'accessory' },
        G: { name: 'herb_leaves', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. WISHING WELL COZY ───────────────────────────────────
    {
      id: 'wishing_well_cozy_16',
      description: 'Small decorative wishing well with a thatched roof and bucket.',
      grid: [
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        'P....RRRRRR....P',
        'PP...RRRRRR..PPP',
        'PP..WWWWWWWW.PPP',
        'PP..WBBBBBBW.PPP',
        'PP..WBBBBBBW.PPP',
        'PP..WBBBBBBW.PPP',
        'PP..WWWWWWWW.PPP',
        'PP..SSSSSSSS.PPP',
        'PP..SSSSSSSS.PPP',
        'PP..SSSSSSSS.PPP',
        'PP..SSSSSSSS.PPP',
        '....CCCCCCCC....',
        '................',
      ],
      chars: {
        R: { name: 'thatched_roof', role: 'head' },
        P: { name: 'wood_posts', role: 'arm' },
        W: { name: 'well_rim', role: 'belt' },
        B: { name: 'well_interior', role: 'body' },
        S: { name: 'stone_wall', role: 'accessory' },
        C: { name: 'base_ground', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. FLOWER CROWN ────────────────────────────────────────
    {
      id: 'flower_crown_16',
      description: 'Wearable flower crown wreath with pink blooms and green leaf band.',
      grid: [
        '................',
        '................',
        '...F..F..F..F...',
        '..FFFF.FFFF.FF..',
        '.FFFF...FFFF.FF.',
        '.FFFFF.FFFFF.F..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GGGYYGGYYYYY..',
        '..GGYYGGGYYYY...',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'pink_petals', role: 'eye' },
        G: { name: 'leaf_band', role: 'body' },
        Y: { name: 'yellow_blooms', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 15. TREASURE BOX ────────────────────────────────────────
    {
      id: 'treasure_box_16',
      description: 'Small wooden keepsake box with brass latch and carved lid design.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBGGGGGGGBBH..',
        '..HBBGGGGGBBBH..',
        '..HBBBGGGBBBBH..',
        '..HBBBBGBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..LLLLLLLLLLLLL.',
        '..LBBBBBBBBBBBLL',
        '..LBBBBBBBBBBBLL',
        '..LBBBBBBBBBBBLL',
        '..LBBBBBBBBBBBLL',
        '..LLLLLLLLLLLLLL',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid_wood', role: 'head' },
        B: { name: 'wood_grain', role: 'body' },
        G: { name: 'carved_design', role: 'accessory' },
        L: { name: 'box_lower', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. TEA SET ─────────────────────────────────────────────
    {
      id: 'tea_set_16',
      description: 'Teacup and saucer with steam, floral decoration on fine china.',
      grid: [
        '................',
        '......SSS.......',
        '.......S........',
        '....HHHHHHH.....',
        '...HBBBBBBBH....',
        'E..HBBFBBFBBH...',
        'EE.HBBFBBFBBH...',
        'E..HBBBBBBBH....',
        '....HHHHHHHH....',
        '.....HHHHHH.....',
        '..DDDDDDDDDDDDD.',
        '..DCCCCCCCCCCDD.',
        '..DDDDDDDDDDDDD.',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'eye' },
        H: { name: 'cup_rim', role: 'head' },
        B: { name: 'cup_body', role: 'body' },
        F: { name: 'floral_decor', role: 'accessory' },
        E: { name: 'handle', role: 'arm' },
        D: { name: 'saucer_rim', role: 'belt' },
        C: { name: 'saucer_surface', role: 'boot' },
      },
      colors: {
        eye:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 17. WATERING ROSE ───────────────────────────────────────
    {
      id: 'watering_rose_16',
      description: 'Green watering can with a painted rose design and arched handle.',
      grid: [
        '................',
        '.......HH.......',
        '......HHHH......',
        '..RRRHHBBHHRRR..',
        '..RRRHHBBHHRRR..',
        '..RRRHHBBHHRRR..',
        '..RRRHHBBHHRRR..',
        'S..RRBBBBBBRRR..',
        'SS..RBBBBBBRR...',
        'SS..RBBBBBBRR...',
        'S..RRBBBBBBRRR..',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '..NNNNNNNNNNNN..',
        '................',
      ],
      chars: {
        H: { name: 'handle_arch', role: 'head' },
        R: { name: 'can_body', role: 'body' },
        B: { name: 'rose_design', role: 'accessory' },
        S: { name: 'spout', role: 'arm' },
        N: { name: 'nozzle_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 18. BIRDCAGE COZY ───────────────────────────────────────
    {
      id: 'birdcage_cozy_16',
      description: 'Decorative domed bird cage with a small bird perched on a swing.',
      grid: [
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '...WWWBBBBWWW...',
        '...WBBBBBBBBW...',
        '...WBBBPBBBBBW..',
        '...WBBPPPPBBW...',
        '...WBBBBBBBBW...',
        '..WWBBSSSSBBWW..',
        '..WBBBSSSSBBW...',
        '..WWBBBBBBBBWW..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
      ],
      chars: {
        H: { name: 'cage_top_hook', role: 'head' },
        W: { name: 'cage_wires', role: 'body' },
        B: { name: 'cage_interior', role: 'belt' },
        P: { name: 'perch_bird', role: 'eye' },
        S: { name: 'swing_bar', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. POTTED CACTUS ───────────────────────────────────────
    {
      id: 'potted_cactus_16',
      description: 'Small potted cactus with two arms, spine dots, and a flower bloom on top.',
      grid: [
        '................',
        '.......FF.......',
        '......FFFF......',
        '......CCCC......',
        'CC....CCCC....CC',
        'CC....CSCC....CC',
        '.CC...CCCC...CC.',
        '.CC...CSCC...CC.',
        '..CCCCCCCCCCCC..',
        '..CCCCSCCCCCC...',
        '...CCCCCCCC.....',
        '....HHHHHH......',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HHHHHHHH.....',
        '....HHHHHHH.....',
      ],
      chars: {
        F: { name: 'cactus_flower', role: 'eye' },
        C: { name: 'cactus_body', role: 'body' },
        S: { name: 'cactus_spines', role: 'accessory' },
        H: { name: 'pot_rim', role: 'head' },
        B: { name: 'pot_body', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 20. LETTER ENVELOPE ─────────────────────────────────────
    {
      id: 'letter_envelope_16',
      description: 'Sealed letter envelope with a red wax stamp and address lines.',
      grid: [
        '................',
        '..EEEEEEEEEEEE..',
        '..EHHHHHHHHHHE..',
        '..EHHHHHHHHHHHE.',
        '..EHHHHHHHHHHHE.',
        '..EHHHHHHHHHHHE.',
        '..EHHHHHHHHHHHE.',
        '..EHHHHHHHHHHHE.',
        '..EHHHHHHWWHHHE.',
        '..EHHHHHHWWHHHE.',
        '..EHHHHHHHHHHHE.',
        '..ELLLLLLLLLLHE.',
        '..ELLLLLLLLLLHE.',
        '..ELLLLLLLLLLHE.',
        '..EEEEEEEEEEEEE.',
        '................',
      ],
      chars: {
        E: { name: 'envelope_edge', role: 'head' },
        H: { name: 'envelope_face', role: 'body' },
        W: { name: 'wax_stamp', role: 'eye' },
        L: { name: 'address_lines', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
