/**
 * Creatures batch 1 — 20 new creature templates.
 * Distinct RPG monster/animal archetypes at 16x16.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'creatures',
  exportNames: { templates: 'CREATURE_BATCH1_TEMPLATES', schemes: 'CREATURE_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SPIDER QUEEN — large spider with crown markings ─────
    {
      id: 'spider_queen_16',
      description: 'Large spider queen with crown-like head markings, 8 legs, bulbous abdomen.',
      grid: [
        '................',
        '......XXXX......',
        '.....HHHHHH.....',
        '....HEEHHEEH....',
        '....HHHHHHHH....',
        '...LFHHHHHFR....',
        '..L..BBBBBB..R..',
        '.L..BBBBBBBB..R.',
        '....BBBBBBBB....',
        '...LBBBBBBBBR...',
        '..L.BBBBBBBB.R..',
        '.L...BBBBBB...R.',
        '......BBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        X: { name: 'crown', role: 'accessory' },
        B: { name: 'abdomen', role: 'body' },
        F: { name: 'fangs', role: 'face' },
        L: { name: 'legs_left', role: 'leg' },
        R: { name: 'legs_right', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        face:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. MUSHROOM — sentient mushroom creature ───────────────
    {
      id: 'mushroom_creature_16',
      description: 'Sentient mushroom with spotted cap, stubby body, small dot eyes.',
      grid: [
        '................',
        '......HHHH......',
        '....HHXXXXHH....',
        '...HHHHHHHHHH...',
        '...HXHHHHHXHH...',
        '....HHHHHHHH....',
        '.....BBBBBB.....',
        '.....BEEBBB.....',
        '.....BFFBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cap', role: 'head' },
        X: { name: 'spots', role: 'accessory' },
        B: { name: 'stem', role: 'body' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. MIMIC — treasure chest with teeth and tongue ────────
    {
      id: 'mimic_16',
      description: 'Mimic disguised as treasure chest with jagged teeth, eye, and tongue peeking out.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...GGGGGGGGGG...',
        '...XBXBXBXBXB...',
        '...E.........E..',
        '...BXBXBXBXBX...',
        '...BBBBFFBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...GGGGGGGGGG...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid', role: 'head' },
        B: { name: 'body', role: 'body' },
        G: { name: 'trim', role: 'belt' },
        X: { name: 'teeth', role: 'accessory' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'tongue', role: 'face' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#757161', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 4. WISP — floating magic orb with tail ─────────────────
    {
      id: 'wisp_16',
      description: 'Floating magical wisp — glowing orb core with trailing flame tail.',
      grid: [
        '................',
        '................',
        '.......XX.......',
        '......XHHX......',
        '.....XHBBHX.....',
        '....XHBEEBHX....',
        '....XHBBBBHX....',
        '.....XHBBHX.....',
        '......XHHX......',
        '.......AA.......',
        '......AA........',
        '.....AA.........',
        '....A...........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'core', role: 'body' },
        H: { name: 'glow_inner', role: 'head' },
        X: { name: 'glow_outer', role: 'accessory' },
        E: { name: 'eyes', role: 'eye' },
        A: { name: 'tail', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 5. GOLEM — rock/earth elemental ────────────────────────
    {
      id: 'golem_16',
      description: 'Stone golem with blocky body, glowing eye cracks, heavy fists.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '....HHEHHEHH....',
        '....HHHHHHHHH...',
        '.....HHFFHH.....',
        '......BBBB......',
        '....AABBBBAA....',
        '...AAABBBBBAA...',
        '...DD.BBBB.DD...',
        '......BBBB......',
        '......LLLL......',
        '.....LLLLLL.....',
        '....TT....TT....',
        '...TTT....TTT...',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hands', role: 'hand' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        hand:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 6. FAIRY — tiny winged humanoid ────────────────────────
    {
      id: 'fairy_16',
      description: 'Tiny fairy with butterfly wings, glowing aura, cute face.',
      grid: [
        '................',
        '................',
        '.......HH.......',
        '......HEHH......',
        '......HFFH......',
        '..XX..BBBB..XX..',
        '.XXXX.BBBB.XXXX.',
        '.XXXX.ABBA.XXXX.',
        '..XX..BBBB..XX..',
        '......GGGG......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
        X: { name: 'wings', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 7. TREANT — walking tree creature ──────────────────────
    {
      id: 'treant_16',
      description: 'Walking tree creature with leafy crown, gnarled trunk body, root-like feet.',
      grid: [
        '...XXXXXXXXX....',
        '..XXXXXXXXXXXX..',
        '..XXXXXXXXXXXX..',
        '...XXXXXXXXXX...',
        '....XXHHHXX.....',
        '.....HHEEH......',
        '.....HHFFHH.....',
        '....AABBBBAA....',
        '....AABBBBAA....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...TT......TT...',
        '..TT........TT..',
      ],
      chars: {
        X: { name: 'canopy', role: 'accessory' },
        H: { name: 'face_bark', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'trunk', role: 'body' },
        A: { name: 'branches', role: 'arm' },
        L: { name: 'roots_upper', role: 'leg' },
        T: { name: 'roots_lower', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 8. JELLYFISH — transparent bell with tentacles ─────────
    {
      id: 'jellyfish_16',
      description: 'Translucent jellyfish with dome bell, inner glow, flowing tentacles.',
      grid: [
        '................',
        '......HHHH......',
        '....HHHHHHHH....',
        '...HHHHHHHHH....',
        '...HHXBBXHHH....',
        '...HHBBBBHHH....',
        '....HHHHHHHH....',
        '.....AAAAAA.....',
        '....A.A..A.A....',
        '...A..A..A..A...',
        '..L...A..A...L..',
        '..L...L..L...L..',
        '..L...L..L...L..',
        '...L..L..L..L...',
        '....L........L..',
        '................',
      ],
      chars: {
        H: { name: 'bell', role: 'head' },
        B: { name: 'core', role: 'body' },
        X: { name: 'glow', role: 'eye' },
        A: { name: 'tentacles_inner', role: 'arm' },
        L: { name: 'tentacles_outer', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 9. ELEMENTAL_FIRE — living flame creature ──────────────
    {
      id: 'fire_elemental_16',
      description: 'Fire elemental — humanoid shape made of flames, bright core, flickering top.',
      grid: [
        '.......X........',
        '......XXX.......',
        '.....XHHHX......',
        '....XHHHHH......',
        '....XHEEHH......',
        '.....HHFFH......',
        '....AABBBBAA....',
        '...AA.BBBB.AA...',
        '..AA..BBBB..AA..',
        '......BBBB......',
        '.....BBBBBB.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'flame_tips', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'core', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'base_flames', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        face:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 10. ICE ELEMENTAL — frozen creature ────────────────────
    {
      id: 'ice_elemental_16',
      description: 'Ice elemental — crystalline humanoid with jagged icicle crown, frozen body.',
      grid: [
        '...X....X..X....',
        '...XX..XX..X....',
        '....XHHHX.X.....',
        '....HHHHHHH.....',
        '....HEEHHHH.....',
        '.....HHFFH......',
        '....AABBBBAA....',
        '...AA.BBBB.AA...',
        '..AA..BBBB..AA..',
        '......BBBB......',
        '.....GGGGGG.....',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...TT......TT...',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'icicles', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'waist', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        face:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#6dc2ca' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        boot:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#597dce' },
      },
    },

    // ─── 11. BEETLE — armored insect ────────────────────────────
    {
      id: 'beetle_16',
      description: 'Giant armored beetle with hard shell, mandibles, 6 legs.',
      grid: [
        '................',
        '................',
        '......FFFF......',
        '.....FHHHFF.....',
        '....EHHHHHE.....',
        '...LHHHHHHHL....',
        '..L.BBBBBB.L....',
        '.L..BBXXBB..L...',
        '..L.BBXXBB.L....',
        '...LBBBBBBBL....',
        '..L.BBBBBB.L....',
        '.L..BBBBBB..L...',
        '....BBBBBB......',
        '.....BBBB.......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mandibles', role: 'face' },
        B: { name: 'shell', role: 'body' },
        X: { name: 'wing_seam', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 12. PHOENIX — mythical fire bird ───────────────────────
    {
      id: 'phoenix_16',
      description: 'Phoenix in flight — fiery plumage, spread wings, trailing tail feathers.',
      grid: [
        '....HH..........',
        '...HHEH.........',
        '...HHHHX........',
        '....HBBX........',
        '..AABBBBXXXX....',
        '.AAABBBBBBXXXX..',
        'AAAABBBBBBBBXX..',
        '.AAABBBBBBBX....',
        '..AABBBBBBX.....',
        '....BBBLLX......',
        '....LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '..LLLLLLLLL.....',
        '...LLLLLLL......',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'wing_left', role: 'arm' },
        X: { name: 'wing_right', role: 'accessory' },
        L: { name: 'tail_plume', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 13. FROG — small amphibian ─────────────────────────────
    {
      id: 'frog_16',
      description: 'Sitting frog — round body, big eyes on top, splayed front legs.',
      grid: [
        '................',
        '................',
        '................',
        '....EE..EE......',
        '...EHHEEHH......',
        '...HHHHHHHH.....',
        '..HHHHFFHHHH....',
        '..HHHHHHHHH.....',
        '..AABBBBBBAA....',
        '.AA.BBBBBB.AA...',
        '.DD.BBBBBB.DD...',
        '....BBBBBB......',
        '...LLBBBBLL.....',
        '..LL.TTTT.LL....',
        '..TT......TT....',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'front_legs', role: 'arm' },
        D: { name: 'front_feet', role: 'hand' },
        L: { name: 'back_legs', role: 'leg' },
        T: { name: 'back_feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 14. SNAKE — coiled serpent ─────────────────────────────
    {
      id: 'snake_16',
      description: 'Coiled snake with raised head, forked tongue, patterned scales.',
      grid: [
        '................',
        '................',
        '.......HHH......',
        '......HHEEH.....',
        '......HHFFH.....',
        '.......BBB......',
        '......BBBBB.....',
        '.....BXBXBB.....',
        '....BBBBBBB.....',
        '...BBBXBXBB.....',
        '..BBBBBBBBB.....',
        '..BBXBXBBBB.....',
        '...BBBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'tongue', role: 'face' },
        B: { name: 'body_coil', role: 'body' },
        X: { name: 'pattern', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. CRAB — armored sea creature ────────────────────────
    {
      id: 'crab_16',
      description: 'Crab facing front — wide shell, raised claws, 6 legs, beady eyes.',
      grid: [
        '................',
        '................',
        '..XX........XX..',
        '..XXX......XXX..',
        '..XXXE....EXXX..',
        '...XHHHHHHHX....',
        '...HHHHHHHHH....',
        '..HHHHFFHHHH....',
        '..HHHHHHHHHH....',
        '..BBBBBBBBBB....',
        '.LBBBBBBBBBBR...',
        'L.BBBBBBBBBB.R..',
        '..LLBBBBBBRL....',
        '..L..TTTT..R....',
        '.....TT.TT......',
        '................',
      ],
      chars: {
        H: { name: 'shell', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'body', role: 'body' },
        X: { name: 'claws', role: 'accessory' },
        L: { name: 'legs_left', role: 'arm' },
        R: { name: 'legs_right', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 16. SCORPION — desert arachnid ─────────────────────────
    {
      id: 'scorpion_16',
      description: 'Scorpion side-view — arched tail with stinger, large claws, 8 legs.',
      grid: [
        '..............X.',
        '.............XX.',
        '............XX..',
        '...........XX...',
        '..........XX....',
        '..XX.....XX.....',
        '.XXXX...HHHH....',
        '.XXXX..EHHHHH...',
        '........BBBBBB..',
        '.......BBBBBBB..',
        '......LLBBBBLL..',
        '.....LL.BBBB.LL.',
        '....L...LLLL..L.',
        '........L..L....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        B: { name: 'body', role: 'body' },
        X: { name: 'tail_stinger', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 17. OWL — nocturnal bird ───────────────────────────────
    {
      id: 'owl_16',
      description: 'Perching owl — round head with horn tufts, big eyes, folded wings, branch feet.',
      grid: [
        '................',
        '....X....X......',
        '...XHHHHHX......',
        '...HHHHHHHH.....',
        '..HHEEHHEEHHH...',
        '..HHHHHHHHHH....',
        '...HHHHFHHH.....',
        '...AABBBBAA.....',
        '..AAABBBBAAA....',
        '..AAABBBBAAA....',
        '...AABBBBAA.....',
        '....ABBBBA......',
        '....BBBBBB......',
        '....TTTTTT......',
        '...TT.TT.TT.....',
        '................',
      ],
      chars: {
        X: { name: 'ear_tufts', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'beak', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'wings', role: 'arm' },
        T: { name: 'talons', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 18. WOLF_PUP — small cute wolf ─────────────────────────
    {
      id: 'wolf_pup_16',
      description: 'Small wolf pup sitting — fluffy, pointed ears, big eyes, bushy tail.',
      grid: [
        '................',
        '................',
        '....XX..XX......',
        '...XHHHHHHX.....',
        '...HHEEHHEH.....',
        '...HHHFFHHH.....',
        '....HHHHHH......',
        '....BBBBBB..X...',
        '...AABBBBAAXX...',
        '...AABBBBAAXX...',
        '....BBBBBB.X....',
        '....BBBBBB......',
        '...LLLLLLLL.....',
        '...TT....TT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'ears_tail', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'snout', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'front_legs', role: 'arm' },
        L: { name: 'back_legs', role: 'leg' },
        T: { name: 'paws', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. TURTLE — shelled reptile ───────────────────────────
    {
      id: 'turtle_16',
      description: 'Turtle side-view — domed shell with pattern, small head poking out, stubby legs.',
      grid: [
        '................',
        '................',
        '................',
        '..HH............',
        '.HEHH...........',
        '.HFFHXXXXXXX....',
        '..HHXXXXXXXXXXX.',
        '...XXXXXXXXXXXXX',
        '...XXBXBXBXBXXX.',
        '...XXXXXXXXXXXXX',
        '...XXBXBXBXBXX..',
        '....XXXXXXXXX...',
        '....LLXXXX.LL...',
        '...TT......TT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'face', role: 'face' },
        X: { name: 'shell', role: 'body' },
        B: { name: 'shell_pattern', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 20. CRYSTAL GOLEM — magical crystal creature ───────────
    {
      id: 'crystal_golem_16',
      description: 'Crystal golem — angular faceted body, glowing core, prismatic shoulders.',
      grid: [
        '................',
        '......XHHX......',
        '.....XHHHHX.....',
        '....XHHEEHX.....',
        '....XHHHHHHX....',
        '.....HHFFHH.....',
        '...XXBBBBBBXX...',
        '..XX.BBBBBB.XX..',
        '..X..BBXXBB..X..',
        '.....BBBBBB.....',
        '.....GGGGGG.....',
        '....LLLLLLLL....',
        '...LL......LL...',
        '..TT........TT..',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crystals', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'torso', role: 'body' },
        G: { name: 'waist', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        face:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#30346d' },
        leg:       { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#30346d' },
      },
    },

  ],
};

export default batch;
