/**
 * Dungeon batch 2 — 14 dungeon props, traps, and atmospheric elements.
 * Dark moody palette: deep purples, stone grays, warm fire/magic accents.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'dungeon',
  exportNames: { templates: 'DUNGEON_BATCH2_TEMPLATES', schemes: 'DUNGEON_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ── 1. iron_door_16 ─────────────────────────────────────────────
    {
      id: 'iron_door_16',
      description: 'Heavy iron dungeon door with bolts and a reinforcing band.',
      grid: [
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..FBBBBBBBBBBF..',
        '..FBBEBBBBEBbF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FBEEEEEEEEbF..',
        '..FBEEEEEEEEbF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FBBEBBBBEBbF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '................',
      ],
      chars: {
        F: { name: 'frame',       role: 'body' },
        B: { name: 'door',        role: 'head' },
        E: { name: 'bolts',       role: 'eye'  },
        b: { name: 'bolt_shadow', role: 'belt' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#30346d', base: '#4e4a4e', highlight: '#8595a1' },
        eye:  { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#442434', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ── 2. portcullis_16 ────────────────────────────────────────────
    {
      id: 'portcullis_16',
      description: 'Raised iron portcullis gate with spiked bottom bars.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBF.F.F.F.F.FBBB',
        'BBF.F.F.F.F.FBBB',
        'BBHHHHHHHHHHHBBB',
        'BBF.F.F.F.F.FBBB',
        'BBF.F.F.F.F.FBBB',
        'BBHHHHHHHHHHHBBB',
        'BBF.F.F.F.F.FBBB',
        'BBF.F.F.F.F.FBBB',
        'BBHHHHHHHHHHHBBB',
        'BBF.F.F.F.F.FBBB',
        'BBF.F.F.F.F.FBBB',
        'BBEFEFEFEFEFEFBB',
        'BB.E.E.E.E.E.EBB',
        '................',
      ],
      chars: {
        B: { name: 'wall',     role: 'body' },
        F: { name: 'bars',     role: 'head' },
        H: { name: 'crossbar', role: 'belt' },
        E: { name: 'spikes',   role: 'eye'  },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
        belt: { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#442434', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ── 3. dungeon_lever_16 ──────────────────────────────────────────
    {
      id: 'dungeon_lever_16',
      description: 'Wall-mounted stone lever switch in up/ready position.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBHBBBBBBB.',
        'BBBBBBHHHbbbbbb.',
        'BBBBBHHHHbbbbb..',
        'BBBBHHHHHbbbb...',
        'BBBHHHHHBBBBBB..',
        'BBBBBBEEBBBBBB..',
        'BBBBBEEEBBBBB...',
        'BBBBEEEEBBBBB...',
        'BBBBBBBBBBBBBB..',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        '................',
      ],
      chars: {
        B: { name: 'wall',    role: 'body' },
        H: { name: 'handle',  role: 'head' },
        E: { name: 'bracket', role: 'eye'  },
        b: { name: 'shadow',  role: 'belt' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:  { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#442434', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ── 4. gargoyle_statue_16 ────────────────────────────────────────
    {
      id: 'gargoyle_statue_16',
      description: 'Stone gargoyle wall decoration with horns, wings and carved eyes.',
      grid: [
        '....H......H....',
        '...HHH....HHH...',
        '...HHHBBBBHHH...',
        '...HBBBBBBBHH...',
        '...HBBEBBEBBH...',
        '....BBBBBBBBB...',
        '..WBBBBBBBBWWW..',
        '..WWBBBBBBBWWW..',
        '.WWWWBBBBBWWWW..',
        '..WWWWBBBWWWW...',
        '....WWWBWWWWW...',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '....BBBBBBBBB...',
        '....BBBBBBBBB...',
        '................',
      ],
      chars: {
        B: { name: 'body',  role: 'body'      },
        H: { name: 'horns', role: 'head'      },
        E: { name: 'eyes',  role: 'eye'       },
        W: { name: 'wings', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#30346d' },
        accessory: { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
      },
    },

    // ── 5. sarcophagus_16 ────────────────────────────────────────────
    {
      id: 'sarcophagus_16',
      description: 'Ancient stone sarcophagus coffin lid with carved face and chest symbol.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBHHHBBBBB..',
        '...BBHHHHHBBBB..',
        '...BBHEEHBBBB...',
        '...BBBHHBBBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBSSSSBBBB..',
        '...BBSSSSSSBB...',
        '...BBBSSSSBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'stone_lid',    role: 'body'      },
        H: { name: 'carved_face',  role: 'head'      },
        E: { name: 'eye_sockets',  role: 'eye'       },
        S: { name: 'chest_symbol', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#30346d' },
        accessory: { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // ── 6. dungeon_well_16 ────────────────────────────────────────────
    {
      id: 'dungeon_well_16',
      description: 'Dark stone well sunk into dungeon floor with rope winch.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBWWWWWWWWBB..',
        '..BBWWWWWWWWBB..',
        '..BBBBBBBBBBBB..',
        '..BBBDDDDDDBBBB.',
        '..BBBDDDDDDBBB..',
        '..BBBDDDDDDBBB..',
        '..BBBDDDDDDBBB..',
        '..BBBDDDDDDBBBB.',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...EEEEEEEEEE...',
        '...EEEEEEEEEE...',
        '................',
      ],
      chars: {
        B: { name: 'stone_rim',  role: 'body' },
        W: { name: 'rope_winch', role: 'head' },
        D: { name: 'dark_shaft', role: 'eye'  },
        E: { name: 'floor',      role: 'belt' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
        belt: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ── 7. poison_trap_16 ────────────────────────────────────────────
    {
      id: 'poison_trap_16',
      description: 'Wall-mounted poison dart trap with housing, nozzle and green drips.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBEEEEEEEEEBBB.',
        'BBBEHHHHHHHHEBB.',
        'BBBEHHHHHHHPEBB.',
        'BBBEHHHHHHHPEBB.',
        'BBBEHHHHHHHHEBB.',
        'BBBEEEEEEEEEBBB.',
        'BBBBBBBBBBBgBBB.',
        'BBBBBBBBBBgBBBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        '................',
      ],
      chars: {
        B: { name: 'wall',    role: 'body'      },
        E: { name: 'housing', role: 'head'      },
        H: { name: 'chamber', role: 'belt'      },
        P: { name: 'nozzle',  role: 'accessory' },
        g: { name: 'poison',  role: 'eye'       },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#4e4a4e' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
      },
    },

    // ── 8. falling_rocks_16 ──────────────────────────────────────────
    {
      id: 'falling_rocks_16',
      description: 'Ceiling trap with falling rocks mid-air hazard.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BB..BBBB..BBBBBB',
        'B..BBBB..BBBBBBB',
        '...RRR...RRR....',
        '..RRRR..RRRR....',
        '....RR....RR....',
        '....RRR..RRR....',
        '......RR.RR.....',
        '.......RRR......',
        '.......RR.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'ceiling', role: 'body' },
        R: { name: 'rock',    role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 9. dungeon_brazier_16 ────────────────────────────────────────
    {
      id: 'dungeon_brazier_16',
      description: 'Standing iron brazier on a pole with roaring fire.',
      grid: [
        '................',
        '.......AA.......',
        '......AAAA......',
        '.....AAEEAA.....',
        '....AAEEEEAA....',
        '....AAEEEEAA....',
        '.....AAAAAA.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '....SSSSSSSS....',
        '................',
      ],
      chars: {
        A: { name: 'flame_outer', role: 'accessory' },
        E: { name: 'flame_core',  role: 'eye'       },
        B: { name: 'bowl',        role: 'body'      },
        H: { name: 'pole',        role: 'head'      },
        S: { name: 'base',        role: 'belt'      },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 10. iron_maiden_16 ──────────────────────────────────────────
    {
      id: 'iron_maiden_16',
      description: 'Closed iron maiden torture device with riveted door and spike-hole details.',
      grid: [
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '..FFFBBBBBBFFF..',
        '..FFBBBBBBBBBF..',
        '..FFBBEBBEBBFF..',
        '..FFBBBBBBBBBF..',
        '..FFFBBBBBBFFF..',
        '..FFBBBBBBBBBF..',
        '..FFBBEBBEBBFF..',
        '..FFBBBBBBBBBF..',
        '..FFFBBBBBBFFF..',
        '..FFFBBBBBFFFF..',
        '...FFBBBBBBBFF..',
        '...FFFFFFFFFFFF.',
        '....FFFFFFFFFF..',
        '................',
      ],
      chars: {
        F: { name: 'frame',       role: 'body' },
        B: { name: 'door',        role: 'head' },
        E: { name: 'spike_holes', role: 'eye'  },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#30346d', base: '#4e4a4e', highlight: '#8595a1' },
        eye:  { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ── 11. dungeon_bookshelf_16 ─────────────────────────────────────
    // Shelf boards B; red tomes R; blue scrolls S; cobweb W
    // Each inner row: '..' + B + [12 content chars] + '..' = 16 ✓
    {
      id: 'dungeon_bookshelf_16',
      description: 'Old dusty bookshelf with tomes, scrolls and a cobweb.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BRRRSSSRRRBB..',
        '..BRRRSSSRWWBB..',
        '..BBBBBBBBWWBB..',
        '..BBBBBBBBBBBB..',
        '..BSSRRRRRRRSB..',
        '..BSSSRRRRRRBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BRRBBSSRRBBB..',
        '..BRRBBSSRRBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shelf_wood', role: 'body'      },
        R: { name: 'book_red',   role: 'head'      },
        S: { name: 'book_blue',  role: 'belt'      },
        W: { name: 'cobweb',     role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ── 12. alchemy_table_16 ─────────────────────────────────────────
    // Wood table T; potions P (red); flask F (blue); burner flame A; brace B
    {
      id: 'alchemy_table_16',
      description: 'Alchemy crafting table with potions, flask and burner flame.',
      grid: [
        '................',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '...TPPTFTPPTT...',
        '...TPPFFFTPTT...',
        '...TPPAAAAATT...',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TT......TT...',
        '...TTBBBBBBTT...',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'table',  role: 'body'      },
        P: { name: 'potion', role: 'head'      },
        F: { name: 'flask',  role: 'belt'      },
        A: { name: 'flame',  role: 'accessory' },
        B: { name: 'brace',  role: 'eye'       },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ── 13. skeleton_cage_16 ─────────────────────────────────────────
    // Chain C above; iron cage bars B; skeleton bones S inside
    {
      id: 'skeleton_cage_16',
      description: 'Hanging iron cage with a skeleton inside, chain above.',
      grid: [
        '......CCCC......',
        '......CCCC......',
        '.......CC.......',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....B.SSSSS.B...',
        '....B.SSSSS.B...',
        '....B.SBSBS.B...',
        '....BSSSBSSBB...',
        '....B.SSSSS.B...',
        '....B..SSS..B...',
        '....B..S.S..B...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'chain',    role: 'accessory' },
        B: { name: 'cage_bar', role: 'body'      },
        S: { name: 'skeleton', role: 'head'      },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ── 14. secret_door_16 ──────────────────────────────────────────
    // Solid wall B; thin revealed door edge D; glowing light crack L
    {
      id: 'secret_door_16',
      description: 'Secret door partially revealed in dungeon wall with faint glowing crack.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBB.',
        'BBBBBBBBBBBBBLL.',
        'BBBBBBBBBBBBLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBDLL..',
        'BBBBBBBBBBBBLL..',
        'BBBBBBBBBBBBBLL.',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall',        role: 'body' },
        D: { name: 'door_edge',   role: 'head' },
        L: { name: 'light_crack', role: 'eye'  },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
