/**
 * Dungeon batch 1 — 14 dungeon tiles, traps, and interactive props.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'dungeon',
  exportNames: { templates: 'DUNGEON_BATCH1_TEMPLATES', schemes: 'DUNGEON_BATCH1_COLOR_SCHEMES' },
  templates: [

    {
      id: 'dungeon_gate_16',
      description: 'Iron dungeon gate / portcullis.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHBHHBHHBHHB..',
        '..HHHHHHHHHHBB..',
        '..EEEEEEEEEEEE..',
        '..EEEEEEEEEEEE..',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        H: { name: 'bars', role: 'head' },
        E: { name: 'floor', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'spike_trap_16',
      description: 'Floor spike trap tile (triggered state).',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BB..HH..HHBB..',
        '..BB.HHHH.HBBB..',
        '..BBHHHHHHHBBB..',
        '..BBHHHHHHHBBB..',
        '..BBHHHHHHHBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'floor', role: 'body' },
        H: { name: 'spikes', role: 'head' },
        E: { name: 'mechanism', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'wall_torch_16',
      description: 'Wall-mounted burning torch / sconce.',
      grid: [
        '................',
        '.......AA.......',
        '......AAAA......',
        '.....AAEEA......',
        '......AAAA......',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'flame', role: 'accessory' },
        E: { name: 'flame_core', role: 'eye' },
        H: { name: 'handle', role: 'head' },
        B: { name: 'bracket', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'treasure_chest_closed_16',
      description: 'Locked treasure chest (closed).',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHHB..',
        '..BHHHHHHHHHHB..',
        '..BHHHHHHHHHHB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBEBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bands', role: 'body' },
        H: { name: 'lid', role: 'head' },
        E: { name: 'base', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'dungeon_pillar_broken_16',
      description: 'Crumbled dungeon pillar / column ruins.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '....BBBB........',
        '...BBBBB........',
        '...BBBBB.HH.....',
        '....BBBB.HH.....',
        '....BBBBHHHH....',
        '....BBBBBBB.....',
        '....BBBBBBB.....',
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pillar', role: 'body' },
        H: { name: 'rubble', role: 'head' },
        E: { name: 'base', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'dungeon_chain_16',
      description: 'Wall chains / shackles decorative element.',
      grid: [
        '...BBB....BBB...',
        '...BBB....BBB...',
        '...HHH....HHH...',
        '...HHH....HHH...',
        '....HH.....HH...',
        '...HHH....HHH...',
        '...HHH....HHH...',
        '....HH.....HH...',
        '...HHH....HHH...',
        '...HHH....HHH...',
        '...EEEE..EEEE...',
        '...EEEE..EEEE...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'hooks', role: 'body' },
        H: { name: 'chains', role: 'head' },
        E: { name: 'shackles', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'wall_crack_16',
      description: 'Cracked dungeon wall with hidden passage hint.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBHBBBBBBBBBB',
        'BBBBHHBBBBBBBBBB',
        'BBBHHHBBBBBHBBBB',
        'BBBBHHBBBBHHBBBB',
        'BBBBBHBBHHHBBBBB',
        'BBBBBBHHHBBBBBBB',
        'BBBBBHHHBBBBBBBB',
        'BBBBHHBBBBBBBBBB',
        'BBBHHBBBBBBBBBBB',
        'BBBHBBBBBBHBBBBB',
        'BBBBBBBBBBHHBBBB',
        'BBBBBBBBBHHHBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        H: { name: 'cracks', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'bone_pile_16',
      description: 'Pile of bones on dungeon floor.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '........HH......',
        '...HH..HHH......',
        '..HHHHHHHHH.....',
        '..BBBBBBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...EEEEEEEEE....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'skulls', role: 'head' },
        B: { name: 'bones', role: 'body' },
        E: { name: 'floor', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#595652', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'arrow_trap_16',
      description: 'Wall-mounted arrow trap with slot.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBEEEEEEEEBB..',
        'BBBHHHHHHHHHBB..',
        'BBBHHHHHHHHHBB..',
        'BBBBEEEEEEEEBB..',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        H: { name: 'arrows', role: 'head' },
        E: { name: 'slot', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#442434' },
      },
    },

    {
      id: 'pressure_plate_16',
      description: 'Floor pressure plate trigger tile.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..EEEEEEEEEEEE..',
        '..EEEEEEEEEEEE..',
        '..EEBBBBBBBBBE..',
        '..EEBBBBBBBBBE..',
        '..EEEEEEEEEEEE..',
        '..EEEEEEEEEEEE..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'floor', role: 'eye' },
        B: { name: 'plate', role: 'body' },
      },
      colors: {
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        body:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'dungeon_arch_16',
      description: 'Stone archway / doorframe in dungeon.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..BBB......BBB..',
        '..EEEEEEEEEEEE..',
        '..EEEEEEEEEEEE..',
        '................',
      ],
      chars: {
        B: { name: 'stone', role: 'body' },
        E: { name: 'floor', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'cobweb_corner_16',
      description: 'Dusty cobweb in dungeon corner.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BHHHHHH.........',
        'BHHHHH..........',
        'BHHHH...........',
        'BHHH............',
        'BHH.............',
        'BH..............',
        'B...............',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        H: { name: 'web', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'magic_rune_floor_16',
      description: 'Glowing magic rune circle on floor.',
      grid: [
        '................',
        '................',
        '....EEEEEEEE....',
        '...EE......EE...',
        '..EE.HHHHHH.EE..',
        '..E.HHHHHHHH.E..',
        '..E.HH....HH.E..',
        '..E.HH....HH.E..',
        '..E.HH....HH.E..',
        '..E.HHHHHHHH.E..',
        '..EE.HHHHHH.EE..',
        '...EE......EE...',
        '....EEEEEEEE....',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'outer_ring', role: 'eye' },
        H: { name: 'rune', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'lava_pool_16',
      description: 'Bubbling lava pool hazard tile.',
      grid: [
        '................',
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBHHBBHBBBB...',
        '..BBBBBBBBBBB...',
        '.BBBBBBBHBBBBB..',
        '.BBBHBBBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '..BBBBHBBBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'lava', role: 'body' },
        H: { name: 'bubbles', role: 'head' },
      },
      colors: {
        body:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
