/**
 * Dungeon Tiles batch 5 — 20 paths & decorative wall tiles (seamless/tileable).
 * Row 0 matches row 15, col 0 matches col 15 for seamless tiling.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'dungeon_tiles',
  exportNames: { templates: 'DUNGEON_TILES_BATCH5_TEMPLATES', schemes: 'DUNGEON_TILES_BATCH5_COLOR_SCHEMES' },
  templates: [

    // 1. stone_path_tile_16
    {
      id: 'stone_path_tile_16',
      description: 'Tileable stone pathway through dirt ground.',
      grid: [
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
        'DDDPPPPPPPPDDDD.',
      ],
      chars: {
        D: { name: 'dirt', role: 'body' },
        P: { name: 'stone_path', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // 2. bridge_plank_tile_16
    {
      id: 'bridge_plank_tile_16',
      description: 'Tileable wooden bridge plank surface.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'SSSSSSSSSSSSSSSS',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'SSSSSSSSSSSSSSSS',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'SSSSSSSSSSSSSSSS',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'SSSSSSSSSSSSSSSS',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'plank', role: 'body' },
        S: { name: 'gap', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
      },
    },

    // 3. stair_step_tile_16
    {
      id: 'stair_step_tile_16',
      description: 'Tileable stair steps going downward.',
      grid: [
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'step', role: 'body' },
        H: { name: 'edge', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // 4. ornate_tile_16
    {
      id: 'ornate_tile_16',
      description: 'Tileable ornate decorative floor with corner flourishes.',
      grid: [
        'GBBBBBBBBBBBBBBG',
        'BGBBBBBBBBBBBBGB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BGBBBBBBBBBBBBGB',
        'GBBBBBBBBBBBBBBG',
      ],
      chars: {
        B: { name: 'marble', role: 'body' },
        G: { name: 'gold', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // 5. drain_tile_16
    {
      id: 'drain_tile_16',
      description: 'Tileable floor with central drain and water flow lines.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBDDDDDBBBBB.',
        'BBBBBDWWWDBBBBBB',
        'BBBBBDWWWDBBBBBB',
        'BBBBBDWWWDBBBBBB',
        'BBBBBDDDDDBBBBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'floor', role: 'body' },
        D: { name: 'drain_rim', role: 'head' },
        W: { name: 'water', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // 6. arrow_slit_wall_16
    {
      id: 'arrow_slit_wall_16',
      description: 'Tileable castle wall with narrow arrow slit.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBSSSSBBBBBB',
        'BBBBBBSSSSBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBSSBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        S: { name: 'slit', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:  { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // 7. window_wall_tile_16
    {
      id: 'window_wall_tile_16',
      description: 'Tileable wall with small barred window.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBHHHHHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHGBGHBBBBB.',
        'BBBBBHHHHHBBBBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        H: { name: 'frame', role: 'head' },
        G: { name: 'glass', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // 8. pillar_base_tile_16
    {
      id: 'pillar_base_tile_16',
      description: 'Tileable floor with embedded pillar base.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBPPPPPPPPBBBB',
        'BBBBPPPPPPPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPCCCCPPBBBB',
        'BBBBPPPPPPPPBBBB',
        'BBBBPPPPPPPPBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'floor', role: 'body' },
        P: { name: 'base_rim', role: 'head' },
        C: { name: 'pillar', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // 9. torch_bracket_wall_16
    {
      id: 'torch_bracket_wall_16',
      description: 'Tileable wall with mounted torch bracket and flame.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBFFBBBBBBB',
        'BBBBBBFFFFBBBBBB',
        'BBBBBBFAAFBBBBBB',
        'BBBBBBBFFBBBBBBB',
        'BBBBBBBHHBBBBBBB',
        'BBBBBBBHHBBBBBBB',
        'BBBBBBBHHBBBBBBB',
        'BBBBBBMHHMBBBBB.',
        'BBBBBMMBBMMBBBBB',
        'BBBBBBMMMMBBBBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        F: { name: 'flame', role: 'accessory' },
        A: { name: 'flame_core', role: 'eye' },
        H: { name: 'handle', role: 'head' },
        M: { name: 'bracket', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
      },
    },

    // 10. vine_wall_tile_16
    {
      id: 'vine_wall_tile_16',
      description: 'Tileable wall with creeping vines and small leaves.',
      grid: [
        'BBVBBBBBBBBBBVBB',
        'BBBVBBBBBBBVBBBB',
        'BBBBVLBBBBVBBBBB',
        'BBBBBVBBBLVBBBBB',
        'BBBBBBVVVBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BVBBBBBBBBBBBVBB',
        'BBVBBBBBBBBVBBBB',
        'BBBVBBBBBLVBBBBB',
        'BBBBVLBBBVBBBBBB',
        'BBBBBVBBVBBBBBBB',
        'BBBBBBVVBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        V: { name: 'vine', role: 'accessory' },
        L: { name: 'leaf', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#346524', base: '#346524', highlight: '#346524' },
        eye:       { shadow: '#346524', base: '#6dc2ca', highlight: '#dad45e' },
      },
    },

    // 11. rail_track_tile_16
    {
      id: 'rail_track_tile_16',
      description: 'Tileable mine rail track on dirt floor.',
      grid: [
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'TTTRRTTTTRRTTTT.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'TTTRRTTTTRRTTTT.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'TTTRRTTTTRRTTTT.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'DDDRRDDDDRRDDDD.',
        'TTTRRTTTTRRTTTT.',
      ],
      chars: {
        D: { name: 'dirt', role: 'body' },
        R: { name: 'rail', role: 'head' },
        T: { name: 'tie', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // 12. sewer_grate_tile_16
    {
      id: 'sewer_grate_tile_16',
      description: 'Tileable sewer floor with large grate covering.',
      grid: [
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
        'GGEGGEGGEGGEGGE.',
        'GGGGGGGGGGGGGGGG',
      ],
      chars: {
        G: { name: 'grate', role: 'body' },
        E: { name: 'gap', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:  { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // 13. cobble_path_tile_16
    {
      id: 'cobble_path_tile_16',
      description: 'Tileable cobblestone path with grass border.',
      grid: [
        'GGPPPPPPPPPPPPGG',
        'GGPPPPPPPPPPPPGG',
        'GGPPSPPPSPPPPPGG',
        'GGPPPPPPPPSPPPGG',
        'GGPPPPPPPPPPPPGG',
        'GGPPSPPPPPPPPGGG',
        'GGPPPPPPPPSPPPGG',
        'GGPPPPSPPPPPPPGG',
        'GGPPPPPPPPPPPPGG',
        'GGPPPPPPSPPPPPGG',
        'GGPPSPPPPPPPPGGG',
        'GGPPPPPPPPSPPPGG',
        'GGPPPPPPPPPPPPGG',
        'GGPPSPPPSPPPPPGG',
        'GGPPPPPPPPPPPPGG',
        'GGPPPPPPPPSPPPGG',
      ],
      chars: {
        G: { name: 'grass', role: 'accessory' },
        P: { name: 'cobble', role: 'body' },
        S: { name: 'grout', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#346524', highlight: '#346524' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // 14. chain_wall_tile_16
    {
      id: 'chain_wall_tile_16',
      description: 'Tileable wall with hanging chain pattern.',
      grid: [
        'BBBBBBCCBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
        'BBBBBCCBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        C: { name: 'chain', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // 15. banner_wall_tile_16
    {
      id: 'banner_wall_tile_16',
      description: 'Tileable wall with hanging cloth banner.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBRRRRRRRRBBBB',
        'BBBBRRRRRRRRBBB.',
        'BBBBRRREERRRBBBB',
        'BBBBRRREERRRBBBB',
        'BBBBRRRRRRRRBBBB',
        'BBBBRRRRRRRRBBB.',
        'BBBBRRRRRRRRBBB.',
        'BBBBRRRRRRRRBBBB',
        'BBBBRRRRRRRRBBB.',
        'BBBBRRRRRRRRBBB.',
        'BBBBBRRRRRRBBBB.',
        'BBBBBBRRRRBBBBBB',
        'BBBBBBBRRBBBBBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        R: { name: 'banner', role: 'accessory' },
        E: { name: 'emblem', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // 16. bookshelf_wall_tile_16
    {
      id: 'bookshelf_wall_tile_16',
      description: 'Tileable wall filled with book shelves.',
      grid: [
        'SSSSSSSSSSSSSSSS',
        'BRRBBRRBBRRBBRRB',
        'BRRBBRRBBRRBBRRB',
        'SSSSSSSSSSSSSSSS',
        'BRRBBRRBBRRBBRRB',
        'BRRBBRRBBRRBBRRB',
        'SSSSSSSSSSSSSSSS',
        'BRRBBRRBBRRBBRRB',
        'BRRBBRRBBRRBBRRB',
        'SSSSSSSSSSSSSSSS',
        'BRRBBRRBBRRBBRRB',
        'BRRBBRRBBRRBBRRB',
        'SSSSSSSSSSSSSSSS',
        'BRRBBRRBBRRBBRRB',
        'BRRBBRRBBRRBBRRB',
        'SSSSSSSSSSSSSSSS',
      ],
      chars: {
        S: { name: 'shelf', role: 'head' },
        B: { name: 'book_blue', role: 'body' },
        R: { name: 'book_red', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
      },
    },

    // 17. pipe_wall_tile_16
    {
      id: 'pipe_wall_tile_16',
      description: 'Tileable industrial wall with steam pipes.',
      grid: [
        'BBBBPPBBBBBBBBBB',
        'BBBBPPBBBBBBBBBB',
        'BBBBPPBBBBBBBBBB',
        'BBBBPPBBBBBBBBBB',
        'BBBBPPPPPPPPPPPP',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'PPPPPPPPPPPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
        'BBBBBBBBBBPPBBBB',
      ],
      chars: {
        B: { name: 'wall', role: 'body' },
        P: { name: 'pipe', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // 18. crystal_wall_tile_16
    {
      id: 'crystal_wall_tile_16',
      description: 'Tileable cave wall with crystal cluster growth.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBBBCBBBBBBBB.',
        'BBBBBCCBBBBBBBBB',
        'BBBBBCCCBBBBBBBB',
        'BBBBBBCCBBBBBBBB',
        'BBBBBBBCBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBCBBBB',
        'BBBBBBBBBBCCBBBB',
        'BBBBBBBBBCCCBBBB',
        'BBBBBBBBBBCCBBBB',
        'BBBBBBBBBBBCBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBCBBBBBBBBBBBBB',
        'BCCBBBBBBBBBBBBB',
        'BCCCBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'stone', role: 'body' },
        C: { name: 'crystal', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:  { shadow: '#442434', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // 19. waterfall_wall_tile_16
    {
      id: 'waterfall_wall_tile_16',
      description: 'Tileable wall with waterfall cascade effect.',
      grid: [
        'BBBBWWWWWWWWBBBB',
        'BBBBWWWWWWWWBBBB',
        'BBBWWWHHWWWWBBBB',
        'BBBWWWWWWWWWBBBB',
        'BBBBWWWWWWHWBBBB',
        'BBBBWWWWWWWWBBBB',
        'BBBWWWHWWWWWBBBB',
        'BBBWWWWWWWWWBBBB',
        'BBBBWWWWWWWWBBBB',
        'BBBBWWWWWWHWBBBB',
        'BBBWWWWWWWWWBBBB',
        'BBBWWWHWWWWWBBBB',
        'BBBBWWWWWWWWBBBB',
        'BBBBWWWWWWWWBBBB',
        'BBBWWWWWWHWWBBBB',
        'BBBWWWWWWWWWBBBB',
      ],
      chars: {
        B: { name: 'stone', role: 'body' },
        W: { name: 'water', role: 'accessory' },
        H: { name: 'highlight', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // 20. rune_wall_tile_16
    {
      id: 'rune_wall_tile_16',
      description: 'Tileable wall with glowing rune inscription.',
      grid: [
        'BBBBBBBBBBBBBBBB',
        'BBBBRRBBBBBRRBB.',
        'BBBRBBRBBBRBBBB.',
        'BBBRBBRBBBRBBBB.',
        'BBBBRRBBBBBRRBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBRRBBBBBBRRBB.',
        'BBRBBBBBRBBBBBB.',
        'BBRBBBBBRBBBBBB.',
        'BBBRRBBBBBBRRBB.',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
      ],
      chars: {
        B: { name: 'stone', role: 'body' },
        R: { name: 'rune', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
