/**
 * Editor Icons 32x32 — Batch 1: Drawing Tools + Layer Controls (20 templates).
 * Bold, high-contrast icons for the DogSprite editor UI.
 * Designed to be recognizable at 14px display size.
 *
 * DSL draw format — uses rect/circle/tri/smooth/line/pixels.
 * DB16 palette only, 2-4 roles per template.
 * Light from top-left, shadows bottom-right.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'editor_icons',
  exportNames: { templates: 'EDITOR_ICONS_BATCH1_TEMPLATES', schemes: 'EDITOR_ICONS_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    //  1. BRUSH — vertical paintbrush with wooden handle + bristles
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'brush_icon_32',
      description: 'Vertical paintbrush with wooden handle, metal ferrule, and tan bristles.',
      size: 32,
      //        01234567890123456789012345678901
      grid: [
        '................................',
        '..............HH................',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBb...............',
        '.............BBBb...............',
        '.............BBBb...............',
        '.............BBBb...............',
        '............FFFFF...............',
        '............FFFFF...............',
        '............FFFff...............',
        '...........TTTTTT...............',
        '...........TTTTTT...............',
        '...........TTTTTT...............',
        '..........TTTTTTTT..............',
        '..........TTTTTTTT..............',
        '..........TTTTTTTt..............',
        '.........TTTTTTTTTT.............',
        '.........TTTTTTTTTt.............',
        '.........TTTTTTTTTt.............',
        '........TTTTTTTTTTTt............',
        '........TTTTTTTTTTTt............',
        '........TTTTTTTTTTTt............',
        '.........TTTTTTTTTt.............',
        '..........TTTTTTTt..............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'handle', role: 'body' },
        H: { name: 'handle_hi', role: 'body', tone: 'highlight' },
        b: { name: 'handle_sh', role: 'body', tone: 'shadow' },
        F: { name: 'ferrule', role: 'accessory' },
        f: { name: 'ferrule_sh', role: 'accessory', tone: 'shadow' },
        T: { name: 'bristle', role: 'head' },
        t: { name: 'bristle_sh', role: 'head', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  2. ERASER — rectangular eraser block with band
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'eraser_icon_32',
      description: 'Rectangular eraser with blue paper wrapper band and pink rubber body.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '........AAAAAAAAAAAAAAA.........',
        '........AAAAAAAAAAAAAAA.........',
        '........AAAAAAAAAAAAAAA.........',
        '........AAAAAAAAAAAAaaa.........',
        '........AAAAAAAAAAAAaaa.........',
        '........AAAAAAAAAAAAaaa.........',
        '........FFFFFFFFFFFFFFA.........',
        '........FFFFFFFFFFFFFfA.........',
        '........BBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBBBb.........',
        '........HBBBBBBBBBBBBBb.........',
        '........HBBBBBBBBBBBBBb.........',
        '........HBBBBBBBBBBBBBb.........',
        '........HBBBBBBBBBBBBBb.........',
        '........HBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBBbb.........',
        '........BBBBBBBBBBBBBbb.........',
        '........BBBBBBBBBBBBbbb.........',
        '........bbbbbbbbbbbbbbb.........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'band', role: 'accessory' },
        a: { name: 'band_sh', role: 'accessory', tone: 'shadow' },
        F: { name: 'ferrule', role: 'belt' },
        f: { name: 'ferrule_sh', role: 'belt', tone: 'shadow' },
        B: { name: 'rubber', role: 'body' },
        H: { name: 'rubber_hi', role: 'body', tone: 'highlight' },
        b: { name: 'rubber_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        belt: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  3. FILL — paint bucket with dripping paint
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'fill_icon_32',
      description: 'Tilted paint bucket pouring blue paint with a curved handle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '......HH........................',
        '.....HH.........................',
        '....HH..........................',
        '...HH..RRRRRRRRRRRRRRR..........',
        '..HH..HRRRRRRRRRRRRRRRRR........',
        '..HH.HBBBBBBBBBBBBBBBBRRR.......',
        '..HH.HBBBBBBBBBBBBBBBBBRRR......',
        '...HH.BBBBBBBBBBBBBBBBBBRRR.....',
        '....HH.BBBBBBBBBBBBBBBBBbRR.....',
        '.......BBBBBBBBBBBBBBBBBBbRR....',
        '.......BBBBBBBBBBBBBBBBBBb......',
        '.......BBBBBBBBBBBBBBBBBBb......',
        '........BBBBBBBBBBBBBBBBBb......',
        '........BBBBBBBBBBBBBBBBbb......',
        '........BBBBBBBBBBBBBBBbb.......',
        '.........BBBBBBBBBBBBBbb........',
        '.........BBBBBBBBBBBBbb.........',
        '..........BBBBBBBBBBbb..........',
        '..........BBBBBBBBBbb...........',
        '...........BBBBBBBbb............',
        '...........BBBBBBbb.............',
        '............BBBBbb..............',
        '.............PPbb...............',
        '.............PPP................',
        '..............PP................',
        '..............PP................',
        '...............P................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'bucket', role: 'body' },
        b: { name: 'bucket_sh', role: 'body', tone: 'shadow' },
        H: { name: 'handle', role: 'body', tone: 'highlight' },
        R: { name: 'rim', role: 'accessory' },
        P: { name: 'paint', role: 'head' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  4. EYEDROPPER — vertical pipette with rubber bulb
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'eyedropper_icon_32',
      description: 'Vertical eyedropper pipette with brown rubber bulb and glass tube.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.............TTTTTT.............',
        '............TTTTTTTT............',
        '............TTTTTTTT............',
        '............TTTTTTTt............',
        '............TTTTTTTt............',
        '.............TTTTTt.............',
        '.............FFFFFF.............',
        '.............FFFFFf.............',
        '.............GGGGGG.............',
        '.............GGGGGG.............',
        '.............GGGGGG.............',
        '.............GGGGGG.............',
        '.............GGGGGg.............',
        '.............GGGGGg.............',
        '.............GGGGGg.............',
        '.............GGGGGg.............',
        '.............GGGGGg.............',
        '.............GGGGGg.............',
        '..............GGGGg.............',
        '..............GGGg..............',
        '..............GGGg..............',
        '...............GGg..............',
        '...............GGg..............',
        '...............Gg...............',
        '................G...............',
        '................P...............',
        '................P...............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        T: { name: 'bulb', role: 'body' },
        t: { name: 'bulb_sh', role: 'body', tone: 'shadow' },
        F: { name: 'ferrule', role: 'accessory' },
        f: { name: 'ferrule_sh', role: 'accessory', tone: 'shadow' },
        G: { name: 'glass', role: 'head' },
        g: { name: 'glass_sh', role: 'head', tone: 'shadow' },
        P: { name: 'tip', role: 'belt' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  5. LINE TOOL — diagonal line with endpoint dots
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'line_icon_32',
      description: 'Diagonal line from bottom-left to top-right with dot endpoints.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..........................AA....',
        '.........................ABBA...',
        '........................ABBA....',
        '.........................AA.....',
        '......................BBB.......',
        '.....................BBB........',
        '....................BBB.........',
        '...................BBB..........',
        '..................BBB...........',
        '.................BBB............',
        '................BBB.............',
        '...............BBB..............',
        '..............BBB...............',
        '.............BBB................',
        '............BBB.................',
        '...........BBB..................',
        '..........BBB...................',
        '.........BBB....................',
        '........BBB.....................',
        '.......BBB......................',
        '......BBB.......................',
        '.....BBB........................',
        '......AA........................',
        '.....ABBA.......................',
        '....ABBA........................',
        '.....AA.........................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'line_body', role: 'body' },
        A: { name: 'endpoint', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  6. RECTANGLE TOOL — rectangle outline
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'rect_icon_32',
      description: 'Rectangle outline with thick 3px border and empty center.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '....HHHHHHHHHHHHHHHHHHHHHH......',
        '....HBBBBBBBBBBBBBBBBBBBBH......',
        '....HBBBBBBBBBBBBBBBBBBBBH......',
        '....BBBBBBBBBBBBBBBBBBBBBB......',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................BB.....',
        '....BBB..................bb.....',
        '....BBBBBBBBBBBBBBBBBBBBbb......',
        '....BBBBBBBBBBBBBBBBBBBBbb......',
        '....BBBBBBBBBBBBBBBBBBBbbb......',
        '....bbbbbbbbbbbbbbbbbbbbb.......',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'border', role: 'body' },
        H: { name: 'border_hi', role: 'body', tone: 'highlight' },
        b: { name: 'border_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  7. SELECT — cursor pointer arrow
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'select_icon_32',
      description: 'Classic cursor pointer arrow pointing up-left.',
      size: 32,
      grid: [
        '................................',
        '......HH........................',
        '......HBB.......................',
        '......HBBBB.....................',
        '......HBBBBB....................',
        '......HBBBBBBB..................',
        '......HBBBBBBBB.................',
        '......HBBBBBBBBB................',
        '......HBBBBBBBBBB...............',
        '......HBBBBBBBBBBB..............',
        '......HBBBBBBBBBBBB.............',
        '......HBBBBBBBBBBBBB............',
        '......HBBBBBBBBBBBBBB...........',
        '......HBBBBBBBBBBBBBBb..........',
        '......HBBBBBBBBBBBBBBBb.........',
        '......HBBBBBBBBBbbbbbbb.........',
        '......HBBBBBBBBBb...............',
        '......HBBBBBBBBBBb..............',
        '......HBBBBbbBBBBBb.............',
        '......HBBBbb..BBBBBb............',
        '......HBBbb...BBBBBBb...........',
        '......Hbbb.....BBBBBBb..........',
        '......bb.......BBBBBBb..........',
        '.......b........BBBBbb..........',
        '..................bbb...........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'cursor', role: 'body' },
        H: { name: 'cursor_hi', role: 'body', tone: 'highlight' },
        b: { name: 'cursor_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  8. MAGIC WAND — diagonal wand with star sparkle at tip
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'wand_icon_32',
      description: 'Diagonal magic wand with wooden handle and golden star sparkle at tip.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '...............SS...............',
        '..............SSSS..............',
        '...........SSSSSSSSS............',
        '............SSSSSSSS............',
        '.............SSSSSS.............',
        '..............SSSS..............',
        '.............SS..SS.............',
        '............SS....SS............',
        '...........SS......SS...........',
        '...........BB...................',
        '..........BBB...................',
        '.........BBBF...................',
        '........BBBFF...................',
        '.......BBBFF....................',
        '......BBBFF.....................',
        '.....BBBFF......................',
        '....BBHHF.......................',
        '...BBHHH........................',
        '..BBHHH.........................',
        '..BHHH..........................',
        '..BHH...........................',
        '..BH............................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        H: { name: 'handle', role: 'body' },
        B: { name: 'shaft', role: 'body', tone: 'shadow' },
        F: { name: 'ferrule', role: 'accessory' },
        S: { name: 'star', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  9. UNDO — curved arrow pointing left
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'undo_icon_32',
      description: 'Curved counterclockwise arrow for undo action.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '..........BB....................',
        '.........BBB....................',
        '........BBBB....................',
        '.......BBBBB....................',
        '......BBBBBBBBBBBBBBBB..........',
        '.....BBBBBBBBBBBBBBBBBBB........',
        '....BBBBBBBBBBBBBBBBBBBBB.......',
        '...BBBBBBBBBBBBBBBBBBBBBBB......',
        '..BBBBBBBBBB.......BBBBBBB......',
        '..BBBBBBBBB..........BBBBBB.....',
        '..BBBBBBBB............BBBBB.....',
        '..BBBBBBB..............BBBBB....',
        '................................',
        '...............BBBB....BBBBB....',
        '...............BBBB....BBBBB....',
        '...............BBBB....BBBBB....',
        '...............BBBB....BBBBB....',
        '...............BBBB...BBBBBB....',
        '...............BBBB..BBBBBBB....',
        '...............BBBB.BBBBBBB.....',
        '...............BBBBBBBBBBB......',
        '................BBBBBBBBB.......',
        '................BBBBBBBB........',
        '.................BBBBBB.........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  10. REDO — curved arrow pointing right
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'redo_icon_32',
      description: 'Curved clockwise arrow for redo action.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '....................BB..........',
        '....................BBB.........',
        '....................BBBB........',
        '....................BBBBB.......',
        '..........BBBBBBBBBBBBBB........',
        '........BBBBBBBBBBBBBBBBB.......',
        '.......BBBBBBBBBBBBBBBBBBB......',
        '......BBBBBBBBBBBBBBBBBBBBB.....',
        '.....BBBBBBB.......BBBBBBBBBB...',
        '....BBBBBB..........BBBBBBBBB...',
        '....BBBBB............BBBBBBBB...',
        '...BBBBB..............BBBBBBB...',
        '................................',
        '...BBBBB....BBBB................',
        '...BBBBB....BBBB................',
        '...BBBBB....BBBB................',
        '...BBBBB....BBBB................',
        '...BBBBBB...BBBB................',
        '...BBBBBBB..BBBB................',
        '....BBBBBBB.BBBB................',
        '.....BBBBBBBBBBB................',
        '......BBBBBBBBB.................',
        '.......BBBBBBBB.................',
        '........BBBBBB..................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  11. HOME — simple house with door
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'home_icon_32',
      description: 'House with triangular roof and rectangular door.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '...............RR...............',
        '..............RRRR..............',
        '.............RRRRRR.............',
        '............RRHRRRRR............',
        '...........RRHHRRRRR............',
        '..........RRHHRRRRRRRR..........',
        '.........RRHHRRRRRRRRR..........',
        '........RRHHRRRRRRRRRRRR........',
        '.......RRHHRRRRRRRRRRRRR........',
        '......RRHHRRRRRRRRRRRRRRrr......',
        '.....RRHHRRRRRRRRRRRRRRRRrr.....',
        '....rrrrrrrrrrrrrrrrrrrrrrrr....',
        '........HBBBBBBBBBBBBB..........',
        '........HBBBBBBBBBBBBB..........',
        '........HBBBBBBBBBBBBB..........',
        '........HBBBBDDDBBBBB...........',
        '........HBBBBDDDBBBBB...........',
        '........HBBBBDDDBBBBB...........',
        '........BBBBBDDDBBBBBb..........',
        '........BBBBBDDDBBBBBb..........',
        '........BBBBBDDDBBBBBb..........',
        '........BBBBBDDDBBBBBb..........',
        '........BBBBBDDDBBBBBb..........',
        '........bbbbbbbbbbbbbbb.........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        R: { name: 'roof', role: 'accessory' },
        H: { name: 'roof_hi', role: 'accessory', tone: 'highlight' },
        r: { name: 'roof_sh', role: 'accessory', tone: 'shadow' },
        B: { name: 'wall', role: 'body' },
        b: { name: 'wall_sh', role: 'body', tone: 'shadow' },
        D: { name: 'door', role: 'belt' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  12. HISTORY — clock face with hands
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'history_icon_32',
      description: 'Circular clock face with hour and minute hands for history/recent.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........BBBBBBBBBB............',
        '.........BBBBBBBBBBBB...........',
        '........BBBBBBBBBBBBBB..........',
        '.......BBBBBBBBBBBBBBBB.........',
        '......BBBBBB......BBBBBB........',
        '.....BBBBB..........BBBBB.......',
        '.....BBBB....HHAA....BBBB.......',
        '....BBBBB....HHAA....BBBBB......',
        '....BBBB.....HHAA.....BBBB......',
        '....BBBB.....HHAA.....BBBB......',
        '...BBBBB.....HHAA.....BBBBB.....',
        '...BBBB......HHAA......BBBB.....',
        '...BBBB......HHAAAAAAAAAABB.....',
        '...BBBB......HHAAAAAAAAAAbb.....',
        '...BBBB......HHAA......BBBB.....',
        '...BBBBB.....HHAA.....BBBBB.....',
        '....BBBB.............BBBBB......',
        '....BBBB.............BBBB.......',
        '....BBBBB..........BBBBB........',
        '.....BBBB..........BBBB.........',
        '.....BBBBB........BBBBB.........',
        '......BBBBBB....BBBBBB..........',
        '.......BBBBBBBBBBBBBBb..........',
        '........BBBBBBBBBBBBb...........',
        '.........BBBBBBBBBBb............',
        '..........BBBBBBBBb.............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'clock_body', role: 'body' },
        b: { name: 'clock_sh', role: 'body', tone: 'shadow' },
        H: { name: 'hand_hi', role: 'accessory', tone: 'highlight' },
        A: { name: 'hand', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  13. PLUS — bold plus/add icon
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'plus_icon_32',
      description: 'Bold plus sign for adding layers, frames, or colors.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '..............HHHH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '..............HBBH..............',
        '....HHHHHHHHHHBBBBBBBBBBBB......',
        '....HBBBBBBBBBBBBBBBBBBBBBB.....',
        '....HBBBBBBBBBBBBBBBBBBBBBB.....',
        '....HBBBBBBBBBBBBBBBBBBBBbb.....',
        '....BBBBBBBBBBBBBBBBBBBBBbb.....',
        '....BBBBBBBBBBBBBBBBBBBBBbb.....',
        '....bbbbbbbbbbbBBbbbbbbbbbb.....',
        '..............BBBb..............',
        '..............BBBb..............',
        '..............BBBb..............',
        '..............BBBb..............',
        '..............BBBb..............',
        '..............BBBb..............',
        '..............BBbb..............',
        '..............bbbb..............',
        '..............bbb...............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'plus_body', role: 'body' },
        H: { name: 'plus_hi', role: 'body', tone: 'highlight' },
        b: { name: 'plus_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  14. TRASH — trash can with lid and slots
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'trash_icon_32',
      description: 'Trash can with removable lid, handle, and vertical slots.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..............HHHH..............',
        '.............HAAAAH.............',
        '........HAAAAAAAAAAAAAAAA.......',
        '........AAAAAAAAAAAAAAAAAA......',
        '........AAAAAAAAAAAAAAAAaaa.....',
        '........aaaaaaaaaaaaaaaaaaa.....',
        '.........BBBBBBBBBBBBBBBB.......',
        '.........HBBBBBBBBBBBBBB........',
        '.........HBBBBBBBBBBBBBB........',
        '.........HBB..BB..BB..BB........',
        '.........HBB..BB..BB..BB........',
        '.........HBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..BB........',
        '.........BBB..BB..BB..Bb........',
        '.........BBB..BB..BB..Bb........',
        '.........BBB..BB..BB..Bb........',
        '..........BB..BB..BB..b.........',
        '..........BB..BB..BBbb..........',
        '..........BBBBBBBBBBbb..........',
        '...........BBBBBBBBbb...........',
        '...........bbbbbbbbbb...........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'can', role: 'body' },
        H: { name: 'can_hi', role: 'body', tone: 'highlight' },
        b: { name: 'can_sh', role: 'body', tone: 'shadow' },
        A: { name: 'lid', role: 'accessory' },
        a: { name: 'lid_sh', role: 'accessory', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  15. COPY — two overlapping pages
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'copy_icon_32',
      description: 'Two overlapping document pages indicating copy/duplicate.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..........HAAAAAAAAAAA..........',
        '..........HAAAAAAAAAAA..........',
        '..........HAAAAAAAAAAA..........',
        '..........HAAALLLAAAAAA.........',
        '..........HAAALLLAAAAAA.........',
        '..........HAAAAAAAAABBB.........',
        '..........HAAALLLAAHBBB.........',
        '..........HAAALLLAAHBBB.........',
        '..........HAAAAAAA.HBBB.........',
        '..........AAAAAAAAa.HBBB........',
        '..........AAAAAAAAa.HBBB........',
        '..........aaaaaaaaaa.HBBB.......',
        '..............HBBBBBBBBBB.......',
        '..............HBBBLLLBBBB.......',
        '..............HBBBLLLBBBB.......',
        '..............HBBBBBBBBBB.......',
        '..............HBBBLLLBBBB.......',
        '..............HBBBLLLBBBB.......',
        '..............HBBBBBBBBBB.......',
        '..............HBBBLLLBBBB.......',
        '..............BBBBBBBBBBb.......',
        '..............BBBBBBBBBBb.......',
        '..............bbbbbbbbbbbb......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'back_page', role: 'accessory' },
        a: { name: 'back_sh', role: 'accessory', tone: 'shadow' },
        B: { name: 'front_page', role: 'body' },
        H: { name: 'front_hi', role: 'body', tone: 'highlight' },
        b: { name: 'front_sh', role: 'body', tone: 'shadow' },
        L: { name: 'lines', role: 'belt' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  16. EYE — open eye for layer visibility
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'eye_icon_32',
      description: 'Open eye with iris and pupil for layer visibility toggle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '...........BBBBBBBBB............',
        '........BBBBBBBBBBBBBBB.........',
        '.......BBBBBBBBBBBBBBBBB........',
        '......BBBBBBBIIIIIBBBBBBB.......',
        '.....BBBBBBIIIIIIIIIBBBBB.......',
        '....BBBBBBIIIIIIIIIIBBBBB.......',
        '...BBBBBBIIPPPPPIIIIBBBBB.......',
        '...BBBBBBIIPPPPPIIIIBBBBB.......',
        '...BBBBBBIIPhPPPIIIIBBBBBb......',
        '...BBBBBBIIPhPPPIIIIBBBBBb......',
        '....BBBBBBIIPPPPPIIIIBBBBB......',
        '.....BBBBBBIIIIIIIIIBBBBBB......',
        '......BBBBBBIIIIIIIBBBBBB.......',
        '.......BBBBBBBBBBBBBBBBb........',
        '........BBBBBBBBBBBBBBb.........',
        '.........BBBBBBBBBBBbb..........',
        '...........BBBBBBBbb............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'eyelid', role: 'body' },
        b: { name: 'eyelid_sh', role: 'body', tone: 'shadow' },
        I: { name: 'iris', role: 'accessory' },
        P: { name: 'pupil', role: 'belt' },
        h: { name: 'highlight', role: 'head' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  17. EYE OFF — closed/slashed eye for hidden layers
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'eye_off_icon_32',
      description: 'Eye with diagonal slash through it for hidden layer toggle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........................SS...',
        '..........................SS....',
        '.........................SS.....',
        '........................SS......',
        '...........BBBBBBBBSSS..........',
        '........BBBBBBBBBSSBBBB.........',
        '.......BBBBBBBBSSBBBBBBB........',
        '......BBBBBBBSSIIIIBBBBB........',
        '.....BBBBBSSIIIIIIIIBBBB........',
        '....BBBBBSIIIIIIIIIIBBBBB.......',
        '...BBBBBSSIPPPPPIIIIBBBBB.......',
        '...BBBBBSIIPPPPPIIIIBBBBB.......',
        '...BBBBBSIIPPPPPIIIIBBBBB.......',
        '...BBBSSBIIPPPPPIIIIBBBBB.......',
        '....BSSBBBIIIIIIIIIIBBBB........',
        '....SSBBBBBIIIIIIIIIBBBB........',
        '...SS.BBBBBBIIIIIIBBBBB.........',
        '..SS...BBBBBBBBBBBBBBBBb........',
        '.SS.....BBBBBBBBBBBBBb..........',
        'SS.......BBBBBBBBBBbb...........',
        '...........BBBBBBbb.............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'eyelid', role: 'body' },
        b: { name: 'eyelid_sh', role: 'body', tone: 'shadow' },
        I: { name: 'iris', role: 'accessory' },
        P: { name: 'pupil', role: 'belt' },
        S: { name: 'slash', role: 'head' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  18. LOCK — padlock closed
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'lock_icon_32',
      description: 'Closed padlock with metal shackle and keyhole.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........AAAAAAAAA............',
        '..........AAAAAAAAAAA...........',
        '.........AAAA.....AAAA..........',
        '.........AAA.......AAA..........',
        '.........AAA.......AAA..........',
        '.........AAA.......AAA..........',
        '.........AAA.......AAA..........',
        '.........AAA.......AAA..........',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBB.........',
        '.......HBBBBBBBBBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBKKKKBBBBBBB.........',
        '.......HBBBBKKKKBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBBBBBBBBBBB..........',
        '.......HBBBBBBBBBBBBBB..........',
        '.......BBBBBBBBBBBBBBBB.........',
        '.......BBBBBBBBBBBBBBBb.........',
        '.......BBBBBBBBBBBBBBbb.........',
        '.......bbbbbbbbbbbbbbb..........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'lock_body', role: 'body' },
        H: { name: 'body_hi', role: 'body', tone: 'highlight' },
        b: { name: 'body_sh', role: 'body', tone: 'shadow' },
        A: { name: 'shackle', role: 'accessory' },
        K: { name: 'keyhole', role: 'belt' },
      },
      colors: {
        body: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  19. UNLOCK — padlock open
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'unlock_icon_32',
      description: 'Open padlock with raised shackle and keyhole.',
      size: 32,
      grid: [
        '..........AAAAAAAAA.............',
        '.........AAAAAAAAAAA............',
        '........AAAA.....AAAA...........',
        '........AAA.......AAA...........',
        '........AAA.......AAA...........',
        '........AAA.....................',
        '........AAA.....................',
        '........AAA.....................',
        '................................',
        '................................',
        '................................',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBBB........',
        '.......HBBBBBBBBBBBBBBB.........',
        '.......HBBBBBBBBBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBKKKKBBBBBBB.........',
        '.......HBBBBKKKKBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBBKKBBBBBBBB.........',
        '.......HBBBBBBBBBBBBBB..........',
        '.......HBBBBBBBBBBBBBB..........',
        '.......BBBBBBBBBBBBBBBB.........',
        '.......BBBBBBBBBBBBBBBb.........',
        '.......BBBBBBBBBBBBBBbb.........',
        '.......bbbbbbbbbbbbbbb..........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'lock_body', role: 'body' },
        H: { name: 'body_hi', role: 'body', tone: 'highlight' },
        b: { name: 'body_sh', role: 'body', tone: 'shadow' },
        A: { name: 'shackle', role: 'accessory' },
        K: { name: 'keyhole', role: 'belt' },
      },
      colors: {
        body: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  20. ROTATE 3D — circular arrow with arrowhead
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'rotate3d_icon_32',
      description: 'Circular arrow suggesting 3D rotation.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '...........BB...................',
        '..........BBB...................',
        '.........BBBBBBBBBBBBB..........',
        '........BBBBBBBBBBBBBBB.........',
        '.......BBBBBBBBBBBBBBBBB........',
        '......BBBBBBB.....BBBBBBB.......',
        '.....BBBBBB.........BBBBB.......',
        '....BBBBBB...........BBBBB......',
        '....BBBBB.............BBBB......',
        '....BBBBB..............BBB......',
        '...BBBBB...............BBB......',
        '...BBBBB..............BBB.......',
        '...BBBBB..............BBB.......',
        '...BBBBB.............BBB........',
        '...BBBBB............BBBB........',
        '....BBBBB..........BBBBB........',
        '....BBBBB.........BBBBB.........',
        '.....BBBBBB.....BBBBBBB.........',
        '......BBBBBBBBBBBBBBBBB.........',
        '.......BBBBBBBBBBBBBBB..........',
        '........BBBBBBBBBBBBB...........',
        '..........BBBBBBBBB.............',
        '...................BBB..........',
        '...................BBBB.........',
        '....................BBB.........',
        '.....................BB.........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
