/**
 * Editor Icons 32x32 — Batch 2: Timeline, Palette, UI & Branding (19 templates).
 * Bold, high-contrast icons for the DogSprite editor UI.
 * Designed to be recognizable at 14px display size.
 *
 * ASCII grid format — exactly 32 rows x 32 chars each.
 * DB16 palette only, 2-4 roles per template.
 * Light from top-left, shadows bottom-right.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'editor_icons',
  exportNames: { templates: 'EDITOR_ICONS_BATCH2_TEMPLATES', schemes: 'EDITOR_ICONS_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    //  1. ARROW UP — bold upward chevron/arrow
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'arrow_up_icon_32',
      description: 'Bold upward arrow for moving layers up.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '...............BB...............',
        '..............BBBB..............',
        '.............BBBBBB.............',
        '............BBBBBBBB............',
        '...........BBBBBBBBBB...........',
        '..........HBBBBBBBBBBBB.........',
        '.........HHBBBBBBBBBBBBBB.......',
        '........HHBBBBBBBBBBBBBBbb......',
        '.......HHBBBBBBBBBBBBBBBBbb.....',
        '......HHBBBBBBBBBBBBBBBBBBbb....',
        '.......bbbb...BBBB...bbbbb......',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBbb..............',
        '..............bbbb..............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
        H: { name: 'arrow_hi', role: 'body', tone: 'highlight' },
        b: { name: 'arrow_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  2. ARROW DOWN — bold downward arrow
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'arrow_down_icon_32',
      description: 'Bold downward arrow for moving layers down.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..............HHBB..............',
        '..............HHBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '..............BBBB..............',
        '.......HHbbb..BBBB..bbbbb.......',
        '......HHBBBBBBBBBBBBBBBBBbb.....',
        '.......HHBBBBBBBBBBBBBBBBbb.....',
        '........HHBBBBBBBBBBBBBBbb......',
        '.........HBBBBBBBBBBBBBbb.......',
        '..........BBBBBBBBBBBBbb........',
        '...........BBBBBBBBBBbb.........',
        '............BBBBBBBBbb..........',
        '..............BBBBbb............',
        '...............BBbb.............',
        '................bb..............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
        H: { name: 'arrow_hi', role: 'body', tone: 'highlight' },
        b: { name: 'arrow_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  3. PLAY — play triangle
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'play_icon_32',
      description: 'Play triangle pointing right for animation playback.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '........HH......................',
        '........HBBB....................',
        '........HBBBBB..................',
        '........HBBBBBBB................',
        '........HBBBBBBBBB..............',
        '........HBBBBBBBBBBB............',
        '........HBBBBBBBBBBBBB..........',
        '........HBBBBBBBBBBBBBBB........',
        '........HBBBBBBBBBBBBBBBBB......',
        '........HBBBBBBBBBBBBBBBBB......',
        '........HBBBBBBBBBBBBBBBBBB.....',
        '........HBBBBBBBBBBBBBBBBBBB....',
        '........HBBBBBBBBBBBBBBBBBBB....',
        '........HBBBBBBBBBBBBBBBBBBb....',
        '........BBBBBBBBBBBBBBBBBbb.....',
        '........BBBBBBBBBBBBBBBbb.......',
        '........BBBBBBBBBBBBBBb.........',
        '........BBBBBBBBBBBBbb..........',
        '........BBBBBBBBBBbb............',
        '........BBBBBBBBbb..............',
        '........BBBBBBbb................',
        '........BBBBbb..................',
        '........BBbb....................',
        '........bb......................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'play', role: 'body' },
        H: { name: 'play_hi', role: 'body', tone: 'highlight' },
        b: { name: 'play_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  4. PAUSE — two vertical bars
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'pause_icon_32',
      description: 'Two vertical bars for pause action.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '........HHHH.....HHHH...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........HBBB.....HBBB...........',
        '........BBBB.....BBBB...........',
        '........BBBB.....BBBB...........',
        '........BBBb.....BBBb...........',
        '........BBBb.....BBBb...........',
        '........BBBb.....BBBb...........',
        '........BBBb.....BBBb...........',
        '........BBBb.....BBBb...........',
        '........BBbb.....BBbb...........',
        '........BBbb.....BBbb...........',
        '........bbbb.....bbbb...........',
        '........bbb......bbb............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'bar', role: 'body' },
        H: { name: 'bar_hi', role: 'body', tone: 'highlight' },
        b: { name: 'bar_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  5. STOP — square stop button
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'stop_icon_32',
      description: 'Square stop button for animation.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '......HHHHHHHHHHHHHHHHHHH.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......HBBBBBBBBBBBBBBBBBB.......',
        '......BBBBBBBBBBBBBBBBBBBB......',
        '......BBBBBBBBBBBBBBBBBBBb......',
        '......BBBBBBBBBBBBBBBBBBBb......',
        '......BBBBBBBBBBBBBBBBBBBb......',
        '......BBBBBBBBBBBBBBBBBBBb......',
        '......BBBBBBBBBBBBBBBBBBbb......',
        '......BBBBBBBBBBBBBBBBBbbb......',
        '......BBBBBBBBBBBBBBBBbbbb......',
        '......bbbbbbbbbbbbbbbbbbbbb.....',
        '......bbbbbbbbbbbbbbbbbbb.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'stop', role: 'body' },
        H: { name: 'stop_hi', role: 'body', tone: 'highlight' },
        b: { name: 'stop_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  6. LOOP — circular arrows for loop toggle
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'loop_icon_32',
      description: 'Two circular arrows forming a loop/repeat symbol.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.............BBB................',
        '............BBBBB...............',
        '...........BBBBBB...............',
        '..........BBBBBBBBBBBBB.........',
        '.........BBBBBBBBBBBBBBB........',
        '........BBBBBBBBBBBBBBBBB.......',
        '.......BBBBBB.....BBBBBBB.......',
        '......BBBBB.........BBBBBB......',
        '......BBBBB..........BBBBB......',
        '.....BBBBB............BBBBB.....',
        '.....BBBBB............BBBBB.....',
        '.....BBBBB............BBBBB.....',
        '................................',
        '................................',
        '.....BBBBB............BBBBB.....',
        '.....BBBBB............BBBBB.....',
        '.....BBBBB............BBBBB.....',
        '.....BBBBBB..........BBBBB......',
        '......BBBBBB.........BBBBB......',
        '.......BBBBBBB.....BBBBBB.......',
        '........BBBBBBBBBBBBBBBBB.......',
        '.........BBBBBBBBBBBBBBB........',
        '..........BBBBBBBBBBBBB.........',
        '...............BBBBBBB..........',
        '................BBBBB...........',
        '................BBB.............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  7. LINK — chain link
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'link_icon_32',
      description: 'Two interlocked chain links for linked frames.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.........BBBBBB.................',
        '........BBBBBBBB................',
        '.......BBBB..BBBB...............',
        '.......BBB....BBB...............',
        '.......BBB....BBB...............',
        '.......BBB....BBB...............',
        '.......BBB....BBB...............',
        '.......BBB....BBBBBBBBB.........',
        '.......BBB....BBBBBBBBBB........',
        '.......BBBB..BBBBB..BBBB........',
        '........BBBBBBBBBB...BBB........',
        '.........BBBBBBBBB...BBB........',
        '................BBB...BBB.......',
        '................BBB...BBB.......',
        '................BBB...BBB.......',
        '................BBB..BBBB.......',
        '................BBBBBBBB........',
        '.................BBBBBB.........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'chain', role: 'body' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  8. UNLINK — broken chain link
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'unlink_icon_32',
      description: 'Two separated chain links for unlinking frames.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.......BBBBBB...................',
        '......BBBBBBBB..................',
        '.....BBBB..BBBB.................',
        '.....BBB....BBB.................',
        '.....BBB....BBB.................',
        '.....BBB....BBB.................',
        '.....BBB....BBB.................',
        '.....BBB....BBB.................',
        '.....BBB....BBB.................',
        '.....BBBB..BBBB.................',
        '......BBBBBBBB..................',
        '.......BBBBBB...................',
        '................BBBBBB..........',
        '...............BBBBBBBB.........',
        '..............BBBB..BBBB........',
        '..............BBB....BBB........',
        '..............BBB....BBB........',
        '..............BBB....BBB........',
        '..............BBB....BBB........',
        '..............BBB....BBB........',
        '..............BBB....BBB........',
        '..............BBBB..BBBB........',
        '...............BBBBBBBB.........',
        '................BBBBBB..........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'chain', role: 'body' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  9. SWAP COLORS — two overlapping squares with arrows
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'swap_colors_icon_32',
      description: 'Two overlapping squares with swap arrows for FG/BG color swap.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.....AAAAAAAAAAAA...............',
        '.....AAAAAAAAAAAA...............',
        '.....AAAAAAAAAAAA...............',
        '.....AAAAAAAAAAAA..........BB...',
        '.....AAAAAAAAAAAA.........BBB...',
        '.....AAAAAAAAAAAA........BBBB...',
        '.....AAAAAAAAAAAA.......BBBBB...',
        '.....AAAAAAAAAAAA......BBBBBB...',
        '.....AAAAAAAAAAAA.....BBBBBBB...',
        '.....AAAAAAAAAAAA....BBBBBBBB...',
        '.....aaaaaaaaaaaaa...bbbbbbb....',
        '.............HHHHHHHHHHHHHH.....',
        '.............HBBBBBBBBBBBB......',
        '.............HBBBBBBBBBBBB......',
        '.............HBBBBBBBBBBBB......',
        '....BBBBBBB..HBBBBBBBBBBBB......',
        '...BBBBBBBB..HBBBBBBBBBBBB......',
        '..BBBBBBB....HBBBBBBBBBBBB......',
        '..BBBBBB.....HBBBBBBBBBBBB......',
        '..BBBBB......HBBBBBBBBBBBB......',
        '..BBBB.......BBBBBBBBBBBBB......',
        '..BBB........BBBBBBBBBBBBb......',
        '..BB.........BBBBBBBBBBBbb......',
        '.............bbbbbbbbbbbbb......',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'bg_square', role: 'accessory' },
        a: { name: 'bg_sh', role: 'accessory', tone: 'shadow' },
        B: { name: 'fg_square', role: 'body' },
        H: { name: 'fg_hi', role: 'body', tone: 'highlight' },
        b: { name: 'fg_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  10. COLOR RAMP — three gradient bars
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'color_ramp_icon_32',
      description: 'Three vertical bars showing dark-to-light gradient for color ramp generation.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '.....SSSSSS.BBBBBB.HHHHHH.......',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        S: { name: 'dark_bar', role: 'body', tone: 'shadow' },
        B: { name: 'mid_bar', role: 'body' },
        H: { name: 'light_bar', role: 'body', tone: 'highlight' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  11. CLOSE (X) — bold X mark
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'close_icon_32',
      description: 'Bold X mark for close/dismiss actions.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '......BBB................BBB....',
        '.......BBB..............BBB.....',
        '........BBB............BBB......',
        '.........BBB..........BBB.......',
        '..........BBB........BBB........',
        '...........BBB......BBB.........',
        '............BBB....BBB..........',
        '.............BBB..BBB...........',
        '..............BBBBBB............',
        '...............BBBB.............',
        '...............BBBB.............',
        '..............BBBBBB............',
        '.............BBB..BBB...........',
        '............BBB....BBB..........',
        '...........BBB......BBB.........',
        '..........BBB........BBB........',
        '.........BBB..........BBB.......',
        '........BBB............BBB......',
        '.......BBB..............BBB.....',
        '......BBB................BBB....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'x_mark', role: 'body' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  12. CHECK — bold checkmark
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'check_icon_32',
      description: 'Bold checkmark for accept/confirm actions.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..........................BBB...',
        '.........................BBB....',
        '........................BBB.....',
        '.......................BBB......',
        '......................BBB.......',
        '.....................BBB........',
        '....................BBB.........',
        '...................BBB..........',
        '..................BBB...........',
        '.................BBB............',
        '................BBB.............',
        '...............BBB..............',
        '......BBB....BBB................',
        '.......BBB..BBB.................',
        '........BBBBBB..................',
        '.........BBBBB..................',
        '..........BBBB..................',
        '...........BBB..................',
        '............BB..................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'check', role: 'body' },
      },
      colors: {
        body: { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  13. ARROW LEFT — bold left arrow for back navigation
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'arrow_left_icon_32',
      description: 'Bold left-pointing arrow for back navigation.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..............BB................',
        '.............BBB................',
        '............BBBB................',
        '...........BBBBB................',
        '..........BBBBBBBBBBBBBBBBB.....',
        '.........BBBBBBBBBBBBBBBBBB.....',
        '........BBBBBBBBBBBBBBBBBBB.....',
        '.......BBBBBBBBBBBBBBBBBBBB.....',
        '......BBBBBBBBBBBBBBBBBBBBB.....',
        '.......BBBBBBBBBBBBBBBBBBBB.....',
        '........BBBBBBBBBBBBBBBBBBB.....',
        '.........BBBBBBBBBBBBBBBBBB.....',
        '..........BBBBBBBBBBBBBBBBB.....',
        '...........BBBBB................',
        '............BBBB................',
        '.............BBB................',
        '..............BB................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  14. SPARKLES — star with sparkle dots for AI/magic
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'sparkles_icon_32',
      description: 'Four-pointed star with sparkle dots for AI/magic effects.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..............BB....SS..........',
        '..............BB....SS..........',
        '.............BBBB..SSSS.........',
        '............BBBBBB.SSS..........',
        '...........BBBBBBBB.............',
        '..........BBBBBBBBBB............',
        '.........BBBBBBBBBBBB...........',
        '........BBBBBBBBBBBBBB..........',
        '.......BBBBBBBBBBBBBBBB.........',
        '......BBBBBBBBBBBBBBBBBB........',
        '.....BBBBBBBBBBBBBBBBBBBB.......',
        '....BBBBBBBBBBBBBBBBBBBBBB......',
        '.....BBBBBBBBBBBBBBBBBBBB.......',
        '......BBBBBBBBBBBBBBBBBB........',
        '.......BBBBBBBBBBBBBBBB.........',
        '........BBBBBBBBBBBBBB..........',
        '.........BBBBBBBBBBBB...........',
        '..........BBBBBBBBBB............',
        '...........BBBBBBBB.............',
        '............BBBBBB..............',
        '.............BBBB...............',
        '..............BB................',
        '..............BB................',
        '...SS...........................',
        '...SS...........................',
        '..SSSS..........................',
        '...SS...........................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'star', role: 'body' },
        S: { name: 'sparkle', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  15. LOADER — ring with highlight arc for loading spinner
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'loader_icon_32',
      description: 'Circular ring with bright arc segment for loading spinner.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..........HHHHHHHH..............',
        '.........HHHHHHHHHHH............',
        '........HHHH.....HHHBB..........',
        '.......HHH..........BBB.........',
        '......HHH............BBB........',
        '......HHH............BBB........',
        '.....HHH..............BBB.......',
        '.....HHH..............BBB.......',
        '.....HHH..............BBB.......',
        '....HHH................BBB......',
        '....BBB................BBB......',
        '....BBB................BBB......',
        '....BBB................BBB......',
        '....BBB................BBB......',
        '....BBB................BBB......',
        '....BBB................BBB......',
        '.....BBB..............BBB.......',
        '.....BBB..............BBB.......',
        '.....BBB..............BBB.......',
        '......BBB............BBB........',
        '......BBB............BBB........',
        '.......BBB..........BBB.........',
        '........BBBB.....BBBB...........',
        '.........BBBBBBBBBBB............',
        '..........BBBBBBBBB.............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'ring', role: 'body' },
        H: { name: 'ring_hi', role: 'body', tone: 'highlight' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  16. DOG — golden retriever face (DogSprite mascot)
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'dog_icon_32',
      description: 'Golden retriever face as DogSprite mascot logo.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.......EEEE..........EEEE.......',
        '......EEEEEE........EEEEEE......',
        '.....EEEEEEE.BBBBBB.EEEEEEE.....',
        '.....EEEEEE.BBBBBBBB.EEEEEE.....',
        '....EEEEEEE.BBBBBBBB.EEEEEEE....',
        '....EEEEEEE.BBBBBBBB.EEEEEEE....',
        '....EEEEEE.HBBBBBBBB.EEEEEEE....',
        '....EEEEEE.HBBBBBBBB.EEEEEEE....',
        '....EEEEEE.HBBBBBBBB.EEEEEEE....',
        '.....EEEEE.HBBBBBBBB.EEEEE......',
        '.....EEEEE.HBBBBBBBB.EEEEE......',
        '......EEEE.HBBBBBBBB.EEEE.......',
        '...........HBBPPBBBB............',
        '...........HBBPPBBBB............',
        '...........HBBBBBBBB............',
        '..........HBBBNNBBBBB...........',
        '..........HBBBNNNBBBB...........',
        '..........HBBBNNBBBBB...........',
        '..........HBMMBBMMBBBB..........',
        '..........BBMMMMMMBBB...........',
        '..........BBMMMMMMBBB...........',
        '...........BMMMMMMBB............',
        '...........BBMMMMBB.............',
        '............BBBBBB..............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'face', role: 'body' },
        H: { name: 'face_hi', role: 'body', tone: 'highlight' },
        E: { name: 'ears', role: 'body', tone: 'shadow' },
        P: { name: 'eyes', role: 'eye' },
        N: { name: 'nose', role: 'belt' },
        M: { name: 'muzzle', role: 'head' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye: { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        belt: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  17. SUN — circle with four thick rays
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'sun_icon_32',
      description: 'Sun with central disc and four thick rays for light theme.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..............BBB...............',
        '..............BBB...............',
        '..............BBB...............',
        '..............BBB...............',
        '................................',
        '................................',
        '........HHHHHHHHHHHHH...........',
        '.........HBBBBBBBBBB............',
        '..........HBBBBBBBBBB...........',
        'BBB.......HBBBBBBBBBB.......BBB.',
        'BBB.......HBBBBBBBBBB.......BBB.',
        'BBB.......HBBBBBBBBBB.......BBB.',
        '..........HBBBBBBBBBB...........',
        '..........HBBBBBBBBBB...........',
        '..........HBBBBBBBBBB...........',
        '..........HBBBBBBBBBB...........',
        '..........BBBBBBBBBBBb..........',
        '..........BBBBBBBBBBBb..........',
        'BBB.......BBBBBBBBBBBb......BBB.',
        'BBB.......BBBBBBBBBBBb......BBB.',
        'BBB........BBBBBBBBBbb......BBB.',
        '..........bbbbbbbbbbbb..........',
        '................................',
        '................................',
        '..............BBB...............',
        '..............BBB...............',
        '..............BBB...............',
        '..............BBB...............',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'sun', role: 'body' },
        H: { name: 'sun_hi', role: 'body', tone: 'highlight' },
        b: { name: 'sun_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  18. MOON — crescent moon for dark theme
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'moon_icon_32',
      description: 'Crescent moon shape for dark theme toggle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........HBBBBBB..............',
        '..........HBBBBBBB..............',
        '.........HBBBBBBBB..............',
        '........HBBBBBBBBB..............',
        '........HBBBBBBBB...............',
        '.......HBBBBBBBB................',
        '.......HBBBBBBB.................',
        '.......HBBBBBB..................',
        '......HBBBBBB...................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBB....................',
        '......HBBBBBB...................',
        '.......BBBBBB...................',
        '.......BBBBBBB..................',
        '.......BBBBBBBBB................',
        '........BBBBBBBBBb..............',
        '........BBBBBBBBBBb.............',
        '.........BBBBBBBBBbb............',
        '..........BBBBBBBBbb............',
        '...........BBBBBBbb.............',
        '............bbbbb...............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'moon', role: 'body' },
        H: { name: 'moon_hi', role: 'body', tone: 'highlight' },
        b: { name: 'moon_sh', role: 'body', tone: 'shadow' },
      },
      colors: {
        body: { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  19. GLOBE — sphere with meridian/latitude lines
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'globe_icon_32',
      description: 'Globe sphere with meridian and latitude lines for language/locale.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........HBBBBBBBB.............',
        '.........HBBBBBBBBBB............',
        '........HBBBB.LL.BBBBB..........',
        '.......HBBBB..LL..BBBBB.........',
        '......HBBBB...LL...BBBBB........',
        '.....HBBBBB...LL...BBBBBB.......',
        '.....HBBBB....LL....BBBBB.......',
        '....HBBBBB....LL....BBBBBB......',
        '....HLLLLLLLLLLLLLLLLLLLLBB.....',
        '....HLLLLLLLLLLLLLLLLLLLLBB.....',
        '....HBBBBB....LL....BBBBBB......',
        '....HBBBBB....LL....BBBBBB......',
        '....HBBBBB....LL....BBBBBB......',
        '....HBBBBB....LL....BBBBBb......',
        '....HBBBBB....LL....BBBBBb......',
        '....HBBBBB....LL....BBBBBb......',
        '....HLLLLLLLLLLLLLLLLLLLLBB.....',
        '....HLLLLLLLLLLLLLLLLLLLLBB.....',
        '....BBBBBB....LL....BBBBBb......',
        '.....BBBBB....LL....BBBBb.......',
        '.....BBBBB....LL...BBBBBb.......',
        '......BBBBB...LL...BBBBb........',
        '.......BBBBB..LL..BBBBb.........',
        '........BBBBB.LL.BBBBb..........',
        '.........BBBBBBBBBBBb...........',
        '..........BBBBBBBBBb............',
        '...........bbbbbbb..............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'globe', role: 'body' },
        H: { name: 'globe_hi', role: 'body', tone: 'highlight' },
        b: { name: 'globe_sh', role: 'body', tone: 'shadow' },
        L: { name: 'lines', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#346524', base: '#346524', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
