/**
 * Effects batch 6 — 13 unique VFX effects to reach 100.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'effects',
  exportNames: { templates: 'EFFECT_BATCH6_TEMPLATES', schemes: 'EFFECT_BATCH6_COLOR_SCHEMES' },
  templates: [

    {
      id: 'frost_nova_16',
      description: 'Expanding ring of frost / ice explosion.',
      grid: [
        '................',
        '....HH....HH....',
        '...HH..HH..HH...',
        '..HH..EEEE..HH..',
        '..H..EEEEEE..H..',
        '.HH.EE....EE.HH.',
        '..H.EE....EE.H..',
        '..HH.EEEEEE.HH..',
        '...HH..EEEE..H..',
        '....HH....HH....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'ice_shards', role: 'head' },
        E: { name: 'frost_ring', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'chain_lightning_16',
      description: 'Branching chain lightning bolt effect.',
      grid: [
        '....HH..........',
        '.....HH.........',
        '......HHH.......',
        '.......HH.......',
        '......HH........',
        '.....HHH........',
        '......HHHH......',
        '.......HHH......',
        '........HHHH....',
        '.........HH.....',
        '..........HHH...',
        '...........HH...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lightning', role: 'head' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    {
      id: 'fire_tornado_16',
      description: 'Swirling fire tornado / flame vortex.',
      grid: [
        '......HH........',
        '.....HHHH.......',
        '....HHHHHH......',
        '...EEHHHHEE.....',
        '..EEEEHHEEEE....',
        '..EEEEHHEEEEE...',
        '...EEEHHEEEE....',
        '....EEHHEEEE....',
        '.....EHHEEE.....',
        '....EEHHEEE.....',
        '....EEHHEEE.....',
        '.....EEEE.......',
        '......EE........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'core', role: 'head' },
        E: { name: 'flames', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'heal_pulse_16',
      description: 'Pulsing green healing wave effect.',
      grid: [
        '................',
        '......EEEE......',
        '....EE....EE....',
        '...EE......EE...',
        '..EE.HHHHHH.EE..',
        '..E.HHHHHHHH.E..',
        '..E.HH....HH.E..',
        '..E.HH....HH.E..',
        '..E.HHHHHHHH.E..',
        '..EE.HHHHHH.EE..',
        '...EE......EE...',
        '....EE....EE....',
        '......EEEE......',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'outer_wave', role: 'eye' },
        H: { name: 'inner_glow', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:  { shadow: '#6daa2c', base: '#8bef88', highlight: '#deeed6' },
      },
    },

    {
      id: 'shadow_bolt_16',
      description: 'Dark magic shadow bolt projectile.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..EE............',
        '.EEEEHHHH.......',
        'EEEEEHHHHHHHH...',
        'EEEEEHHHHHHHH...',
        '.EEEEHHHH.......',
        '..EE............',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'shadow_trail', role: 'eye' },
        H: { name: 'bolt_core', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        head:  { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
      },
    },

    {
      id: 'poison_mist_16',
      description: 'Spreading poison mist / toxic gas.',
      grid: [
        '................',
        '....HH..HH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '.HHEEHHHHEEHH...',
        '.HHEEHHHHEE.HH..',
        'HHHHHHHHHHHHHH..',
        'HHHHHHHHHHHHHH..',
        '.HHHHHHHHHHHH...',
        '..HHHHHHHHHH....',
        '...HHHHHHHH.....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'mist', role: 'head' },
        E: { name: 'bubbles', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:   { shadow: '#6daa2c', base: '#8bef88', highlight: '#deeed6' },
      },
    },

    {
      id: 'arcane_missile_16',
      description: 'Homing arcane magic missile.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..EEE...........',
        '.EEEEHHHHHH.....',
        '.EEEEHHHHHH.....',
        '..EEE...........',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'trail', role: 'eye' },
        H: { name: 'missile', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    {
      id: 'ground_crack_16',
      description: 'Ground cracking / earthquake fissure effect.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...HH...........',
        '..HHHH..........',
        '...HHHHH........',
        '....HHHHHHH.....',
        '.....HHHHHH.....',
        '......HHHHHHH...',
        '.......HHHH.....',
        '........HH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'crack', role: 'head' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'divine_beam_16',
      description: 'Vertical divine light beam from above.',
      grid: [
        '....HHHHHHHH....',
        '.....HHHHHH.....',
        '.....EEEEEE.....',
        '.....EEEEEE.....',
        '.....EEEEEE.....',
        '......EEEE......',
        '......EEEE......',
        '......EEEE......',
        '......EEEE......',
        '......EEEE......',
        '.....EEEEEE.....',
        '....EEEEEEEE....',
        '...EEEEEEEEEE...',
        '..EEEEEEEEEEEE..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'source', role: 'head' },
        E: { name: 'beam', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:   { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    {
      id: 'smoke_bomb_16',
      description: 'Ninja smoke bomb / poof cloud.',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '.HHHHHHHHHHHHH..',
        '.HHHHHHHHHHHHH..',
        '.HHHHHHHHHHHH...',
        '..HHHHHHHHHH....',
        '...HHHHHHHHH....',
        '....HHHHHH......',
        '.....HHHH.......',
        '......BB........',
        '......BB........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'smoke', role: 'head' },
        B: { name: 'bomb', role: 'body' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'blood_drain_16',
      description: 'Vampiric blood drain / life steal effect.',
      grid: [
        '................',
        '..HH........HH..',
        '...HH......HH...',
        '....HH....HH....',
        '.....HH..HH.....',
        '......HHHH......',
        '.......EE.......',
        '......EEEE......',
        '.....EEEEEE.....',
        '....EEEEEEEE....',
        '...EE......EE...',
        '..EE........EE..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'drain_lines', role: 'head' },
        E: { name: 'blood_pool', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    {
      id: 'sand_blast_16',
      description: 'Desert sand blast / wind attack.',
      grid: [
        '................',
        '..H.....H.......',
        '...HH..HHH......',
        '.HHHHHHHHHH.....',
        'HHHHHHHHHHHHH...',
        'HHHHHHHHHHHHHH..',
        'HHHHHHHHHHHHH...',
        '.HHHHHHHHHH.....',
        '...HH..HHH......',
        '..H.....H.......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'sand', role: 'head' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'time_warp_16',
      description: 'Time distortion / clock warp effect.',
      grid: [
        '................',
        '....EEEEEEEE....',
        '...EE......EE...',
        '..EE.HHHHHH.EE..',
        '..E.HH....HH.E..',
        '..E.HH.HH.HH.E..',
        '..E.HH.HH.HH.E..',
        '..E.HH....HH.E..',
        '..EE.HHHHHH.EE..',
        '...EE......EE...',
        '....EEEEEEEE....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'distortion', role: 'eye' },
        H: { name: 'clock', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'venom_spit_16',
      description: 'Acid / venom spit projectile.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..EEHHHHHH......',
        '.EEEEHHHHHHH....',
        '.EEEEHHHHHHH....',
        '..EEHHHHHH......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'trail', role: 'eye' },
        H: { name: 'spit', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:  { shadow: '#6daa2c', base: '#8bef88', highlight: '#deeed6' },
      },
    },

    {
      id: 'gravity_crush_16',
      description: 'Gravity crush / implosion effect.',
      grid: [
        '................',
        '..H..........H..',
        '...H........H...',
        '....H......H....',
        '.....EEEEEE.....',
        '....EEEEEEEE....',
        '....EEEEEEEE....',
        '....EEEEEEEE....',
        '....EEEEEEEE....',
        '.....EEEEEE.....',
        '....H......H....',
        '...H........H...',
        '..H..........H..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'force_lines', role: 'head' },
        E: { name: 'core', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
        eye:   { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
      },
    },

    {
      id: 'wind_slash_crescent_16',
      description: 'Crescent wind slash / air cutter.',
      grid: [
        '................',
        '................',
        '..............HH',
        '...........HHHH.',
        '.........HHHH...',
        '.......HHHH.....',
        '.....HHHH.......',
        '...HHHH.........',
        '.HHHH...........',
        'HHHH............',
        'HH..............',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'slash', role: 'head' },
      },
      colors: {
        head:  { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
