/**
 * Effects batch 1 — 20 new VFX/magic effect templates.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'effects',
  exportNames: { templates: 'EFFECT_BATCH1_TEMPLATES', schemes: 'EFFECT_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. FIREBALL ────────────────────────────────────────────
    {
      id: 'fireball_16',
      description: 'Fireball projectile — bright core, orange-red outer flames, motion trail.',
      grid: [
        '................',
        '................',
        '........HH......',
        '.......HHHH.....',
        '......HHBBHH....',
        '.....HHBEEBHH...',
        '.....HHBBBBHH...',
        '....XHHBBBBHHX..',
        '....XHHHHHHHX...',
        '.....XHHHHHX....',
        '......XHHHX.....',
        '.....XXAAXX.....',
        '....XXAAXX......',
        '...XXAAX........',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'core_bright', role: 'eye' },
        B: { name: 'core', role: 'body' },
        H: { name: 'flame_mid', role: 'head' },
        X: { name: 'flame_outer', role: 'accessory' },
        A: { name: 'trail', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 2. ICE SHARD ───────────────────────────────────────────
    {
      id: 'ice_shard_16',
      description: 'Ice shard projectile — crystalline spike with frost trail.',
      grid: [
        '................',
        '..........B.....',
        '.........BB.....',
        '........BBB.....',
        '.......BBBE.....',
        '......BBBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBB.....',
        '...BBBBBBB......',
        '..BBBBBBB.......',
        '..BBBBBB........',
        '..AABBB.........',
        '...AAB..........',
        '....AA..........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'crystal', role: 'body' },
        E: { name: 'sparkle', role: 'eye' },
        A: { name: 'frost_trail', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 3. LIGHTNING BOLT ──────────────────────────────────────
    {
      id: 'lightning_bolt_16',
      description: 'Zigzag lightning bolt with bright core, electric glow.',
      grid: [
        '......BBB.......',
        '.......BBB......',
        '........BBB.....',
        '.......EBBB.....',
        '......BBBBB.....',
        '.....BBBBB......',
        '....BBBBB.......',
        '...EBBBBE.......',
        '....BBBBB.......',
        '.....BBBBB......',
        '......BBBBB.....',
        '.......BBBB.....',
        '........BBB.....',
        '.........BB.....',
        '..........B.....',
        '................',
      ],
      chars: {
        B: { name: 'bolt', role: 'body' },
        E: { name: 'glow_nodes', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 4. HEALING AURA ────────────────────────────────────────
    {
      id: 'healing_aura_16',
      description: 'Healing magic aura — glowing cross/plus shape with sparkles, green glow.',
      grid: [
        '................',
        '......E..E......',
        '.......BB.......',
        '......BBBB......',
        '......BBBB......',
        '..E.BBBBBBBB.E..',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '..E.BBBBBBBB.E..',
        '......BBBB......',
        '......BBBB......',
        '.......BB.......',
        '......E..E......',
        '................',
      ],
      chars: {
        B: { name: 'aura', role: 'body' },
        E: { name: 'sparkles', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 5. SHIELD BUBBLE ───────────────────────────────────────
    {
      id: 'shield_bubble_16',
      description: 'Magical shield bubble — translucent sphere with hex pattern and sparkle.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '...HH......HH...',
        '..H..........H..',
        '.H..E.........H.',
        '.H............H.',
        'H....XX....XX..H',
        'H....XX....XX..H',
        'H..............H',
        '.H..XX....XX..H.',
        '.H..XX....XX..H.',
        '..H..........H..',
        '...HH......HH...',
        '.....HHHHHH.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'shell', role: 'head' },
        X: { name: 'hex_pattern', role: 'accessory' },
        E: { name: 'sparkle', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 6. SMOKE PUFF ──────────────────────────────────────────
    {
      id: 'smoke_puff_16',
      description: 'Smoke cloud puff — billowing gray cloud with darker core.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '...HHHHHHHHH....',
        '..HHHHHHHHHHHH..',
        '.HHHHBBBBHHHHHH.',
        '.HHHBBBBBBHHHH..',
        'HHHHBBBBBBHHHH..',
        'HHHHHBBBBHHHHH..',
        '.HHHHHHHHHHHHH..',
        '..HHHHHHHHHH....',
        '...HHHHHHH......',
        '.....HHH........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'outer_cloud', role: 'head' },
        B: { name: 'inner_cloud', role: 'body' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. EXPLOSION ───────────────────────────────────────────
    {
      id: 'explosion_16',
      description: 'Explosion burst — bright center, orange-red expanding ring, debris.',
      grid: [
        '......X..X......',
        '...X..HH..X.....',
        '....HHHHHH......',
        '...HHHHHHHHX....',
        '..XHHBBBBHHH....',
        '..HHHBEEBHHH....',
        '..HHHBBBBHHH.X..',
        '..HHHHHHHHHHH...',
        '...HHHHHHHHHX...',
        '..X.HHHHHHHH....',
        '....XHHHHHX.....',
        '.....XHHX..X....',
        '......X.X.......',
        '...X............',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'core_white', role: 'eye' },
        B: { name: 'core_hot', role: 'body' },
        H: { name: 'fireball', role: 'head' },
        X: { name: 'debris', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 8. POISON CLOUD ────────────────────────────────────────
    {
      id: 'poison_cloud_16',
      description: 'Toxic poison cloud — green murky gas with skull shape, bubbles.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHHEEHHHHHH..',
        '.HHHHHHHHHHHHHH.',
        '.HHHHHFFHHHHHH..',
        '.HHHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHH...',
        '...HHHHHHHHH....',
        '....XHHHHHX.....',
        '.....XHHHX......',
        '......XXX.......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'gas_cloud', role: 'head' },
        E: { name: 'skull_eyes', role: 'eye' },
        F: { name: 'skull_mouth', role: 'face' },
        X: { name: 'bubbles', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        face:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 9. MAGIC CIRCLE ────────────────────────────────────────
    {
      id: 'magic_circle_16',
      description: 'Arcane magic circle — glowing ring with rune symbols.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHHHH.....',
        '...HH......HH...',
        '..H..XXXXXX..H..',
        '..H.X......X.H..',
        '..H.X......X.H..',
        '..H..XXXXXX..H..',
        '...HH......HH...',
        '.....HHHHHH.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'outer_ring', role: 'head' },
        X: { name: 'inner_runes', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 10. STAR BURST ─────────────────────────────────────────
    {
      id: 'star_burst_16',
      description: 'Star/sparkle burst — 8-pointed star with bright center.',
      grid: [
        '................',
        '.......B........',
        '......BBB.......',
        '.......B........',
        '..B...BEB...B...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '..BBBBEEBBBBB...',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '..B...BEB...B...',
        '.......B........',
        '......BBB.......',
        '.......B........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'rays', role: 'body' },
        E: { name: 'center', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 11. WATER SPLASH ───────────────────────────────────────
    {
      id: 'water_splash_16',
      description: 'Water splash impact — droplets radiating from center, foam.',
      grid: [
        '..B.........B...',
        '...B.......B....',
        '....B..B..B.....',
        '.....BBBBB......',
        '....BBBBBBB.....',
        '...BBBEEEBBB....',
        '..BBBBEEEBBBB...',
        '..BBBBEEEBBBB...',
        '...BBBEEEBBB....',
        '....BBBBBBB.....',
        'HHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHH',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'droplets', role: 'body' },
        E: { name: 'foam_center', role: 'eye' },
        H: { name: 'water_surface', role: 'head' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 12. TORNADO ────────────────────────────────────────────
    {
      id: 'tornado_16',
      description: 'Small tornado/whirlwind — funnel shape with debris, wind lines.',
      grid: [
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '....HHHHHHHHH...',
        '.....HHHHHHHH...',
        '.....HHHHHHH....',
        '......HHHHHH....',
        '......HBHBHH....',
        '.......HBHH.....',
        '.......HHBH.....',
        '......HHBHH.....',
        '......HHHH......',
        '.......HHH......',
        '.......HH.......',
        '........H.......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wind', role: 'head' },
        B: { name: 'debris', role: 'body' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 13. DARK ORBS ──────────────────────────────────────────
    {
      id: 'dark_orbs_16',
      description: 'Dark magic orbs — three floating dark spheres with purple glow.',
      grid: [
        '................',
        '................',
        '....XBBX........',
        '...XBBBBX.......',
        '...XBEBB.X......',
        '....XBBX........',
        '..........XBBX..',
        '.........XBBBBX.',
        '.........XBEBBX.',
        '..........XBBX..',
        '......XBBX......',
        '.....XBBBBX.....',
        '.....XBEBBX.....',
        '......XBBX......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'orb_body', role: 'body' },
        E: { name: 'orb_glow', role: 'eye' },
        X: { name: 'aura', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#442434', base: '#30346d', highlight: '#442434' },
      },
    },

    // ─── 14. HOLY LIGHT ─────────────────────────────────────────
    {
      id: 'holy_light_16',
      description: 'Divine holy light — radiant beam from above with sparkles.',
      grid: [
        '......EEEE......',
        '.....EEEEEE.....',
        '......BBBB......',
        '.....BBBBBB.....',
        '....HBBBBBBH....',
        '...HHBBBBBBHH...',
        '..HHHBBBBBBHHH..',
        '.HHHHBBBBBBHHHH.',
        'HHHHHBBBBBBHHHHH',
        '.HHHHBBBBBBHHHH.',
        '..HHHBBBBBBHHH..',
        '...HHBBBBBBHH...',
        '....HBBBBBBH....',
        '.....HHHHHH.....',
        '......HHHH......',
        '................',
      ],
      chars: {
        E: { name: 'source', role: 'eye' },
        B: { name: 'beam_core', role: 'body' },
        H: { name: 'glow_halo', role: 'head' },
      },
      colors: {
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. SLASH EFFECT ───────────────────────────────────────
    {
      id: 'slash_effect_16',
      description: 'Melee slash arc — curved white trail with speed lines.',
      grid: [
        '..............BB',
        '.............BBB',
        '...........BBBB.',
        '..........BBBB..',
        '.........BBBE...',
        '........BBBB....',
        '.......BBBB.....',
        '......BBBB......',
        '.....BBBE.......',
        '....BBBB........',
        '...BBBB.........',
        '..BBBB..........',
        '.BBBE...........',
        'BBBB............',
        'BBB.............',
        'B...............',
      ],
      chars: {
        B: { name: 'slash_trail', role: 'body' },
        E: { name: 'sparkle', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 16. TELEPORT PARTICLES ─────────────────────────────────
    {
      id: 'teleport_particles_16',
      description: 'Teleport effect — vertical sparkle column with dissolving pixels.',
      grid: [
        '.....B..B.B.....',
        '....BBB.BB......',
        '...B.BBBBB.B....',
        '....BBBBBBB.....',
        '...BBBEEBBBB....',
        '...BBBEEBBBB....',
        '...BBBEEBBB.....',
        '....BBEEBBBB....',
        '....BBEEBBBB....',
        '...BBBEEBBB.....',
        '....BBBBBBB.....',
        '...B.BBBBB.B....',
        '....BBB.BB......',
        '.....B..B.B.....',
        '......B.B.......',
        '................',
      ],
      chars: {
        B: { name: 'particles', role: 'body' },
        E: { name: 'core_column', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 17. FIRE COLUMN ────────────────────────────────────────
    {
      id: 'fire_column_16',
      description: 'Rising fire column — pillar of flame with bright core.',
      grid: [
        '......X.X.......',
        '.....XHHHX......',
        '....XHHHHXHX....',
        '....XHHHHHX.....',
        '...XHHBBHHX.....',
        '...XHHBBHHX.....',
        '...XHHBBHHX.....',
        '...HHBBBBHH.....',
        '...HHBBBBHH.....',
        '...HHBBBBHH.....',
        '..HHHBBBBHHH....',
        '..HHHBBBBHHH....',
        '.HHHHBBBBHHHH...',
        '.AAAAAAAAAAAAA..',
        'AAAAAAAAAAAAAAA.',
        '................',
      ],
      chars: {
        X: { name: 'flame_tips', role: 'accessory' },
        H: { name: 'outer_flame', role: 'head' },
        B: { name: 'core', role: 'body' },
        A: { name: 'base_embers', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 18. BUFF ARROW UP ──────────────────────────────────────
    {
      id: 'buff_arrow_up_16',
      description: 'Stat buff indicator — upward green arrow with sparkle effect.',
      grid: [
        '................',
        '.......BB.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBEBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
        E: { name: 'sparkle', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 19. DEBUFF ARROW DOWN ──────────────────────────────────
    {
      id: 'debuff_arrow_down_16',
      description: 'Stat debuff indicator — downward red arrow with skull.',
      grid: [
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBEBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......BB.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'arrow', role: 'body' },
        E: { name: 'skull', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 20. CRYSTAL SHATTER ────────────────────────────────────
    {
      id: 'crystal_shatter_16',
      description: 'Crystal shattering effect — fragments flying outward, light burst.',
      grid: [
        'B..........B....',
        '.BB.......BB....',
        '..BB.....BB.....',
        '...B..E..B......',
        '....BBBBB.......',
        '...BBBBBBB......',
        '..BBBBEBBBB.....',
        '..BBBBBBBBB.B...',
        '...BBBBBBB.BB...',
        '....BBBBB.BB....',
        '...B..E..BB.....',
        '..BB.....B......',
        '.BB.............',
        'B...............',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'fragments', role: 'body' },
        E: { name: 'light_burst', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
