/**
 * Enemies batch 1 — 20 new enemy templates.
 * Distinct RPG monster/enemy archetypes at 16x16.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'enemies',
  exportNames: { templates: 'ENEMY_BATCH1_TEMPLATES', schemes: 'ENEMY_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. GOBLIN — small green humanoid ───────────────────────
    {
      id: 'goblin_16',
      description: 'Small goblin with pointy ears, loincloth, crude dagger.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....XHEHHEHX....',
        '.....HHFFHH.....',
        '......HHHH......',
        '.....AABBAA.....',
        '....AA.BB.AA....',
        '.....ABBBBA.....',
        '......GGGG......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        X: { name: 'ears', role: 'hair' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'loincloth', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        hair:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 2. ORC WARRIOR — muscular brute ────────────────────────
    {
      id: 'orc_warrior_16',
      description: 'Muscular orc with tusks, leather armor, battleaxe.',
      grid: [
        '................',
        '.....XHHHX......',
        '....XHHHHHX.....',
        '....HHEHHEH.....',
        '....HHFFHHHH....',
        '.....HHHHHH.....',
        '....AABBBBA.....',
        '...AAABBBBAA....',
        '...DD.BBBB.DD...',
        '......GGGG......',
        '.....GGGGGG.....',
        '.....LLLLLL.....',
        '....LL....LL....',
        '....TT....TT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'tusks_ears', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hands', role: 'hand' },
        G: { name: 'belt_armor', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. DARK MAGE — hooded spellcaster ──────────────────────
    {
      id: 'dark_mage_16',
      description: 'Dark mage with hooded robe, glowing eyes, staff, flowing cloak.',
      grid: [
        '................',
        '.....XXXXX......',
        '....XHHHHHX.....',
        '....XHEEHX......',
        '.....XHHX.......',
        '.....BBBB.......',
        '....AABBBBX.....',
        '...AA.BBBB.X....',
        '...D..BBBB..X...',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..LLLLLLLLLLLL..',
        '..TTTTTTTTTTTT..',
        '................',
      ],
      chars: {
        X: { name: 'hood_cloak', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'robe', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hand', role: 'hand' },
        L: { name: 'robe_bottom', role: 'leg' },
        T: { name: 'robe_hem', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        hand:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
      },
    },

    // ─── 4. ZOMBIE — shambling undead ───────────────────────────
    {
      id: 'zombie_16',
      description: 'Shambling zombie with torn clothes, exposed ribs, outstretched arms.',
      grid: [
        '................',
        '.....XHHHX......',
        '.....HHHHHH.....',
        '.....HHEHHEH....',
        '.....HHFFHH.....',
        '......HHHH......',
        '....AABBBBAA....',
        '...AAABBBBAAA...',
        '..DD..BBBB..DD..',
        '......GGGG......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hair_ragged', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mouth', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hands', role: 'hand' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        hand:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 5. WRAITH — floating spectral figure ───────────────────
    {
      id: 'wraith_16',
      description: 'Floating wraith — dark hooded figure with glowing eyes, ragged trailing form.',
      grid: [
        '................',
        '......XXXX......',
        '.....XHHHHX.....',
        '....XHHEEHX.....',
        '....XXHHHXX.....',
        '.....XBBX.......',
        '....AABBBBAA....',
        '...AA.BBBB.AA...',
        '..DD..BBBB..DD..',
        '......BBBB......',
        '.....BBBBBB.....',
        '....LLLLLLLL....',
        '...LL.LLLL.LL...',
        '..LL...LL...LL..',
        '.LL.........LL..',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'claws', role: 'hand' },
        L: { name: 'trailing_form', role: 'leg' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
        hand:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
      },
    },

    // ─── 6. HARPY — bird-woman hybrid ───────────────────────────
    {
      id: 'harpy_16',
      description: 'Harpy with woman face, feathered body, large wing-arms, taloned feet.',
      grid: [
        '......HHHH......',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '......BBBB......',
        '....AABBBBAA....',
        '...AAABBBBAAAA..',
        '..AAAABBBBAAA...',
        '..AAABBBBBBAA...',
        '...AABBBBBA.....',
        '....AABBBA......',
        '......LLLL......',
        '.....LL..LL.....',
        '....LL....LL....',
        '...TT......TT...',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'wings', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'talons', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 7. TROLL — large regenerating brute ────────────────────
    {
      id: 'troll_16',
      description: 'Large troll with long nose, mossy skin, hunched posture, big hands.',
      grid: [
        '................',
        '....HHHHH.......',
        '...HHHHHHHH.....',
        '...HHEHHEHH.....',
        '...HHFFFHH......',
        '....HHHHHH......',
        '...AABBBBBA.....',
        '..AAABBBBBAAA...',
        '.DDD.BBBBB.DDD..',
        '......GGGG......',
        '.....GGGGGG.....',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...TTT....TTT...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'nose_mouth', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'big_hands', role: 'hand' },
        G: { name: 'loincloth', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. MINOTAUR — bull-headed warrior ──────────────────────
    {
      id: 'minotaur_16',
      description: 'Bull-headed minotaur with horns, muscular body, hooves.',
      grid: [
        '...X......X.....',
        '..XHHHHHHHX.....',
        '...HHHHHHHH.....',
        '...HHEEHHEH.....',
        '...HHHHFFHH.....',
        '....HHHHHH......',
        '...AABBBBBA.....',
        '..AAABBBBBAAA...',
        '..DD.BBBBB.DD...',
        '.....BBBBB......',
        '.....GGGGGG.....',
        '....LLLLLLLL....',
        '...LL......LL...',
        '...TT......TT...',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'horns', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'snout', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hands', role: 'hand' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'hooves', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. IMP — small flying demon ────────────────────────────
    {
      id: 'imp_16',
      description: 'Small imp with bat wings, horns, pointed tail, mischievous grin.',
      grid: [
        '................',
        '....X....X......',
        '...XHHHHHHX.....',
        '....HHEEHHH.....',
        '....HHFFHHH.....',
        '.....HHHH.......',
        '..XX.BBBB.XX....',
        '.XXXXBBBBXXXX...',
        '.XXXXBBBBXXXX...',
        '..XX.BBBB.XX....',
        '.....GGGG.......',
        '.....LLLL.A.....',
        '....LL..LLAA....',
        '....TT..TT.A....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'wings', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'grin', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'tail', role: 'arm' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'hooves', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 10. NECROMANCER — undead summoner ──────────────────────
    {
      id: 'necromancer_16',
      description: 'Necromancer in dark robes with skull staff, glowing green eyes.',
      grid: [
        '.......XX.......',
        '......XAAX......',
        '.....XXXXX......',
        '....XXHHHXX.....',
        '....XHHEEHX.....',
        '.....XHHX.......',
        '.....BBBBA......',
        '....BBBBBBAA....',
        '...BBBBBBBBA....',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..LLLLLLLLLL....',
        '..TTTTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hood', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'robe', role: 'body' },
        A: { name: 'staff', role: 'accessory' },
        L: { name: 'robe_bottom', role: 'leg' },
        T: { name: 'robe_hem', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 11. GARGOYLE — stone demon ─────────────────────────────
    {
      id: 'gargoyle_16',
      description: 'Stone gargoyle with bat wings, horns, crouched on pedestal.',
      grid: [
        '................',
        '...X.HHHH.X.....',
        '....HHHHHHHH....',
        '....HHEEHHHH....',
        '....HHFFHHH.....',
        '.....BBBB.......',
        '..XXBBBBBBXX....',
        '.XXXXBBBBXXXX...',
        '.XXXXBBBBXXXX...',
        '..XXBBBBBBXX....',
        '.....GGGG.......',
        '.....LLLL.......',
        '....LLLLLL......',
        '...TTTTTTTT.....',
        '..TTTTTTTTTT....',
        '................',
      ],
      chars: {
        X: { name: 'wings', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        G: { name: 'waist', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'pedestal', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        face:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 12. BANDIT — masked thief ──────────────────────────────
    {
      id: 'bandit_16',
      description: 'Masked bandit with hood, dual daggers, leather armor.',
      grid: [
        '................',
        '......XXXX......',
        '.....XHHHHX.....',
        '.....HHEEHH.....',
        '.....XXFFXX.....',
        '......HHHH......',
        '....AABBBBAA....',
        '...AAABBBBAAA...',
        '...DD.BBBB.DD...',
        '......GGGG......',
        '.....GGGGGG.....',
        '.....LLLLLL.....',
        '....LL....LL....',
        '....TT....TT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'hood_mask', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'mask', role: 'face' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'daggers', role: 'accessory' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 13. VAMPIRE — undead noble ─────────────────────────────
    {
      id: 'vampire_16',
      description: 'Vampire with slicked hair, cape, pale skin, fangs.',
      grid: [
        '................',
        '.....hhhhh......',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '......HHHH......',
        '..XX.BBBBBB.XX..',
        '..XXBBBBBBBBXX..',
        '..XXBBBBBBBBXX..',
        '..XX.BBBBBB.XX..',
        '......GGGG......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
      ],
      chars: {
        h: { name: 'hair', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'fangs', role: 'face' },
        B: { name: 'torso', role: 'body' },
        X: { name: 'cape', role: 'accessory' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'boots', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        face:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 14. CENTAUR — horse-body warrior ───────────────────────
    {
      id: 'centaur_16',
      description: 'Centaur warrior — human torso on horse body, wielding spear.',
      grid: [
        '....HHH.........',
        '...HHHHH........',
        '...HEEHH........',
        '...HFFH.........',
        '..AABBBA........',
        '.AA.BBB.........',
        '.D..BBBBBBB.....',
        '...XBBBBBBBX....',
        '...XBBBBBBBX....',
        '....BBBBBBB.....',
        '...LL.BBBB.LL...',
        '..LL..LLLL..LL..',
        '..TT..TT.TT.TT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'spear', role: 'accessory' },
        X: { name: 'saddle', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'hooves', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 15. SHADOW STALKER — living shadow ─────────────────────
    {
      id: 'shadow_stalker_16',
      description: 'Living shadow — dark humanoid silhouette with glowing red eyes, wispy edges.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHHHHH.....',
        '......HHHH......',
        '.....BBBBBB.....',
        '...AABBBBBBAA...',
        '..AA.BBBBBB.AA..',
        '.AA..BBBBBB..AA.',
        '......LLLL......',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...LL......LL...',
        '..LL........LL..',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 16. CURSED ARMOR — animated empty armor ────────────────
    {
      id: 'cursed_armor_16',
      description: 'Haunted empty suit of armor — glowing visor, floating plates.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '....HHEEEEHHH...',
        '....HHHHHHHH....',
        '.....HHHHHH.....',
        '...XXBBBBBBXX...',
        '..XX.BBBBBB.XX..',
        '..XX.BBBBBB.XX..',
        '..DD.GGGGGG.DD..',
        '.....GGGGGG.....',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...TT......TT...',
        '..TTT......TTT..',
        '................',
      ],
      chars: {
        H: { name: 'helmet', role: 'head' },
        E: { name: 'visor_glow', role: 'eye' },
        B: { name: 'chestplate', role: 'body' },
        X: { name: 'pauldrons', role: 'accessory' },
        D: { name: 'gauntlets', role: 'hand' },
        G: { name: 'tasset', role: 'belt' },
        L: { name: 'greaves', role: 'leg' },
        T: { name: 'sabatons', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        hand:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 17. MUSHROOM WARRIOR — armed fungus ────────────────────
    {
      id: 'mushroom_warrior_16',
      description: 'Mushroom warrior with cap helmet, spore cloud, tiny shield.',
      grid: [
        '................',
        '.....XXXXXX.....',
        '....XXXXXXXXX...',
        '...XXXXXXXXXXX..',
        '....XXXXXXXXX...',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '....AABBBBDD....',
        '...AA.BBBB.DD...',
        '......GGGG......',
        '......LLLL......',
        '.....LL..LL.....',
        '.....TT..TT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'mushroom_cap', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'sword_arm', role: 'arm' },
        D: { name: 'shield_arm', role: 'hand' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        face:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        hand:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. LIZARDMAN — reptilian warrior ──────────────────────
    {
      id: 'lizardman_16',
      description: 'Reptilian lizardman with scaled skin, tail, crude spear, fin crest.',
      grid: [
        '................',
        '.....XHHHX......',
        '.....HHHHHH.....',
        '.....HHEEHH.....',
        '.....HHFFHH.....',
        '......HHHH......',
        '....AABBBBAA....',
        '...AA.BBBB.AA...',
        '...DD.BBBB......',
        '......GGGGLL....',
        '......LLLLLL....',
        '.....LL..LLLL...',
        '....LL....LL....',
        '....TT....TT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crest', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'snout', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'hands', role: 'hand' },
        G: { name: 'belt', role: 'belt' },
        L: { name: 'legs_tail', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#346524', base: '#6daa2c', highlight: '#d04648' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 19. WORM — giant segmented worm ────────────────────────
    {
      id: 'giant_worm_16',
      description: 'Giant worm bursting from ground — segmented body, circular maw with teeth.',
      grid: [
        '......XXXX......',
        '.....XFFFFX.....',
        '....XFHHHFX.....',
        '....XHHEEHX.....',
        '....XHHHHHX.....',
        '.....BBBBB......',
        '.....BXBXB......',
        '....BBBBBBB.....',
        '....BXBXBXB.....',
        '...BBBBBBBBB....',
        '...BXBXBXBXB....',
        '..BBBBBBBBBBB...',
        '..LLLLLLLLLLL...',
        '.LLLLLLLLLLLLL..',
        'LLLLLLLLLLLLLLL.',
        '................',
      ],
      chars: {
        X: { name: 'teeth_ring', role: 'accessory' },
        F: { name: 'maw', role: 'face' },
        H: { name: 'inner_mouth', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body_segments', role: 'body' },
        L: { name: 'ground_dirt', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        face:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 20. ELEMENTAL EARTH — mud/rock creature ────────────────
    {
      id: 'earth_elemental_16',
      description: 'Earth elemental — boulder-like body, moss patches, crystal growths.',
      grid: [
        '................',
        '.....XXHHHX.....',
        '....XHHHHHHHX...',
        '....HHHEHHEHH...',
        '....HHHHHHHH....',
        '.....HHFFHH.....',
        '....AABBBBAA....',
        '...AAABBBBAAAA..',
        '..DD..BBBB..DD..',
        '......BBBB......',
        '.....GGGGGG.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'crystals_moss', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        F: { name: 'face', role: 'face' },
        B: { name: 'body', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        D: { name: 'fists', role: 'hand' },
        G: { name: 'waist', role: 'belt' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        hand:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
