/**
 * Food batch 4 — 20 new food/drink templates.
 * Covers: bacon, french toast, smoothie, hot chocolate, cinnamon roll,
 *         tempura, curry rice, bao bun, nachos, popcorn box,
 *         cheesecake, brownie, milkshake, espresso, matcha latte,
 *         mango, banana, blueberry bowl, onion rings, garlic bread.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'FOOD_BATCH4_TEMPLATES', schemes: 'FOOD_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. BACON STRIPS ────────────────────────────────────────
    {
      id: 'bacon_strips_16',
      description: 'Three crispy bacon strips with fat marbling and browned edges.',
      grid: [
        '................',
        '................',
        '.HHHBHHBHHHBHHH.',
        '.HHHBHHBHHHBHHH.',
        '.HHBBHHBHHHBBHH.',
        '................',
        '.AHHBHHHBHHBHHH.',
        '.AHHBHHHBHHBHHH.',
        '.AHBBHHHBBHBBHH.',
        '................',
        '.HHHBHHBHHHBHHH.',
        '.HHHBHHBHHHBHHH.',
        '.HHBBHHBBHHBBHH.',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lean_meat', role: 'head' },
        B: { name: 'fat_stripe', role: 'body' },
        A: { name: 'crispy_edge', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 2. FRENCH TOAST ────────────────────────────────────────
    {
      id: 'french_toast_16',
      description: 'Two thick slices of French toast with syrup drizzle and powdered sugar.',
      grid: [
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '..SSSSSSSSSSSS..',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '..HHBHBHHHBHH...',
        '..HHHHHHHHHHH...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '..BBHBHHHBHBB...',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '....PPPPPPPP....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'syrup_drizzle', role: 'accessory' },
        H: { name: 'top_slice', role: 'head' },
        B: { name: 'bottom_slice', role: 'body' },
        T: { name: 'plate_rim', role: 'boot' },
        P: { name: 'powdered_sugar', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 3. SMOOTHIE CUP ────────────────────────────────────────
    {
      id: 'smoothie_cup_16',
      description: 'Tall fruit smoothie in clear cup with straw and fruit layer gradient.',
      grid: [
        '......SSSS......',
        '.......SS.......',
        '....HHHHHHHH....',
        '....HHHHHHHH....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBSBB...',
        '...BBBBBBBBBB...',
        '...PPPPPPPPPP...',
        '...PPPPPPPPPP...',
        '...PPPPPPPPPP...',
        '....GGGGGGGG....',
        '....GGGGGGGG....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'straw', role: 'accessory' },
        H: { name: 'foam_top', role: 'head' },
        B: { name: 'berry_layer', role: 'body' },
        P: { name: 'mango_layer', role: 'arm' },
        G: { name: 'green_layer', role: 'belt' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 4. HOT CHOCOLATE ───────────────────────────────────────
    {
      id: 'hot_chocolate_16',
      description: 'Cozy mug of hot chocolate with swirled whipped cream and cocoa dusting.',
      grid: [
        '....XXXXX.......',
        '....X...........',
        '....XXXXX.......',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBBM.',
        '..BBBBBBBBBBBBM.',
        '..BBBBBBBBBBBBM.',
        '..BBBBBBBBBBBB..',
        '...HHHHHHHHHH...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'steam_wisps', role: 'accessory' },
        C: { name: 'whipped_cream', role: 'head' },
        B: { name: 'chocolate', role: 'body' },
        H: { name: 'mug_body', role: 'arm' },
        M: { name: 'mug_handle', role: 'belt' },
        T: { name: 'mug_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 5. CINNAMON ROLL ───────────────────────────────────────
    {
      id: 'cinnamon_roll_16',
      description: 'Spiral cinnamon roll with icing drizzle and golden baked layers.',
      grid: [
        '................',
        '....IIIIIIII....',
        '...IIIIIIIIII...',
        '..HHHHHHHHHHHH..',
        '..HHSSSHHHSSSH..',
        '..HHSSSSHSSSHH..',
        '..HHHSSSSSSHHH..',
        '..HHHHSSSSHHHH..',
        '..HHHHHSSHHHHHH.',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '................',
        '................',
        '................',
      ],
      chars: {
        I: { name: 'icing_drizzle', role: 'accessory' },
        H: { name: 'dough_top', role: 'head' },
        S: { name: 'cinnamon_spiral', role: 'body' },
        B: { name: 'dough_base', role: 'arm' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 6. TEMPURA SHRIMP ──────────────────────────────────────
    {
      id: 'tempura_16',
      description: 'Golden tempura shrimp with crispy batter coat and tail exposed.',
      grid: [
        '................',
        '.........TTT....',
        '........TTTT....',
        '.......TTTTT....',
        '.......BBBBB....',
        '......BBBBBBB...',
        '.....BBBBBBBBB..',
        '....BBBHBBBBBBB.',
        '...BBBHHBBBBBBB.',
        '...BBHHHHBBBBBB.',
        '....BHHHHBBBBB..',
        '.....BHHHHBBB...',
        '......BHHBB.....',
        '.......BBB......',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'shrimp_tail', role: 'accessory' },
        B: { name: 'batter_coat', role: 'body' },
        H: { name: 'shrimp_flesh', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 7. CURRY RICE BOWL ─────────────────────────────────────
    {
      id: 'curry_rice_16',
      description: 'Bowl of golden curry poured over white rice with garnish.',
      grid: [
        '................',
        '..XXXXXXXXXX....',
        '.XXXXXXXXXXXX...',
        '..XXXXXXXXXX....',
        '...RRRRRRRRRR...',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..CCCCCCCRRRRRR.',
        '..CCCCCCCCRRRRR.',
        '..CCCCCCCCCRRRR.',
        '..CCCCCCCCCRRR..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'steam', role: 'accessory' },
        R: { name: 'rice', role: 'head' },
        C: { name: 'curry_sauce', role: 'body' },
        B: { name: 'bowl', role: 'arm' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. BAO BUN ─────────────────────────────────────────────
    {
      id: 'bao_bun_16',
      description: 'Steamed bao bun, half-open showing savory pork filling inside.',
      grid: [
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHHH.',
        '..HHHFFFFFFF.HH.',
        '..HHHFFFFFFHHHH.',
        '..HHHFFFFFFHHHH.',
        '...HHFFFFFFFF...',
        '....HHHHHHHH....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bun_dough', role: 'head' },
        F: { name: 'pork_filling', role: 'body' },
        T: { name: 'base_fold', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 9. NACHOS PLATE ────────────────────────────────────────
    {
      id: 'nachos_plate_16',
      description: 'Loaded nachos on plate with cheese sauce, jalapeños, and sour cream.',
      grid: [
        '................',
        '................',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '..NNNCCCCCNNN...',
        '..NNNNCCNNNN....',
        '.NNNNJJNNNNNNN..',
        '.NNNNNNNNNNNNN..',
        '.NNNSNNNNSNNN...',
        '..NNNNNNNNNNN...',
        '..NNNNNNNNNNN...',
        '...PPPPPPPPP....',
        '....PPPPPPP.....',
        '.....PPPPP......',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cheese_sauce', role: 'head' },
        N: { name: 'chips', role: 'body' },
        J: { name: 'jalapeno', role: 'accessory' },
        S: { name: 'sour_cream', role: 'eye' },
        P: { name: 'plate', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 10. POPCORN BOX ────────────────────────────────────────
    {
      id: 'popcorn_box_16',
      description: 'Classic cinema popcorn box with red and white stripes, fluffy popcorn piled on top.',
      grid: [
        '....PPPPPPPPPP..',
        '...PPPPPPPPPPPP.',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..PPPPPPPPPPPPPP',
        '..BRBRBRBRBRBRBR',
        '..BRBRBRBRBRBRBR',
        '..BRRBRRBRRBRRBR',
        '..BRBRBRBRBRBRBR',
        '..BRBRBRBRBRBRBR',
        '..BRBRBRBRBRBRBR',
        '...BRBRBRBRBRBRB',
        '....BBRRBBRRBBRR',
        '.....BBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'popcorn', role: 'head' },
        B: { name: 'box_white', role: 'body' },
        R: { name: 'box_red_stripe', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 11. CHEESECAKE SLICE ───────────────────────────────────
    {
      id: 'cheesecake_16',
      description: 'Slice of New York cheesecake with berry compote topping and graham cracker crust.',
      grid: [
        '................',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '....HHHHHHHH....',
        '...HHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '...TTTTTTTTTT...',
        '................',
      ],
      chars: {
        B: { name: 'berry_topping', role: 'accessory' },
        H: { name: 'cheesecake_body', role: 'head' },
        C: { name: 'graham_crust', role: 'body' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 12. BROWNIE ────────────────────────────────────────────
    {
      id: 'brownie_16',
      description: 'Rich chocolate brownie square with crackly top, chocolate chunks, and walnuts.',
      grid: [
        '................',
        '................',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHWHHHHHWHHHH.',
        '..HHHHHHHHHHHH..',
        '..HHHWWHHWWHHH..',
        '..HHHHHHHHHHHHH.',
        '..BBBBBBBBBBBBH.',
        '..BBBWBBBBBWBBB.',
        '..BBBBBBBBBBBBH.',
        '..BBBBBBBBBBBBB.',
        '..BBBWBBBBBWBBB.',
        '..BBBBBBBBBBBBB.',
        '...TTTTTTTTTTT..',
        '................',
      ],
      chars: {
        H: { name: 'crackly_top', role: 'head' },
        B: { name: 'brownie_body', role: 'body' },
        W: { name: 'walnut_chunks', role: 'accessory' },
        T: { name: 'parchment', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 13. MILKSHAKE ──────────────────────────────────────────
    {
      id: 'milkshake_16',
      description: 'Tall milkshake glass with whipped cream, cherry on top, and straw.',
      grid: [
        '.....CCCCCCC....',
        '....CCCCCCCCC...',
        '....CCCCCCCCC...',
        '.....ACCCCCC....',
        '.....ASSSSSSS...',
        '.....ASSSSSSSS..',
        '.....ASSSSSSSSS.',
        '.....ASSSSSSSS..',
        '.....ASSSSSSSS..',
        '.....ASSSSSSS...',
        '......AAAAAAAAA.',
        '......AAAAAAAAA.',
        '.......AAAAAAA..',
        '.......AAAAAAA..',
        '........AAAAA...',
        '................',
      ],
      chars: {
        C: { name: 'whipped_cream', role: 'head' },
        A: { name: 'straw', role: 'accessory' },
        S: { name: 'shake_body', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. ESPRESSO CUP ───────────────────────────────────────
    {
      id: 'espresso_cup_16',
      description: 'Small espresso demitasse cup on saucer with dark crema layer.',
      grid: [
        '................',
        '................',
        '................',
        '.....CCCCCCC....',
        '....CCCCCCCCC...',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBBM.',
        '....BBBBBBBBBBM.',
        '....BBBBBBBBBB..',
        '.....HHHHHHHH...',
        '......HHHHHH....',
        '...SSSSSSSSSSSS.',
        '...SSSSSSSSSSS..',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crema', role: 'head' },
        B: { name: 'espresso', role: 'body' },
        M: { name: 'cup_handle', role: 'arm' },
        H: { name: 'cup_base', role: 'belt' },
        S: { name: 'saucer', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 15. MATCHA LATTE ───────────────────────────────────────
    {
      id: 'matcha_latte_16',
      description: 'Green matcha latte in a ceramic cup with foam art and bamboo whisk beside it.',
      grid: [
        '................',
        '..W.............',
        '..W.............',
        '..WWWWWW........',
        '.....FFFFFFFF...',
        '....FFFFFFFFFF..',
        '....FFFFFFFFFM..',
        '....GGGGGGGGFM..',
        '....GGGGGGGGFM..',
        '....GGGGGGGGFF..',
        '....GGGGGGGGFF..',
        '....FFFFFFFFFM..',
        '.....FFFFFFFF...',
        '......TTTTTT....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'bamboo_whisk', role: 'accessory' },
        F: { name: 'foam_milk', role: 'head' },
        G: { name: 'matcha_layer', role: 'body' },
        M: { name: 'cup_handle', role: 'arm' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 16. MANGO ──────────────────────────────────────────────
    {
      id: 'mango_16',
      description: 'Ripe whole mango with orange-yellow gradient skin, green stem, and leaf.',
      grid: [
        '................',
        '.......LL.......',
        '......SSSS......',
        '.......SS.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '....HHHEHHHHHH..',
        '...HHHHHHHHHHH..',
        '...BBBBBBBBBBH..',
        '...BBBBBBBBBBH..',
        '....BBBBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '......BBBB......',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        H: { name: 'skin_top', role: 'head' },
        E: { name: 'skin_shine', role: 'eye' },
        B: { name: 'skin_bottom', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d04648' },
      },
    },

    // ─── 17. BANANA ─────────────────────────────────────────────
    {
      id: 'banana_16',
      description: 'Ripe yellow banana in natural curved shape with brown tip and speckles.',
      grid: [
        '................',
        '.....AAAA.......',
        '....AABBAA......',
        '....ABBBBA......',
        '...ABBBBBBA.....',
        '...ABBBBBBBA....',
        '...ABBBBBBBA....',
        '...ABBBBBBBBA...',
        '....ABBBBBBBBA..',
        '....AABBBBBBBBA.',
        '.....AABBBBBBBA.',
        '......AABBBBBA..',
        '.......AABBBAA..',
        '.........AAAA...',
        '..........TT....',
        '................',
      ],
      chars: {
        A: { name: 'peel_outline', role: 'arm' },
        B: { name: 'peel_body', role: 'body' },
        T: { name: 'brown_tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. BLUEBERRY BOWL ─────────────────────────────────────
    {
      id: 'blueberry_bowl_16',
      description: 'Ceramic bowl filled with plump blueberries, each with a tiny highlight dot.',
      grid: [
        '................',
        '................',
        '...BEBEBEBEBEB..',
        '..BEBEBEBEBEBEB.',
        '..BEBEBEBEBEBEB.',
        '..BEBEBEBEBBEBB.',
        '..BEBEBEBEBEBEB.',
        '..BEBEBEBEBBEBB.',
        '..WBEBEBEBBEBEW.',
        '...WBEBEBEBEBW..',
        '....WBEBEBEW....',
        '...HHHHHHHHHHH..',
        '..HHHHHHHHHHHHH.',
        '...TTTTTTTTTTT..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'blueberry', role: 'body' },
        E: { name: 'berry_highlight', role: 'eye' },
        W: { name: 'bowl_rim', role: 'head' },
        H: { name: 'bowl_side', role: 'arm' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. ONION RINGS ────────────────────────────────────────
    {
      id: 'onion_rings_16',
      description: 'Stack of three golden fried onion rings with crispy breading.',
      grid: [
        '................',
        '................',
        '...HHHHHHHHHH...',
        '..HH........HHH.',
        '..HH.FFFFFF.HH..',
        '..HH.FFFFFF.HH..',
        '...HHHHHHHHHH...',
        '...BBBBBBBBBB...',
        '..BB........BBB.',
        '..BB.FFFFFF.BB..',
        '..BB.FFFFFF.BB..',
        '...BBBBBBBBBB...',
        '...AAAAAAAAAA...',
        '..AA........AA..',
        '...AAAAAAAAAA...',
        '................',
      ],
      chars: {
        H: { name: 'ring_top', role: 'head' },
        B: { name: 'ring_mid', role: 'body' },
        A: { name: 'ring_bot', role: 'arm' },
        F: { name: 'onion_center', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 20. GARLIC BREAD ───────────────────────────────────────
    {
      id: 'garlic_bread_16',
      description: 'Toasted garlic bread slices with herb butter, golden crust and green herb specks.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHHH.',
        '.HHHHHHHHHHHHHH.',
        '.HHGHHGHHHGHHHH.',
        '.HHHHHHHHHHHHHH.',
        '.BBBBBBBBBBBBBH.',
        '.BBBGBBBBBGBBBB.',
        '.BBBBBBBBBBBBBH.',
        '.BBBBBBBBBBBBBH.',
        '.CCCCCCCCCCCCCB.',
        '.CCCCCCCCCCCCCC.',
        '..CCCCCCCCCCCC..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_crust', role: 'head' },
        G: { name: 'herb_specks', role: 'accessory' },
        B: { name: 'bread_body', role: 'body' },
        C: { name: 'bottom_crust', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
