/**
 * Food batch 5 — 12 new food/drink templates.
 * Covers: grape juice, pita bread, tiramisu, fruit tart, iced tea,
 *         waffle cone, soft pretzel, rice ball, candy cane,
 *         gingerbread man, popsicle, fortune cookie.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'FOOD_BATCH5_TEMPLATES', schemes: 'FOOD_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ─── 1. GRAPE JUICE ─────────────────────────────────────────
    {
      id: 'grape_juice_16',
      description: 'Tall glass of deep purple grape juice with a highlight stripe and foam rim.',
      grid: [
        '................',
        '.....GGGGGG.....',
        '.....GGGGGG.....',
        '.....GGGGGG.....',
        '....GHHHHHHHG...',
        '....GPPPPPPGG...',
        '....GPPPPPPGG...',
        '....GPEHPPPPG...',
        '....GPPPPPPGG...',
        '....GPPPPPPGG...',
        '....GPPPPPPGG...',
        '....GPPPPPPGG...',
        '....GPPPPPPGG...',
        '.....GGGGGGGG...',
        '......BBBBBB....',
        '................',
      ],
      chars: {
        G: { name: 'glass_wall',   role: 'body' },
        H: { name: 'foam_rim',     role: 'head' },
        P: { name: 'juice',        role: 'arm' },
        E: { name: 'juice_shine',  role: 'eye' },
        B: { name: 'glass_base',   role: 'boot' },
      },
      colors: {
        body:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#597dce', base: '#8595a1',  highlight: '#d2aa99' },
        arm:   { shadow: '#442434', base: '#30346d',  highlight: '#597dce' },
        eye:   { shadow: '#597dce', base: '#6dc2ca',  highlight: '#deeed6' },
        boot:  { shadow: '#757161', base: '#8595a1',  highlight: '#d2aa99' },
      },
    },

    // ─── 2. PITA BREAD ──────────────────────────────────────────
    {
      id: 'pita_bread_16',
      description: 'Round golden pita bread viewed from above, with char spots and pocket shadow.',
      grid: [
        '................',
        '................',
        '.....HHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHXHHHXHHH..',
        '..HHHHHHHHHHHH..',
        '.HHHHHBBBBHHHH..',
        '.HHHHHBBBBHHHH..',
        '.HHHHHBBBBHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHXHHHXHHH..',
        '...HHHHHHHHHH...',
        '.....HHHHHHH....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'pita_surface', role: 'head' },
        X: { name: 'char_spots',   role: 'accessory' },
        B: { name: 'pocket_shadow', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 3. TIRAMISU SLICE ──────────────────────────────────────
    {
      id: 'tiramisu_16',
      description: 'Slice of tiramisu: cocoa-dusted top, mascarpone layer, espresso ladyfinger base.',
      grid: [
        '................',
        '................',
        '.....CCCCCCCC...',
        '....CCCCCCCCCC..',
        '....CXCXCCXCCC..',
        '....CCCCCCCCCC..',
        '....MMMMMMMMMM..',
        '....MMMMMMMMMM..',
        '....MMEMMMEMMM..',
        '....MMMMMMMMMM..',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '.....TTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cocoa_dust',      role: 'head' },
        X: { name: 'cocoa_spots',     role: 'accessory' },
        M: { name: 'mascarpone',      role: 'body' },
        E: { name: 'cream_highlight', role: 'eye' },
        B: { name: 'ladyfinger',      role: 'arm' },
        T: { name: 'plate',           role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. FRUIT TART ──────────────────────────────────────────
    {
      id: 'fruit_tart_16',
      description: 'Mini fruit tart: golden pastry shell, cream filling, mixed berries on top.',
      grid: [
        '................',
        '................',
        '....RSBRSRSB....',
        '...RSBRSRSBRSB..',
        '...SBRSRSRSBRS..',
        '...RSBMMMMRSBR..',
        '...SBMMMMMMSBS..',
        '...RBMMMMMMSRB..',
        '...SBMMMMMMRSB..',
        '....HHHHHHHH....',
        '....HHHHHHHH....',
        '....HHHHHHHH....',
        '.....TTTTTT.....',
        '......PPPP......',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'red_berry',   role: 'head' },
        S: { name: 'shine_dot',   role: 'eye' },
        B: { name: 'blue_berry',  role: 'accessory' },
        M: { name: 'cream_fill',  role: 'body' },
        H: { name: 'pastry_wall', role: 'arm' },
        T: { name: 'crust_base',  role: 'boot' },
        P: { name: 'plate_rim',   role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 5. ICED TEA ────────────────────────────────────────────
    {
      id: 'iced_tea_16',
      description: 'Tall glass of amber iced tea with ice cubes, lemon slice wedge, and straw.',
      grid: [
        '........SS......',
        '........SS......',
        '....GIIIIIG.....',
        '....GTTTTTG.....',
        '....GTTTTTG.....',
        '....GIITTTG.....',
        '....GTTTTTG.....',
        '....GTTTLTG.....',
        '....GTTTTTG.....',
        '....GIITTTG.....',
        '....GTTTTTG.....',
        '....GTTTTTG.....',
        '....GTTTTTG.....',
        '.....GGGGG......',
        '......BBB.......',
        '................',
      ],
      chars: {
        S: { name: 'straw',       role: 'accessory' },
        G: { name: 'glass_wall',  role: 'body' },
        I: { name: 'ice_cube',    role: 'head' },
        T: { name: 'tea_liquid',  role: 'arm' },
        L: { name: 'lemon_slice', role: 'eye' },
        B: { name: 'glass_base',  role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 6. WAFFLE CONE ─────────────────────────────────────────
    {
      id: 'waffle_cone_16',
      description: 'Ice cream waffle cone with two scoops — vanilla and strawberry — and a drip.',
      grid: [
        '....SSSSVVVV....',
        '...SSSSVVVVVV...',
        '...SSSSEVVVVV...',
        '....SSSSSSSS....',
        '.....DDDDDD.....',
        '.....DDDDDD.....',
        '......CCCC......',
        '.....CWWWWC.....',
        '....CWWWWWWC....',
        '....CWWCWWWC....',
        '.....CWWWWC.....',
        '......CCCC......',
        '.......CC.......',
        '........C.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'strawberry_scoop', role: 'head' },
        V: { name: 'vanilla_scoop',    role: 'accessory' },
        E: { name: 'scoop_shine',      role: 'eye' },
        D: { name: 'drip',             role: 'belt' },
        C: { name: 'cone_shell',       role: 'body' },
        W: { name: 'waffle_pattern',   role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. SOFT PRETZEL ────────────────────────────────────────
    {
      id: 'pretzel_soft_16',
      description: 'Large soft pretzel with salt crystals, shiny golden-brown baked crust.',
      grid: [
        '................',
        '...HHHHH.HHHHH..',
        '..HH...HHH...HH.',
        '..HH..HHHHH..HH.',
        '..HH.HH...HH.HH.',
        '...HHHHH.HHHHH..',
        '....HHHHHHHHHH..',
        '...HHHHXHXHHHH..',
        '..HHHHHHHHHHHHH.',
        '..HHHHXHXHHHHH..',
        '...HHHHHHHHHHH..',
        '....HHHHHHHHHH..',
        '.....HHHHHHH....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dough',        role: 'head' },
        X: { name: 'salt_crystal', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 8. RICE BALL ───────────────────────────────────────────
    {
      id: 'rice_ball_16',
      description: 'Japanese onigiri rice ball — triangular shape, nori seaweed band, sesame specks.',
      grid: [
        '................',
        '........R.......',
        '.......RRR......',
        '......RRRRR.....',
        '.....RRRRRRR....',
        '....RRRRRRRRRR..',
        '....RRRRRRRRRR..',
        '....RRXRRXRRRR..',
        '....RRRRRRRRRR..',
        '....NNNNNNNNNN..',
        '....NNNNNNNNNN..',
        '....RRRRRRRRRR..',
        '....RRRRRRRRRR..',
        '....RRRRRRRRRR..',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rice',        role: 'head' },
        X: { name: 'sesame',      role: 'eye' },
        N: { name: 'nori_strip',  role: 'body' },
      },
      colors: {
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 9. CANDY CANE ──────────────────────────────────────────
    {
      id: 'candy_cane_16',
      description: 'Classic red and white striped candy cane with curved hook and glossy shine.',
      grid: [
        '................',
        '.....RRR........',
        '....RWRWRR......',
        '...RR.RWRWRR....',
        '..RR...RWRWRR...',
        '..RR....RWRWR...',
        '..RR.....RWRW...',
        '...RR....RWRW...',
        '....RRRRRWRWW...',
        '.....RRRRWRWW...',
        '......RRRWRWW...',
        '.......RRWRWW...',
        '........RRWW....',
        '.........RR.....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'red_stripe',   role: 'head' },
        W: { name: 'white_stripe', role: 'body' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 10. GINGERBREAD MAN ────────────────────────────────────
    {
      id: 'gingerbread_man_16',
      description: 'Gingerbread cookie man with icing buttons, eyes, smile, and scalloped outline.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHEEHEHH....',
        '....HHHHHHHH....',
        '....HHHHHHHH....',
        '.AHHHHHHHHHHHA..',
        '.AHHHHHHHHHHHA..',
        '..AHHBHBHBHHHA..',
        '...HHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '..HH.......HH...',
        '..HH.......HH...',
        '..HH.......HH...',
        '...H.......H....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cookie_body', role: 'head' },
        E: { name: 'icing_face',  role: 'eye' },
        A: { name: 'arm_cookie',  role: 'arm' },
        B: { name: 'icing_button', role: 'body' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 11. POPSICLE ───────────────────────────────────────────
    {
      id: 'popsicle_16',
      description: 'Fruit popsicle on a stick — two-tone mango/strawberry gradient with a drip.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '...HHHEHHHHHH...',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...BBBBBBBBBBH..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBBH..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....SSSSSS.....',
        '.......SS.......',
        '.......SS.......',
        '................',
      ],
      chars: {
        H: { name: 'top_flavor',   role: 'head' },
        E: { name: 'ice_shine',    role: 'eye' },
        B: { name: 'bottom_flavor', role: 'body' },
        S: { name: 'stick',        role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 12. FORTUNE COOKIE ─────────────────────────────────────
    {
      id: 'fortune_cookie_16',
      description: 'Fortune cookie cracked open with a strip of white paper fortune sticking out.',
      grid: [
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '...HHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '...HHHHHHHHHHHH.',
        '....WWWWWWWWWW..',
        '.....WWWWWWWWW..',
        '....HHHHHHHHHH..',
        '....HHHHHHHHHHH.',
        '....HHHHHHHHHH..',
        '.....HHHHHHHH...',
        '......HHHHHH....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cookie_body',  role: 'head' },
        W: { name: 'paper_fortune', role: 'body' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
