/**
 * Food batch 1 — 20 new food/consumable templates.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'FOOD_BATCH1_TEMPLATES', schemes: 'FOOD_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. APPLE ───────────────────────────────────────────────
    {
      id: 'apple_16',
      description: 'Red apple with leaf stem, classic RPG healing item.',
      grid: [
        '................',
        '........XX......',
        '.......XXX......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '...HHHHEHHHHH...',
        '...HHHHHHHHHH...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'stem_leaf', role: 'accessory' },
        H: { name: 'top_half', role: 'head' },
        E: { name: 'shine', role: 'eye' },
        B: { name: 'bottom_half', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 2. BREAD LOAF ──────────────────────────────────────────
    {
      id: 'bread_loaf_16',
      description: 'Fresh bread loaf with golden crust, score marks.',
      grid: [
        '................',
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHXHXHHHH...',
        '...HHHHHHHHHH...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...TTTTTTTTTT...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'crust_top', role: 'head' },
        X: { name: 'score_marks', role: 'accessory' },
        B: { name: 'bread_body', role: 'body' },
        T: { name: 'bottom', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. CHEESE WHEEL ────────────────────────────────────────
    {
      id: 'cheese_wheel_16',
      description: 'Cheese wheel wedge with holes, golden rind.',
      grid: [
        '................',
        '................',
        '................',
        'HHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHH',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBXBBBXBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBXBBBBBBBBBBBB',
        'BBBBBBBBBXBBBBBB',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'rind', role: 'head' },
        B: { name: 'cheese', role: 'body' },
        X: { name: 'holes', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. MEAT LEG ────────────────────────────────────────────
    {
      id: 'meat_leg_16',
      description: 'Roasted meat leg/drumstick with bone handle.',
      grid: [
        '................',
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHH....',
        '...HHHHEHHHHH...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '.....BBBBB......',
        '......AAAA......',
        '.......AAA......',
        '.......AATT.....',
        '........TT......',
        '................',
      ],
      chars: {
        H: { name: 'meat_top', role: 'head' },
        E: { name: 'glaze_shine', role: 'eye' },
        B: { name: 'meat_body', role: 'body' },
        A: { name: 'bone', role: 'arm' },
        T: { name: 'bone_tip', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 5. PIE ─────────────────────────────────────────────────
    {
      id: 'pie_16',
      description: 'Baked pie with lattice top crust, fruit filling visible.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHHH...',
        '..HXHXHXHXHXHH..',
        '..HHXHXHXHXHHH..',
        '..HXHXHXHXHXHH..',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '...TTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lattice_crust', role: 'head' },
        X: { name: 'filling', role: 'accessory' },
        B: { name: 'pie_sides', role: 'body' },
        T: { name: 'bottom_crust', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 6. FISH ────────────────────────────────────────────────
    {
      id: 'fish_16',
      description: 'Whole fish side-view — silvery scales, fins, eye.',
      grid: [
        '................',
        '................',
        '................',
        '......XX........',
        '.....HHHHH......',
        '....HHHHHHHH....',
        '..AAHHHEHHHHH...',
        '.AAAHHHHHHHHHX..',
        '..AAHHHHHHHHHX..',
        '....HHHHHHHH....',
        '.....HHHHH......',
        '......XX........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'body_scales', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        A: { name: 'tail', role: 'arm' },
        X: { name: 'fins', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        arm:       { shadow: '#597dce', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 7. CAKE SLICE ──────────────────────────────────────────
    {
      id: 'cake_slice_16',
      description: 'Slice of layered cake with frosting and cherry on top.',
      grid: [
        '................',
        '..........XX....',
        '.........XAAX...',
        '..........XX....',
        '.......HHHHH....',
        '......HHHHHH....',
        '.....HHHHHHH....',
        '....HHHHHHHH....',
        '...BBBBBBBBB....',
        '..GGBBBBBBBB....',
        '..GGBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..GGBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..TTTTTTTTTT....',
        '................',
      ],
      chars: {
        X: { name: 'cherry_stem', role: 'accessory' },
        A: { name: 'cherry', role: 'arm' },
        H: { name: 'frosting', role: 'head' },
        B: { name: 'sponge', role: 'body' },
        G: { name: 'cream_layers', role: 'belt' },
        T: { name: 'plate', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 8. MUSHROOM ────────────────────────────────────────────
    {
      id: 'mushroom_food_16',
      description: 'Edible mushroom with spotted cap.',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '....HHXXXXHH....',
        '...HHHHHHHHHH...',
        '...HXHHHHHHXH...',
        '....HHHHHHHH....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....TTTTTTTT....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cap', role: 'head' },
        X: { name: 'spots', role: 'accessory' },
        B: { name: 'stem', role: 'body' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. GRAPES ──────────────────────────────────────────────
    {
      id: 'grapes_16',
      description: 'Bunch of grapes with vine leaf, clustered berries.',
      grid: [
        '................',
        '.......XXX......',
        '......XXXXX.....',
        '.......XX.......',
        '.......AA.......',
        '......BBBB......',
        '.....BBEBBBB....',
        '....BBBBBBBBB...',
        '....BBBEBBEBB...',
        '....BBBBBBBBB...',
        '.....BBEBBBB....',
        '......BBBBB.....',
        '.......BBB......',
        '........B.......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'leaf', role: 'accessory' },
        A: { name: 'stem', role: 'arm' },
        B: { name: 'berries', role: 'body' },
        E: { name: 'highlights', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 10. EGG ────────────────────────────────────────────────
    {
      id: 'egg_16',
      description: 'Single egg — smooth oval, subtle shine.',
      grid: [
        '................',
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHEHHHHH....',
        '....HHHHHHHH....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_half', role: 'head' },
        E: { name: 'shine', role: 'eye' },
        B: { name: 'bottom_half', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 11. SOUP BOWL ──────────────────────────────────────────
    {
      id: 'soup_bowl_16',
      description: 'Bowl of hot soup with steam rising, chunks visible.',
      grid: [
        '.....X..X.......',
        '....X..X........',
        '................',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHXHHEHHXHH...',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'steam_chunks', role: 'accessory' },
        H: { name: 'soup', role: 'head' },
        E: { name: 'shine', role: 'eye' },
        B: { name: 'bowl', role: 'body' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 12. WINE BOTTLE ────────────────────────────────────────
    {
      id: 'wine_bottle_16',
      description: 'Wine bottle with cork, label, dark glass.',
      grid: [
        '................',
        '.......XX.......',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '......HHHH......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BXXXXB.....',
        '.....BXXXXB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        X: { name: 'label', role: 'accessory' },
        H: { name: 'neck_cork', role: 'head' },
        B: { name: 'bottle', role: 'body' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 13. CARROT ─────────────────────────────────────────────
    {
      id: 'carrot_16',
      description: 'Fresh carrot with leafy green top.',
      grid: [
        '................',
        '.....XXXXXX.....',
        '....XXXXXXXX....',
        '.....XXXXXX.....',
        '......HHHH......',
        '.....HHHHHH.....',
        '.....HHHHHH.....',
        '....HHHHEHHH....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BBBB......',
        '.......BB.......',
        '.......BB.......',
        '................',
      ],
      chars: {
        X: { name: 'leaves', role: 'accessory' },
        H: { name: 'top_thick', role: 'head' },
        E: { name: 'shine', role: 'eye' },
        B: { name: 'body_root', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. CANDY ──────────────────────────────────────────────
    {
      id: 'candy_16',
      description: 'Wrapped candy/sweet with twisted wrapper ends.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..XX........XX..',
        '.XXXHHHHHHHHXXX.',
        '.XXXHHHHHHHHXXX.',
        '.XXXXHHEHHXXXXX.',
        '.XXXXHHHHHHXXXX.',
        '.XXXBBBBBBBBXXX.',
        '.XXXBBBBBBBBXXX.',
        '..XX........XX..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'wrapper', role: 'accessory' },
        H: { name: 'candy_top', role: 'head' },
        E: { name: 'shine', role: 'eye' },
        B: { name: 'candy_bottom', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. PUMPKIN ────────────────────────────────────────────
    {
      id: 'pumpkin_16',
      description: 'Round pumpkin with stem and ridges.',
      grid: [
        '................',
        '................',
        '.......XX.......',
        '......HHHH......',
        '....HHHHHHHH....',
        '...HHHXHHXHHH...',
        '..HHHHXHHXHHHH..',
        '..BBBBXBBXBBBB..',
        '..BBBBXBBXBBBB..',
        '..BBBBXBBXBBBB..',
        '..BBBBXBBXBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'stem_ridges', role: 'accessory' },
        H: { name: 'top', role: 'head' },
        B: { name: 'body', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#854c30', highlight: '#6daa2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. HONEY JAR ──────────────────────────────────────────
    {
      id: 'honey_jar_16',
      description: 'Honey jar with cloth lid cover, drip, label.',
      grid: [
        '................',
        '....XXXXXXXX....',
        '...XXXXXXXXXX...',
        '....XXXXXXXX....',
        '.....GGGGGG.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBHHHBB....',
        '....BBBHHHBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'cloth_lid', role: 'accessory' },
        G: { name: 'string_tie', role: 'belt' },
        B: { name: 'jar_glass', role: 'body' },
        H: { name: 'label', role: 'head' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. WATERMELON ─────────────────────────────────────────
    {
      id: 'watermelon_16',
      description: 'Watermelon slice with red flesh, seeds, green rind.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        'HHHHHHHHHHHHHHHH',
        'HHHHHHHHHHHHHHHH',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBB..',
        '..BXBBXBBXBBXB..',
        '...BBBBBBBBBB...',
        '...BXBBXBBXBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'rind', role: 'head' },
        B: { name: 'flesh', role: 'body' },
        X: { name: 'seeds', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 18. PRETZEL ────────────────────────────────────────────
    {
      id: 'pretzel_16',
      description: 'Twisted pretzel with salt crystals, golden brown baked.',
      grid: [
        '................',
        '................',
        '..HHHH...HHHH...',
        '.HH..HHHHHH..HH.',
        '.HH...HHHH...HH.',
        '.HH.HHHHHHH..HH.',
        '..HHHHXHXHHHH...',
        '...HHHHHHHHHH...',
        '..HHHHXHXHHHH...',
        '.HH.HHHHHHH..HH.',
        '.HH...HHHH...HH.',
        '.HH..HHHHHH..HH.',
        '..HHHH...HHHH...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dough', role: 'head' },
        X: { name: 'salt', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 19. MILK BOTTLE ────────────────────────────────────────
    {
      id: 'milk_bottle_16',
      description: 'Glass milk bottle with cap, white liquid.',
      grid: [
        '................',
        '......XXXX......',
        '.......HH.......',
        '.......HH.......',
        '......HHHH......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBEEBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'cap', role: 'accessory' },
        H: { name: 'neck', role: 'head' },
        B: { name: 'bottle', role: 'body' },
        E: { name: 'shine', role: 'eye' },
        T: { name: 'base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 20. DONUT ──────────────────────────────────────────────
    {
      id: 'donut_16',
      description: 'Glazed donut with frosting and sprinkles, torus shape.',
      grid: [
        '................',
        '................',
        '................',
        '.....HHHHHH.....',
        '...HHHHHHHHHH...',
        '..HHXHHHHHXHH...',
        '..HHHHH.HHHHH...',
        '.HHHH.....HHHHH.',
        '.BBB.......BBB..',
        '.BBBB...BBBBB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '.....BBBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frosting', role: 'head' },
        X: { name: 'sprinkles', role: 'accessory' },
        B: { name: 'dough', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
