/**
 * Fruits batch 2 — 20 exotic/tropical fruit templates for farming simulator bundles.
 * Covers: dragon fruit, starfruit, papaya, lychee, guava, persimmon,
 *         rambutan, jackfruit chunk, kumquat, blood orange, tangerine,
 *         cantaloupe slice, honeydew slice, gooseberry, cranberry bunch,
 *         date fruit, tamarind, cactus fruit, plantain, durian.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'FRUITS_BATCH2_TEMPLATES', schemes: 'FRUITS_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. DRAGON FRUIT ────────────────────────────────────────
    {
      id: 'dragon_fruit_farm_16',
      description: 'Pink dragon fruit with scale protrusions, cut showing white flesh and seeds.',
      grid: [
        '......TTTT......',
        '.....TPPPPT.....',
        '....PPPPPPPP....',
        '...TPPFFFFPPT...',
        '..TPPFFFFFFPPT..',
        '..PPFFFSFFSFPP..',
        '.TPPFFFHFFSFPPT.',
        '..PPFFSFFFSFPP..',
        '..TPPFFFFFFPPT..',
        '...TPPFFFFPPT...',
        '....PPPPPPPP....',
        '.....PPPPPP.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'scale_tip', role: 'accessory' },
        P: { name: 'pink_skin', role: 'body' },
        F: { name: 'white_flesh', role: 'head' },
        S: { name: 'seeds', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 2. STARFRUIT ───────────────────────────────────────────
    {
      id: 'starfruit_farm_16',
      description: 'Yellow star-shaped cross section of starfruit with five points.',
      grid: [
        '................',
        '.......BB.......',
        '......BBBB......',
        '.....BBHHBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        'BBBBBBBBBBBBBBB.',
        '.BBBRRBBBBRRBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBBB....BBBB..',
        '..BBB......BBB..',
        '.BBB........BBB.',
        '.BB..........BB.',
        '................',
      ],
      chars: {
        B: { name: 'flesh', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'ridge', role: 'head' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 3. PAPAYA HALF ─────────────────────────────────────────
    {
      id: 'papaya_half_16',
      description: 'Elongated oval papaya half showing cavity with dark round seeds.',
      grid: [
        '................',
        '.......GGG......',
        '......GGGGG.....',
        '.....GGBBBGG....',
        '....GGBBBBBGG...',
        '...GGBBBBBBGGG..',
        '...GBBBBSSBGGG..',
        '..GGBBBHSSSBBG..',
        '..GGBBBBSSSBBGG.',
        '..GGBBBSSSBBBGG.',
        '...GGBBBBBBGGG..',
        '....GGBBBGGG....',
        '.....GGGGGGG....',
        '......AAAAA.....',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'green_skin', role: 'accessory' },
        B: { name: 'orange_flesh', role: 'body' },
        S: { name: 'seeds', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 4. LYCHEE ──────────────────────────────────────────────
    {
      id: 'lychee_farm_16',
      description: 'Red/pink rough-skinned lychee with white inside peeking out.',
      grid: [
        '................',
        '........SS......',
        '.......SLLS.....',
        '......RRRR......',
        '.....RRRRRR.....',
        '....RRRRWWRR....',
        '....RRRWWWRR....',
        '...RRRRWHWWRR...',
        '...RRRWWWWRRR...',
        '...RRRRWWRRRR...',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        R: { name: 'rough_skin', role: 'body' },
        W: { name: 'white_flesh', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 5. GUAVA ───────────────────────────────────────────────
    {
      id: 'guava_farm_16',
      description: 'Wide oval guava cut in half showing pink interior flesh.',
      grid: [
        '................',
        '................',
        '.....GGGGGG.....',
        '...GGGGGGGGGG...',
        '..GGGGPPPPGGGG..',
        '.GGGGGPPPPPGGGG.',
        '.GGGGPPPHPPGGGG.',
        '.GGGGGPPPPPGGGG.',
        '.GGGGGGPPGGGGG..',
        '..GGGGGGGGGGG...',
        '...GGGGGGGGG....',
        '....GGGGGGGG....',
        '.....AAAAAA.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'green_skin', role: 'body' },
        P: { name: 'pink_flesh', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 6. PERSIMMON ───────────────────────────────────────────
    {
      id: 'persimmon_farm_16',
      description: 'Wide flat persimmon with large spreading green leaf calyx.',
      grid: [
        '................',
        '...LLLLLLLLLL...',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '....BBBBBBBB....',
        '...BBBBHBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf_calyx', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. RAMBUTAN ────────────────────────────────────────────
    {
      id: 'rambutan_farm_16',
      description: 'Red hairy rambutan fruit with spiky tendrils.',
      grid: [
        '......H.HH......',
        '.....H.HH.H.....',
        '....H.BBBB.H....',
        '...H.BBBBBB.H...',
        '..H.BBBBBBBB.H..',
        '..HBBBBBSBBBBH..',
        '.H.BBBBBBBBBB.H.',
        '.HBBBBBBBBBBBBH.',
        '.H.BBBBBBBBBB.H.',
        '..HBBBBBBBBBHH..',
        '..H.BBBBBBBB.H..',
        '...H.BBBBBB.H...',
        '....H.BBBB.H....',
        '.....HAAAAH.....',
        '......HHHH......',
        '................',
      ],
      chars: {
        H: { name: 'hair_tendril', role: 'accessory' },
        B: { name: 'red_skin', role: 'body' },
        S: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 8. JACKFRUIT CHUNK ─────────────────────────────────────
    {
      id: 'jackfruit_chunk_16',
      description: 'Yellow jackfruit segment/pod with visible seed.',
      grid: [
        '................',
        '................',
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBHBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBSSBBBB...',
        '...BBBSSSSBBBB..',
        '....BBBSSBBBB...',
        '.....BBBBBBB....',
        '......BBBBB.....',
        '.......AAA......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'flesh', role: 'body' },
        S: { name: 'seed', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. KUMQUAT ─────────────────────────────────────────────
    {
      id: 'kumquat_farm_16',
      description: 'Tiny orange oval kumquat with small leaf at top.',
      grid: [
        '................',
        '................',
        '................',
        '.......LL.......',
        '......SLLS......',
        '.......BB.......',
        '......BBBB......',
        '.....BBBHBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......AAAA......',
        '.......AA.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. BLOOD ORANGE ───────────────────────────────────────
    {
      id: 'blood_orange_16',
      description: 'Orange half showing deep red interior with segment lines.',
      grid: [
        '................',
        '................',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '...RRFFFFFFRR...',
        '..RRFFSFFSFFRR..',
        '..RRFFSFFSFFRR..',
        '..RRFFHFFHFFRR..',
        '..RRFFSFFSFFRR..',
        '..RRFFSFFSFFRR..',
        '...RRFFFFFFRR...',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rind', role: 'arm' },
        F: { name: 'red_flesh', role: 'body' },
        S: { name: 'segment_wall', role: 'head' },
        H: { name: 'shine', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 11. TANGERINE ──────────────────────────────────────────
    {
      id: 'tangerine_farm_16',
      description: 'Small orange tangerine with green leaf at stem.',
      grid: [
        '................',
        '................',
        '.......LL.......',
        '......SLLS......',
        '.......SS.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. CANTALOUPE SLICE ───────────────────────────────────
    {
      id: 'cantaloupe_slice_16',
      description: 'Cantaloupe wedge with green rind and orange flesh.',
      grid: [
        '................',
        '................',
        '................',
        '.......BB.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBHBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.RRRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRRR.',
        '.GGGGGGGGGGGGGG.',
        '.GGGGGGGGGGGGGG.',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'orange_flesh', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'pale_rind', role: 'head' },
        G: { name: 'green_rind', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. HONEYDEW SLICE ─────────────────────────────────────
    {
      id: 'honeydew_slice_16',
      description: 'Wide crescent honeydew slice with pale green flesh and rind.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBB.',
        'BBBBBBBHBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBB..',
        '..RRRRRRRRRRRR..',
        '..GGGGGGGGGGGG..',
        '...GGGGGGGGGG...',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pale_flesh', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'white_rind', role: 'head' },
        G: { name: 'green_rind', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#6daa2c', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. GOOSEBERRY ─────────────────────────────────────────
    {
      id: 'gooseberry_farm_16',
      description: 'Small green gooseberry with papery husk leaves.',
      grid: [
        '................',
        '................',
        '....LL....LL....',
        '.....LL..LL.....',
        '......LLLL......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBHBBB.....',
        '....BBBBBBBB....',
        '....BBBXBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'papery_husk', role: 'accessory' },
        B: { name: 'berry_skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        X: { name: 'stripe', role: 'head' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 15. CRANBERRY BUNCH ────────────────────────────────────
    {
      id: 'cranberry_bunch_16',
      description: 'Cluster of small red cranberries with tiny stems.',
      grid: [
        '................',
        '......SS.SS.....',
        '.....SS.SS.S....',
        '....SSSS.SSS....',
        '....BBBB.BBB....',
        '...BBBHBBBBHB...',
        '...BBBBBBBBBB...',
        '..BBBBB.BBBBBB..',
        '..BHBBB.BBBHBB..',
        '..BBBBB.BBBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBB.BBBBB...',
        '....BBB.BBBB....',
        '.....AA.AAA.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stems', role: 'arm' },
        B: { name: 'berry', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 16. DATE FRUIT ─────────────────────────────────────────
    {
      id: 'date_fruit_16',
      description: 'Brown dried date fruit, oblong and wrinkled.',
      grid: [
        '................',
        '................',
        '................',
        '.......SS.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBHBB.....',
        '....BBBBBBBB....',
        '....BWBBBBWB....',
        '....BBBBBBBB....',
        '....BBWBBBWB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_nub', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        W: { name: 'wrinkle', role: 'head' },
        A: { name: 'base_tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 17. TAMARIND ───────────────────────────────────────────
    {
      id: 'tamarind_farm_16',
      description: 'Brown tamarind pod, curved bean-like shape.',
      grid: [
        '................',
        '................',
        '................',
        '....SS..........',
        '...SSBBB........',
        '..SSBBBBB.......',
        '..BBBBBBBBB.....',
        '..BBBHBBBBBBB...',
        '...BBBBBBBBBBB..',
        '....BBBBBBBBBBB.',
        '.....BBBBBBBBBB.',
        '......BBBBBBB...',
        '.......AAAAA....',
        '........AAA.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_end', role: 'arm' },
        B: { name: 'pod_shell', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 18. CACTUS FRUIT ───────────────────────────────────────
    {
      id: 'cactus_fruit_farm_16',
      description: 'Pink/magenta prickly pear cactus fruit with tiny spines.',
      grid: [
        '................',
        '................',
        '.......TT.......',
        '......BBBB......',
        '.....TBBBBT.....',
        '....BBBBBBBBT...',
        '...TBBBBHBBBB...',
        '...BBBBBBBBBBT..',
        '..TBBBBBBBBBB...',
        '...BBBBBBBBBT...',
        '...TBBBBBBBB....',
        '....BBBBBBB.....',
        '.....BBBBB......',
        '......AAA.......',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'tiny_spines', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 19. PLANTAIN ───────────────────────────────────────────
    {
      id: 'plantain_farm_16',
      description: 'Green plantain, banana-like shape but greener and straighter.',
      grid: [
        '................',
        '............SS..',
        '..........SSS...',
        '.........BBB....',
        '........BBBB....',
        '.......BBBBB....',
        '......BBBBBB....',
        '.....BBBHBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBB....',
        '..BBBBBBBBB.....',
        '..BBBBBBBB......',
        '..AABBBB........',
        '...AAA..........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#854c30', highlight: '#854c30' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 20. DURIAN ─────────────────────────────────────────────
    {
      id: 'durian_farm_16',
      description: 'Spiky yellow-green durian fruit, large and intimidating.',
      grid: [
        '.......TT.......',
        '......TTTT......',
        '....TTTTTTTT....',
        '...TTBBBBBBTT...',
        '..TTBBBBBBBBTT..',
        '..TBBBBHBBBBT...',
        '.TTBBBBBBBBBBTT.',
        '.TBBBBBBBBBBBT..',
        '.TTBBBBBBBBBBTT.',
        '..TBBBBBBBBBT...',
        '..TTBBBBBBBBTT..',
        '...TTBBBBBBTT...',
        '....TTBBBBTT....',
        '.....TTAATT.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        T: { name: 'spiky_shell', role: 'accessory' },
        B: { name: 'inner_skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
