/**
 * Fruits batch 1 — 20 common fruit templates for farming simulator bundles.
 * Covers: apple, pear, orange, lemon, lime, strawberry, cherry pair,
 *         grape bunch, watermelon slice, peach, plum, raspberry,
 *         kiwi half, pineapple, coconut half, pomegranate, fig,
 *         apricot, grapefruit half, passion fruit.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'FRUITS_BATCH1_TEMPLATES', schemes: 'FRUITS_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. APPLE ──────────────────────────────────────────────
    {
      id: 'apple_16',
      description: 'Round red apple with brown stem and green leaf.',
      grid: [
        '................',
        '.......SS.......',
        '......SLLS......',
        '......BBBB......',
        '....BBBBBBBB....',
        '...BBBHBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 2. PEAR ───────────────────────────────────────────────
    {
      id: 'pear_16',
      description: 'Green pear with narrow top, wide bottom, brown stem.',
      grid: [
        '................',
        '.......SS.......',
        '......SLLS......',
        '.......BB.......',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBHBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 3. ORANGE ─────────────────────────────────────────────
    {
      id: 'orange_fruit_16',
      description: 'Round orange with dimpled texture and small leaf on top.',
      grid: [
        '................',
        '........LL......',
        '.......SSS......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '...BBBXBBXBBB...',
        '...BBBBBBBBBB...',
        '...BBXBBBBXBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem_top', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        X: { name: 'dimple', role: 'head' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 4. LEMON ──────────────────────────────────────────────
    {
      id: 'lemon_16',
      description: 'Oval yellow lemon with pointed ends and small green leaf.',
      grid: [
        '................',
        '................',
        '.........LL.....',
        '........SS......',
        '.......BBBB.....',
        '......BBBBBB....',
        '.....BBBHBBBB...',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '.....BBBBBBBB...',
        '......BBBBBB....',
        '.......AABB.....',
        '........AA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. LIME ───────────────────────────────────────────────
    {
      id: 'lime_16',
      description: 'Green lime, slightly smaller than orange, glossy.',
      grid: [
        '................',
        '................',
        '.......SS.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_nub', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 6. STRAWBERRY ─────────────────────────────────────────
    {
      id: 'strawberry_farm_16',
      description: 'Red strawberry with seed dots and green leafy crown.',
      grid: [
        '................',
        '................',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '......BBBB......',
        '.....BSBBSB.....',
        '....BBBBBBBB....',
        '....BSBHBBSB....',
        '....BBBBBBBB....',
        '...BBBSBBSBBB...',
        '...BBBBBBBBBB...',
        '....BSBBBBSB....',
        '.....BBBBBB.....',
        '......ABBA......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf_crown', role: 'accessory' },
        B: { name: 'flesh', role: 'body' },
        S: { name: 'seeds', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#d04648', highlight: '#d04648' },
      },
    },

    // ─── 7. CHERRY PAIR ────────────────────────────────────────
    {
      id: 'cherry_pair_16',
      description: 'Two red cherries connected by stems with a single leaf.',
      grid: [
        '................',
        '.......LL.......',
        '......LSLL......',
        '.....SS..SS.....',
        '....SS....SS....',
        '...SS......SS...',
        '..SS........SS..',
        '..BB........BB..',
        '.BBBB......BBBB.',
        '.BHBBB....BBBHB.',
        '.BBBBB....BBBBB.',
        '.BBBBB....BBBBB.',
        '..BBB......BBB..',
        '..AAA......AAA..',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'cherry', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 8. GRAPE BUNCH ────────────────────────────────────────
    {
      id: 'grape_bunch_16',
      description: 'Purple grape cluster with vine stem at top.',
      grid: [
        '................',
        '.......SS.......',
        '......SLLS......',
        '.......SS.......',
        '......BBBB......',
        '.....BHBBHB.....',
        '....BBBBBBBB....',
        '....BHBBBBHB....',
        '...BBBBBBBBBB...',
        '...BHBBBBBBHB...',
        '....BBBBBBBB....',
        '.....BHBBHB.....',
        '......BBBB......',
        '.......BB.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'vine_stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        B: { name: 'grape_berry', role: 'body' },
        H: { name: 'grape_shine', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        eye:       { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 9. WATERMELON SLICE ───────────────────────────────────
    {
      id: 'watermelon_slice_16',
      description: 'Triangular slice with pink flesh, green rind, and dark seeds.',
      grid: [
        '................',
        '................',
        '................',
        '.......BB.......',
        '......BBBB......',
        '.....BBSBBB.....',
        '....BBBBBSBB....',
        '....BBSBBBBBB...',
        '...BBBBBHBSBBB..',
        '..BBBSBBBBBBBBB.',
        '..BBBBBBSBBBBB..',
        '.RRRRRRRRRRRRRRR',
        '.RRRRRRRRRRRRRRR',
        '.LLLLLLLLLLLLLLL',
        '.LLLLLLLLLLLLLLL',
        '................',
      ],
      chars: {
        B: { name: 'flesh', role: 'body' },
        S: { name: 'seeds', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'white_rind', role: 'arm' },
        L: { name: 'green_rind', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. PEACH ─────────────────────────────────────────────
    {
      id: 'peach_farm_16',
      description: 'Round pink-orange peach with slight crease and leaf.',
      grid: [
        '................',
        '........LL......',
        '.......SSS......',
        '......BBBB......',
        '.....BFBBBB.....',
        '....BBFBBBBB....',
        '....BBFHBBBBB...',
        '...BBBFBBBBBBB..',
        '...BBBFBBBBBBB..',
        '...BBBFBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        F: { name: 'crease', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d04648' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 11. PLUM ──────────────────────────────────────────────
    {
      id: 'plum_farm_16',
      description: 'Dark purple oval plum with highlight shine.',
      grid: [
        '................',
        '........SS......',
        '.......SLLS.....',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 12. RASPBERRY ─────────────────────────────────────────
    {
      id: 'raspberry_farm_16',
      description: 'Red raspberry made of small bumpy drupelets.',
      grid: [
        '................',
        '.......LL.......',
        '......SLLS......',
        '.......SS.......',
        '.....XBXBX......',
        '....BXBXBXB.....',
        '....XBHBXBX.....',
        '...BXBXBXBXB....',
        '...XBXBXBXBX....',
        '...BXBXBXBXB....',
        '....XBXBXBX.....',
        '.....BXBXB......',
        '......AAA.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'drupelet', role: 'body' },
        X: { name: 'drupelet_gap', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 13. KIWI HALF ─────────────────────────────────────────
    {
      id: 'kiwi_half_16',
      description: 'Cross-section showing green flesh, white core, black seed ring.',
      grid: [
        '................',
        '................',
        '......FFFF......',
        '.....FFFFFF.....',
        '....FFBBBBFF....',
        '...FFBBBBBBFF...',
        '..FFBBSSSSBBFF..',
        '..FFBSSWWSSBBF..',
        '..FFBSSWWSSBFF..',
        '..FFBBSSSSBBFF..',
        '...FFBBBBBBFF...',
        '....FFBBBBFF....',
        '.....FFFFFF.....',
        '......FFFF......',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'brown_skin', role: 'arm' },
        B: { name: 'green_flesh', role: 'body' },
        S: { name: 'seed_ring', role: 'head' },
        W: { name: 'white_core', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 14. PINEAPPLE ─────────────────────────────────────────
    {
      id: 'pineapple_farm_16',
      description: 'Tall pineapple with diamond texture skin and spiky crown.',
      grid: [
        '.....LLLLLL.....',
        '....LL.LL.LL....',
        '.....LLLLLL.....',
        '......BBBB......',
        '.....BXBBXB.....',
        '.....BBBBBB.....',
        '....BXBBBBXB....',
        '....BBBBHBBB....',
        '....BXBBBBXB....',
        '....BBBBBBBB....',
        '....BXBBBBXB....',
        '....BBBBBBBB....',
        '.....BXBBXB.....',
        '.....BBBBBB.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        L: { name: 'crown_leaves', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'diamond_groove', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 15. COCONUT HALF ──────────────────────────────────────
    {
      id: 'coconut_half_16',
      description: 'Brown coconut cut in half showing white interior.',
      grid: [
        '................',
        '................',
        '......FFFF......',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFWWWWWWFF...',
        '..FFFWWWWWWFFF..',
        '..FFFWWHWWWFFF..',
        '..FFFWWWWWWFFF..',
        '..FFFWWWWWWFFF..',
        '...FFWWWWWWFF...',
        '....FFFFFFFF....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'shell', role: 'body' },
        W: { name: 'white_meat', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 16. POMEGRANATE ───────────────────────────────────────
    {
      id: 'pomegranate_farm_16',
      description: 'Round red fruit with crown, showing seeds inside cut section.',
      grid: [
        '................',
        '.....LLLLLL.....',
        '......LLLL......',
        '......BBBB......',
        '.....BBBSSS.....',
        '....BBBSSSSSS...',
        '....BBBSHSSSSS..',
        '...BBBBSSSSSSSS.',
        '...BBBSSSSSSSS..',
        '...BBBSSSSSSSS..',
        '...BBBBSSSSSS...',
        '....BBBBSSSS....',
        '.....BBBBBB.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'crown', role: 'accessory' },
        B: { name: 'outer_skin', role: 'body' },
        S: { name: 'seed_flesh', role: 'head' },
        H: { name: 'seed_shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 17. FIG ───────────────────────────────────────────────
    {
      id: 'fig_farm_16',
      description: 'Teardrop-shaped purple fig with green stem.',
      grid: [
        '................',
        '........SS......',
        '.......SLLS.....',
        '.......BB.......',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBHBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        L: { name: 'leaf', role: 'accessory' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 18. APRICOT ───────────────────────────────────────────
    {
      id: 'apricot_farm_16',
      description: 'Small round orange fruit with crease line and leaf.',
      grid: [
        '................',
        '................',
        '.......LL.......',
        '......SLLS......',
        '.......SS.......',
        '......BBBB......',
        '.....BFBBBB.....',
        '....BBFHBBBB....',
        '....BBFBBBBB....',
        '....BBFBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        F: { name: 'crease', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. GRAPEFRUIT HALF ───────────────────────────────────
    {
      id: 'grapefruit_half_16',
      description: 'Large citrus half showing pink segments and yellow rind.',
      grid: [
        '................',
        '................',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '...RRSSSSSSSR...',
        '..RRSSSSSSSSRR..',
        '..RSSSBSSBSSRR..',
        '..RSSSBSSBSSRR..',
        '..RSSSHSSHSSRR..',
        '..RSSSBSSBSSRR..',
        '..RSSSBSSBSSRR..',
        '..RRSSSSSSSSRR..',
        '...RRSSSSSRRR...',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '................',
      ],
      chars: {
        R: { name: 'rind', role: 'arm' },
        S: { name: 'segment_flesh', role: 'body' },
        B: { name: 'segment_wall', role: 'head' },
        H: { name: 'segment_shine', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 20. PASSION FRUIT ─────────────────────────────────────
    {
      id: 'passion_fruit_farm_16',
      description: 'Round purple fruit with wrinkled skin, cut showing yellow interior.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBSSS.....',
        '....BBBSSSSS....',
        '....BBBSSSSSS...',
        '...BBBBSHSSSS...',
        '...BBBBSXSXSS...',
        '...BBBSSXSXSS...',
        '...BBBSSSSSSSS..',
        '....BBBSSSSS....',
        '.....BBBSSS.....',
        '......BBBB......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'outer_skin', role: 'body' },
        S: { name: 'yellow_pulp', role: 'head' },
        X: { name: 'seeds', role: 'arm' },
        H: { name: 'pulp_shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#597dce' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

  ],
};

export default batch;
