/**
 * Furniture & Props batch 1 — 20 interactive objects.
 * RPG chests, signs, switches, campfires, altars, sci-fi consoles.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'furniture',
  exportNames: { templates: 'FURNITURE_BATCH1_TEMPLATES', schemes: 'FURNITURE_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TREASURE CHEST — open ─────────────────────────────────
    {
      id: 'treasure_chest_open_16',
      description: 'Open treasure chest with gold coins visible inside.',
      grid: [
        '................',
        '................',
        '...HHHHHHHH.....',
        '..HHHHHHHHH.....',
        '..H.............',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBXXBBXXBB....',
        '..BGGGGGGGBB....',
        '..BGGGGGGGBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid', role: 'head' },
        B: { name: 'box', role: 'body' },
        X: { name: 'metal_bands', role: 'accessory' },
        G: { name: 'gold', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 2. WOODEN SIGN — directional ─────────────────────────────
    {
      id: 'wooden_sign_16',
      description: 'Wooden sign post pointing right with text area.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBBB....',
        '.....BBBBBBBX...',
        '.....BBBBBBB....',
        '........H.......',
        '........H.......',
        '........H.......',
        '........H.......',
        '........H.......',
        '........H.......',
        '.......HHH......',
        '......HHHHH.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'sign_board', role: 'body' },
        X: { name: 'arrow', role: 'accessory' },
        H: { name: 'post', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 3. CAMPFIRE — survival/RPG ───────────────────────────────
    {
      id: 'campfire_16',
      description: 'Crackling campfire with logs and flame.',
      grid: [
        '................',
        '................',
        '................',
        '.......FF.......',
        '......FFFF......',
        '.....FFFFFF.....',
        '.....FGGGFF.....',
        '....FFGGGGFF....',
        '....FFGGGGFF....',
        '.....FFFFFF.....',
        '...BBBBBBBBBB...',
        '..BBHHHHHHHBB...',
        '..BHHHHHHHHBB...',
        '..BBHHHHHHHBB...',
        '...BBBBBBBBBB...',
        '................',
      ],
      chars: {
        F: { name: 'flame', role: 'accessory' },
        G: { name: 'core', role: 'eye' },
        B: { name: 'stones', role: 'body' },
        H: { name: 'logs', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 4. LEVER — puzzle/dungeon ────────────────────────────────
    {
      id: 'lever_switch_16',
      description: 'Stone-mounted lever in pulled position.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '......XX........',
        '.......XX.......',
        '........XX......',
        '.........X......',
        '.........H......',
        '.........H......',
        '......HHHHHH....',
        '.....HHHHHHHH...',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'handle', role: 'accessory' },
        H: { name: 'mechanism', role: 'head' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 5. CRYSTAL LAMP — fantasy light ──────────────────────────
    {
      id: 'crystal_lamp_16',
      description: 'Glowing crystal on ornate pedestal.',
      grid: [
        '................',
        '................',
        '.......GG.......',
        '......GGGG......',
        '.....GGGGGG.....',
        '.....GGXXGG.....',
        '.....GGGGGG.....',
        '......GGGG......',
        '.......HH.......',
        '.......HH.......',
        '......HHHH......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'crystal', role: 'accessory' },
        X: { name: 'glow_core', role: 'eye' },
        H: { name: 'stem', role: 'head' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. BOOKSHELF — RPG/library ───────────────────────────────
    {
      id: 'bookshelf_tall_16',
      description: 'Tall wooden bookshelf packed with colorful books.',
      grid: [
        '..HHHHHHHHHH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HHHHHHHHHH....',
        '..HXXBBBXXXH....',
        '..HXXBBBXXXH....',
        '..HHHHHHHHHH....',
        '..HBBXXXBBBH....',
        '..HBBXXXBBBH....',
        '..HHHHHHHHHH....',
        '..HXXBBBBXXH....',
        '..HXXBBBBXXH....',
        '..HHHHHHHHHH....',
        '..HLLLLLLLLH....',
        '..HHHHHHHHHH....',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        B: { name: 'books_red', role: 'body' },
        X: { name: 'books_blue', role: 'accessory' },
        L: { name: 'shelf_bottom', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 7. ANVIL — blacksmith shop ───────────────────────────────
    {
      id: 'anvil_16',
      description: 'Heavy iron anvil on wooden stump.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHHHHHHHHH....',
        '...HHHHHHHHH....',
        '....HHHHHH......',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '................',
      ],
      chars: {
        H: { name: 'iron_top', role: 'head' },
        B: { name: 'wood_stump', role: 'body' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 8. POTION SHELF — alchemy ────────────────────────────────
    {
      id: 'potion_shelf_16',
      description: 'Small shelf with colorful potion bottles.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHH....',
        '..HXRXGXBXBH....',
        '..HXRXGXBXBH....',
        '..HRRRGBBBBH....',
        '..HHHHHHHHHH....',
        '..HBXRXGXRXH....',
        '..HBXRXGXRXH....',
        '..HBBRRGGRRH....',
        '..HHHHHHHHHH....',
        '....HH..HH......',
        '....HH..HH......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'shelf', role: 'head' },
        R: { name: 'red_potions', role: 'body' },
        G: { name: 'green_potions', role: 'accessory' },
        B: { name: 'blue_potions', role: 'arm' },
        X: { name: 'bottle_necks', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 9. THRONE — royal/RPG ────────────────────────────────────
    {
      id: 'throne_16',
      description: 'Ornate golden throne with red cushion.',
      grid: [
        '..XX......XX....',
        '..XH......HX....',
        '..XH......HX....',
        '..XHXXXXXXHX....',
        '..XHHHHHHHH.....',
        '..XHHHHHHHH.....',
        '..XHHHHHHHH.....',
        '..XHHHHHHHH.....',
        '..XHBBBBBBH.....',
        '..XHBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HHHHHHHH.....',
        '...HH....HH.....',
        '..HHH....HHH....',
        '..HHH....HHH....',
        '................',
      ],
      chars: {
        X: { name: 'crown_detail', role: 'accessory' },
        H: { name: 'frame', role: 'head' },
        B: { name: 'cushion', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 10. SCI-FI CONSOLE — control panel ──────────────────────
    {
      id: 'scifi_console_16',
      description: 'Futuristic control console with screen and buttons.',
      grid: [
        '................',
        '................',
        '..HHHHHHHHHH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HHHHHHHHHH....',
        '..HXXGXXGXXH....',
        '..HXXGXXGXXH....',
        '..HHHHHHHHHH....',
        '...HHHHHHHH.....',
        '...HH....HH.....',
        '..HHH....HHH....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        B: { name: 'screen', role: 'body' },
        X: { name: 'buttons', role: 'accessory' },
        G: { name: 'lights', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 11. WELL — village/RPG ───────────────────────────────────
    {
      id: 'village_well_16',
      description: 'Stone well with wooden roof and bucket.',
      grid: [
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '...XX....XX.....',
        '...XX....XX.....',
        '...XX.BB.XX.....',
        '...XX.BB.XX.....',
        '..BBBBBBBBBB....',
        '..BBBGGGGBBB....',
        '..BBGGGGGGBB....',
        '..BBGGGGGGBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'roof', role: 'head' },
        X: { name: 'posts', role: 'arm' },
        B: { name: 'stone', role: 'body' },
        G: { name: 'water', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 12. ALTAR — dungeon/temple ───────────────────────────────
    {
      id: 'altar_16',
      description: 'Stone altar with glowing rune circle on top.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '...GGGGGGGG.....',
        '..GGGGXXGGGG....',
        '..GGXXGGXXGG....',
        '..GGGGXXGGGG....',
        '...GGGGGGGG.....',
        '..HHHHHHHHHH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '.HHHHHHHHHHHH...',
        '.HHHHHHHHHHHH...',
        '................',
      ],
      chars: {
        G: { name: 'rune_glow', role: 'accessory' },
        X: { name: 'rune_marks', role: 'eye' },
        H: { name: 'stone_trim', role: 'head' },
        B: { name: 'stone_body', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. COOKING POT — farming/survival ──────────────────────
    {
      id: 'cooking_pot_16',
      description: 'Bubbling cooking pot over fire with steam.',
      grid: [
        '......SS........',
        '.....SSSS.......',
        '......SS........',
        '....HHHHHH......',
        '...HBBBBBBH.....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBXXBBBBH....',
        '..HHBBBBBBHH....',
        '...HHHHHHHH.....',
        '....FFFFFF......',
        '...FFFFFFFF.....',
        '...FFFGGFFF.....',
        '..GGGGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'arm' },
        H: { name: 'pot', role: 'head' },
        B: { name: 'stew', role: 'body' },
        X: { name: 'bubbles', role: 'eye' },
        F: { name: 'flame', role: 'accessory' },
        G: { name: 'logs', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. PORTAL — magic/dungeon ───────────────────────────────
    {
      id: 'magic_portal_16',
      description: 'Swirling magic portal with stone archway.',
      grid: [
        '....HHHHHH......',
        '...HHHHHHHHH....',
        '..HH.GGGG.HH....',
        '..H.GGGGGG.H....',
        '.HH.GXXXXG.HH...',
        '.H..GXGGXG..H...',
        '.H..GXGGXG..H...',
        '.H..GXGGXG..H...',
        '.H..GXGGXG..H...',
        '.HH.GXXXXG.HH...',
        '..H.GGGGGG.H....',
        '..HH.GGGG.HH....',
        '..BHHHHHHHHB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'archway', role: 'head' },
        G: { name: 'portal_glow', role: 'accessory' },
        X: { name: 'vortex', role: 'eye' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. WEAPONS RACK — RPG shop ──────────────────────────────
    {
      id: 'weapons_rack_16',
      description: 'Wooden rack displaying swords and axes.',
      grid: [
        '................',
        '..HH......HH....',
        '..HH......HH....',
        '..HHXXXXXXHH....',
        '..HH.X..X.HH....',
        '..HH.X..X.HH....',
        '..HHXXXXXXHH....',
        '..HH.X..X.HH....',
        '..HH.X..X.HH....',
        '..HHXXXXXXHH....',
        '..HH......HH....',
        '..HH......HH....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        X: { name: 'weapons', role: 'accessory' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 16. STATUE — decorative/puzzle ──────────────────────────
    {
      id: 'stone_statue_16',
      description: 'Stone warrior statue on pedestal.',
      grid: [
        '......HH........',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HHEEHH......',
        '....HHHHHH......',
        '...AABBBBAA.....',
        '..AA.BBBB.AA....',
        '.A...BBBB...A...',
        '.....BBBB.......',
        '.....LLLL.......',
        '....LL..LL......',
        '...GGGGGGGG.....',
        '..GGGGGGGGGG....',
        '..GGGGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        G: { name: 'pedestal', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // ─── 17. BED — inn/home ───────────────────────────────────────
    {
      id: 'bed_inn_16',
      description: 'Cozy bed with pillows and blanket.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..HH........HH..',
        '..HPPPPPPPPPH...',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HGGGGGGGGGGH..',
        '..HGGGGGGGGGGH..',
        '..HHHHHHHHHHHH..',
        '..HH........HH..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        P: { name: 'pillows', role: 'arm' },
        B: { name: 'blanket', role: 'body' },
        G: { name: 'mattress', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. WORKBENCH — crafting ─────────────────────────────────
    {
      id: 'workbench_16',
      description: 'Sturdy crafting workbench with tools hanging.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..XXHHHHHHHXX...',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..HH........HH..',
        '..HH........HH..',
        '..HH........HH..',
        '..HH........HH..',
        '..HHHH..HHHH....',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'tools_hanging', role: 'accessory' },
        H: { name: 'wood_frame', role: 'head' },
        B: { name: 'work_surface', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 19. CRATE — warehouse/platformer ─────────────────────────
    {
      id: 'wooden_crate_16',
      description: 'Breakable wooden shipping crate with cross bands.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHH....',
        '..HBBBBBBBBH....',
        '..HBBXXBBBBH....',
        '..HBXBBBBXBH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBXBBBBXBH....',
        '..HBBXXBBBBH....',
        '..HBBBBBBBBH....',
        '..HHHHHHHHHH....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'head' },
        B: { name: 'planks', role: 'body' },
        X: { name: 'bands', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. TREASURE PILE — loot/reward ──────────────────────────
    {
      id: 'treasure_pile_16',
      description: 'Pile of gold coins, gems, and a goblet.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '........GG......',
        '.......GGGG.....',
        '......XGGGX.....',
        '.....BBBBBBB....',
        '....BBBBBBBBB...',
        '...BXBBBBBBXBB..',
        '..BBBBBBBBBBBBB.',
        '.BBBXBBBBBBXBBB.',
        '.BBBBBBBBBBBBBBB',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'gold_coins', role: 'body' },
        X: { name: 'gems', role: 'accessory' },
        G: { name: 'goblet', role: 'head' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
