/**
 * Furniture batch 3 — 14 interior furniture and decorative props.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'furniture',
  exportNames: { templates: 'FURNITURE_BATCH3_TEMPLATES', schemes: 'FURNITURE_BATCH3_COLOR_SCHEMES' },
  templates: [

    {
      id: 'wardrobe_16',
      description: 'Wooden wardrobe / armoire cabinet.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEBBEEEBB..',
        '..BBEEEBBEEEBB..',
        '..BBEEEBBEEEBB..',
        '..BBEEEBBEEEBB..',
        '..BBEEEBBEEEBB..',
        '..BBEEEBBEEEBB..',
        '..BBBBBHBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'doors', role: 'eye' },
        H: { name: 'handle', role: 'head' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'dresser_16',
      description: 'Wooden dresser with drawers.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'drawers', role: 'eye' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'candelabra_16',
      description: 'Ornate three-candle candelabra.',
      grid: [
        '................',
        '..AA...AA...AA..',
        '..HH...HH...HH..',
        '..HH...HH...HH..',
        '..BBBBBBBBBBBB..',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'flames', role: 'accessory' },
        H: { name: 'candles', role: 'head' },
        B: { name: 'arms', role: 'body' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'writing_desk_16',
      description: 'Writing desk with quill and inkwell.',
      grid: [
        '................',
        '................',
        '......AA.HH.....',
        '......AA........',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '..GG........GG..',
        '..GG........GG..',
        '..GG........GG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'desk', role: 'body' },
        E: { name: 'drawer', role: 'eye' },
        A: { name: 'inkwell', role: 'accessory' },
        H: { name: 'quill', role: 'head' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'barrel_stack_16',
      description: 'Stacked wooden barrels.',
      grid: [
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BHHHBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '..BBBB..BBBB....',
        '.BBBBBB.BBBBB...',
        '.BHHBB..BHHBB...',
        '.BBBBBB.BBBBB...',
        '..BBBB..BBBB....',
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        H: { name: 'bands', role: 'head' },
        E: { name: 'floor', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'coat_rack_16',
      description: 'Standing coat rack / hat stand.',
      grid: [
        '................',
        '......HH........',
        '.....HHHH.......',
        '...HHHHHHHHH....',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hooks', role: 'head' },
        B: { name: 'pole', role: 'body' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'stool_16',
      description: 'Simple wooden stool / bar stool.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...GG......GG...',
        '...GG......GG...',
        '...GG......GG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'seat', role: 'body' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'chandelier_16',
      description: 'Hanging chandelier with candles.',
      grid: [
        '.......BB.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '...BBBBBBBBBB...',
        '..AAHBBBBBBHAA..',
        '..AAHBBBBBBHAA..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        H: { name: 'candles', role: 'head' },
        A: { name: 'flames', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'rug_16',
      description: 'Decorative floor rug with pattern.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BEEEEEEEEEEBB..',
        '.BEHHEHHEHHEEB..',
        '.BEHHEHHEHHEEB..',
        '.BEEEEEEEEEEBB..',
        '.BBBBBBBBBBBBBB.',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'border', role: 'body' },
        E: { name: 'fabric', role: 'eye' },
        H: { name: 'pattern', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'wall_painting_16',
      description: 'Framed wall painting / portrait.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEHEEEEBB..',
        '..BBEEEHEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'canvas', role: 'eye' },
        H: { name: 'subject', role: 'head' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'kitchen_stove_16',
      description: 'Old wood-burning kitchen stove.',
      grid: [
        '......HH........',
        '.....HHHH.......',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEBB.BEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'chimney', role: 'head' },
        E: { name: 'burners', role: 'eye' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'rocking_chair_16',
      description: 'Wooden rocking chair.',
      grid: [
        '................',
        '..BBB...........',
        '..BBBBB.........',
        '..BBBBB.........',
        '..BBBBB.........',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '...GG......GG...',
        '..GGGGGGGGGGG...',
        '..GGGGGGGGGGG...',
        '.GG..........GG.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chair', role: 'body' },
        G: { name: 'rockers', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'vanity_mirror_16',
      description: 'Vanity table with oval mirror.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHEEEEHH....',
        '....HHEEEEHH....',
        '....HHEEEEHH....',
        '.....HHHHHH.....',
        '......BBBB......',
        '..BBBBBBBBBBBB..',
        '..BBAABBBBABBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '..GG........GG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'mirror_frame', role: 'head' },
        E: { name: 'mirror', role: 'eye' },
        B: { name: 'table', role: 'body' },
        A: { name: 'items', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'cupboard_16',
      description: 'Kitchen cupboard with shelves.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBHHBBHHBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBHHBBHHBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'shelves', role: 'eye' },
        H: { name: 'items', role: 'head' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
