/**
 * Game Icons 32x32 — Batch 3: Resource & Crafting Icons (20 templates).
 * ASCII grid format. DB16 palette, colored selout, 3-5 roles per icon.
 * Clean silhouettes, no orphan pixels, min 2px structural width.
 * Light from top-left, shadow bottom-right.
 *
 * 1-12:  Resource icons   13-20: Crafting tools/stations
 */
import type { BatchDefinition } from '../templateGenerator.js';

/* padRow ensures exactly 32 chars — pads with '.' on right */
function r(s: string): string {
  if (s.length > 32) throw new Error(`Row too long (${s.length}): ${s}`);
  return s.padEnd(32, '.');
}

const batch: BatchDefinition = {
  category: 'game_icons_32',
  exportNames: { templates: 'GAME_ICONS_32_BATCH3_TEMPLATES', schemes: 'GAME_ICONS_32_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    // 1. WOOD LOGS — pyramid stack of 3 logs with cut ends visible
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_wood_icon_32',
      description: 'Stack of three wooden logs with bark texture and visible cut ends.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('..........bbHHHHHHbb'),
        r('.........bHBBBBBBBBHb'),
        r('........bHBBBBAABBBBHb'),
        r('........bBBBBAAAABBBBBb'),
        r('........bBBBBBAABBBBBBb'),
        r('.........bBBBBBBBBBBBb'),
        r('..........bbbbbbbbbb'),
        r('....bbHHHHbb......bbHHHHbb'),
        r('...bHBBBBBBHb....bHBBBBBBHb'),
        r('..bHBBBAABBBHb..bHBBBAABBBHb'),
        r('..bBBBAAAABBBBb.bBBBAAAABBBBb'),
        r('..bBBBBAABBBBBbbBBBBAABBBBBb'),
        r('..bBBBBBBBBBBBbbBBBBBBBBBBBb'),
        r('...bBBBBBBBBBBb..bBBBBBBBBBb'),
        r('....bbbbbbbbbb....bbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'wood_base', role: 'body' },
        b: { name: 'bark_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'wood_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'cut_face', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 2. STONE CHUNK — rough gray stone
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_stone_icon_32',
      description: 'Rough stone chunk with faceted surface and gray tones.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('..........HHHHHHHHH'),
        r('.........HHHHHHHHHHH'),
        r('........HHBBBBBBBBBHH'),
        r('.......HHBBBBBBBBBBBHH'),
        r('......HHBBBBBBBBBBBBBBH'),
        r('.....HHBBBBBBBBBBBBBBBBH'),
        r('.....HBBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBBB'),
        r('.....BBBBBBBBBBBBBBBBBBB'),
        r('.....BBBBBBBBBBBBBBBBBBb'),
        r('......BBBBBBBBBBBBBBBBb'),
        r('.......BBBBBBBBBBBBBBbb'),
        r('........BBBBBBBBBBBBbb'),
        r('.........BBBBBBBBBbbb'),
        r('..........BBBBBBbbb'),
        r('...........bbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'stone_base', role: 'body' },
        b: { name: 'stone_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'stone_highlight', role: 'body', tone: 'highlight' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 3. IRON ORE — dark rock with metallic flecks
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_iron_ore_icon_32',
      description: 'Iron ore chunk with dark rock body and bright metallic flecks.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('..........HHHHHHHHH'),
        r('.........HHHHHHHHHHH'),
        r('........HHBBBBBBBBBHH'),
        r('.......HHBBBABBBBBBHH'),
        r('......HHBBBBBBBBBBBBBBH'),
        r('.....HHBBBBBBBBABBBBBBBH'),
        r('.....HBBBABBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBABBBBBBH'),
        r('....HBBBBBBABBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBABBBBBBB'),
        r('....BBBABBBBBBBBBBBBBBBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBBB'),
        r('.....BBBBBBBBBBBABBBBBBB'),
        r('.....BBBBBABBBBBBBBBBBBb'),
        r('......BBBBBBBBBBBBBBBBb'),
        r('.......BBBBBBBABBBBBBbb'),
        r('........BBBBBBBBBBBBbb'),
        r('.........BBBBBBBBBbbb'),
        r('..........BBBBBBbbb'),
        r('...........bbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'rock_base', role: 'body' },
        b: { name: 'rock_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'rock_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'metal_fleck', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 4. GOLD ORE — rock with golden veins
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_gold_ore_icon_32',
      description: 'Gold ore chunk with dark stone and golden veins and nuggets.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('..........HHHHHHHHH'),
        r('.........HHHHHHHHHHH'),
        r('........HHBBBBBBBBBHH'),
        r('.......HHBBBAABBBBBHH'),
        r('......HHBBBBBAABBBBBBH'),
        r('.....HHBBBBBBBBBBBBBBBBH'),
        r('.....HBBBAABBBBBBBBBBBBBBH'),
        r('....HBBBBAAABBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBAAABBBBBH'),
        r('....HBBBBBBBBBBBBBBAABBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBBB'),
        r('.....BBBBBBBAAABBBBBBBBB'),
        r('.....BBBBBBBAABBBBBBBBb'),
        r('......BBBBBBBBBBBBBBBBb'),
        r('.......BBBBBBBBBBBBBbb'),
        r('........BBBBBBBBBBBbb'),
        r('.........BBBBBBBBbbb'),
        r('..........BBBBBBbb'),
        r('...........bbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'rock_base', role: 'body' },
        b: { name: 'rock_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'rock_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'gold_vein', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 5. CRYSTAL CLUSTER — blue crystal spikes from rock base
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_crystal_icon_32',
      description: 'Cluster of blue crystal spikes rising from a stone base.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r('..............BH'),
        r('.............BBHH'),
        r('.............BBHH'),
        r('............BBBHH'),
        r('......BB....BBBHH'),
        r('.....BBHH..BBBBHH'),
        r('.....BBHH..BBBBBH'),
        r('....BBBHH.BBBBBHH.....BB'),
        r('....BBBHH.BBBBBbH....BBHH'),
        r('....BBBBHHBBBBBbH....BBHH'),
        r('...BBBBBHHBBBBBbH...BBBHH'),
        r('...BBBBBbHBBBBBbH...BBBbH'),
        r('...BBBBBbHBBBBBbH..BBBBbH'),
        r('...BBBBBbbBBBBBbH..BBBBbH'),
        r('...BBBBBbbBBBBBbbHBBBBBbH'),
        r('....BBBBbbBBBBBbbHBBBBBbH'),
        r('....BBBBbbBBBBBbbBBBBBbbH'),
        r('....BBBBbbBBBBBbbBBBBBbb'),
        r('.....BBBbbBBBBBbbBBBBbb'),
        r('......AAAAAAAAAAAAAAA'),
        r('.......AAAAAAAAAAAAA'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'crystal_base', role: 'body' },
        b: { name: 'crystal_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'crystal_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'rock_base', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 6. HERB BUNDLE — tied green leaves
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_herb_icon_32',
      description: 'Bundle of green herbs tied together with brown twine.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r('.......HH........HH'),
        r('......HBBH......HBBH'),
        r('.....HBBBHH...HHBBBBH'),
        r('....HBBBBBHH.HBBBBBH'),
        r('....HBBBBBBHHBBBBBHH'),
        r('...HBBBBBBBBBBBBBBH'),
        r('...HBBBBBBBBBBBBHH.....HH'),
        r('...HBBBBBBBBBBBHH.....HBBH'),
        r('....HBBBBBBBBBbH....HBBBBH'),
        r('....HBBBBBBBBbbH...HBBBBBH'),
        r('.....HBBBBBBbbH...HBBBBBBH'),
        r('......HHBBBbbH....HBBBBbH'),
        r('.......AAbbAAH...HBBBbbH'),
        r('........AAAAA...HBBBbbH'),
        r('.........AAAA...HBBbbH'),
        r('.........AAAA...ABbbH'),
        r('.........AAAA...AAAH'),
        r('.........AAAA...AAAA'),
        r('.........AAAA...AAAA'),
        r('.........AAAA...AAAA'),
        r('..........AA.....AA'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'leaf_base', role: 'body' },
        b: { name: 'leaf_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'leaf_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'stem_twine', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 7. LEATHER HIDE — folded animal hide
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_leather_icon_32',
      description: 'Folded leather hide with warm brown tones and visible fold crease.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('.....HHHHHHHHHHHHHHHHHH'),
        r('....HHHHHHHHHHHHHHHHHHHH'),
        r('...HHBBBBBBBBBBBBBBBBBBBH'),
        r('...HBBBBBBBBBBBBBBBBBBBBBH'),
        r('...HBBBBBBBBBBBBBBBBBBBBBBH'),
        r('...AAAAAAAAAAAAAAAAAAAAAAAAA'),
        r('...HBBBBBBBBBBBBBBBBBBBBBBH'),
        r('...HBBBBBBBBBBBBBBBBBBBBBH'),
        r('...BBBBBBBBBBBBBBBBBBBBBbb'),
        r('...BBBBBBBBBBBBBBBBBBBBbb'),
        r('...BBBBBBBBBBBBBBBBBBBbbb'),
        r('....BBBBBBBBBBBBBBBBBbbb'),
        r('.....BBBBBBBBBBBBBBBbbb'),
        r('......bbbbbbbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'leather_base', role: 'body' },
        b: { name: 'leather_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'leather_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'fold_line', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 8. CLOTH BOLT — rolled fabric with spiral cross-section
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_cloth_icon_32',
      description: 'Rolled bolt of fabric with visible spiral cross-section.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('......HHHHHHHHHHHHHHHH'),
        r('.....HHBBBBBBBBBBBBBBHH'),
        r('....HHBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBBB'),
        r('....HBBBBBBBBBBBBBBBBBBBBBB'),
        r('....BBBBBBBBBBBBBBBBBBBAAAbH'),
        r('....BBBBBBBBBBBBBBBBBBBAAbAH'),
        r('....BBBBBBBBBBBBBBBBBBBAAbAH'),
        r('....BBBBBBBBBBBBBBBBBBBBAAAbH'),
        r('....BBBBBBBBBBBBBBBBBBBBAAAb'),
        r('....bBBBBBBBBBBBBBBBBBBBAAb'),
        r('....bBBBBBBBBBBBBBBBBBBBbb'),
        r('.....bBBBBBBBBBBBBBBBBBb'),
        r('......bbbbbbbbbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'cloth_base', role: 'body' },
        b: { name: 'cloth_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'cloth_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'spiral_end', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 9. BONE — classic dog-bone shape, diagonal
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_bone_icon_32',
      description: 'Large bone with rounded knobs on each end, diagonal orientation.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r('...................AAHH'),
        r('..................AAHHHH'),
        r('.................AAHHHHH'),
        r('..................HHBBAA'),
        r('.................HBBBB'),
        r('................HBBBB'),
        r('...............HBBBB'),
        r('..............HBBBB'),
        r('.............HBBBBb'),
        r('............HBBBBb'),
        r('...........HBBBBb'),
        r('..........HBBBBb'),
        r('.........HBBBBb'),
        r('........HBBBBb'),
        r('.......HBBBBb'),
        r('......HBBBBb'),
        r('.....HBBBbb'),
        r('....AABBBb'),
        r('....AAHHHBB'),
        r('....AAHHHHBB'),
        r('....AAHHHH'),
        r('.....HHHH'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'bone_base', role: 'body' },
        b: { name: 'bone_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'bone_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'joint_detail', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 10. FEATHER — diagonal plume with blue tip
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_feather_icon_32',
      description: 'Large feather with white vane and blue-tipped barbs.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r('.....................TT'),
        r('....................TTTH'),
        r('...................TTBBH'),
        r('..................TTBBBH'),
        r('.................TTBBBBHH'),
        r('................TTBBBBBHH'),
        r('...............TBBBBBBBBH'),
        r('..............TBBBBABBBBH'),
        r('.............TBBBBAAABBBBH'),
        r('............TBBBBAABBBBBBH'),
        r('...........BBBBBAAABBBBBBH'),
        r('..........BBBBBBABBBBBBBbH'),
        r('.........BBBBBBBBBBBBBBbH'),
        r('........BBBBBBBBBBBBBBbH'),
        r('.......BBBBBBBBBBBBBBbH'),
        r('........BBBBBBBBBBBBbH'),
        r('.........BBBBBBBBBBbH'),
        r('..........BBBBBBBbbH'),
        r('...........BBBBBbbH'),
        r('............BBBBbH'),
        r('.............BBbbH'),
        r('..............bbH'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'feather_vane', role: 'body' },
        b: { name: 'vane_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'vane_highlight', role: 'body', tone: 'highlight' },
        T: { name: 'blue_tip', role: 'accessory' },
        A: { name: 'shaft', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 11. DRAGON SCALE — teardrop/shield shape with ridges
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_scale_icon_32',
      description: 'Large dragon scale with green-blue iridescence and ridges.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r('..............HH'),
        r('.............HHHH'),
        r('............HHHHBB'),
        r('...........HHHBBBBB'),
        r('..........HHBBBBBBBb'),
        r('.........HHBBBBBBBBBb'),
        r('........HHBBBBBBBBBBBB'),
        r('.......HHBBBBBBBBBBBBBH'),
        r('.......HBBBBAAABBBBBBBb'),
        r('......HBBBBAAAABBBBBBBBb'),
        r('......HBBBBAAABBBBBBBBBb'),
        r('.....HBBBBBBBBBBBBBBBBBBb'),
        r('.....HBBBBBBBBBBBBBBBBBBb'),
        r('.....BBBBBAAAAAABBBBBBBbb'),
        r('.....BBBBAAAAAAAABBBBBBbb'),
        r('.....BBBBBAAAAABBBBBBBbbb'),
        r('......BBBBBBBBBBBBBBBbbb'),
        r('......BBBBBBBBBBBBBBbbb'),
        r('.......BBBBBBBBBBBBbbb'),
        r('........BBBBBBBBBbbbb'),
        r('.........BBBBBBBbbb'),
        r('..........BBBBBbb'),
        r('...........BBBbb'),
        r('............bbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'scale_base', role: 'body' },
        b: { name: 'scale_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'scale_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'ridge_lines', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#346524', highlight: '#6dc2ca' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 12. PEARL IN SHELL — round pearl in half-shell
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'resource_pearl_icon_32',
      description: 'Lustrous pearl resting in an open half-shell.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('............EEHHH'),
        r('...........EHHBBBBH'),
        r('..........EHHBBBBBBH'),
        r('..........HHBBBBBBBH'),
        r('..........HBBBBBBBBbH'),
        r('..........HBBBBBBBBbH'),
        r('..........HBBBBBBBbbH'),
        r('...........BBBBBBbbb'),
        r('............bbbbbbb'),
        r('......AAAAAAAAAAAAAAAAAAA'),
        r('.....AATTTTTTTTTTTTTTTTAAA'),
        r('....AATTTTTTTTTTTTTTTTTTAAA'),
        r('...AATTTTTTTTTTTTTTTTTTTTTAA'),
        r('...ATTTTTTTTTTTTTTTTTTTTTTAA'),
        r('...ATTTTTTTTTTTTTTTTTTTTTaA'),
        r('...ATTTTTTTTTTTTTTTTTTTTaaA'),
        r('....ATTTTTTTTTTTTTTTTTaaAA'),
        r('.....ATTTTTTTTTTTTTTaaaAA'),
        r('......AATTTTTTTTTTaaaAAA'),
        r('.......AAAAAAaaaaaAAAA'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'pearl_base', role: 'body' },
        b: { name: 'pearl_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'pearl_highlight', role: 'body', tone: 'highlight' },
        E: { name: 'pearl_shine', role: 'eye' },
        T: { name: 'shell_inner', role: 'accessory' },
        A: { name: 'shell_outer', role: 'belt' },
        a: { name: 'shell_shadow', role: 'belt', tone: 'shadow' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // CRAFTING TOOLS & STATIONS (13-20)
    // ═══════════════════════════════════════════════════════════════

    // ═══════════════════════════════════════════════════════════════
    // 13. ANVIL — blacksmith's anvil front view
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_anvil_icon_32',
      description: 'Classic blacksmith anvil with flat top, horn, and wide base.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('..EEEEEEEEEEEEEEEEEEEEE'),
        r('.HHHHHHHHHHHHHHHHHHHHHHBB'),
        r('HHBBBBBBBBBBBBBBBBBBBBBBBB'),
        r('.bBBBBBBBBBBBBBBBBBBBBBBBb'),
        r('..bBBBBBBBBBBBBBBBBBBBBBbb'),
        r('....bBBBBBBBBBBBBBBBBBBb'),
        r('.....bBBBBBBBBBBBBBBBBb'),
        r('......bBBBBBBBBBBBBBBb'),
        r('.......BBBBBBBBBBBBBB'),
        r('.......BBBBBBBBBBBBBB'),
        r('......BBBBBBBBBBBBBBBb'),
        r('.....BBBBBBBBBBBBBBBBBb'),
        r('....BBBBBBBBBBBBBBBBBBBb'),
        r('...BBBBBBBBBBBBBBBBBBBBBb'),
        r('..BBBBBBBBBBBBBBBBBBBBBBBb'),
        r('..bbbbbbbbbbbbbbbbbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'anvil_base', role: 'body' },
        b: { name: 'anvil_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'anvil_highlight', role: 'body', tone: 'highlight' },
        E: { name: 'top_surface', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 14. CAULDRON — round pot with green bubbles and legs
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_cauldron_icon_32',
      description: 'Round cauldron with green bubbling liquid and three legs.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r('.........AA..........AA'),
        r('........AAAA........AAAA'),
        r('........AAAA........AAAA'),
        r('.......HHHHHHHHHHHHHHHHHH'),
        r('......HHTTTTTTTTTTTTTTTHH'),
        r('.....HHTTTTTEETTTTTTTTTTHH'),
        r('.....HTTTTTTEETTTEETTTTTTH'),
        r('....HHBBBBBBBBBBBBBBBBBBHH'),
        r('....HBBBBBBBBBBBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBBBbH'),
        r('....HBBBBBBBBBBBBBBBBBBBBbH'),
        r('....HBBBBBBBBBBBBBBBBBBBBbH'),
        r('....HBBBBBBBBBBBBBBBBBBBBbH'),
        r('.....BBBBBBBBBBBBBBBBBBBbb'),
        r('.....BBBBBBBBBBBBBBBBBBBbb'),
        r('......BBBBBBBBBBBBBBBBBbb'),
        r('.......BBBBBBBBBBBBBBBbb'),
        r('........bBBBBBBBBBBBbb'),
        r('.........bbbbbbbbbbb'),
        r('........AA..........AA'),
        r('.......AA............AA'),
        r('......AA..............AA'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'cauldron_base', role: 'body' },
        b: { name: 'cauldron_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'cauldron_highlight', role: 'body', tone: 'highlight' },
        T: { name: 'liquid_green', role: 'accessory' },
        E: { name: 'bubbles', role: 'eye' },
        A: { name: 'handles_legs', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 15. NEEDLE & THREAD — vertical needle with red thread loop
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_needle_icon_32',
      description: 'Steel sewing needle with red thread looping through the eye.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r('..............HH'),
        r('..............BB'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBAA'),
        r('..............BAAAB'),
        r('..............AAA'),
        r('.............AAAA'),
        r('...........AAAA'),
        r('..........AAAA'),
        r('.........AAAA'),
        r('........AAAA'),
        r('.......AAAA'),
        r('......AAAA'),
        r('.......AA'),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'needle_base', role: 'body' },
        b: { name: 'needle_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'needle_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'thread_red', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 16. MORTAR & PESTLE — bowl with grinding tool
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_mortar_icon_32',
      description: 'Stone mortar bowl with pestle leaning diagonally inside.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r('...................AA'),
        r('..................AAHH'),
        r('.................AAHH'),
        r('................AAHH'),
        r('...............AAHH'),
        r('..............AAHH'),
        r('.............AAHH'),
        r('............AAHH'),
        r('...........AAHH'),
        r('......HHHHAAHHHHHHHHH'),
        r('.....HHBBAABBBBBBBBBHH'),
        r('....HHBBBTTTBBBBBBBBBBH'),
        r('....HBBBBTTTTBBBBBBBBBBH'),
        r('....HBBBBTTTBBBBBBBBBBBH'),
        r('....HBBBBBBBBBBBBBBBBBBbH'),
        r('....HBBBBBBBBBBBBBBBBBBbH'),
        r('.....BBBBBBBBBBBBBBBBBBbb'),
        r('.....BBBBBBBBBBBBBBBBBbbb'),
        r('......BBBBBBBBBBBBBBBbb'),
        r('.......BBBBBBBBBBBBBbb'),
        r('........BBBBBBBBBBBbb'),
        r('.........bbbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'mortar_base', role: 'body' },
        b: { name: 'mortar_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'mortar_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'pestle', role: 'accessory' },
        T: { name: 'herb_residue', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#346524', base: '#346524', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 17. FURNACE — brick furnace with fire glow
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_furnace_icon_32',
      description: 'Brick furnace with arched fire opening and chimney on top.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r('...........AAAA'),
        r('..........AATTAA'),
        r('..........AATTAA'),
        r('..........AATTAA'),
        r('..........AATTAA'),
        r('......HHHHAATTAAHHHH'),
        r('.....HHBBBBBBBBBBBBBBH'),
        r('....HHBBBBBBBBBBBBBBBBB'),
        r('....HBBBBBBBBBBBBBBBBBBB'),
        r('....HBBBBBBBBBBBBBBBBBBB'),
        r('....HBBBBBbbbbbbBBBBBBBb'),
        r('....HBBBBbbbbbbbbbBBBBBb'),
        r('....HBBBBbbbEEEbbbBBBBBb'),
        r('....HBBBBbbbEEEbbbBBBBBb'),
        r('....HBBBBbbbEEEbbbBBBBBb'),
        r('....HBBBBbbEEEEEbbBBBBBb'),
        r('....HBBBBbbEEEEEbbBBBBBb'),
        r('....BBBBBbbbbbbbbbBBBBBBb'),
        r('....BBBBBBBBBBBBBBBBBBBBb'),
        r('....BBBBBBBBBBBBBBBBBBBBb'),
        r('....BBBBBBBBBBBBBBBBBBBbb'),
        r('....bbbbbbbbbbbbbbbbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'brick_base', role: 'body' },
        b: { name: 'brick_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'brick_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'chimney', role: 'accessory' },
        T: { name: 'smoke', role: 'belt' },
        E: { name: 'fire_glow', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 18. LOOM — wooden frame with threads and woven cloth
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_loom_icon_32',
      description: 'Wooden weaving loom frame with warp threads and woven cloth.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r('.....HHHHHHHHHHHHHHHHHH'),
        r('.....HBBBBBBBBBBBBBBBBH'),
        r('.....HHHHHHHHHHHHHHHHHH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HBTTTTTTTTTTTTBbH'),
        r('.....HBTTATTATTATTTBbH'),
        r('.....HBTTTTTTTTTTTTBbH'),
        r('.....HBTTATTATTATTTBbH'),
        r('.....HBTTTTTTTTTTTTBbH'),
        r('.....HBTTATTATTATTTBbH'),
        r('.....HBTTTTTTTTTTTTBbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HB..A..A..A..ABbH'),
        r('.....HHHHHHHHHHHHHHHHHH'),
        r('.....HBBBBBBBBBBBBBBBBH'),
        r('.....HHHHHHHHHHHHHHHHHH'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'wood_frame', role: 'body' },
        b: { name: 'wood_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'wood_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'warp_threads', role: 'accessory' },
        T: { name: 'woven_cloth', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 19. HAMMER — vertical handle with rectangular metal head
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_hammer_icon_32',
      description: 'Crafting hammer with wooden handle and flat metallic head.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r('......AAAAAAEEEEEEEEE'),
        r('.....AAAAAAbEEEEEEEEEB'),
        r('.....AAAAAAbEEEEEEEEEB'),
        r('.....AAAAAAbTTTTTTTTTB'),
        r('......AAAAAbbbbbbbbbbb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('.............HBBb'),
        r('............HBBBB'),
        r('...........HBBBBBb'),
        r('...........bbbbbbb'),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'handle_wood', role: 'body' },
        b: { name: 'handle_shadow', role: 'body', tone: 'shadow' },
        H: { name: 'handle_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'metal_head', role: 'accessory' },
        E: { name: 'head_highlight', role: 'accessory', tone: 'highlight' },
        T: { name: 'head_shadow', role: 'accessory', tone: 'shadow' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // 20. HANDSAW — blade with teeth and wooden handle
    // ═══════════════════════════════════════════════════════════════
    {
      id: 'crafting_saw_icon_32',
      description: 'Handsaw with wooden grip handle and toothed steel blade.',
      size: 32,
      grid: [
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r('.....AAAAAEEEEEEEEEEEEEEEEEE'),
        r('.....AAAAAbBBBBBBBBBBBBBBBBBb'),
        r('.....AAHHAbBBBBBBBBBBBBBBBBBBb'),
        r('.....AAHHAbBBBBBBBBBBBBBBBBBBBb'),
        r('.....AAAAAbBBBBBBBBBBBBBBBBBBBb'),
        r('.....AAAAAbbBBBBBBBBBBBBBBBBBbb'),
        r('.....AAAAAbbbBBBBBBBBBBBBBBBbbb'),
        r('.....AAAAAbbbbTbTbTbTbTbTbTbbbb'),
        r('.....AAAAA....bb.bb.bb.bb.bb'),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
        r(''),
      ],
      chars: {
        B: { name: 'blade_steel', role: 'body' },
        b: { name: 'blade_shadow', role: 'body', tone: 'shadow' },
        E: { name: 'blade_highlight', role: 'body', tone: 'highlight' },
        A: { name: 'handle_wood', role: 'accessory' },
        H: { name: 'handle_hole', role: 'belt' },
        T: { name: 'saw_teeth', role: 'body', tone: 'shadow' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

  ],
};

export default batch;
