/**
 * Game-Inspired Characters Batch 1 — 20 templates
 * Iconic game archetype characters (NOT direct copies, but clearly inspired silhouettes)
 * All 16x16, 3/4 view chibi style, DB16 palette
 */
import type { BatchDefinition } from '../templateGenerator.js';

const H = { name: 'head', role: 'head' };
const E = { name: 'eyes', role: 'eye' };
const F = { name: 'face', role: 'face' };
const B = { name: 'body', role: 'body' };
const A = { name: 'arms', role: 'arm' };
const L = { name: 'boots', role: 'boot' };
const G = { name: 'belt', role: 'belt' };
const R = { name: 'hair', role: 'hair' };
const X = { name: 'hat', role: 'accessory' };
const P = { name: 'pack', role: 'hand' };
const T = { name: 'tail', role: 'leg' };

const batch: BatchDefinition = {
  category: 'game-inspired',
  exportNames: {
    templates: 'GAME_INSPIRED_BATCH1_TEMPLATES',
    schemes: 'GAME_INSPIRED_BATCH1_COLOR_SCHEMES',
  },
  templates: [
    // 1. Red Plumber — Mario-inspired plumber with cap and overalls
    {
      id: 'gi_plumber_16',
      description: 'Red-capped plumber hero with overalls and mustache',
      grid: [
        '................',
        '....XXXXXX......',
        '...XXXHHHX......',
        '...XHHHHHX......',
        '...HEEHFHX......',
        '...HHFFFFHH.....',
        '....HHHHHH......',
        '...ABBBBBBA.....',
        '..AABBBBBBAA....',
        '..AABBBBBBAA....',
        '...GBBBBBG......',
        '...GBBBBBG......',
        '....BBBBB.......',
        '....BB.BB.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'cap', role: 'accessory' }, H: H, E: E, F: F, A: A, B: { name: 'overalls', role: 'body' }, G: G, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 2. Blue Hedgehog — Sonic-inspired fast runner
    {
      id: 'gi_speedster_16',
      description: 'Blue spiky speedster with red boots',
      grid: [
        '......HHHH......',
        '....HHHHHHH.....',
        '...HHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHEHHEHHF....',
        '...HBBBBHH......',
        '....BBBBH.......',
        '....BBBBB.......',
        '...ABBBBBA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BBBB........',
        '....BB.BB.......',
        '...LL..LL.......',
        '...LLL.LLL......',
        '..LLLL.LLLL.....',
      ],
      chars: { H: H, E: E, F: F, B: B, A: A, L: L },
      colors: {
        head:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:  { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
      },
    },
    // 3. Pixel Trainer — Pokémon-inspired trainer with cap
    {
      id: 'gi_trainer_16',
      description: 'Young monster trainer with cap and backpack',
      grid: [
        '................',
        '....XXXXXX......',
        '...XXXXXXX......',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..PPBBBBA.......',
        '...PBBBBA.......',
        '....BBBBB.......',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'cap', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, P: P, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 4. Round Eater — Pac-Man-inspired circle character
    {
      id: 'gi_gobbler_16',
      description: 'Round yellow chomper with big mouth',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHHEHHHHH....',
        '..HHHHHHHHH.....',
        '..HHHHHHHH......',
        '..HHHHHHH.......',
        '..HHHHHHHH......',
        '..HHHHHHHHH.....',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '......HHHH......',
        '................',
        '................',
      ],
      chars: { H: H, E: E },
      colors: {
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
      },
    },
    // 5. Karate Fighter — Street Fighter-inspired martial artist
    {
      id: 'gi_karate_hero_16',
      description: 'Martial arts fighter with headband and gi',
      grid: [
        '................',
        '.....XXXXX......',
        '....HHHHHHH.....',
        '...HHHHHHHH.....',
        '...HHEFEHH......',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '...ABBBBBBA.....',
        '..AABBBBBBA.....',
        '..AABBBBBBAA....',
        '...ABBBBBA......',
        '....BBBBB.......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'headband', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 6. Bubble Dragon — Bubble Bobble-inspired cute dragon
    {
      id: 'gi_bubble_dragon_16',
      description: 'Small cute dragon that blows bubbles',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHHH....',
        '..HHHFFFFHH.....',
        '...HHHHHHH......',
        '...HBBBBH.......',
        '..AABBBBAA......',
        '..AABBBBAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '...LL..LL.......',
        '...LL..LL.......',
        '..TTT..TTT......',
        '................',
      ],
      chars: { H: H, E: E, F: F, B: B, A: A, L: L, T: T },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },
    // 7. Dhampir — Castlevania Alucard-inspired vampire hunter
    {
      id: 'gi_dhampir_16',
      description: 'Elegant vampire hunter with flowing coat',
      grid: [
        '................',
        '.....RRRRRR.....',
        '....RHHHHHR.....',
        '...HHEFEHH......',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '...ABBBBBA......',
        '..XABBBBBA......',
        '..XABBBBBA......',
        '..XXBBBBXX......',
        '..XXBBBBXX......',
        '...XBBBBXX......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { R: R, H: H, E: E, F: F, A: A, B: B, X: { name: 'coat', role: 'accessory' }, L: L },
      colors: {
        hair:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
      },
    },
    // 8. Time Hero — Chrono Trigger-inspired spiky-haired hero
    {
      id: 'gi_time_hero_16',
      description: 'Spiky red-haired hero with katana and headband',
      grid: [
        '...RRRR.........',
        '..RRRRRRR.......',
        '..RRRRRRR.......',
        '.RRRHHHHH.......',
        '..HHEFEHH.......',
        '..HHHHHHH.......',
        '...HHHHH........',
        '..AABBBBBA......',
        '..AABBBBA.......',
        '..AABBBBA.......',
        '...ABBBBA.......',
        '....BBBBB.......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { R: R, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        hair:  { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 9. PSI Kid — Earthbound-inspired cap kid
    {
      id: 'gi_psi_kid_16',
      description: 'Kid with baseball cap and striped shirt with psychic powers',
      grid: [
        '................',
        '....XXXXXX......',
        '...XXXXXXXX.....',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBA.......',
        '..AAGGGGA.......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'cap', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, G: G, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#dad45e' },
        belt:      { shadow: '#dad45e', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
      },
    },
    // 10. Hollow Bug — Hollow Knight-inspired small bug knight
    {
      id: 'gi_bug_knight_16',
      description: 'Small insectoid knight with horned mask and nail weapon',
      grid: [
        '..H..........H..',
        '..HH........HH..',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHHH....',
        '...HHHHHHHH.....',
        '....XXXXXX......',
        '...ABBBBBBA.....',
        '...AABBBBA......',
        '....ABBBBA......',
        '....BBBB........',
        '....BB.BB.......',
        '...LL..LL.......',
        '...LL..LL.......',
        '................',
      ],
      chars: { H: H, E: E, X: { name: 'cloak', role: 'accessory' }, B: B, A: A, L: L },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#854c30' },
      },
    },
    // 11. Mountain Climber — Celeste-inspired red-haired climber
    {
      id: 'gi_climber_16',
      description: 'Determined red-haired mountain climber girl',
      grid: [
        '................',
        '....RRRRRR......',
        '...RRHHHHRR.....',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AABBBBAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....LLLL........',
        '....LL.LL.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { R: R, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        hair:  { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 12. Shovel Warrior — Shovel Knight-inspired armored knight with shovel
    {
      id: 'gi_shovel_warrior_16',
      description: 'Blue-armored knight wielding a mighty shovel',
      grid: [
        '................',
        '....HHHHH.......',
        '...HHHHHHHH.....',
        '..HHHHHHHHH.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHH.....',
        '...HHHHHHH......',
        '..AABBBBBBA.....',
        '..AABBBBBBA.....',
        '..AABBBBBA......',
        '...ABBBBA.......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '..LLLL.LLLL.....',
        '................',
      ],
      chars: { H: H, E: E, A: A, B: B, L: L },
      colors: {
        head:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:   { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:  { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
      },
    },
    // 13. Valley Farmer — Stardew Valley-inspired farmer
    {
      id: 'gi_valley_farmer_16',
      description: 'Happy farmer with straw hat and overalls',
      grid: [
        '................',
        '...XXXXXXXX.....',
        '..XXXXXXXXX.....',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AAGGGGAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'hat', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, G: G, L: L },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 14. Pixel Explorer — Terraria-inspired adventurer
    {
      id: 'gi_pixel_explorer_16',
      description: 'Adventurer with mining helmet and pickaxe',
      grid: [
        '................',
        '....XXXXXX......',
        '...XXXHHHX......',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AABBBBAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'helmet', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 15. Slug Soldier — Metal Slug-inspired commando
    {
      id: 'gi_slug_soldier_16',
      description: 'Military commando with bandana and heavy gun',
      grid: [
        '................',
        '...XXXXXXXX.....',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AAGGGGAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BBLBB.......',
        '....LL.LL.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'bandana', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, G: G, L: L },
      colors: {
        accessory: { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },
    // 16. Bomb Hero — Bomberman-inspired character
    {
      id: 'gi_bomb_hero_16',
      description: 'Round-headed bomber with antenna and white suit',
      grid: [
        '.......X........',
        '......XX........',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHHH....',
        '...HHFFHHHH.....',
        '....HHHH........',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AABBBBAA......',
        '...ABBBBA.......',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '................',
      ],
      chars: { X: { name: 'antenna', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },
    // 17. Pink Puffball — Kirby-inspired cute round character
    {
      id: 'gi_puffball_16',
      description: 'Pink round puffball with big eyes and red shoes',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHHH....',
        '..HHHFFFHHHH....',
        '..HHHHHHHHHH....',
        '..AHHHHHHHAB....',
        '...HHHHHH.......',
        '....HHHH........',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
        '................',
      ],
      chars: { H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        head:  { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        eye:   { shadow: '#30346d', base: '#30346d', highlight: '#597dce' },
        face:  { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        arm:   { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        body:  { shadow: '#d04648', base: '#d04648', highlight: '#d2aa99' },
        boot:  { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
      },
    },
    // 18. Space Bounty Hunter — Metroid-inspired armored hunter (zero suit variant)
    {
      id: 'gi_bounty_hunter_16',
      description: 'Armored space bounty hunter in sleek zero suit',
      grid: [
        '................',
        '.....RRRRR......',
        '....RHHHHHR.....',
        '...HHHHHHHH.....',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '...ABBBBA.......',
        '..AABBBBAA......',
        '..AABBBBAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BB.BB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { R: R, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        hair:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },
    // 19. Contra Commando — Contra-inspired action hero
    {
      id: 'gi_commando_16',
      description: 'Muscular commando with bandana and machine gun',
      grid: [
        '................',
        '...XXXXXXXX.....',
        '...XHHHHHX......',
        '...HHEFEHH......',
        '...HHHHHHH......',
        '....HHHHH.......',
        '..AABBBBA.......',
        '..AABBBBAA......',
        '.AAABBBBAA......',
        '...ABBBBA.......',
        '....BBBB........',
        '....BBLBB.......',
        '....LL.LL.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '...LLL.LLL......',
      ],
      chars: { X: { name: 'bandana', role: 'accessory' }, H: H, E: E, F: F, A: A, B: B, L: L },
      colors: {
        accessory: { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        face:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },
    // 20. Ghost Knight — Ghosts 'n Goblins-inspired knight
    {
      id: 'gi_ghost_knight_16',
      description: 'Brave knight in silver armor who fights the undead',
      grid: [
        '....XXXXXX......',
        '...XXXXXXX......',
        '..XXHHHHHXX.....',
        '..HHHEHHEHH.....',
        '..HHHHHHHHH.....',
        '...HHHHHHH......',
        '..AABBBBBBA.....',
        '..AABBBBBA......',
        '..AABBBBBA......',
        '...ABBBBA.......',
        '....BBBBB.......',
        '....BBLBB.......',
        '....LL.LL.......',
        '...LLL.LLL......',
        '..LLLL.LLLL.....',
        '................',
      ],
      chars: { X: { name: 'helmet', role: 'accessory' }, H: H, E: E, A: A, B: B, L: L },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#140c1c' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        boot:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },
  ],
};

export default batch;
