/**
 * Guns batch 3 — 20 shotguns & SMGs.
 * Covers: pump shotgun, double barrel, sawed-off, auto shotgun, coach gun,
 *         combat shotgun, Uzi, MP5, Thompson, P90, MAC-10, Vector, PPSh,
 *         MP40, sci-fi shotgun, steampunk scatter, street sweeper, slug cannon,
 *         plasma SMG, grease gun.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'weapons',
  exportNames: { templates: 'GUNS_BATCH3_TEMPLATES', schemes: 'GUNS_BATCH3_COLOR_SCHEMES' },
  templates: [

    // --- 1. PUMP SHOTGUN ---------------------------------------------------
    {
      id: 'pump_shotgun_gn_16',
      description: 'Pump-action shotgun with tube magazine, wooden stock and forend grip.',
      grid: [
        '................',
        '................',
        '................',
        '.........MMMBBBB',
        '.SSSSSFFFMMMBBBB',
        'SSSSSSFFFMMMBBBB',
        'SSSSSSFFRRRRBBB.',
        '.SSSSFFRRRR.....',
        '.....FFGGGG.....',
        '......GGGGG.....',
        '......GGTT......',
        '.......TT.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tube', role: 'body' },
        M: { name: 'tube_magazine', role: 'arm' },
        S: { name: 'wooden_stock', role: 'belt' },
        F: { name: 'receiver', role: 'head' },
        R: { name: 'action_slide', role: 'eye' },
        G: { name: 'pump_forend', role: 'accessory' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        eye:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 2. DOUBLE BARREL --------------------------------------------------
    {
      id: 'double_barrel_gn_16',
      description: 'Side-by-side double barrel shotgun with walnut stock and twin muzzles.',
      grid: [
        '................',
        '................',
        '................',
        '..........BBBBBB',
        '.SSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBB.',
        '.SSSSSRRGG......',
        '.....RRGGG......',
        '......GGGG......',
        '......GGTT......',
        '.......TT.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'twin_barrels', role: 'body' },
        S: { name: 'walnut_stock', role: 'belt' },
        R: { name: 'receiver_hinge', role: 'head' },
        G: { name: 'forend_grip', role: 'accessory' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 3. SAWED-OFF ------------------------------------------------------
    {
      id: 'sawed_off_gn_16',
      description: 'Short sawed-off shotgun with pistol grip and stubby double barrels.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.......RRRBBBBBB',
        '......RRRRBBBBBB',
        '...PPPRRRRBBBBB.',
        '...PPPRRGG......',
        '...PP.RGGG......',
        '......GGGG......',
        '......GGTT......',
        '.......TT.......',
        '........T.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'stub_barrels', role: 'body' },
        P: { name: 'pistol_grip', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'forend_stub', role: 'accessory' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 4. AUTO SHOTGUN ---------------------------------------------------
    {
      id: 'auto_shotgun_gn_16',
      description: 'Semi-auto combat shotgun with drum magazine and pistol grip.',
      grid: [
        '................',
        '................',
        '................',
        '..........BBBBBB',
        '..SSSRRRRRBBBBB.',
        '..SSSRRRRRBBBBB.',
        '..SSSRRRRRBBB...',
        '......RRDDD.....',
        '......RDDDD.....',
        '.......DDDD.....',
        '.......TDDD.....',
        '........TDD.....',
        '.........D......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_shroud', role: 'body' },
        S: { name: 'folding_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        D: { name: 'drum_magazine', role: 'accessory' },
        T: { name: 'trigger_grip', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 5. COACH GUN ------------------------------------------------------
    {
      id: 'coach_gun_gn_16',
      description: 'Old west coach gun with short double barrels and ornate walnut stock.',
      grid: [
        '................',
        '................',
        '................',
        '..........ABBBBB',
        '.SSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBBB',
        'SSSSSARRRRBBBB..',
        '.SSSAARGG.......',
        '......RGGG......',
        '......GGGG......',
        '.......GTT......',
        '.......TT.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'short_barrels', role: 'body' },
        S: { name: 'ornate_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'forend_wood', role: 'accessory' },
        A: { name: 'brass_accent', role: 'arm' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 6. COMBAT SHOTGUN -------------------------------------------------
    {
      id: 'combat_shotgun_gn_16',
      description: 'Tactical shotgun with picatinny rail, flashlight, and collapsible stock.',
      grid: [
        '................',
        '................',
        '........AAAAAAA.',
        '.........AABBBB.',
        '..SSRRRRRRBBBBBB',
        '..SSRRRRRRBBBBBB',
        '..SSRRRRRRBBBBBB',
        '......RRGGGLL...',
        '......RGGGGL....',
        '.......GGGTT....',
        '.......GGTT.....',
        '........TT......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_body', role: 'body' },
        S: { name: 'collapsible_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        A: { name: 'picatinny_rail', role: 'arm' },
        G: { name: 'forend_grip', role: 'accessory' },
        L: { name: 'flashlight', role: 'eye' },
        T: { name: 'trigger_grip', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 7. UZI SMG --------------------------------------------------------
    {
      id: 'uzi_smg_gn_16',
      description: 'Compact Uzi submachine gun with folding stock and front grip.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..SS.RRRRRBBBB..',
        '..SS.RRRRRBBBB..',
        '..SSRRRRRRBBBB..',
        '.....RRRRRR.....',
        '.....RRRGMM.....',
        '......RRGMM.....',
        '.......GGMM.....',
        '.......GGMM.....',
        '........GM......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_shroud', role: 'body' },
        S: { name: 'folding_stock', role: 'belt' },
        R: { name: 'receiver_body', role: 'head' },
        G: { name: 'pistol_grip', role: 'accessory' },
        M: { name: 'box_magazine', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 8. MP5 SMG --------------------------------------------------------
    {
      id: 'mp5_smg_gn_16',
      description: 'Classic MP5 submachine gun with solid stock and curved magazine.',
      grid: [
        '................',
        '................',
        '................',
        '..........BBBBB.',
        '.SSSSRRRRRBBBBB.',
        'SSSSSRRRRRBBBBB.',
        'SSSSSRRRRRBBBB..',
        '.SSSSRRRGG......',
        '......RRGGG.....',
        '.......GGGG.....',
        '.......GTMM.....',
        '........TMM.....',
        '........TMM.....',
        '.........M......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_shroud', role: 'body' },
        S: { name: 'fixed_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'handguard', role: 'accessory' },
        M: { name: 'curved_magazine', role: 'arm' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 9. THOMPSON SMG ---------------------------------------------------
    {
      id: 'thompson_smg_gn_16',
      description: 'Tommy gun with round drum magazine, vertical foregrip, and wooden stock.',
      grid: [
        '................',
        '................',
        '..........BBBBB.',
        '.........ABBBBB.',
        '.SSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBB.',
        'SSSSSSRRRRBB....',
        '.SSSAARRGGG.....',
        '.....ARRDDD.....',
        '......RTDDDD....',
        '.......TDDDD....',
        '........DDDD....',
        '.........DD.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_fins', role: 'body' },
        S: { name: 'wooden_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'vertical_grip', role: 'accessory' },
        D: { name: 'drum_magazine', role: 'arm' },
        A: { name: 'brass_accent', role: 'eye' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 10. P90 SMG -------------------------------------------------------
    {
      id: 'p90_smg_gn_16',
      description: 'Unique P90 bullpup SMG with top-mounted horizontal magazine.',
      grid: [
        '................',
        '................',
        '...MMMMMMMMM....',
        '...MMMMMMMMM....',
        '...MMMMMMMMMM...',
        '..RRRRRRRRRBBB..',
        '.RRRRRRRRRRBBB..',
        '.RRRRRRRRRRBB...',
        '..RRRRRRGG......',
        '...RRRRGGG......',
        '....GGGGG.......',
        '.....GGTT.......',
        '......TT........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tip', role: 'body' },
        R: { name: 'receiver_shell', role: 'head' },
        M: { name: 'top_magazine', role: 'arm' },
        G: { name: 'front_grip', role: 'accessory' },
        T: { name: 'trigger_grip', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 11. MAC-10 SMG ----------------------------------------------------
    {
      id: 'mac10_smg_gn_16',
      description: 'Boxy MAC-10 machine pistol with suppressor and top-mounted bolt.',
      grid: [
        '................',
        '................',
        '................',
        '....RRRRRBBBBBBB',
        '....RRRRRBBBBBBB',
        '....RRRRRBBBBBBB',
        '....RRRRRBB.....',
        '....RRRRR.......',
        '.....RRGMM......',
        '.....RRGMM......',
        '......GGMM......',
        '......GGMM......',
        '.......GM.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'suppressor', role: 'body' },
        R: { name: 'boxy_receiver', role: 'head' },
        G: { name: 'pistol_grip', role: 'accessory' },
        M: { name: 'box_magazine', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 12. VECTOR SMG ----------------------------------------------------
    {
      id: 'vector_smg_gn_16',
      description: 'Angular Kriss Vector with downward recoil system and folding stock.',
      grid: [
        '................',
        '................',
        '................',
        '..SS.RRRRRBBBB..',
        '..SS.RRRRRBBBB..',
        '..SSSRRRRRBBBB..',
        '....SRRRRR......',
        '.....RRRRR......',
        '.....RRDGG......',
        '.....RDDGG......',
        '......DDGG......',
        '......DDD.......',
        '.......DD.......',
        '........D.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_shroud', role: 'body' },
        S: { name: 'folding_stock', role: 'belt' },
        R: { name: 'angular_receiver', role: 'head' },
        D: { name: 'recoil_system', role: 'arm' },
        G: { name: 'pistol_grip', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 13. PPSH SMG ------------------------------------------------------
    {
      id: 'ppsh_smg_gn_16',
      description: 'WW2 PPSh-41 with large drum magazine, perforated barrel shroud, and wooden stock.',
      grid: [
        '................',
        '................',
        '..........BBBBB.',
        '.........ABBBBB.',
        '.SSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBB.',
        'SSSSSSRRRRBB....',
        '.SSSAARRGGG.....',
        '.....ARRDDD.....',
        '......RTDDDD....',
        '.......TDDDD....',
        '........DDDD....',
        '........DDD.....',
        '.........D......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'perforated_shroud', role: 'body' },
        S: { name: 'wooden_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'front_grip', role: 'accessory' },
        D: { name: 'drum_magazine', role: 'arm' },
        A: { name: 'stock_plate', role: 'eye' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 14. MP40 SMG ------------------------------------------------------
    {
      id: 'mp40_smg_gn_16',
      description: 'WW2 German MP40 with folding wire stock and straight magazine.',
      grid: [
        '................',
        '................',
        '................',
        '..........BBBBB.',
        '..SS.RRRRRBBBBB.',
        '..SS.RRRRRBBBBB.',
        '..SSSRRRRRBB....',
        '..S..RRRRR......',
        '.....RRRGG......',
        '.....RRTGG......',
        '......TGMM......',
        '.......GMM......',
        '.......GMMM.....',
        '........MM......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tube', role: 'body' },
        S: { name: 'wire_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        G: { name: 'handguard_grip', role: 'accessory' },
        M: { name: 'straight_magazine', role: 'arm' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 15. SCIFI SHOTGUN -------------------------------------------------
    {
      id: 'scifi_shotgun_gn_16',
      description: 'Futuristic wide-bore energy shotgun with glowing energy vents.',
      grid: [
        '................',
        '................',
        '..........BBBBBB',
        '.........EBBBBBB',
        '.SSSRRRRRRBBBBBB',
        '.SSSRRRRRRBBBBB.',
        '.SSSRRRRRRBBBB..',
        '.SSSRRRREGG.....',
        '......RREGG.....',
        '.......RGGG.....',
        '.......GGTT.....',
        '........TT......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'wide_barrel', role: 'body' },
        S: { name: 'tech_stock', role: 'belt' },
        R: { name: 'receiver_shell', role: 'head' },
        E: { name: 'energy_vents', role: 'eye' },
        G: { name: 'front_grip', role: 'accessory' },
        T: { name: 'trigger_grip', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 16. STEAMPUNK SCATTER ---------------------------------------------
    {
      id: 'steampunk_scatter_gn_16',
      description: 'Brass Victorian scattergun with copper pipes and pressure gauge.',
      grid: [
        '................',
        '..........PPPP..',
        '.........PPPPP..',
        '.........PPBBBB.',
        '.SSSSSRRRRBBBBBB',
        'SSSSSSRRRRBBBBBB',
        'SSSSSARRRRBBBB..',
        '.SSSAARRGGG.....',
        '.....ARRGGG.....',
        '......RGGGG.....',
        '.......GGTT.....',
        '........TT......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'brass_barrels', role: 'body' },
        S: { name: 'wooden_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        P: { name: 'copper_pipes', role: 'arm' },
        G: { name: 'forend_grip', role: 'accessory' },
        A: { name: 'pressure_gauge', role: 'eye' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 17. STREET SWEEPER ------------------------------------------------
    {
      id: 'street_sweeper_gn_16',
      description: 'Revolving cylinder shotgun with large rotary drum and pistol grip.',
      grid: [
        '................',
        '................',
        '..........BBBBB.',
        '.........BBBBBB.',
        '..SSRRRRRRBBBBBB',
        '..SSRRRRRRBBB...',
        '..SSRRDDDRR.....',
        '.....RDDDDG.....',
        '.....RDDDDDG....',
        '......DDDDDG....',
        '......GDDDD.....',
        '.......TDDD.....',
        '........DD......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tube', role: 'body' },
        S: { name: 'skeleton_stock', role: 'belt' },
        R: { name: 'receiver', role: 'head' },
        D: { name: 'revolving_drum', role: 'arm' },
        G: { name: 'pistol_grip', role: 'accessory' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 18. SLUG CANNON ---------------------------------------------------
    {
      id: 'slug_cannon_gn_16',
      description: 'Heavy single-shot slug launcher with thick barrel and reinforced stock.',
      grid: [
        '................',
        '................',
        '.........BBBBBBB',
        '.........BBBBBBB',
        '.SSSSSRRRBBBBBB.',
        'SSSSSSRRRBBBBBB.',
        'SSSSSSRRRBBBBBB.',
        'SSSSSSRRRBBB....',
        '.SSSSSRRGG......',
        '......RRGGG.....',
        '.......GGGG.....',
        '.......GGTT.....',
        '........TT......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'thick_barrel', role: 'body' },
        S: { name: 'reinforced_stock', role: 'belt' },
        R: { name: 'heavy_receiver', role: 'head' },
        G: { name: 'forend_grip', role: 'accessory' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 19. PLASMA SMG ----------------------------------------------------
    {
      id: 'plasma_smg_gn_16',
      description: 'Sci-fi plasma submachine gun with glowing energy core and heat vents.',
      grid: [
        '................',
        '................',
        '................',
        '.........BBBBBBB',
        '..SSRRRRRRBBBBBB',
        '..SSRREERRBBBBBB',
        '..SSRREERRBBBB..',
        '....RRRRRRR.....',
        '.....RRRGG......',
        '......RRGGG.....',
        '.......GGGG.....',
        '.......GGTT.....',
        '........TT......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_emitter', role: 'body' },
        S: { name: 'tech_stock', role: 'belt' },
        R: { name: 'receiver_housing', role: 'head' },
        E: { name: 'plasma_core', role: 'eye' },
        G: { name: 'front_grip', role: 'accessory' },
        T: { name: 'trigger_grip', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 20. GREASE GUN ----------------------------------------------------
    {
      id: 'grease_gun_gn_16',
      description: 'WW2 M3 grease gun with simple tube receiver, wire stock, and straight magazine.',
      grid: [
        '................',
        '................',
        '................',
        '..........BBBBB.',
        '..SS.RRRRRBBBBB.',
        '..SS.RRRRRBBBBB.',
        '..SSSRRRRRBBB...',
        '..S..RRRRRR.....',
        '.....RRRGG......',
        '.....RRTGG......',
        '......TGMM......',
        '.......GMM......',
        '.......GMMM.....',
        '........MM......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tube', role: 'body' },
        S: { name: 'wire_stock', role: 'belt' },
        R: { name: 'tube_receiver', role: 'head' },
        G: { name: 'pistol_grip', role: 'accessory' },
        M: { name: 'box_magazine', role: 'arm' },
        T: { name: 'trigger_guard', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
