/**
 * Guns batch 1 — 20 pistol & revolver templates.
 * Category: weapons (handguns, side-profile, barrel pointing right).
 * Steel grays for barrels, wood browns for grips, brass for accents,
 * chrome for highlights, themed colors for special variants.
 * All 16x16, DB16 palette only. Chunky pixel art, 28-45% density.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'weapons',
  exportNames: { templates: 'GUNS_BATCH1_TEMPLATES', schemes: 'GUNS_BATCH1_COLOR_SCHEMES' },
  templates: [

    // --- 1. REVOLVER CLASSIC -----------------------------------------------
    {
      id: 'revolver_classic_gn_16',
      description: 'Classic six-shooter revolver with thick cylinder, curved grip, and front sight.',
      grid: [
        '................',
        '................',
        '.......SS.......',
        '....BBBBBBBBBBB.',
        '....BBBBBBBBBBB.',
        '....BBBBBBBBBBB.',
        '...CCCCCBBBBBB..',
        '...CCCCCTTBBBB..',
        '...CCCCC.TTBB...',
        '...CCGGBB.......',
        '...GGGBB........',
        '..GGGGB.........',
        '..GGGG..........',
        '..GGG...........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_frame', role: 'body' },
        S: { name: 'front_sight', role: 'head' },
        C: { name: 'cylinder', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'wood_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 2. REVOLVER SNUBNOSE ----------------------------------------------
    {
      id: 'revolver_snubnose_gn_16',
      description: 'Compact snubnose revolver with stubby barrel, round cylinder, and rubber grip.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '...CCCCCBBBB....',
        '...CCCCCTTBB....',
        '...CCCCC.TBB....',
        '...CCGGBB.......',
        '..GGGGGB........',
        '..GGGGG.........',
        '..GGGG..........',
        '..GGG...........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_frame', role: 'body' },
        C: { name: 'cylinder', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'rubber_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // --- 3. SEMI AUTO 9MM --------------------------------------------------
    {
      id: 'semi_auto_9mm_gn_16',
      description: 'Modern semi-automatic 9mm pistol with boxy slide and polymer frame.',
      grid: [
        '................',
        '................',
        '................',
        '..SSSSSSSSSSS...',
        '..SSSSSSSSSSS...',
        '..SSSSSSSSSSS...',
        '..SSSSSSSSSSS...',
        '..FFFTTFSSSSF...',
        '..FFFF.TTF......',
        '..GGGFFF........',
        '..GGGGF.........',
        '..GGGGG.........',
        '..GGGG..........',
        '...GG...........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'slide_top', role: 'body' },
        F: { name: 'polymer_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'textured_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 4. DESERT EAGLE ---------------------------------------------------
    {
      id: 'desert_eagle_gn_16',
      description: 'Large heavy desert eagle pistol with long barrel, wide slide, and chrome finish.',
      grid: [
        '................',
        '................',
        '.SSSSSSSSSSSSSS.',
        '.SSSSSSSSSSSSSS.',
        '.SSSSSSSSSSSSSS.',
        '.SSSSSSSSSSSSSS.',
        '.FFFFTTFSSSSFF..',
        '.FFFFF.TTFF.....',
        '.GGGFFFF........',
        '.GGGGGFF........',
        '.GGGGGG.........',
        '.GGGGG..........',
        '..GGGG..........',
        '..GGG...........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'chrome_slide', role: 'body' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'rubber_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 5. FLINTLOCK PISTOL -----------------------------------------------
    {
      id: 'flintlock_pistol_gn_16',
      description: 'Historical flintlock pistol with ornate wooden stock, brass hardware, and wide bore.',
      grid: [
        '................',
        '................',
        '................',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '....BBBBBBBBBB..',
        '..HHHFFBBBBBB...',
        '..HHH.FFFBB.....',
        '..WWWWWFFF......',
        '.WWWWWWWF.......',
        '.WWWWWWWW.......',
        '.WWWWWWW........',
        '..WWWWWW........',
        '..WWWW..........',
        '...WW...........',
        '................',
      ],
      chars: {
        B: { name: 'barrel_steel', role: 'body' },
        H: { name: 'hammer_flint', role: 'head' },
        F: { name: 'brass_frizzen', role: 'accessory' },
        W: { name: 'wood_stock', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 6. DERRINGER ------------------------------------------------------
    {
      id: 'derringer_gn_16',
      description: 'Small two-shot over-under derringer with pearl grip and chrome barrels.',
      grid: [
        '................',
        '................',
        '................',
        '......BBBBBB....',
        '......BBBBBB....',
        '......BBBBBB....',
        '......BBBBBB....',
        '......BBBBBB....',
        '......BBBBBB....',
        '....FFTTBBB.....',
        '....FFF.TTB.....',
        '...GGGFF........',
        '...GGGGG........',
        '...GGGG.........',
        '....GG..........',
        '................',
      ],
      chars: {
        B: { name: 'barrel_steel', role: 'body' },
        F: { name: 'frame_hinge', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'pearl_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 7. LUGER PISTOL ---------------------------------------------------
    {
      id: 'luger_pistol_gn_16',
      description: 'WW2 era Luger pistol with distinctive toggle-lock action and angled grip.',
      grid: [
        '................',
        '................',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '...SSSBBBBBBB...',
        '...SSSFFTTBBB...',
        '...FFFFF.TTB....',
        '..GGGFFFF.......',
        '..GGGGFF........',
        '..GGGGG.........',
        '.GGGGG..........',
        '.GGGG...........',
        '.GGG............',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_body', role: 'body' },
        S: { name: 'toggle_lock', role: 'head' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'wood_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 8. COLT 1911 ------------------------------------------------------
    {
      id: 'colt_1911_gn_16',
      description: 'Classic M1911 military pistol with beaver tail, slide serrations, and walnut grip.',
      grid: [
        '................',
        '................',
        '..BSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..FFFFTTSSSFF...',
        '..FFFFF.TTFF....',
        '..GGGFFFF.......',
        '..GGGGGF........',
        '..GGGGG.........',
        '..GGGGG.........',
        '...GGG..........',
        '...GG...........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'slide_body', role: 'body' },
        B: { name: 'beaver_tail', role: 'head' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'walnut_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 9. BERETTA PISTOL -------------------------------------------------
    {
      id: 'beretta_pistol_gn_16',
      description: 'Modern Beretta-style pistol with exposed barrel top and rounded trigger guard.',
      grid: [
        '................',
        '................',
        '..EESSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..FFFFTTSSSFF...',
        '..FFFFF.TTFF....',
        '..GGGFFFF.......',
        '..GGGGFF........',
        '..GGGGG.........',
        '..GGGGG.........',
        '...GGG..........',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'slide_body', role: 'body' },
        E: { name: 'exposed_barrel', role: 'head' },
        F: { name: 'alloy_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'plastic_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // --- 10. SILENCED PISTOL -----------------------------------------------
    {
      id: 'silenced_pistol_gn_16',
      description: 'Tactical pistol with long threaded suppressor and low-profile sights.',
      grid: [
        '................',
        '................',
        'PPPPPPSSSSSSS...',
        'PPPPPPSSSSSSS...',
        'PPPPPPSSSSSSSS..',
        'PPPPPPSSSSSSSS..',
        '......FFFTTSSF..',
        '......FFFF.TTF..',
        '......GGGFFF....',
        '......GGGGGF....',
        '......GGGGG.....',
        '......GGGGG.....',
        '.......GGG......',
        '........GG......',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'suppressor', role: 'head' },
        S: { name: 'slide_body', role: 'body' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'tactical_grip', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 11. WATER PISTOL --------------------------------------------------
    {
      id: 'water_pistol_gn_16',
      description: 'Colorful toy water gun with wide nozzle, tank reservoir, and bright colors.',
      grid: [
        '................',
        '................',
        '....NN..........',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '...BBBRRRRRBBB..',
        '...BRRRRRTTTBB..',
        '...BBRR..TTB....',
        '...GGBBBB.......',
        '..GGGGGB........',
        '..GGGGG.........',
        '..GGGG..........',
        '...GG...........',
        '................',
        '................',
      ],
      chars: {
        N: { name: 'nozzle_tip', role: 'head' },
        B: { name: 'plastic_body', role: 'body' },
        R: { name: 'water_tank', role: 'arm' },
        T: { name: 'trigger_pump', role: 'accessory' },
        G: { name: 'orange_grip', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // --- 12. FLARE GUN -----------------------------------------------------
    {
      id: 'flare_gun_gn_16',
      description: 'Orange emergency flare gun with wide bore barrel and chunky grip.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBBB....',
        '...RRRBBBBBB....',
        '...RRRBBBBBB....',
        '...RRRBBBBBB....',
        '...RRRBBBBBB....',
        '...FFFTTRRR.....',
        '...FFFF.TTF.....',
        '..GGGFFF........',
        '..GGGGG.........',
        '..GGGGG.........',
        '..GGGG..........',
        '...GG...........',
        '................',
      ],
      chars: {
        B: { name: 'wide_barrel', role: 'body' },
        R: { name: 'receiver_hinge', role: 'head' },
        F: { name: 'frame_body', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'rubber_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // --- 13. NAIL GUN ------------------------------------------------------
    {
      id: 'nail_gun_gn_16',
      description: 'Industrial yellow nail gun tool with magazine strip and safety nose.',
      grid: [
        '................',
        '.NN.............',
        '.NNNBBBBBBBB....',
        '.BBBBBBBBBBB....',
        '.BBBBBBBBBBB....',
        '.BBBBBBBBBB.....',
        '.BBBBBBBBB......',
        '.MMMTTBBBBB.....',
        '.MMM.TTBBB......',
        '.MMM.GGGBB......',
        '.MMM.GGGGG......',
        '.MMM.GGGGG......',
        '......GGGG......',
        '.......GG.......',
        '................',
        '................',
      ],
      chars: {
        N: { name: 'safety_nose', role: 'head' },
        B: { name: 'yellow_body', role: 'body' },
        M: { name: 'nail_magazine', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'rubber_grip', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // --- 14. MACHINE PISTOL ------------------------------------------------
    {
      id: 'machine_pistol_gn_16',
      description: 'Compact automatic machine pistol with extended magazine and foregrip.',
      grid: [
        '................',
        '................',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..FFFTTFSSSSSF..',
        '..FFFF.TTFF.....',
        '..GGGFFFF.......',
        '..GGGGGF........',
        '..GGGGG.........',
        '..MMMGG.........',
        '..MMMG..........',
        '..MMM...........',
        '..MMM...........',
        '................',
      ],
      chars: {
        S: { name: 'slide_body', role: 'body' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'extended_mag', role: 'head' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#757161' },
      },
    },

    // --- 15. COWBOY REVOLVER -----------------------------------------------
    {
      id: 'cowboy_revolver_gn_16',
      description: 'Long-barrel western peacemaker revolver with ivory grip and brass frame.',
      grid: [
        '................',
        '................',
        '........SS......',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '..CCCCCCBBBBB...',
        '..CCCCCCTTBBBB..',
        '..CCCCCC.TTBB...',
        '..CCGGGBB.......',
        '..GGGGGB........',
        '.GGGGG..........',
        '.GGGG...........',
        '.GGG............',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_frame', role: 'body' },
        S: { name: 'front_sight', role: 'head' },
        C: { name: 'cylinder', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'ivory_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 16. PIRATE PISTOL -------------------------------------------------
    {
      id: 'pirate_pistol_gn_16',
      description: 'Ornate pirate flintlock with gold trim, flared barrel, and carved stock.',
      grid: [
        '................',
        '................',
        '....AABBBBBBBB..',
        '....AABBBBBBBB..',
        '....AABBBBBBBB..',
        '..HHHFFBBBBBBA..',
        '..HHH.FFFBBA....',
        '..WWWWWFFFA.....',
        '.WWWWWWWFF......',
        '.WWAWWWWW.......',
        '.WWWWWWWW.......',
        '.WWWWWWW........',
        '..WWWWW.........',
        '..WWWW..........',
        '...WW...........',
        '................',
      ],
      chars: {
        B: { name: 'barrel_steel', role: 'body' },
        A: { name: 'gold_filigree', role: 'accessory' },
        H: { name: 'hammer_flint', role: 'head' },
        F: { name: 'brass_lock', role: 'arm' },
        W: { name: 'carved_stock', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 17. SCIFI PISTOL --------------------------------------------------
    {
      id: 'scifi_pistol_gn_16',
      description: 'Futuristic energy pistol with glowing barrel, angular frame, and holographic sight.',
      grid: [
        '................',
        '................',
        '........HH......',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..FFFTTFBBBBBB..',
        '..FFFF.TTFF.....',
        '..GGGFFFF.......',
        '..GGGGGF........',
        '..GGGGG.........',
        '..GGGG..........',
        '...GG...........',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'energy_barrel', role: 'head' },
        B: { name: 'angular_frame', role: 'body' },
        H: { name: 'holo_sight', role: 'accessory' },
        F: { name: 'alloy_receiver', role: 'arm' },
        T: { name: 'trigger_guard', role: 'belt' },
        G: { name: 'tech_grip', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 18. STEAMPUNK PISTOL ----------------------------------------------
    {
      id: 'steampunk_pistol_gn_16',
      description: 'Brass and copper Victorian pistol with visible gears, pipe barrel, and wood grip.',
      grid: [
        '................',
        '................',
        '..PPP...........',
        '..PPPBBBBBBBBB..',
        '..PPPBBBBBBBBB..',
        '..PPPBBBBBBBBB..',
        '..GGGBBBBBBBB...',
        '..GGGBFFTTBBBB..',
        '..FFFFF.TTFB....',
        '.WWWWFFFF.......',
        '.WWWWWWF........',
        '.WWWWWW.........',
        '.WWWWW..........',
        '..WWW...........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'brass_barrel', role: 'body' },
        P: { name: 'steam_pipes', role: 'head' },
        G: { name: 'copper_gears', role: 'accessory' },
        F: { name: 'copper_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'belt' },
        W: { name: 'wood_grip', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 19. DOUBLE BARREL PISTOL ------------------------------------------
    {
      id: 'double_barrel_pistol_gn_16',
      description: 'Over-under double barrel derringer pistol with nickel finish and pearl panels.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '.....BBBBBBB....',
        '...FFTTBBBB.....',
        '...FFF.TTBB.....',
        '..GGGGFFF.......',
        '..GGGGGF........',
        '..GGGGG.........',
        '..GGGG..........',
        '...GG...........',
      ],
      chars: {
        B: { name: 'twin_barrels', role: 'body' },
        F: { name: 'nickel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'pearl_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 20. TARGET PISTOL -------------------------------------------------
    {
      id: 'target_pistol_gn_16',
      description: 'Competition target pistol with long barrel, adjustable sights, and ergonomic weighted grip.',
      grid: [
        '................',
        '................',
        '.HH.............',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '.FFFFTTFBBBBF...',
        '.FFFFF.TTFF.....',
        '.GGGFFFF........',
        '.GGGGGF.........',
        '.GGGGG..........',
        '.GGGGGG.........',
        'GGGGGGG.........',
        '.GGGGG..........',
        '................',
      ],
      chars: {
        B: { name: 'long_barrel', role: 'body' },
        H: { name: 'target_sight', role: 'head' },
        F: { name: 'steel_frame', role: 'arm' },
        T: { name: 'trigger_guard', role: 'accessory' },
        G: { name: 'ergonomic_grip', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
