/**
 * Guns batch 2 — 20 rifles & long guns (side profile, barrel pointing right).
 * Diagonal layout: stock at bottom-left, barrel at upper-right for max visual span.
 * Covers: assault rifle, AK-47, sniper, hunting, musket, lever-action, bolt-action,
 *         battle rifle, carbine, DMR, bullpup, anti-material, sci-fi, steampunk,
 *         blunderbuss, modern crossbow, gauss, ice, fire, railgun.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: { templates: 'GUNS_BATCH2_TEMPLATES', schemes: 'GUNS_BATCH2_COLOR_SCHEMES' },
  templates: [

    // --- 1. ASSAULT RIFLE (M4/AR-15 style) --------------------------------
    {
      id: 'assault_rifle_gn_16',
      description: 'Modern assault rifle with picatinny rail, polymer furniture, and detachable magazine.',
      grid: [
        '................',
        '..........RRR...',
        '.........RBBBBBA',
        '........BBBBBBB.',
        '.......BBBBBA...',
        '......BBBBB.....',
        '.....BBBBBA.....',
        '....BBBBB.......',
        '...BBBMMM.......',
        '..GGBBMM........',
        '..GGGBB.........',
        '.SSGGG..........',
        '.SSSS...........',
        'SSSSS...........',
        'SSSS............',
        '................',
      ],
      chars: {
        B: { name: 'receiver_barrel', role: 'body' },
        R: { name: 'rail_system', role: 'head' },
        S: { name: 'polymer_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'magazine', role: 'arm' },
        A: { name: 'accessories', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // --- 2. AK-47 RIFLE ---------------------------------------------------
    {
      id: 'ak47_rifle_gn_16',
      description: 'Iconic AK-47 with curved banana magazine, wooden stock and handguard.',
      grid: [
        '................',
        '...........BBBA.',
        '..........BBBBB.',
        '.........BWWWBB.',
        '........BWWWBB..',
        '.......BBBBBB...',
        '......BBBBB.....',
        '.....BBBBA......',
        '....BBBMMM......',
        '...GGBMMM.......',
        '...GGGBB........',
        '..SSSGG.........',
        '..SSSS..........',
        '.SSSSS..........',
        '.SSSS...........',
        '................',
      ],
      chars: {
        B: { name: 'metal_receiver', role: 'body' },
        W: { name: 'wood_handguard', role: 'arm' },
        S: { name: 'wood_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'curved_magazine', role: 'head' },
        A: { name: 'front_sight', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // --- 3. SNIPER RIFLE --------------------------------------------------
    {
      id: 'sniper_rifle_gn_16',
      description: 'Long-barrel bolt-action sniper rifle with magnified scope and bipod legs.',
      grid: [
        '................',
        '.............BBB',
        '..........SSBBB.',
        '.........SSBBBB.',
        '........SBBBBB..',
        '.......BBBBB....',
        '......BBBBBA....',
        '.....BBBBA.A....',
        '....BBBMMM......',
        '...GGBBMM.......',
        '..GGGBB.........',
        '.TTTGG..........',
        '.TTTT...........',
        'TTTTT...........',
        'TTTT............',
        '................',
      ],
      chars: {
        B: { name: 'rifle_body', role: 'body' },
        S: { name: 'scope', role: 'head' },
        T: { name: 'tactical_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'magazine', role: 'arm' },
        A: { name: 'bipod', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // --- 4. HUNTING RIFLE -------------------------------------------------
    {
      id: 'hunting_rifle_gn_16',
      description: 'Classic wooden stock hunting rifle with blued barrel, iron sights, and trigger guard.',
      grid: [
        '................',
        '.............ABB',
        '............BBBB',
        '...........BBBBB',
        '..........BBBBB.',
        '.........BBBBB..',
        '........BFFBB...',
        '.......BFFBB....',
        '......WWWWW.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWW..........',
        '.WWWW...........',
        '................',
      ],
      chars: {
        B: { name: 'blued_barrel', role: 'body' },
        W: { name: 'walnut_stock', role: 'leg' },
        F: { name: 'barrel_band', role: 'arm' },
        G: { name: 'trigger_guard', role: 'belt' },
        A: { name: 'iron_sight', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // --- 5. MUSKET WITH BAYONET -------------------------------------------
    {
      id: 'musket_gn_16',
      description: 'Historical flintlock musket with fixed bayonet, brass fittings, and wooden stock.',
      grid: [
        '..............AA',
        '.............ABB',
        '............BBBB',
        '...........BBBB.',
        '..........BBBBB.',
        '.........FBBF...',
        '........FBBF....',
        '.......BBBF.....',
        '......BBBB......',
        '.....GBBB.......',
        '....GGWW........',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWWW.........',
        '.WWWWW..........',
        '.WWWW...........',
      ],
      chars: {
        B: { name: 'barrel_body', role: 'body' },
        W: { name: 'wooden_stock', role: 'leg' },
        A: { name: 'bayonet_blade', role: 'accessory' },
        F: { name: 'brass_fittings', role: 'belt' },
        G: { name: 'flintlock', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // --- 6. LEVER-ACTION RIFLE (Winchester) --------------------------------
    {
      id: 'lever_action_gn_16',
      description: 'Winchester-style lever-action rifle with octagonal barrel and brass receiver.',
      grid: [
        '................',
        '.............BBB',
        '............BBBB',
        '...........FBBB.',
        '..........FFFBB.',
        '.........FFFBB..',
        '........FFFFL...',
        '.......FFFLL....',
        '......WWWWL.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWW..........',
        '.WWWW...........',
        '................',
      ],
      chars: {
        B: { name: 'octagonal_barrel', role: 'body' },
        F: { name: 'brass_receiver', role: 'head' },
        W: { name: 'walnut_stock', role: 'leg' },
        L: { name: 'lever_action', role: 'arm' },
        G: { name: 'trigger_guard', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // --- 7. BOLT-ACTION RIFLE (Kar98 style) --------------------------------
    {
      id: 'bolt_action_gn_16',
      description: 'WW2-era bolt-action rifle with turned-down bolt handle and full wood stock.',
      grid: [
        '................',
        '.............BBB',
        '............BBBB',
        '...........BBBBB',
        '..........BBHBB.',
        '.........BBBHB..',
        '........BBBBB...',
        '.......BBBBB....',
        '......WWWWW.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWWW.........',
        '.WWWWW..........',
        '.WWWW...........',
      ],
      chars: {
        B: { name: 'blued_receiver', role: 'body' },
        W: { name: 'beech_stock', role: 'leg' },
        H: { name: 'bolt_handle', role: 'arm' },
        G: { name: 'trigger_guard', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 8. BATTLE RIFLE WITH BIPOD ---------------------------------------
    {
      id: 'battle_rifle_gn_16',
      description: 'Heavy battle rifle with bipod, large magazine, and picatinny rail.',
      grid: [
        '................',
        '.........RRR....',
        '........RBBBBBB.',
        '.......BBBBBBBB.',
        '......BBBBBBA.A.',
        '.....BBBBBB.....',
        '....BBBBBB......',
        '...BBBBBMM......',
        '..GGBBMMM.......',
        '..GGGBB.........',
        '.SSSGG..........',
        '.SSSSS..........',
        'SSSSSS..........',
        'SSSSS...........',
        'SSSS............',
        '................',
      ],
      chars: {
        B: { name: 'rifle_receiver', role: 'body' },
        R: { name: 'rail_optic', role: 'head' },
        S: { name: 'heavy_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'large_magazine', role: 'arm' },
        A: { name: 'bipod_legs', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // --- 9. COMPACT CARBINE -----------------------------------------------
    {
      id: 'carbine_short_gn_16',
      description: 'Compact tactical carbine with folding stock, short barrel, and red dot sight.',
      grid: [
        '................',
        '................',
        '.........RR.....',
        '........RBBBBBB.',
        '.......BBBBBBB..',
        '......BBBBBBB...',
        '.....BBBBB......',
        '....BBBBBA......',
        '...BBBMMM.......',
        '..GGBBMM........',
        '..GGGBB.........',
        '.SSSGG..........',
        '.SSSS...........',
        'SSSS............',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'short_receiver', role: 'body' },
        R: { name: 'red_dot_sight', role: 'head' },
        S: { name: 'folding_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'magazine', role: 'arm' },
        A: { name: 'flashlight', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // --- 10. DMR (Designated Marksman Rifle) --------------------------------
    {
      id: 'dmr_rifle_gn_16',
      description: 'Designated marksman rifle with variable scope, long barrel, and ergonomic stock.',
      grid: [
        '................',
        '...........SSSB.',
        '..........SSBBB.',
        '.........SSBBBB.',
        '........BBBBBB..',
        '.......BBBBBA...',
        '......BBBBBBA...',
        '.....BBBBB......',
        '....BBBMMM......',
        '...GGBBMM.......',
        '..GGGBB.........',
        '.TTTGG..........',
        '.TTTTT..........',
        'TTTTTT..........',
        'TTTTT...........',
        '................',
      ],
      chars: {
        B: { name: 'match_barrel', role: 'body' },
        S: { name: 'variable_scope', role: 'head' },
        T: { name: 'ergo_stock', role: 'leg' },
        G: { name: 'angled_grip', role: 'belt' },
        M: { name: 'long_magazine', role: 'arm' },
        A: { name: 'muzzle_brake', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 11. BULLPUP RIFLE ------------------------------------------------
    {
      id: 'bullpup_rifle_gn_16',
      description: 'Bullpup assault rifle with magazine behind trigger, integrated carry handle.',
      grid: [
        '................',
        '................',
        '.........HBBBBB.',
        '........HBBBBBB.',
        '.......BBBBBBB..',
        '......BBBBBBB...',
        '.....BBBBBB.....',
        '....BBGBBB......',
        '...BBBGBBB......',
        '..MMMBBBBB......',
        '..MMMBB.........',
        '.MMMSSSS........',
        '.MMSSSS.........',
        '..SSSS..........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'polymer_body', role: 'body' },
        H: { name: 'carry_handle', role: 'head' },
        S: { name: 'buttpad', role: 'leg' },
        G: { name: 'trigger_grip', role: 'belt' },
        M: { name: 'rear_magazine', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 12. ANTI-MATERIAL RIFLE ------------------------------------------
    {
      id: 'anti_material_gn_16',
      description: 'Massive anti-material rifle with oversized barrel, muzzle brake, and bipod.',
      grid: [
        '..............AA',
        '.............ABB',
        '............BBBB',
        '...........BBBBB',
        '..........BBBBB.',
        '.........BBBBBB.',
        '........RBBBB...',
        '.......RBBBA.A..',
        '......BBBBBA....',
        '.....GBBMMM.....',
        '....GGBBMM......',
        '...SSSGG........',
        '..SSSSS.........',
        '.SSSSSS.........',
        '.SSSSS..........',
        'SSSSS...........',
      ],
      chars: {
        B: { name: 'heavy_receiver', role: 'body' },
        R: { name: 'scope_rail', role: 'head' },
        S: { name: 'padded_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        M: { name: 'box_magazine', role: 'arm' },
        A: { name: 'muzzle_bipod', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // --- 13. SCI-FI ENERGY RIFLE ------------------------------------------
    {
      id: 'scifi_rifle_gn_16',
      description: 'Futuristic energy rifle with glowing power cell, holographic sight, and plasma barrel.',
      grid: [
        '................',
        '..........HH....',
        '.........HCCCCC.',
        '........CCCCCCC.',
        '.......CCCCCCEE.',
        '......CCCCCC....',
        '.....CCCCCC.....',
        '....CCCCGC......',
        '...CCPPMM.......',
        '..GGCCMM........',
        '..GGGCC.........',
        '.SSSGG..........',
        '.SSSSS..........',
        'SSSSS...........',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'composite_body', role: 'body' },
        H: { name: 'holo_sight', role: 'head' },
        S: { name: 'ergo_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        P: { name: 'power_cell', role: 'arm' },
        M: { name: 'energy_mag', role: 'arm' },
        E: { name: 'energy_emitter', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#6dc2ca', highlight: '#dad45e' },
      },
    },

    // --- 14. STEAMPUNK RIFLE ----------------------------------------------
    {
      id: 'steampunk_rifle_gn_16',
      description: 'Victorian steampunk long gun with brass pipes, copper receiver, and steam vents.',
      grid: [
        '................',
        '.............PPP',
        '............PBBB',
        '...........BBBBB',
        '..........BBBBB.',
        '.........FBBVV..',
        '........FFFBB...',
        '.......FFFBV....',
        '......FFFFF.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWWW.........',
        '.WWWWW..........',
        '................',
      ],
      chars: {
        B: { name: 'copper_receiver', role: 'body' },
        F: { name: 'brass_fittings', role: 'head' },
        W: { name: 'mahogany_stock', role: 'leg' },
        G: { name: 'trigger_mech', role: 'belt' },
        P: { name: 'brass_pipes', role: 'arm' },
        V: { name: 'steam_vents', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 15. BLUNDERBUSS --------------------------------------------------
    {
      id: 'blunderbuss_gn_16',
      description: 'Wide flared muzzle blunderbuss with brass bell, wooden stock, and flintlock mechanism.',
      grid: [
        '................',
        '.........AAAAAA.',
        '........AAAAAAA.',
        '.........AAAAA..',
        '..........BBBB..',
        '.........BBBBB..',
        '........BBBBB...',
        '.......FFBBF....',
        '......FFBBF.....',
        '.....GFBBF......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWW.........',
        '.WWWWWW.........',
        '.WWWWW..........',
        '................',
      ],
      chars: {
        A: { name: 'flared_muzzle', role: 'head' },
        B: { name: 'barrel_body', role: 'body' },
        W: { name: 'wooden_stock', role: 'leg' },
        F: { name: 'brass_bands', role: 'arm' },
        G: { name: 'flintlock', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // --- 16. MODERN TACTICAL CROSSBOW -------------------------------------
    {
      id: 'crossbow_modern_gn_16',
      description: 'Modern tactical crossbow with cam limbs, scope, and bolt rail.',
      grid: [
        '.........LLL....',
        '........LLLL....',
        '.........LRRR...',
        '..........RRRR..',
        '.........BBRRR..',
        '........BBBBR...',
        '.......BBBBSS...',
        '......BBBBS.....',
        '.....BBBBB......',
        '....GGBBBB......',
        '...GGBBB........',
        '..TTGGG.........',
        '.TTTTT..........',
        '.TTTT...........',
        'LLLL............',
        '.LLL............',
      ],
      chars: {
        B: { name: 'rail_body', role: 'body' },
        L: { name: 'cam_limbs', role: 'head' },
        R: { name: 'bolt_string', role: 'arm' },
        T: { name: 'tactical_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        S: { name: 'scope_mount', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 17. GAUSS RIFLE --------------------------------------------------
    {
      id: 'gauss_rifle_gn_16',
      description: 'Electromagnetic accelerator rifle with visible coil rings and power conduit.',
      grid: [
        '................',
        '...........CBBBB',
        '..........CBBBB.',
        '.........CBBCBB.',
        '........CBBBCB..',
        '.......CBBBB....',
        '......CBBBBB....',
        '.....BBBBBB.....',
        '....BBBPPP......',
        '...GGBPPP.......',
        '..GGBBB.........',
        '.SSSGG..........',
        '.SSSSS..........',
        'SSSSS...........',
        'SSSS............',
        '................',
      ],
      chars: {
        B: { name: 'rifle_housing', role: 'body' },
        C: { name: 'em_coils', role: 'head' },
        S: { name: 'tech_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        P: { name: 'power_conduit', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#dad45e' },
      },
    },

    // --- 18. ICE RIFLE ----------------------------------------------------
    {
      id: 'ice_rifle_gn_16',
      description: 'Fantasy ice-themed rifle with crystal barrel, frozen stock, and frost accents.',
      grid: [
        '..............CC',
        '.............CBB',
        '............CBBB',
        '...........BBBBB',
        '..........BBBBB.',
        '.........BBBFF..',
        '........BBBF....',
        '.......BBBBB....',
        '......WWWWW.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWC.........',
        '.WWWCC..........',
        '.WWCC...........',
        '..CC............',
      ],
      chars: {
        B: { name: 'ice_metal_body', role: 'body' },
        C: { name: 'ice_crystals', role: 'head' },
        W: { name: 'frozen_stock', role: 'leg' },
        G: { name: 'frost_grip', role: 'belt' },
        F: { name: 'frost_accents', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // --- 19. FIRE RIFLE ---------------------------------------------------
    {
      id: 'fire_rifle_gn_16',
      description: 'Fantasy fire-themed rifle with flame barrel, ember stock, and molten accents.',
      grid: [
        '..............FF',
        '.............FBB',
        '............FBBB',
        '...........BBBBB',
        '..........BBBBB.',
        '.........BBBAA..',
        '........BBBA....',
        '.......BBBBB....',
        '......WWWWW.....',
        '.....GWWWW......',
        '....GGWWW.......',
        '...WWWWW........',
        '..WWWWF.........',
        '.WWWFF..........',
        '.WWFF...........',
        '..FF............',
      ],
      chars: {
        B: { name: 'heated_metal', role: 'body' },
        F: { name: 'flame_elements', role: 'head' },
        W: { name: 'charred_stock', role: 'leg' },
        G: { name: 'ember_grip', role: 'belt' },
        A: { name: 'molten_accents', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#854c30', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // --- 20. RAILGUN ------------------------------------------------------
    {
      id: 'railgun_gn_16',
      description: 'Heavy electromagnetic railgun with parallel rails, power pack, and capacitor banks.',
      grid: [
        '................',
        '............RRBR',
        '...........RRBBR',
        '..........RRBBB.',
        '.........RBBBB..',
        '........BBBBBR..',
        '.......BBBBBB...',
        '......BBBBBB....',
        '.....PPBBBB.....',
        '....PPGGBB......',
        '...PPPGGB.......',
        '..SSSSG.........',
        '.SSSSS..........',
        'SSSSSS..........',
        'SSSSS...........',
        '................',
      ],
      chars: {
        B: { name: 'main_housing', role: 'body' },
        R: { name: 'conductive_rails', role: 'head' },
        S: { name: 'heavy_stock', role: 'leg' },
        G: { name: 'pistol_grip', role: 'belt' },
        P: { name: 'power_pack', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
