/**
 * Guns batch 4 — 20 Heavy & Explosive weapons.
 * Covers: RPG launcher, minigun, grenade launcher, mortar, bazooka,
 *         Gatling gun, M60 LMG, PKM LMG, heavy MG, flamethrower,
 *         frag grenade, smoke grenade, C4 charge, dynamite bundle,
 *         claymore mine, missile launcher, sci-fi cannon, tesla gun,
 *         cryo cannon, acid launcher.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: { templates: 'GUNS_BATCH4_TEMPLATES', schemes: 'GUNS_BATCH4_COLOR_SCHEMES' },
  templates: [

    // --- 1. RPG LAUNCHER ---------------------------------------------------
    {
      id: 'rpg_launcher_gn_16',
      description: 'RPG-7 rocket launcher with conical warhead, tube body, and rear grip.',
      grid: [
        '................',
        '................',
        '................',
        '..WWHHH.........',
        '.WWTTTTTTTTT....',
        '.WWTTTTTTTTTT...',
        '..WTTTTTTTTTTT..',
        '..TTTTTTTTTTTRR.',
        '..TTTTTTTTTTTRR.',
        '..TTTGGTTTTTTT..',
        '...TTTGGTTTTT...',
        '....TTTT........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'warhead_cone', role: 'head' },
        H: { name: 'warhead_tip', role: 'accessory' },
        T: { name: 'tube_body', role: 'body' },
        G: { name: 'grip_handle', role: 'arm' },
        R: { name: 'rear_exhaust', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 2. MINIGUN ---------------------------------------------------------
    {
      id: 'minigun_gn_16',
      description: 'Multi-barrel rotary minigun with thick barrel cluster and rear motor housing.',
      grid: [
        '................',
        '................',
        '................',
        '..BBBB..........',
        '..BBBBB.........',
        '.BBBBBMMMMM.....',
        '.BBBBBMMMMMRR...',
        '.BBBBBMMMMMRRRR.',
        '.BBBBBMMMMMRRRR.',
        '.BBBBBMMMMMRR...',
        '.BBBBBMMMMM.....',
        '..BBBBB.........',
        '..BBBBGGGG......',
        '......GGGG......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_cluster', role: 'body' },
        M: { name: 'motor_housing', role: 'head' },
        R: { name: 'rear_assembly', role: 'accessory' },
        G: { name: 'grip_handle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#4e4a4e', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 3. GRENADE LAUNCHER ------------------------------------------------
    {
      id: 'grenade_launcher_gn_16',
      description: 'M79 single-shot break-action grenade launcher with wide bore and wooden stock.',
      grid: [
        '................',
        '................',
        '................',
        '..BBBBB.........',
        '.BBBBBBMMMMM....',
        '.BBBBBMMMMMMSS..',
        '.BBBBBMMMMMMSSS.',
        '..BBBMMMMMMMSSS.',
        '...BMMMMMMMMSSS.',
        '....MMMMMMMMSS..',
        '....MMMGG.......',
        '.....GGGG.......',
        '......GG........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'wide_bore', role: 'head' },
        M: { name: 'receiver_body', role: 'body' },
        S: { name: 'wooden_stock', role: 'accessory' },
        G: { name: 'grip_trigger', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // --- 4. MORTAR TUBE -----------------------------------------------------
    {
      id: 'mortar_tube_gn_16',
      description: 'Infantry mortar tube on bipod base plate with round shell at top.',
      grid: [
        '.....RRR........',
        '....RRRRR.......',
        '.....TTT........',
        '.....TTT........',
        '.....TTT........',
        '.....TTT........',
        '.....TTT........',
        '.....TTT........',
        '....TTTTT.......',
        '....TTTTT.......',
        '...LLTTTLL......',
        '..LL.TTT.LL.....',
        '.LL..TTT..LL....',
        '.LL.PPPPPP.LL...',
        '...PPPPPPPP.....',
        '...PPPPPPPP.....',
      ],
      chars: {
        R: { name: 'mortar_round', role: 'head' },
        T: { name: 'mortar_tube', role: 'body' },
        L: { name: 'bipod_legs', role: 'accessory' },
        P: { name: 'base_plate', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 5. BAZOOKA ---------------------------------------------------------
    {
      id: 'bazooka_gn_16',
      description: 'Classic bazooka tube launcher with front sight and shoulder rest.',
      grid: [
        '................',
        '................',
        '................',
        '.FFF............',
        'FFFFTTTTTTTTTT..',
        'FFFFTTTTTTTTTSS.',
        'FFFFTTTTTTTTTSS.',
        '..FFTTTTTTTTTSS.',
        '..TTTTTTTTTTTSS.',
        '...TTTGGTTTT....',
        '....TTGGG.......',
        '.....GGG........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'front_sight', role: 'accessory' },
        T: { name: 'tube_body', role: 'body' },
        G: { name: 'grip_trigger', role: 'arm' },
        S: { name: 'shoulder_rest', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // --- 6. GATLING GUN -----------------------------------------------------
    {
      id: 'gatling_gun_gn_16',
      description: 'Historical hand-crank Gatling gun on wheeled carriage with brass receiver.',
      grid: [
        '................',
        '..BBB...........',
        '..BBBBB.........',
        '.BBBBBBBRRR.....',
        '.BBBBBBBRRR.....',
        '.BBBBBBBRRR.....',
        '.BBBBBBBRRR.....',
        '..BBBBBRRR......',
        '..BBBBBRRR..CC..',
        '...BBBRRR..CC...',
        '....RRRR..CC....',
        '....RRRR.CC.....',
        '...WWWWWWW......',
        '..WW.....WW.....',
        '.WW.......WW....',
        '................',
      ],
      chars: {
        B: { name: 'barrel_cluster', role: 'body' },
        R: { name: 'brass_receiver', role: 'head' },
        C: { name: 'hand_crank', role: 'accessory' },
        W: { name: 'wheel_carriage', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // --- 7. M60 LMG ---------------------------------------------------------
    {
      id: 'm60_lmg_gn_16',
      description: 'M60 light machine gun with ammo belt feed, bipod, and long barrel.',
      grid: [
        '................',
        '................',
        '................',
        '...BB...........',
        '..BBBMMMMMMM....',
        '..BBBMMMMMMMSS..',
        '...BMMMMMMMMSSS.',
        '...MMMMMMMMMSS..',
        '...MMMMGMMMMM...',
        '....MMMGGAAAA...',
        '...LLMGG.AAAA...',
        '..LL..G..AAA....',
        '.LL.....AA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_tip', role: 'head' },
        M: { name: 'receiver_body', role: 'body' },
        S: { name: 'stock_rear', role: 'accessory' },
        G: { name: 'grip_trigger', role: 'arm' },
        L: { name: 'bipod_legs', role: 'belt' },
        A: { name: 'ammo_belt', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // --- 8. PKM LMG ---------------------------------------------------------
    {
      id: 'pkm_lmg_gn_16',
      description: 'PKM machine gun with bipod deployed, wooden furniture, and ammo box.',
      grid: [
        '................',
        '................',
        '................',
        '...BBB..........',
        '..BBBMMMMMMM....',
        '..BBBMMMMMMMWW..',
        '...BMMMMMMMWWWW.',
        '...MMMMMMMWWWW..',
        '...MMMGMMMMM....',
        '...LLMGG........',
        '..LL..G.........',
        '.LL.............',
        '......AAAAAAA...',
        '......AAAAAAA...',
        '......AAAAAAA...',
        '................',
      ],
      chars: {
        B: { name: 'barrel_flash', role: 'head' },
        M: { name: 'metal_receiver', role: 'body' },
        W: { name: 'wooden_stock', role: 'accessory' },
        G: { name: 'grip_handle', role: 'arm' },
        L: { name: 'bipod_legs', role: 'belt' },
        A: { name: 'ammo_box', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
      },
    },

    // --- 9. HEAVY MG --------------------------------------------------------
    {
      id: 'heavy_mg_gn_16',
      description: 'Tripod-mounted heavy machine gun with thick barrel jacket and ammo feed.',
      grid: [
        '................',
        '................',
        '....BB..........',
        '...BBBBMMMM.....',
        '...BBBMMMMMMM...',
        '..BBBBMMMMMMM...',
        '..BBBMMMMMMMMR..',
        '...BBMMMGMMMR...',
        '....BMMGGGMM....',
        '....LLMGG.......',
        '...LL..GLLL.....',
        '..LL.....LLL....',
        '.LL.......LL....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel_jacket', role: 'head' },
        M: { name: 'receiver_body', role: 'body' },
        G: { name: 'grip_spade', role: 'arm' },
        R: { name: 'rear_sight', role: 'accessory' },
        L: { name: 'tripod_legs', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 10. FLAMETHROWER ---------------------------------------------------
    {
      id: 'flamethrower_gn_16',
      description: 'Flamethrower with fuel tank backpack, hose, and flame nozzle emitting fire.',
      grid: [
        '....FFF.........',
        '...FFFFF........',
        '..FFFFFF........',
        '..FFFNN.........',
        '.FFNNNHHHH......',
        '.FNNNNHHHHH.....',
        '..NNNHHHHHH.....',
        '...NNHHHHH.TT...',
        '....HHGGGH.TT...',
        '.....HGGG..TT...',
        '...........TT...',
        '..........TTTT..',
        '..........TTTT..',
        '..........TTTT..',
        '..........TTTT..',
        '................',
      ],
      chars: {
        F: { name: 'flame_burst', role: 'accessory' },
        N: { name: 'nozzle_tip', role: 'head' },
        H: { name: 'hose_pipe', role: 'body' },
        G: { name: 'grip_handle', role: 'arm' },
        T: { name: 'fuel_tank', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
      },
    },

    // --- 11. FRAG GRENADE ---------------------------------------------------
    {
      id: 'grenade_frag_gn_16',
      description: 'Pineapple-style fragmentation hand grenade with textured body and safety lever.',
      grid: [
        '................',
        '................',
        '......PP........',
        '.....PPLL.......',
        '.....SSLL.......',
        '....SSSS........',
        '...BBBBBB.......',
        '..BBBBBBBB......',
        '..BBRBBRBBB.....',
        '..BBBBBBBB......',
        '..BBRBBRBBB.....',
        '..BBBBBBBB......',
        '..BBRBBRBBB.....',
        '...BBBBBB.......',
        '....TTTT........',
        '................',
      ],
      chars: {
        P: { name: 'safety_pin', role: 'accessory' },
        L: { name: 'safety_lever', role: 'head' },
        S: { name: 'spoon_cap', role: 'arm' },
        B: { name: 'grenade_body', role: 'body' },
        R: { name: 'ridge_texture', role: 'belt' },
        T: { name: 'base_bottom', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#4e4a4e' },
      },
    },

    // --- 12. SMOKE GRENADE --------------------------------------------------
    {
      id: 'grenade_smoke_gn_16',
      description: 'Cylindrical smoke grenade canister with pull ring and vent holes.',
      grid: [
        '................',
        '.....SSS........',
        '....SSSSS.......',
        '....SRRRS.......',
        '....SSSSS.......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BBBVBBB......',
        '...BBBBBBB......',
        '...BBBVBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '....TTTTT.......',
        '................',
      ],
      chars: {
        S: { name: 'spoon_top', role: 'head' },
        R: { name: 'pull_ring', role: 'accessory' },
        B: { name: 'canister_body', role: 'body' },
        V: { name: 'vent_holes', role: 'arm' },
        T: { name: 'base_cap', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 13. C4 CHARGE ------------------------------------------------------
    {
      id: 'c4_charge_gn_16',
      description: 'C4 plastic explosive block with embedded detonator and blinking light.',
      grid: [
        '................',
        '................',
        '......WW........',
        '.....WWWW.......',
        '.....WLLW.......',
        '................',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBDDDDDDBB....',
        '..BBDDDDDDBB....',
        '..BBDDDDDDBB....',
        '..BBDDDDDDBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'detonator_wire', role: 'accessory' },
        L: { name: 'blink_light', role: 'head' },
        B: { name: 'c4_wrapper', role: 'body' },
        D: { name: 'explosive_clay', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 14. DYNAMITE BUNDLE ------------------------------------------------
    {
      id: 'dynamite_bundle_gn_16',
      description: 'Bundle of dynamite sticks tied together with lit fuse sparking at the top.',
      grid: [
        '......FF........',
        '.....FF.........',
        '.....FW.........',
        '......WW........',
        '......WW........',
        '....RRRRRR......',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '...RRLLLLRR.....',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '....RRRRRR......',
        '....TTTTTT......',
        '................',
      ],
      chars: {
        F: { name: 'fuse_spark', role: 'accessory' },
        W: { name: 'fuse_cord', role: 'head' },
        R: { name: 'dynamite_sticks', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        T: { name: 'base_caps', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // --- 15. CLAYMORE MINE --------------------------------------------------
    {
      id: 'claymore_mine_gn_16',
      description: 'Claymore directional mine with curved face, scissor legs, and detonator wire.',
      grid: [
        '................',
        '................',
        '................',
        '......WW........',
        '.....WW.........',
        '....WW..........',
        '..BBBBBBBBBB....',
        '..BFFFFFFFFB....',
        '..BFFFFFFFFB....',
        '..BFFFTTFFFB....',
        '..BFFFTTFFFB....',
        '..BFFFFFFFFB....',
        '..BBBBBBBBBB....',
        '..LL......LL....',
        '..LL......LL....',
        '................',
      ],
      chars: {
        W: { name: 'det_wire', role: 'accessory' },
        B: { name: 'casing_edge', role: 'body' },
        F: { name: 'front_face', role: 'head' },
        T: { name: 'label_text', role: 'arm' },
        L: { name: 'scissor_legs', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        head:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // --- 16. MISSILE LAUNCHER -----------------------------------------------
    {
      id: 'missile_launcher_gn_16',
      description: 'Shoulder-fired guided missile launcher with targeting scope and missile tip.',
      grid: [
        '................',
        '................',
        '................',
        '.MMMM...........',
        'MMMTTTTTTTTT....',
        'MMMTTTTTTTTTSS..',
        '.MMTTTTTTTTTSSS.',
        '..MTTTTTTTTTSS..',
        '..TTTTTPTTTT....',
        '...TTTPPGGTT....',
        '....TTTGG.......',
        '.....TG.........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'missile_tip', role: 'head' },
        T: { name: 'launcher_tube', role: 'body' },
        S: { name: 'rear_housing', role: 'accessory' },
        P: { name: 'targeting_scope', role: 'arm' },
        G: { name: 'grip_trigger', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 17. SCIFI CANNON ---------------------------------------------------
    {
      id: 'scifi_cannon_gn_16',
      description: 'Huge sci-fi energy cannon with glowing power cell, wide muzzle, and armored housing.',
      grid: [
        '................',
        '................',
        '..MMMM..........',
        '.MMMMM..........',
        'MMMMMAAAAAAA....',
        'MMMMMAAAAAAARR..',
        'MMMMMAAAAAAARR..',
        '.MMMMAAEAAAARR..',
        '.MMMMAAEAAAARR..',
        'MMMMMAAAAAAARR..',
        'MMMMMAAAAAAARR..',
        'MMMMMAAAAAAA....',
        '.MMMMM.GGG......',
        '..MMMM.GGG......',
        '........GG......',
        '................',
      ],
      chars: {
        M: { name: 'muzzle_wide', role: 'head' },
        A: { name: 'armored_housing', role: 'body' },
        E: { name: 'power_cell_glow', role: 'accessory' },
        R: { name: 'rear_vent', role: 'arm' },
        G: { name: 'grip_handle', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 18. TESLA GUN ------------------------------------------------------
    {
      id: 'tesla_gun_gn_16',
      description: 'Electricity-themed tesla gun with copper coil rings, arc emitter, and power cable.',
      grid: [
        '................',
        '................',
        '.EE.............',
        'EEEE............',
        '.EECCCMMM.......',
        '..CCCCMMMMM.....',
        '..CCCMMMMMMMRR..',
        '...CMMMMMMMMRR..',
        '...CMMMMMMMRR...',
        '..CCCMMMGMMM....',
        '..CCCCMMGG......',
        '.EECCMMGG.......',
        'EEEE............',
        '.EE.............',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'arc_emitter', role: 'accessory' },
        C: { name: 'copper_coils', role: 'head' },
        M: { name: 'gun_housing', role: 'body' },
        R: { name: 'rear_cable', role: 'arm' },
        G: { name: 'grip_handle', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // --- 19. CRYO CANNON ----------------------------------------------------
    {
      id: 'cryo_cannon_gn_16',
      description: 'Ice/freeze cannon with frost-venting muzzle, coolant tank, and icy highlights.',
      grid: [
        '................',
        '..FF............',
        '.FFFMM..........',
        '.FFMMMM.........',
        'FFMMMMMMMMM.....',
        '.FMMMMMMMMMMRR..',
        '..MMMMMMMMMMRR..',
        '..MMMMMMMMMMRR..',
        '..MMMMMGMMTTT...',
        '...MMMMGG.TTT...',
        '....MMMG..TTT...',
        '..........TTT...',
        '..........TTT...',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frost_muzzle', role: 'accessory' },
        M: { name: 'cannon_housing', role: 'body' },
        R: { name: 'rear_vent', role: 'head' },
        G: { name: 'grip_trigger', role: 'arm' },
        T: { name: 'coolant_tank', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // --- 20. ACID LAUNCHER --------------------------------------------------
    {
      id: 'acid_launcher_gn_16',
      description: 'Green acid/chemical launcher with transparent tank, dripping nozzle, and hazard markings.',
      grid: [
        '................',
        '..DD............',
        '..DNNMM.........',
        '..NNMMMM........',
        '..NMMMMMMM......',
        '..MMMMMMMMMMM...',
        '..MMMMMMMMMMM...',
        '..MMMMMMMGMMM...',
        '..MMMMMMGGTTT...',
        '...MMMMMG.TTT...',
        '..........THHT..',
        '..........THHT..',
        '..........THHT..',
        '..........TTTT..',
        '................',
        '................',
      ],
      chars: {
        D: { name: 'acid_drip', role: 'accessory' },
        N: { name: 'nozzle_tip', role: 'head' },
        M: { name: 'launcher_body', role: 'body' },
        G: { name: 'grip_handle', role: 'arm' },
        T: { name: 'acid_tank', role: 'belt' },
        H: { name: 'hazard_stripe', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        boot:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
