/**
 * Guns batch 5 — 20 sci-fi energy weapons & gun accessories.
 * Covers: ray gun, plasma rifle, laser pistol, ion blaster, photon cannon,
 *         pulse rifle, disruptor, neutron gun, gravity gun, portal gun,
 *         sonic blaster, warp pistol, bullet cartridge, ammo box,
 *         magazine clip, scope optic, holster, gun case, silencer, bandolier.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'weapons',
  exportNames: { templates: 'GUNS_BATCH5_TEMPLATES', schemes: 'GUNS_BATCH5_COLOR_SCHEMES' },
  templates: [

    // --- 1. RAY GUN RETRO --------------------------------------------------
    {
      id: 'ray_gun_retro_gn_16',
      description: 'Classic 1950s retro ray gun with dish emitter, swept fins, and chrome body.',
      grid: [
        '................',
        '......EEE.......',
        '.....EEGEE......',
        '....DDEEED......',
        '....DBBBBBD.....',
        'BBBBBBBBBBBBD...',
        'BBBBBGGGBBBBD...',
        'BBBBBGGGBBBBD...',
        'FBBBBBBBBBBBD...',
        'FFHHHHHBBBD.....',
        '.FHHHHH.........',
        '..HHHH..........',
        '...HH...........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chrome_body', role: 'body' },
        E: { name: 'dish_emitter', role: 'head' },
        D: { name: 'dark_hull', role: 'belt' },
        G: { name: 'energy_core', role: 'accessory' },
        H: { name: 'grip_handle', role: 'arm' },
        F: { name: 'fin_wings', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#2e484c', base: '#6daa2c', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // --- 2. PLASMA RIFLE ----------------------------------------------------
    {
      id: 'plasma_rifle_gn_16',
      description: 'Heavy plasma weapon with glowing core chamber and vented barrel.',
      grid: [
        '................',
        '................',
        '......VVVV......',
        '.BBEEEEEEEEBB...',
        'BBBBBBBBBBBBBBB.',
        'BBBBGGGGBBBBBB..',
        'DBBBBGGGGBBBBB..',
        'DBBBBBBBBBBBBBD.',
        'DDDDDBBBBBBBBBD.',
        '....DHHHHBBBD...',
        '.....HHHHHD.....',
        '......HHH.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'gun_body', role: 'body' },
        E: { name: 'barrel_vents', role: 'head' },
        G: { name: 'plasma_core', role: 'accessory' },
        D: { name: 'dark_chassis', role: 'belt' },
        H: { name: 'grip_stock', role: 'arm' },
        V: { name: 'vent_fins', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 3. LASER PISTOL ----------------------------------------------------
    {
      id: 'laser_pistol_gn_16',
      description: 'Sleek laser handgun with crystal emitter tip and power cell grip.',
      grid: [
        '................',
        '................',
        '....CCCCC.......',
        '...CCCCCCBB.....',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBGGGBBBBBB..',
        '..DBBBBBBBBBBBD.',
        '..DDDDDHHHHBD...',
        '......HHHHHD....',
        '.......HHPP.....',
        '........PP......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crystal_tip', role: 'head' },
        B: { name: 'gun_body', role: 'body' },
        G: { name: 'power_cell', role: 'accessory' },
        D: { name: 'dark_frame', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
        P: { name: 'grip_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#2e484c', base: '#6daa2c', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 4. ION BLASTER -----------------------------------------------------
    {
      id: 'ion_blaster_gn_16',
      description: 'Chunky ion blaster with vented barrel shroud and side power pack.',
      grid: [
        '................',
        '................',
        '....VVVVV.......',
        '..BBBBBBBBB.....',
        '.BBBBBBBBBBB....',
        'DBBEEBBBBBBBB...',
        'DBBEEBBGGGBBBD..',
        'DBBBBBBGGGBBD...',
        '.DDDDDBBBBBD....',
        '.....DHHHHD.....',
        '......HHHH......',
        '.......HH.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'blaster_body', role: 'body' },
        E: { name: 'barrel_vents', role: 'head' },
        G: { name: 'ion_pack', role: 'accessory' },
        D: { name: 'hull_frame', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
        V: { name: 'vent_shroud', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 5. PHOTON CANNON ---------------------------------------------------
    {
      id: 'photon_cannon_gn_16',
      description: 'Wide-bore photon energy cannon with massive barrel and shoulder brace.',
      grid: [
        '................',
        '.EEEEEE.........',
        'EEEEEEEEE.......',
        'DEEEEEEEED......',
        'DBBBBBBBBBD.....',
        'DBBBBBBBBBBBD...',
        'DBBBGGGGBBBBD...',
        'DBBBBBBBBBBBD...',
        'DDBBBBBBBBBDD...',
        '..DDDHHHHDD.....',
        '.....HHHHD......',
        '....SSHHHD......',
        '....SS..........',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'barrel_bore', role: 'head' },
        B: { name: 'cannon_body', role: 'body' },
        G: { name: 'photon_core', role: 'accessory' },
        D: { name: 'armored_hull', role: 'belt' },
        H: { name: 'grip_stock', role: 'arm' },
        S: { name: 'shoulder_brace', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 6. PULSE RIFLE -----------------------------------------------------
    {
      id: 'pulse_rifle_gn_16',
      description: 'Military-style pulse weapon with digital readout panel and long barrel.',
      grid: [
        '................',
        '................',
        '....BBB.........',
        '..BBBBBBBBB.....',
        '.BBBBBBBBBBBB...',
        'DBBRRBBBBBBBBBD.',
        'DBBBBBGGGBBBBBD.',
        'DBBBBBBBBBBBBBBD',
        '.DDDDDDBBBBBBDD.',
        '......DHHHHDD...',
        '.......HHHH.....',
        '........HH......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'rifle_body', role: 'body' },
        R: { name: 'readout_panel', role: 'head' },
        G: { name: 'pulse_emitter', role: 'accessory' },
        D: { name: 'dark_chassis', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#2e484c', base: '#6daa2c', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 7. DISRUPTOR -------------------------------------------------------
    {
      id: 'disruptor_gn_16',
      description: 'Alien disruptor weapon with organic curved body and pulsing energy veins.',
      grid: [
        '................',
        '................',
        '.....EEEE.......',
        '...EEEEEEE......',
        '..BBBBBBBBB.....',
        '.BBBVBBVBBBB....',
        'BBBBVBBVBBBBB...',
        'BBBBBBBBBBBBB...',
        '.DBBBBBBBBBD....',
        '..DDDHHHDD......',
        '....DHHHD.......',
        '.....HHH........',
        '......H.........',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'emitter_tip', role: 'head' },
        B: { name: 'organic_body', role: 'body' },
        V: { name: 'energy_veins', role: 'accessory' },
        D: { name: 'chitin_frame', role: 'belt' },
        H: { name: 'bone_grip', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 8. NEUTRON GUN -----------------------------------------------------
    {
      id: 'neutron_gun_gn_16',
      description: 'Neutron particle weapon with containment rings around barrel and power conduit.',
      grid: [
        '................',
        '................',
        '...RR..RR.......',
        '..RBBRRBBRR.....',
        '.RBBBBBBBBR.....',
        'BBBBBBBBBBBB....',
        'BBBBBGGGBBBBD...',
        'BBBBBGGGBBBBD...',
        'DBBBBBBBBBBBBD..',
        '.RBBRRBBRDHHD...',
        '..RRRRRRDHHHD...',
        '........HHH.....',
        '.........H......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'gun_body', role: 'body' },
        R: { name: 'containment_rings', role: 'head' },
        G: { name: 'neutron_core', role: 'accessory' },
        D: { name: 'hull_plating', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#2e484c', base: '#6daa2c', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 9. GRAVITY GUN -----------------------------------------------------
    {
      id: 'gravity_gun_gn_16',
      description: 'Gravity manipulation gun with floating core suspended between prongs.',
      grid: [
        '................',
        '....PP..PP......',
        '....PP..PP......',
        '....PPCCPP......',
        '....PPCCPP......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBBD...',
        '..BBBGGBBBBBD...',
        '..DBBBBBBBBD....',
        '...DDDHHHHD.....',
        '......HHHH......',
        '.......HH.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'prong_forks', role: 'head' },
        C: { name: 'floating_core', role: 'accessory' },
        B: { name: 'gun_body', role: 'body' },
        G: { name: 'grav_emitter', role: 'eye' },
        D: { name: 'dark_frame', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 10. PORTAL GUN -----------------------------------------------------
    {
      id: 'portal_gun_gn_16',
      description: 'Portal device with prominent glowing ring emitter and stabilizer fins.',
      grid: [
        '................',
        '....RRRRR.......',
        '...RR...RR......',
        '..RR.EEE.RR.....',
        '..R..EEE..R.....',
        '..RR.EEE.RR.....',
        '...RRBBBRRB.....',
        '...BBBBBBBBD....',
        '..BBBBBBBBBBD...',
        '..DBBBBBBBBD....',
        '..FDDDHHHDD.....',
        '..FF..HHHH......',
        '......HHH.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'ring_emitter', role: 'head' },
        E: { name: 'portal_glow', role: 'accessory' },
        B: { name: 'gun_body', role: 'body' },
        D: { name: 'dark_chassis', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
        F: { name: 'stabilizer_fins', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // --- 11. SONIC BLASTER --------------------------------------------------
    {
      id: 'sonic_blaster_gn_16',
      description: 'Sound-wave weapon with parabolic dish emitter and amplifier body.',
      grid: [
        '................',
        '...DDDDDD.......',
        '..DDDDDDD.......',
        '.DDDEEEDD.......',
        '.DDEEEEEDD......',
        '.DDDEEEDD.......',
        '..DDDDDDDBBB....',
        '...BBBBBBBBB....',
        '..BBBBBBBBBBD...',
        '..BBBGGBBBBBD...',
        '..DDBBBBBBD.....',
        '....DHHHHD......',
        '.....HHHH.......',
        '......HH........',
        '................',
        '................',
      ],
      chars: {
        D: { name: 'dish_shell', role: 'head' },
        E: { name: 'sonic_emitter', role: 'accessory' },
        B: { name: 'amplifier_body', role: 'body' },
        G: { name: 'power_cell', role: 'eye' },
        H: { name: 'grip_handle', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 12. WARP PISTOL ----------------------------------------------------
    {
      id: 'warp_pistol_gn_16',
      description: 'Warp-tech sidearm with phase crystal barrel and compact frame.',
      grid: [
        '................',
        '................',
        '....CCCCC.......',
        '...CCCCCCBB.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..DBBGGGBBBBBD..',
        '..DDDDDHHHBBD...',
        '......DHHHD.....',
        '.......HHHP.....',
        '........PP......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'phase_crystal', role: 'head' },
        B: { name: 'pistol_body', role: 'body' },
        G: { name: 'warp_core', role: 'accessory' },
        D: { name: 'dark_frame', role: 'belt' },
        H: { name: 'grip_handle', role: 'arm' },
        P: { name: 'grip_cap', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 13. BULLET AMMO ----------------------------------------------------
    {
      id: 'bullet_ammo_gn_16',
      description: 'Single large bullet cartridge with brass casing and copper tip.',
      grid: [
        '................',
        '.....TTTT.......',
        '....TTTTTT......',
        '....TTTTTT......',
        '...TTTTTTTT.....',
        '...TTTTTTTT.....',
        '...SSSSSSSS.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBRRBBBB....',
        '...BBBRRBBBB....',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'bullet_tip', role: 'head' },
        S: { name: 'neck_ring', role: 'accessory' },
        B: { name: 'brass_casing', role: 'body' },
        R: { name: 'primer_base', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 14. AMMO BOX -------------------------------------------------------
    {
      id: 'ammo_box_gn_16',
      description: 'Military ammo crate with reinforced corners, latch, and stencil marking.',
      grid: [
        '................',
        '................',
        '...CCCCCCCCCC...',
        '...CBBBBBBBC....',
        '...CBBBBBBBC....',
        '...CBBBLLBBC....',
        '...CBBBBBBBC....',
        '...CBBSSSBBC....',
        '...CBBSSSBBC....',
        '...CBBSSSBBC....',
        '...CBBBBBBBC....',
        '...CBBBBBBBC....',
        '...CCCCCCCCCC...',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'corner_frame', role: 'belt' },
        B: { name: 'box_body', role: 'body' },
        L: { name: 'latch_clasp', role: 'accessory' },
        S: { name: 'stencil_mark', role: 'head' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 15. MAGAZINE CLIP --------------------------------------------------
    {
      id: 'magazine_clip_gn_16',
      description: 'Detached gun magazine with visible rounds and feed lip detail.',
      grid: [
        '................',
        '......FFFF......',
        '.....BBBBBB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BRRRRB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....DDDDDD.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'feed_lips', role: 'head' },
        B: { name: 'mag_housing', role: 'body' },
        R: { name: 'visible_rounds', role: 'accessory' },
        D: { name: 'floor_plate', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 16. SCOPE OPTIC ----------------------------------------------------
    {
      id: 'scope_optic_gn_16',
      description: 'Detached rifle scope with lens glass, adjustment turrets, and mounting rail.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..LLBB..........',
        '.LLLBBBBBBB.....',
        '.LLBBBBBBBBBB...',
        '.LLBBBTTBBBBBBL.',
        '.LLBBBBBBBBBB...',
        '.LLLBBBBBBB.....',
        '..LLBB..........',
        '...MMMMMM.......',
        '...MMMMMM.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lens_glass', role: 'head' },
        B: { name: 'scope_tube', role: 'body' },
        T: { name: 'turret_knobs', role: 'accessory' },
        M: { name: 'mount_rail', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 17. HOLSTER LEATHER ------------------------------------------------
    {
      id: 'holster_leather_gn_16',
      description: 'Leather gun holster with belt loop, snap closure, and stitching detail.',
      grid: [
        '................',
        '...LLLLLL.......',
        '...LLLLLLLL.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBBB...',
        '..BBSSBBBBBB....',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '....BBBBBB......',
        '....TTTTTT......',
        '................',
      ],
      chars: {
        L: { name: 'belt_loop', role: 'head' },
        B: { name: 'leather_body', role: 'body' },
        S: { name: 'snap_closure', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 18. GUN CASE -------------------------------------------------------
    {
      id: 'gun_case_gn_16',
      description: 'Padded gun carrying case with handle, latches, and foam interior visible.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '..CCCCCCCCCCCC..',
        '..CBBBBBBBBBC...',
        '..CBLLBBLLBBC...',
        '..CBBBBBBBBBC...',
        '..CBBFFBBBBBC...',
        '..CBBFFFBBBBC...',
        '..CBBBBBBBBBC...',
        '..CBBBBBBBBBC...',
        '..CCCCCCCCCCCC..',
        '..TTTTTTTTTTTT..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'carry_handle', role: 'head' },
        C: { name: 'case_frame', role: 'belt' },
        B: { name: 'case_body', role: 'body' },
        L: { name: 'latch_clasps', role: 'accessory' },
        F: { name: 'foam_cutout', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 19. SILENCER -------------------------------------------------------
    {
      id: 'silencer_gn_16',
      description: 'Detached suppressor cylinder with vented baffles and threading.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '....TTBBBBTT....',
        '...TBBBBBBBBT...',
        '..TBBVBBVBBBBT..',
        '..BBBVBBVBBBBBB.',
        '..BBBVBBVBBBBBB.',
        '..TBBVBBVBBBBT..',
        '...TBBBBBBBBT...',
        '....TTBBBBTT....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cylinder_body', role: 'body' },
        V: { name: 'baffle_vents', role: 'head' },
        T: { name: 'thread_caps', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // --- 20. BANDOLIER ------------------------------------------------------
    {
      id: 'bandolier_gn_16',
      description: 'Ammo bandolier belt with shell loops and metal buckle.',
      grid: [
        '................',
        '................',
        '..RRRRRRRRRR....',
        '..BRBRBRBRBB....',
        '..RRRRRRRRRR....',
        '..RRRRRRRRRR....',
        '..BRBRBRBRBB....',
        '..RRRRRRRRRR....',
        '..RRRRRRRRRR....',
        '..BRBRBRBRBB....',
        '..RRRRRRRRRR....',
        '..MMBRRRRRRRR...',
        '..RRRRRRRRRR....',
        '...TTTTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'shell_rounds', role: 'head' },
        B: { name: 'belt_leather', role: 'body' },
        M: { name: 'metal_buckle', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
