/**
 * Medieval Scholar's Collection — 32x32 Batch 4: Music (10) + Astronomy (10)
 *
 * 20 templates, all 32x32, DB16 palette only, ASCII grid format.
 * Neo-SNES style (Chrono Trigger + Sea of Stars quality).
 * Colored selout, 4-8 roles per template, different material ramp per role.
 *
 * Design rules:
 * - Clean silhouette, no isolated pixels
 * - 2-3 tones per material (shadow/base/highlight)
 * - Shadow clusters: 2-4px groups, never single dots
 * - Light from top-left, shadows bottom-right
 * - Centered in 32x32 canvas, 1px transparent border on at least 2 sides
 * - Fill 35-65% of canvas
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_32_BATCH4_TEMPLATES', schemes: 'LIBERAL_ARTS_32_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    // MUSIC — Medieval Instruments & Performance (10)
    // ═══════════════════════════════════════════════════════════════

    // ─── 1. HAND DRUM ──────────────────────────────────────────
    {
      id: 'hand_drum_32',
      description: 'Round hand drum (frame drum) seen at 3/4 angle with decorative painted skin, grip strap, and brass rivets.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '..........FFFFFFFFFFF...........',
        '........FFFFFFFFFFFFFFFF........',
        '.......FFFFFFFFFFFFFFFFFFL......',
        '......FFPPPPPPPPPPPPPPPPFFL.....',
        '.....FFPPPPPPPPPPPPPPPPPFFL.....',
        '.....FPPPPPPPEEEPPPPPPPPFFL.....',
        '....FFPPPPPEEPPEEPPPPPPPFFLL....',
        '....FPPPPPEPPPPPEEPPPPPPPFLL....',
        '....FPPPPEPPPPPPPEEPPPPPFFL.....',
        '....FPPPPEPPPRRPPPEEPPPPFFL.....',
        '....FPPPEPPPPRRRPPPEEPPPFFL.....',
        '....FPPPEPPPPRRRPPPEPPPPFFL.....',
        '....FPPPPEPPPRRPPPEEPPPPFFL.....',
        '....FPPPPEPPPPPPPEEPPPPPFFL.....',
        '....FPPPPPEPPPPPEEPPPPPFFLL.....',
        '....FFPPPPPEEPPEEPPPPPPPFLL.....',
        '.....FPPPPPPPEEEPPPPPPPPFFL.....',
        '.....FFPPPPPPPPPPPPPPPPPFFL.....',
        '......FFPPPPPPPPPPPPPPPPFFL.....',
        '.......FFFFFFFFFFFFFFFFFFL......',
        '........FFFFFFFFFFFFFFFF.LL.....',
        '..........FFFFFFFGGGGLL.LL......',
        '...........LLLLLLGGGG.LL........',
        '..................GGGG..........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'drum_frame', role: 'body' },
        P: { name: 'drum_skin', role: 'head' },
        E: { name: 'decorative_paint', role: 'eye' },
        R: { name: 'rivets', role: 'accessory' },
        G: { name: 'grip_strap', role: 'arm' },
        L: { name: 'frame_shadow', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 2. PSALTERY ───────────────────────────────────────────
    {
      id: 'psaltery_32',
      description: 'Trapezoidal plucked psaltery instrument with gold strings, steel pegs, and decorative sound holes.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.......WWWWWWW..................',
        '......WWPPPPWWW.................',
        '.....WWPSSSSPDDWWW..............',
        '....WWPPSSSSSPPDDWWW............',
        '...WWPPPSSSSSPPPDDDWWW..........',
        '...WPPPPSSSSSPPPPDDDDWW.........',
        '..WWPPPPPSSSSPPPPPDDDDDWW.......',
        '..WPPPPPPSSSPPPPPPDDDDDDWW......',
        '..WPPPHPPSSPPPPHPPPDDDDDDWW.....',
        '..WPPPHHPSSPPPPHHPPPDDDDDDDW....',
        '..WPPPHPPSPPPPPHPPPPDDDDDDDDW...',
        '..WPPPPPPSPPPPPPPPPPDDDDDDDDDW..',
        '..WPPPPPSSPPPPPPPPPPDDDDDDDDWW..',
        '..WPPPPPSPPPPPPPPPPPDDDDDDDWW...',
        '..WPPPPSSPPPPPPPPPPPDDDDDDWW....',
        '..WPPPPSPPPPPPPPPPPPDDDDDDWW....',
        '..WPPPSSPPPPPPPPPPPPDDDDDDWW....',
        '..WPPPSPPPPPPPPPPPPPDDDDDWW.....',
        '..WPPPSPPPPPPPPPPPPPDDDDWW......',
        '..WPPSSPPPPPPPPPPPPPDDDDWW......',
        '..WWWWWWWWWWWWWWWWWWWWWWWW......',
        '..GGGGGGGGGGGGGGGGGGGGGGGG......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        W: { name: 'body_wood', role: 'body' },
        P: { name: 'face_wood', role: 'head' },
        S: { name: 'strings', role: 'arm' },
        D: { name: 'shadow_side', role: 'belt' },
        H: { name: 'sound_holes', role: 'eye' },
        G: { name: 'tuning_pegs', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 3. REBEC ──────────────────────────────────────────────
    {
      id: 'rebec_32',
      description: 'Pear-shaped bowed rebec with separate bow, gold strings, and dark sound holes.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '....GG..........................',
        '...GGGG.........................',
        '....GGNN........................',
        '.....NNNN.......................',
        '.....NNSNN......................',
        '......NNSNN.....................',
        '......NNSSNN....................',
        '.......NNSSNN...................',
        '......BBBBBBB...................',
        '.....BBBSSSBBB...BB.............',
        '....BBBHSSHBBBB..BBB............',
        '....BBHHHSHHBBBB..BBB...........',
        '....BBBHSSHBBBB....BBB..........',
        '.....BBBSSSBBB......BBB.........',
        '......BBBBBBB........BBB........',
        '.......BBBBB..........BBB.......',
        '........BBB............BBB......',
        '.........................BB.....',
        '..........................BB....',
        '...........................BB...',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'pegbox', role: 'accessory' },
        N: { name: 'neck', role: 'arm' },
        B: { name: 'body_wood', role: 'body' },
        S: { name: 'strings', role: 'head' },
        H: { name: 'sound_holes', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 4. CRUMHORN ───────────────────────────────────────────
    {
      id: 'crumhorn_32',
      description: 'J-shaped medieval wind instrument with gold bell end, red cap, and finger holes along the body.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........CCCC..................',
        '.........CCCCCC.................',
        '.........CCCCCC.................',
        '..........BBBB..................',
        '..........BBBB..................',
        '..........BHBB..................',
        '..........BBBB..................',
        '..........BHBB..................',
        '..........BBBB..................',
        '..........BHBB..................',
        '..........BBBB..................',
        '..........BHBB..................',
        '..........BBBB..................',
        '..........BHBB..................',
        '..........BBBB..................',
        '..........BBBB..................',
        '..........BDDB..................',
        '..........BDDB..................',
        '..........BBBB..................',
        '...........BBBB.................',
        '............BBBB................',
        '.............BBBBB..............',
        '..............BBBBB.............',
        '..............GGBBBB............',
        '..............GGGBBB............',
        '..............GGGGG.............',
        '...............GGGG.............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        C: { name: 'wind_cap', role: 'eye' },
        B: { name: 'tube_body', role: 'body' },
        H: { name: 'finger_holes', role: 'arm' },
        D: { name: 'tube_shadow', role: 'belt' },
        G: { name: 'bell_end', role: 'head' },
      },
      colors: {
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. MUSIC STAND ────────────────────────────────────────
    {
      id: 'music_stand_32',
      description: 'Ornate music stand holding an open sheet of music with visible notes, on a steel tripod base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '......WWWWWWWWWWWWWWWW..........',
        '......WPPPPPPPPPPPPPPW..........',
        '......WPPNNPPPPPPPPPPW..........',
        '......WPPPPPPNNPPPPPPW..........',
        '......WPPPPPPPPPPPPPPW..........',
        '......WPPNNPPPPPPNNPPW..........',
        '......WPPPPPPNNPPPPPPW..........',
        '......WPPPPPPPPPPPPPPW..........',
        '......WPPPPPPPPNNPPPPW..........',
        '......WPPNNPPPPPPPPPPW..........',
        '......WPPPPPPPPPPPPPPW..........',
        '......WWWWWWWWWWWWWWWW..........',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '..............SS................',
        '.............SSSS...............',
        '............SSSSSS..............',
        '...........SS.SS.SS.............',
        '..........SS..SS..SS............',
        '.........SS...SS...SS...........',
        '........FF....FF....FF..........',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        W: { name: 'stand_top', role: 'body' },
        P: { name: 'sheet_music', role: 'head' },
        N: { name: 'music_notes', role: 'eye' },
        S: { name: 'stand_post', role: 'arm' },
        F: { name: 'tripod_feet', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. CHOIR BOOK ─────────────────────────────────────────
    {
      id: 'choir_book_32',
      description: 'Large open choir antiphoner on a wooden stand, showing musical notation with red initials.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...CCCCCCCCCCCCCCCCCCCCCCC......',
        '...CPPPPPPPPPPCPPPPPPPPPPPC.....',
        '...CPPNNPPPPPPCCPPPPPPNNPPC.....',
        '...CPPPPPPNNPPCPPPNNPPPPPPCC....',
        '...CPPPPPPPPPPCCPPPPPPPPPPCC....',
        '...CPPRRPPPPPPCCPPPPPPRRPPCC....',
        '...CPPPPPPNNPPCCPPNNPPPPPPCC....',
        '...CPPPPPPPPPPCCPPPPPPPPPPCC....',
        '...CPPNNPPPPPPCCPPPPPPNNPPCC....',
        '...CPPPPPPPPPPCCPPPPPPPPPPCC....',
        '...CPPPPPPNNPPCCPPNNPPPPPPCC....',
        '...CPPPPPPPPPPCCPPPPPPPPPPCC....',
        '...CCCCCCCCCCCCCCCCCCCCCCCCC....',
        '............CCSSCC..............',
        '............SSSSSS..............',
        '...........SS..SS..SS...........',
        '..........SS....SS..SS..........',
        '.........SS......SS..SS.........',
        '........FF........FF..FF........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        C: { name: 'book_cover', role: 'body' },
        P: { name: 'pages', role: 'head' },
        N: { name: 'note_lines', role: 'arm' },
        R: { name: 'red_initials', role: 'eye' },
        S: { name: 'stand_post', role: 'belt' },
        F: { name: 'stand_feet', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. TUNING FORK ────────────────────────────────────────
    {
      id: 'tuning_fork_32',
      description: 'Two-pronged steel tuning fork with gold-tipped handle, U-shape prongs at top.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PP....PP.............',
        '...........PPP..PPP.............',
        '............PPPPPP..............',
        '............PPPPPP..............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............HHHH...............',
        '.............GGGG...............',
        '.............GGGG...............',
        '..............GG................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        P: { name: 'prongs', role: 'body' },
        H: { name: 'handle', role: 'head' },
        G: { name: 'handle_tip', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. CYMBAL PAIR ────────────────────────────────────────
    {
      id: 'cymbal_pair_32',
      description: 'Pair of small brass hand cymbals with leather straps, overlapping at an angle with metallic shine.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..........MMMMMMMM..............',
        '.........MMMMMMMMMMM............',
        '........MMMMMMMMMMMMMM..........',
        '.......MMMMMMCCMMMMMMMM.........',
        '......MMMMMMMCCMMMMMMMMM........',
        '.....MMMMSMMMMMMMMMSMMMMM.......',
        '.....MMMMSMMMMMMMMMSMMMMMM......',
        '.....MMMMMMMMMMMMMMMMMMMMMM.....',
        '.....MMMMMMMLLLLMMMMMMMMMMM.....',
        '......MMMMLLMMMMLLMMMMMMMMM.....',
        '.......MLLMMMMMMMMLLMMMMMM......',
        '......LLMMMMMMMMMMMMLLMMM.......',
        '.....LLMMMMMMMDDMMMMMLLM........',
        '....LLMMMMMMMMDDMMMMMMMLL.......',
        '...LLMMMMSMMMMMMMMMSMMMMLL......',
        '...LMMMMMSMMMMMMMMMSMMMMML......',
        '...LMMMMMMMMMMMMMMMMMMMML.......',
        '....LMMMMMMMMMMMMMMMMMML........',
        '.....LMMMMMMMMMMMMMMML..........',
        '......LLMMMMMMMMMMMLL...........',
        '........LLLMMMMMLL..............',
        '..........LLLLLLL...............',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        M: { name: 'cymbal_metal', role: 'body' },
        S: { name: 'shine_spot', role: 'head' },
        C: { name: 'strap_top', role: 'arm' },
        D: { name: 'strap_bottom', role: 'arm' },
        L: { name: 'shadow_edge', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. FIDDLE ─────────────────────────────────────────────
    {
      id: 'fiddle_32',
      description: 'Medieval fiddle (vielle) with figure-8 body, gold strings, f-holes, and a separate bow resting beside it.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.....GGG........................',
        '....GPPGG.......................',
        '....GPPGG.......................',
        '.....NNNN.......................',
        '.....NSNN.......................',
        '.....NSNN.......................',
        '.....NSNN.......................',
        '....BBBBB....BB.................',
        '...BBSSSBB...BBB................',
        '..BBHSSHBB....BBB...............',
        '..BBBSBBB......BBB..............',
        '...BBBBB........BBB.............',
        '..BBBSBBB........BBB............',
        '..BBHSSHBB........BBB...........',
        '..BBHSSHBB.........BBB..........',
        '..BBBSBBB...........BBB.........',
        '...BBSBBB............BBB........',
        '...BBBBB..............BBB.......',
        '....BBB................BB.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'pegbox', role: 'accessory' },
        P: { name: 'pegs', role: 'belt' },
        N: { name: 'neck', role: 'arm' },
        B: { name: 'body_wood', role: 'body' },
        S: { name: 'strings', role: 'head' },
        H: { name: 'f_holes', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 10. BAGPIPE ───────────────────────────────────────────
    {
      id: 'bagpipe_32',
      description: 'Medieval bagpipe with inflated leather bag, chanter pipe, drone pipes, and red tassels.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........DD..DD................',
        '..........DD..DD................',
        '..........DD..DD................',
        '..........DD..DD................',
        '..........DD..DD................',
        '..........DD..DD................',
        '.........DDDDDDD................',
        '........BBBBBBBBB...............',
        '.......BBBBBBBBBBB..............',
        '......BBBBBBBBBBBBB.............',
        '.....BBBBBBBBBBBBBBB............',
        '.....BBBBBBBBBBBBBBBB...........',
        '....BBBBBBBBBBBBBBBBB...........',
        '....BBBBBBBBBBBBBBBBBB..........',
        '....BBBBBBBBBBBBBBBBBCC.........',
        '....BBBBBBBBBBBBBBBBCCCC........',
        '.....BBBBBBBBBBBBBBCCCC.........',
        '.....BBBBBBBBBBBBBCCCC..........',
        '......BBBBBBBBBBB.CCC...........',
        '.......BBBBBBBBB..CC............',
        '........BBBBBBB..CC.............',
        '.........BBBBB..CC..............',
        '..........BBB..CC...............',
        '...........MM.CC................',
        '...........MMCC.................',
        '...........TTCC.................',
        '...........TT...................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        D: { name: 'drone_pipes', role: 'arm' },
        B: { name: 'bag_leather', role: 'body' },
        C: { name: 'chanter', role: 'head' },
        M: { name: 'mouthpipe', role: 'belt' },
        T: { name: 'tassels', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // ASTRONOMY — Celestial Instruments & Charts (10)
    // ═══════════════════════════════════════════════════════════════

    // ─── 11. ASTROLABE ─────────────────────────────────────────
    {
      id: 'astrolabe_32',
      description: 'Detailed brass astrolabe with outer ring, inner rete plate, cross pattern, and ornate throne at top.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '...........TTTTTT...............',
        '..........TTGGGGTT..............',
        '..........TTGGGGTT..............',
        '...........OOOOOO...............',
        '.........OOOOOOOOOO.............',
        '........OOOOOOOOOOOO............',
        '.......OOORRRRRRRROOOO..........',
        '......OOORRIIIIIIRRROOO.........',
        '.....OOORRIIIIIIIIRROOO.........',
        '.....OORRIIIIPIIIIRROOO.........',
        '....OOORIIIIPPIIIIRRROO.........',
        '....OORRIPPPPPPPPIIRROO.........',
        '....OORRIPPPPPPPPIIRROO.........',
        '....OORRIIIPPPPIIIIRROOO........',
        '....OORRIIIIPIIIIRRROO..........',
        '....OOORRIIIIIIIIRROOO..........',
        '.....OOORRIIIIIIRRROOO..........',
        '.....OOORRRRRRRRRROOO...........',
        '......OOORRRRRRRROOOO...........',
        '.......OOOOOOOOOOOOO............',
        '........OOOOOOOOOOOO............',
        '.........OOOOOOOOOO.............',
        '...........OOOOOO...............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        T: { name: 'throne', role: 'eye' },
        G: { name: 'throne_detail', role: 'accessory' },
        O: { name: 'outer_ring', role: 'body' },
        R: { name: 'rete_plate', role: 'head' },
        I: { name: 'inner_plate', role: 'arm' },
        P: { name: 'center_cross', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 12. ARMILLARY SPHERE ──────────────────────────────────
    {
      id: 'armillary_sphere_32',
      description: 'Nested ring armillary sphere on wooden stand, with tilted gold and steel rings around a blue center globe.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........RRRRRRRR.............',
        '..........RR......RR............',
        '.........RR........RR...........',
        '........RR..SSSSSS..RR..........',
        '.......RR..SS....SS..RR.........',
        '......RR..SS..CC..SS..RR........',
        '......RR.SS..CCCC..SS.RR........',
        '.....RR..SS.CCCCCC.SS..RR.......',
        '.....RR.SS..CCCCCC..SS.RR.......',
        '.....RR.SS..CCCCCC..SS.RR.......',
        '.....RR.SS..CCCCCC..SS.RR.......',
        '.....RR..SS.CCCCCC.SS..RR.......',
        '......RR.SS..CCCC..SS.RR........',
        '......RR..SS..CC..SS..RR........',
        '.......RR..SS....SS..RR.........',
        '........RR..SSSSSS..RR..........',
        '.........RR........RR...........',
        '..........RR......RR............',
        '...........RRRRRRRR.............',
        '.............WWWW...............',
        '.............WWWW...............',
        '............WWWWWW..............',
        '...........WW.WW.WW.............',
        '..........WW..WW..WW............',
        '.........BB...BB...BB...........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        R: { name: 'outer_rings', role: 'body' },
        S: { name: 'inner_rings', role: 'head' },
        C: { name: 'center_globe', role: 'eye' },
        W: { name: 'stand_post', role: 'arm' },
        B: { name: 'stand_base', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 13. CELESTIAL GLOBE ───────────────────────────────────
    {
      id: 'celestial_globe_32',
      description: 'Dark blue globe showing gold star constellations on a wooden stand with brass meridian ring.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '...........MMMMMMMM.............',
        '..........MM......MM............',
        '.........MMGGGGGGGGMM...........',
        '........MGGGSGGGGSGGGM..........',
        '.......MGGGGGGGGGGGGGMM.........',
        '......MGGGGSGSGSGGGGGGGM........',
        '......MGGGGGSGSGGGGGSGGM........',
        '.....MGGGGGGGSGGGGGGGGGM........',
        '.....MGGSGGGGGGGSGGGGGGGM.......',
        '.....MGGGGGGGSGGGGGSGGGGM.......',
        '.....MGGGGGGGGGGGGGGGGGM........',
        '.....MGGGSGSGGGGGSGGGGM.........',
        '......MGGGSGGGSGGGGGGGM.........',
        '......MGGGGGGGGGGGGSGM..........',
        '.......MGGGSGGGGGGGMM...........',
        '........MGGGGGSGGGGM............',
        '.........MMGGGGGGMM.............',
        '..........MM......MM............',
        '...........MMMMMMMM.............',
        '.............PPPP...............',
        '.............PPPP...............',
        '............PPPPPP..............',
        '...........PP.PP.PP.............',
        '..........PP..PP..PP............',
        '.........WW...WW...WW...........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        M: { name: 'meridian_ring', role: 'head' },
        G: { name: 'globe_surface', role: 'eye' },
        S: { name: 'star_dots', role: 'accessory' },
        P: { name: 'stand_post', role: 'arm' },
        W: { name: 'stand_base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. TELESCOPE ─────────────────────────────────────────
    {
      id: 'telescope_32',
      description: 'Early telescope (long brass tube) on a wooden tripod, with gold lens rim and decorative band.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.GG.............................',
        '.GGTT...........................',
        '..TTTT..........................',
        '...TTTT.........................',
        '....TTTT........................',
        '.....TTTT.......................',
        '......TTTT......................',
        '.......TTTT.....................',
        '........TTTTD...................',
        '.........TTTDD..................',
        '..........TTTDD.................',
        '...........TTTDD................',
        '............TTTDD...............',
        '.............TTTDD..............',
        '..............TTTGG.............',
        '...............TTGG.............',
        '................TT..............',
        '................LL..............',
        '...............LL.LL............',
        '..............LL...LL...........',
        '.............LL.....LL..........',
        '............LL.......LL.........',
        '...........LL.........LL........',
        '..........FF...........FF.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'lens_rim', role: 'head' },
        T: { name: 'tube_body', role: 'body' },
        D: { name: 'decorative_band', role: 'accessory' },
        L: { name: 'tripod_legs', role: 'arm' },
        F: { name: 'tripod_feet', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 15. STAR CHART ────────────────────────────────────────
    {
      id: 'star_chart_32',
      description: 'Circular parchment star chart with constellation lines in blue, gold star markers, and a wooden border frame.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.........FFFFFFFFFFF............',
        '........FFFFFFFFFFFFL...........',
        '.......FFPPPPPPPPPPFFL..........',
        '......FFPPPPPPPPPPPPFFL.........',
        '.....FFPPSPPPPPPSPPPFFL.........',
        '....FFPPPLLLPPPPPPPPFFL.........',
        '....FPPPPPPLLPPPPPPPFFLL........',
        '...FFPPPPPPPLLLPPSPPPFFL........',
        '...FPPPSPPPPPPLPPPPPPFFLL.......',
        '...FPPPPPPSPPPLLPPPPPFFLL.......',
        '...FPPPLPPPPPPPLLPPPPFFLL.......',
        '...FPPPPLPPPPPPPLLPPPFFLL.......',
        '...FPPPPPLPPSPPPPLLPPFFLL.......',
        '...FPPPPPPLLPPPPPPLPPFFLL.......',
        '...FPPPPPPPLLLPPPPPPFFLL........',
        '...FFPPPPPPPPPLLPPPPPFFL........',
        '....FPPPPSPPPPPLLPPPPFFL........',
        '....FFPPPPPPPPPPPPPPPFFL........',
        '.....FFPPPPPPPPPPPPPFFL.........',
        '......FFPPPPPPPPPPPPFFL.........',
        '.......FFPPPPPPPPPPFFL..........',
        '........FFFFFFFFFFFFL...........',
        '.........FFFFFFFLLLL............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'border_frame', role: 'body' },
        P: { name: 'parchment', role: 'head' },
        S: { name: 'star_markers', role: 'accessory' },
        L: { name: 'constellation_lines', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 16. SUNDIAL ───────────────────────────────────────────
    {
      id: 'sundial_32',
      description: 'Stone sundial with brass gnomon casting a shadow, hour marks around the elliptical dial face, on a stone pedestal.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..............GG................',
        '.............GGGG...............',
        '............GG.GGG..............',
        '...........GG...GGG.............',
        '..........GG.....GGG............',
        '..........HHHHHHHHHHH...........',
        '.......HHHHDDDDDDDDHHHHH........',
        '......HDDDDDDDDDDDDDDDDH........',
        '.....HDDDMMDDDDDDMMDDDDDH.......',
        '....HDDMDDDDDDSDDDDMDDDDDH......',
        '....HDDDDDMDDDDDDMDDDDDDSH......',
        '.....HDDDDDDDMMMDDDDDDDDSH......',
        '......HDDDDDDDDDDDDDDDDSH.......',
        '.......HHHHDDDDDDDDDSSSH........',
        '..........SHHHHHHHHSSS..........',
        '...........PPPPPPPP.............',
        '...........PPPPPPPP.............',
        '...........PPPPPPPP.............',
        '..........PPPPPPPPPP............',
        '.........PPPPPPPPPPPP...........',
        '........PPPPPPPPPPPPPP..........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'gnomon', role: 'head' },
        D: { name: 'dial_face', role: 'body' },
        M: { name: 'hour_marks', role: 'arm' },
        H: { name: 'dial_rim', role: 'eye' },
        S: { name: 'shadow_area', role: 'belt' },
        P: { name: 'pedestal', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 17. ORRERY ────────────────────────────────────────────
    {
      id: 'orrery_32',
      description: 'Mechanical solar system model with central gold sun, orbiting planets on steel arms, on a wooden base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '...........PP...................',
        '..........PPAA..................',
        '...........AAAA.................',
        '............AAAA................',
        '.............AASSSSS............',
        '..............AASSGGG...........',
        '...............ASSGGG...........',
        '...PP.........ASSGGG............',
        '..PPAA.......AASSGG.............',
        '...AAAA....AASSSS...............',
        '....AAAAAASSSS..................',
        '......AAASSS....................',
        '.........SSS....................',
        '.........SSS......PP............',
        '........AASSSS..PPAA............',
        '.......AAAA..AAAAA..............',
        '......AAAA.....AAAA.............',
        '....PPAA.........AAAA...........',
        '...PP.............AAAA..........',
        '....................AAPP........',
        '.....................PP.........',
        '.............WWWW...............',
        '.............WWWW...............',
        '............WWWWWW..............',
        '..........BBBBBBBBBB............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        S: { name: 'central_sun', role: 'eye' },
        G: { name: 'sun_glow', role: 'accessory' },
        P: { name: 'planets', role: 'head' },
        A: { name: 'orbit_arms', role: 'arm' },
        W: { name: 'stand_post', role: 'body' },
        B: { name: 'base_plate', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. MOON PHASE ────────────────────────────────────────
    {
      id: 'moon_phase_32',
      description: 'Moon phase diagram showing 5 phases from new to full on a parchment background with gold border marks.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..BBBBB..BBBBB..BBBBB..BBBBB....',
        '.BDDDDB.BDDLLB.BLLLLB.BLLLPB....',
        '.BDDDDB.BDDLLLB.BLLLPB.BPPPB....',
        'BDDDDDB.BDDLLLB.BLLLPB.BPPPPB...',
        'BDDDDDB.BDDLLLB.BLLLPB.BPPPPB...',
        'BDDDDDB.BDDLLLB.BLLLPB.BPPPPB...',
        '.BDDDDB.BDDLLLB.BLLLPB.BPPPB....',
        '.BDDDDBB.BDDLLB.BLLLLB.BLLLPB...',
        '..BBBBB..BBBBB..BBBBB..BBBBB....',
        '................................',
        '...GG......GG......GG......GG...',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'moon_border', role: 'arm' },
        D: { name: 'dark_side', role: 'body' },
        L: { name: 'terminator', role: 'belt' },
        P: { name: 'lit_side', role: 'head' },
        G: { name: 'phase_labels', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 19. COMPASS ROSE ──────────────────────────────────────
    {
      id: 'compass_rose_32',
      description: 'Ornate 8-pointed compass rose with gold cardinal points, steel secondary points, red center dot, and dark outer ring.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..............GG................',
        '.............GGGG...............',
        '............GGGGGG..............',
        '...........GGGGGGG..............',
        '..........RRGGGGGGR.............',
        '.........RR..GGGG..RR...........',
        '........RR...GGGG...RR..........',
        '.......RR.....GG.....RR.........',
        '......RR..............RR........',
        '.....RRSS............SSRR.......',
        '....RRSSS....CCCC....SSSRR......',
        '...GGGGGGGGGCCCCCCGGGGGGGG......',
        '...GGGGGGGGGCCCCCCGGGGGGGG......',
        '....RRSSS....CCCC....SSSRR......',
        '.....RRSS............SSRR.......',
        '......RR..............RR........',
        '.......RR.....GG.....RR.........',
        '........RR...GGGG...RR..........',
        '.........RR..GGGG..RR...........',
        '..........RRGGGGGGR.............',
        '...........GGGGGGG..............',
        '............GGGGGG..............',
        '.............GGGG...............',
        '..............GG................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'cardinal_points', role: 'body' },
        S: { name: 'secondary_points', role: 'head' },
        R: { name: 'ring_outline', role: 'arm' },
        C: { name: 'center_jewel', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 20. SEXTANT ───────────────────────────────────────────
    {
      id: 'sextant_32',
      description: 'Navigation sextant with arc-shaped steel frame, gold graduated arc, blue glass mirrors, and wooden handle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.....MM.........................',
        '....MMMM........................',
        '....MMFF........................',
        '.....FFF........................',
        '......FFF.......................',
        '.......FFF......................',
        '........FFF.....................',
        '.........FFF....................',
        '..........FFF...................',
        '...........FFF..................',
        '............FFF.................',
        '.............FFFAA..............',
        '..............FFAAAA............',
        '...............AAAAAA...........',
        '..............AAAAAAAA..........',
        '.............AAGGGGGGAA.........',
        '............AAGGGGGGGGA.........',
        '...........AAGGGGGGGGGA.........',
        '..........AAGGGGGGGGGGA.........',
        '.........AAHHHHHHHHHHHHAA.......',
        '........HHHHHHHHHHHHHHHH........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        M: { name: 'mirror_glass', role: 'eye' },
        F: { name: 'frame_arm', role: 'body' },
        A: { name: 'arc_frame', role: 'arm' },
        G: { name: 'graduated_scale', role: 'head' },
        H: { name: 'handle', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
