/**
 * Medieval Scholar's Collection — Batch 2: Logic (7) + Rhetoric (13) = 20 templates.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_BATCH2_TEMPLATES', schemes: 'LIBERAL_ARTS_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════
    // LOGIC continued (7 of 13)
    // ═══════════════════════════════════════════════════

    // ─── 1. MAGNIFYING LENS ───────────────────────────
    {
      id: 'magnifying_lens_16',
      description: 'Brass-rimmed magnifying glass for examining truth and detail.',
      grid: [
        '................',
        '....RRRRRR......',
        '...RRGGGGGRR....',
        '..RRGG.GGGRR....',
        '..RGGGGGGGGRR...',
        '..RGGGGGGGGRR...',
        '..RRGG.GGGRR....',
        '...RRGGGGRR.....',
        '....RRRRRR......',
        '.....RRHH.......',
        '......RRHH......',
        '.......RRHH.....',
        '........HH......',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rim_frame', role: 'body' },
        G: { name: 'glass_lens', role: 'head' },
        H: { name: 'handle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. PHILOSOPHER'S HAT ─────────────────────────
    {
      id: 'philosophers_hat_16',
      description: 'Pointed scholar hat with star-studded band and crescent.',
      grid: [
        '........PP......',
        '.......PPP......',
        '......PPPP......',
        '.....PPPPP......',
        '....PPPPPP......',
        '...PPPPPPPP.....',
        '..PPPPPBBPPP....',
        '..PPPPBBBBPP....',
        '.PPPBBSBBPPP....',
        '.PPPPPPPPPPPP...',
        'DDDDDDDDDDDDDD..',
        'DDDDDDDDDDDDDD..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'hat_fabric', role: 'body' },
        B: { name: 'band', role: 'accessory' },
        S: { name: 'star_emblem', role: 'eye' },
        D: { name: 'brim', role: 'head' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. DEBATE TABLET ─────────────────────────────
    {
      id: 'debate_tablet_16',
      description: 'Divided tablet with pro and contra columns for dialectic.',
      grid: [
        '................',
        '.FFFFFFFFFFFF...',
        '.FPPPDPPPPPPF...',
        '.FPPPDPPPPPPF...',
        '.FGGPDPPRRPPF...',
        '.FPPPDPPPPPPF...',
        '.FPPPDPPRRPPF...',
        '.FGGPDPPPPPPF...',
        '.FPPPDPPRRPPF...',
        '.FPPPDPPPPPPF...',
        '.FGGPDPPRRPPF...',
        '.FPPPDPPPPPPF...',
        '.FFFFFFFFFFFF...',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        P: { name: 'parchment', role: 'head' },
        D: { name: 'divider', role: 'arm' },
        G: { name: 'check_pro', role: 'eye' },
        R: { name: 'cross_con', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 4. PUZZLE BOX ────────────────────────────────
    {
      id: 'puzzle_box_16',
      description: 'Ornate puzzle box with sliding panels and glowing seam.',
      grid: [
        '................',
        '................',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '..BBRRBBRRBBBB..',
        '..BBRRBBRRBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBRRBBRRBBB...',
        '..BBRRBBRRBBB...',
        '..BBBBGGBBBBBB..',
        '..BBBBGGBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..CCCCCCCCCCCC..',
        '................',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'lid_top', role: 'head' },
        B: { name: 'box_body', role: 'body' },
        R: { name: 'panels', role: 'accessory' },
        G: { name: 'glow_seam', role: 'eye' },
        C: { name: 'base_trim', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. OWL OF WISDOM ─────────────────────────────
    {
      id: 'owl_wisdom_16',
      description: 'Perched owl symbolizing Athena and wisdom.',
      grid: [
        '................',
        '................',
        '....TTBBTT......',
        '...TBBBBBBT.....',
        '...BEEBBEEB.....',
        '...BBBBBBBB.....',
        '...BBBNNBBB.....',
        '...BBBBBBBB.....',
        '....BWWWWB......',
        '....BWWWWB......',
        '....BWWWWB......',
        '.....BWWB.......',
        '.....BWWB.......',
        '....CCCCCC......',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'ear_tufts', role: 'accessory' },
        B: { name: 'plumage', role: 'body' },
        E: { name: 'eyes', role: 'eye' },
        N: { name: 'beak', role: 'arm' },
        W: { name: 'breast', role: 'head' },
        C: { name: 'talons', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. TRUTH MIRROR ──────────────────────────────
    {
      id: 'truth_mirror_16',
      description: 'Ornate hand mirror symbolizing clear sight and self-knowledge.',
      grid: [
        '................',
        '.....FFFF.......',
        '....FFRRRFF.....',
        '...FFRMMMMRFF...',
        '...FRMMMMMMRF...',
        '...FRMMHHMMRF...',
        '...FRMMMMMMRF...',
        '...FFRMMMMRFF...',
        '....FFRRRFF.....',
        '.....FFFF.......',
        '......HH........',
        '......HH........',
        '......HH........',
        '.....HHHH.......',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        R: { name: 'rim', role: 'accessory' },
        M: { name: 'mirror_glass', role: 'head' },
        H: { name: 'handle', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. LABYRINTH TILE ────────────────────────────
    {
      id: 'labyrinth_tile_16',
      description: 'Top-down maze tile pattern inspired by Chartres labyrinth.',
      grid: [
        'WWWWWWWWWWWWWWWW',
        'W..............W',
        'W.WWWWWWWWWWWW.W',
        'W.W..........W.W',
        'W.W.WWWWWWWW.W.W',
        'W.W.W......W.W.W',
        'W.W.W.WWWW.W.W.W',
        'W.W.W.W..W.W.W.W',
        'W.W.W.WGGW.W.W.W',
        'W.W.W.WWWW.W.W.W',
        'W.W.W......W.W.W',
        'W.W.WWWWWWWW.W.W',
        'W.W..........W.W',
        'W.WWWWWWWWWWWW.W',
        'W..............W',
        'WWWWWWWWWWWWWWWW',
      ],
      chars: {
        W: { name: 'walls', role: 'body' },
        G: { name: 'center_gem', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════
    // RHETORIC — Oratory & Persuasion (13 of 14)
    // ═══════════════════════════════════════════════════

    // ─── 8. ORATOR'S LECTERN ──────────────────────────
    {
      id: 'orators_lectern_16',
      description: 'Tall wooden lectern with angled reading surface and carved front.',
      grid: [
        '................',
        '...RRRRRRRR.....',
        '..RRBBBBBBRR....',
        '..RRBBBBBBRR....',
        '...RRBBBBRR.....',
        '....FFFFFFFFFFF.',
        '....FFDDDDDDFF..',
        '....FFDDGGDDFF..',
        '....FFDDGGDDFF..',
        '....FFDDDDDDFF..',
        '....FFFFFFFFFFF.',
        '.....FFPPFF.....',
        '......PPPP......',
        '......PPPP......',
        '....BBBBBBBB....',
        '................',
      ],
      chars: {
        R: { name: 'reading_surface', role: 'head' },
        B: { name: 'book_on_top', role: 'accessory' },
        F: { name: 'front_panel', role: 'body' },
        D: { name: 'carved_panel', role: 'arm' },
        G: { name: 'gold_emblem', role: 'eye' },
        P: { name: 'pedestal', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. WAX SEAL STAMP ────────────────────────────
    {
      id: 'wax_seal_stamp_16',
      description: 'Wooden-handled wax seal stamp with metal face.',
      grid: [
        '................',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '.....BBBB.......',
        '....FFFFFF......',
        '...FFSSSSFF.....',
        '...FFSSSSFF.....',
        '...FFFFFFFF.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'handle', role: 'body' },
        F: { name: 'seal_face', role: 'head' },
        S: { name: 'engraved_pattern', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. SEALED LETTER ────────────────────────────
    {
      id: 'sealed_letter_16',
      description: 'Folded parchment letter sealed with red wax.',
      grid: [
        '................',
        '................',
        '................',
        '..PPPPPPPPPP....',
        '..PPPPPPPPPP....',
        '..PPPPPPPPPP....',
        '..PPPPPPPPPP....',
        '..PPPPSSSPPP....',
        '..PPPSSSSSPP....',
        '..PPPSSSSSPP....',
        '..PPPPSSSPPP....',
        '..PPPPPPPPPP....',
        '..PPPPPPPPPP....',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'parchment', role: 'body' },
        S: { name: 'wax_seal', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 11. LAUREL WREATH ────────────────────────────
    {
      id: 'laurel_wreath_16',
      description: 'Victory laurel wreath crown for triumph in debate.',
      grid: [
        '................',
        '.....LLLLLL.....',
        '....LL....LL....',
        '...LL......LL...',
        '..LL........LL..',
        '..LL........LL..',
        '..LL........LL..',
        '..LL........LL..',
        '..LL........LL..',
        '...LL......LL...',
        '....LL....LL....',
        '.....LLRRLL.....',
        '......RRRR......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'body' },
        R: { name: 'ribbon_tie', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 12. SPEAKING HORN ────────────────────────────
    {
      id: 'speaking_horn_16',
      description: 'Medieval speaking trumpet for amplifying the voice.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        'MM..............',
        'MMBB............',
        'MMBBBBBB........',
        'MMBBBBBBBBFFFF..',
        'MMBBBBBB..FFFF..',
        'MMBB......FFFF..',
        'MM........FFFF..',
        '..........FFFF..',
        '................',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'mouthpiece', role: 'arm' },
        B: { name: 'tube_body', role: 'body' },
        F: { name: 'flared_bell', role: 'head' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. ROYAL DECREE ─────────────────────────────
    {
      id: 'royal_decree_16',
      description: 'Royal proclamation scroll with crown symbol and gold border.',
      grid: [
        '................',
        '..GRRRRRRRRGG...',
        '..GPPPPPPPPGG...',
        '..GPPCPPPCPPG...',
        '..GPPCCCCPPGG...',
        '..GPPPPPPPPPG...',
        '..GPPP.PP.PPG...',
        '..GPPPPPPPPPG...',
        '..GPPP..PPPPG...',
        '..GPPPPPPPPPG...',
        '..GPPPPSSPPPG...',
        '..GPPPPSSPPPG...',
        '..GPPPPPPPPGG...',
        '..GRRRRRRRRGG...',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'gold_border', role: 'accessory' },
        R: { name: 'rollers', role: 'arm' },
        P: { name: 'parchment', role: 'body' },
        C: { name: 'crown_symbol', role: 'eye' },
        S: { name: 'seal', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 14. COMEDY MASK ──────────────────────────────
    {
      id: 'theater_mask_comedy_16',
      description: 'Smiling comedy theater mask for rhetoric and performance.',
      grid: [
        '................',
        '....FFFFFF......',
        '...FFFFFFFFFF...',
        '..FFFFFFFFFFFF..',
        '..FFEEFFFFEEFF..',
        '..FFEEFFFFEE.F..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFF...',
        '..FF.FFFFFF.FF..',
        '..FFF......FFF..',
        '..FFFFFFFFFF.F..',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'mask_face', role: 'body' },
        E: { name: 'eye_holes', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 15. TRAGEDY MASK ─────────────────────────────
    {
      id: 'theater_mask_tragedy_16',
      description: 'Frowning tragedy theater mask for rhetoric and drama.',
      grid: [
        '................',
        '....FFFFFF......',
        '...FFFFFFFFFF...',
        '..FFFFFFFFFFFF..',
        '..FFEEFFFFEEFF..',
        '..FFEEFFFFEE.F..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFF...',
        '..FFF......FFF..',
        '..FF.FFFFFF.FF..',
        '..FFFFFFFFFF.F..',
        '...FFFFFFFFFF...',
        '....FFFFFFFF....',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'mask_face', role: 'body' },
        E: { name: 'eye_holes', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 16. HERALD BANNER ────────────────────────────
    {
      id: 'herald_banner_16',
      description: 'Heraldic banner on pole with lion device.',
      grid: [
        '..PP............',
        '..PPBBBBBBBB....',
        '..PPBBBBBBBB....',
        '..PPBBBBBBBB....',
        '..PPBBGGGGBB....',
        '..PPBBGGGGBB....',
        '..PPBBBBBBBB....',
        '..PPBBBBBBBB....',
        '..PP..BBBBBB....',
        '..PP....BBBB....',
        '..PP......BB....',
        '..PP............',
        '..PP............',
        '..PP............',
        '..PP............',
        '................',
      ],
      chars: {
        P: { name: 'pole', role: 'arm' },
        B: { name: 'banner_cloth', role: 'body' },
        G: { name: 'device_symbol', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. SIGNET RING ──────────────────────────────
    {
      id: 'signet_ring_16',
      description: 'Gold signet ring with engraved seal face.',
      grid: [
        '................',
        '................',
        '................',
        '....SSSSSS......',
        '...SSEEEESS.....',
        '..SSEEEEEESS....',
        '..SSEEEEEESS....',
        '...SSEEEESS.....',
        '....SSSSSS......',
        '...RR....RR.....',
        '..RR......RR....',
        '..RR......RR....',
        '...RR....RR.....',
        '....RRRRRR......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'seal_face', role: 'head' },
        E: { name: 'engraving', role: 'eye' },
        R: { name: 'ring_band', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 18. PULPIT ───────────────────────────────────
    {
      id: 'church_pulpit_16',
      description: 'Elevated church pulpit for preaching and oratory.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '...RRRRRRRRRR...',
        '...FFFFFFFFFF...',
        '...FFPPPPPPFF...',
        '...FFPPPPPPFF...',
        '...FFPPGGPPFF...',
        '...FFPPGGPPFF...',
        '...FFPPPPPPFF...',
        '....FFFFFFFF....',
        '.....FFFFFF.....',
        '......FFFF......',
        '......FFFF......',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        P: { name: 'panel', role: 'head' },
        G: { name: 'cross_emblem', role: 'eye' },
        B: { name: 'base', role: 'belt' },
        R: { name: 'reading_surface', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. HERALDIC SHIELD ──────────────────────────
    {
      id: 'heraldic_shield_16',
      description: 'Decorated heraldic shield with quartered coat of arms.',
      grid: [
        '................',
        '.FFFFFFFFFFFF...',
        '.FRRRRRSBBBBF...',
        '.FRRRRRSBBBBF...',
        '.FRRRRRSBBBBF...',
        '.FRRRRRSBBBBF...',
        '.FSSSSSSSSSSF...',
        '.FBBBBRSRRRRF...',
        '.FBBBBRSRRRRF...',
        '.FBBBBRSRRRRF...',
        '..FBBBRRRRRRF...',
        '..FFBBRRRRRFF...',
        '...FFBBRRRFF....',
        '....FFFFFFFF....',
        '.....FFFFFF.....',
        '................',
      ],
      chars: {
        F: { name: 'border', role: 'body' },
        R: { name: 'field_red', role: 'accessory' },
        B: { name: 'field_blue', role: 'arm' },
        S: { name: 'divider_cross', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. SPEECH SCROLL ────────────────────────────
    {
      id: 'speech_scroll_16',
      description: 'Unfurling speech scroll with flowing text lines.',
      grid: [
        '................',
        '..RRRR..........',
        '..RPPPRRR.......',
        '..RPPPPPRR......',
        '..RP.PP.PPRR....',
        '..RPPPPPPPPRRR..',
        '..RP..PPPPPPRR..',
        '..RPPPPPP.PPPR..',
        '..RP.PPPPPPPPPR.',
        '..RPPPPP..PPPPR.',
        '..RPPPPPPPPPPPR.',
        '...RRPPPPPPPPR..',
        '.....RRRRRRRR...',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'scroll_edge', role: 'arm' },
        P: { name: 'parchment', role: 'body' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
