/**
 * Medieval Scholar's Collection — Batch 1: Grammar (14) + Logic (6) = 20 templates.
 * The 7 Liberal Arts bundle for itch.io.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_BATCH1_TEMPLATES', schemes: 'LIBERAL_ARTS_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════
    // GRAMMAR — Writing Tools, Books, Manuscripts (14)
    // ═══════════════════════════════════════════════════

    // ─── 1. QUILL PEN — feathered writing quill ───────
    {
      id: 'quill_pen_16',
      description: 'Feathered quill pen angled for writing with ink-tipped nib.',
      grid: [
        '................',
        '..........FFFF..',
        '.........FFFFF..',
        '........FFFFF...',
        '.......FFFF.....',
        '......FFSS......',
        '.....FFSS.......',
        '....SSSS........',
        '...SSSS.........',
        '..SSNN..........',
        '.SSNN...........',
        '.NNN............',
        '.II.............',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'feather_vane', role: 'body' },
        S: { name: 'shaft', role: 'head' },
        N: { name: 'nib', role: 'arm' },
        I: { name: 'ink_tip', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 2. INKWELL WITH QUILL — pot with quill resting in it ───
    {
      id: 'inkwell_quill_16',
      description: 'Round ceramic inkwell with quill pen resting inside.',
      grid: [
        '................',
        '........FF......',
        '.......FF.......',
        '......FF........',
        '.....FFR........',
        '.....RRRRRR.....',
        '....RRIIIIRR....',
        '...RRIIIIIIRR...',
        '...RRIIIIIIRR...',
        '...RRIIIIIIRR...',
        '....RRIIIIRR....',
        '....RRRRRRRR....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'quill', role: 'accessory' },
        R: { name: 'pot_rim', role: 'head' },
        I: { name: 'ink_surface', role: 'eye' },
        B: { name: 'pot_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 3. OPEN CODEX — open book lying flat ─────────
    {
      id: 'open_codex_16',
      description: 'Open leather-bound codex with visible text on both pages.',
      grid: [
        '................',
        '................',
        '.CCPPPPSPPPCC...',
        '.CCPPPPSPPPCC...',
        '.CCP..PSPPPCC...',
        '.CCPPPPSPPPCC...',
        '.CCP..PSP.PCC...',
        '.CCPPPPSPPPCC...',
        '.CCP..PSPPPCC...',
        '.CCPPPPSPPPCC...',
        '.CCPPPPSPPPCC...',
        '.CCPPPP.PPPCC...',
        '.CCCCCCCCCCCC...',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cover', role: 'body' },
        P: { name: 'pages', role: 'head' },
        S: { name: 'spine', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 4. ROLLED SCROLL — tightly rolled with ribbon ──
    {
      id: 'rolled_scroll_16',
      description: 'Tightly rolled parchment scroll tied with a red ribbon.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..KRRRRRRRRRRK..',
        '..KPPPPPPPPPPK..',
        '..KPPPPPPPPPPK..',
        '...PPPPRRPPPP...',
        '...PPPPRRPPPP...',
        '..KPPPPPPPPPPK..',
        '..KPPPPPPPPPPK..',
        '..KRRRRRRRRRRK..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rollers', role: 'arm' },
        K: { name: 'knobs', role: 'belt' },
        P: { name: 'parchment', role: 'body' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 5. UNFURLED SCROLL — open scroll with text and seal ──
    {
      id: 'unfurled_scroll_16',
      description: 'Partially unrolled scroll with visible writing and wax seal.',
      grid: [
        '................',
        '..RRRRRRRRRR....',
        '..KPPPPPPPPK....',
        '...PPPPPPPP.....',
        '...PP.PP.PP.....',
        '...PPPPPPPP.....',
        '...PP..P.PP.....',
        '...PPPPPPPP.....',
        '...PP.PPPPP.....',
        '...PPPPPPPP.....',
        '...PPPPWWPP.....',
        '...PPPPWWPP.....',
        '..KPPPPPPPPK....',
        '..RRRRRRRRRR....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rollers', role: 'arm' },
        K: { name: 'knobs', role: 'belt' },
        P: { name: 'parchment', role: 'body' },
        W: { name: 'wax_seal', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 6. WAX TABLET — hinged writing tablet with stylus marks ──
    {
      id: 'wax_tablet_16',
      description: 'Hinged wooden wax tablet with etched writing marks.',
      grid: [
        '................',
        '.FFFFFFFFFFFF...',
        '.FWWWWWWWWWWF...',
        '.FWWWWWWWWWWF...',
        '.FWW.WWW.WWWF...',
        '.FWWWWWWWWWWF...',
        '.FWW..WW.WWWF...',
        '.FWWWWWWWWWWF...',
        '.FWW.WWWWWWWF...',
        '.FWWWWWWWWWWF...',
        '.FWWWWWWWWWWF...',
        '.FFFFFFFFFFFF...',
        '.HH.........HH..',
        '.FFFFFFFFFFFF...',
        '.FFFFFFFFFFFF...',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        W: { name: 'wax_surface', role: 'head' },
        H: { name: 'hinge', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. ILLUMINATED LETTER — ornate capital on parchment ──
    {
      id: 'illuminated_letter_16',
      description: 'Ornate illuminated capital letter on parchment with vine detail.',
      grid: [
        '................',
        '.PPPPPPPPPPPP...',
        '.PLLLLLLLLLLP...',
        '.PLVV.LLLLLLP...',
        '.PLV.VLLLLLLP...',
        '.PLVVVLLLLLLP...',
        '.PLV.VLLLLLLP...',
        '.PLV.VLLLLLLP...',
        '.PLLLLLLLLLLP...',
        '.PLL.LL.LLLLP...',
        '.PLLLLLLLLLLP...',
        '.PLL.LLL.LLLP...',
        '.PLLLLLLLLLVP...',
        '.PPPPPPPPPPPP...',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'parchment', role: 'head' },
        L: { name: 'letter_body', role: 'body' },
        V: { name: 'vine_detail', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. LEATHER TOME — thick closed leather book ──
    {
      id: 'leather_tome_16',
      description: 'Thick leather-bound tome with metal clasp and visible page edges.',
      grid: [
        '................',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBGGBBBB..',
        '..SSBBBBGGBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBCC..',
        '..SSBBBBBBBBCC..',
        '..SSPPPPPPPPPP..',
        '..SSBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'spine', role: 'arm' },
        B: { name: 'cover', role: 'body' },
        P: { name: 'page_edge', role: 'head' },
        G: { name: 'gold_emboss', role: 'accessory' },
        C: { name: 'clasp', role: 'belt' },
      },
      colors: {
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 9. PARCHMENT SHEET — single page with curled corner ──
    {
      id: 'parchment_sheet_16',
      description: 'Single parchment page with writing and one curled corner.',
      grid: [
        '................',
        '................',
        '...PPPPPPPPPP...',
        '...PPPPPPPPPP...',
        '...PP.PP.PPPP...',
        '...PPPPPPPPPP...',
        '...PP..PPPPPP...',
        '...PPPPPPPPPP...',
        '...PP.PPPPPPP...',
        '...PPPPPPPPPP...',
        '...PP..PPRRPP...',
        '...PPPPPPRRCC...',
        '...PPPPPPPPCC...',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'parchment', role: 'body' },
        R: { name: 'red_ink', role: 'eye' },
        C: { name: 'curl_shadow', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 10. GRAMMAR PRIMER — ABC teaching slate ──────
    {
      id: 'grammar_primer_16',
      description: 'Small chalk slate with ABC letters and wooden frame.',
      grid: [
        '................',
        '.HH.............',
        '.FFFFFFFFFFFF...',
        '.FSSSSSSSSSSF...',
        '.FSSSSSSSSSSF...',
        '.FSSCCSCCSCSF...',
        '.FSSC.SC.SCSF...',
        '.FSSCCSC.SCSF...',
        '.FSSC.SCCSCSF...',
        '.FSSC.SC.SCSF...',
        '.FSSSSSSSSSSF...',
        '.FSSSSSSSSSSF...',
        '.FFFFFFFFFFFF...',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        S: { name: 'slate', role: 'head' },
        C: { name: 'chalk_letters', role: 'arm' },
        H: { name: 'handle', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 11. SCRIBE'S LECTERN — angled desk with book ──
    {
      id: 'scribes_lectern_16',
      description: 'Angled scribe lectern with open book resting on surface.',
      grid: [
        '................',
        '................',
        '...BBBBRRRR.....',
        '...BBBBRRRR.....',
        '....BBBBRRRR....',
        '....BBBBRRRR....',
        '.....BBBBRRRR...',
        '.....BBBBRRR....',
        '......PPPP......',
        '......PPPP......',
        '......PPPP......',
        '......PPPP......',
        '......PPPP......',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '................',
      ],
      chars: {
        B: { name: 'book_cover', role: 'accessory' },
        R: { name: 'book_pages', role: 'head' },
        P: { name: 'post', role: 'body' },
        F: { name: 'base_foot', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 12. INK POT — small ceramic ink pot ──────────
    {
      id: 'ink_pot_16',
      description: 'Small round ceramic ink pot with dark ink visible inside.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....IIIIII.....',
        '....IIIIIIII....',
        '....RRRRRRRR....',
        '...RRBBBBBBR....',
        '...RRBBBBBBR....',
        '...RRBBBBBBR....',
        '...RRBBBBBBR....',
        '....RRRRRRRR....',
        '.....FFFFFF.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        I: { name: 'ink_surface', role: 'eye' },
        R: { name: 'rim_wall', role: 'head' },
        B: { name: 'pot_body', role: 'body' },
        F: { name: 'base_foot', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. REED PEN — simple calamus reed pen ──────
    {
      id: 'reed_pen_16',
      description: 'Simple bamboo reed pen with cut nib for calligraphy.',
      grid: [
        '................',
        '...........SS...',
        '..........SS....',
        '.........SS.....',
        '........SS......',
        '.......SS.......',
        '......SS........',
        '.....SS.........',
        '....SS..........',
        '...SS...........',
        '..NN............',
        '..NN............',
        '.II.............',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'shaft', role: 'body' },
        N: { name: 'nib_cut', role: 'head' },
        I: { name: 'ink_tip', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 14. SCROLL RACK — shelf with scrolls and books ──
    {
      id: 'scroll_rack_16',
      description: 'Small wooden shelf with rolled scrolls and standing books.',
      grid: [
        '..FFFFFFFFFFFF..',
        '..FSSSSRRRRBBF..',
        '..FSSSSRRRRBBF..',
        '..FFFFFFFFFFFF..',
        '..FRRBBSSSSBBF..',
        '..FRRBBSSSSBBF..',
        '..FFFFFFFFFFFF..',
        '..FBBSSRRRRSSF..',
        '..FBBSSRRRRSSF..',
        '..FFFFFFFFFFFF..',
        '..FSSRRBBRRSSF..',
        '..FSSRRBBRRSSF..',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        S: { name: 'scrolls', role: 'head' },
        R: { name: 'red_books', role: 'accessory' },
        B: { name: 'blue_books', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ═══════════════════════════════════════════════════
    // LOGIC — Reasoning & Wisdom Symbols (6 of 13)
    // ═══════════════════════════════════════════════════

    // ─── 15. BALANCE SCALE — two-pan weighing scale ───
    {
      id: 'balance_scale_16',
      description: 'Two-pan balance scale for weighing arguments and truth.',
      grid: [
        '................',
        '.......GG.......',
        '......GGGG......',
        '.CCCCCCPPCCCCCC.',
        '..CC...PP...CC..',
        '..CC...PP...CC..',
        '.CCCC..PP..CCCC.',
        '.BBBB..PP..BBBB.',
        '.BBBB..PP..BBBB.',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '................',
      ],
      chars: {
        G: { name: 'crown_pivot', role: 'eye' },
        C: { name: 'chains_beam', role: 'arm' },
        P: { name: 'post', role: 'body' },
        B: { name: 'pans', role: 'head' },
        F: { name: 'base', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. LOGIC WHEEL — circular pattern wheel ─────
    {
      id: 'logic_wheel_16',
      description: 'Patterned circular wheel of logical relationships and categories.',
      grid: [
        '................',
        '................',
        '.....RRRRRR.....',
        '...RRRRRRRRRR...',
        '..RRBBBSSBBBRR..',
        '..RBBBBSSBBBBR..',
        '..RSSSSGGSSSSR..',
        '..RSSSSGGSSSSR..',
        '..RBBBBSSBBBBR..',
        '..RRBBBSSBBBRR..',
        '...RRRRRRRRRR...',
        '.....RRRRRR.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'outer_ring', role: 'body' },
        B: { name: 'quadrant_fill', role: 'head' },
        S: { name: 'cross_spokes', role: 'arm' },
        G: { name: 'center_hub', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 17. CHESS KING — chess piece for strategy ────
    {
      id: 'chess_king_16',
      description: 'Ornate chess king piece symbolizing strategic logical thinking.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '.......CC.......',
        '......GGGG......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '................',
      ],
      chars: {
        C: { name: 'cross_top', role: 'eye' },
        G: { name: 'crown', role: 'accessory' },
        B: { name: 'piece_body', role: 'head' },
        F: { name: 'base', role: 'body' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. SKELETON KEY — ornate key for unlocking truth ──
    {
      id: 'skeleton_key_16',
      description: 'Ornate medieval skeleton key symbolizing unlocking truth.',
      grid: [
        '................',
        '......BBBB......',
        '.....BB..BB.....',
        '.....BB..BB.....',
        '.....BB..BB.....',
        '......BBBB......',
        '.......SS.......',
        '.......SS.......',
        '.......SS.......',
        '.......SS.......',
        '.......SS.......',
        '.......SSTT.....',
        '.......SS.TT....',
        '.......SSTT.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bow_handle', role: 'body' },
        S: { name: 'shaft', role: 'head' },
        T: { name: 'teeth_bit', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. OIL LANTERN — medieval lantern (light of reason) ──
    {
      id: 'oil_lantern_16',
      description: 'Medieval oil lantern representing the light of reason.',
      grid: [
        '................',
        '......HHHH......',
        '.....HH..HH.....',
        '......HHHH......',
        '.....FFFFFF.....',
        '....FFGGGGFF....',
        '....FFGGGGFF....',
        '....FFGGGGFF....',
        '....FFGGGGFF....',
        '....FFGGGGFF....',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'arm' },
        F: { name: 'frame', role: 'body' },
        G: { name: 'glass_flame', role: 'eye' },
        B: { name: 'base', role: 'belt' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. HOURGLASS — time and deliberation ────────
    {
      id: 'hourglass_16',
      description: 'Wooden-framed hourglass with golden sand flowing through.',
      grid: [
        '................',
        '...FFFFFFFFFF...',
        '...FGGGGGGGGF...',
        '....FGGSSGGF....',
        '.....FGSSGF.....',
        '......FSSF......',
        '......FSSF......',
        '.......FF.......',
        '.......FF.......',
        '......FSSF......',
        '......FSSF......',
        '.....FGGSSGF....',
        '....FGGSSSSGF...',
        '...FGGSSSSSSGF..',
        '...FFFFFFFFFF...',
        '................',
      ],
      chars: {
        F: { name: 'frame_posts', role: 'body' },
        G: { name: 'glass_bulb', role: 'head' },
        S: { name: 'sand', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
