/**
 * Medieval Scholar's Collection — 32x32 Batch 5
 * Astronomy (10) + Mixed Scholarly (10) = 20 templates.
 *
 * All 32x32, DB16 palette only, ASCII grid format.
 * Neo-SNES style (Chrono Trigger + Sea of Stars quality).
 * Colored selout, 4-8 roles per template, light from top-left.
 *
 * VALIDATION: Every grid = exactly 32 rows x 32 chars.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_32_BATCH5_TEMPLATES', schemes: 'LIBERAL_ARTS_32_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    //  ASTRONOMY (10 templates)
    // ═══════════════════════════════════════════════════════════════

    // ─── 1. ZODIAC WHEEL ───────────────────────────────────────────
    {
      id: 'zodiac_wheel_32',
      description: 'Circular zodiac wheel with 12 alternating warm/cool segments, gold outer ring, and central sun emblem.',
      size: 32,
      grid: [
        //CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC  (32 ruler)
        '................................', // row 0
        '.........AAAAAAAAAAAAA..........',
        '........AAAAAAAAAAAAAAA.........',
        '......AAABBBBCCCCCBBBBAAA.......',
        '.....AABBB..........BBBAA......',
        '....AABC..............CBAA.....',
        '...AABB................BBAA....',
        '...ABC......EEEEE......CBA....',
        '..AABB.....EEEEEEE.....BBAA...',
        '..ABC.....EEEEEEEEE.....CBA...',
        '..ABB....EEEEEDEEEE.....BBA...',
        '.AABC....EEEEDDDEEE....CBAA...',
        '.AABB....EEEDDDDEEE....BBAA...',
        '.ABC.....EEEDDDDEEE.....CBA...',
        '.ABB.....EEEEDDDEEE.....BBA...',
        '.AABC....EEEEEDEEEE....CBAA...',
        '.AABB.....EEEEEEEEE....BBAA...',
        '.ABC......EEEEEEE......CBA....',
        '..ABB......EEEEE......BBA.....',
        '..AABC................CBAA....',
        '..AABB................BBAA....',
        '...ABC..............CBA.......',
        '...AABBB..........BBBAA.......',
        '....AAABBBBCCCCCBBBAAA.........',
        '.....AAAAAAAAAAAAAAAA..........',
        '........AAAAAAAAAAAA...........',
        '..........AAAAAAAA.............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'outer_ring', role: 'body' },
        B: { name: 'segments_warm', role: 'head' },
        C: { name: 'segments_cool', role: 'arm' },
        D: { name: 'center_sun', role: 'eye' },
        E: { name: 'inner_field', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. ECLIPSE DIAGRAM ────────────────────────────────────────
    {
      id: 'eclipse_diagram_32',
      description: 'Sun-moon eclipse alignment diagram with bright corona, dark moon disc, and scattered stars.',
      size: 32,
      grid: [
        '................................',
        '......E..........E..............',
        '..........AAAAAAA...............',
        '........AAAAAAAAAAA.............',
        '.......AAAAACCCCAAAA............',
        '......AAAACCCCCCCAAAA...........',
        '.....AAAACCCCCCCCCAAAA..........',
        '....AAAACCCCCCCCCCCCAAA.........',
        '....AAACCCCCCCCCCCCCAAA.........',
        '...AAAACCCCCCCCCCCCCCAAA........',
        '...AAACCCCCCCCCCCCCCCAAA........',
        '..AAAACCCCCCCCCCCCCCCCAAA.......',
        '..AAACCCCCCCCCCCCCCCCCAAA.......',
        '..AAACCCCCCCCCCCCCCCCCAAA.......',
        '..AAACCCCCCCCCCCCCCCCCAAA.......',
        '..AAAACCCCCCCCCCCCCCCCAAA.......',
        '...AAACCCCCCCCCCCCCCCAAA........',
        '...AAAACCCCCCCCCCCCCCAAA........',
        '....AAACCCCCCCCCCCCCAAA.........',
        '....AAAACCCCCCCCCCCCAAA.........',
        '....AAAACCCCCCCCCCCAAAA.........',
        '.....AAAACCCCCCCCCAAAA..........',
        '......AAAACCCCCCAAAAA...........',
        '.......AAAAACCCCAAAA............',
        '........AAAAAAAAAAA.............',
        '..........AAAAAAA...............',
        '...E.........................E..',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'corona', role: 'body' },
        C: { name: 'moon_disc', role: 'head' },
        E: { name: 'stars', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 3. CONSTELLATION MAP ──────────────────────────────────────
    {
      id: 'constellation_map_32',
      description: 'Circular constellation map on dark sky with bright stars, connecting lines, and steel border ring.',
      size: 32,
      grid: [
        '................................',
        '.........DDDDDDDDDDDDD.........',
        '.......DDDAAAAAAAAADDDDD.......',
        '......DDAAAAAAAAAAAAAADDD.......',
        '.....DDAAABAAAAAABAAAAADD.......',
        '....DDAAACAAAAACAAAAAAADDD.....',
        '...DDDAACAAACAAABAAAAAADDD.....',
        '...DDAAAAAABACAACAAAAAADDDD....',
        '..DDDAAACAAABAAACAAAADDDDDD...',
        '..DDAAAAAACAAABCAAAADDDDDDD...',
        '..DDAABAAACAAAAAAAABAADDDD.....',
        '.DDDAAACAACAAACAAACAADDDDDD...',
        '.DDAAAAAABAAACAACAAADDDDDDDD..',
        '.DDAAACAAAACAAACAAAAAADDDDD...',
        '.DDAACAAAAACAAACAAABAAADDDD...',
        '.DDDAAABAAAAAAAAACAAADDDDDD...',
        '.DDAAAAAACAAABACAAAAAADDDDD...',
        '..DDAAACAAACAAACAAAAAADDDD....',
        '..DDDAAACAAACAAAAAAADDDDDD...',
        '..DDAABAAAAACAAABAAADDDDDD....',
        '...DDAAAAAACAAAAAADDDDDDDD...',
        '...DDDAACAAAAABAADDDDDDDD....',
        '....DDDAAAAAAAAAAADDDDDDD....',
        '.....DDDAAABAAAAAADDDDDD.....',
        '......DDDDDAAAAAADDDDDDD.....',
        '.......DDDDDDDDDDDDDDDDD....',
        '.........DDDDDDDDDDDDDDD....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'sky_field', role: 'body' },
        B: { name: 'bright_stars', role: 'head' },
        C: { name: 'constellation_lines', role: 'arm' },
        D: { name: 'border_ring', role: 'eye' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. ASTRONOMER TOOLS ───────────────────────────────────────
    {
      id: 'astronomer_tools_32',
      description: 'Grouped arrangement of astronomical tools: astrolabe, compass, scroll, and quill on a desk.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..........EEEEE.................',
        '.........EAAAAAE................',
        '........EAAAAAAE................',
        '........EAAADDAE......FF.......',
        '........EAAADAAE.....FF........',
        '.........EAAAAAE....FF.........',
        '..........EEEEE....FF..........',
        '...................FF...........',
        '..................FF............',
        '.............BBBB.FF...........',
        '............BBBBBFF............',
        '...........BBBBBBB.............',
        '...........BBBBBBB.............',
        '..CCCCCCCCCCBBBBBB.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '..CCCCCCCCCCCCCCCC.............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'astrolabe', role: 'body' },
        B: { name: 'compass', role: 'head' },
        C: { name: 'scroll', role: 'arm' },
        D: { name: 'star_pointers', role: 'eye' },
        E: { name: 'astrolabe_ring', role: 'accessory' },
        F: { name: 'quill', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. CELESTIAL COMPASS ──────────────────────────────────────
    {
      id: 'celestial_compass_32',
      description: 'Ornate celestial navigation compass with detailed dial face, cardinal points, and glass cover.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '............AAAA................',
        '...........AABBAA...............',
        '..........AABBBBAA..............',
        '.........DDDDDDDDDDD...........',
        '........DDCCCCCCCCCCCDD.........',
        '.......DDCCCCCCCCCCCCCDD........',
        '......DDCCCCCCCCCCCCCCCCDD......',
        '.....DDCCCCCCCECCCCCCCCDD.......',
        '.....DCCCCCCCEEECCCCCCCCDD......',
        '....DDCCCCCCEEEEECCCCCCCDD.....',
        '....DCCCCCCEEEEEEECCCCCCDD.....',
        '....DDCCCCCCEEEECCCCCCCCDD.....',
        '....DDCCCCCCCEECCCCCCCCDD......',
        '.....DCCCCCCCCECCCCCCCDD.......',
        '.....DDCCCCCCCCCCCCCCDD........',
        '......DDCCCCCCCCCCCCDD.........',
        '.......DDCCCCCCCCCCCDD.........',
        '........DDDCCCCCCCDDDD.........',
        '.........DDDDDDDDDDD...........',
        '..........DDDDDDDDD............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'top_ring', role: 'body' },
        B: { name: 'bail_loop', role: 'head' },
        C: { name: 'dial_face', role: 'arm' },
        D: { name: 'case_rim', role: 'eye' },
        E: { name: 'needle', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 6. QUADRANT ───────────────────────────────────────────────
    {
      id: 'quadrant_32',
      description: 'Medieval astronomical quadrant instrument with graduated arc, sighting vane, and plumb line.',
      size: 32,
      grid: [
        '................................',
        '..AABBB.........................',
        '..AABBBB........................',
        '..AACBBBBB......................',
        '..AACCBBBBBB....................',
        '..AACCCBBBBBBB..................',
        '..AACCCCBBBBBBBB................',
        '..AACCCCCBBBBBBBBB..............',
        '..AACCCCCCBBBBBBBBBB............',
        '..AACCCCCCCBBBBBBBBBB...........',
        '..AACCCCCCCCBBBBBBBBB...........',
        '..AACCCCCCCCCBBBBBBBB...........',
        '..AADDDDDDDDDDDDBBBBB..........',
        '..AA............DDBBBB..........',
        '..AA..............DDBBB.........',
        '..AA...............DDBB.........',
        '..AA................DDB.........',
        '..AA.................DD.........',
        '..AA.......................E....',
        '..AA.......................E....',
        '..AA.......................E....',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAAAA.',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAAAA.',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'frame', role: 'body' },
        B: { name: 'scale_arc', role: 'head' },
        C: { name: 'graduated_marks', role: 'arm' },
        D: { name: 'sighting_vane', role: 'eye' },
        E: { name: 'plumb_line', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. SCHOLAR'S LAMP ─────────────────────────────────────────
    {
      id: 'scholars_lamp_32',
      description: 'Oil lamp for nighttime study with brass body, glass shade, glowing flame, and wooden base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..............BB................',
        '.............BBBB...............',
        '............BBBBBB..............',
        '...........CCBBBBCC.............',
        '...........CCBBBBCC.............',
        '..........CCCBBBBCCC............',
        '..........CCCBBBBCCC............',
        '..........CCCCBBCCCC............',
        '...........CCCCCCCC.............',
        '...........CCCCCCCC.............',
        '............AAAAAA..............',
        '............AAAAAA..............',
        '...........AAAAAAAA.............',
        '...........AAAAAAAA.............',
        '...........AAAAAAAA.............',
        '............AAAAAA..............',
        '............AAAAAA..............',
        '.............AAAA...............',
        '.............DDDD...............',
        '............DDDDDD..............',
        '............DDDDDD..............',
        '...........EEEEEEEE.............',
        '..........EEEEEEEEEE............',
        '..........EEEEEEEEEE............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'lamp_body', role: 'body' },
        B: { name: 'flame', role: 'head' },
        C: { name: 'glass_shade', role: 'arm' },
        D: { name: 'stem', role: 'eye' },
        E: { name: 'base', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 8. LECTERN ────────────────────────────────────────────────
    {
      id: 'lectern_32',
      description: 'Reading lectern bookstand with angled book rest, open book, and ornate wooden base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.....DDDDDDDDDDDDDDDDD........',
        '.....DDDDDDDDDDDDDDDDDD.......',
        '....DDDDDDDDDDDDDDDDDDD.......',
        '....DDDDDDDDDDDDDDDDDD........',
        '...AAAAAAAAAAAAAAAAAAAA.........',
        '...AAAAAAAAAAAAAAAAAAAAA........',
        '....AAAAAAAAAAAAAAAAAAA.........',
        '.....AAAAAAAAAAAAAAAAAA.........',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '..........AAAA..................',
        '.........CCCCCC.................',
        '........CCCCCCCC................',
        '.......CCCCCCCCCC...............',
        '......CCCCCCCCCCCC..............',
        '.....EEEEEEEEEEEEEE............',
        '....EEEEEEEEEEEEEEEE...........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'frame', role: 'body' },
        C: { name: 'base_foot', role: 'arm' },
        D: { name: 'open_book', role: 'eye' },
        E: { name: 'base_plate', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. LIBRARY SHELF ──────────────────────────────────────────
    {
      id: 'library_shelf_32',
      description: 'Small bookshelf with three rows of varied colored books in red, blue, and brown covers.',
      size: 32,
      grid: [
        '................................',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AABCDBCDBCDBCDBBCDBCDBCDAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AADBCBDCBDBCDBDBCBDCBDBCAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AACDBCDBCDBCDBBCDBCDBCDAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAA...',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'shelf_frame', role: 'body' },
        B: { name: 'books_red', role: 'head' },
        C: { name: 'books_blue', role: 'arm' },
        D: { name: 'books_brown', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. PRAYER BOOK ───────────────────────────────────────────
    {
      id: 'prayer_book_32',
      description: 'Small ornate prayer book with rich red cover, gold cross emblem, parchment pages, and metal clasp.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '......AAAAAAAAAAAAAAAAAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAADDDDAAAAAADAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAADDDDDDDDDDDDAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAADDDDAAAAAADAAA........',
        '.....AAAAAADAAAAAAAADAAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAAAAAAAAAAAAAAEAAAA.......',
        '.....BBBBBBBBBBBBBBBBBBBB.......',
        '.....BBBBBBBBBBBBBBBBBBBB.......',
        '.....CCCCCCCCCCCCCCCCCCCC.......',
        '.....CCCCCCCCCCCCCCCCCCCC.......',
        '.....CCCCCCCCCCCCCCCCCCCC.......',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'cover', role: 'body' },
        B: { name: 'page_edges', role: 'head' },
        C: { name: 'pages', role: 'arm' },
        D: { name: 'cross_emblem', role: 'eye' },
        E: { name: 'clasp', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  MIXED SCHOLARLY (10 templates)
    // ═══════════════════════════════════════════════════════════════

    // ─── 11. ROSARY BEADS ──────────────────────────────────────────
    {
      id: 'rosary_beads_32',
      description: 'String of rosary prayer beads in circular arrangement with gold cross pendant at bottom.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........AAAAAAAAA.............',
        '.........AA.......AA............',
        '........AA.........AA...........',
        '.......AA...........AA..........',
        '......DA.............AD.........',
        '.....DA...............AD........',
        '.....AA...............AA........',
        '....DA.................AD.......',
        '....AA.................AA.......',
        '....DA.................AD.......',
        '....AA.................AA.......',
        '....DA.................AD.......',
        '.....AA...............AA........',
        '.....DA...............AD........',
        '......DA.............AD.........',
        '.......AA...........AA..........',
        '........AA.........AA...........',
        '.........AA.......AA............',
        '..........AADDDAAA..............',
        '.............DDD................',
        '............BBBBB...............',
        '............BB.BB...............',
        '...........BBBBBBB..............',
        '............BB.BB...............',
        '............BBBBB...............',
        '.............BBB................',
        '..............B.................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'beads', role: 'body' },
        B: { name: 'cross', role: 'head' },
        D: { name: 'large_beads', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 12. SAND TIMER ────────────────────────────────────────────
    {
      id: 'sand_timer_32',
      description: 'Desk sand timer hourglass with wooden frame, blue glass bulbs, and golden sand inside.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.......AAAAAAAAAAAAAAAA.........',
        '.......AAAAAAAAAAAAAAAA.........',
        '........BBBBBBBBBBBBBB..........',
        '........BBDDDDDDDDDDBB.........',
        '.........BBDDDDDDDDBB..........',
        '.........BBDDDDDDDDBB..........',
        '..........BBDDDDDDBB...........',
        '..........BBDDDDDDBB...........',
        '...........BBDDDDBB............',
        '...........BBDDDDBB............',
        '............BBDDBB.............',
        '............BBDDBB.............',
        '.............BBBB...............',
        '.............BBBB...............',
        '............BBDDBB.............',
        '............BBDDBB.............',
        '...........BBDDDDBB............',
        '...........BBDDDDBB............',
        '..........BBBBDDDDBB...........',
        '..........BBBBBBBBBB...........',
        '.........BBBBBBBBBBBB..........',
        '.........BBBBBBBBBBBB..........',
        '........BBBBBBBBBBBBBB..........',
        '........BBBBBBBBBBBBBB..........',
        '.......AAAAAAAAAAAAAAAA.........',
        '.......AAAAAAAAAAAAAAAA.........',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'frame_caps', role: 'body' },
        B: { name: 'glass_bulbs', role: 'head' },
        D: { name: 'sand', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. MAGNIFYING LENS ───────────────────────────────────────
    {
      id: 'magnifying_lens_32',
      description: 'Hand magnifying glass with round blue lens, gold frame ring, and turned wooden handle.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........BBBBBBBBB.............',
        '.........BBBBBBBBBBB............',
        '........BBBAAAAAABBBB...........',
        '.......BBBAAAAAAAAABBB..........',
        '.......BBAAAAAAAAAAABB..........',
        '......BBAADAAAAAADAABB..........',
        '......BBAAAAAAAAAAAABB..........',
        '......BBAAAAAAAAAAAABB..........',
        '......BBAAAAAAAADAAABB..........',
        '.......BBAAAAAAAAAABB...........',
        '.......BBBAAAAAABBBB............',
        '........BBBAAABBBBBB............',
        '.........BBBBBBBBB..............',
        '..........BBBBBBB...............',
        '............CCCC................',
        '............CCCC................',
        '.............CCC................',
        '.............CCC................',
        '.............CCC................',
        '.............CCC................',
        '.............CCC................',
        '..............CC................',
        '..............CC................',
        '..............CC................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'lens', role: 'body' },
        B: { name: 'frame_ring', role: 'head' },
        C: { name: 'handle', role: 'arm' },
        D: { name: 'reflection', role: 'eye' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. GLOBE STAND ───────────────────────────────────────────
    {
      id: 'globe_stand_32',
      description: 'Earth globe on ornate stand with visible continents, gold meridian ring, and sturdy base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..........DDDDDDDD.............',
        '.........DAAAAAAAAAD............',
        '........DAAAAAAAAAAADD..........',
        '.......DAAABBAAABBAAAD..........',
        '......DAABBBBAABBBBAAAD.........',
        '......DAAABBAAABBAAAAD..........',
        '.....DAAAAAAAAAAABAAAD..........',
        '.....DAAABBAAABBBAAAAD..........',
        '.....DAAABBBAABBBAAAAD..........',
        '......DAAABBAAABBAAAD...........',
        '......DAAAAAAAAAAAAADD..........',
        '.......DAAABBAAABBAAAD..........',
        '........DAAAAAAAAAAADD..........',
        '.........DAAAAAAAAAD............',
        '..........DDDDDDDD.............',
        '..............CC................',
        '..............CC................',
        '.............CCCC...............',
        '.............CCCC...............',
        '..............CC................',
        '..............CC................',
        '.............EEEE...............',
        '............EEEEEE..............',
        '...........EEEEEEEE.............',
        '..........EEEEEEEEEE............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'ocean', role: 'body' },
        B: { name: 'land', role: 'head' },
        C: { name: 'meridian', role: 'arm' },
        D: { name: 'globe_ring', role: 'eye' },
        E: { name: 'stand', role: 'belt' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 15. ALCHEMIST FLASK ───────────────────────────────────────
    {
      id: 'alchemist_flask_32',
      description: 'Round-bottom alchemist flask with green liquid, cork stopper, iron ring stand, and bubbles.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '.............CCC................',
        '.............CCC................',
        '............BBBBB...............',
        '............BBBBB...............',
        '...........BBBBBBB..............',
        '..........BBBBBBBBB.............',
        '.........BBBBBBBBBBB............',
        '........BBBAAAABABBBB...........',
        '.......BBBAAAAAAEABBBB..........',
        '......BBBAAAAAAAAAABBBB.........',
        '......BBAAAAAAAAAAAAAABB........',
        '.....BBBAAAAAEAAAAAAAABB........',
        '.....BBAAAAAAAAAAAAAABBB.......',
        '.....BBAAAAAAAAAAAAAAABB........',
        '.....BBAAAAAAAAAAAAAAABB........',
        '......BBAAAAAAAAAAAAAABB........',
        '......BBBAAAAAAAAAAABBBB........',
        '.......BBBBAAAAABBBBBB..........',
        '........BBBBBBBBBBBBB...........',
        '.........DDDDDDDDDDD...........',
        '........DD...........DD.........',
        '.......DD.............DD........',
        '......DD...............DD.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'liquid', role: 'body' },
        B: { name: 'glass', role: 'head' },
        C: { name: 'cork', role: 'arm' },
        D: { name: 'stand', role: 'eye' },
        E: { name: 'bubbles', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 16. CANDELABRA ────────────────────────────────────────────
    {
      id: 'candelabra_32',
      description: 'Three-armed candelabra with tall candles, dripping wax, golden flames, and steel base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.......BB.....BB.....BB.........',
        '......BBBB...BBBB...BBBB.......',
        '......CCCC...CCCC...CCCC.......',
        '......CCCC...CCCC...CCCC.......',
        '......CDCC...CDCC...CDCC.......',
        '......CCCC...CCCC...CCCC.......',
        '......CCCC...CCCC...CCCC.......',
        '......CCCC...CCCC...CCCC.......',
        '......CCCC...CCCC...CCCC.......',
        '......CDCC...CDCC...CDCC.......',
        '.......AAA...AAAA...AAA........',
        '........AAAAAAAAAAAAA...........',
        '.........AAAAAAAAAAA............',
        '..........AAAAAAAAA.............',
        '...........AAAAAAA..............',
        '............AAAAA...............',
        '............AAAAA...............',
        '............AAAAA...............',
        '...........AAAAAAA..............',
        '..........AAAAAAAAA.............',
        '.........EEEEEEEEEEE............',
        '........EEEEEEEEEEEEE...........',
        '.......EEEEEEEEEEEEEEE..........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'arms_stem', role: 'body' },
        B: { name: 'flames', role: 'head' },
        C: { name: 'candles', role: 'arm' },
        D: { name: 'wax_drips', role: 'eye' },
        E: { name: 'base', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 17. DESK BELL ─────────────────────────────────────────────
    {
      id: 'desk_bell_32',
      description: 'Small service desk bell with polished brass dome, wooden knob handle, and highlight shine.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..............BB................',
        '.............BBBB...............',
        '.............BBBB...............',
        '..............CC................',
        '.............CCCC...............',
        '............AAAAAA..............',
        '...........AAAAAAAA.............',
        '..........AADAAAAAAA............',
        '.........AADDAAAAAAAAA..........',
        '........AADDAAAAAAAAAA..........',
        '.......AADDDAAAAAAAAAAA.........',
        '......AADDDAAAAAAAAAAAA.........',
        '.....AADDDDDAAAAAAAAAAAAA.......',
        '....AADDDDDDAAAAAAAAAAAAAA......',
        '...AADDDDDDDAAAAAAAAAAAAAAA....',
        '..AADDDDDDDDAAAAAAAAAAAAAAAA...',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..',
        '..AAAAAAAAAAAAAAAAAAAAAAAAAAAA..',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'bell_body', role: 'body' },
        B: { name: 'handle', role: 'head' },
        C: { name: 'stem', role: 'arm' },
        D: { name: 'shine', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. PARCHMENT ROLL ────────────────────────────────────────
    {
      id: 'parchment_roll_32',
      description: 'Decorative parchment scroll rolled horizontally with wooden rollers, red wax seal, and ink text.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '....BBBB................BBBB....',
        '....BBBB................BBBB....',
        '...BBBBB................BBBBB...',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBAAEEEAAAEEEAAAEEEAAABB....',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBAAEEEAAAEEEAAAEEEAAABB....',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBAAEEEAAAEEEAAAEEEAAABB....',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBAAEEEAAAEEEAAADDDAABB.....',
        '...BBAAAAAAAAAAADDDDDDAABB.....',
        '...BBAAAAAAAAAAADDDDDDAABB.....',
        '...BBAAAAAAAAAAAAAAAAAAAAABB....',
        '...BBBBB................BBBBB...',
        '....BBBB................BBBB....',
        '....BBBB................BBBB....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'parchment', role: 'body' },
        B: { name: 'rollers', role: 'head' },
        D: { name: 'wax_seal', role: 'arm' },
        E: { name: 'ink_text', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 19. SCHOLAR'S HAT ─────────────────────────────────────────
    {
      id: 'scholars_hat_32',
      description: 'Medieval scholar biretta cap with square top, red band accent, gold tassel, and dark fabric.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..........BBBB..................',
        '.........BBBBB..................',
        '........BBBBBB..................',
        '.......AAAAAAAAAAAAAAAAAA.......',
        '......AAAAAAAAAAAAAAAAAAAA......',
        '......AAAAAAAAAAAAAAAAAAAA......',
        '.....AAAAAAAAAAAAAAAAAAAAAA.....',
        '.....AAAAAAAAAAAAAAAAAAAAAA.....',
        '......AAAAAAAAAAAAAAAAAAAAA.....',
        '......AAAAAAAAAAAAAAAAAAAA......',
        '.......AAAAAAAAAAAAAAAAAAA......',
        '........CCCCCCCCCCCCCCCC........',
        '........CCCCCCCCCCCCCCCC........',
        '.......AAAAAAAAAAAAAAAAAAA......',
        '......AAAAAAAAAAAAAAAAAAAA......',
        '.....AAAAAAAAAAAAAAAAAAAAAA.....',
        '.....AAAAAAAAAAAAAAAAAAAAAA.....',
        '......AAAAAAAAAAAAAAAAAAAA......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'cap_body', role: 'body' },
        B: { name: 'tassel', role: 'head' },
        C: { name: 'band', role: 'arm' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 20. UNIVERSITY SEAL ───────────────────────────────────────
    {
      id: 'university_seal_32',
      description: 'Official university wax seal medallion with gold outer ring, blue inner field, parchment shield, and ribbon.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..........AAAAAAAAA.............',
        '.........AAAAAAAAAAA............',
        '........AAAAAAAAAAAAA...........',
        '.......AAABBBBBBBBBAAAA.........',
        '......AAABBBBBBBBBBBAAAA........',
        '.....AAABBBBBBBBBBBBAAAAA.......',
        '.....AABBBBBBCCCBBBBBAAA........',
        '....AAABBBBBCCCCCBBBBAAAA.......',
        '....AABBBBBBCCCCCBBBBAAA........',
        '....AABBBBCCCCCCCBBBBAAA........',
        '....AABBBBCCCCCCCBBBBAAA........',
        '....AABBBBCCCCCCCBBBBAAA........',
        '....AABBBBBCCCCCCBBBBAAAA.......',
        '....AAABBBBBCCCCCBBBBAAAA.......',
        '.....AABBBBBBCCCBBBBBAAA........',
        '.....AAABBBBBBBBBBBBAAAAA.......',
        '......AAABBBBBBBBBBBAAAA........',
        '.......AAABBBBBBBBBAAAA.........',
        '........AAAAAAAAAAAAA...........',
        '.........AAAAAAAAAAA............',
        '..........AAAAAAAAA.............',
        '...........EEEEEEE..............',
        '..........EE.....EE.............',
        '.........EE.......EE............',
        '........EE.........EE...........',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'outer_ring', role: 'body' },
        B: { name: 'inner_field', role: 'head' },
        C: { name: 'shield_emblem', role: 'arm' },
        E: { name: 'ribbon', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
