/**
 * Medieval Scholar's Collection — 32x32 Batch 1: Grammar (14) + Logic (6) = 20 templates.
 * Neo-SNES style (Chrono Trigger + Sea of Stars quality).
 * All 32x32, DB16 palette only, colored selout, 4-8 roles per template.
 *
 * Row format: every row is exactly 32 characters.
 * '.' = transparent, letter = role pixel.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_32_BATCH1_TEMPLATES', schemes: 'LIBERAL_ARTS_32_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    // GRAMMAR — Writing Tools, Books, Manuscripts (14)
    // ═══════════════════════════════════════════════════════════════

    // ─── 1. QUILL PEN — large feathered quill at 45° ────────────
    {
      id: 'quill_pen_32',
      description: 'Large feathered quill pen at 45-degree angle with inked nib and visible barbs.',
      size: 32,
      grid: [
        //01234567890123456789012345678901
        '................................', // 0
        '...................FFFFF........', // 1
        '..................FFFFFF........', // 2
        '.................FFFFFFF........', // 3
        '................FFFFFFBB........', // 4
        '...............FFFFFBBB.........',
        '..............FFFFBBB...........',
        '.............FFFFBB.............', // 7
        '............FFFBB...............',
        '...........FFFBB................',
        '..........FFBB..................',
        '.........FFBB...................', // 11
        '........FBBB....................',
        '.......SSBB.....................', // 13
        '......SSSB......................',
        '.....SSSS.......................',
        '....SSSS........................',
        '...SSSS.........................', // 17
        '...SSNN.........................',
        '..SSNNN.........................',
        '..NNNN..........................',
        '.NNNN...........................', // 21
        '.NNN............................',
        '.NII............................',
        '.III............................',
        '.II.............................', // 25
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'feather_vane', role: 'body' },
        B: { name: 'barb_detail', role: 'accessory' },
        S: { name: 'shaft', role: 'head' },
        N: { name: 'nib', role: 'arm' },
        I: { name: 'ink_tip', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. INKWELL — round ceramic inkwell with quill ──────────
    {
      id: 'inkwell_32',
      description: 'Round ceramic inkwell with quill resting diagonally inside and ink surface visible.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '..............PP................',
        '.............PPP................',
        '............PPP.................',
        '...........PPP..................',
        '..........PPP...................',
        '.........PPP....................',
        '........PPP.....................',
        '.......PPR......................',
        '........RRRRRRRRRRR.............',
        '.......RRRRRRRRRRRRRR...........',
        '......RRRIIIIIIIIIRRR...........',
        '.....RRRIIIIIIIIIIIRRRR.........',
        '.....RRRIIIIIIIIIIIRRRR.........',
        '.....RRRIIIIIIIIIIIRRRR.........',
        '.....RRRIIIIIIIIIIIRRRR.........',
        '......RRRIIIIIIIIIRRR...........',
        '.......RRRRRRRRRRRRRR...........',
        '........RRRRRRRRRRR.............',
        '.........BBBBBBBBB..............',
        '..........BBBBBBB...............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        P: { name: 'quill_handle', role: 'accessory' },
        R: { name: 'pot_rim', role: 'head' },
        I: { name: 'ink_surface', role: 'eye' },
        B: { name: 'pot_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 3. OPEN CODEX — butterfly-open leather book ────────────
    {
      id: 'open_codex_32',
      description: 'Open leather-bound codex lying flat in butterfly shape with visible text on both pages.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPP.PP.PPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPP.PP.PPCC......',
        '.CCPP.PPP.PPPSSPP.PPPP.PCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPP.PPPPPPPSSPPPP.PPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPP..PP.PPPSSP.PP.PPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPP.PPPPPPSSP.PPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSPPPPPPPPPCC......',
        '.CCPPPPPPPPPPSSGGGPPPPPGCC......',
        '.CCCCCCCCCCCCCCCCCCCCCCCCC......',
        '.CCCCCCCCCCCCCCCCCCCCCCCCC......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        C: { name: 'cover', role: 'body' },
        P: { name: 'pages', role: 'head' },
        S: { name: 'spine', role: 'belt' },
        G: { name: 'gold_clasp', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. ROLLED SCROLL — tightly rolled parchment ────────────
    {
      id: 'rolled_scroll_32',
      description: 'Tightly rolled parchment scroll with wooden rollers and gold knobs.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KPPPPPPPWWWPPPPPPPPPPPPK......',
        '..KPPPPPPPWWWPPPPPPPPPPPPK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KPPPPPPPPPPPPPPPPPPPPPPK......',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '..KRRRRRRRRRRRRRRRRRRRRRRK......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        R: { name: 'rollers', role: 'arm' },
        K: { name: 'knobs', role: 'belt' },
        P: { name: 'parchment', role: 'body' },
        W: { name: 'wax_seal', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 5. UNFURLED SCROLL — partially unrolled with text ──────
    {
      id: 'unfurled_scroll_32',
      description: 'Partially unrolled scroll with visible text lines and a wax seal near the bottom.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '....KRRRRRRRRRRRRRRRRRRK........',
        '....KRRRRRRRRRRRRRRRRRRK........',
        '....KPPPPPPPPPPPPPPPPPPK........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP.PPP.PPPPPPPPPPP..........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP.PP.PPPPPPPPPPPP..........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP..PPP.PPPPPPPPPP..........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP.PPPP.PPPPPPPPP...........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP.PP..PPPPPPPPPPPP.........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PP..PP.PPPPPPPPPPP..........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....PPPPPPPPPPPPWWWPPPP.........',
        '....PPPPPPPPPPPPWWWPPPP.........',
        '....PPPPPPPPPPPPWWWPPPP.........',
        '....PPPPPPPPPPPPPPPPPPPP........',
        '....KPPPPPPPPPPPPPPPPPPK........',
        '....KRRRRRRRRRRRRRRRRRRK........',
        '....KRRRRRRRRRRRRRRRRRRK........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        R: { name: 'rollers', role: 'arm' },
        K: { name: 'knobs', role: 'belt' },
        P: { name: 'parchment', role: 'body' },
        W: { name: 'wax_seal', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 6. WAX TABLET — hinged wooden writing tablet ───────────
    {
      id: 'wax_tablet_32',
      description: 'Hinged wooden writing tablet with wax surface and etched stylus marks.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '...FFFFFFFFFFFFFFFFFFFFFFFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWW.WWW.WWWWWWWWWWWWFF......',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWW.WW.WWWWWWWWWWWWWFF......',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWW..WWW.WWWWWWWWWWWFF......',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFFFFFFFFFFFFFFFFFFFFFFF.....',
        '...HHH..................HHH.....',
        '...HHH..................HHH.....',
        '...FFFFFFFFFFFFFFFFFFFFFFFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFWWWWWWWWWWWWWWWWWWWWFF.....',
        '...FFFFFFFFFFFFFFFFFFFFFFFF.....',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        W: { name: 'wax_surface', role: 'head' },
        H: { name: 'hinge', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. ILLUMINATED LETTER — ornate capital on parchment ────
    {
      id: 'illuminated_letter_32',
      description: 'Ornate illuminated capital letter on parchment with vine border and gold leaf.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..GGPPPPPPPPPPPPPPPPPPPPGG......',
        '..GPPPPPPPPPPPPPPPPPPPPPPG......',
        '..GPVVVVPPPPPPPPPPPPPPPPPG......',
        '..GPVV.VVPPPPPPPPPPPPPPPPG......',
        '..GPV...VVPPPPPPPPPPPPPPNG......',
        '..GPVVVVVVPPPPPPPPPPPPPPNG......',
        '..GPV..VVVPPP.PPP.PPPPPPPG......',
        '..GPV...VVPPPPPPPPPPPPPPNG......',
        '..GPV...VVPPPPPPPPPPPPPPNG......',
        '..GPPPPPPPPPPP.PP.PPPPPPPPG.....',
        '..GPPPPPPPPPPPPPPPPPPPPPPGG.....',
        '..GPPPPPPPPPPP.PPP.PPPPPPPG.....',
        '..GPPPPPPPPPPPPPPPPPPPPPPPG.....',
        '..GPPPPPPPPPPP.PP..PPPPPPGG.....',
        '..GPPPPPPPPPPPPPPPPPPPPPPGG.....',
        '..GPPPPPPPPPPP.PPP.PPPPPPPG.....',
        '..GPPPPPPPPPPPPPPPPPPPPPPGG.....',
        '..GPPPPPPPPPPPP.PP.PPPPPPPG.....',
        '..GPPPPPPPPPPPPPPPPPPPPPPGG.....',
        '..GPPPPPPPPPPPPPPPPPPPVVPPG.....',
        '..GPPPPPPPPPPPPPPPPPPVVVPPG.....',
        '..GGPPPPPPPPPPPPPPPPPPPPPPGG....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        P: { name: 'parchment', role: 'head' },
        V: { name: 'letter_body', role: 'body' },
        G: { name: 'gold_border', role: 'accessory' },
        N: { name: 'vine_detail', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. SCRIBAL DESK — angled lectern with open book ────────
    {
      id: 'scribal_desk_32',
      description: 'Angled scribe lectern desk with open book resting on slanted surface.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '....BBBBBRRRRRRRRR..............',
        '....BBBBBRRRRRRRRR..............',
        '.....BBBBBRRRRRRRRR.............',
        '.....BBBBBRRRRRRRRR.............',
        '......BBBBBRRRRRRRRR............',
        '......BBBBBRRRRRRRRR............',
        '.......BBBBBRRRRRRRR............',
        '.......BBBBBRRRRRRRR............',
        '........BBBBBRRRRRRR............',
        '........BBBBBRRRRRR.............',
        '.........BBBBBRRRRR.............',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '..........PPPP..................',
        '.......FFFFFFFFFFFF.............',
        '......FFFFFFFFFFFFFF............',
        '......FFFFFFFFFFFFFF............',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        B: { name: 'book_cover', role: 'accessory' },
        R: { name: 'book_pages', role: 'head' },
        P: { name: 'post', role: 'body' },
        F: { name: 'base_foot', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. BOOK STACK — 4 books stacked ────────────────────────
    {
      id: 'book_stack_32',
      description: 'Stack of 4 books of different sizes and colors with visible page edges.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '.....AAPPPPPPPPPPPPPPPAA........',
        '.....AAAAAAAAAAAAAAAAAAA........',
        '....BBBBBBBBBBBBBBBBBBBBB.......',
        '....BBBBBBBBBBBBBBBBBBBBB.......',
        '....BBPPPPPPPPPPPPPPPPPBB.......',
        '....BBBBBBBBBBBBBBBBBBBBB.......',
        '....BBBBBBBBBBBBBBBBBBBBB.......',
        '.....CCCCCCCCCCCCCCCCCCC........',
        '.....CCCCCCCCCCCCCCCCCCC........',
        '.....CCPPPPPPPPPPPPPPPCC........',
        '.....CCCCCCCCCCCCCCCCCCC........',
        '....DDDDDDDDDDDDDDDDDDDDD.......',
        '....DDDDDDDDDDDDDDDDDDDDD.......',
        '....DDDDDDDDDDDDDDDDDDDDD.......',
        '....DDPPPPPPPPPPPPPPPPPDDDD.....',
        '....DDDDDDDDDDDDDDDDDDDDD.......',
        '....DDDDDDDDDDDDDDDDDDDDD.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        A: { name: 'book_red', role: 'body' },
        B: { name: 'book_blue', role: 'arm' },
        C: { name: 'book_brown', role: 'belt' },
        D: { name: 'book_green', role: 'accessory' },
        P: { name: 'page_edges', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 10. MANUSCRIPT PAGE — single decorated page ────────────
    {
      id: 'manuscript_page_32',
      description: 'Single decorated manuscript page with text lines, red initial, and curled corner.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPRRPPPPPPPPPPPPPPPPPP......',
        '....PPRRPPPPPPPPPPPPPPPPPP......',
        '....PPRRPP.PP.PPPPPPPPPPP.......',
        '....PPRRPPPPPPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPPP......',
        '....PPPP.PPP.PPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPP.PP.PPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPP..PP.PPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPP.PPP.PPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPP.PP..PPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPPPPP.......',
        '....PPPPPPPPPPPPPPPPPCCPP.......',
        '....PPPPPPPPPPPPPPPPCCPPP.......',
        '....PPPPPPPPPPPPPPPPCCCC........',
        '....PPPPPPPPPPPPPPPPPCCCC.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        P: { name: 'parchment', role: 'body' },
        R: { name: 'red_initial', role: 'eye' },
        C: { name: 'curl_shadow', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 11. INK POT SET — ink pot with pen holder and bottles ──
    {
      id: 'ink_pot_set_32',
      description: 'Writing desk set with main ink pot, pen holder, and two small ink bottles.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '........HHHH....................',
        '........HHHH....................',
        '.......HHHHHH...................',
        '......EEEEEEEE...SSSS..SSSS.....',
        '......EEEEEEEE..SSSSSS.SSSSS....',
        '.....EEEIIIIEEE.SSMMSS.SSMMSS...',
        '.....EEEIIIIEEE.SSMMSS.SSMMSS...',
        '.....EEEIIIIEEE.SSMMSS.SSMMSS...',
        '.....EEEIIIIEEE.SSSSSS.SSSSS....',
        '......EEEEEEEE...SSSS..SSSS.....',
        '......EEEEEEEE..................',
        '.......BBBBBBB..................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        H: { name: 'pen_holder', role: 'head' },
        E: { name: 'main_pot', role: 'body' },
        I: { name: 'ink_surface', role: 'eye' },
        S: { name: 'small_bottle', role: 'arm' },
        M: { name: 'bottle_ink', role: 'belt' },
        B: { name: 'base_tray', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. LEATHER JOURNAL — thick journal with strap ─────────
    {
      id: 'leather_journal_32',
      description: 'Thick leather-bound journal with strap closure and gold buckle, standing upright.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCAAACCCC.........',
        '.....SSCCCCCCCCCAAACCCC.........',
        '.....SSCCCCCCCCCAAACCCC.........',
        '.....SSCCCCCCCCCCCCCCCCAAA......',
        '.....SSCCCCCCCCCCCCCCCCAAA......',
        '.....SSCCCCCCCCCCCCCCCBBBA......',
        '.....SSCCCCCCCCCCCCCCCCAAA......',
        '.....SSCCCCCCCCCCCCCCCCAAA......',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSPPPPPPPPPPPPPPPP.........',
        '.....SSPPPPPPPPPPPPPPPP.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '.....SSCCCCCCCCCCCCCCCC.........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        S: { name: 'spine', role: 'belt' },
        C: { name: 'cover', role: 'body' },
        P: { name: 'page_edge', role: 'head' },
        A: { name: 'strap', role: 'arm' },
        B: { name: 'buckle', role: 'eye' },
      },
      colors: {
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. CALLIGRAPHY BRUSH — East-Asian calligraphy brush ───
    {
      id: 'calligraphy_brush_32',
      description: 'East-Asian style calligraphy brush with bamboo handle, brass ferrule, and ink-loaded bristles.',
      size: 32,
      grid: [
        '................................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '..............HH................',
        '.............FFFF...............',
        '.............FFFF...............',
        '.............FFFF...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '..............BB................',
        '..............BB................',
        '..............BB................',
        '..............BB................',
        '..............BB................',
        '..............II................',
        '..............II................',
        '.............IIII...............',
        '..............II................',
        '................................',
        '................................',
      ],
      chars: {
        H: { name: 'handle', role: 'body' },
        F: { name: 'ferrule', role: 'accessory' },
        B: { name: 'bristles', role: 'head' },
        I: { name: 'ink_tip', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // ─── 14. GRAMMAR ROD — teacher's pointing rod/staff ─────────
    {
      id: 'grammar_rod_32',
      description: 'Grammar teacher pointing rod with ornate gold tip, dark cloth grip, and gold ring.',
      size: 32,
      grid: [
        '................................',
        '..........................TT....',
        '.........................TTT....',
        '........................TTT.....',
        '.......................SSS......',
        '......................SSS.......',
        '.....................SSS........',
        '....................SSS.........',
        '...................SSS..........',
        '..................SSS...........',
        '.................SSS............',
        '................SSS.............',
        '...............SSS..............',
        '..............SSS...............',
        '.............SSS................',
        '............RRR.................',
        '...........GGG..................',
        '..........GGG...................',
        '.........GGG....................',
        '........GGG.....................',
        '.......GGG......................',
        '......GGG.......................',
        '.....GGG........................',
        '....RRR.........................',
        '...SSS..........................',
        '..SSS...........................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        T: { name: 'tip', role: 'head' },
        S: { name: 'shaft', role: 'body' },
        G: { name: 'grip', role: 'arm' },
        R: { name: 'ring', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    // LOGIC — Reasoning & Wisdom Symbols (6)
    // ═══════════════════════════════════════════════════════════════

    // ─── 15. LOGIC WHEEL — circular pattern wheel ───────────────
    {
      id: 'logic_wheel_32',
      description: 'Large circular wheel of logical categories with quadrants and cross spokes.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '.........RRRRRRRRRRRRRR.........',
        '.......RRRRRRRRRRRRRRRRRR.......',
        '......RRRRRRRRRRRRRRRRRRRR......',
        '.....RRRRBBBBBSSBBBBBRRRR.......',
        '....RRRRBBBBBBSSBBBBBBRRRRR.....',
        '....RRRBBBBBBBBSSBBBBBBBRRRR....',
        '....RRRBBBBBBBSSSBBBBBBBRRRR....',
        '....RRBBBBBBBBBSSSBBBBBBBRRR....',
        '....RRSSSSSSSSSGGSSSSSSSSSRR....',
        '....RRSSSSSSSSSGGSSSSSSSSSRR....',
        '....RRBBBBBBBBBSSSBBBBBBBRRR....',
        '....RRRBBBBBBBSSSBBBBBBBRRRR....',
        '....RRRBBBBBBBBSSBBBBBBBRRRR....',
        '....RRRRBBBBBBSSBBBBBBRRRRR.....',
        '.....RRRRBBBBBSSBBBBBRRRR.......',
        '......RRRRRRRRRRRRRRRRRRRR......',
        '.......RRRRRRRRRRRRRRRRRR.......',
        '.........RRRRRRRRRRRRRR.........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        R: { name: 'outer_ring', role: 'body' },
        B: { name: 'quadrants', role: 'head' },
        S: { name: 'cross_spokes', role: 'arm' },
        G: { name: 'center_hub', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 16. BALANCE SCALES — two-pan balance scale ─────────────
    {
      id: 'balance_scales_32',
      description: 'Full two-pan balance scale with chains, pans, wooden post, and decorative pivot.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '.............GGGG...............',
        '............GGGGGG..............',
        '............GGGGGG..............',
        '..CCCCCCCCCCCPPCCCCCCCCCCCC.....',
        '...CCC.......PP.......CCC.......',
        '....CCC......PP......CCC........',
        '....CCC......PP......CCC........',
        '.....CCC.....PP.....CCC.........',
        '.....CCC.....PP.....CCC.........',
        '..CCCCCCCC...PP...CCCCCCCC......',
        '..BBBBBBBB...PP...BBBBBBBB......',
        '..BBBBBBBBB..PP..BBBBBBBBB......',
        '..BBBBBBBB...PP...BBBBBBBB......',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '.............PP.................',
        '..........FFFFFFFF..............',
        '.........FFFFFFFFFF.............',
        '........FFFFFFFFFFFF............',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        G: { name: 'crown_pivot', role: 'eye' },
        C: { name: 'chains_beam', role: 'arm' },
        P: { name: 'post', role: 'body' },
        B: { name: 'pans', role: 'head' },
        F: { name: 'base', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. CHESS KING — ornate chess piece ────────────────────
    {
      id: 'chess_piece_32',
      description: 'Ornate chess king piece with cross top, crown, and wide base.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '..............CC................',
        '.............CCCC...............',
        '..............CC................',
        '............GGGGGG..............',
        '...........GGGGGGGG.............',
        '..........GGGGGGGGGG............',
        '..........GGGGGGGGGG............',
        '...........GGGGGGGG.............',
        '............BBBBBB..............',
        '...........BBBBBBBB.............',
        '............BBBBBB..............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '.............BBBB...............',
        '............BBBBBB..............',
        '...........BBBBBBBB.............',
        '..........BBBBBBBBBB............',
        '.........BBBBBBBBBBBB...........',
        '........FFFFFFFFFFFFFF..........',
        '........FFFFFFFFFFFFFF..........',
        '.......FFFFFFFFFFFFFFFR.........',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        C: { name: 'cross_top', role: 'eye' },
        G: { name: 'crown', role: 'accessory' },
        B: { name: 'piece_body', role: 'head' },
        F: { name: 'base', role: 'body' },
        R: { name: 'base_shadow', role: 'body', tone: 'shadow' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 18. PUZZLE BOX — ornate interlocking puzzle box ────────
    {
      id: 'puzzle_box_32',
      description: 'Ornate interlocking puzzle box with gold inlay pattern and a blue gem.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '......LLLLLLLLLLLLLLLLLL........',
        '......LLLLLLLLLLLLLLLLLL........',
        '......LLLLLLLLLLLLLLLLLL........',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....WWGGWWWWWWWWWWWWGGWWWW......',
        '....WWWWGGWWWWWWWWGGWWWWWW......',
        '....WWWWWWGGWWWWGGWWWWWWWW......',
        '....WWWWWWWWGBBGWWWWWWWWWW......',
        '....WWWWWWWWGBBGWWWWWWWWWW......',
        '....WWWWWWGGWWWWGGWWWWWWWW......',
        '....WWWWGGWWWWWWWWGGWWWWWW......',
        '....WWGGWWWWWWWWWWWWGGWWWW......',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....WWWWWWWWWWWWWWWWWWWWWW......',
        '....FFFFFFFFFFFFFFFFFFFFF.......',
        '....FFFFFFFFFFFFFFFFFFFFF.......',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        W: { name: 'box_body', role: 'body' },
        G: { name: 'inlay_pattern', role: 'head' },
        B: { name: 'gem', role: 'eye' },
        L: { name: 'lid', role: 'arm' },
        F: { name: 'base_trim', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. SYLLOGISM TABLET — stone tablet with inscriptions ──
    {
      id: 'syllogism_tablet_32',
      description: 'Stone tablet with carved logical inscriptions, steel frame, and wax seal.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTT.TTT.TTTTTTTTTTTFF......',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTT.TT.TTTTTTTTTTTTFF......',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTT..TTT.TTTTTTTTTTFF......',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTT.TTTT.TTTTTTTTTTTFF.....',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTT.TT..TTTTTTTTTTTTFF.....',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFTTTTTTTTTTTWWWTTTTFF......',
        '....FFTTTTTTTTTTTWWWTTTTFF......',
        '....FFTTTTTTTTTTTWWWTTTTFF......',
        '....FFTTTTTTTTTTTTTTTTTTTFF.....',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'frame', role: 'arm' },
        T: { name: 'tablet_stone', role: 'body' },
        W: { name: 'wax_seal', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 20. HOURGLASS — wood-framed hourglass with golden sand ─
    {
      id: 'hourglass_logic_32',
      description: 'Elegant wood-framed hourglass with golden sand flowing through glass bulbs.',
      size: 32,
      grid: [
        '................................',
        '................................',
        '................................',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '.....FFGGGGGGGGGGGGGGGGGGFF.....',
        '.....FFGGGGGGGGGGGGGGGGGGFF.....',
        '......FFGGGGGGSSSGGGGGGFF.......',
        '.......FFGGGGGSSSGGGGFF.........',
        '........FFGGGGSSSGGFF...........',
        '.........FFGGGSSSGGFF...........',
        '..........FFGGSSSFF.............',
        '...........FFFSSFF..............',
        '...........FFFSSFF..............',
        '...........FFFSSFF..............',
        '...........FFFSSFF..............',
        '...........FFFSSFF..............',
        '...........FFFSSFF..............',
        '..........FFGGSSSFF.............',
        '.........FFGGGSSSGGFF...........',
        '........FFGGGGSSSGGFF...........',
        '.......FFGGGGSSSSSGGFF..........',
        '......FFGGGSSSSSSSGGGFF.........',
        '.....FFGGGSSSSSSSSSGGFF.........',
        '.....FFGGSSSSSSSSSSSGGFF........',
        '.....FFGGSSSSSSSSSSSGGFF........',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '....FFFFFFFFFFFFFFFFFFFFFFFF....',
        '................................',
        '................................',
        '................................',
        '................................',
      ],
      chars: {
        F: { name: 'frame_posts', role: 'body' },
        G: { name: 'glass_bulb', role: 'head' },
        S: { name: 'sand', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
