/**
 * Medieval Scholar's Collection — Batch 5: Music (5) + Astronomy (14) = 19 templates.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_BATCH5_TEMPLATES', schemes: 'LIBERAL_ARTS_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════════════════
    //  MUSIC (5 templates)
    // ═══════════════════════════════════════════════════════════════

    // ─── 1. RECORDER / SHAWM ────────────────────────────────────
    {
      id: 'recorder_shawm_16',
      description: 'Medieval recorder or shawm wind instrument with flared bell and finger holes.',
      grid: [
        '................',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '.......AC.......',
        '.......AA.......',
        '.......AC.......',
        '.......AA.......',
        '.......AC.......',
        '......AAAA......',
        '......ABBA......',
        '.....AABBAA.....',
        '.....ABBBBA.....',
        '....AABBBBAA....',
        '....ABBBBBBA....',
        '................',
      ],
      chars: {
        A: { name: 'tube', role: 'body' },
        B: { name: 'bell', role: 'head' },
        C: { name: 'holes', role: 'arm' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. MUSIC NOTATION ──────────────────────────────────────
    {
      id: 'music_notation_16',
      description: 'Medieval neume notation on parchment with 4-line staff and square note heads.',
      grid: [
        '................',
        '.AAAAAAAAAAAAAA.',
        '.AAAAAAAAAAAAAA.',
        '.ABBBBBBBBBBDBA.',
        '.AACCAACCAACCAA.',
        '.ABBBDBBBBBBDBA.',
        '.AACCAACCAACCAA.',
        '.ABBBBBBDBBBDBA.',
        '.AACCAACCAACCAA.',
        '.ABDBBBBBDBBDBA.',
        '.AACCAACCAACCAA.',
        '.ABBBBBDBBBBBBA.',
        '.AAAAAAAAAAAAAA.',
        '.AAAAAAAAAAAAAA.',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'parchment', role: 'body' },
        B: { name: 'staff_lines', role: 'head' },
        C: { name: 'notes', role: 'arm' },
        D: { name: 'clef_marks', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 3. TAMBOURINE ──────────────────────────────────────────
    {
      id: 'medieval_tambourine_16',
      description: 'Small tambourine frame drum with jingles and stretched drum head.',
      grid: [
        '................',
        '................',
        '.....AAAAAA.....',
        '....AAAAAAAA....',
        '...AABBBBBBAA...',
        '..AACBBBBBBCAA..',
        '..ABBBBBBBBBBA..',
        '..ABBBBBBBBBBA..',
        '..ABBBBBBBBBBA..',
        '..ABBBBBBBBBBA..',
        '..AACBBBBBBCAA..',
        '...AABBBBBBAA...',
        '....AAAAAAAA....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'frame', role: 'body' },
        B: { name: 'drum_head', role: 'head' },
        C: { name: 'jingles', role: 'arm' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. BAGPIPE ─────────────────────────────────────────────
    {
      id: 'bagpipe_16',
      description: 'Medieval bagpipe with leather bag, chanter pipe, drones, and blowpipe.',
      grid: [
        '......CC.CC.....',
        '......CC.CC.....',
        '......CC.CC.....',
        '..D...CC.CC.....',
        '..D..CCCCCC.....',
        '..D.AAAAAAAA....',
        '...AAAAAAAAAA...',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '...AAAAAAAAAA...',
        '....AAAAAAAA....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......BB.......',
      ],
      chars: {
        A: { name: 'bag', role: 'body' },
        B: { name: 'chanter', role: 'head' },
        C: { name: 'drones', role: 'arm' },
        D: { name: 'blowpipe', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. HERALD TRUMPET ──────────────────────────────────────
    {
      id: 'herald_trumpet_16',
      description: 'Long straight herald trumpet with hanging banner and flared bell.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        'DD.AAAAAAAAAA...',
        'DD.AAAAAAAAABBB.',
        '...AAAAAAAAABBB.',
        '...CCCCCC..BBB..',
        '...CCCCCC.......',
        '...CCCCCC.......',
        '...CCDDCC.......',
        '...CCCCCC.......',
        '...CCCCCC.......',
        '...CCCCCC.......',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'trumpet', role: 'body' },
        B: { name: 'bell', role: 'eye' },
        C: { name: 'banner', role: 'head' },
        D: { name: 'device', role: 'arm' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ═══════════════════════════════════════════════════════════════
    //  ASTRONOMY (14 templates)
    // ═══════════════════════════════════════════════════════════════

    // ─── 6. ASTROLABE ───────────────────────────────────────────
    {
      id: 'astrolabe_16',
      description: 'Handheld astrolabe astronomical calculator with rete pattern and throne ring.',
      grid: [
        '.......CC.......',
        '......CCCC......',
        '....AAAAAAAA....',
        '...AABBBBBBAA...',
        '..AABBBBBBBBAA..',
        '..ABBBDBBDBBBA..',
        '..ABBBBBBBBBBA..',
        '..AEEEEEEEEEEA..',
        '..ABBBBBBBBBBA..',
        '..ABDBBBBBDBBA..',
        '..AABBBBBBBBAA..',
        '...AABBBBBBAA...',
        '....AAAAAAAA....',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'mater', role: 'body' },
        B: { name: 'rete_face', role: 'head' },
        C: { name: 'throne_ring', role: 'arm' },
        D: { name: 'star_pointers', role: 'eye' },
        E: { name: 'rule_line', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 7. ARMILLARY SPHERE ────────────────────────────────────
    {
      id: 'armillary_sphere_16',
      description: 'Armillary sphere with nested tilted rings, central axis, and wooden stand.',
      grid: [
        '................',
        '.....AAAAAA.....',
        '....AB....BA....',
        '...AB.AAAA.BA...',
        '..AB.AB..BA.BA..',
        '..A.AB.DD.BA.A..',
        '..A.AB.DD.BA.A..',
        '..AB.AB..BA.BA..',
        '...AB.AAAA.BA...',
        '....AB....BA....',
        '.....AAAAAA.....',
        '.......BB.......',
        '......CCCC......',
        '.....CCCCCC.....',
        '....CC....CC....',
        '................',
      ],
      chars: {
        A: { name: 'rings', role: 'body' },
        B: { name: 'axis', role: 'head' },
        C: { name: 'stand', role: 'arm' },
        D: { name: 'earth', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 8. CELESTIAL GLOBE ─────────────────────────────────────
    {
      id: 'celestial_globe_16',
      description: 'Dark globe showing constellation stars on cradle stand.',
      grid: [
        '................',
        '................',
        '.....AAAAAA.....',
        '....AABAAABA....',
        '...AAADAAADAA...',
        '...AAAABAADAA...',
        '..AAADAAAAAABA..',
        '..AABAAADAADAA..',
        '..AAAAAABAAABA..',
        '...AADAAAAAAA...',
        '...AAAAADAAAA...',
        '....AABAAABA....',
        '.....CCCCCC.....',
        '......CCCC......',
        '.....CC..CC.....',
        '................',
      ],
      chars: {
        A: { name: 'globe', role: 'body' },
        B: { name: 'stars', role: 'head' },
        C: { name: 'stand', role: 'arm' },
        D: { name: 'lines', role: 'eye' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 9. TELESCOPE (EARLY) ───────────────────────────────────
    {
      id: 'telescope_early_16',
      description: 'Early refracting telescope with brass banding and wide objective end.',
      grid: [
        '................',
        '..C.............',
        '..AB............',
        '...ABB..........',
        '....ABBB........',
        '.....ABBB.......',
        '......ABBB......',
        '.......ABBB.....',
        '........ABBB....',
        '.........ABB....',
        '..........AB....',
        '...........AB...',
        '............CC..',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'tube', role: 'body' },
        B: { name: 'bands', role: 'head' },
        C: { name: 'lens', role: 'arm' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 10. CRESCENT MOON ──────────────────────────────────────
    {
      id: 'crescent_moon_16',
      description: 'Crescent moon with medieval face profile and surrounding glow.',
      grid: [
        '........D.......',
        '....CCAAAA......',
        '...CAAAAAAC.....',
        '..CAAAAAA.......',
        '..CAABAA........',
        '.CAAABAA........',
        '.CAAAAA.........',
        '.CAAAAAC........',
        '.CAAAAA.........',
        '.CAABAA.........',
        '..CAAAAA........',
        '..CAAAAAA..D....',
        '...CAAAAAAC.....',
        '....CCAAAA......',
        '.......D........',
        '................',
      ],
      chars: {
        A: { name: 'moon', role: 'body' },
        B: { name: 'face', role: 'head' },
        C: { name: 'glow', role: 'arm' },
        D: { name: 'stars', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 11. SUN FACE ───────────────────────────────────────────
    {
      id: 'sun_face_16',
      description: 'Medieval sun with face and alternating pointed rays radiating outward.',
      grid: [
        '.......B........',
        '..B...BBB...B...',
        '...B.BAAAB.B....',
        '....BAAAAAB.....',
        '...BAAAAAAAB....',
        '..BAACAACAAB....',
        '.BBAAAAAAAABB...',
        '.BBAAAAAAAA.BB..',
        '.BBAACAAAAA.BB..',
        '..BAAAAAAAAB....',
        '...BAAAAAAAB....',
        '....BAAAAAB.....',
        '...B.BAAAB.B....',
        '..B...BBB...B...',
        '.......B........',
        '................',
      ],
      chars: {
        A: { name: 'face', role: 'body' },
        B: { name: 'rays', role: 'head' },
        C: { name: 'features', role: 'arm' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. STAR CHART ─────────────────────────────────────────
    {
      id: 'star_chart_16',
      description: 'Circular star map planisphere with concentric grid and bright star dots.',
      grid: [
        '................',
        '.....DDDDDD.....',
        '...DDAAAAAADD...',
        '..DAABBAAABBAD..',
        '..DAABAABABAAD..',
        '.DABAAAAAAAABD..',
        '.DABABAABCABAD..',
        '.DAAAAAAAABAAD..',
        '.DABAABABAABAD..',
        '.DAAACAAAAABD...',
        '..DAABAABABAAD..',
        '..DAABBAAABBAD..',
        '...DDAAAAAADD...',
        '.....DDDDDD.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'chart', role: 'body' },
        B: { name: 'grid', role: 'head' },
        C: { name: 'stars', role: 'arm' },
        D: { name: 'border', role: 'eye' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. CONSTELLATION ORION ────────────────────────────────
    {
      id: 'constellation_orion_16',
      description: 'Orion constellation with bright stars connected by lines and belt of three.',
      grid: [
        '................',
        '....AA.....AA...',
        '....BB.....BB...',
        '.....BB...BB....',
        '......BB.BB.....',
        '.......BAB......',
        '......CCCCC.....',
        '.....BB...BB....',
        '....BB.....BB...',
        '...BB.......BB..',
        '..BB.........BB.',
        '..AA.........AA.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'stars', role: 'body' },
        B: { name: 'lines', role: 'head' },
        C: { name: 'belt', role: 'arm' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 14. SUNDIAL ────────────────────────────────────────────
    {
      id: 'sundial_16',
      description: 'Horizontal sundial with triangular gnomon, hour lines, and stone face.',
      grid: [
        '................',
        '................',
        '................',
        '.....AAAAAA.....',
        '....AAAAAAAA....',
        '...AACAAACAAA...',
        '..AACAAABAAAA...',
        '..AACAABBCAAAA..',
        '..AACABBBAACAA..',
        '..AAABBBAACAAA..',
        '...AABBBCAAAA...',
        '...AABBCAAAAA...',
        '....AACCAAAA....',
        '.....DDDDDD.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'dial', role: 'body' },
        B: { name: 'gnomon', role: 'head' },
        C: { name: 'hour_lines', role: 'arm' },
        D: { name: 'shadow', role: 'eye' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:  { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 15. MINI ORRERY ────────────────────────────────────────
    {
      id: 'mini_orrery_16',
      description: 'Small mechanical solar system model with sun, planet spheres, and metal arms.',
      grid: [
        '................',
        '................',
        '................',
        '.......AA.......',
        '......AAAA......',
        '......AAAA......',
        '.......BB.......',
        '...CC.BBBB.CC...',
        '..CCC.B..B.CCC..',
        '...BB.B..B.BB...',
        '....BBB..BBB....',
        '.......BB.......',
        '......DDDD......',
        '.....DDDDDD.....',
        '....DD....DD....',
        '................',
      ],
      chars: {
        A: { name: 'sun', role: 'body' },
        B: { name: 'arms', role: 'head' },
        C: { name: 'planets', role: 'arm' },
        D: { name: 'base', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. COMET ──────────────────────────────────────────────
    {
      id: 'comet_16',
      description: 'Comet with bright nucleus, coma glow, and streaming tail.',
      grid: [
        '..........CCCCC.',
        '.........CCCCC..',
        '........CCCCC...',
        '.......CCCC.....',
        '......CCCC......',
        '.....CCCC.......',
        '....CCCC........',
        '...CCCC.........',
        '...BBB..........',
        '..BBBB..........',
        '..BABB..........',
        '..BAAB..........',
        '..BBBB..........',
        '...BB...........',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'nucleus', role: 'body' },
        B: { name: 'coma', role: 'head' },
        C: { name: 'tail', role: 'arm' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 17. ECLIPSE ────────────────────────────────────────────
    {
      id: 'eclipse_16',
      description: 'Solar eclipse with dark moon disc, bright corona ring, and small prominences.',
      grid: [
        '..........D.....',
        '.....AAAAAA.....',
        '...AAACCCAAAA...',
        '..AACCCCCCCCAA..',
        '..ACCCCCCCCCCA..',
        '.AACCCCCCCCCBAA.',
        '.ACCCCCCCCCCCCA.',
        '.ACCCCCCCCCCCCA.',
        '.ACCCCCCCCCCCBA.',
        '.AACCCCCCCCCAA..',
        '..ACCCCCCCCCBA..',
        '..AACCCCCCCCAA..',
        '...AAACCCAAAA...',
        '.....AAAAAA.....',
        '...D............',
        '................',
      ],
      chars: {
        A: { name: 'corona', role: 'body' },
        B: { name: 'prominences', role: 'arm' },
        C: { name: 'moon', role: 'head' },
        D: { name: 'stars', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 18. ZODIAC WHEEL ───────────────────────────────────────
    {
      id: 'zodiac_wheel_16',
      description: 'Circular zodiac wheel with 12 alternating warm/cool segments and central sun.',
      grid: [
        '................',
        '.....AAAAAA.....',
        '...AABBCCBBAA...',
        '..ABBA..ABBCAA..',
        '..BBA....ABCBA..',
        '.ABC..DD..CBA...',
        '.ABB..DD..BBA...',
        '.ACB......BCA...',
        '.ABB......BBA...',
        '.ABC..DD..CBA...',
        '..BBA....ABCBA..',
        '..ABBA..ABBCAA..',
        '...AABBCCBBAA...',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'ring', role: 'body' },
        B: { name: 'segments_warm', role: 'head' },
        C: { name: 'segments_cool', role: 'arm' },
        D: { name: 'center', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. CELESTIAL COMPASS ──────────────────────────────────
    {
      id: 'celestial_compass_16',
      description: 'Eight-pointed compass rose with celestial motif, decorative ring, and central star.',
      grid: [
        '................',
        '.......AA.......',
        '......ABBA......',
        '.....DABBAD.....',
        '....DD.CC.DD....',
        '...D..CCCC..D...',
        '..DAABCCCCBAAD..',
        '.AABBCCCCCCBBAA.',
        '.AABBCCCCCCBBAA.',
        '..DAABCCCCBAAD..',
        '...D..CCCC..D...',
        '....DD.CC.DD....',
        '.....DABBAD.....',
        '......ABBA......',
        '.......AA.......',
        '................',
      ],
      chars: {
        A: { name: 'points', role: 'body' },
        B: { name: 'ring', role: 'head' },
        C: { name: 'center', role: 'arm' },
        D: { name: 'minor_points', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
