/**
 * Medieval Scholar's Collection — Batch 4: Geometry (11) + Music (9) = 20 templates.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'liberal_arts',
  exportNames: { templates: 'LIBERAL_ARTS_BATCH4_TEMPLATES', schemes: 'LIBERAL_ARTS_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ═══════════════════════════════════════════════════
    // GEOMETRY — Architecture, Measurement, Patterns (11)
    // ═══════════════════════════════════════════════════

    // ─── 1. ARCHITECT'S BLUEPRINT ────────────────────
    {
      id: 'architects_blueprint_16',
      description: 'Rolled architectural blueprint with floor plan lines and curled corner.',
      grid: [
        '................',
        '..AAAAAAAAAAAA..',
        '..ABBBBBBBBBBAC.',
        '..ABWWBBWWWBBAC.',
        '..ABWWBBWWWBBAC.',
        '..ABWWBBBBBBBA..',
        '..ABBBBBBBBBBBA.',
        '..ABWWWBBWWBBA..',
        '..ABWWWBBWWBBA..',
        '..ABWWWBBBBBBBA.',
        '..ABBBBBBBBBBA..',
        '..ABWBBWWWBBBA..',
        '..AAAAAAAAAAAA..',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'paper_edge', role: 'body' },
        B: { name: 'plan_field', role: 'head' },
        W: { name: 'wall_lines', role: 'arm' },
        C: { name: 'curl_shadow', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 2. STONE BLOCK CARVED ───────────────────────
    {
      id: 'stone_block_carved_16',
      description: 'Rectangular stone block with carved geometric circle-in-square motif.',
      grid: [
        '................',
        '................',
        '................',
        '...SSSSSSSSSS...',
        '...SFFCCCCFFS...',
        '...SFCDDDDCFS...',
        '...SFCD..DCFS...',
        '...SFCD..DCFS...',
        '...SFCDDDDCFS...',
        '...SFFCCCCFFS...',
        '...SSSSSSSSSS...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stone_body', role: 'body' },
        F: { name: 'face_plane', role: 'arm' },
        C: { name: 'carving', role: 'head' },
        D: { name: 'deep_cut', role: 'belt' },
        B: { name: 'shadow_base', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 3. GOTHIC WINDOW ────────────────────────────
    {
      id: 'gothic_window_16',
      description: 'Miniature Gothic pointed arch window with tracery and stained glass.',
      grid: [
        '................',
        '.......SS.......',
        '......SWWS......',
        '.....SWCCWS.....',
        '....SWCCCCWS....',
        '....SWCCCCWS....',
        '...SWWCCCCWWS...',
        '...SWCCCCCCWS...',
        '...SWCCWWCCWS...',
        '...SWCCWWCCWS...',
        '...SWCCWWCCWS...',
        '...SWWCCCCWWS...',
        '...SWCCCCCCWS...',
        '...SSSSSSSSSS...',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stone_frame', role: 'body' },
        W: { name: 'tracery', role: 'belt' },
        C: { name: 'glass_warm', role: 'head' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 4. ROSE WINDOW ─────────────────────────────
    {
      id: 'rose_window_16',
      description: 'Circular rose window with radial petal divisions and glowing center.',
      grid: [
        '................',
        '.....SSSSSS.....',
        '....SRRRRRRS....',
        '...SRRRBRRRS....',
        '..SRRRRBRRRRRS..',
        '..SRRRBBBRRRRS..',
        '..SBBBBGBBBBBS..',
        '..SRRRBBBRRRRS..',
        '..SRRRRBRRRRRS..',
        '...SRRRBRRRS....',
        '....SRRRRRRS....',
        '.....SSSSSS.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stone_frame', role: 'body' },
        R: { name: 'petals_warm', role: 'head' },
        B: { name: 'petals_cool', role: 'arm' },
        G: { name: 'center_gem', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. PLUMB BOB ───────────────────────────────
    {
      id: 'plumb_bob_16',
      description: 'Plumb bob hanging from string for vertical alignment.',
      grid: [
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '......SS........',
        '.....BRRB.......',
        '....BRRRRB......',
        '....BRRRRB......',
        '....BRRRRB......',
        '.....BRRB.......',
        '......BB........',
        '................',
      ],
      chars: {
        S: { name: 'string', role: 'head' },
        R: { name: 'weight_body', role: 'body' },
        B: { name: 'weight_edge', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 6. MASON TOOLS ─────────────────────────────
    {
      id: 'mason_tools_16',
      description: 'Mason chisel and mallet crossed in X formation with stone chips.',
      grid: [
        '................',
        '..MM......CC....',
        '...MM....CC.....',
        '....MM..CC......',
        '.....MMCC.......',
        '....MMHHCC......',
        '...MM.HH.CC.....',
        '..MM..HH..CC....',
        '.MM...HH...CC...',
        '......HH........',
        '......HH........',
        '......BB........',
        '.....DDDD.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'mallet_head', role: 'body' },
        H: { name: 'handles', role: 'arm' },
        C: { name: 'chisel_blade', role: 'head' },
        B: { name: 'chisel_tip', role: 'belt' },
        D: { name: 'stone_chips', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 7. GEOMETRIC TILE ──────────────────────────
    {
      id: 'geometric_tile_16',
      description: 'Repeatable interlocking geometric floor tile in Islamic/medieval style.',
      grid: [
        'GGGGAAAAAAGGGGAA',
        'GGGAAAAAAGGGAAAA',
        'GGAAAABBAAAABBAA',
        'GAAABBBBAAABBBBA',
        'AAABBBBBBABBBBBB',
        'AABBBBBBBBBBBBBB',
        'AABBBBGGBBBBGGBB',
        'AABBGGGGBBGGGGBB',
        'AABBGGGGBBGGGGBB',
        'AABBBBGGBBBBGGBB',
        'AABBBBBBBBBBBBBB',
        'AAABBBBBBABBBBBB',
        'GAAABBBBAAABBBBA',
        'GGAAAABBAAAABBAA',
        'GGGAAAAAAGGGAAAA',
        'GGGGAAAAAAGGGGAA',
      ],
      chars: {
        A: { name: 'pattern_a', role: 'body' },
        B: { name: 'pattern_b', role: 'head' },
        G: { name: 'grout_line', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 8. DIVIDER CALIPERS ────────────────────────
    {
      id: 'divider_calipers_16',
      description: 'Measuring calipers with two pointed legs and ornate pivot knob.',
      grid: [
        '................',
        '.......GG.......',
        '......GGGG......',
        '.......LL.......',
        '......L..L......',
        '.....L....L.....',
        '.....L....L.....',
        '....L......L....',
        '....L......L....',
        '...L........L...',
        '...L........L...',
        '..L..........L..',
        '..TT........TT..',
        '..DD........DD..',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'pivot_knob', role: 'head' },
        L: { name: 'legs', role: 'body' },
        T: { name: 'tips', role: 'arm' },
        D: { name: 'points', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. LEVEL TOOL ──────────────────────────────
    {
      id: 'level_tool_16',
      description: 'Builder A-frame spirit level with dangling plumb line from apex.',
      grid: [
        '................',
        '......FFFF......',
        '.....FF..FF.....',
        '.....FF..FF.....',
        '....FF.PP.FF....',
        '....FF.PP.FF....',
        '...FF..PP..FF...',
        '...FF..PP..FF...',
        '..FF...GG...FF..',
        '..FFFFFFFFFFFF..',
        '.FF....GG....FF.',
        '.FF....GG....FF.',
        'FF.....GG.....FF',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame_legs', role: 'body' },
        P: { name: 'plumb_string', role: 'arm' },
        G: { name: 'plumb_weight', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. GEOMETRIC STAR ─────────────────────────
    {
      id: 'geometric_star_16',
      description: 'Six-pointed star from two overlapping triangles with bright center.',
      grid: [
        '................',
        '.......AA.......',
        '......AAAA......',
        '.....AACCAA.....',
        '....AACCCCAA....',
        '...AACCCCCCAA...',
        '..BBBBCCCCBBBB..',
        '...BBCCCCCCBB...',
        '....BBCCCCBB....',
        '...BBCCCCCCBB...',
        '..BBBBCCCCBBBB..',
        '...AACCCCCCAA...',
        '....AACCCCAA....',
        '.....AACCAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        A: { name: 'triangle_a', role: 'body' },
        B: { name: 'triangle_b', role: 'head' },
        C: { name: 'overlap_center', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 11. PROTRACTOR ARC ─────────────────────────
    {
      id: 'protractor_arc_16',
      description: 'Half-circle protractor with degree tick marks and center point.',
      grid: [
        '................',
        '................',
        '................',
        '...DDSSSSSSDD...',
        '..DSSSSSSSSSD...',
        '..DSBBBBBBBBSD..',
        '.DSBB......BBSD.',
        '.DSB........BSD.',
        '.DSB........BSD.',
        '.DSB...CC...BSD.',
        '.DSB........BSD.',
        '.DSBB......BBSD.',
        '..DSBBBBBBBBSD..',
        '..DSSSSSSSSSSSD.',
        '...DDSSSSSSSDD..',
        '................',
      ],
      chars: {
        S: { name: 'arc_body', role: 'body' },
        D: { name: 'tick_marks', role: 'head' },
        B: { name: 'inner_field', role: 'arm' },
        C: { name: 'center_point', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ═══════════════════════════════════════════════════
    // MUSIC — Medieval Instruments & Sound (9)
    // ═══════════════════════════════════════════════════

    // ─── 12. MEDIEVAL LUTE ──────────────────────────
    {
      id: 'medieval_lute_16',
      description: 'Lute with teardrop body, rosette sound hole, neck and angled pegbox.',
      grid: [
        '................',
        '.PP.............',
        '..PP............',
        '..PPSS..........',
        '...SSSS.........',
        '...SSSS.........',
        '....SSSS........',
        '....SSSS........',
        '...BBBBBB.......',
        '..BBBDDBBB......',
        '..BBBDDBBB......',
        '..BBBBBBBB......',
        '..BBBBBBB.......',
        '...BBBBB........',
        '....BBB.........',
        '................',
      ],
      chars: {
        P: { name: 'pegbox', role: 'belt' },
        S: { name: 'strings_neck', role: 'arm' },
        B: { name: 'body_wood', role: 'body' },
        D: { name: 'soundhole', role: 'head' },
      },
      colors: {
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 13. CELTIC HARP ────────────────────────────
    {
      id: 'celtic_harp_16',
      description: 'Small triangular Celtic harp with curved pillar and vertical strings.',
      grid: [
        '................',
        '..FFFFFF........',
        '..F...FF........',
        '..F..SSFF.......',
        '..F..S.SFF......',
        '..F..S..SFF.....',
        '..F..S..SFFF....',
        '..F..S..S.FFF...',
        '..FF.S..S..FF...',
        '...FFS..S..FF...',
        '...FFS..S.FF....',
        '....FFS.SFFF....',
        '....BBBBBBB.....',
        '.....BBBBB......',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame_pillar', role: 'body' },
        S: { name: 'strings', role: 'head' },
        B: { name: 'soundbox', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 14. LYRE ───────────────────────────────────
    {
      id: 'lyre_16',
      description: 'Ancient lyre with U-shaped arms, crossbar, and strings over sound box.',
      grid: [
        '................',
        '..AA......AA....',
        '..AA......AA....',
        '..AA......AA....',
        '..AACCCCCCAA....',
        '..AA.SSSS.AA....',
        '..AA.SSSS.AA....',
        '...A.SSSS.A.....',
        '...BBBBBBBBB....',
        '...BBSSSSBB.....',
        '...BBSSSSBB.....',
        '...BBSSSSBB.....',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'arms', role: 'body' },
        C: { name: 'crossbar', role: 'belt' },
        S: { name: 'strings', role: 'arm' },
        B: { name: 'sound_box', role: 'head' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 15. PSALTERY ───────────────────────────────
    {
      id: 'psaltery_16',
      description: 'Trapezoidal psaltery with diagonal strings, sound holes, and tuning pins.',
      grid: [
        '................',
        '................',
        '..WWWW..........',
        '..WSSWWW........',
        '..WSSDSSWW......',
        '..WSSSDSSSWW....',
        '..WSSSSDSSSWWW..',
        '..WSSSSSDSSSWW..',
        '..WSSSSSSDSSSWW.',
        '..WSSSSSSSDSWW..',
        '..WSSDSSSSSDWW..',
        '..WSSSSSSSSWW...',
        '..WWWWWWWWWWWW..',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'body_wood', role: 'body' },
        S: { name: 'strings', role: 'head' },
        D: { name: 'sound_holes', role: 'arm' },
        P: { name: 'pins', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 16. REBEC ──────────────────────────────────
    {
      id: 'rebec_16',
      description: 'Pear-shaped bowed rebec with narrow neck, bow, and strings.',
      grid: [
        '................',
        '..PP............',
        '..PPNN..........',
        '...NNNN.........',
        '...NNNN.........',
        '....NNSS........',
        '...BBBBSS.......',
        '..BBSSBBSS......',
        '..BSSSSB.SS.....',
        '..BSSSSB..SS....',
        '..BBSSBB...SS...',
        '...BBBB.....SS..',
        '....BB.......SS.',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'pegbox', role: 'belt' },
        N: { name: 'neck', role: 'body' },
        B: { name: 'body_wood', role: 'head' },
        S: { name: 'strings_bow', role: 'arm' },
      },
      colors: {
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. PORTATIVE ORGAN ────────────────────────
    {
      id: 'portative_organ_16',
      description: 'Small portable pipe organ with graduated pipes and keyboard row.',
      grid: [
        '................',
        '......PP........',
        '.....PPPP.......',
        '....PPPPPP......',
        '...PPPPPPPP.....',
        '..PPPPPPPPPP....',
        '..FFFFFFFFFFFF..',
        '..FPPPPPPPPPPF..',
        '..FPPPPPPPPPPF..',
        '..FPPPPPPPPPPF..',
        '..FFFFFFFFFFFF..',
        '..FKKBKKBKKBKF..',
        '..FKKBKKBKKBKF..',
        '..FFFFFFFFFFFF..',
        '..FDDDDDDDDDDF..',
        '................',
      ],
      chars: {
        P: { name: 'pipes', role: 'body' },
        F: { name: 'frame', role: 'head' },
        K: { name: 'white_keys', role: 'arm' },
        B: { name: 'black_keys', role: 'belt' },
        D: { name: 'bellows', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 18. DRUM TABOR ─────────────────────────────
    {
      id: 'drum_tabor_16',
      description: 'Small cylindrical tabor drum with tension cords and drumstick.',
      grid: [
        '................',
        '................',
        '...HHHHHHHH.....',
        '..HPPPPPPPPPH...',
        '..BCBCBCBCBCB...',
        '..BWWWWWWWWWB...',
        '..BWCWWWWCWWB...',
        '..BWWWCWWWCWB...',
        '..BWWWWCWWWWB...',
        '..BWCWWWWCWWB...',
        '..BWWWWWWWWWB...',
        '..BCBCBCBCBCB...',
        '..HPPPPPPPPPH...',
        '...HHHHHHHH..SS.',
        '..............SS',
        '................',
      ],
      chars: {
        H: { name: 'drum_head', role: 'head' },
        P: { name: 'head_skin', role: 'arm' },
        B: { name: 'shell_body', role: 'body' },
        W: { name: 'shell_wall', role: 'body' },
        C: { name: 'cords', role: 'eye' },
        S: { name: 'stick', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. CHURCH BELL ────────────────────────────
    {
      id: 'church_bell_16',
      description: 'Bronze church bell with crown mount, flared lip and hanging clapper.',
      grid: [
        '................',
        '......CCCC......',
        '.....CCCCCC.....',
        '.....CCCCCC.....',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBDDBBBB....',
        '...BBBBDDBBBB...',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..FFFFFFFFFFFF..',
        '................',
      ],
      chars: {
        C: { name: 'crown_yoke', role: 'head' },
        B: { name: 'bell_body', role: 'body' },
        D: { name: 'clapper', role: 'arm' },
        F: { name: 'flared_lip', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. MONOCHORD ──────────────────────────────
    {
      id: 'monochord_16',
      description: 'Single-string monochord instrument with long sound box and movable bridge.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.SSSSSSSSSSSSSS.',
        '.WWWWWWWWWWWWWW.',
        '.WBBBBBBBBBBBBW.',
        '.WBBBBBRBBBBBBW.',
        '.WBBBBBBBBBBBBW.',
        '.WWWWWWWWWWWWWW.',
        '.PPWWWWWWWWWWPP.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'string', role: 'head' },
        W: { name: 'box_frame', role: 'body' },
        B: { name: 'box_face', role: 'arm' },
        R: { name: 'bridge', role: 'eye' },
        P: { name: 'pegs', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

  ],
};

export default batch;
