/**
 * Library batch 4 — Atmosphere & Cozy Details.
 * 20 cozy library simulator props: candles, tea, blankets, cats, fireside items.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'library',
  exportNames: { templates: 'LIBRARY_BATCH4_TEMPLATES', schemes: 'LIBRARY_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. CAT SLEEPING ────────────────────────────────────────
    {
      id: 'cat_sleeping_16',
      description: 'Curled-up sleeping cat on a round cushion.',
      grid: [
        '................',
        '................',
        '................',
        '.....HHEE.......',
        '....HHHHHH......',
        '...HHHHHHHBB....',
        '..CCCBBBBBBBB...',
        '..CBBBBBBBBBBC..',
        '..CBBBTTBBBBC...',
        '..CCBBBBBBCCC...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cat_head', role: 'head' },
        E: { name: 'cat_ears', role: 'accessory' },
        B: { name: 'cat_body', role: 'body' },
        C: { name: 'cat_outline', role: 'arm' },
        T: { name: 'tail_tip', role: 'belt' },
        P: { name: 'cushion', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 2. TEACUP SAUCER ───────────────────────────────────────
    {
      id: 'teacup_saucer_16',
      description: 'Teacup on saucer with wisps of steam rising.',
      grid: [
        '................',
        '.......S.S......',
        '......S.S.......',
        '.......S........',
        '....RRRRRRRR....',
        '...RBBBBBBBBR...',
        '...RBBBBBBBBR...',
        '...RBBBBBBBBR...',
        '....RBBBBBBR.H..',
        '.....RRRRRR..H..',
        '......RRRR..H...',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'accessory' },
        R: { name: 'cup_rim', role: 'head' },
        B: { name: 'tea_liquid', role: 'body' },
        H: { name: 'handle', role: 'arm' },
        P: { name: 'saucer', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 3. READING BOOKMARK ────────────────────────────────────
    {
      id: 'reading_bookmark_16',
      description: 'Decorative ribbon bookmark with tassel, resting in open book.',
      grid: [
        '................',
        '......RR........',
        '......RR........',
        '......RR........',
        '......RR........',
        '..BBBBRRBBBBB...',
        '..BPPPRRPPPBB...',
        '..BPPPRRPPPBB...',
        '..BPPPRRPPPBB...',
        '..BPPPRRPPPBB...',
        '..BBBBRRBBBBB...',
        '......RR........',
        '......RR........',
        '.....TTTT.......',
        '....TT..TT......',
        '................',
      ],
      chars: {
        R: { name: 'ribbon', role: 'accessory' },
        B: { name: 'book_cover', role: 'body' },
        P: { name: 'pages', role: 'head' },
        T: { name: 'tassel', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. CANDLE MELTING ──────────────────────────────────────
    {
      id: 'candle_melting_16',
      description: 'Half-melted candle in brass holder with wax drips.',
      grid: [
        '................',
        '........F.......',
        '.......FFF......',
        '.......WW.......',
        '......WWWW......',
        '......WWWW......',
        '......WWWW......',
        '.....WWWWWW.....',
        '.....WDDWWW.....',
        '....HHHHHHHH....',
        '...HHBBBBBBHH...',
        '...HBBBBBBBBH...',
        '....HBBBBBBH....',
        '.....HHHHHH.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flame', role: 'accessory' },
        W: { name: 'wax_body', role: 'head' },
        D: { name: 'wax_drip', role: 'eye' },
        H: { name: 'holder_rim', role: 'arm' },
        B: { name: 'holder_body', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. LANTERN DESK ────────────────────────────────────────
    {
      id: 'lantern_desk_16',
      description: 'Small brass desk lantern with glass dome and warm glow.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '.....GGGGGG.....',
        '....GGFFFFGG....',
        '....GGFFFFGG....',
        '....GGFFFFGG....',
        '....GGFFGGGG....',
        '.....GGGGGG.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'top_cap', role: 'head' },
        G: { name: 'glass_dome', role: 'eye' },
        F: { name: 'flame_glow', role: 'accessory' },
        B: { name: 'brass_base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. OIL LAMP ────────────────────────────────────────────
    {
      id: 'oil_lamp_library_16',
      description: 'Glass oil lamp with brass fittings and visible flame.',
      grid: [
        '................',
        '.......FF.......',
        '......FFFF......',
        '......GGGG......',
        '.....GGGGG......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '....GGGGGGGG....',
        '.....GGGGGG.....',
        '....HHHHHHHH....',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '....HHHHHHHH....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flame', role: 'accessory' },
        G: { name: 'glass_chimney', role: 'eye' },
        H: { name: 'brass_fittings', role: 'head' },
        B: { name: 'oil_reservoir', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. DUSTY WINDOW ────────────────────────────────────────
    {
      id: 'dusty_window_16',
      description: 'Arched window with dust motes floating in a light beam.',
      grid: [
        '..FFFFFFFFFFF...',
        '.FFFFFFFFFFFFF..',
        '.FGGGGFFGGGGGF..',
        '.FGGGGFFGGGGGF..',
        '.FGGGGFFGGGGGF..',
        '.FGGDGFFGGDGGF..',
        '.FGGGGFFGGGGGF..',
        '.FFFFFFFFFFFFFFI',
        '.FGGGGFFGGGGGF..',
        '.FGDGGFFGGDGGF..',
        '.FGGGGFFGGGGGF..',
        '.FGGGGFFGGGGGF..',
        '.FFFFFFFFFFFFF..',
        '..SSSSSSS.......',
        '...SSSSS........',
        '................',
      ],
      chars: {
        F: { name: 'window_frame', role: 'body' },
        G: { name: 'glass_panes', role: 'eye' },
        D: { name: 'dust_motes', role: 'accessory' },
        S: { name: 'light_beam', role: 'head' },
        I: { name: 'latch', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 8. READING TRAY ────────────────────────────────────────
    {
      id: 'reading_tray_16',
      description: 'Wooden serving tray with tea mug and biscuit.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBCCBBBBBBH..',
        '..HBBCCBBDDDDHK.',
        '..HBBCCBBDDDDHK.',
        '..HBBBBBBDDDDHK.',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'tray_rim', role: 'head' },
        B: { name: 'tray_surface', role: 'body' },
        C: { name: 'biscuit', role: 'accessory' },
        D: { name: 'mug_body', role: 'eye' },
        K: { name: 'mug_handle', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 9. NIGHT CANDLE ────────────────────────────────────────
    {
      id: 'night_candle_16',
      description: 'Candle in handheld chamberstick with finger loop.',
      grid: [
        '................',
        '.........F......',
        '........FFF.....',
        '........WW......',
        '........WW......',
        '........WW......',
        '.......WWWW.....',
        '......HHHHHH....',
        '.....HBBBBBBH...',
        '.....HBBBBBBH...',
        '......HHHHHH....',
        '.....HHHH.......',
        '....HH..........',
        '....HHH.........',
        '.....HH.........',
        '................',
      ],
      chars: {
        F: { name: 'flame', role: 'accessory' },
        W: { name: 'candle_wax', role: 'eye' },
        H: { name: 'holder_brass', role: 'head' },
        B: { name: 'dish_interior', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 10. READING PILLOW ─────────────────────────────────────
    {
      id: 'reading_pillow_16',
      description: 'Plush velvet reading cushion with tufted button center.',
      grid: [
        '................',
        '................',
        '................',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBCBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....SSSSSSSS....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'velvet_fabric', role: 'body' },
        C: { name: 'tuft_button', role: 'accessory' },
        S: { name: 'shadow', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 11. PIPE TOBACCO ───────────────────────────────────────
    {
      id: 'pipe_tobacco_16',
      description: 'Tobacco pipe resting on a small wooden stand.',
      grid: [
        '................',
        '................',
        '................',
        '....BB..........',
        '...BBBB.........',
        '...BCCB.........',
        '...BBBB.........',
        '....SSSS........',
        '.....SSSS.......',
        '......SSSS......',
        '.......SSSSM....',
        '........SSMM....',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '................',
      ],
      chars: {
        B: { name: 'bowl', role: 'body' },
        C: { name: 'tobacco', role: 'accessory' },
        S: { name: 'stem', role: 'head' },
        M: { name: 'mouthpiece', role: 'eye' },
        R: { name: 'rest_stand', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 12. POCKET WATCH ───────────────────────────────────────
    {
      id: 'pocket_watch_library_16',
      description: 'Open pocket watch showing clock face with chain.',
      grid: [
        '................',
        '.........KK.....',
        '........KK......',
        '.......KK.......',
        '....HHHHHHHH....',
        '...HHHHHHHHHHH..',
        '..HHFFFFFFFHH...',
        '..HFFFFFFFFFFFH.',
        '..HFFFFFAFFFFFH.',
        '..HFFFFFAAFFHH..',
        '..HHFFFFFFFHH...',
        '...HHHHHHHHHHH..',
        '....HHHHHHHH....',
        '................',
        '................',
        '................',
      ],
      chars: {
        K: { name: 'chain', role: 'accessory' },
        H: { name: 'case_rim', role: 'head' },
        F: { name: 'watch_face', role: 'body' },
        A: { name: 'hands', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 13. TEA COZY KNIT ──────────────────────────────────────
    {
      id: 'tea_cozy_knit_16',
      description: 'Knitted tea cozy covering a teapot with pom-pom on top.',
      grid: [
        '................',
        '.......PP.......',
        '......PPPP......',
        '.....KKKKKK.....',
        '....KKKKKKKKK...',
        '...KKMKKKMKKK...',
        '...KKKKKKKKKKK..',
        '..KKMKKKMKKKKKH.',
        '..KKKKKKKKKKKKHH',
        '..KKKKKKKKKKKKH.',
        '...BBBBBBBBBBH..',
        '...BBBBBBBBBB...',
        '....SSSSSSSS....',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'pom_pom', role: 'accessory' },
        K: { name: 'knit_cozy', role: 'body' },
        M: { name: 'knit_pattern', role: 'belt' },
        H: { name: 'spout_handle', role: 'head' },
        B: { name: 'teapot_base', role: 'arm' },
        S: { name: 'saucer', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 14. WOOL BLANKET ───────────────────────────────────────
    {
      id: 'wool_blanket_16',
      description: 'Folded wool throw blanket with plaid pattern.',
      grid: [
        '................',
        '................',
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BBPPBBPPBBPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BPPBBPPBBPPBBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBPPBBPPBBPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BPPBBPPBBPPBBB.',
        '.BBBBBBBBBBBBBB.',
        '..FFFFFFFFFFFF..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'wool_base', role: 'body' },
        P: { name: 'plaid_stripe', role: 'accessory' },
        F: { name: 'fringe', role: 'head' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 15. HOUSE SLIPPERS ─────────────────────────────────────
    {
      id: 'house_slippers_16',
      description: 'Pair of cozy house slippers side by side.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.TTTTTT.TTTTTT..',
        '.TBBBBT.TBBBBT..',
        '.TBBBBT.TBBBBT..',
        'TBBBBBBTTBBBBBBT',
        'TBBBBBBTTBBBBBBT',
        'TBBSSBBTTBBSSBBR',
        'TBBBBBBTTTBBBBBT',
        '.TTTTTT..TTTTTT.',
        '................',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'slipper_rim', role: 'head' },
        B: { name: 'slipper_body', role: 'body' },
        S: { name: 'inner_lining', role: 'eye' },
        R: { name: 'sole_edge', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 16. HOT COCOA MUG ──────────────────────────────────────
    {
      id: 'hot_cocoa_mug_16',
      description: 'Mug of hot cocoa with a marshmallow floating on top.',
      grid: [
        '................',
        '......S.S.......',
        '.......S........',
        '....RRRRRRRR....',
        '...RCCCCCCCCR...',
        '...RCCMMMMCCR...',
        '...RCCMMMMCCR...',
        '...RCCCCCCCCR.H.',
        '...RCCCCCCCCRHH.',
        '...RCCCCCCCCR.H.',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'accessory' },
        R: { name: 'mug_body', role: 'body' },
        C: { name: 'cocoa', role: 'head' },
        M: { name: 'marshmallow', role: 'eye' },
        H: { name: 'handle', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 17. CINNAMON BUNDLE ────────────────────────────────────
    {
      id: 'cinnamon_bundle_16',
      description: 'Cinnamon sticks tied together with rustic twine.',
      grid: [
        '................',
        '................',
        '................',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCTTTTTTCCC..',
        '..CCCTTTTTTCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..SSCCCCCCCCSS..',
        '..SSCCCCCCCCSS..',
        '...CCCCCCCCCC...',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cinnamon_bark', role: 'body' },
        T: { name: 'twine', role: 'accessory' },
        S: { name: 'stick_ends', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 18. FIREPLACE TOOLS ────────────────────────────────────
    {
      id: 'fireplace_tools_16',
      description: 'Poker and tongs on a standing iron tool rack.',
      grid: [
        '................',
        '.....BBBB.......',
        '.....BRRB.......',
        '.....BBBB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '.....BPPB.......',
        '....BBPPBB......',
        '...HHHPPHHH.....',
        '..HH..PP..HH....',
        '................',
      ],
      chars: {
        B: { name: 'rack_frame', role: 'body' },
        R: { name: 'rack_hook', role: 'accessory' },
        P: { name: 'poker_tongs', role: 'head' },
        H: { name: 'base_feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. LOG STACK ──────────────────────────────────────────
    {
      id: 'log_stack_16',
      description: 'Neat stack of firewood logs, cross-section visible.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBRBB......',
        '....BBBRBBB.....',
        '...BBRBBBRBB....',
        '..BBRBBBBBRBB...',
        '..BBBBBBBBBBB...',
        '..BBRBBBRBBBB...',
        '..BBBBRBBBRBB...',
        '..BBRBBBBBRBB...',
        '..BBBBBBBBBBB...',
        '..BBRBBBRBBBB...',
        '..BBBBBBBBBBB...',
        '...SSSSSSSSS....',
        '................',
      ],
      chars: {
        B: { name: 'bark', role: 'body' },
        R: { name: 'wood_rings', role: 'head' },
        S: { name: 'ground_shadow', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 20. COZY SCARF ─────────────────────────────────────────
    {
      id: 'cozy_scarf_16',
      description: 'Knitted scarf draped over a wall hook.',
      grid: [
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '......HHH.......',
        '.....BB.BB......',
        '....BB...BB.....',
        '...BBB...BBB....',
        '...BBB...BBB....',
        '...BPB...BPB....',
        '...BBB...BBB....',
        '...BPB...BBB....',
        '...BBB...BPB....',
        '...BPB...BBB....',
        '...BBB...BBB....',
        '..FFFF..FFFF....',
        '................',
      ],
      chars: {
        H: { name: 'wall_hook', role: 'head' },
        B: { name: 'scarf_knit', role: 'body' },
        P: { name: 'stripe_pattern', role: 'accessory' },
        F: { name: 'fringe_tassels', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
