/**
 * Cozy Library Simulator batch 1 — 20 furniture & shelves.
 * Reading rooms, study nooks, brass lamps, oak cabinets.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'library',
  exportNames: { templates: 'LIBRARY_BATCH1_TEMPLATES', schemes: 'LIBRARY_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. BOOKSHELF TALL — three shelves of books ─────────────
    {
      id: 'bookshelf_tall_lib_16',
      description: 'Tall oak bookshelf with three shelves of colorful books.',
      grid: [
        '..FFFFFFFFFFFF..',
        '..FRRBBRRBBRRF..',
        '..FRRBBRRBBRRF..',
        '..FFFFFFFFFFFF..',
        '..FBBGGBBGGGBF..',
        '..FBBGGBBGGGBF..',
        '..FFFFFFFFFFFF..',
        '..FRRGGRRGGGRF..',
        '..FRRGGRRGGGRF..',
        '..FFFFFFFFFFFF..',
        '..FBBRRBBRRRRF..',
        '..FBBRRBBRRRRF..',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        R: { name: 'red_books', role: 'accessory' },
        B: { name: 'blue_books', role: 'arm' },
        G: { name: 'green_books', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 2. READING DESK — green felt top and drawers ───────────
    {
      id: 'reading_desk_16',
      description: 'Reading desk with green felt writing surface and side drawers.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.FFFFFFFFFFFFFF.',
        '.FGGGGGGGGGGGGF.',
        '.FGGGGGGGGGGGGF.',
        '.FGGGGGGGGGGGGF.',
        '.FFFFFFFFFFFFFF.',
        '.FF.DDHHDD..FF..',
        '.FF.DDHHDD..FF..',
        '.FF.DDHHDD..FF..',
        '.FF.FFFFFF..FF..',
        '.FF.........FF..',
        '.FF.........FF..',
        '................',
      ],
      chars: {
        F: { name: 'desk_frame', role: 'body' },
        G: { name: 'felt_top', role: 'accessory' },
        D: { name: 'drawers', role: 'head' },
        H: { name: 'handles', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 3. ARMCHAIR LEATHER — wingback ─────────────────────────
    {
      id: 'armchair_leather_16',
      description: 'Leather wingback armchair with tufted back and wooden feet.',
      grid: [
        '................',
        '..BBBBBBBBBB....',
        '..BBLLLLLLBB....',
        '..BBLLLLLLBB....',
        '..BBLLLLLLBB....',
        '..BBLLTTLLBB....',
        '.AABBLLLLBBAA...',
        '.AABBLLLLBBAA...',
        '.AABBBBBBBBA....',
        '.AASSSSSSSSAA...',
        '.AASSSSSSSSAA...',
        '..AABBBBBBAA....',
        '..AABBBBBBAA....',
        '..FF......FF....',
        '..FF......FF....',
        '................',
      ],
      chars: {
        B: { name: 'back', role: 'body' },
        L: { name: 'leather_pad', role: 'head' },
        T: { name: 'tufts', role: 'belt' },
        A: { name: 'armrests', role: 'arm' },
        S: { name: 'seat_cushion', role: 'accessory' },
        F: { name: 'feet', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 4. LIBRARY LADDER — rolling on rail ────────────────────
    {
      id: 'library_ladder_16',
      description: 'Rolling library ladder on brass rail with wooden rungs.',
      grid: [
        '...RR......RR...',
        '...RR......RR...',
        '...RRRRRRRRRR...',
        '...RR......RR...',
        '...RR......RR...',
        '..LLLLLLLLLLLL..',
        '..LL........LL..',
        '..LLRRRRRRRRLL..',
        '..LL........LL..',
        '..LLRRRRRRRRLL..',
        '..LL........LL..',
        '..LLRRRRRRRRLL..',
        '..LL........LL..',
        '..LL........LL..',
        '..WW........WW..',
        '................',
      ],
      chars: {
        R: { name: 'rail', role: 'accessory' },
        L: { name: 'ladder_side', role: 'body' },
        W: { name: 'wheels', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 5. BOOK CART — wheeled two-shelf ───────────────────────
    {
      id: 'book_cart_16',
      description: 'Wheeled book cart with two shelves loaded with books.',
      grid: [
        '................',
        '................',
        '..FFFFFFFFFFFF..',
        '..FRRBBRRBBRRF..',
        '..FRRBBRRBBRRF..',
        '..FFFFFFFFFFFF..',
        '..FBBGGBBGGGBF..',
        '..FBBGGBBGGGBF..',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FFFFFFFFFFFF..',
        '..WW........WW..',
        '..WW........WW..',
        '................',
      ],
      chars: {
        F: { name: 'cart_frame', role: 'body' },
        R: { name: 'red_books', role: 'accessory' },
        B: { name: 'blue_books', role: 'arm' },
        G: { name: 'green_books', role: 'eye' },
        W: { name: 'wheels', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 6. CARD CATALOG — cabinet with tiny drawers ────────────
    {
      id: 'card_catalog_16',
      description: 'Wooden card catalog cabinet with rows of small labeled drawers.',
      grid: [
        '..FFFFFFFFFFFF..',
        '..FDDHDDHDDHDDF.',
        '..FDDHDDHDDHDDF.',
        '..FFFFFFFFFFFF..',
        '..FDDHDDHDDHDDF.',
        '..FDDHDDHDDHDDF.',
        '..FFFFFFFFFFFF..',
        '..FDDHDDHDDHDDF.',
        '..FDDHDDHDDHDDF.',
        '..FFFFFFFFFFFF..',
        '..FDDHDDHDDHDDF.',
        '..FDDHDDHDDHDDF.',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'cabinet_frame', role: 'body' },
        D: { name: 'drawers', role: 'head' },
        H: { name: 'drawer_pulls', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 7. FLOOR LAMP — standing with fabric shade ─────────────
    {
      id: 'floor_lamp_16',
      description: 'Standing floor lamp with warm fabric shade and brass pole.',
      grid: [
        '................',
        '.....SSSSSS.....',
        '....SSSSSSSS....',
        '...SSSGGGGSSS...',
        '...SSGGGGGSS....',
        '....SSSSSSSS....',
        '.....SSSSSS.....',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '.......PP.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '................',
      ],
      chars: {
        S: { name: 'shade', role: 'head' },
        G: { name: 'glow', role: 'eye' },
        P: { name: 'pole', role: 'accessory' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. WALL SCONCE — candle sconce ─────────────────────────
    {
      id: 'wall_sconce_16',
      description: 'Wall-mounted iron candle sconce with lit candle and dripping wax.',
      grid: [
        '................',
        '........GG......',
        '.......GGGG.....',
        '.......GGGG.....',
        '........CC......',
        '........CC......',
        '........CC......',
        '........CC......',
        '.......WWWW.....',
        '.......WWWW.....',
        '......BBBBBB....',
        '......BBBBB.....',
        '.....AAABBB.....',
        '.....AAA........',
        '....AAA.........',
        '................',
      ],
      chars: {
        G: { name: 'flame_glow', role: 'eye' },
        C: { name: 'candle', role: 'head' },
        W: { name: 'wax_drip', role: 'belt' },
        B: { name: 'holder', role: 'body' },
        A: { name: 'arm_bracket', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 9. FIREPLACE LIBRARY — brick with fire and mantle ──────
    {
      id: 'fireplace_library_16',
      description: 'Brick library fireplace with crackling fire and wooden mantle.',
      grid: [
        '.MMMMMMMMMMMMMM.',
        '.MMMMMMMMMMMMMM.',
        '.BB..FFFFFFFF.BB',
        '.BB.FFFFFFFFFF.B',
        '.BB.FFFFGGFFFF.B',
        '.BB.FFFGGGGFFF.B',
        '.BB.FFFGGGGFFF.B',
        '.BB..FFFFFFFF..B',
        '.BBBB........BBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        'BBBBBBBBBBBBBBBB',
        '.HHHHHHHHHHHHHH.',
        '................',
      ],
      chars: {
        M: { name: 'mantle', role: 'head' },
        B: { name: 'brickwork', role: 'body' },
        F: { name: 'flames', role: 'accessory' },
        G: { name: 'fire_core', role: 'eye' },
        H: { name: 'hearth', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 10. BOOKEND PAIR — metal bookends with books ───────────
    {
      id: 'bookend_pair_16',
      description: 'Decorative metal bookends with a row of books between them.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BB.RRGGRR.BB..',
        '..BBBRRGGRRBBBB.',
        '..BBBBBBBBBBBBB.',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bookends', role: 'body' },
        R: { name: 'red_books', role: 'accessory' },
        G: { name: 'green_books', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 11. READING NOOK — built-in seat with cushion ──────────
    {
      id: 'reading_nook_16',
      description: 'Built-in reading nook with arched top, cushion seat, and pillow.',
      grid: [
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF.PPPPPP.FF..',
        '..FFCCCCCCCCFF..',
        '..FFCCCCCCCCFF..',
        '..FFSSSSSSSSFF..',
        '..FFSSSSSSSSFF..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        P: { name: 'pillow', role: 'head' },
        C: { name: 'cushion', role: 'accessory' },
        S: { name: 'seat_base', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 12. MAGAZINE RACK — wooden display ─────────────────────
    {
      id: 'magazine_rack_16',
      description: 'Wooden magazine and newspaper rack with angled slots.',
      grid: [
        '................',
        '................',
        '..FFFFFFFFFFFF..',
        '..FM.MM.MM.MF...',
        '..FMMMMMMMMMF...',
        '..FFFFFFFFFFFF..',
        '..FM.MM.MM.MF...',
        '..FMMMMMMMMMF...',
        '..FFFFFFFFFFFF..',
        '..FM.MM.MM.MF...',
        '..FMMMMMMMMMF...',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        M: { name: 'magazines', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 13. DESK LAMP BRASS — articulated ──────────────────────
    {
      id: 'desk_lamp_brass_16',
      description: 'Brass articulated desk lamp with green glass shade.',
      grid: [
        '................',
        '................',
        '...SSSSSSS......',
        '..SSSSSSSSS.....',
        '..SSSGGGGSSS....',
        '..SSSSSSSSS.....',
        '...SSSSSSS......',
        '......AA........',
        '.......AA.......',
        '........AA......',
        '.........AA.....',
        '........AA......',
        '.......AAA......',
        '......BBBBBB....',
        '.....BBBBBBBB...',
        '................',
      ],
      chars: {
        S: { name: 'shade', role: 'head' },
        G: { name: 'bulb_glow', role: 'eye' },
        A: { name: 'arm_brass', role: 'accessory' },
        B: { name: 'base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. FILING CABINET — wooden with drawers ───────────────
    {
      id: 'filing_cabinet_16',
      description: 'Wooden filing cabinet with three deep drawers and brass pulls.',
      grid: [
        '..FFFFFFFFFFFF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FFFFFFFFFFFF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FFFFFFFFFFFF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FDDDDDDDDDHF..',
        '..FFFFFFFFFFFF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        D: { name: 'drawer_face', role: 'head' },
        H: { name: 'handle', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. WINDOW SEAT — bench with cushion ───────────────────
    {
      id: 'window_seat_16',
      description: 'Window seat bench with plush cushion and storage underneath.',
      grid: [
        '..WWWWWWWWWWWW..',
        '..WWGGGGGGGGWW..',
        '..WWGGGGGGGGWW..',
        '..WWGGGGGGGGWW..',
        '..WWGGGGGGGGWW..',
        '..WWWWWWWWWWWW..',
        '.FFFFFFFFFFFFFF.',
        '.FCCCCCCCCCCCCF.',
        '.FCCCCCCCCCCCCF.',
        '.FFFFFFFFFFFFFF.',
        '.FDDDDDDDDDDDDF.',
        '.FDDDDDDDDDDDDF.',
        '.FDDDDHHDDDDDDF.',
        '.FFFFFFFFFFFFFF.',
        '..FF........FF..',
        '................',
      ],
      chars: {
        W: { name: 'window_frame', role: 'belt' },
        G: { name: 'glass_pane', role: 'eye' },
        F: { name: 'seat_frame', role: 'body' },
        C: { name: 'cushion', role: 'accessory' },
        D: { name: 'storage_door', role: 'head' },
        H: { name: 'knob', role: 'arm' },
      },
      colors: {
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. SIDE TABLE — small with book on top ────────────────
    {
      id: 'side_table_16',
      description: 'Small wooden side table with a book and teacup resting on top.',
      grid: [
        '................',
        '................',
        '................',
        '......CC........',
        '.....CCCC.......',
        '...BBB..........',
        '...BRRBB........',
        '.FFFFFFFFFFFFFF.',
        '.FTTTTTTTTTTTTF.',
        '.FFFFFFFFFFFFFF.',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '..FFFF..FFFFF...',
        '................',
      ],
      chars: {
        C: { name: 'teacup', role: 'eye' },
        B: { name: 'book', role: 'accessory' },
        R: { name: 'bookmark', role: 'belt' },
        F: { name: 'table_frame', role: 'body' },
        T: { name: 'table_top', role: 'head' },
      },
      colors: {
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 17. PEDESTAL TABLE — round top ─────────────────────────
    {
      id: 'pedestal_table_16',
      description: 'Round wooden pedestal table with turned column base.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..TTTTTTTTTTTT..',
        '.TTTTTTTTTTTTTT.',
        '.FFFFFFFFFFFFFF.',
        '......FFFF......',
        '......PPPP......',
        '......PPPP......',
        '.....PPPPPP.....',
        '......PPPP......',
        '......PPPP......',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '................',
      ],
      chars: {
        T: { name: 'tabletop', role: 'head' },
        F: { name: 'apron', role: 'body' },
        P: { name: 'pedestal', role: 'accessory' },
        B: { name: 'base_feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 18. UMBRELLA STAND — ceramic by door ───────────────────
    {
      id: 'umbrella_stand_16',
      description: 'Ceramic umbrella stand with two umbrellas poking out.',
      grid: [
        '..UU......UU....',
        '..UU......UU....',
        '..UU......UU....',
        '..UU......UU....',
        '..UU......UU....',
        '..UU.HHHH.UU....',
        '...UHHHHHHU.....',
        '...HBBBBBBH.....',
        '...HBBPPBBH.....',
        '...HBBPPBBH.....',
        '...HBBBBBBH.....',
        '...HBBPPBBH.....',
        '...HBBBBBBH.....',
        '...HHHHHHHH.....',
        '....FFFFFF......',
        '................',
      ],
      chars: {
        U: { name: 'umbrellas', role: 'accessory' },
        H: { name: 'stand_rim', role: 'head' },
        B: { name: 'stand_body', role: 'body' },
        P: { name: 'pattern', role: 'eye' },
        F: { name: 'foot_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. MAP TABLE — large table with map ───────────────────
    {
      id: 'map_table_16',
      description: 'Large table with a parchment map spread across its surface.',
      grid: [
        '................',
        '................',
        '................',
        '.FFFFFFFFFFFFFF.',
        '.FMMMMMMMMMMMF..',
        '.FMMPMMMPMMMMF..',
        '.FMMMMMMMPMMMF..',
        '.FMMPMMMMMMMF...',
        '.FMMMMMMMMMMMF..',
        '.FFFFFFFFFFFFFF.',
        '.FF..........FF.',
        '.FF..........FF.',
        '.FF..........FF.',
        '.FF..........FF.',
        '.FF..........FF.',
        '................',
      ],
      chars: {
        F: { name: 'table_frame', role: 'body' },
        M: { name: 'map_parchment', role: 'head' },
        P: { name: 'map_marks', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 20. STUDY CHAIR — wooden with leather seat ─────────────
    {
      id: 'study_chair_16',
      description: 'Wooden study chair with leather padded seat and turned legs.',
      grid: [
        '................',
        '................',
        '..FF........FF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FBBBBBBBBBBF..',
        '..FFFFFFFFFFFF..',
        '.FFFFFFFFFFFFFF.',
        '.FLLLLLLLLLLLLF.',
        '.FLLLLLLLLLLLLF.',
        '.FFFFFFFFFFFFFF.',
        '..FF........FF..',
        '..FF........FF..',
        '..FF........FF..',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'body' },
        B: { name: 'backrest', role: 'head' },
        L: { name: 'leather_seat', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
