/**
 * Cozy Library Simulator batch 2 — 20 Books & Writing themed sprites.
 * Parchment tones, leather bindings, brass accents, ink blues.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'library',
  exportNames: { templates: 'LIBRARY_BATCH2_TEMPLATES', schemes: 'LIBRARY_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. BOOK OPEN — laying flat with visible pages ─────────────
    {
      id: 'book_open_16',
      description: 'Open book laying flat with visible page text lines and spine.',
      grid: [
        '................',
        '................',
        '..HPPPPSPPPPH...',
        '..HPPPPSPPPPH...',
        '..HPTTPSPTPPH...',
        '..HPPPPSPPPPH...',
        '..HPTTPSPTTPH...',
        '..HPPPPSPPPPH...',
        '..HPTTPSPTPPH...',
        '..HPPPPSPPPPH...',
        '..HPTTPSPTTPH...',
        '..HPPPPSPPPPH...',
        '..HPPPPSPPPPH...',
        '..HHHHHSHHHHHH..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cover', role: 'body' },
        P: { name: 'pages', role: 'head' },
        S: { name: 'spine', role: 'belt' },
        T: { name: 'text_lines', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 2. BOOK LEATHER — closed with clasp ───────────────────────
    {
      id: 'book_leather_16',
      description: 'Closed leather-bound book with decorative clasp and embossed cover.',
      grid: [
        '................',
        '................',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HBBDDBBH.....',
        '...HBBDDBBH.....',
        '...HBBDDBBH.....',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HBBBBBBHCC...',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...SSSSSSSS.....',
        '...HBBBBBBH.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'binding_edge', role: 'head' },
        B: { name: 'leather_cover', role: 'body' },
        D: { name: 'emboss_detail', role: 'accessory' },
        S: { name: 'page_edge', role: 'arm' },
        C: { name: 'clasp', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 3. BOOK ANCIENT — worn dusty tome ─────────────────────────
    {
      id: 'book_ancient_16',
      description: 'Very old dusty book with cracked cover and faded gold rune.',
      grid: [
        '................',
        '...HHHHHHHH.....',
        '...HBBBBBBH.....',
        '...HBBRRBBH.....',
        '...HBRRRRBH.....',
        '...HBRRRRBH.....',
        '...HBBRRBBH.....',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...HBBBBBBH.....',
        '...HHHHHHHH.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'worn_binding', role: 'head' },
        B: { name: 'aged_cover', role: 'body' },
        R: { name: 'faded_rune', role: 'accessory' },
        S: { name: 'yellowed_pages', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 4. INK WELL — glass inkwell with dark ink ─────────────────
    {
      id: 'ink_well_16',
      description: 'Glass inkwell with dark ink pool and light reflection.',
      grid: [
        '................',
        '................',
        '................',
        '......IIII......',
        '.....IIIIII.....',
        '....HHHHHHHH....',
        '....HGGGGGHH....',
        '...HHGGGGGHH....',
        '...HGGIIGGHH....',
        '...HGGIIGGHH....',
        '...HHGGGGGHH....',
        '....HGGGGGHH....',
        '....HHHHHHHH....',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        I: { name: 'ink_surface', role: 'eye' },
        H: { name: 'glass_rim', role: 'head' },
        G: { name: 'glass_body', role: 'body' },
        B: { name: 'base', role: 'boot' },
      },
      colors: {
        eye:  { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        head: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 5. QUILL PEN — feathered quill with ink tip ───────────────
    {
      id: 'quill_pen_16',
      description: 'Feathered quill pen with ink-stained nib and barbed vane.',
      grid: [
        '..............FF',
        '.............FFF',
        '............FFFF',
        '...........FFFV.',
        '..........FFF...',
        '.........FFFV...',
        '........FFF.....',
        '.......SSS......',
        '......SSS.......',
        '.....SSS........',
        '....SSS.........',
        '...SSS..........',
        '..NNN...........',
        '.NNN............',
        '.II.............',
        '................',
      ],
      chars: {
        F: { name: 'feather_vane', role: 'body' },
        V: { name: 'feather_barb', role: 'accessory' },
        S: { name: 'shaft', role: 'head' },
        N: { name: 'nib', role: 'arm' },
        I: { name: 'ink_tip', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
      },
    },

    // ─── 6. WAX SEAL STAMP — brass stamp with handle ───────────────
    {
      id: 'wax_seal_stamp_16',
      description: 'Brass wax seal stamp with turned wood handle and flat die face.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '.....HHHH.......',
        '.....HHHH.......',
        '....HHHHHH......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '...SSSSSSSS.....',
        '...BBBBBBBB.....',
        '...BBDDDDBB.....',
        '...BBDDDDBB.....',
        '...BBBBBBBB.....',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'head' },
        S: { name: 'shaft', role: 'body' },
        B: { name: 'stamp_base', role: 'arm' },
        D: { name: 'die_pattern', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 7. PARCHMENT SCROLL — rolled with ribbon tie ──────────────
    {
      id: 'parchment_scroll_16',
      description: 'Rolled parchment scroll with red ribbon tie and curled ends.',
      grid: [
        '................',
        '..RRRRRRRRRRR...',
        '..RPPPPPPPPPR...',
        '..RPTTTTTTPR....',
        '..RPPPPPPPPR....',
        '..RPTTTTTTPR....',
        '..RPPPPPPPPR....',
        '..RPTTTTTTPR....',
        '..RPPPPPPPPR....',
        '..RPPPPPPPPPR...',
        '..RRRRRRRRRRR...',
        '......CC........',
        '.....CCCC.......',
        '......CC........',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'scroll_roll', role: 'head' },
        P: { name: 'parchment', role: 'body' },
        T: { name: 'text_lines', role: 'accessory' },
        C: { name: 'ribbon', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 8. ANTIQUE MAP — aged map with compass rose ───────────────
    {
      id: 'antique_map_16',
      description: 'Aged map with torn edges, compass rose detail, and faded landmass.',
      grid: [
        '................',
        '..BBBBBBBBBB....',
        '..BPPPPPPPPB....',
        '..BPPLLPPPPPB...',
        '..BPLLLLPPPPB...',
        '..BPPLLLPPPPB...',
        '..BPPPPPPPPB....',
        '..BPPPCCPPPB....',
        '..BPPPCCCPPB....',
        '..BPPPCCPPPB....',
        '..BPPPPPPPPB....',
        '..BPPPPPPPPB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'map_border', role: 'head' },
        P: { name: 'parchment', role: 'body' },
        L: { name: 'landmass', role: 'accessory' },
        C: { name: 'compass_rose', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 9. READING GLASSES — round spectacles ─────────────────────
    {
      id: 'reading_glasses_16',
      description: 'Round spectacles with wire frames and thin temple arms.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.FFFF..FFFF.....',
        'FGGGFBBFGGGF....',
        'FGLLF..FGLLF....',
        'FGGGF..FGGGF....',
        '.FFFF..FFFF.....',
        'T..........T....',
        '.TT......TT.....',
        '...TTTTTT.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'head' },
        G: { name: 'lens', role: 'body' },
        L: { name: 'lens_glare', role: 'eye' },
        B: { name: 'bridge', role: 'accessory' },
        T: { name: 'temple_arms', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. MAGNIFYING GLASS — brass frame ────────────────────────
    {
      id: 'magnifying_glass_library_16',
      description: 'Magnifying glass with brass rim and wooden handle.',
      grid: [
        '................',
        '....RRRRRR......',
        '...RRGGGGRRR....',
        '..RRGGGGGGRRR...',
        '..RGGGLLGGGRR...',
        '..RGGGLLGGGRR...',
        '..RRGGGGGGRRR...',
        '...RRGGGGRRR....',
        '....RRRRRR......',
        '.......HH.......',
        '........HH......',
        '.........HH.....',
        '..........HH....',
        '...........HH...',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'brass_rim', role: 'head' },
        G: { name: 'glass_lens', role: 'body' },
        L: { name: 'light_glare', role: 'eye' },
        H: { name: 'handle', role: 'arm' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:  { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 11. NEWSPAPER FOLDED — folded newspaper ───────────────────
    {
      id: 'newspaper_folded_16',
      description: 'Folded newspaper with headline text and column layout.',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBB....',
        '..BPPPPPPPPB....',
        '..BPTTTTTTPB....',
        '..BPTTTTTTPB....',
        '..BPPPPPPPPB....',
        '..BPTPPTPPTPB...',
        '..BPTPPTPPTPB...',
        '..BPTPPTPPTPB...',
        '..BPPPPPPPPB....',
        '..BBBBBBBBBB....',
        '..BSSSSSSSSB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'paper_edge', role: 'head' },
        P: { name: 'paper', role: 'body' },
        T: { name: 'text_ink', role: 'accessory' },
        S: { name: 'fold_shadow', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 12. MANUSCRIPT PAGE — loose page with text ────────────────
    {
      id: 'manuscript_page_16',
      description: 'Loose manuscript page with handwritten text lines and ink blot.',
      grid: [
        '................',
        '..BBBBBBBBB.....',
        '..BPPPPPPPB.....',
        '..BPTTTTTPB.....',
        '..BPPPPPPPB.....',
        '..BPTTTTTPB.....',
        '..BPPPPPPPB.....',
        '..BPTTTTTPB.....',
        '..BPPPPPPPB.....',
        '..BPTTTPPPB.....',
        '..BPPPIIPPB.....',
        '..BPPPIPPB......',
        '..BPPPPPPPB.....',
        '..BBBBBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'page_edge', role: 'head' },
        P: { name: 'parchment', role: 'body' },
        T: { name: 'handwriting', role: 'accessory' },
        I: { name: 'ink_blot', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 13. BOOK STACK SMALL — 3 books stacked ────────────────────
    {
      id: 'book_stack_small_16',
      description: 'Small stack of three colorful books with visible page edges.',
      grid: [
        '................',
        '................',
        '................',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '..SSSSSSSSSSSS..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..SSSSSSSSSSSS..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..SSSSSSSSSSSS..',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'book_red', role: 'head' },
        B: { name: 'book_green', role: 'body' },
        C: { name: 'book_blue', role: 'arm' },
        S: { name: 'page_edges', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. JOURNAL LEATHER — personal journal with strap ─────────
    {
      id: 'journal_leather_16',
      description: 'Personal leather journal with wrap-around strap and bookmark ribbon.',
      grid: [
        '................',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HSSSSSSHR....',
        '...HBBBBBBHR....',
        '...HBBBBBBHR....',
        '...HBBBBBBH.....',
        '...HSSSSSSHR....',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...PPPPPPPP.....',
        '...HBBBBBBH.....',
        '...HHHHHHHH.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'binding', role: 'head' },
        B: { name: 'leather', role: 'body' },
        S: { name: 'strap', role: 'belt' },
        P: { name: 'page_edge', role: 'arm' },
        R: { name: 'bookmark', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. ENVELOPE SEALED — letter with wax seal ────────────────
    {
      id: 'envelope_sealed_16',
      description: 'Sealed letter envelope with triangular flap and red wax seal.',
      grid: [
        '................',
        '................',
        '................',
        '..BBBBBBBBBB....',
        '..BFFFFFFFB.....',
        '..BBFFFFFBB.....',
        '..BBBFFFBBB.....',
        '..BBBBWBBBB.....',
        '..BPPPWPPPB.....',
        '..BPPPWPPPB.....',
        '..BPPWWWPPB.....',
        '..BPPPPPPPB.....',
        '..BPPPPPPPB.....',
        '..BBBBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'envelope_edge', role: 'head' },
        F: { name: 'flap', role: 'body' },
        P: { name: 'paper_front', role: 'arm' },
        W: { name: 'wax_seal', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 16. CALLIGRAPHY SET — pen and ink set ─────────────────────
    {
      id: 'calligraphy_set_16',
      description: 'Calligraphy pen resting on ink stone with brush holder.',
      grid: [
        '..............PP',
        '.............PPP',
        '............PPP.',
        '...........PPP..',
        '..........NNN...',
        '.........NNN....',
        '................',
        '...HHHHHHHHHH...',
        '...HIIIIIIIIH...',
        '...HIIIIIIIIH...',
        '...HHHHHHHHHH...',
        '....BBBB..BBBB..',
        '....BRRB..BRRB..',
        '....BRRB..BRRB..',
        '....BBBB..BBBB..',
        '................',
      ],
      chars: {
        P: { name: 'pen_shaft', role: 'body' },
        N: { name: 'pen_nib', role: 'arm' },
        H: { name: 'inkstone_rim', role: 'head' },
        I: { name: 'ink_pool', role: 'eye' },
        B: { name: 'brush_holder', role: 'belt' },
        R: { name: 'brush_tips', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#442434' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 17. BOOK RED — red hardcover standing upright ─────────────
    {
      id: 'book_red_16',
      description: 'Red hardcover book standing upright with gold title stripe.',
      grid: [
        '................',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBGGBB....',
        '....SSBBGGBB....',
        '....SSBBGGBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....SSBBBBBB....',
        '....HHHHHHHH....',
        '................',
      ],
      chars: {
        S: { name: 'spine', role: 'head' },
        B: { name: 'cover', role: 'body' },
        G: { name: 'title_stripe', role: 'accessory' },
        H: { name: 'bottom_edge', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. BOOK BLUE — blue hardcover laying on side ─────────────
    {
      id: 'book_blue_16',
      description: 'Blue hardcover book laying on its side with page edges visible.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBGGBBBBH..',
        '..HBBBBGGBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..SSSSSSSSSSSS..',
        '..HBBBBBBBBBBH..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'binding', role: 'head' },
        B: { name: 'cover', role: 'body' },
        G: { name: 'gold_emblem', role: 'accessory' },
        S: { name: 'page_edges', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. DICTIONARY THICK — thick encyclopedia ─────────────────
    {
      id: 'dictionary_thick_16',
      description: 'Thick dictionary or encyclopedia with tabbed page markers.',
      grid: [
        '................',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HBBGGGGBBH....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBHT...',
        '..HBBBBBBBBH....',
        '..SSSSSSSSSS....',
        '..SSSSSSSSSS....',
        '..SSSSSSSSSSST..',
        '..SSSSSSSSSS....',
        '..SSSSSSSSSS....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBHT...',
        '..HHHHHHHHHH....',
        '................',
      ],
      chars: {
        H: { name: 'cover', role: 'head' },
        B: { name: 'front_cover', role: 'body' },
        G: { name: 'title_text', role: 'accessory' },
        S: { name: 'page_block', role: 'arm' },
        T: { name: 'tab_markers', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. SCROLL CASE — cylindrical carrying case ───────────────
    {
      id: 'scroll_case_16',
      description: 'Cylindrical leather scroll carrying case with brass end caps.',
      grid: [
        '................',
        '................',
        '...CCCCCCCC.....',
        '...CCCCCCCC.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBSSBBB.....',
        '...BBBSSBBB.....',
        '...BBBSSBBB.....',
        '...BBBSSBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...CCCCCCCC.....',
        '...CCCCCCCC.....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'brass_cap', role: 'head' },
        B: { name: 'leather_tube', role: 'body' },
        S: { name: 'strap_buckle', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

  ],
};

export default batch;
