/**
 * Library batch 3 — 20 Cozy Library Simulator decor & curiosities.
 * Globes, telescopes, curio cabinets, music boxes, crystal balls, etc.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'library',
  exportNames: { templates: 'LIBRARY_BATCH3_TEMPLATES', schemes: 'LIBRARY_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. GLOBE DESK ─────────────────────────────────────────────
    {
      id: 'globe_desk_16',
      description: 'Decorative desk globe on brass stand with meridian ring.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '....RGGGGGGR....',
        '...RGGLGGLGGR...',
        '...RGGGGGGGGR...',
        '...RGGLGGLGGR...',
        '...RGGGGGGGGR...',
        '....RGGGGGGR....',
        '.....RRRRRR.....',
        '.......BB.......',
        '.......BB.......',
        '......BBBB......',
        '.....SSSSSS.....',
        '....SSSSSSSS....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'meridian_ring', role: 'accessory' },
        G: { name: 'globe_surface', role: 'body' },
        L: { name: 'land_masses', role: 'eye' },
        B: { name: 'brass_post', role: 'head' },
        S: { name: 'stand_base', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. TELESCOPE DESK ──────────────────────────────────────────
    {
      id: 'telescope_desk_16',
      description: 'Small brass telescope on tripod stand.',
      grid: [
        '................',
        '.LLLLLL.........',
        '..LBBBBBBBB.....',
        '...LBBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBBB....',
        '......BBBBHH....',
        '.......BBHH.....',
        '........HH......',
        '.......TTTT.....',
        '......TT..TT....',
        '.....TT....TT...',
        '....TT......TT..',
        '...FF........FF.',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lens_hood', role: 'eye' },
        B: { name: 'barrel', role: 'body' },
        H: { name: 'eyepiece', role: 'head' },
        T: { name: 'tripod_legs', role: 'arm' },
        F: { name: 'feet_pads', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. WALL MAP FRAMED ─────────────────────────────────────────
    {
      id: 'wall_map_framed_16',
      description: 'Framed antique map on wall with parchment tones.',
      grid: [
        '................',
        '.FFFFFFFFFFFF...',
        '.FMMMMMMMMMMF...',
        '.FMLLMMMLLMMF...',
        '.FMMMMMMMMMMF...',
        '.FMMMLLMMMMF....',
        '.FMMMMMMMMMMF...',
        '.FMLLMMMLLMMF...',
        '.FMMMMMMMMMMF...',
        '.FMMMMMMMMMMF...',
        '.FFFFFFFFFFFF...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame', role: 'head' },
        M: { name: 'parchment', role: 'body' },
        L: { name: 'land_detail', role: 'eye' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. CURIO CABINET ───────────────────────────────────────────
    {
      id: 'curio_cabinet_16',
      description: 'Glass-front display cabinet with shelves and curiosities.',
      grid: [
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBGGGGGGGGGGBB.',
        '.BBGIIGGGGIIGGBB',
        '.BBGGGGGGGGGGBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBGGGGGGGGGGBB.',
        '.BBGGIIIIIIGGBB.',
        '.BBGGGGGGGGGGBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBGGGGGGGGGGBB.',
        '.BBGGIIGGIIGBB..',
        '.BBGGGGGGGGGGBB.',
        '.BBBBBBBBBBBBBB.',
        '.FF..........FF.',
        '................',
      ],
      chars: {
        B: { name: 'cabinet_frame', role: 'body' },
        G: { name: 'glass_panels', role: 'eye' },
        I: { name: 'display_items', role: 'accessory' },
        F: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. CANDLESTICK BRASS ───────────────────────────────────────
    {
      id: 'candlestick_brass_16',
      description: 'Tall brass candlestick with lit candle and wax drip.',
      grid: [
        '......FF........',
        '......FF........',
        '.....CCCC.......',
        '.....CCCC.......',
        '.....CWCC.......',
        '.....CCCC.......',
        '.....CCCC.......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....BBBBBB......',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '................',
      ],
      chars: {
        F: { name: 'flame', role: 'accessory' },
        C: { name: 'candle_wax', role: 'head' },
        W: { name: 'wax_drip', role: 'eye' },
        B: { name: 'brass_stem', role: 'body' },
        S: { name: 'base_plate', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. RUG ROUND LIBRARY ───────────────────────────────────────
    {
      id: 'rug_round_library_16',
      description: 'Round decorative library rug with ornate border pattern.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....BBBBBB.....',
        '...BBBPPPBBBB...',
        '..BBPPIIIPPPBB..',
        '..BPPIIIIIPPBB..',
        '..BPPIIIIIPPBB..',
        '..BBPPIIIPPPBB..',
        '...BBBPPPBBBB...',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'border_ring', role: 'body' },
        P: { name: 'inner_pattern', role: 'head' },
        I: { name: 'center_field', role: 'eye' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 7. CURTAIN HEAVY ───────────────────────────────────────────
    {
      id: 'curtain_heavy_16',
      description: 'Heavy velvet curtain pulled to side with tassel tie-back.',
      grid: [
        'RRRRRRRRRRRRRRRR',
        'RRRRRRRRRRRRRRRR',
        'CCCCCCCCCC......',
        '.CCCCCCCCC......',
        '.CCCCCCCCC......',
        '..CCCCCCCC......',
        '..CCCCCCCC......',
        '..CCTTCCCC......',
        '..CCTTCCCC......',
        '...CCCCCCC......',
        '...CCCCCCC......',
        '...CCCCCCC......',
        '....CCCCCC......',
        '....CCCCCC......',
        '....CCCCCC......',
        '....CCCCCC......',
      ],
      chars: {
        R: { name: 'curtain_rod', role: 'head' },
        C: { name: 'curtain_fabric', role: 'body' },
        T: { name: 'tassel_tieback', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 8. WINDOW LIBRARY ──────────────────────────────────────────
    {
      id: 'window_library_16',
      description: 'Lattice window with warm light streaming through panes.',
      grid: [
        '.FFFFFFFFFFFF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FFFFFFFFFFFF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FFFFFFFFFFFF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FLLLFLLLFLLF...',
        '.FFFFFFFFFFFF...',
        '.SSSSSSSSSSSS...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'frame_lattice', role: 'body' },
        L: { name: 'light_panes', role: 'eye' },
        S: { name: 'window_sill', role: 'head' },
      },
      colors: {
        body: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. POTTED FERN ─────────────────────────────────────────────
    {
      id: 'potted_fern_16',
      description: 'Large fern plant in terracotta clay pot.',
      grid: [
        '....GG..GG......',
        '...GGG.GGGG.....',
        '..GGGG.GGGGG....',
        '..GGGGGGGGGGG...',
        '...GGGGGGGGG....',
        '..GGGGGGGGGGG...',
        '...GGGGGGGGG....',
        '....GGGGGGG.....',
        '....PPPPPPP.....',
        '....PBBBBPP.....',
        '....PBBBBPP.....',
        '....PBBBBPP.....',
        '....PPPPPP......',
        '.....SSSS.......',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'fern_fronds', role: 'eye' },
        P: { name: 'pot_rim', role: 'head' },
        B: { name: 'pot_body', role: 'body' },
        S: { name: 'saucer', role: 'accessory' },
      },
      colors: {
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 10. PORTRAIT FRAME ─────────────────────────────────────────
    {
      id: 'portrait_frame_16',
      description: 'Ornate hanging portrait in gold frame with painted figure.',
      grid: [
        '......CC........',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..FFPPPPPPPPFF..',
        '..FFPPPPPPPPFF..',
        '..FFPPHHHHPPFF..',
        '..FFPPHEEHPPFF..',
        '..FFPPHHHHPPFF..',
        '..FFPPBBBBPPFF..',
        '..FFPPBBBBPPFF..',
        '..FFPPPPPPPPFF..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'hanging_wire', role: 'arm' },
        F: { name: 'gold_frame', role: 'head' },
        P: { name: 'canvas_bg', role: 'body' },
        H: { name: 'portrait_face', role: 'eye' },
        B: { name: 'portrait_body', role: 'accessory' },
        E: { name: 'portrait_eyes', role: 'belt' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 11. TROPHY CUP ────────────────────────────────────────────
    {
      id: 'trophy_cup_16',
      description: 'Small engraved trophy cup on pedestal.',
      grid: [
        '................',
        '................',
        '...HBBBBBBH.....',
        '...HBBBBBBH.....',
        '...HBBEEBBH.....',
        '...HBBBBBBH.....',
        '....HBBBBH......',
        '.....HBBH.......',
        '......BB........',
        '......BB........',
        '......BB........',
        '.....SSSS.......',
        '....SSSSSS......',
        '...SSSSSSSS.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cup_body', role: 'body' },
        H: { name: 'handles', role: 'head' },
        E: { name: 'engraving', role: 'eye' },
        S: { name: 'pedestal', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. LETTER OPENER ──────────────────────────────────────────
    {
      id: 'letter_opener_16',
      description: 'Ornate brass letter opener with jeweled handle.',
      grid: [
        '................',
        '................',
        '................',
        '..BB............',
        '...BBB..........',
        '....BBBB........',
        '.....BBBBB......',
        '......BBBBB.....',
        '.......HHHH.....',
        '........HHHH....',
        '.........HGHH...',
        '..........HHH...',
        '...........HH...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'blade', role: 'body' },
        H: { name: 'handle', role: 'head' },
        G: { name: 'jewel_inlay', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. HOURGLASS DESK ─────────────────────────────────────────
    {
      id: 'hourglass_desk_16',
      description: 'Sand hourglass on wooden frame, sand flowing.',
      grid: [
        '................',
        '...FFFFFFFFFFF..',
        '...FGGGGGGGFF...',
        '....FGGGGGF.....',
        '.....FGGGF......',
        '......FGF.......',
        '.......F........',
        '......FGF.......',
        '.....FGGGF......',
        '....FGGGGGF.....',
        '...FSSSSSSSFF...',
        '...FFFFFFFFFFF..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'wood_frame', role: 'body' },
        G: { name: 'glass_bulbs', role: 'eye' },
        S: { name: 'sand_pile', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. COMPASS BRASS ──────────────────────────────────────────
    {
      id: 'compass_brass_16',
      description: 'Brass navigation compass, open lid, needle visible.',
      grid: [
        '................',
        '................',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '..LLLLLLLLLL....',
        '..LLLLLLLLLL....',
        '..RRRRRRRRRR....',
        '..RBBBBBBBBR....',
        '..RBBBNBNBBR....',
        '..RBBBBBBBBR....',
        '..RBBNBNBBBR....',
        '..RBBBBBBBBR....',
        '..RRRRRRRRRR....',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lid', role: 'head' },
        R: { name: 'rim_case', role: 'body' },
        B: { name: 'compass_face', role: 'eye' },
        N: { name: 'needle_marks', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. MUSIC BOX ──────────────────────────────────────────────
    {
      id: 'music_box_library_16',
      description: 'Open music box with spinning mechanism and velvet lining.',
      grid: [
        '................',
        '..LLLLLLLLLL....',
        '..LLLLLLLLLL....',
        '..LLVVVVVVLL....',
        '..LLVVVVVVLL....',
        '..LLLLLLLLLL....',
        '..BBBBBBBBBBBB..',
        '..BBVVVVVVVVBB..',
        '..BBVVMMVVVVBB..',
        '..BBVVVVMMVVBB..',
        '..BBVVVVVVVVBB..',
        '..BBBBBBBBBBBB..',
        '..FF........FF..',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'lid', role: 'head' },
        B: { name: 'box_body', role: 'body' },
        V: { name: 'velvet_lining', role: 'eye' },
        M: { name: 'mechanism', role: 'accessory' },
        F: { name: 'feet', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. SNOW GLOBE ─────────────────────────────────────────────
    {
      id: 'snow_globe_library_16',
      description: 'Decorative snow globe with miniature scene inside.',
      grid: [
        '................',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '...GGGSSSSGGG...',
        '...GGGSSSSSGGG..',
        '...GGGGSSGGGGG..',
        '...GGDDDDDDGG...',
        '....GGDDDDGG....',
        '.....GGGGGG.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'glass_dome', role: 'eye' },
        S: { name: 'snow_flakes', role: 'accessory' },
        D: { name: 'scene_inside', role: 'head' },
        B: { name: 'wooden_base', role: 'body' },
      },
      colors: {
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. CRYSTAL BALL ───────────────────────────────────────────
    {
      id: 'crystal_ball_library_16',
      description: 'Fortune teller crystal ball on ornate metal stand.',
      grid: [
        '................',
        '................',
        '.....CCCCCC.....',
        '....CCCCCCCC....',
        '...CCCCMMCCCC...',
        '...CCCCMMCCCC...',
        '...CCCCCCCCCC...',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '......SSSS......',
        '.....SSSSSS.....',
        '....SSBBBBSS....',
        '...SSBBBBBBSS...',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'crystal_orb', role: 'eye' },
        M: { name: 'mystic_glow', role: 'accessory' },
        S: { name: 'stand_arms', role: 'head' },
        B: { name: 'base_plate', role: 'body' },
      },
      colors: {
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 18. SHIP MODEL ─────────────────────────────────────────────
    {
      id: 'ship_model_16',
      description: 'Miniature ship model on wooden desk stand.',
      grid: [
        '......MM........',
        '......MM........',
        '....MMMMSS......',
        '....MMMMSS......',
        '......MM........',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '.BBBBBBBBBBBBB..',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '................',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'mast_rigging', role: 'arm' },
        S: { name: 'sails', role: 'eye' },
        B: { name: 'hull', role: 'body' },
        H: { name: 'hull_keel', role: 'head' },
        F: { name: 'display_stand', role: 'accessory' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. CLOCK MANTLE ───────────────────────────────────────────
    {
      id: 'clock_mantle_16',
      description: 'Small mantle clock with round face and wooden case.',
      grid: [
        '................',
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBFFFFFFBB...',
        '...BFFFCCFFFB...',
        '...BFFCCCFFB....',
        '...BFFFCCFFFB...',
        '...BBFFFFFFBB...',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '..FF........FF..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'wood_case', role: 'body' },
        F: { name: 'clock_face', role: 'eye' },
        C: { name: 'clock_hands', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 20. CANDELABRA ORNATE ──────────────────────────────────────
    {
      id: 'candelabra_ornate_16',
      description: 'Ornate 3-branch candelabra with lit candles.',
      grid: [
        '..FF...FF...FF..',
        '..CC...CC...CC..',
        '..CC...CC...CC..',
        '..CC...CC...CC..',
        '..BB...BB...BB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....SSSSSS.....',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'flames', role: 'accessory' },
        C: { name: 'candles', role: 'head' },
        B: { name: 'brass_arms', role: 'body' },
        S: { name: 'base_stand', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
