/**
 * Mangaka Simulator batch 5 — 20 mangaka lifestyle snacks, drinks & accessories.
 * Focus: convenience store food, comfort drinks, desk accessories, and cozy items
 * that surround a working mangaka during long late-night drawing sessions.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'MANGAKA_BATCH5_TEMPLATES', schemes: 'MANGAKA_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ─── 1. ENERGY DRINK CAN ────────────────────────────────────────
    // Tall slim can — metallic body, bold label band, pull tab on top
    {
      id: 'energy_drink_can_mg_16',
      description: 'Tall energy drink can with metallic finish, bold label band, and pull tab on top.',
      grid: [
        '................',
        '......TTTT......',
        '.....TTPPTT.....',
        '.....CCCCCC.....',
        '.....CCCCCC.....',
        '.....LLLLLL.....',
        '.....LLLLLL.....',
        '.....LLDDLL.....',
        '.....LLDDLL.....',
        '.....LLLLLL.....',
        '.....LLLLLL.....',
        '.....CCCCCC.....',
        '.....CCCCCC.....',
        '.....CCCCCC.....',
        '......SSSS......',
        '................',
      ],
      chars: {
        T: { name: 'can_top', role: 'head' },
        P: { name: 'pull_tab', role: 'eye' },
        C: { name: 'can_body', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        D: { name: 'label_logo', role: 'belt' },
        S: { name: 'can_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:   { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 2. COFFEE CUP KONBINI ──────────────────────────────────────
    // Paper cup with sleeve, plastic lid, steam wisps
    {
      id: 'coffee_cup_konbini_mg_16',
      description: 'Convenience store hot coffee cup with paper sleeve, brown lid, and steam wisps.',
      grid: [
        '................',
        '.....SSSSSS.....',
        '......SSSS......',
        '.....LLLLLL.....',
        '.....LLLLLL.....',
        '....CCCCCCCC....',
        '....CCCCCCCC....',
        '....CWWWWWWC....',
        '....CWWWWWWC....',
        '....CWWWWWWC....',
        '....CWWWWWWC....',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '.....CCCCCC.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        L: { name: 'plastic_lid', role: 'head' },
        C: { name: 'cup_body', role: 'body' },
        W: { name: 'paper_sleeve', role: 'arm' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 3. TEA BOTTLE PET ──────────────────────────────────────────
    // PET bottle with green tea, label wrap, white cap
    {
      id: 'tea_bottle_pet_mg_16',
      description: 'PET bottle of green tea with green label wrap, white cap, and visible tea level.',
      grid: [
        '................',
        '.......CC.......',
        '.......CC.......',
        '......NNNN......',
        '......NNNN......',
        '.....LLLLLL.....',
        '.....LLDDLL.....',
        '.....LLDDLL.....',
        '.....LLLLLL.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'head' },
        N: { name: 'bottle_neck', role: 'eye' },
        L: { name: 'label_wrap', role: 'arm' },
        D: { name: 'label_text', role: 'belt' },
        B: { name: 'tea_body', role: 'body' },
        T: { name: 'bottle_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:  { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        body:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. ONIGIRI KONBINI ─────────────────────────────────────────
    // Wrapped konbini onigiri with plastic wrapper and pull tab
    {
      id: 'onigiri_konbini_mg_16',
      description: 'Convenience store onigiri in plastic wrapper with pull tab and nori visible through wrap.',
      grid: [
        '................',
        '................',
        '.......PP.......',
        '......PPPP......',
        '.....WWWWWW.....',
        '....WWWWWWWW....',
        '....WWWWWWWW....',
        '...WWWWRRWWWW...',
        '...WWWWWWWWWW...',
        '...WWWWWWWWWW...',
        '..WWNNNNNNNWW...',
        '..WWNNNNNNNWW...',
        '..WWNNNNNNNWW...',
        '..WWNNNNNNNWW...',
        '...NNNNNNNNNN...',
        '................',
      ],
      chars: {
        P: { name: 'pull_tab', role: 'eye' },
        W: { name: 'plastic_wrap', role: 'body' },
        R: { name: 'rice_peek', role: 'head' },
        N: { name: 'nori_wrap', role: 'arm' },
      },
      colors: {
        eye:   { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 5. CUP NOODLE ─────────────────────────────────────────────
    // Instant noodle cup with peeled lid and noodles visible
    {
      id: 'cup_noodle_mg_16',
      description: 'Instant cup noodle with peeled-back foil lid, noodles visible, and branded cup body.',
      grid: [
        '..LLLLLLLL......',
        '..LLLLLLLLL.....',
        '...LLLLLLLL.....',
        '....NNNNNNNN....',
        '....NNNNNNNN....',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCDDCCDDCC...',
        '...CCCCCCCCCC...',
        '...CCCCCCCCCC...',
        '...CCDDCCDDCC...',
        '...CCCCCCCCCC...',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        L: { name: 'foil_lid', role: 'accessory' },
        N: { name: 'noodles_top', role: 'head' },
        C: { name: 'cup_body', role: 'body' },
        D: { name: 'cup_design', role: 'arm' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 6. POCKY BOX ───────────────────────────────────────────────
    // Tall slim snack box, open top with sticks peeking out
    {
      id: 'pocky_box_mg_16',
      description: 'Pocky-style snack box, open top with chocolate-coated sticks peeking out.',
      grid: [
        '................',
        '....SS.SS.SS....',
        '....SS.SS.SS....',
        '....SS.SS.SS....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BLLLLLLLLB...',
        '...BLLLLLLLLB...',
        '...BLDDDDDDLB...',
        '...BLDDDDDDLB...',
        '...BLLLLLLLLB...',
        '...BLLLLLLLLB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        S: { name: 'pocky_sticks', role: 'head' },
        B: { name: 'box_body', role: 'body' },
        L: { name: 'box_label', role: 'arm' },
        D: { name: 'label_design', role: 'belt' },
        T: { name: 'box_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 7. RICE BALL PLATE ─────────────────────────────────────────
    // Two rice balls on a flat ceramic plate
    {
      id: 'rice_ball_plate_mg_16',
      description: 'Two rice balls on a ceramic plate, one with sesame and one with nori wrap.',
      grid: [
        '................',
        '................',
        '....RRR..RRR....',
        '...RRRRR.RRRRR..',
        '...RRRRR.RRRRR..',
        '...RRSRR.RRRRR..',
        '..RRRRRR.RRRRR..',
        '..RRRRRRNNNRRR..',
        '..RRRRRRNNNRRR..',
        '..RRRRRRNNNRRR..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rice_surface', role: 'head' },
        S: { name: 'sesame_seeds', role: 'eye' },
        N: { name: 'nori_strip', role: 'belt' },
        P: { name: 'plate_surface', role: 'body' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:  { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        body:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. BENTO BOX ───────────────────────────────────────────────
    // Open bento with dividers showing rice, meat, veggies
    {
      id: 'bento_box_mg_16',
      description: 'Packed bento lunch box with rice section, meat section, and vegetable section.',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BRRRRRDDDDDB..',
        '..BRRRRRDDDDDB..',
        '..BRRRRRDDDDDB..',
        '..BRRSRRDDMDDB..',
        '..BRRRRRDDDDDB..',
        '..BBBBBBBBBBBB..',
        '..BGGGGGVVVVVB..',
        '..BGGGGGVVVVVB..',
        '..BGGGGGVVVVVB..',
        '..BBBBBBBBBBBB..',
        '..WWWWWWWWWWWW..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'box_frame', role: 'body' },
        R: { name: 'rice_section', role: 'head' },
        S: { name: 'umeboshi_center', role: 'eye' },
        D: { name: 'meat_section', role: 'arm' },
        M: { name: 'meat_glaze', role: 'belt' },
        G: { name: 'veggie_greens', role: 'leg' },
        V: { name: 'veggie_pickles', role: 'accessory' },
        W: { name: 'box_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. CANDY BAG ───────────────────────────────────────────────
    // Crinkly bag of hard candies with twist-tied top
    {
      id: 'candy_bag_mg_16',
      description: 'Clear bag of colorful hard candies with twist-tied top and label tag.',
      grid: [
        '................',
        '................',
        '.....TTTT.......',
        '......TT........',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BCBCBCBBB....',
        '...BBBCBCBBB....',
        '...BCBBBBCBB....',
        '...BBBCBBBBB....',
        '...BCBCBCBBB....',
        '...BBBBBBBBB....',
        '...BBBBBBBB.....',
        '....LLLLLL......',
        '.....SSSS.......',
        '................',
      ],
      chars: {
        T: { name: 'twist_tie', role: 'eye' },
        B: { name: 'bag_plastic', role: 'body' },
        C: { name: 'candy_pieces', role: 'head' },
        L: { name: 'bag_label', role: 'arm' },
        S: { name: 'bag_base', role: 'boot' },
      },
      colors: {
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 10. CHIP BAG ───────────────────────────────────────────────
    // Puffy chip bag with bold label design and sealed top
    {
      id: 'chip_bag_mg_16',
      description: 'Puffy potato chip bag with bold label design and sealed crinkle top.',
      grid: [
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BLLLLLLLLB...',
        '...BLLDDDDLLB...',
        '...BLLDDDDLLB...',
        '...BLLDDDDLLB...',
        '...BLLLLLLLLB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        S: { name: 'sealed_top', role: 'head' },
        B: { name: 'bag_body', role: 'body' },
        L: { name: 'label_area', role: 'arm' },
        D: { name: 'label_design', role: 'belt' },
        T: { name: 'bag_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#597dce' },
      },
    },

    // ─── 11. WRIST REST ─────────────────────────────────────────────
    // Ergonomic rectangular pad with rounded edges and fabric texture
    {
      id: 'wrist_rest_mg_16',
      description: 'Ergonomic gel wrist rest pad with soft fabric cover and rounded profile.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '.FFFFFFFFFFFF...',
        '.FFFFFFEFFFFF...',
        '.FFFFFFFFFFFF...',
        '.GGGGGGGGGGGG...',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...SSSSSSSS.....',
        '................',
      ],
      chars: {
        F: { name: 'fabric_top', role: 'body' },
        E: { name: 'fabric_stitch', role: 'eye' },
        G: { name: 'gel_side', role: 'arm' },
        B: { name: 'rubber_base', role: 'head' },
        S: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:   { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:  { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 12. HAND CREAM ─────────────────────────────────────────────
    // Squeeze tube with flip cap, pastel label, cream at nozzle
    {
      id: 'hand_cream_mg_16',
      description: 'Hand cream squeeze tube with flip cap, pastel label, and cream visible at nozzle.',
      grid: [
        '................',
        '................',
        '.......CC.......',
        '.......CC.......',
        '......CCCC......',
        '......NNNN......',
        '.....TTTTTT.....',
        '.....TLLLLT.....',
        '.....TLDDLT.....',
        '.....TLDDLT.....',
        '.....TLLLLT.....',
        '.....TTTTTT.....',
        '.....TTTTTT.....',
        '......BBBB......',
        '.......SS.......',
        '................',
      ],
      chars: {
        C: { name: 'flip_cap', role: 'head' },
        N: { name: 'cream_nozzle', role: 'eye' },
        T: { name: 'tube_body', role: 'body' },
        L: { name: 'tube_label', role: 'arm' },
        D: { name: 'label_text', role: 'belt' },
        B: { name: 'tube_crimp', role: 'leg' },
        S: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        arm:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#4e4a4e' },
      },
    },

    // ─── 13. EYE DROPS ──────────────────────────────────────────────
    // Small squeeze bottle with drip tip and blue tint
    {
      id: 'eye_drops_mg_16',
      description: 'Eye drops squeeze bottle with narrow drip tip, blue tinted body, and label band.',
      grid: [
        '................',
        '................',
        '.......DD.......',
        '.......DD.......',
        '......CCCC......',
        '......CCCC......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BLLLLB.....',
        '.....BLLLLB.....',
        '.....BLLLLB.....',
        '.....BBBBBB.....',
        '......SSSS......',
        '................',
        '................',
      ],
      chars: {
        D: { name: 'drip_tip', role: 'head' },
        C: { name: 'bottle_cap', role: 'eye' },
        B: { name: 'bottle_body', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        S: { name: 'bottle_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 14. HEADPHONES ─────────────────────────────────────────────
    // Over-ear headphones with thick headband and cushioned earcups
    {
      id: 'headphones_mg_16',
      description: 'Over-ear headphones with padded headband and large cushioned earcups.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HH........HH..',
        '..HH........HH..',
        '.HH..........HH.',
        '.HH..........HH.',
        '.PP..........PP.',
        'PPPP........PPPP',
        'PCCP........PCCP',
        'PCCP........PCCP',
        'PPPP........PPPP',
        '.PP..........PP.',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'headband', role: 'body' },
        P: { name: 'earcup_shell', role: 'arm' },
        C: { name: 'earcup_cushion', role: 'head' },
      },
      colors: {
        body:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 15. SLIPPERS ROOM ──────────────────────────────────────────
    // Pair of cozy room slippers side by side
    {
      id: 'slippers_room_mg_16',
      description: 'Pair of cozy indoor room slippers side by side with fluffy lining.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..FFFF..FFFF....',
        '.FFFFFF.FFFFFF..',
        '.FFFFFF.FFFFFF..',
        '.SSSSSS.SSSSSS..',
        '.SSSSSS.SSSSSS..',
        '.SSSSSS.SSSSSS..',
        '.SSSSSS.SSSSSS..',
        '..SSSS...SSSS...',
        '...TT.....TT....',
        '................',
      ],
      chars: {
        F: { name: 'fluffy_top', role: 'head' },
        S: { name: 'slipper_body', role: 'body' },
        T: { name: 'sole_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 16. BLANKET WRAP ───────────────────────────────────────────
    // Folded cozy blanket/throw with plaid pattern
    {
      id: 'blanket_wrap_mg_16',
      description: 'Folded cozy throw blanket wrapped in a neat bundle with visible plaid pattern.',
      grid: [
        '................',
        '................',
        '................',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '.BBBBBBBBBBBBBB.',
        '.BBPPBBPPBBPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBPPBBPPBBPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBPPBBPPBBPPBB.',
        '.BBBBBBBBBBBBBB.',
        '..SSSSSSSSSSSS..',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'fold_edge', role: 'head' },
        B: { name: 'blanket_body', role: 'body' },
        P: { name: 'plaid_pattern', role: 'arm' },
        S: { name: 'blanket_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:   { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        boot:  { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // ─── 17. HAND WARMER ────────────────────────────────────────────
    // Disposable hand warmer packet with label and heat wave marks
    {
      id: 'hand_warmer_mg_16',
      description: 'Disposable hand warmer packet with brand label and heat wave indicator.',
      grid: [
        '................',
        '................',
        '................',
        '...SSSSSSSSSS...',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '..PPLLLLLLLLPP..',
        '..PPLLDDDDLLPP..',
        '..PPLLDDDDLLPP..',
        '..PPLLLLLLLLPP..',
        '..PPWWPPWWPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '...BBBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'sealed_edge', role: 'eye' },
        P: { name: 'packet_body', role: 'body' },
        L: { name: 'label_area', role: 'arm' },
        D: { name: 'brand_text', role: 'belt' },
        W: { name: 'heat_waves', role: 'head' },
        B: { name: 'packet_base', role: 'boot' },
      },
      colors: {
        eye:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. MANGA TIMER ────────────────────────────────────────────
    // Round kitchen/deadline timer with dial face and minute markers
    {
      id: 'manga_timer_mg_16',
      description: 'Round kitchen deadline timer with dial face, minute markers, and chunky base.',
      grid: [
        '................',
        '................',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '...RRFFFFFFRR...',
        '...RFMMFMMFMR...',
        '..RRFMMMMMFRR...',
        '..RRFMMHMMFRR...',
        '..RRFMMHMMFRR...',
        '..RRFMMMMMFRR...',
        '...RFMMFMMFMR...',
        '...RRFFFFFFRR...',
        '....RRRRRRRR....',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '................',
      ],
      chars: {
        R: { name: 'timer_rim', role: 'body' },
        F: { name: 'face_ring', role: 'arm' },
        M: { name: 'dial_face', role: 'head' },
        H: { name: 'dial_hands', role: 'eye' },
        B: { name: 'timer_base', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. LUCKY CHARM (DARUMA) ───────────────────────────────────
    // Round daruma doll with painted face circles and gold trim
    {
      id: 'lucky_charm_mg_16',
      description: 'Daruma lucky charm doll with painted face circles, gold wish band, and rounded body.',
      grid: [
        '................',
        '................',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '...RRWWRRWWRR...',
        '..RRRWERRWERR...',
        '..RRRWWRRWWRRR..',
        '..RRRRRGGRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        R: { name: 'daruma_body', role: 'body' },
        W: { name: 'eye_circles', role: 'head' },
        E: { name: 'eye_pupil', role: 'eye' },
        G: { name: 'gold_band', role: 'arm' },
        T: { name: 'daruma_base', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:   { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        arm:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. CAT MASCOT (MANEKI-NEKO) ───────────────────────────────
    // Lucky cat figure with raised paw, bell collar, gold coin
    {
      id: 'cat_mascot_mg_16',
      description: 'Maneki-neko lucky cat figure with raised paw, bell collar, and gold coin.',
      grid: [
        '................',
        '..EE......EE....',
        '..EHE....EHE....',
        '..HHHHHHHHHH....',
        '..HHEEHHEEHH....',
        '..HHEEHHEEHH....',
        '..HHHHNHHHHH....',
        '..HHHHHHHHHH....',
        '.PPHHCCCCHHH....',
        '.PPHHCCCCHHH....',
        '.PPHHBBBBHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '...GGGGGGGG.....',
        '...GGGGGGGG.....',
        '................',
      ],
      chars: {
        E: { name: 'ear_tips', role: 'arm' },
        H: { name: 'cat_body', role: 'head' },
        N: { name: 'nose_mouth', role: 'eye' },
        P: { name: 'raised_paw', role: 'body' },
        C: { name: 'collar_bell', role: 'belt' },
        B: { name: 'gold_coin', role: 'accessory' },
        G: { name: 'base_cushion', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
