/**
 * Mangaka Simulator batch 1 — 20 drawing tool templates.
 * Focus: chunky, recognizable inking tools, drafting aids, desk stationery.
 * Earthbound/Stardew Valley item style — fat, round, readable at 16x16.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: {
    templates: 'MANGAKA_BATCH1_TEMPLATES',
    schemes: 'MANGAKA_BATCH1_COLOR_SCHEMES',
  },
  templates: [
    // ── 1. G-PEN NIB ──────────────────────────────────────────────
    {
      id: 'g_pen_nib_mg_16',
      description: 'Chunky G-pen nib with polished metal body and ink-dipped tip.',
      grid: [
        '................',
        '..........MM....',
        '.........MMMM...',
        '........MMMEM...',
        '.......MMMEE....',
        '......GGMM......',
        '.....GGG........',
        '....HHHG........',
        '...HHHH.........',
        '...HHHH.........',
        '..HHHH..........',
        '..HHHH..........',
        '.HHHH...........',
        '.HHH............',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'nib_metal', role: 'body' },
        E: { name: 'ink_edge', role: 'head' },
        H: { name: 'holder_barrel', role: 'arm' },
        G: { name: 'grip_ring', role: 'belt' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ── 2. MARU PEN NIB ───────────────────────────────────────────
    {
      id: 'maru_pen_nib_mg_16',
      description: 'Round maru pen nib — fatter profile with brass collar and ink point.',
      grid: [
        '................',
        '.........MMM....',
        '........MMMMM...',
        '.......MMMMEM...',
        '......MMMMMM....',
        '......GGGM......',
        '.....GGGG.......',
        '....HHHG........',
        '...HHHHH........',
        '...HHHHH........',
        '..HHHH..........',
        '..HHHH..........',
        '.HHHH...........',
        '.HHH............',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'nib_body', role: 'body' },
        E: { name: 'ink_tip', role: 'head' },
        H: { name: 'holder_wood', role: 'arm' },
        G: { name: 'brass_collar', role: 'belt' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ── 3. BRUSH PEN ──────────────────────────────────────────────
    {
      id: 'brush_pen_mg_16',
      description: 'Thick brush pen with snap cap and flexible tip for expressive inking.',
      grid: [
        '................',
        '......CCCC......',
        '......CCCC......',
        '......CCCC......',
        '......CCCC......',
        '......RBBR......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......RBBR......',
        '......TTTT......',
        '......TTTT......',
        '.......TT.......',
        '.......EE.......',
        '................',
      ],
      chars: {
        C: { name: 'cap_body', role: 'body' },
        B: { name: 'barrel', role: 'arm' },
        T: { name: 'brush_tip', role: 'head' },
        R: { name: 'ring_band', role: 'belt' },
        E: { name: 'ink_edge', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ── 4. MECHANICAL PENCIL ──────────────────────────────────────
    {
      id: 'mechanical_pencil_mg_16',
      description: 'Fat mechanical pencil with rubber grip, clip, and lead tip.',
      grid: [
        '................',
        '.......CC.......',
        '.......CC.......',
        '......BBBB......',
        '......BBBB......',
        '......BDDB......',
        '......GGGG......',
        '......GGGG......',
        '......GGGG......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......RBBR......',
        '.......TT.......',
        '.......LL.......',
        '................',
      ],
      chars: {
        C: { name: 'clip_top', role: 'accessory' },
        B: { name: 'pencil_barrel', role: 'body' },
        G: { name: 'rubber_grip', role: 'arm' },
        R: { name: 'ring_band', role: 'belt' },
        T: { name: 'tip_cone', role: 'head' },
        L: { name: 'lead_point', role: 'eye' },
        D: { name: 'clip_detail', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        belt: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ── 5. ERASER BLOCK ───────────────────────────────────────────
    {
      id: 'eraser_block_mg_16',
      description: 'Soft rectangular eraser block with paper sleeve and rounded corners.',
      grid: [
        '................',
        '................',
        '................',
        '....SSSSSSSS....',
        '....SSSSSSSS....',
        '...SBBBBBBBS....',
        '...SBBEBBBES....',
        '...SBBBBBBBS....',
        '...SBBBBBBBS....',
        '...SBBEBBBES....',
        '...SBBBBBBBS....',
        '...SBBBBBBBS....',
        '....EEEEEEEE....',
        '....EEEEEEEE....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'eraser_body', role: 'body' },
        S: { name: 'paper_sleeve', role: 'head' },
        E: { name: 'worn_edge', role: 'arm' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 6. CORRECTION FLUID ───────────────────────────────────────
    {
      id: 'correction_fluid_mg_16',
      description: 'Correction fluid bottle with screw cap and built-in brush.',
      grid: [
        '................',
        '.......BB.......',
        '......BCCB......',
        '......CCCC......',
        '......CCCC......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BLLLBB.....',
        '.....BLLLBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......TT.......',
        '................',
      ],
      chars: {
        B: { name: 'bottle_body', role: 'body' },
        C: { name: 'screw_cap', role: 'head' },
        L: { name: 'label_patch', role: 'arm' },
        T: { name: 'brush_tip', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 7. INK BOTTLE ─────────────────────────────────────────────
    {
      id: 'ink_bottle_mg_16',
      description: 'Round ink bottle with label and cork stopper.',
      grid: [
        '................',
        '................',
        '.......CC.......',
        '......CNNC......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBLLLLBB....',
        '....BBLLLLBB....',
        '....BBLLLLBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bottle_glass', role: 'body' },
        C: { name: 'cork_stopper', role: 'head' },
        L: { name: 'label_panel', role: 'arm' },
        N: { name: 'neck_rim', role: 'belt' },
      },
      colors: {
        body: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ── 8. INK WELL ───────────────────────────────────────────────
    {
      id: 'ink_well_mg_16',
      description: 'Open ink well pot seen from above, dark ink surface with ceramic rim.',
      grid: [
        '................',
        '................',
        '................',
        '....RRRRRRRR....',
        '...RRIIIIIIRR...',
        '...RIIIIIIIIR...',
        '..RRIIIHHIIIRR..',
        '..RIIIHHHHIIIR..',
        '..RIIIHHHHIIIR..',
        '..RRIIIHHIIIRR..',
        '...RIIIIIIIIR...',
        '...RRIIIIIIRR...',
        '....RRRRRRRR....',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'ceramic_rim', role: 'body' },
        I: { name: 'ink_surface', role: 'head' },
        H: { name: 'ink_highlight', role: 'arm' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head: { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        arm: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ── 9. RULER STRAIGHT ─────────────────────────────────────────
    {
      id: 'ruler_straight_mg_16',
      description: 'Thick transparent ruler with centimeter markings and accent stripe.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.RRRRRRRRRRRRRR.',
        '.RAAARAAARARAAR.',
        '.RRRRRRRRRRRRRR.',
        '.RMMDMMDMMDMMDR.',
        '.RRRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRRR.',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'ruler_body', role: 'body' },
        M: { name: 'tick_marks', role: 'head' },
        A: { name: 'accent_stripe', role: 'arm' },
        D: { name: 'digit_marks', role: 'belt' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ── 10. TRIANGLE RULER ────────────────────────────────────────
    {
      id: 'triangle_ruler_mg_16',
      description: 'Triangle set-square filled solid with measurement markings.',
      grid: [
        '................',
        '................',
        '.TT.............',
        '.TTTT...........',
        '.TTTTT..........',
        '.TMTTTT.........',
        '.TTTTTTT........',
        '.TMAAATTTT......',
        '.TTTAAATTTT.....',
        '.TMTTAAATTTT....',
        '.TTTTTAAATTTT...',
        '.TMTTTTTMTTTTT..',
        '.DTTDTTDTTTTTTTT',
        '.TTTTTTTTTTTTTTT',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'triangle_body', role: 'body' },
        M: { name: 'cm_marks', role: 'head' },
        A: { name: 'angle_window', role: 'arm' },
        D: { name: 'degree_dots', role: 'belt' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm: { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        belt: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ── 11. FRENCH CURVE ──────────────────────────────────────────
    {
      id: 'french_curve_mg_16',
      description: 'Thick curved template tool for speech balloons and flowing lines.',
      grid: [
        '................',
        '...FFFFFFFF.....',
        '..FFFFFFFFFFF...',
        '..FFFF...FFFF...',
        '.FFF.......FFF..',
        '.FFF.......FFF..',
        '.FFF......FFF...',
        '.FFF.....FFF....',
        '.FFMM.....MFFF..',
        '..FFMMMFF.......',
        '..FFFFFFFF......',
        '...FFFFFF.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'curve_body', role: 'body' },
        M: { name: 'mark_notches', role: 'head' },
      },
      colors: {
        body: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ── 12. CUTTING MAT ───────────────────────────────────────────
    {
      id: 'cutting_mat_mg_16',
      description: 'Self-healing cutting mat grid seen from above with ruler markings.',
      grid: [
        '................',
        '.MRRRMRRRMRRRM..',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.MRRRMRRRMRRRM..',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.MRRRMRRRMRRRM..',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.RGGGRGGGRGGGRR.',
        '.MRRRMRRRMRRRM..',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'mat_surface', role: 'body' },
        R: { name: 'grid_lines', role: 'head' },
        M: { name: 'major_marks', role: 'arm' },
      },
      colors: {
        body: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head: { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        arm: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ── 13. CRAFT KNIFE ───────────────────────────────────────────
    {
      id: 'craft_knife_mg_16',
      description: 'Chunky craft hobby knife with retractable blade and safety slider.',
      grid: [
        '................',
        '...........EE...',
        '..........EBE...',
        '.........EBBE...',
        '........BBBB....',
        '.......SBBS.....',
        '......SSSS......',
        '.....HHHH.......',
        '....HHHHH.......',
        '....HHHH........',
        '...HHHH.........',
        '...HHHH.........',
        '..HHHH..........',
        '..HHH...........',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'blade_edge', role: 'head' },
        B: { name: 'blade_body', role: 'body' },
        H: { name: 'handle_grip', role: 'arm' },
        S: { name: 'slider_lock', role: 'belt' },
      },
      colors: {
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 14. SCISSORS ──────────────────────────────────────────────
    {
      id: 'scissors_mg_16',
      description: 'Open scissors with chunky plastic handles and thick steel blades.',
      grid: [
        '................',
        '..BBB.....BBB...',
        '...BBBB.BBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '....PPPPPPPP....',
        '...PPBBBBBBPP...',
        '..PPBBBBBBBBPP..',
        '.HHH........RRR.',
        '.HHHH......RRRR.',
        '.HHHH......RRRR.',
        '..HHHH....RRRR..',
        '..HHHH....RRRR..',
        '...HHH....RRR...',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'blade_steel', role: 'body' },
        P: { name: 'pivot_joint', role: 'head' },
        H: { name: 'handle_left', role: 'arm' },
        R: { name: 'handle_right', role: 'belt' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ── 15. PENCIL CASE ───────────────────────────────────────────
    {
      id: 'pencil_case_mg_16',
      description: 'Zippered pencil case pouch with visible zipper and rounded shape.',
      grid: [
        '................',
        '................',
        '..ZZZZZZZZZZ....',
        '..ZBBBBBBBBBZ...',
        '.ZBBBBBBBBBBZ...',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBBZ..',
        '.ZBBBBBBBBBBZ...',
        '..ZBBBBBBBBBZ...',
        '..ZZZZZZZZZZ....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case_fabric', role: 'body' },
        Z: { name: 'zipper_track', role: 'head' },
      },
      colors: {
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ── 16. COPIC MARKER ──────────────────────────────────────────
    {
      id: 'marker_copic_mg_16',
      description: 'Thick chisel-tip Copic-style marker with dual caps and label band.',
      grid: [
        '................',
        '......CCCC......',
        '......CCCC......',
        '......CCCC......',
        '......LLLL......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......LLLL......',
        '......TTTT......',
        '......TTTT......',
        '................',
      ],
      chars: {
        C: { name: 'cap_top', role: 'head' },
        B: { name: 'marker_barrel', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        T: { name: 'chisel_tip', role: 'belt' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ── 17. SCREENTONE ROLL ───────────────────────────────────────
    {
      id: 'screen_tone_roll_mg_16',
      description: 'Screentone adhesive sheet roll with dotted pattern visible on surface.',
      grid: [
        '................',
        '....RRRRRR......',
        '...RRRRRRRRR....',
        '..RRSSDSSDSSRR..',
        '..RSDSSDSSDSR...',
        '..RSSDSSDSSDR...',
        '..RSDSSDSSDSR...',
        '..RSSDSSDSSDR...',
        '..RSDSSDSSDSR...',
        '..RSSDSSDSSDR...',
        '..RRSSDSSDSSRR..',
        '...RRRRRRRRR....',
        '....RRRRRR......',
        '......TTTT......',
        '......TTTT......',
        '................',
      ],
      chars: {
        R: { name: 'roll_edge', role: 'body' },
        S: { name: 'tone_surface', role: 'head' },
        D: { name: 'dot_pattern', role: 'arm' },
        T: { name: 'tab_pull', role: 'belt' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ── 18. WHITE-OUT PEN ─────────────────────────────────────────
    {
      id: 'white_out_pen_mg_16',
      description: 'White-out correction pen with squeeze body and fine applicator tip.',
      grid: [
        '................',
        '.....CCCC.......',
        '.....CCCC.......',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBLBBB......',
        '....BBLBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....RRBB.......',
        '......TT........',
        '......TT........',
        '................',
      ],
      chars: {
        C: { name: 'cap_top', role: 'head' },
        B: { name: 'pen_body', role: 'body' },
        L: { name: 'label_stripe', role: 'arm' },
        R: { name: 'ring_band', role: 'belt' },
        T: { name: 'applicator_tip', role: 'accessory' },
      },
      colors: {
        head: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ── 19. PEN HOLDER CUP ────────────────────────────────────────
    {
      id: 'pen_holder_cup_mg_16',
      description: 'Cup stuffed with pens and brushes sticking out the top.',
      grid: [
        '.....PP.BB......',
        '....PPP.BBM.....',
        '....PPP.BBM.....',
        '....PP..BM......',
        '....PP..BM......',
        '...CCCCCCCC.....',
        '...CCCCCCCC.....',
        '...CCLLLCCC.....',
        '...CCLLLCCC.....',
        '...CCLLLCCC.....',
        '...CCCCCCCC.....',
        '...CCCCCCCC.....',
        '....CCCCCC......',
        '....CCCCCC......',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cup_ceramic', role: 'body' },
        L: { name: 'cup_label', role: 'head' },
        P: { name: 'pen_sticks', role: 'arm' },
        B: { name: 'brush_sticks', role: 'belt' },
        M: { name: 'marker_tips', role: 'accessory' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ── 20. DRAFTING TAPE ─────────────────────────────────────────
    {
      id: 'drafting_tape_mg_16',
      description: 'Roll of low-tack drafting tape with visible core and torn edge.',
      grid: [
        '................',
        '................',
        '......TTTT......',
        '....TTTTTTTT....',
        '...TTTTTTTTTT...',
        '..TTTTOOTTTTTT..',
        '..TTTOOOOTTTTT..',
        '..TTTOOOOTTTET..',
        '..TTTOOOOTTTET..',
        '..TTTTOOTTTTEE..',
        '...TTTTTTTTTT...',
        '....TTTTTTTT....',
        '......TTTT......',
        '................',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'tape_surface', role: 'body' },
        O: { name: 'core_hole', role: 'head' },
        E: { name: 'torn_edge', role: 'arm' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },
  ],
};

export default batch;
