/**
 * Mangaka Simulator batch 2 — 20 paper & manuscript templates.
 * Focus: manga pages, stationery, screentones, and documents.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: { templates: 'MANGAKA_BATCH2_TEMPLATES', schemes: 'MANGAKA_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. BLANK MANUSCRIPT — empty manga page with border lines ─
    {
      id: 'blank_manuscript_mg_16',
      description: 'Empty manga manuscript page with printed border guidelines.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PBBBBBBBBBBBBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBPPPPPPPPPPBP.',
        '.PBBBBBBBBBBBBP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'page_surface', role: 'body' },
        B: { name: 'border_guide', role: 'arm' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 2. INKED PAGE — manuscript page with ink panel lines ─────
    {
      id: 'inked_page_mg_16',
      description: 'Manuscript page with black inked panel borders and gutter lines.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PIIIIIIIIIIIIP.',
        '.PIIPPPPPIIPPIP.',
        '.PIIPPPPPIIPPIP.',
        '.PIIPPPPPIIPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIPPIIPPPPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'page_paper', role: 'body' },
        I: { name: 'ink_lines', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 3. FINISHED PAGE — completed manga page with tone and ink ─
    {
      id: 'finished_page_mg_16',
      description: 'Completed manga page with screentone shading and inked artwork.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PIIIIIIIIIIIIP.',
        '.PITTTTTIIDDDIP.',
        '.PITTTTTIIDDDIP.',
        '.PITTTTTIIDDDIP.',
        '.PIIIIIIIIIIIIP.',
        '.PIDDDIITTTTDIP.',
        '.PIDDDIITTTTDIP.',
        '.PIDDDIITTTTDIP.',
        '.PIDDDIITTTTDIP.',
        '.PIDDDIITTTTDIP.',
        '.PIDDDIITTTTDIP.',
        '.PIIIIIIIIIIIIP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'page_paper', role: 'body' },
        I: { name: 'ink_borders', role: 'eye' },
        T: { name: 'screentone_fill', role: 'arm' },
        D: { name: 'dark_shading', role: 'belt' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        belt: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 4. STORYBOARD SHEET — rough storyboard/name with sketches ─
    {
      id: 'storyboard_sheet_mg_16',
      description: 'Rough storyboard sheet with sketchy pencil panels and notes.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PSSSSPPSSSSSSP.',
        '.PSSSSPPSSSSSSP.',
        '.PSSSSPPSSSSSSP.',
        '.PPPPPPPPPPPPPP.',
        '.PSSSSSSSPSSPPP.',
        '.PSSSSSSSPSSPPP.',
        '.PSSSSSSSPSSPPP.',
        '.PSSSSSSSPSSPPP.',
        '.PPPPPPPPPPPPPP.',
        '.PSSSPPSSSSSPNP.',
        '.PSSSPPSSSSSPNP.',
        '.PSSSPPSSSSSPNP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'paper_base', role: 'body' },
        S: { name: 'sketch_marks', role: 'arm' },
        N: { name: 'margin_notes', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 5. 4-PANEL LAYOUT — yonkoma style grid ──────────────────
    {
      id: 'panel_layout_4_mg_16',
      description: 'Four-panel yonkoma manga layout with equal vertical panels.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PIIIIIIIIIIIIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIPPPPPPPPPPIP.',
        '.PIIIIIIIIIIIIP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'page_white', role: 'body' },
        I: { name: 'panel_borders', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 6. SPEECH BUBBLE — empty manga speech bubble ─────────────
    {
      id: 'speech_bubble_mg_16',
      description: 'Classic manga speech bubble with rounded outline and tail.',
      grid: [
        '................',
        '....BBBBBB......',
        '..BBPPPPPPBB....',
        '..BPPPPPPPPB....',
        '.BPPPPPPPPPPB...',
        '.BPPPPPPPPPPB...',
        '.BPPPPPPPPPPB...',
        '.BPPPPPPPPPPB...',
        '..BPPPPPPPPB....',
        '..BBPPPPPPBB....',
        '....BBBBBB......',
        '....BP..........',
        '...BP...........',
        '...B............',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'bubble_fill', role: 'body' },
        B: { name: 'bubble_outline', role: 'eye' },
      },
      colors: {
        body: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 7. THOUGHT BUBBLE — cloud-shaped thought bubble ──────────
    {
      id: 'thought_bubble_mg_16',
      description: 'Cloud-shaped thought bubble with scalloped edges and trail dots.',
      grid: [
        '................',
        '....BBBBB.......',
        '..BBPPPPPBB.....',
        '.BPPPPPPPPPB....',
        '.BPPPPPPPPPBB...',
        'BPPPPPPPPPPPB...',
        'BPPPPPPPPPPPB...',
        'BPPPPPPPPPPBB...',
        '.BBPPPPPPPB.....',
        '..BBPPPPPBB.....',
        '....BBBBB.......',
        '.....BB.........',
        '......BB........',
        '.......BP.......',
        '........BP......',
        '................',
      ],
      chars: {
        P: { name: 'cloud_fill', role: 'body' },
        B: { name: 'cloud_outline', role: 'arm' },
      },
      colors: {
        body: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. SFX BURST — sound effect explosion burst shape ────────
    {
      id: 'sfx_burst_mg_16',
      description: 'Jagged starburst shape for manga sound effects and impacts.',
      grid: [
        '......BB........',
        '...B.BPPB.......',
        '..BPBPPPPB.B....',
        '..BPPPPPPPBPB...',
        '.BPPPPPPPPPPB...',
        '.BPPPPPPPPPPPB..',
        'BPPPPPPPPPPPPB..',
        'BPPPPPPPPPPPPBB.',
        '.BPPPPPPPPPPPPB.',
        '.BPPPPPPPPPPPBB.',
        '..BPPPPPPPPPPB..',
        '..BPBPPPPPBPPB..',
        '...B.BPPPPBPB...',
        '......BPPBB.....',
        '.......BB.......',
        '................',
      ],
      chars: {
        P: { name: 'burst_fill', role: 'body' },
        B: { name: 'burst_outline', role: 'eye' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. SCREEN TONE SHEET — flat screentone dot pattern ───────
    {
      id: 'screen_tone_sheet_mg_16',
      description: 'Flat screentone sheet with regular halftone dot pattern.',
      grid: [
        '................',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SDSDSDSDSDSDSS.',
        '.SSSSSSSSSSSSSS.',
        '.SSSSSSSSSSSSBP.',
        '...............P',
      ],
      chars: {
        S: { name: 'tone_surface', role: 'body' },
        D: { name: 'tone_dots', role: 'arm' },
        B: { name: 'peel_fold', role: 'belt' },
        P: { name: 'backing_paper', role: 'head' },
      },
      colors: {
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 10. GRADIENT TONE — gradient screentone sheet ────────────
    {
      id: 'gradient_tone_mg_16',
      description: 'Gradient screentone sheet fading from dark to light dots.',
      grid: [
        '................',
        '.SSSSSSSSSSSSSS.',
        '.SDDDDDDSSSSSSS.',
        '.SDDDDDDSDSSTSS.',
        '.SDDDDDDSSSSSSS.',
        '.SDDDDDDSDSSTSS.',
        '.SDDDDDDSSSSSSS.',
        '.SDDMDDDSDSSTSS.',
        '.SDDDDDDSSSSSSS.',
        '.SDDMDDDSDSSTSS.',
        '.SDDDDDDSSSSSSS.',
        '.SDDMDDDSDSSSSS.',
        '.SDDDDDDSSSSSSS.',
        '.SSSSSSSSSSSSSS.',
        '.SSSSSSSSSSSSBP.',
        '..............PP',
      ],
      chars: {
        S: { name: 'tone_surface', role: 'body' },
        D: { name: 'dark_tone', role: 'belt' },
        M: { name: 'mid_dots', role: 'arm' },
        T: { name: 'light_dots', role: 'head' },
        B: { name: 'peel_corner', role: 'accessory' },
        P: { name: 'backing', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 11. REFERENCE PHOTO — pinned reference photo ─────────────
    {
      id: 'reference_photo_mg_16',
      description: 'Pinned reference photo with corner tab and scenic image.',
      grid: [
        '....AA..........',
        '...APPA.........',
        '.FFFFFFFFFFFFFF.',
        '.FBBBBBBBBBBBBF.',
        '.FBBBBBBBBBBBBF.',
        '.FBBBBSSBBBBBBF.',
        '.FBBSSSSSSBBBBF.',
        '.FBSSSSSSSSSBGF.',
        '.FGGGGGGGGGGGGF.',
        '.FGGGGGGGGGGGGF.',
        '.FGGGGGGGGGGGGF.',
        '.FBBBBBBBBBBBBF.',
        '.FBBBBBBBBBBBBF.',
        '.FFFFFFFFFFFFFF.',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'photo_border', role: 'body' },
        B: { name: 'sky_area', role: 'arm' },
        S: { name: 'sun_clouds', role: 'accessory' },
        G: { name: 'ground_area', role: 'belt' },
        A: { name: 'pin_tack', role: 'head' },
        P: { name: 'pin_point', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 12. SKETCH PAD — spiral-bound sketchpad ──────────────────
    {
      id: 'sketch_pad_mg_16',
      description: 'Spiral-bound sketchpad with wire binding and sketch marks.',
      grid: [
        '................',
        '.RPPPPPPPPPPPP..',
        '.RPPPPPPPPPPPP..',
        '.R.PPPPPPPPPPP..',
        '.RPPPSPPPSPPPPP.',
        '.R.PPPPPPPPPPP..',
        '.RPPPPSPSPPPPP..',
        '.R.PPPPPPSSPPP..',
        '.RPPSPPPPPPPPP..',
        '.R.PPPPPPPPPPP..',
        '.RPPPPPSPPPPP...',
        '.R.PPPPPPPPPPP..',
        '.RPPPPPPPPPPPPP.',
        '.R.PPPPPPPPPPP..',
        '.RPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'pad_paper', role: 'body' },
        R: { name: 'spiral_wire', role: 'arm' },
        S: { name: 'pencil_sketch', role: 'belt' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        belt: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 13. TRACING PAPER — semi-transparent tracing paper ───────
    {
      id: 'tracing_paper_mg_16',
      description: 'Semi-transparent tracing paper sheet layered over sketch.',
      grid: [
        '................',
        '..TTTTTTTTTTTT..',
        '..TTTTTTTTTTTT..',
        '..TTGGTTGGTTTT..',
        '..TTGGTTGGTTTT..',
        '..TTTTTTTTTTTT..',
        '..TTTTGGGGTTTT..',
        '..TTTTGGGGTTTT..',
        '..TTTTTTTTTTTT..',
        '..TTGGGGGGGTTT..',
        '..TTGGGGGGGTTT..',
        '..TTTTTTTTTTTT..',
        '..TTTTTTTTTTTT..',
        '..TTTTTTTTTTTC..',
        '..TTTTTTTTTTCC..',
        '................',
      ],
      chars: {
        T: { name: 'tracing_sheet', role: 'body' },
        G: { name: 'ghost_image', role: 'arm' },
        C: { name: 'curl_corner', role: 'head' },
      },
      colors: {
        body: { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. MANGA SCRIPT — written manga script document ─────────
    {
      id: 'manga_script_mg_16',
      description: 'Typed manga script document with title header and dialogue lines.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PTTTTTTTTTTTPP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLPPLLLLP.',
        '.PLLLLLLPPLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '................',
      ],
      chars: {
        P: { name: 'script_paper', role: 'body' },
        T: { name: 'title_header', role: 'head' },
        L: { name: 'text_lines', role: 'arm' },
      },
      colors: {
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. STICKY NOTE — colored sticky note with writing ───────
    {
      id: 'sticky_note_mg_16',
      description: 'Yellow sticky note with handwritten reminder text.',
      grid: [
        '................',
        '................',
        '..SSSSSSSSSSSS..',
        '..SAASSSSSSASS..',
        '..SSSSSSSSSSSS..',
        '..SLLLLLLLLSSS..',
        '..SSSSSSSSSSSS..',
        '..SLLLLLLLLSSS..',
        '..SSSSSSSSSSSS..',
        '..SLLLLLSSSSSS..',
        '..SSSSSSSSSSSS..',
        '..SSSSSSSSSSS...',
        '..SSSSSSSSSSC...',
        '..SSSSSSSSSSCC..',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'note_surface', role: 'body' },
        L: { name: 'writing_lines', role: 'arm' },
        A: { name: 'adhesive_strip', role: 'belt' },
        C: { name: 'corner_curl', role: 'head' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 16. CORRECTION STRIP — white correction paper strip ──────
    {
      id: 'correction_strip_mg_16',
      description: 'White correction paper strip used to cover inking mistakes.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.CCCCCCCCCCCCCC.',
        '.CWWWWWWWWWWWWC.',
        '.CWWWWWWWWWWWWC.',
        '.CWWWWWWWWWWWWC.',
        '.CWWWWWWWWWWWWC.',
        '.CWWGGGGWWWWWWC.',
        '.CWWGGGGWWWWWWC.',
        '.CCCCCCCCCCCCCC.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'white_surface', role: 'body' },
        C: { name: 'cut_edge', role: 'arm' },
        G: { name: 'glue_residue', role: 'belt' },
      },
      colors: {
        body: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 17. ENVELOPE SUBMISSION — manuscript submission envelope ──
    {
      id: 'envelope_submission_mg_16',
      description: 'Large manuscript submission envelope with address label and stamp.',
      grid: [
        '................',
        '.FFFFFFFFFFFFFF.',
        '.FEEEEEEEEEEEEF.',
        '.FEEEEEEEEEEEEF.',
        '.FEEEEEEEEEEEEF.',
        '.FEELLLLLLLEEEF.',
        '.FEELLLLLLLEEEF.',
        '.FEELLLLLLLEEEF.',
        '.FEEEEEEEEEEEEF.',
        '.FEESSSEEEEEEEF.',
        '.FEESSSEEEEEEEF.',
        '.FEEEEEEEETTTEF.',
        '.FEEEEEEEETTTEF.',
        '.FEEEEEEEEEEEEF.',
        '.FFFFFFFFFFFFFF.',
        '................',
      ],
      chars: {
        E: { name: 'envelope_paper', role: 'body' },
        F: { name: 'flap_border', role: 'arm' },
        L: { name: 'address_label', role: 'head' },
        S: { name: 'sender_label', role: 'belt' },
        T: { name: 'stamp_mark', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 18. POSTCARD FAN — fan postcard/letter ───────────────────
    {
      id: 'postcard_fan_mg_16',
      description: 'Fan mail postcard with heart sticker and handwritten message.',
      grid: [
        '................',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPHHPPPPPPPP..',
        '..PHHHHPPPPPPP..',
        '..PPHHPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '..PLLLLLLLLLLP..',
        '..PPPPPPPPPPPP..',
        '..PLLLLLLLLLLP..',
        '..PPPPPPPPPPPP..',
        '..PLLLLLLPPPPP..',
        '..PPPPPPPPPSSP..',
        '..PPPPPPPPSSSP..',
        '..PPPPPPPPPPPP..',
        '................',
      ],
      chars: {
        P: { name: 'postcard_paper', role: 'body' },
        L: { name: 'written_lines', role: 'arm' },
        H: { name: 'heart_sticker', role: 'accessory' },
        S: { name: 'stamp_corner', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 19. CONTRACT DOC — publisher contract document ───────────
    {
      id: 'contract_doc_mg_16',
      description: 'Official publisher contract document with seal and signature line.',
      grid: [
        '................',
        '.PPPPPPPPPPPPPP.',
        '.PTTTTTTTTTTPPP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PLLLLLLLLLLLLP.',
        '.PPPPPPPPPPPPPP.',
        '.PPPSSSPPPPPPPP.',
        '.PPPSSSSPPRRRPP.',
        '.PPPSSSPPPRRRPP.',
        '................',
      ],
      chars: {
        P: { name: 'contract_paper', role: 'body' },
        T: { name: 'title_line', role: 'head' },
        L: { name: 'legal_text', role: 'arm' },
        S: { name: 'official_seal', role: 'accessory' },
        R: { name: 'signature_ink', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. BUSINESS CARD — editor's business card ───────────────
    {
      id: 'business_card_mg_16',
      description: 'Editor business card with publisher logo and contact details.',
      grid: [
        '................',
        '................',
        '................',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCLLCCCCCCCC..',
        '..CLLLLCCCCCCC..',
        '..CCLLCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCTTTTTTTTCC..',
        '..CCCCCCCCCCCC..',
        '..CCTTTTTTCCCC..',
        '..CCCCCCCCCCCC..',
        '................',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'card_stock', role: 'body' },
        L: { name: 'publisher_logo', role: 'accessory' },
        T: { name: 'contact_text', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

  ],
};

export default batch;
