/**
 * Modern Tech batch 2 — 20 more futuristic gadgets.
 * Cyberpunk implants, AI cores, plasma weapons, holographic displays.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'modernTech',
  exportNames: { templates: 'MODERN_TECH_BATCH2_TEMPLATES', schemes: 'MODERN_TECH_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. CYBER EYE IMPLANT ──────────────────────────────
    {
      id: 'cyber_eye_16',
      description: 'Cyberpunk eye implant with glowing iris.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBEEEEEEBB...',
        '..BBEEEEEEEEBB..',
        '..BBEEEHHEEEBB..',
        '..BBEEEHHEEEBB..',
        '..BBEEEEEEEEBB..',
        '...BBEEEEEEBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'iris', role: 'eye' },
        H: { name: 'pupil', role: 'head' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 2. AI CORE ────────────────────────────────────────
    {
      id: 'ai_core_16',
      description: 'Glowing AI processing core with data streams.',
      grid: [
        '......EE........',
        '.....EEEE.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBBEEBBBBB...',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBEEBBBBB...',
        '..BBBBEEBBBBB...',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....AAAA.......',
        '......AA........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'glow', role: 'eye' },
        A: { name: 'connector', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 3. PLASMA RIFLE ───────────────────────────────────
    {
      id: 'plasma_rifle_16',
      description: 'Heavy plasma rifle with energy coils.',
      grid: [
        '................',
        '................',
        'EBBBBBBBBBB.....',
        'EBBBBBBBBBBBBB..',
        'BBBBBBBBBBBBBBB.',
        'BBBBBEBBBBBBBB..',
        '...BBBBBBBBB....',
        '....GGGBBBB.....',
        '....GGGG........',
        '....GGGG........',
        '.....AAA........',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'coil', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'stock', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 4. HOLOGRAPHIC DISPLAY ────────────────────────────
    {
      id: 'holo_display_16',
      description: 'Floating holographic display screen.',
      grid: [
        '................',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '....BBBBBB......',
        '.....BBBB.......',
        '......BB........',
        '......BB........',
        '.....AAAA.......',
        '....AAAAAA......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'screen', role: 'eye' },
        B: { name: 'neck', role: 'body' },
        A: { name: 'stand', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 5. JETPACK ────────────────────────────────────────
    {
      id: 'jetpack_16',
      description: 'Personal jetpack with dual thrusters.',
      grid: [
        '................',
        '....AAAAAA......',
        '...AABBBBAA.....',
        '...AABBBBAA.....',
        '..AABBBBBBA.....',
        '..AABBBBBBA.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..EEBB..BBEE....',
        '..EEE....EEE....',
        '...EE....EE.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'tank', role: 'body' },
        A: { name: 'straps', role: 'arm' },
        E: { name: 'thruster', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. FORCEFIELD EMITTER ─────────────────────────────
    {
      id: 'forcefield_emitter_16',
      description: 'Wall-mounted forcefield barrier emitter.',
      grid: [
        '..BB............',
        '..BBBB..........',
        '..BBBBBB........',
        '..BBEEBB........',
        '..BBBBBB........',
        '..BBBHHHHHHHH...',
        '..BBBHHHHHHHH...',
        '..BBBHHHHHHHH...',
        '..BBBHHHHHHHH...',
        '..BBBHHHHHHHH...',
        '..BBBBBB........',
        '..BBEEBB........',
        '..BBBBBB........',
        '..BBBB..........',
        '..BB............',
        '................',
      ],
      chars: {
        B: { name: 'emitter', role: 'body' },
        E: { name: 'core', role: 'eye' },
        H: { name: 'barrier', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 7. SMART WATCH ────────────────────────────────────
    {
      id: 'smart_watch_16',
      description: 'Futuristic smartwatch with holographic interface.',
      grid: [
        '................',
        '................',
        '......AA........',
        '......AA........',
        '.....BBBB.......',
        '....BBEEBB......',
        '....BBEEBB......',
        '....BBEEBB......',
        '....BBEEBB......',
        '.....BBBB.......',
        '......AA........',
        '......AA........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'display', role: 'eye' },
        A: { name: 'band', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 8. CRYOGENIC POD ──────────────────────────────────
    {
      id: 'cryo_pod_16',
      description: 'Cryogenic stasis pod with frosted glass.',
      grid: [
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..AABBBBBBAA....',
        '..AAAAAAAAAA....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pod', role: 'body' },
        E: { name: 'glass', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 9. PLASMA CORE ────────────────────────────────────
    {
      id: 'plasma_core_16',
      description: 'Contained plasma energy sphere.',
      grid: [
        '................',
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBEEBBB....',
        '..BBBBEEEEBBB...',
        '..BBBBEEEEBBB...',
        '..BBBBEEEEBBB...',
        '..BBBBEEEEBBB...',
        '...BBBBEEBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'containment', role: 'body' },
        E: { name: 'plasma', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. NEURAL LINK ───────────────────────────────────
    {
      id: 'neural_link_16',
      description: 'Brain-computer neural interface device.',
      grid: [
        '................',
        '................',
        '....AABB........',
        '....AABB........',
        '...BBBBBB.......',
        '..BBBEEBBBB.....',
        '..BBBEEBBBB.....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '....AABB........',
        '.....ABB........',
        '......A.........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'device', role: 'body' },
        E: { name: 'interface', role: 'eye' },
        A: { name: 'leads', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 11. HOVER DRONE ───────────────────────────────────
    {
      id: 'hover_drone_16',
      description: 'Small delivery/surveillance hover drone.',
      grid: [
        '................',
        '................',
        '...RR......RR...',
        '...RRR....RRR...',
        '....RBBBBBBR....',
        '....BBBBBBBB....',
        '...BBBBEEBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        R: { name: 'rotor', role: 'arm' },
        E: { name: 'sensor', role: 'eye' },
        A: { name: 'cargo_bay', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 12. ENERGY SWORD ──────────────────────────────────
    {
      id: 'energy_sword_16',
      description: 'Sci-fi energy blade / beam sword.',
      grid: [
        '.........E......',
        '........EE......',
        '.......EEE......',
        '......EEEE......',
        '.....EEEEE......',
        '....EEEEEE......',
        '...EEEEEEE......',
        '..EEEEEEEE......',
        '.EEEEEEEEE......',
        '..EEEEEE........',
        '....BBBB........',
        '....BBBB........',
        '.....GG.........',
        '.....GG.........',
        '......A.........',
        '................',
      ],
      chars: {
        E: { name: 'blade', role: 'eye' },
        B: { name: 'guard', role: 'body' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'pommel', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 13. RECHARGE STATION ──────────────────────────────
    {
      id: 'recharge_station_16',
      description: 'Power recharge station with charge indicator.',
      grid: [
        '................',
        '.....EEEE.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBEEBBBB.....',
        '...BBEEBBBB.....',
        '...BBBBBBBB.....',
        '..AAAAAAAAAA....',
        '..AAAAAAAAAA....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'station', role: 'body' },
        E: { name: 'indicator', role: 'eye' },
        A: { name: 'platform', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 14. MECH LEG ──────────────────────────────────────
    {
      id: 'mech_leg_16',
      description: 'Robotic mech leg with hydraulic joints.',
      grid: [
        '................',
        '.....BBB........',
        '....BBBBB.......',
        '....BBBBB.......',
        '.....ABBA.......',
        '......ABB.......',
        '......ABB.......',
        '.....ABBA.......',
        '....BBBBB.......',
        '...BBBBBB.......',
        '...BBBBB........',
        '....ABBA........',
        '.....ABB........',
        '.....BBBB.......',
        '....EEEEEE......',
        '...EEEEEEEE.....',
      ],
      chars: {
        B: { name: 'plating', role: 'body' },
        A: { name: 'hydraulic', role: 'arm' },
        E: { name: 'foot_pad', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 15. COMMS DEVICE ──────────────────────────────────
    {
      id: 'comms_device_16',
      description: 'Wrist-mounted communication device.',
      grid: [
        '................',
        '................',
        '................',
        '.....AAAA.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '....BBBBBB......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        A: { name: 'strap', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 16. STASIS FIELD ──────────────────────────────────
    {
      id: 'stasis_field_16',
      description: 'Stasis containment field with trapped object.',
      grid: [
        '................',
        '....HHHHHHH.....',
        '...H.......H....',
        '..H.........H...',
        '..H...BBB...H...',
        '..H..BBBBB..H...',
        '..H..BBEEB..H...',
        '..H..BBBBB..H...',
        '..H...BBB...H...',
        '..H.........H...',
        '...H.......H....',
        '....HHHHHHH.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'field', role: 'accessory' },
        B: { name: 'object', role: 'body' },
        E: { name: 'glow', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 17. SOLAR PANEL ───────────────────────────────────
    {
      id: 'solar_panel_16',
      description: 'Deployable solar panel array.',
      grid: [
        '................',
        '.BBBBBBBBBBBB...',
        '.BEEBBEEBBEEB...',
        '.BEEBBEEBBEEB...',
        '.BBBBBBBBBBBB...',
        '.BEEBBEEBBEEB...',
        '.BEEBBEEBBEEB...',
        '.BBBBBBBBBBBB...',
        '......AA........',
        '......AA........',
        '......AA........',
        '.....GGGG.......',
        '....GGGGGG......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'panel_frame', role: 'body' },
        E: { name: 'cell', role: 'eye' },
        A: { name: 'pole', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 18. EXOSUIT GLOVE ─────────────────────────────────
    {
      id: 'exosuit_glove_16',
      description: 'Powered exosuit gauntlet with energy knuckles.',
      grid: [
        '................',
        '................',
        '...BB...........',
        '..BBB...........',
        '..BBB...........',
        '..BBBBB.........',
        '.BBBBBBB........',
        '.BBBBBBBBB......',
        '.BBBBBBBBBB.....',
        '..EEBBBBBB......',
        '..EEBBBBB.......',
        '...BBBBBB.......',
        '....BBBB........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'gauntlet', role: 'body' },
        E: { name: 'knuckle', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 19. FUSION REACTOR ────────────────────────────────
    {
      id: 'fusion_reactor_16',
      description: 'Miniature fusion reactor with containment ring.',
      grid: [
        '................',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBB..BBBB....',
        '..BBB.EE.BBB....',
        '..BB.EEEE.BB....',
        '..BB.EEEE.BB....',
        '..BBB.EE.BBB....',
        '..BBBB..BBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....AAAA.......',
        '....AAAAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'containment', role: 'body' },
        E: { name: 'plasma', role: 'eye' },
        A: { name: 'cooling', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. GRAVITY GUN ───────────────────────────────────
    {
      id: 'gravity_gun_16',
      description: 'Gravity manipulation tool / weapon.',
      grid: [
        '................',
        '................',
        '................',
        '..EEBBBBBB......',
        '..EEBBBBBBBBB...',
        '.EEBBBBBBBBBBB..',
        '.EEBBBBBBBBBBB..',
        '..EEBBBBBBBBB...',
        '..EEBBBBBB......',
        '.....GGBB.......',
        '.....GGG........',
        '.....GGG........',
        '......AA........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'emitter', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'stock', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
