/**
 * Modern Tech batch 4 — 20 final sci-fi tech items.
 * Space exploration, robotics, energy systems, advanced weapons.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'modernTech',
  exportNames: { templates: 'MODERN_TECH_BATCH4_TEMPLATES', schemes: 'MODERN_TECH_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SPACE SUIT HELMET ──────────────────────────────
    {
      id: 'space_helmet_16',
      description: 'Astronaut space suit helmet with visor.',
      grid: [
        '................',
        '.....BBBBB......',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '..BBEEEEEEEEB...',
        '..BBEEEEEEEEB...',
        '..BBEEEEEEEEB...',
        '..BBEEEEEEEEB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'visor', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 2. ROBOT HEAD ─────────────────────────────────────
    {
      id: 'robot_head_16',
      description: 'Friendly robot head with LED eyes.',
      grid: [
        '......AA........',
        '.....ABBA.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBEEBB.EEBB...',
        '..BBEEBB.EEBB...',
        '..BBBBBBBBBB....',
        '..BBBBEEEEBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....GGGG.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'head', role: 'body' },
        E: { name: 'eyes_mouth', role: 'eye' },
        A: { name: 'antenna', role: 'arm' },
        G: { name: 'neck', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 3. ION THRUSTER ───────────────────────────────────
    {
      id: 'ion_thruster_16',
      description: 'Ion propulsion engine nozzle.',
      grid: [
        '................',
        '....BBBB........',
        '...BBBBBB.......',
        '..BBBBBBBBB.....',
        '..BBBBBBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBEE..',
        '.BBBBBBBBBBBEE..',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBB.....',
        '...BBBBBB.......',
        '....BBBB........',
        '................',
      ],
      chars: {
        B: { name: 'engine', role: 'body' },
        E: { name: 'exhaust', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 4. PLASMA BATTERY ─────────────────────────────────
    {
      id: 'plasma_battery_16',
      description: 'Large plasma-filled battery cylinder.',
      grid: [
        '................',
        '.....AAAA.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '....BBBBBB......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'casing', role: 'body' },
        E: { name: 'plasma', role: 'eye' },
        A: { name: 'cap', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 5. GAUSS PISTOL ───────────────────────────────────
    {
      id: 'gauss_pistol_16',
      description: 'Electromagnetic gauss handgun.',
      grid: [
        '................',
        '................',
        '................',
        '..AABBBBBBB.....',
        '..AABBBBBBBBB...',
        '...BBBBBBBBBBB..',
        '...EEBBBBBBBB...',
        '......GGGBBB....',
        '......GGGBB.....',
        '......GGGG......',
        '......GGGG......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'coil', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'sight', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 6. CONTAINMENT JAR ────────────────────────────────
    {
      id: 'containment_jar_16',
      description: 'Specimen containment jar with energy lid.',
      grid: [
        '................',
        '.....EEEE.......',
        '....EEEEEE......',
        '....BBBBBB......',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '....BBBBBB......',
        '....AAAAAA......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'glass', role: 'body' },
        H: { name: 'specimen', role: 'accessory' },
        E: { name: 'lid', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 7. ENERGY SHIELD ──────────────────────────────────
    {
      id: 'energy_shield_16',
      description: 'Portable energy barrier shield.',
      grid: [
        '..EEEEEEEEEE....',
        '.EEEEEEEEEEEEE..',
        '.EEEEEEEEEEEEE..',
        '.EEEEEEEEEEEEE..',
        '.EEEEEEEEEEEEE..',
        '.EEEEEEEEEEEEE..',
        '.EEEEEEEEEEEEE..',
        '..EBBBBBBBBE....',
        '...BBBBBBB......',
        '....BBBBB.......',
        '.....BBB........',
        '......B.........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'field', role: 'eye' },
        B: { name: 'emitter', role: 'body' },
      },
      colors: {
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 8. SERVO MOTOR ────────────────────────────────────
    {
      id: 'servo_motor_16',
      description: 'High-torque servo motor component.',
      grid: [
        '................',
        '................',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..AABBBBBBA.....',
        '..AABBEEBBA.....',
        '..AABBEEBBA.....',
        '..AABBBBBBA.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....GGGG.......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'motor', role: 'body' },
        E: { name: 'shaft', role: 'eye' },
        A: { name: 'mount', role: 'arm' },
        G: { name: 'wire', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 9. TESLA COIL ─────────────────────────────────────
    {
      id: 'tesla_coil_16',
      description: 'Electrical tesla coil emitting arcs.',
      grid: [
        '..E.......E.....',
        '...E.EEE.E......',
        '....EEEEE.......',
        '.....BBB........',
        '....BBBBB.......',
        '....BBBBB.......',
        '....BBBBB.......',
        '.....BBB........',
        '.....BBB........',
        '.....BBB........',
        '....AAAAA.......',
        '...AAAAAAA......',
        '..AAAAAAAAA.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'coil', role: 'body' },
        E: { name: 'arc', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 10. SERVER RACK ───────────────────────────────────
    {
      id: 'server_rack_16',
      description: 'Data server rack with blinking LEDs.',
      grid: [
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBEEEBBEBB....',
        '..BBBBBBBBBB....',
        '..BBEEEBBEBB....',
        '..BBBBBBBBBB....',
        '..BBEEEBBEBB....',
        '..BBBBBBBBBB....',
        '..BBEEEBBEBB....',
        '..BBBBBBBBBB....',
        '..BBEEEBBEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..AAAAAAAAAA....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'rack', role: 'body' },
        E: { name: 'led', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 11. GRAPPLING HOOK ────────────────────────────────
    {
      id: 'grapple_hook_16',
      description: 'Sci-fi magnetic grappling hook gun.',
      grid: [
        '................',
        '.EEE............',
        '.EEEBB..........',
        '...BBBBB........',
        '....BBBBBBB.....',
        '.....BBBBBBB....',
        '......BBBBB.....',
        '......GGGBB.....',
        '......GGGBB.....',
        '......GGGG......',
        '.......AA.......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'hook', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'reel', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 12. MEDI BOT ─────────────────────────────────────
    {
      id: 'medi_bot_16',
      description: 'Small medical robot with healing beam.',
      grid: [
        '................',
        '................',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBBBBBBB.....',
        '..AABBBBBBAA....',
        '..AABBBBBBAA....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '....GGGGGG......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'cross_eye', role: 'eye' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'hover', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 13. PROBE DROID ───────────────────────────────────
    {
      id: 'probe_droid_16',
      description: 'Exploration probe droid with sensor eye.',
      grid: [
        '................',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '...AABBBBAA.....',
        '..AAABBBBAAA....',
        '..AA..BB..AA....',
        '......BB........',
        '.....GGGG.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'sensor', role: 'eye' },
        A: { name: 'appendage', role: 'arm' },
        G: { name: 'thruster', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. JUMP PACK ─────────────────────────────────────
    {
      id: 'jump_pack_16',
      description: 'Short-range jump booster pack.',
      grid: [
        '................',
        '...AAAAAAA......',
        '..AABBBBBBAA....',
        '..AABBBBBBAA....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBEEBB.EEBB...',
        '..BBEEBB.EEBB...',
        '..BBBBBB.BBBB...',
        '...EEEE.EEEE....',
        '....EEE..EEE....',
        '.....E....E.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'tank', role: 'body' },
        A: { name: 'harness', role: 'arm' },
        E: { name: 'nozzle', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. FLASH BANG ────────────────────────────────────
    {
      id: 'flash_bang_16',
      description: 'Sci-fi flash/stun grenade.',
      grid: [
        '................',
        '................',
        '................',
        '.......AA.......',
        '......ABBA......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'flash_core', role: 'eye' },
        A: { name: 'pin', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 16. GRAVITY GENERATOR ─────────────────────────────
    {
      id: 'gravity_generator_16',
      description: 'Artificial gravity field generator.',
      grid: [
        '................',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBB......',
        '..AAAAAAAAAA....',
        '..AAAAAAAAAA....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'field', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#442434', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 17. CRYO GRENADE ──────────────────────────────────
    {
      id: 'cryo_grenade_16',
      description: 'Cryogenic freeze grenade.',
      grid: [
        '................',
        '................',
        '................',
        '.......AA.......',
        '......ABBA......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'cryo_core', role: 'eye' },
        A: { name: 'pin', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 18. EXOSUIT TORSO ─────────────────────────────────
    {
      id: 'exosuit_torso_16',
      description: 'Powered exosuit upper body armor.',
      grid: [
        '................',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..AABBBBBBA.....',
        '..AABBBBBBA.....',
        '.AABBBBBBBBAA...',
        '.AABBBEBBBBAA...',
        '.AABBBEBBBBAA...',
        '.AABBBBBBBBAA...',
        '..AABBBBBBA.....',
        '..AABBBBBBA.....',
        '...BBBBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'plate', role: 'body' },
        E: { name: 'reactor', role: 'eye' },
        A: { name: 'joints', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 19. HARD LIGHT BRIDGE ─────────────────────────────
    {
      id: 'hard_light_bridge_16',
      description: 'Hard light bridge projector.',
      grid: [
        '................',
        '..BB........BB..',
        '..BB........BB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BB........BB..',
        '..BB........BB..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'emitter', role: 'body' },
        E: { name: 'bridge', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 20. WRIST BLADE ───────────────────────────────────
    {
      id: 'wrist_blade_16',
      description: 'Retractable energy wrist blade.',
      grid: [
        '................',
        '.......E........',
        '......EE........',
        '.....EEE........',
        '....EEEE........',
        '...EEEEE........',
        '..EEEEEE........',
        '.EEEEEEE........',
        '..BBBBBB........',
        '..BBBBBBB.......',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '...BBBBBBB......',
        '....BBBBB.......',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'blade', role: 'eye' },
        B: { name: 'gauntlet', role: 'body' },
      },
      colors: {
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
