/**
 * Modern Tech batch 3 — 20 more sci-fi/cyberpunk tech items.
 * Space tech, medical devices, cyberpunk gear, industrial machines.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'modernTech',
  exportNames: { templates: 'MODERN_TECH_BATCH3_TEMPLATES', schemes: 'MODERN_TECH_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. OXYGEN TANK ────────────────────────────────────
    {
      id: 'oxygen_tank_16',
      description: 'Portable oxygen supply tank with gauge.',
      grid: [
        '................',
        '......AA........',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBEEEE......',
        '....BBEEEE......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'tank', role: 'body' },
        E: { name: 'gauge', role: 'eye' },
        A: { name: 'valve', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 2. MEDKIT ─────────────────────────────────────────
    {
      id: 'sci_medkit_16',
      description: 'Futuristic medical kit with healing nanobots.',
      grid: [
        '................',
        '................',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBEEBBB.....',
        '..BBBEEEEBB.....',
        '..BBBBEEBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..AAAAAAAAAA....',
        '..AAAAAAAAAA....',
        '...AAAAAAAA.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'cross', role: 'eye' },
        A: { name: 'bottom', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 3. GRAVITY WELL ───────────────────────────────────
    {
      id: 'gravity_well_16',
      description: 'Gravity distortion field generator.',
      grid: [
        '................',
        '......HH........',
        '.....HHHH.......',
        '....HHHHHH......',
        '...HHHHBBHH.....',
        '..HHHHBBBBHH....',
        '..HHHBBEEBHH....',
        '..HHHBBEEBHH....',
        '..HHHHBBBBHH....',
        '...HHHHBBHH.....',
        '....HHHHHH......',
        '.....HHHH.......',
        '......HH........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'distortion', role: 'accessory' },
        B: { name: 'core', role: 'body' },
        E: { name: 'singularity', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 4. TELEPORTER PAD ─────────────────────────────────
    {
      id: 'teleporter_pad_16',
      description: 'Ground teleportation platform with ring lights.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '...EEEEEEEE.....',
        '..EBBBBBBBBE....',
        '..EBBBBBBBBBE...',
        '.EBBBBBBBBBBE...',
        '.EBBBBEBBBBBE...',
        '.EBBBBBBBBBBE...',
        '..EBBBBBBBBE....',
        '...EEEEEEEE.....',
      ],
      chars: {
        B: { name: 'platform', role: 'body' },
        E: { name: 'ring_light', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 5. MAGNETIC MINE ──────────────────────────────────
    {
      id: 'magnetic_mine_16',
      description: 'Deployable magnetic proximity mine.',
      grid: [
        '................',
        '................',
        '................',
        '.....AAAA.......',
        '....AABBAA......',
        '...AABBBBAA.....',
        '..AABBEEBBA.....',
        '..AABBEEBBA.....',
        '..AABBBBBBAA....',
        '...AABBBBAA.....',
        '....AABBAA......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'sensor', role: 'eye' },
        A: { name: 'spikes', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 6. HACKING TOOL ───────────────────────────────────
    {
      id: 'hacking_tool_16',
      description: 'Cyberpunk hacking multitool device.',
      grid: [
        '................',
        '................',
        '......BB........',
        '.....BBBB.......',
        '....BBEEBB......',
        '....BBEEBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '......BB........',
        '......GG........',
        '......GG........',
        '......GG........',
        '......GG........',
        '.....AAAA.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'head', role: 'body' },
        E: { name: 'display', role: 'eye' },
        G: { name: 'shaft', role: 'belt' },
        A: { name: 'grip', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 7. CLOAKING DEVICE ────────────────────────────────
    {
      id: 'cloaking_device_16',
      description: 'Personal cloaking / invisibility generator.',
      grid: [
        '................',
        '................',
        '...HHHHHHHH.....',
        '..H.BBBBBB.H....',
        '..H.BBBBBB.H....',
        '..H.BBEEBB.H....',
        '..H.BBEEBB.H....',
        '..H.BBBBBB.H....',
        '..H.BBBBBB.H....',
        '...HHHHHHHH.....',
        '.....AAAA.......',
        '......AA........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'core', role: 'body' },
        E: { name: 'crystal', role: 'eye' },
        H: { name: 'field', role: 'accessory' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 8. POWER CELL PACK ────────────────────────────────
    {
      id: 'power_cell_pack_16',
      description: 'Pack of three power cells in a carrier.',
      grid: [
        '................',
        '................',
        '..BBB.BBB.BBB...',
        '..BEB.BEB.BEB...',
        '..BEB.BEB.BEB...',
        '..BEB.BEB.BEB...',
        '..BEB.BEB.BEB...',
        '..BBB.BBB.BBB...',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cell', role: 'body' },
        E: { name: 'charge', role: 'eye' },
        A: { name: 'carrier', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 9. REPAIR DRONE ───────────────────────────────────
    {
      id: 'repair_drone_16',
      description: 'Small autonomous repair bot.',
      grid: [
        '................',
        '................',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBEEEBB.....',
        '...BBBEEEBB.....',
        '...BBBBBBBB.....',
        '..AABBBBBBAA....',
        '..AABBBBBBAA....',
        '...AAABBAAA.....',
        '......GG........',
        '.....GGGG.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'welder', role: 'eye' },
        A: { name: 'arms', role: 'arm' },
        G: { name: 'thruster', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. STIM INJECTOR ─────────────────────────────────
    {
      id: 'stim_injector_16',
      description: 'Medical stimulant auto-injector.',
      grid: [
        '................',
        '.....AAAA.......',
        '....AABBAA......',
        '....BBBBBB......',
        '...BBBBBBB......',
        '...BBBEEBB......',
        '...BBBEEBB......',
        '...BBBEEBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '....BBBBBB......',
        '.....GGGG.......',
        '.....GGGG.......',
        '......GG........',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'liquid', role: 'eye' },
        A: { name: 'plunger', role: 'arm' },
        G: { name: 'needle', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 11. CIRCUIT BOARD ─────────────────────────────────
    {
      id: 'circuit_board_16',
      description: 'Circuit board component with chips.',
      grid: [
        '................',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBAABBBBBB....',
        '..BBAABBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBAABBBB....',
        '..BBBBAABBBB....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'board', role: 'body' },
        E: { name: 'chip', role: 'eye' },
        A: { name: 'trace', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 12. ANTENNA TOWER ─────────────────────────────────
    {
      id: 'antenna_tower_16',
      description: 'Communication antenna tower.',
      grid: [
        '.......E........',
        '......EBE.......',
        '......BBB.......',
        '.....AABAA......',
        '......BBB.......',
        '......BBB.......',
        '.....AABAA......',
        '......BBB.......',
        '......BBB.......',
        '.....AABAA......',
        '......BBB.......',
        '......BBB.......',
        '.....GGGGG......',
        '....GGGGGGG.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'mast', role: 'body' },
        E: { name: 'dish', role: 'eye' },
        A: { name: 'cross_beam', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 13. BIOSCANNER ────────────────────────────────────
    {
      id: 'bioscanner_16',
      description: 'Handheld biological scanning device.',
      grid: [
        '................',
        '................',
        '...BBBBBBB......',
        '..BBEEEEEEB.....',
        '..BBEEEEEEB.....',
        '..BBEEEEEEB.....',
        '..BBBBBBBBB.....',
        '...BBBBBBB......',
        '....GGGG........',
        '....GGGG........',
        '....GGGG........',
        '.....GG.........',
        '......A.........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'display', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'antenna', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 14. SHIELD BATTERY ────────────────────────────────
    {
      id: 'shield_battery_16',
      description: 'Rechargeable energy shield battery.',
      grid: [
        '................',
        '................',
        '......AA........',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BEEEEB......',
        '....BEEEEB......',
        '....BEEEEB......',
        '....BEEEEB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'casing', role: 'body' },
        E: { name: 'charge', role: 'eye' },
        A: { name: 'terminal', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 15. THERMAL SCOPE ─────────────────────────────────
    {
      id: 'thermal_scope_16',
      description: 'Thermal vision scope / monocular.',
      grid: [
        '................',
        '................',
        '................',
        '..BBBBB.........',
        '.BBBBBBB........',
        '.BBEEEEBB.......',
        '.BBEEEEBB.......',
        '.BBBBBBBBB......',
        '..BBBBBBBBB.....',
        '....BBBBBBB.....',
        '......BBB.......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'lens', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. MINING LASER ──────────────────────────────────
    {
      id: 'mining_laser_16',
      description: 'Industrial mining laser tool.',
      grid: [
        '................',
        '................',
        '..EE............',
        '..EEBBB.........',
        '..BBBBBBB.......',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBB.......',
        '....GGGBB.......',
        '....GGGG........',
        '....GGGG........',
        '.....AAA........',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'emitter', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'battery', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 17. HOLOGRAPHIC MAP ───────────────────────────────
    {
      id: 'holo_map_16',
      description: 'Portable holographic map projector.',
      grid: [
        '....HHHHHHH.....',
        '...HHHHHHHHH....',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '...HHHHHHHHH....',
        '....HHHHHHH.....',
        '......BB........',
        '.....BBBB.......',
        '....BBEEBB......',
        '....BBBBBB......',
        '....AAAAAA......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hologram', role: 'accessory' },
        B: { name: 'projector', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 18. TRACTOR BEAM ──────────────────────────────────
    {
      id: 'tractor_beam_16',
      description: 'Tractor beam emitter device.',
      grid: [
        '................',
        '................',
        '......EE........',
        '.....EEEE.......',
        '....EEEEEE......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....GGGG.......',
        '.....GGGG.......',
        '......AA........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'beam', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'control', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 19. THERMAL DETONATOR ─────────────────────────────
    {
      id: 'thermal_detonator_16',
      description: 'Compact thermal explosive device.',
      grid: [
        '................',
        '................',
        '................',
        '......AA........',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBBBBB......',
        '...BBBEBB.B.....',
        '...BBBEBB.B.....',
        '...BBBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'trigger', role: 'eye' },
        A: { name: 'pin', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. QUANTUM COMPUTER ──────────────────────────────
    {
      id: 'quantum_computer_16',
      description: 'Miniature quantum computing unit.',
      grid: [
        '................',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..AAAAAAAAAA....',
        '..AAAAAAAAAA....',
        '...AAAAAAAA.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'qubit', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

  ],
};

export default batch;
