/**
 * Modern Tech batch 1 — 20 new futuristic/sci-fi tech gadgets.
 * Drones, holograms, laser guns, energy cells, scanners, etc.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'modernTech',
  exportNames: { templates: 'MODERN_TECH_BATCH1_TEMPLATES', schemes: 'MODERN_TECH_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. COMBAT DRONE ───────────────────────────────────
    {
      id: 'combat_drone_16',
      description: 'Small military drone with rotors and camera eye.',
      grid: [
        '................',
        '................',
        '..R..........R..',
        '..RR........RR..',
        '...RR.BBBB.RR...',
        '....RBBBBBBR....',
        '....BBBEEBBBB...',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...AABBBBBBAA...',
        '....AABBBBAA....',
        '.....AAAAAA.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        R: { name: 'rotor', role: 'arm' },
        E: { name: 'camera', role: 'eye' },
        A: { name: 'undercarriage', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 2. HOLOGRAM PROJECTOR ─────────────────────────────
    {
      id: 'hologram_projector_16',
      description: 'Compact device projecting a holographic image upward.',
      grid: [
        '......HHHH......',
        '.....HHHHHH.....',
        '......HHHH......',
        '.......HH.......',
        '........H.......',
        '................',
        '....BBBBBBBB....',
        '...BBEEEEBBBB...',
        '...BBBBBBBBBB...',
        '...AABBBBBBAA...',
        '....AAAAAAAA....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'base_unit', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        H: { name: 'hologram', role: 'accessory' },
        A: { name: 'stand', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 3. LASER PISTOL ───────────────────────────────────
    {
      id: 'laser_pistol_16',
      description: 'Compact sci-fi laser pistol with glowing barrel.',
      grid: [
        '................',
        '................',
        '................',
        '..EEBBBBBBB.....',
        '..EEBBBBBBBBB...',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '......GGGBBBB...',
        '......GGGBB.....',
        '......GGGG......',
        '......GGGG......',
        '......AAAA......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'barrel', role: 'body' },
        E: { name: 'emitter', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'magazine', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 4. ENERGY CELL ────────────────────────────────────
    {
      id: 'energy_cell_16',
      description: 'Glowing energy cell / battery pack.',
      grid: [
        '................',
        '................',
        '.....AAAAAA.....',
        '....AABBBBAA....',
        '...AABBBBBBAA...',
        '...BBEEEEBBBB...',
        '...BBEEEEBBBB...',
        '...BBEEEEBBBB...',
        '...BBEEEEBBBB...',
        '...BBBBBBBBBB...',
        '...AABBBBBBAA...',
        '....AABBBBAA....',
        '.....AAAAAA.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'casing', role: 'body' },
        E: { name: 'energy_core', role: 'eye' },
        A: { name: 'terminal', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 5. SCANNER DEVICE ─────────────────────────────────
    {
      id: 'scanner_device_16',
      description: 'Handheld scanner with screen and antenna.',
      grid: [
        '......AA........',
        '......AA........',
        '......AA........',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBBBBBBB.....',
        '....GGGGGG......',
        '....GGGGGG......',
        '....GGGGGG......',
        '.....GGGG.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'antenna', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 6. PLASMA GRENADE ─────────────────────────────────
    {
      id: 'plasma_grenade_16',
      description: 'Spherical plasma grenade with glowing core.',
      grid: [
        '................',
        '................',
        '.......AA.......',
        '......AAAA......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBEEBBB....',
        '...BBBEEEBBB....',
        '...BBBEEEBBB....',
        '...BBBBEEBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'plasma_core', role: 'eye' },
        A: { name: 'detonator', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 7. MECH ARM ───────────────────────────────────────
    {
      id: 'mech_arm_16',
      description: 'Robotic mechanical arm with joints and claw.',
      grid: [
        '................',
        '..BB............',
        '..BBB...........',
        '..ABBA..........',
        '...ABBA.........',
        '....ABBA........',
        '.....ABBA.......',
        '......ABBA......',
        '.......BBBB.....',
        '.......BBBBB....',
        '......EEBBEE....',
        '.....EE..BBEE...',
        '.....E....BE....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'arm_segment', role: 'body' },
        A: { name: 'joint', role: 'arm' },
        E: { name: 'claw', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 8. SHIELD GENERATOR ───────────────────────────────
    {
      id: 'shield_generator_16',
      description: 'Personal shield generator emitting a force field.',
      grid: [
        '....HHHHHHHH....',
        '...H........H...',
        '..H..........H..',
        '..H..BBBBBB..H..',
        '..H..BEEEEB..H..',
        '..H..BEEEEB..H..',
        '..H..BBBBBB..H..',
        '..H..AABBAA..H..',
        '..H...ABBA...H..',
        '...H..ABBA..H...',
        '....HHHHHHHH....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'generator', role: 'body' },
        E: { name: 'core', role: 'eye' },
        A: { name: 'base', role: 'arm' },
        H: { name: 'shield_field', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 9. HOVERBOARD ─────────────────────────────────────
    {
      id: 'hoverboard_16',
      description: 'Futuristic hoverboard with glowing thrust pads.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...EEEE..EEEE...',
        '....EE....EE....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'deck', role: 'body' },
        E: { name: 'thrust', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 10. CYBER HELMET ──────────────────────────────────
    {
      id: 'cyber_helmet_16',
      description: 'Full-face cyber helmet with visor.',
      grid: [
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BEEEEEEEEB...',
        '...BEEEEEEEEB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBAAABBB....',
        '....BBAABBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'visor', role: 'eye' },
        A: { name: 'ventilation', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 11. ROCKET LAUNCHER ───────────────────────────────
    {
      id: 'rocket_launcher_16',
      description: 'Shoulder-mounted rocket launcher tube.',
      grid: [
        '................',
        '................',
        '................',
        'EEBBBBBBBBB.....',
        'EEBBBBBBBBBBB...',
        'BBBBBBBBBBBBBBB.',
        'BBBBBBBBBBBBBBB.',
        'EEBBBBBBBBBBB...',
        'EEBBBBBBBBB.....',
        '......GGGG......',
        '......GGGG......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'tube', role: 'body' },
        E: { name: 'muzzle', role: 'eye' },
        G: { name: 'grip', role: 'belt' },
        A: { name: 'shoulder_rest', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 12. SATELLITE DISH ────────────────────────────────
    {
      id: 'satellite_dish_16',
      description: 'Satellite communication dish on a stand.',
      grid: [
        '..BBBBBBBB......',
        '.BBBBBBBBBB.....',
        'BBBBBBBBBBBB....',
        'BBBBBBBBBBB.....',
        '.BBBBBEBBBB.....',
        '..BBBBBBB.......',
        '....AABBA.......',
        '.....AABA.......',
        '......AA........',
        '......AA........',
        '......AA........',
        '.....GGGG.......',
        '....GGGGGG......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'dish', role: 'body' },
        E: { name: 'receiver', role: 'eye' },
        A: { name: 'arm_support', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 13. POWER ARMOR CHEST ─────────────────────────────
    {
      id: 'power_armor_chest_16',
      description: 'Heavy-duty power armor chestplate with reactor core.',
      grid: [
        '................',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '.BBBBBBBBBBB....',
        '.BBBBEEBBBBBB...',
        '.BBBBEEBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '.AABBBBBBBBAA...',
        '..AABBBBBBAA....',
        '...AABBBBAA.....',
        '....AABBAA......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'plate', role: 'body' },
        E: { name: 'reactor', role: 'eye' },
        A: { name: 'joints', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 14. TABLET DEVICE ─────────────────────────────────
    {
      id: 'tablet_device_16',
      description: 'Sleek handheld tablet with touch screen.',
      grid: [
        '................',
        '................',
        '...BBBBBBBB.....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBBBBBBBBB....',
        '..BBBBABBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        A: { name: 'button', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 15. SECURITY CAMERA ───────────────────────────────
    {
      id: 'security_camera_16',
      description: 'Wall-mounted security camera with red light.',
      grid: [
        '................',
        '..AAAA..........',
        '..AAAA..........',
        '...AABB.........',
        '....ABBB........',
        '.....BBBBB......',
        '....BBBBBBB.....',
        '...BBBBEBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        A: { name: 'mount', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

    // ─── 16. NANOBOT SWARM ─────────────────────────────────
    {
      id: 'nanobot_swarm_16',
      description: 'Cloud of tiny nanobots forming a cluster.',
      grid: [
        '................',
        '.......E........',
        '....E.EEE.E.....',
        '...EEEBBBEE.....',
        '...EBBBBBBE.....',
        '..EBBBBBBBBE....',
        '..EBBBBBBBBE....',
        '..EBBBBBBBBBE...',
        '..EBBBBBBBBE....',
        '..EBBBBBBBBE....',
        '...EBBBBBBE.....',
        '...EEEBBBEE.....',
        '....E.EEE.E.....',
        '.......E........',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'swarm_core', role: 'body' },
        E: { name: 'outer_bots', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 17. GRAVITY BOOTS ─────────────────────────────────
    {
      id: 'gravity_boots_16',
      description: 'Pair of anti-gravity boots with hover pads.',
      grid: [
        '................',
        '................',
        '..BBB....BBB....',
        '..BBB....BBB....',
        '..BBB....BBB....',
        '..BBBB..BBBB....',
        '..BBBB..BBBB....',
        '.BBBBB.BBBBB....',
        '.BBBBB.BBBBB....',
        '.BBBBB.BBBBB....',
        '.EEEEE.EEEEE....',
        '..EEE...EEE.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'boot', role: 'body' },
        E: { name: 'hover_pad', role: 'eye' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#6dc2ca', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 18. DATA CHIP ─────────────────────────────────────
    {
      id: 'data_chip_16',
      description: 'Small data storage chip with circuit traces.',
      grid: [
        '................',
        '................',
        '................',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '..AABBEEBBAAA...',
        '..AABBBBBBAAA...',
        '..AABBBBBBAAA...',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '....AAAAAA......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chip_body', role: 'body' },
        E: { name: 'circuit', role: 'eye' },
        A: { name: 'pins', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 19. WARP GATE ─────────────────────────────────────
    {
      id: 'warp_gate_16',
      description: 'Small portal / warp gate device.',
      grid: [
        '................',
        '.....BBBB.......',
        '...BBBBBBBB.....',
        '..BBBEEEEBBBB...',
        '..BBEEEEEEBB....',
        '.BBEEEEEEEEBB...',
        '.BBEEEEEEEEBB...',
        '.BBEEEEEEEEBB...',
        '.BBEEEEEEEEBB...',
        '..BBEEEEEEBB....',
        '..BBBEEEEBBBB...',
        '...BBBBBBBB.....',
        '.....BBBB.......',
        '....AAAAAA......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'portal', role: 'eye' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        eye:       { shadow: '#442434', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. TURRET ────────────────────────────────────────
    {
      id: 'auto_turret_16',
      description: 'Automated defense turret with rotating barrel.',
      grid: [
        '................',
        '................',
        '..EEBBB.........',
        '..EEBBBBB.......',
        '..BBBBBBBBB.....',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '....BBBBB.......',
        '...AABBBAA......',
        '..AABBBBBA......',
        '..AABBBBBA......',
        '.AAAAAAAAAA.....',
        '.GGGGGGGGGG.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'turret_body', role: 'body' },
        E: { name: 'barrel', role: 'eye' },
        A: { name: 'mount', role: 'arm' },
        G: { name: 'base_plate', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        leg:       { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
      },
    },

  ],
};

export default batch;
