/**
 * Retro Tech batch 2 — 20 vintage tech items: computers, gaming, media.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'retroTech',
  exportNames: { templates: 'RETRO_TECH_BATCH2_TEMPLATES', schemes: 'RETRO_TECH_BATCH2_COLOR_SCHEMES' },
  templates: [

    {
      id: 'crt_monitor_16',
      description: 'Bulky CRT computer monitor with green phosphor screen.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBHBBBBBBB..',
        '....GGGGGGGG....',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        H: { name: 'power_led', role: 'accessory' },
        G: { name: 'stand', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        accessory: { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'floppy_disk_16',
      description: '3.5 inch floppy disk with metal slider.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHBB..',
        '..BHHHHHHHHHBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBEEEEBBB...',
        '..BBBEEEEEBB....',
        '..BBBEEEEEBB....',
        '..BBBBEEEEBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        H: { name: 'slider', role: 'head' },
        E: { name: 'label', role: 'eye' },
      },
      colors: {
        body:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#757161' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        eye:   { shadow: '#595652', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'game_cartridge_16',
      description: 'Retro game cartridge with label art area.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BEEEEEEEBB...',
        '...BEEEEEEEBB...',
        '...BEEEEEEEBB...',
        '...BEEEEEEEBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBHHBBBBHHBB..',
        '..BBHHBBBBHHBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'label', role: 'eye' },
        H: { name: 'contacts', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'handheld_console_16',
      description: 'Portable handheld gaming console with d-pad.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBBBBBBBBB...',
        '...BHHBBBBABB...',
        '...BHHBBBBABB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        H: { name: 'dpad', role: 'head' },
        A: { name: 'buttons', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'arcade_stick_16',
      description: 'Classic arcade joystick with buttons.',
      grid: [
        '................',
        '......HH........',
        '......HH........',
        '......HH........',
        '......HH........',
        '.....HHHH.......',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBAABBB...',
        '..BBBBBBAABBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'panel', role: 'body' },
        H: { name: 'stick', role: 'head' },
        A: { name: 'buttons', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        head:      { shadow: '#30346d', base: '#595652', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#757161' },
      },
    },

    {
      id: 'tape_recorder_16',
      description: 'Portable cassette tape recorder with mic.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEHHEEBB....',
        '..BBEEHHEEBB....',
        '..BBEEHHEEBB....',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBAABBBBABBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'reels', role: 'eye' },
        H: { name: 'tape_window', role: 'head' },
        A: { name: 'buttons', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'crt_tv_16',
      description: 'Retro CRT television with antenna and dials.',
      grid: [
        '.....HH..HH.....',
        '......HHHH......',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        H: { name: 'antenna', role: 'head' },
        A: { name: 'dials', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        accessory: { shadow: '#595652', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'dot_matrix_printer_16',
      description: 'Noisy dot matrix printer with paper feed.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBABBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        H: { name: 'paper', role: 'head' },
        E: { name: 'slot', role: 'eye' },
        A: { name: 'led', role: 'accessory' },
        G: { name: 'tray', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#d2aa99' },
        head:      { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'dial_up_modem_16',
      description: 'External dial-up modem box with LED indicators.',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BAABBBBBBABB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'vents', role: 'eye' },
        A: { name: 'leds', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'overhead_projector_16',
      description: 'Classroom overhead projector with glass plate.',
      grid: [
        '......HHHH......',
        '.....HHHHHH.....',
        '......HHHH......',
        '.......HH.......',
        '.......HH.......',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'base', role: 'body' },
        E: { name: 'glass', role: 'eye' },
        H: { name: 'projector_head', role: 'head' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#6dc2ca', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'cathode_tube_16',
      description: 'Vacuum tube / thermionic valve for vintage electronics.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHEEEEHH....',
        '....HEEEEEEH....',
        '....HEEEEEEH....',
        '....HEEEEEEH....',
        '....HEEEEEEH....',
        '....HHEEEEHH....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....GGGGGGGG....',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'glass', role: 'head' },
        E: { name: 'filament', role: 'eye' },
        B: { name: 'base_ring', role: 'body' },
        G: { name: 'pins', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:   { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'reel_to_reel_16',
      description: 'Reel-to-reel tape deck with two spools.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBEEBB..EEBB..',
        '..BEEEBBBEEEEB..',
        '..BEEEBBBEEEEB..',
        '..BBEEBB..EEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHHBBB..',
        '..BBBBBBBBBBBB..',
        '..BBAABBBBABBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'reels', role: 'eye' },
        H: { name: 'tape_path', role: 'head' },
        A: { name: 'controls', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#8b8e8a' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'nixie_clock_16',
      description: 'Nixie tube clock display with warm orange digits.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BHEEBHEEBHEB..',
        '..BHEEBHEEBHEB..',
        '..BHEEBHEEBHEB..',
        '..BHEEBHEEBHEB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        H: { name: 'digits', role: 'head' },
        E: { name: 'tube_glass', role: 'eye' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#30346d', base: '#442434', highlight: '#595652' },
        leg:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'betamax_player_16',
      description: 'Betamax video cassette player.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHABBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'slot', role: 'eye' },
        H: { name: 'buttons', role: 'head' },
        A: { name: 'display', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        eye:       { shadow: '#30346d', base: '#595652', highlight: '#757161' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'oscilloscope_16',
      description: 'Analog oscilloscope with glowing green waveform.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BEEEEEEEEABB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHHBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        A: { name: 'knobs', role: 'accessory' },
        H: { name: 'controls', role: 'head' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'punch_card_16',
      description: 'Vintage computer punch card with hole pattern.',
      grid: [
        '................',
        '.BBBBBBBBBBBBB..',
        '.BHHBHBHHBHBHB..',
        '.BBBBBBBBBBBB...',
        '.BHHBHHBHBHHB...',
        '.BBBBBBBBBBBB...',
        '.BHBHHBHHBHBB...',
        '.BBBBBBBBBBBB...',
        '.BHHBHBHBHHBB...',
        '.BBBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'card', role: 'body' },
        H: { name: 'holes', role: 'head' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
      },
    },

    {
      id: 'abacus_16',
      description: 'Traditional abacus calculation tool with colored beads.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..B..........B..',
        '..BHHHH..HHHBB..',
        '..B..........B..',
        '..BEEE....EEBB..',
        '..B..........B..',
        '..BAAA..AAABBB..',
        '..B..........B..',
        '..BGGG....GGBB..',
        '..B..........B..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        H: { name: 'beads_top', role: 'head' },
        E: { name: 'beads_mid', role: 'eye' },
        A: { name: 'beads_bottom', role: 'accessory' },
        G: { name: 'beads_base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#442434', base: '#757161', highlight: '#d2aa99' },
      },
    },

    {
      id: 'fax_machine_16',
      description: 'Office fax machine with paper tray and handset.',
      grid: [
        '..HHHHHHHH......',
        '..HHHHHHHH......',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAABBBBBB.',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        H: { name: 'paper_tray', role: 'head' },
        E: { name: 'display', role: 'eye' },
        A: { name: 'keypad', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#d2aa99' },
        head:      { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#346524', highlight: '#6daa2c' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'analog_meter_16',
      description: 'Vintage analog meter with needle gauge.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEHEEEEBB..',
        '..BEEEHHEEEEEB..',
        '..BEEHEEEEEEEB..',
        '..BBBBBBBBBBBB..',
        '..BBBBAABBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'dial_face', role: 'eye' },
        H: { name: 'needle', role: 'head' },
        A: { name: 'terminals', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
      },
    },

    {
      id: 'polaroid_camera_16',
      description: 'Instant Polaroid-style camera with flash.',
      grid: [
        '................',
        '....HH..........',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBEEEEBBB...',
        '..BBBEEEEEEBB...',
        '..BBBEEEEEEBB...',
        '..BBBBEEEEBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBAABBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        H: { name: 'flash', role: 'head' },
        A: { name: 'shutter', role: 'accessory' },
        G: { name: 'output_slot', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#595652', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

  ],
};

export default batch;
