/**
 * Retro Tech batch 1 — 20 vintage/nostalgic 80s-90s tech items.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'retroTech',
  exportNames: { templates: 'RETRO_TECH_BATCH1_TEMPLATES', schemes: 'RETRO_TECH_BATCH1_COLOR_SCHEMES' },
  templates: [

    {
      id: 'record_player_16',
      description: 'Vintage vinyl record player turntable.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBHBBBB..',
        '..BBBEEEEEBBB...',
        '..BBEEEEEEEEBB..',
        '..BBEEEAEEEBB...',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBEEEEEBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'platter', role: 'eye' },
        A: { name: 'spindle', role: 'arm' },
        H: { name: 'tonearm', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'vhs_tape_16',
      description: 'VHS video cassette tape.',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEBB..EEBB..',
        '..BBEEBB..EEBB..',
        '..BBEEBB..EEBB..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAAAAABB..',
        '..BBAAAAAAAABB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shell', role: 'body' },
        E: { name: 'reel', role: 'eye' },
        A: { name: 'tape', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'boombox_16',
      description: 'Portable boombox ghetto blaster.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBB.',
        '.BBEEBBB.BBEEBB.',
        '.BBEEBBB.BBEEBB.',
        '.BBEEBBB.BBEEBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBAAAAAAAAABB..',
        '.BBAAAAAAAAABB..',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '..GGG......GGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'speaker', role: 'eye' },
        A: { name: 'controls', role: 'arm' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'walkman_16',
      description: 'Portable cassette Walkman.',
      grid: [
        '................',
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBEEEEEEBB...',
        '...BBBBBBBBBB...',
        '...BBAAAAABBB...',
        '...BBAAAAABBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '......HH........',
        '.....HHHH.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'buttons', role: 'arm' },
        H: { name: 'headphone', role: 'head' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'typewriter_16',
      description: 'Classic mechanical typewriter.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '.BBEEBBEEBBEEBB.',
        '.BBEEBBEEBBEEBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBEEBBEEBBEEBB.',
        '.BBEEBBEEBBEEBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBBAAAAAABBBBB.',
        '.BBBBBBBBBBBBBB.',
        '..GGG......GGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'keys', role: 'eye' },
        H: { name: 'paper', role: 'head' },
        A: { name: 'spacebar', role: 'arm' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'film_reel_16',
      description: 'Movie film reel with sprockets.',
      grid: [
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBEEBB.EEBBB..',
        '..BBBBBABBBBB...',
        '..BBEEBB.EEBBB..',
        '..BBBBBBBBBBB...',
        '...BBBEEBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'reel', role: 'body' },
        E: { name: 'hole', role: 'eye' },
        A: { name: 'hub', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'old_radio_16',
      description: 'Vintage wooden table radio.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHBBBBBB..',
        '..BBHHHHBBBBBB..',
        '..BBAABBAAABBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cabinet', role: 'body' },
        E: { name: 'grille', role: 'eye' },
        H: { name: 'dial', role: 'head' },
        A: { name: 'knob', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'tube_amplifier_16',
      description: 'Vacuum tube audio amplifier.',
      grid: [
        '................',
        '....EE.EE.EE....',
        '...EEEEEEEEEE...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAAABBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'tubes', role: 'eye' },
        A: { name: 'knobs', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'phonograph_16',
      description: 'Antique phonograph with horn.',
      grid: [
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '.HHHHHHHHHH.....',
        '..HHHHHHHH......',
        '...HHHHH........',
        '....AAA.........',
        '.....AA.........',
        '.....AA.........',
        '....BBBB........',
        '...BBEEBB.......',
        '...BBEEBB.......',
        '...BBBBBB.......',
        '..GGGGGGGG......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'horn', role: 'head' },
        A: { name: 'neck', role: 'arm' },
        B: { name: 'base_unit', role: 'body' },
        E: { name: 'platter', role: 'eye' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'vinyl_record_16',
      description: 'Vinyl LP record disc.',
      grid: [
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBABBBB..',
        '..BBBBBABBBBBB..',
        '..BBBBBABBBBBB..',
        '..BBBBBAAABBBB..',
        '..BBBBBABBBBBB..',
        '..BBBBBABBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'vinyl', role: 'body' },
        A: { name: 'label', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'jukebox_16',
      description: 'Classic diner jukebox.',
      grid: [
        '....EEEEEE......',
        '...EEEEEEEE.....',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHBBBB..',
        '..BBHHHHHHBBBB..',
        '..BBHHHHHHBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAAAAABB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cabinet', role: 'body' },
        E: { name: 'dome', role: 'eye' },
        H: { name: 'display', role: 'head' },
        A: { name: 'buttons', role: 'arm' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'rotary_phone_16',
      description: 'Classic rotary telephone.',
      grid: [
        '................',
        '.HHHH....HHHH...',
        '.HBBHHHHHBBHH...',
        '..HHHHHHHHHH....',
        '..BBBBBBBBBB....',
        '..BBEEEEEEBB....',
        '..BBEEEEEEBB....',
        '..BBEEEAEEBB....',
        '..BBEEEEEEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...GGGGGGGG.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'dial', role: 'eye' },
        A: { name: 'center', role: 'arm' },
        H: { name: 'handset', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'calculator_retro_16',
      description: 'Retro pocket calculator.',
      grid: [
        '................',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBEEEEBB.....',
        '...BBEEEEBB.....',
        '...BBBBBBBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBHHHHBB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'display', role: 'eye' },
        H: { name: 'buttons', role: 'head' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'slide_projector_16',
      description: 'Carousel slide projector.',
      grid: [
        '......HHHHHH....',
        '.....HHHHHHHH...',
        '....HHHHHHHHH...',
        '...BBBBBBBBBBB..',
        '..BBBBBBBBBBBBB.',
        '..BBEBBBBBBBBBB.',
        '..BBEBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '...BBBBBBBBBBB..',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        H: { name: 'carousel', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'telegraph_key_16',
      description: 'Morse code telegraph key.',
      grid: [
        '................',
        '................',
        '........HH......',
        '.......HHHH.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBEEEBBBBBB...',
        '..BBEEEBBBBBB...',
        '..BBBBBBBBBBB...',
        '..AAAAAAAAAAAA..',
        '..AAAAAAAAAAAA..',
        '..GG........GG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'base', role: 'body' },
        E: { name: 'key', role: 'eye' },
        H: { name: 'arm', role: 'head' },
        A: { name: 'board', role: 'arm' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'pager_16',
      description: 'Vintage pager beeper device.',
      grid: [
        '................',
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBEEEEBB....',
        '....BBBBBBBB....',
        '....BBHHHHBB....',
        '....BBHHHHBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        H: { name: 'buttons', role: 'head' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'cassette_deck_16',
      description: 'Cassette tape deck player.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEBBB.EEBB..',
        '..BBEEBBB.EEBB..',
        '..BBBBBBBBBBBB..',
        '..BBAAAAAAAABB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        E: { name: 'reel', role: 'eye' },
        A: { name: 'tape_window', role: 'arm' },
        H: { name: 'buttons', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'pinball_machine_16',
      description: 'Arcade pinball machine.',
      grid: [
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBEBBBBEBB....',
        '..BBBBHBBBBB....',
        '..BBEBBBBEBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBAAAABBBB....',
        '..BBBBBBBBBB....',
        '..GGG....GGG....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cabinet', role: 'body' },
        E: { name: 'backglass', role: 'eye' },
        H: { name: 'ball', role: 'head' },
        A: { name: 'buttons', role: 'arm' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    {
      id: 'film_camera_16',
      description: 'Vintage 35mm film camera.',
      grid: [
        '................',
        '.....HH.........',
        '....HHHH........',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEAAEEBB...',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        A: { name: 'pupil', role: 'arm' },
        H: { name: 'viewfinder', role: 'head' },
      },
      colors: {
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'antenna_rabbit_16',
      description: 'Rabbit ear TV antenna.',
      grid: [
        '.EE..........EE.',
        '..EE........EE..',
        '...EE......EE...',
        '....EE....EE....',
        '.....EE..EE.....',
        '......EEEE......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......AAAA......',
        '.....AAAAAAA....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'ears', role: 'eye' },
        B: { name: 'joint', role: 'body' },
        A: { name: 'base', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

  ],
};

export default batch;
