/**
 * Retro Tech batch 3 — 20 vintage tech: audio, computing, photography, electronics.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'retroTech',
  exportNames: { templates: 'RETRO_TECH_BATCH3_TEMPLATES', schemes: 'RETRO_TECH_BATCH3_COLOR_SCHEMES' },
  templates: [

    {
      id: 'tube_radio_16',
      description: 'Art deco style vintage tube radio with dial.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BEEEEBBEEEBB..',
        '..BEEEEBBEEEBB..',
        '..BEEEEBBEEEBB..',
        '..BEEEEBBEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHHBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cabinet', role: 'body' },
        E: { name: 'speaker_grille', role: 'eye' },
        H: { name: 'dial', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'scientific_calc_16',
      description: 'Vintage scientific calculator with LCD display.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BEEEEEEEBB...',
        '...BEEEEEEEBB...',
        '...BBBBBBBBBB...',
        '...BHHHHHHHHB...',
        '...BHHHHHHHHB...',
        '...BHHHHHHHHB...',
        '...BHHHHHHHHB...',
        '...BHHHHHHHHB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'display', role: 'eye' },
        H: { name: 'keys', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'transistor_radio_16',
      description: 'Pocket transistor radio with round speaker.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBEEEEEBBB...',
        '...BEEEEEEEEB...',
        '...BEEEEEEEEB...',
        '...BEEEEEEEEB...',
        '...BBEEEEEBBB...',
        '...BBBBBBBBBB...',
        '...BBHHBBHBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'speaker', role: 'eye' },
        H: { name: 'dials', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
      },
    },

    {
      id: 'analog_clock_16',
      description: 'Wall-mounted analog clock with roman numerals.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBEEEEEEEEBB..',
        '..BEEEEEEEEEEB..',
        '..BEEEEHEEEEBB..',
        '..BEEEEHEEEEBB..',
        '..BEEEEHHHEEEB..',
        '..BEEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'face', role: 'eye' },
        H: { name: 'hands', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'light_bulb_16',
      description: 'Classic incandescent light bulb with filament.',
      grid: [
        '................',
        '.....EEEEEE.....',
        '....EEEEEEEE....',
        '...EEEEEEEEEE...',
        '...EEEEHHEEEE...',
        '...EEEHHHHEEE...',
        '...EEEEHHEEEE...',
        '...EEEEEEEEEE...',
        '....EEEEEEEE....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.....GGGGGG.....',
        '......GGGG......',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'glass', role: 'eye' },
        H: { name: 'filament', role: 'head' },
        B: { name: 'base_ring', role: 'body' },
        G: { name: 'screw_base', role: 'leg' },
      },
      colors: {
        eye:   { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'compass_16',
      description: 'Vintage brass compass with cardinal directions.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBEEEEEEEEBB..',
        '..BEEEEEEEEEEB..',
        '..BEEEEHEEEEBB..',
        '..BEEEHHHEEEBB..',
        '..BEEEEHEEEEBB..',
        '..BEEEEEEEEEEB..',
        '..BBEEEEEEEEBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'dial', role: 'eye' },
        H: { name: 'needle', role: 'head' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'slide_rule_16',
      description: 'Analog slide rule calculation instrument.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BHHHHHHHHHBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'slider', role: 'eye' },
        H: { name: 'scales', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'cassette_walkman_16',
      description: 'Portable cassette Walkman player with headphone jack.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBEEHHEEBB...',
        '...BBEEHHEEBB...',
        '...BBEEHHEEBB...',
        '...BBBBBBBBBB...',
        '...BAAABBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBHBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'reels', role: 'eye' },
        H: { name: 'window', role: 'head' },
        A: { name: 'buttons', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
      },
    },

    {
      id: 'darkroom_enlarger_16',
      description: 'Photographic darkroom enlarger for print development.',
      grid: [
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '......EEEE......',
        '......EEEE......',
        '.......BB.......',
        '.......BB.......',
        '.......BB.......',
        '.......BB.......',
        '.......BB.......',
        '......BBBB......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '....GGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lamp_head', role: 'head' },
        E: { name: 'lens', role: 'eye' },
        B: { name: 'column', role: 'body' },
        G: { name: 'baseboard', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'gramophone_horn_16',
      description: 'Gramophone with large horn speaker.',
      grid: [
        '........HHHHHH..',
        '.......HHHHHHH..',
        '......HHHHHH....',
        '.....HHHHH......',
        '....EHHH........',
        '...EE...........',
        '...EE...........',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...GGGGGGGG.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'horn', role: 'head' },
        E: { name: 'tonearm', role: 'eye' },
        B: { name: 'cabinet', role: 'body' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#595652', highlight: '#854c30' },
      },
    },

    {
      id: 'sextant_16',
      description: 'Navigation sextant instrument.',
      grid: [
        '................',
        '......HH........',
        '.....HHHH.......',
        '....HHEEHH......',
        '...HH..EE..HH...',
        '..HH...EE...HH..',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BAAAAAABB.....',
        '..BBBBBBBB......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'arc', role: 'head' },
        E: { name: 'telescope', role: 'eye' },
        B: { name: 'frame', role: 'body' },
        A: { name: 'scale', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#deeed6' },
      },
    },

    {
      id: 'magic_lantern_16',
      description: 'Early projection magic lantern / slide projector.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHEEEEHH....',
        '....HEEEEEEH....',
        '....HEEEEEEH....',
        '....HHEEEEHH....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '...BBBABBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...GGGG..GGGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'chimney', role: 'head' },
        E: { name: 'lens', role: 'eye' },
        B: { name: 'box', role: 'body' },
        A: { name: 'slide_slot', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        eye:       { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'telegraph_machine_16',
      description: 'Morse code telegraph machine with key arm.',
      grid: [
        '................',
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '....HHHHHHH.....',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBAABBBBABBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'base', role: 'body' },
        H: { name: 'key_arm', role: 'head' },
        E: { name: 'mechanism', role: 'eye' },
        A: { name: 'contacts', role: 'accessory' },
        G: { name: 'platform', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#442434', base: '#595652', highlight: '#854c30' },
      },
    },

    {
      id: 'oil_lamp_16',
      description: 'Vintage kerosene oil lamp with glass chimney.',
      grid: [
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '.....HEEEEH.....',
        '.....HEEEEH.....',
        '.....HEEEEH.....',
        '.....HHHHHH.....',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'chimney', role: 'head' },
        E: { name: 'flame', role: 'eye' },
        B: { name: 'reservoir', role: 'body' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'hourglass_16',
      description: 'Classic hourglass sand timer.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....EEEEEEEE....',
        '.....EEEEEE.....',
        '......EEEE......',
        '.......EE.......',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'sand_top', role: 'eye' },
        H: { name: 'sand_bottom', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'spyglass_16',
      description: 'Brass spyglass / pirate telescope.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..EEE.BBBBBHHH..',
        '..EEEEBBBBBBHH..',
        '..EEEEBBBBBBHH..',
        '..EEE.BBBBBHHH..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'eyepiece', role: 'eye' },
        B: { name: 'tube', role: 'body' },
        H: { name: 'objective', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'pocket_watch_16',
      description: 'Vintage pocket watch with chain.',
      grid: [
        '................',
        '......HH........',
        '.....HBBH.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '...BEEEEEEB.....',
        '...BEEAEEEB.....',
        '...BEEAAEEB.....',
        '...BEEEEEEB.....',
        '...BBEEEEBB.....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'face', role: 'eye' },
        H: { name: 'crown', role: 'head' },
        A: { name: 'hands', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'microfiche_reader_16',
      description: 'Library microfiche reader with screen.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '.......BB.......',
        '.......BB.......',
        '......BBBB......',
        '....GGGGGGGG....',
        '...HHHGGGGHHHH..',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        G: { name: 'base', role: 'leg' },
        H: { name: 'tray', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'metronome_16',
      description: 'Wooden metronome for music tempo.',
      grid: [
        '................',
        '......HH........',
        '.......HH.......',
        '......BBHH......',
        '.....BBBBB......',
        '.....BBEBBB.....',
        '....BBBEBBB.....',
        '....BBBEBBBB....',
        '...BBBBEBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'pendulum', role: 'eye' },
        H: { name: 'weight', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'pendulum_clock_16',
      description: 'Grandfather-style pendulum wall clock.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BEEEEEBB....',
        '....BEEHEEBB....',
        '....BEEEEEBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBABBBB....',
        '....BBAAABBB....',
        '....BBBABBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....GGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'face', role: 'eye' },
        H: { name: 'hands', role: 'head' },
        A: { name: 'pendulum', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
