/**
 * Retro Tech batch 4 — 20 vintage tech: industrial, home, scientific, toys.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'retroTech',
  exportNames: { templates: 'RETRO_TECH_BATCH4_TEMPLATES', schemes: 'RETRO_TECH_BATCH4_COLOR_SCHEMES' },
  templates: [

    {
      id: 'rotary_dial_16',
      description: 'Close-up of a rotary telephone dial.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBEEEEEEEEBB..',
        '..BEEHHEHHEEEB..',
        '..BEHEEHEHEEBB..',
        '..BEEEEEEEEEEB..',
        '..BEHEEHEHEEBB..',
        '..BEEHHEHHEEEB..',
        '..BBEEEEEEEEBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'housing', role: 'body' },
        E: { name: 'dial_face', role: 'eye' },
        H: { name: 'holes', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'vacuum_cleaner_retro_16',
      description: 'Vintage upright vacuum cleaner.',
      grid: [
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '....EEEEEEEE....',
        '...EEEEEEEEEE...',
        '...EEEEEEEEEE...',
        '...GGGG..GGGG...',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bag', role: 'body' },
        H: { name: 'handle', role: 'head' },
        E: { name: 'motor_unit', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'sewing_machine_16',
      description: 'Vintage sewing machine with hand wheel.',
      grid: [
        '................',
        '.....HH.........',
        '....HHHH........',
        '...HHHHHHH......',
        '..BBBBBBBBB.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBEEBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GG........GG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'machine', role: 'body' },
        H: { name: 'arm', role: 'head' },
        E: { name: 'wheel', role: 'eye' },
        G: { name: 'table', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#8b8e8a' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'cuckoo_clock_16',
      description: 'Wooden cuckoo clock with pendulum chains.',
      grid: [
        '.......HH.......',
        '......HHHH......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BEEEEEBB....',
        '....BEEEEEBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '.....AA..AA.....',
        '.....GG..GG.....',
        '.....GG..GG.....',
        '....GGGG.GGG....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        H: { name: 'roof', role: 'head' },
        E: { name: 'face', role: 'eye' },
        A: { name: 'pendulum', role: 'accessory' },
        G: { name: 'chains', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    {
      id: 'stereoscope_16',
      description: 'Victorian stereoscope viewer for 3D images.',
      grid: [
        '................',
        '..EEEE..EEEE....',
        '..EEEE..EEEE....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '.....BBBB.......',
        '....GGGGGG......',
        '...GGGGGGGG.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'lenses', role: 'eye' },
        B: { name: 'viewer', role: 'body' },
        G: { name: 'stand', role: 'leg' },
      },
      colors: {
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#595652', highlight: '#854c30' },
      },
    },

    {
      id: 'wind_up_key_16',
      description: 'Vintage wind-up key for mechanical toys.',
      grid: [
        '................',
        '................',
        '....HHHHHHHH....',
        '...HH......HH...',
        '...HH......HH...',
        '...HH......HH...',
        '....HHHHHHHH....',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....EEEEEE.....',
        '.....EEEEEE.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bow', role: 'head' },
        B: { name: 'shaft', role: 'body' },
        E: { name: 'bit', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    {
      id: 'music_box_16',
      description: 'Ornate music box with lid and mechanism.',
      grid: [
        '................',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid', role: 'head' },
        B: { name: 'box', role: 'body' },
        E: { name: 'mechanism', role: 'eye' },
        G: { name: 'feet', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    {
      id: 'telegraph_pole_16',
      description: 'Wooden telegraph pole with cross-arms and wires.',
      grid: [
        '................',
        '......BB........',
        '..HHHHHHHHHH....',
        '......BB........',
        '......BB........',
        '...EEEEEEEE.....',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '.....GGGG.......',
        '....GGGGGG......',
        '................',
      ],
      chars: {
        B: { name: 'pole', role: 'body' },
        H: { name: 'crossarm_top', role: 'head' },
        E: { name: 'crossarm_bottom', role: 'eye' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
      },
    },

    {
      id: 'barometer_16',
      description: 'Vintage mercury barometer for weather prediction.',
      grid: [
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BEEEEB.....',
        '.....BEEEEB.....',
        '.....BEHHEB.....',
        '.....BEHHEB.....',
        '.....BEEEEB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '.....GGGGGG.....',
        '.....GGGGGG.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'dial', role: 'eye' },
        H: { name: 'needle', role: 'head' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'view_master_16',
      description: 'View-Master stereoscopic slide viewer.',
      grid: [
        '................',
        '................',
        '...BBBBBBBBBB...',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '...BBBBBBBBBB...',
        '......HHHH......',
        '.......HH.......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'eyepieces', role: 'eye' },
        H: { name: 'lever', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'hand_crank_phone_16',
      description: 'Early wall-mounted hand crank telephone.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBHHHHHHHBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBABB..',
        '..BBBBBBBBBABB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        H: { name: 'earpiece', role: 'head' },
        E: { name: 'bells', role: 'eye' },
        A: { name: 'crank', role: 'accessory' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'etch_a_sketch_16',
      description: 'Classic Etch A Sketch drawing toy.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBHBB..BBHBB..',
        '..BBHBB..BBHBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'frame', role: 'body' },
        E: { name: 'screen', role: 'eye' },
        H: { name: 'knobs', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        head:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'spinning_top_16',
      description: 'Vintage metal spinning top toy.',
      grid: [
        '................',
        '......HH........',
        '......HH........',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBEEEEBB.....',
        '..BBEEEEEEEBB...',
        '..BBEEEEEEEBB...',
        '..BBEEEEEEEBB...',
        '...BBEEEEBB.....',
        '....BBBBBB......',
        '.....BBBB.......',
        '......GG........',
        '......GG........',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'head' },
        B: { name: 'shell', role: 'body' },
        E: { name: 'stripe', role: 'eye' },
        G: { name: 'tip', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:  { shadow: '#30346d', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'kaleidoscope_16',
      description: 'Handheld kaleidoscope tube with colorful eye.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..EEE...........',
        '..EEEEBBBBBHHH..',
        '..EEEEBBBBBHHH..',
        '..EEEEBBBBBHHH..',
        '..EEE...........',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'eyepiece', role: 'eye' },
        B: { name: 'tube', role: 'body' },
        H: { name: 'objective', role: 'head' },
      },
      colors: {
        eye:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'snow_globe_16',
      description: 'Decorative snow globe with scene inside.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '....HHEEEEHH....',
        '...HHEEEEEEEH...',
        '...HEEEEEEEEH...',
        '...HEEEAAEEEH...',
        '...HEEEAAEEEH...',
        '...HHEEEEEEEH...',
        '....HHEEEEHH....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...GGGGGGGGGG...',
        '...GGGGGGGGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'glass', role: 'head' },
        E: { name: 'snow', role: 'eye' },
        A: { name: 'scene', role: 'accessory' },
        B: { name: 'rim', role: 'body' },
        G: { name: 'base', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'tin_robot_16',
      description: 'Classic wind-up tin robot toy.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '.....HEEHEH.....',
        '.....HHHHHH.....',
        '....BBBBBBBB....',
        '..AABBBBBBBBAA..',
        '..AABBEEEEBBAA..',
        '..AABBEEEEBBAA..',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....GG....GG....',
        '....GG....GG....',
        '...GGGG..GGGG...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        B: { name: 'body', role: 'body' },
        E: { name: 'chest_panel', role: 'eye' },
        A: { name: 'arms', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'bellows_camera_16',
      description: 'Large format bellows camera on tripod.',
      grid: [
        '................',
        '..BBBBBBBB......',
        '..BBBBBBBB......',
        '..BBEEEEBB......',
        '..BBEEEEBB......',
        '..BBBBBBBB......',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '.....HHHH.......',
        '......BB........',
        '.....BBBB.......',
        '....GG..GG......',
        '...GG....GG.....',
        '..GG......GG....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'camera', role: 'body' },
        E: { name: 'lens', role: 'eye' },
        H: { name: 'bellows', role: 'head' },
        G: { name: 'tripod', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'hand_drill_16',
      description: 'Vintage hand-cranked drill / egg beater drill.',
      grid: [
        '................',
        '...HHH..........',
        '...HHH..........',
        '...BBBB.........',
        '...BBBBBB.......',
        '...BBBBEEB......',
        '...BBBBBB.......',
        '...BBBBAABB.....',
        '...BBBB.........',
        '...BBBB.........',
        '....GG..........',
        '....GG..........',
        '....GG..........',
        '....GG..........',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'head' },
        B: { name: 'body', role: 'body' },
        E: { name: 'gear', role: 'eye' },
        A: { name: 'crank', role: 'accessory' },
        G: { name: 'bit', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'crystal_radio_16',
      description: 'DIY crystal radio receiver with tuning coil.',
      grid: [
        '................',
        '......HH........',
        '......HH........',
        '......HH........',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBAABBBBABBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'board', role: 'body' },
        E: { name: 'coil', role: 'eye' },
        H: { name: 'antenna', role: 'head' },
        A: { name: 'terminals', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    {
      id: 'player_piano_16',
      description: 'Self-playing player piano with paper roll.',
      grid: [
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BHHHHHHHHHHB..',
        '..BHHHHHHHHHHB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '..GG........GG..',
        '..GG........GG..',
        '..GGGG....GGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'case', role: 'body' },
        E: { name: 'roll_window', role: 'eye' },
        H: { name: 'keys', role: 'head' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
