/**
 * Tokyo batch 3 — 20 Japanese interior & furniture templates.
 * Traditional + modern Japanese home items, 16x16, DB16 palette.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'furniture',
  exportNames: { templates: 'TOKYO_BATCH3_TEMPLATES', schemes: 'TOKYO_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TATAMI MAT ─────────────────────────────────────────────
    {
      id: 'tatami_mat_tk_16',
      description: 'Tatami floor mat with woven texture and dark edge binding.',
      grid: [
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEHHEHHEHHHEBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEHHEHHEHHHEBB.',
        '.BEEEEEEEEEEEEB.',
        '.BXXXXXXXXXXXXB.',
        '.BXXXXXXXXXXXXB.',
        '.BEEEEEEEEEEEEB.',
        '.BEHHEHHEHHHEBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEHHEHHEHHHEBB.',
        '.BEEEEEEEEEEEEB.',
        '.BBBBBBBBBBBBBB.',
        '................',
      ],
      chars: {
        B: { name: 'binding_edge', role: 'body' },
        E: { name: 'straw_surface', role: 'eye' },
        H: { name: 'weave_lines', role: 'head' },
        X: { name: 'center_band', role: 'belt' },
      },
      colors: {
        body: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. FUTON ROLLED ────────────────────────────────────────────
    {
      id: 'futon_rolled_tk_16',
      description: 'Rolled futon bedding tied with cloth bands.',
      grid: [
        '................',
        '................',
        '..BBBBBBBBBBBB..',
        '.BBEEEEEEEEEBBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEEXXEEEXXEEEB.',
        '.BEEEEEEEEEEEEB.',
        '.BHHHHHHHHHHHHB.',
        '.BHHHHHHHHHHHBB.',
        '.BEEXXEEEXXEEEB.',
        '.BEEEEEEEEEEEEB.',
        '.BBEEEEEEEEEBBB.',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'futon_edge', role: 'body' },
        E: { name: 'fabric', role: 'eye' },
        H: { name: 'fold_line', role: 'head' },
        X: { name: 'tie_band', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 3. KOTATSU TABLE ───────────────────────────────────────────
    {
      id: 'kotatsu_table_tk_16',
      description: 'Kotatsu table with blanket draped over it, top-down view.',
      grid: [
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BEEEEEEEEEEEBB.',
        '.BEEEEEEEEEEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEFHHHHFEEBB.',
        '.BEEEFHHHHFEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEFFFFFFEEBB.',
        '.BEEEEEEEEEEEBB.',
        '.BEEEEEEEEEEEBB.',
        '.BBBBBBBBBBBBBB.',
        '................',
      ],
      chars: {
        B: { name: 'blanket_edge', role: 'body' },
        E: { name: 'blanket_fabric', role: 'eye' },
        F: { name: 'table_top', role: 'head' },
        H: { name: 'heater_glow', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 4. ZABUTON CUSHION ─────────────────────────────────────────
    {
      id: 'zabuton_cushion_tk_16',
      description: 'Puffy rounded floor cushion with cross seam, center tuft and corner tassels.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '..TTBEEEEEEBTT..',
        '..BBEESSSSEEEBB.',
        '..BEESSSSSSEEEB.',
        '..BEEEECCEEEEEB.',
        '..BEEEECCEEEEEB.',
        '..BEESSSSSSEEEB.',
        '..BBEESSSSEEEBB.',
        '..TTBEEEEEEBTT..',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'corner_tassel', role: 'accessory' },
        B: { name: 'cushion_edge', role: 'body' },
        E: { name: 'fabric_surface', role: 'eye' },
        S: { name: 'seam_lines', role: 'head' },
        C: { name: 'center_tuft', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 5. CHABUDAI TABLE ──────────────────────────────────────────
    {
      id: 'chabudai_table_tk_16',
      description: 'Low round Japanese table with thick connected legs and tea cup on top.',
      grid: [
        '................',
        '................',
        '........CC......',
        '.......CCCC.....',
        '.......CCCC.....',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HBBEEEEEEBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..GGG......GGG..',
        '..GGG......GGG..',
        '..GGG......GGG..',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'tea_cup', role: 'accessory' },
        H: { name: 'table_rim', role: 'head' },
        B: { name: 'table_surface', role: 'body' },
        E: { name: 'wood_grain', role: 'eye' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 6. SHOJI SCREEN ────────────────────────────────────────────
    {
      id: 'shoji_screen_tk_16',
      description: 'Shoji sliding screen panel with wooden frame and paper.',
      grid: [
        '.BBBBBBBBBBBBBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BBBBBBBBBBBBBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BPPPBPPPBPPPBB.',
        '.BBBBHBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
      ],
      chars: {
        B: { name: 'wood_frame', role: 'body' },
        P: { name: 'paper_panel', role: 'eye' },
        H: { name: 'handle', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 7. NOREN DOORWAY ───────────────────────────────────────────
    {
      id: 'noren_doorway_tk_16',
      description: 'Split noren door curtain on rod with kanji motif.',
      grid: [
        '.HHHHHHHHHHHHHH.',
        '.BBBBBBH.BBBBBBB',
        '.BEEEEEH.BEEEEBB',
        '.BEEEEEH.BEEEEBB',
        '.BEXXEEH.BEXXEBB',
        '.BEXXEEH.BEXXEBB',
        '.BEEEEEH.BEEEEBB',
        '.BEEEEEH.BEEEEBB',
        '.BEEEEEH.BEEEEBB',
        '.BEEEEEH..BEEEBB',
        '.BEEEEE.H..BEEEB',
        '.BEEEEE..H..BEEB',
        '.BBEEE....H..BEB',
        '..BBE......H..BB',
        '...BB.......H...',
        '................',
      ],
      chars: {
        H: { name: 'curtain_rod', role: 'head' },
        B: { name: 'fabric_edge', role: 'body' },
        E: { name: 'fabric_face', role: 'eye' },
        X: { name: 'kanji_motif', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#30346d', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 8. SHOE RACK GENKAN ────────────────────────────────────────
    {
      id: 'shoe_rack_genkan_tk_16',
      description: 'Genkan shoe rack with two pairs of slippers.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BSSBBBBBBSSB..',
        '..BSSBBBBBBSSB..',
        '..BBBBBBBBBBBB..',
        '..BEEEBBBEEEEB..',
        '..BEEEBBBEEEEB..',
        '..BBBBBBBBBBBB..',
        '..BSSBBBBBBSSB..',
        '..BSSBBBBBBSSB..',
        '..BBBBBBBBBBBB..',
        '..GG........GG..',
        '..GG........GG..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'rack_frame', role: 'body' },
        S: { name: 'slippers', role: 'accessory' },
        E: { name: 'shelf_board', role: 'eye' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. RICE COOKER ─────────────────────────────────────────────
    {
      id: 'rice_cooker_home_tk_16',
      description: 'Home rice cooker with steam vent and indicator light.',
      grid: [
        '......WW........',
        '.....W..W.......',
        '......WW........',
        '....HHHHHHHH....',
        '...HBBBBBBBBH...',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHHH.',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEEEEBB..',
        '..BEEEEEEELEBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'steam', role: 'accessory' },
        H: { name: 'lid', role: 'head' },
        B: { name: 'body_shell', role: 'body' },
        E: { name: 'front_panel', role: 'eye' },
        L: { name: 'indicator', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. ELECTRIC KETTLE ────────────────────────────────────────
    {
      id: 'electric_kettle_tk_16',
      description: 'Electric kettle with spout, handle and base.',
      grid: [
        '................',
        '......HHHH......',
        '.....HBBBBH.....',
        '....HBBBBBBH....',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '..SHBBBBBBBBHH..',
        '..SHBBBBBBBBHH..',
        '..SHBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '....HHHHHHHH....',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'kettle_shell', role: 'head' },
        B: { name: 'kettle_body', role: 'body' },
        S: { name: 'spout', role: 'accessory' },
        G: { name: 'base_plate', role: 'leg' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:  { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 11. KARAOKE MIC ────────────────────────────────────────────
    {
      id: 'karaoke_mic_tk_16',
      description: 'Karaoke microphone with large sphere head, neon accent ring and wide handle.',
      grid: [
        '....HHHHHH......',
        '...HMMMMMMMH....',
        '..HMMMMMMMMMH...',
        '..HMMMMMMMMMH...',
        '..HMMMNNNMMMH...',
        '..HMMMNNNMMMH...',
        '...HMMMMMMMH....',
        '....HHHHHH......',
        '.....RRRR.......',
        '.....RRRR.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....GGGGGG......',
        '................',
      ],
      chars: {
        H: { name: 'mic_grille', role: 'head' },
        M: { name: 'mic_mesh', role: 'eye' },
        N: { name: 'neon_badge', role: 'accessory' },
        R: { name: 'neon_ring', role: 'belt' },
        B: { name: 'mic_handle', role: 'body' },
        G: { name: 'base_plate', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#dad45e' },
        belt:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. MANGA CAFE BOOTH ───────────────────────────────────────
    {
      id: 'manga_cafe_booth_tk_16',
      description: 'Manga cafe booth pod with shelving and reading lamp.',
      grid: [
        '.BBBBBBBBBBBBB..',
        '.BSSSSSSSSSSBB..',
        '.BSSSSSSSSSSBB..',
        '.BSSSSSSSSSSBB..',
        '.BSSSSSSSSSSBB..',
        '.BBBBBBBBBBBBB..',
        '.BEEEEEEEEEBB...',
        '.BEEEEEEEEEBB...',
        '.BBBBBBBBBBBBB..',
        '.BEEEEEEEEEBB...',
        '.BEEEEEEEEEBB...',
        '.BBBBBBBBBBBBBLL',
        '.BHHHHHHHHHHHBLL',
        '.BHHHHHHHHHHHB..',
        '.BBBBBBBBBBBBB..',
        '................',
      ],
      chars: {
        B: { name: 'booth_frame', role: 'body' },
        S: { name: 'manga_shelves', role: 'eye' },
        E: { name: 'shelf_books', role: 'accessory' },
        H: { name: 'seat_cushion', role: 'head' },
        L: { name: 'reading_lamp', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 13. CAPSULE BED ────────────────────────────────────────────
    {
      id: 'capsule_bed_tk_16',
      description: 'Capsule hotel sleeping pod with round opening and bedding.',
      grid: [
        '..HHHHHHHHHHHH..',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        'HBBEEEEEEEEEBBH.',
        'HBBEEEEEEEEEBBH.',
        'HBBEEEEEEEEEBBH.',
        'HBBEEEPPPEEEBB..',
        'HBBEEPPPPPEEBB..',
        'HBBEEEEEEEEEBBH.',
        'HBBEEEEEEEEEBBH.',
        'HBBEEEEEEEEEBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '..HHHHHHHHHHHH..',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'pod_frame', role: 'head' },
        B: { name: 'pod_walls', role: 'body' },
        E: { name: 'mattress', role: 'eye' },
        P: { name: 'pillow', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 14. SENTO BUCKET ───────────────────────────────────────────
    {
      id: 'sento_bucket_tk_16',
      description: 'Sento bath bucket sitting on low wooden stool, one connected composition.',
      grid: [
        '................',
        '....HBBBBH......',
        '...HBBBBBBH.....',
        '...HBBWWBBH.....',
        '...HBBWWBBH.....',
        '...HBBBBBBH.....',
        '....HHHHHH......',
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '..EEEEEEEEEE....',
        '...GGG..GGG.....',
        '...GG....GG.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bucket_bands', role: 'head' },
        B: { name: 'bucket_wood', role: 'body' },
        W: { name: 'water', role: 'accessory' },
        E: { name: 'stool_seat', role: 'eye' },
        G: { name: 'stool_legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 15. OFURO TUB ──────────────────────────────────────────────
    {
      id: 'ofuro_tub_tk_16',
      description: 'Japanese wooden bath tub with steam rising.',
      grid: [
        '..SS....SS......',
        '...SS..SS.......',
        '....SSSS........',
        '.HBBBBBBBBBBBBH.',
        '.HBWWWWWWWWWWBH.',
        '.HBWWWWWWWWWWBH.',
        '.HBWWWWWWWWWWBH.',
        '.HBBBBBBBBBBBBH.',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '....HBBBBBBH....',
        '.....HHHHHH.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam', role: 'accessory' },
        H: { name: 'tub_rim', role: 'head' },
        B: { name: 'tub_wood', role: 'body' },
        W: { name: 'hot_water', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 16. TOKONOMA ALCOVE ────────────────────────────────────────
    {
      id: 'tokonoma_alcove_tk_16',
      description: 'Tokonoma alcove with hanging scroll and flower vase.',
      grid: [
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEEESSSSSSEEBB.',
        '.BEEESPPPPSEEBB.',
        '.BEEESPPPPSEEBB.',
        '.BEEESPPPPSEEBB.',
        '.BEEESPPPPSEEBB.',
        '.BEEESSSSSSEEBB.',
        '.BEEEEEEEEEEEEB.',
        '.BEEEEEEVVVEEEB.',
        '.BEEEEEVFFVEEEB.',
        '.BEEEEEEVVVEEEB.',
        '.BHHHHHHHHHHHHB.',
        '.BBBBBBBBBBBBBB.',
        '................',
      ],
      chars: {
        B: { name: 'alcove_frame', role: 'body' },
        E: { name: 'alcove_wall', role: 'eye' },
        S: { name: 'scroll_border', role: 'head' },
        P: { name: 'scroll_paper', role: 'accessory' },
        V: { name: 'vase', role: 'belt' },
        F: { name: 'flowers', role: 'arm' },
        H: { name: 'raised_floor', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. BUTSUDAN ALTAR ─────────────────────────────────────────
    {
      id: 'butsudan_altar_tk_16',
      description: 'Buddhist family altar cabinet with doors, candle and incense.',
      grid: [
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBEEEBBEEEBH..',
        '..HBEEEBBEEEBH..',
        '..HBEEEBBEEEBH..',
        '..HBEEEBBEEEBH..',
        '..HBBBBBBBBBBH..',
        '..HBGGGGGGGGBH..',
        '..HBGGGGGGGGBH..',
        '..HBGCCGGCCGBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '..HLLLLLLLLLLH..',
        '..HHHHHHHHHHHH..',
        '..GG........GG..',
        '................',
      ],
      chars: {
        H: { name: 'cabinet_frame', role: 'head' },
        B: { name: 'cabinet_body', role: 'body' },
        E: { name: 'altar_doors', role: 'eye' },
        G: { name: 'inner_shelf', role: 'leg' },
        C: { name: 'candle_incense', role: 'accessory' },
        L: { name: 'gold_trim', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 18. FOLDING FAN ────────────────────────────────────────────
    {
      id: 'folding_fan_tk_16',
      description: 'Sensu folding fan with clean semicircular shape, visible wide ribs and tassel at pivot.',
      grid: [
        '.....EEEEEE.....',
        '...EERREEEERR...',
        '..ERRREEEERRREE.',
        '.ERREEEEEEEERR..',
        '.ERREEEEEEEERR..',
        'ERRREEEEEEEERRRE',
        'ERRREEEEEEEERRRE',
        '.ERREEEEEEEERR..',
        '..ERREEEEEERR...',
        '...BRREERRRB....',
        '....BBBBBB......',
        '.....BBBB.......',
        '......BB........',
        '......HH........',
        '......HH........',
        '.....TTTT.......',
      ],
      chars: {
        E: { name: 'fan_surface', role: 'eye' },
        R: { name: 'fan_ribs', role: 'accessory' },
        B: { name: 'pivot_guard', role: 'body' },
        H: { name: 'handle', role: 'head' },
        T: { name: 'tassel', role: 'belt' },
      },
      colors: {
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#30346d', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 19. TEA SET ────────────────────────────────────────────────
    {
      id: 'tea_set_tk_16',
      description: 'Large matcha chawan bowl with bamboo whisk resting above it and saucer beneath.',
      grid: [
        '................',
        '.......WWWW.....',
        '......WWWWWW....',
        '......WWWWWW....',
        '.......WWWW.....',
        '..HHBBBBBBHH....',
        '.HBBBBBBBBBBH...',
        '.HBBGGGGGGBBH...',
        '.HBBGGGGGGBBH...',
        '.HBBGGGGGGBBH...',
        '..HBBBBBBBBBH...',
        '...HHHHHHHHH....',
        '....FFFFFFF.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'whisk_chasen', role: 'accessory' },
        H: { name: 'bowl_rim', role: 'head' },
        B: { name: 'bowl_body', role: 'body' },
        G: { name: 'matcha_tea', role: 'eye' },
        F: { name: 'saucer', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 20. FLOOR LAMP PAPER ───────────────────────────────────────
    {
      id: 'floor_lamp_paper_tk_16',
      description: 'Washi paper floor lamp with wooden frame, soft glow.',
      grid: [
        '................',
        '....HHHHHHHH....',
        '...HPPPPPPPPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPGGGGGGPPH..',
        '...HPPPPPPPPPH..',
        '....HHHHHHHH....',
        '......BBBB......',
        '......BBBB......',
        '.....FFFFFF.....',
        '................',
      ],
      chars: {
        H: { name: 'wood_frame', role: 'head' },
        P: { name: 'paper_shade', role: 'eye' },
        G: { name: 'inner_glow', role: 'accessory' },
        B: { name: 'stand_post', role: 'body' },
        F: { name: 'base_feet', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
