/**
 * Tokyo batch 2 — 20 Tokyo food & drink templates.
 * Tokyo-specific convenience store and cafe items, distinct from the Yatai bundle.
 * Covers: melon pan, taiyaki, nikuman, yakitori, karaage cup, crepe,
 *         dango, kakigori, matcha latte, ramune, canned coffee, sake,
 *         curry rice, katsu don, omurice, konbini sandwich, oden pot,
 *         takoyaki boat, wagashi plate, mochi daifuku.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'TOKYO_BATCH2_TEMPLATES', schemes: 'TOKYO_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. MELON PAN ────────────────────────────────────────────
    // Round melon bread with cross-hatch grid pattern on top
    {
      id: 'melon_pan_tk_16',
      description: 'Melon pan with signature grid pattern top crust and golden dough.',
      grid: [
        '................',
        '......CCCC......',
        '.....CCCCCC.....',
        '....CGCGCGCC....',
        '...CCCCCCCCCC...',
        '...CGCGCGCGCC...',
        '..CCCCCCCCCCCC..',
        '..CGCGCGCGCGCC..',
        '..CCCCCCCCCCCC..',
        '..DDDDDDDDDDDD..',
        '..DDDDDDDDDDDD..',
        '..DDDDDDDDDDDD..',
        '...DDDDDDDDDD...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cookie_crust', role: 'head' },
        G: { name: 'grid_groove', role: 'eye' },
        D: { name: 'dough_body', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. TAIYAKI FISH ─────────────────────────────────────────
    // Fat fish-shaped waffle — head left, tail right, clearly connected
    {
      id: 'taiyaki_fish_tk_16',
      description: 'Fat taiyaki fish waffle with 2x2 eye, red bean filling, and connected tail fin.',
      grid: [
        '................',
        '.........TTT....',
        '........TTTTT...',
        '...WWWWWWWTTT...',
        '..WWWWWWWWWWWW..',
        '..WWEEWWWWWWWW..',
        '..WWEEWRRRRWWW..',
        '..WWWWWRRRRWWW..',
        '..WWWWWWWWWWWW..',
        '..WSSWSSWWWWWW..',
        '..WSSWSSWWWWWW..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....MMMMMM.....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'waffle_body', role: 'head' },
        E: { name: 'fish_eye', role: 'eye' },
        R: { name: 'red_bean_fill', role: 'body' },
        T: { name: 'tail_fin', role: 'arm' },
        S: { name: 'belly_scale', role: 'belt' },
        M: { name: 'mouth_edge', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 3. NIKUMAN STEAMED ──────────────────────────────────────
    // Round steamed bun with steam wisps rising
    {
      id: 'nikuman_steamed_tk_16',
      description: 'Steamed pork bun (nikuman) with steam rising and pleated top.',
      grid: [
        '....SS..SS......',
        '...SS..SS.......',
        '......PP........',
        '.....PPPP.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '...WWWWWWWW.....',
        '...WWWWWWWW.....',
        '....WWWWWW......',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        P: { name: 'pleated_top', role: 'eye' },
        B: { name: 'bun_body', role: 'head' },
        W: { name: 'wrapper_paper', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. YAKITORI SKEWER ──────────────────────────────────────
    // Three fat grilled pieces on bamboo stick with tare sauce and green onion
    {
      id: 'yakitori_skewer_tk_16',
      description: 'Three fat yakitori pieces on bamboo skewer with tare sauce glaze, char marks, and negi.',
      grid: [
        '......SS........',
        '....CCCCCCCC....',
        '...CCDDCCDDCC...',
        '...CCCCCCCCCC...',
        '...CCGGCCGGCC...',
        '......SS........',
        '....CCCCCCCC....',
        '...CCDDCCDDCC...',
        '...CCCCCCCCCC...',
        '...CCGGCCGGCC...',
        '......SS........',
        '...NNCCCCCCNN...',
        '...CCDDCCDDCC...',
        '...CCGGCCGGCC...',
        '....CCCCCCCC....',
        '......SS........',
      ],
      chars: {
        C: { name: 'chicken_meat', role: 'head' },
        G: { name: 'char_marks', role: 'eye' },
        S: { name: 'bamboo_stick', role: 'body' },
        D: { name: 'tare_sauce', role: 'arm' },
        N: { name: 'green_onion', role: 'belt' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        belt:  { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
      },
    },

    // ─── 5. KARAAGE CUP ─────────────────────────────────────────
    // Fried chicken pieces in a paper cup
    {
      id: 'karaage_cup_tk_16',
      description: 'Japanese fried chicken (karaage) pieces piled in a red paper cup.',
      grid: [
        '................',
        '................',
        '...KKKKKKKK.....',
        '..KKKKKKKKKKK...',
        '..KKKKKKKKKKKK..',
        '..KKGKKGKKGKKK..',
        '..KKKKKKKKKKKK..',
        '..PPPPPPPPPPPP..',
        '..PLLPLLPLLPLP..',
        '..PPPPPPPPPPPP..',
        '..PLLPLLPLLPLP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        K: { name: 'karaage_piece', role: 'head' },
        G: { name: 'golden_crust', role: 'eye' },
        P: { name: 'paper_cup', role: 'body' },
        L: { name: 'cup_stripe', role: 'arm' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 6. CREPE HARAJUKU ───────────────────────────────────────
    // Wide cone crepe with overflowing cream, strawberry bits, chocolate drizzle
    {
      id: 'crepe_harajuku_tk_16',
      description: 'Harajuku-style crepe cone with overflowing whipped cream, strawberries, and chocolate.',
      grid: [
        '....WWWWWWWW....',
        '...WWWWWWWWWW...',
        '..WWSSWWWWSSWW..',
        '..WWWWWWWWWWWW..',
        '...CCCCCCCCCC...',
        '...CCHCCCCHCC...',
        '...CCCCCCCCCC...',
        '....CCHCCCHC....',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '.....CHCCCC.....',
        '......CCCC......',
        '......CCCC......',
        '......PPPP......',
        '......PPPP......',
        '.......PP.......',
      ],
      chars: {
        W: { name: 'whipped_cream', role: 'accessory' },
        S: { name: 'strawberry_top', role: 'eye' },
        C: { name: 'crepe_wrap', role: 'head' },
        H: { name: 'choco_drizzle', role: 'body' },
        P: { name: 'paper_wrapper', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 7. DANGO TRI ────────────────────────────────────────────
    // Three-color dango balls horizontal on bamboo skewer with serving tray
    {
      id: 'dango_tri_tk_16',
      description: 'Three-color hanami dango horizontal on bamboo skewer — pink, white, green — on serving tray.',
      grid: [
        '................',
        '................',
        '....SS....SS....',
        '.PP.SS.WW.SS.GG.',
        'PPPPSSWWWWSSGGGG',
        'PPPPSSWWWWSSGGGG',
        'PPPPSSWWWWSSGGGG',
        'PPPPSSWWWWSSGGGG',
        'PPPPSSWWWWSSGGGG',
        '.PP.SS.WW.SS.GG.',
        '....SS....SS....',
        '....SS....SS....',
        '................',
        '...TTTTTTTTTT...',
        '...TTTTTTTTTT...',
        '................',
      ],
      chars: {
        P: { name: 'pink_dango', role: 'head' },
        W: { name: 'white_dango', role: 'body' },
        G: { name: 'green_dango', role: 'arm' },
        S: { name: 'bamboo_stick', role: 'belt' },
        T: { name: 'serving_tray', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. KAKIGORI BOWL ────────────────────────────────────────
    // Shaved ice mound in a bowl with syrup drizzle
    {
      id: 'kakigori_bowl_tk_16',
      description: 'Kakigori shaved ice mound in glass bowl with blue syrup and cherry on top.',
      grid: [
        '........CC......',
        '.......CC.......',
        '......IIII......',
        '.....IIIIII.....',
        '....IISSSSII....',
        '...IISSSSSSII...',
        '...IISSSSSSII...',
        '...IIIIIIIIIII..',
        '..GGGGGGGGGGGGG.',
        '..GGIIIIIIIIGG..',
        '..GGIIIIIIIIGG..',
        '...GGGGGGGGGGG..',
        '....GGGGGGGGG...',
        '.....TTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'cherry_top', role: 'accessory' },
        I: { name: 'shaved_ice', role: 'head' },
        S: { name: 'blue_syrup', role: 'eye' },
        G: { name: 'glass_bowl', role: 'body' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 9. MATCHA LATTE ─────────────────────────────────────────
    // Matcha latte cup with foam art on top
    {
      id: 'matcha_latte_tk_16',
      description: 'Matcha latte in white cup with leaf foam art and green matcha color.',
      grid: [
        '................',
        '................',
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '..RRMMLLMMMMRR..',
        '..RRMLLLMMMRRR..',
        '..RRMMLLMMMMRR..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '...CCCCCCCCCC...',
        '....SSSSSSSS....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'cup_rim', role: 'accessory' },
        M: { name: 'matcha_surface', role: 'head' },
        L: { name: 'foam_art', role: 'eye' },
        C: { name: 'cup_body', role: 'body' },
        S: { name: 'saucer_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 10. RAMUNE BOTTLE ───────────────────────────────────────
    // Wide ramune bottle with thick neck, marble, and label band
    {
      id: 'ramune_bottle_tk_16',
      description: 'Classic Ramune marble soda with wide body, thick glass neck, marble, and label.',
      grid: [
        '.....CCCCCC.....',
        '......CCCC......',
        '......NNNN......',
        '.....NNMMNN.....',
        '......NNNN......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BLLLLLLB....',
        '....BLLGGLLB....',
        '....BLLLLLLB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'accessory' },
        N: { name: 'glass_neck', role: 'head' },
        M: { name: 'glass_marble', role: 'eye' },
        B: { name: 'bottle_body', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        G: { name: 'logo_text', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        head:      { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 11. CANNED COFFEE ───────────────────────────────────────
    // Japanese canned coffee (Boss/Georgia style)
    {
      id: 'canned_coffee_tk_16',
      description: 'Japanese vending machine canned coffee with pull-tab top and label.',
      grid: [
        '................',
        '................',
        '.....TTTTTT.....',
        '....TTPPTTTT....',
        '....CCCCCCCC....',
        '....CCCCCCCC....',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '...LLGGGGGGLL...',
        '...LLLLLLLLLL...',
        '...LLLLLLLLLL...',
        '....CCCCCCCC....',
        '....CCCCCCCC....',
        '....CCCCCCCC....',
        '.....FFFFFF.....',
        '................',
      ],
      chars: {
        T: { name: 'can_top', role: 'accessory' },
        P: { name: 'pull_tab', role: 'eye' },
        C: { name: 'can_metal', role: 'body' },
        L: { name: 'label_wrap', role: 'head' },
        G: { name: 'gold_logo', role: 'belt' },
        F: { name: 'can_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        eye:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 12. SAKE BOTTLE ─────────────────────────────────────────
    // Tokkuri sake flask with small ochoko cup
    {
      id: 'sake_bottle_tk_16',
      description: 'Ceramic tokkuri sake flask with ochoko cup beside it.',
      grid: [
        '................',
        '.....NNNN.......',
        '....NNNNNN......',
        '.....NNNN.......',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBLBBBBBB....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.CC..',
        '...BBBBBBBB.CC..',
        '....BBBBBB.CCCC.',
        '....TTTTTT.CCCC.',
        '..........FFFF..',
        '................',
      ],
      chars: {
        N: { name: 'flask_neck', role: 'head' },
        B: { name: 'flask_body', role: 'body' },
        L: { name: 'label_mark', role: 'eye' },
        C: { name: 'ochoko_cup', role: 'arm' },
        T: { name: 'flask_base', role: 'boot' },
        F: { name: 'cup_base', role: 'belt' },
      },
      colors: {
        head:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        arm:   { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. CURRY RICE ──────────────────────────────────────────
    // Japanese curry rice plate with curry on one side, rice on the other
    {
      id: 'curry_rice_tk_16',
      description: 'Japanese curry rice on oval plate — golden curry sauce and white rice side by side.',
      grid: [
        '................',
        '................',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '..PRRRRRCCCCCP..',
        '..PRRRRRCCCCCP..',
        '..PRRRRRCCCCCP..',
        '..PRRRRRCCCCCP..',
        '..PRRRRRCCCCCP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....WWWWWWWW....',
        '.....WWWWWW.....',
        '......TTTT......',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'plate_rim', role: 'body' },
        R: { name: 'white_rice', role: 'head' },
        C: { name: 'curry_sauce', role: 'arm' },
        W: { name: 'plate_wall', role: 'leg' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#757161' },
      },
    },

    // ─── 14. KATSU DON ───────────────────────────────────────────
    // Full-canvas katsu donburi — 3/4 view bowl, curved rim, big toppings
    {
      id: 'katsu_don_tk_16',
      description: 'Katsu donburi — deep bowl with breaded cutlet, egg, and green onion, filling the full canvas.',
      grid: [
        '................',
        '................',
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '..RKKKKKKKKKKR..',
        '..RKKKKKKKGKKR..',
        '..RKKEEKKKKKKR..',
        '..RKKEEKKGGKKR..',
        '..RRRRRRRRRRRR..',
        '.RRRRRRRRRRRRRR.',
        '.RRWWWWWWWWWWRR.',
        '..RRWWWWWWWWRR..',
        '...RWWWWWWWWR...',
        '.....WWWWWW.....',
        '.....FFFFFF.....',
        '................',
      ],
      chars: {
        R: { name: 'bowl_rim', role: 'body' },
        K: { name: 'katsu_cutlet', role: 'head' },
        E: { name: 'egg_custard', role: 'eye' },
        G: { name: 'green_onion', role: 'belt' },
        W: { name: 'bowl_wall', role: 'leg' },
        F: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:  { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 15. OMURICE ─────────────────────────────────────────────
    // Omelette over rice with ketchup writing
    {
      id: 'omurice_tk_16',
      description: 'Omurice — fluffy omelette over fried rice with ketchup heart drawing.',
      grid: [
        '................',
        '................',
        '...PPPPPPPPPP...',
        '..PPPPPPPPPPPP..',
        '..PEEEEEEEEEP...',
        '..PEEEEEEEEEPP..',
        '..PEEKKEKKEEPP..',
        '..PEEEKEKEEEP...',
        '..PEEEEKEEEEP...',
        '..PEEEEEEEEEP...',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....WWWWWWWW....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'plate_rim', role: 'body' },
        E: { name: 'egg_omelette', role: 'head' },
        K: { name: 'ketchup_art', role: 'eye' },
        W: { name: 'plate_wall', role: 'leg' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:   { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#757161' },
      },
    },

    // ─── 16. KONBINI SANDWICH ────────────────────────────────────
    // Triangle convenience store sandwich in plastic wrap
    {
      id: 'konbini_sandwich_tk_16',
      description: 'Convenience store triangle sandwich in clear plastic wrapper with visible layers.',
      grid: [
        '................',
        '................',
        '.......WW.......',
        '......WWWW......',
        '.....WWWWWW.....',
        '....WWBBBBWW....',
        '...WWBBLLBBWW...',
        '..WWBBLGGLLBWW..',
        '..WBBBLLLLBBBW..',
        '.WWBBBBBBBBBBWW.',
        '.WBBBBBBBBBBBBW.',
        '.PPPPPPPPPPPPPP.',
        '.PPPPPPPPPPPPPP.',
        '..PPPPPPPPPPPP..',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'plastic_wrap', role: 'accessory' },
        B: { name: 'bread_slice', role: 'head' },
        L: { name: 'lettuce_fill', role: 'arm' },
        G: { name: 'ham_layer', role: 'eye' },
        P: { name: 'package_base', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 17. ODEN POT ────────────────────────────────────────────
    // Oden hotpot with daikon, egg, and konnyaku visible
    {
      id: 'oden_pot_tk_16',
      description: 'Oden hotpot with daikon rounds, boiled egg, and konnyaku in dashi broth.',
      grid: [
        '...SS....SS.....',
        '..SS....SS......',
        '..HHHHHHHHHHHH..',
        '..HBBBBBBBBBBH..',
        '..HBDDBBEEBBKH..',
        '..HBDDBBEEBBKH..',
        '..HBBBBBBBBBBH..',
        '..HBBKBBDDBBBH..',
        '..HBBKBBDDBBBH..',
        '..HBBBBBBBBBBH..',
        '..HHHHHHHHHHHH..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....FFFFFF.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        H: { name: 'pot_rim', role: 'body' },
        B: { name: 'dashi_broth', role: 'arm' },
        D: { name: 'daikon_round', role: 'head' },
        E: { name: 'boiled_egg', role: 'eye' },
        K: { name: 'konnyaku', role: 'belt' },
        W: { name: 'pot_wall', role: 'leg' },
        F: { name: 'pot_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 18. TAKOYAKI BOAT ───────────────────────────────────────
    // Takoyaki balls in paper boat with sauce and bonito
    {
      id: 'takoyaki_boat_tk_16',
      description: 'Takoyaki octopus balls in paper boat with sauce drizzle and bonito flakes.',
      grid: [
        '................',
        '................',
        '................',
        '..FFFF..FFFF....',
        '..TTTTTTTTTTTT..',
        '..TSTTTSTTTSTT..',
        '..TTTTTTTTTTTT..',
        '..TSTTTSTTTSTT..',
        '..TTTTTTTTTTTT..',
        '..PPPPPPPPPPPP..',
        '.PPPPPPPPPPPPPP.',
        '.PPPPPPPPPPPPPP.',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'bonito_flake', role: 'accessory' },
        T: { name: 'takoyaki_ball', role: 'head' },
        S: { name: 'sauce_drizzle', role: 'eye' },
        P: { name: 'paper_boat', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 19. WAGASHI PLATE ───────────────────────────────────────
    // Large nerikiri flower wagashi with clear petals on minimal ceramic plate
    {
      id: 'wagashi_plate_tk_16',
      description: 'Large nerikiri wagashi flower with five-petal shape, center detail, leaf garnish, on gold-trimmed plate.',
      grid: [
        '................',
        '......PP........',
        '.....PPPP.......',
        '....PPPPPP......',
        '...PPP.PP.PPP...',
        '..PPPP.CC.PPPP..',
        '..PPPPCCCCPPPP..',
        '..PPPPCCCCPPPP..',
        '...PPP.CC.PPP...',
        '....PP.PP.PP....',
        '.....PPPPPP.....',
        '..LL..PPPP..LL..',
        '..LLLL....LLLL..',
        '...TGGGGGGGGT...',
        '..TTGGGGGGGGTT..',
        '...TTTTTTTTTT...',
      ],
      chars: {
        P: { name: 'petal_body', role: 'head' },
        C: { name: 'flower_center', role: 'eye' },
        L: { name: 'leaf_garnish', role: 'arm' },
        T: { name: 'plate_rim', role: 'body' },
        G: { name: 'plate_gold', role: 'belt' },
      },
      colors: {
        head:  { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:   { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        belt:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 20. MOCHI DAIFUKU ───────────────────────────────────────
    // Single large mochi cross-section showing skin + paste + anko, on leaf
    {
      id: 'mochi_daifuku_tk_16',
      description: 'Large mochi daifuku cross-section revealing skin, inner paste, and anko filling, on kashiwa leaf.',
      grid: [
        '................',
        '.....MMMMMM.....',
        '...MMMMMMMMMM...',
        '..MMMIIIIIIMMM..',
        '..MMIIAAAAIIMM..',
        '..MMIIAAAAIIMM..',
        '..MMMIIIIIIMMM..',
        '...MMMMMMMMMM...',
        '....DDMMMMDD....',
        '...LLLLLLLLLL...',
        '..LLLLLLLLLLLL..',
        '..LLVVLLLLVVLL..',
        '...LLLLLLLLLL...',
        '....LLLLLLLL....',
        '......LLLL......',
        '................',
      ],
      chars: {
        M: { name: 'mochi_skin', role: 'head' },
        I: { name: 'inner_paste', role: 'body' },
        A: { name: 'anko_filling', role: 'eye' },
        D: { name: 'flour_dusting', role: 'accessory' },
        L: { name: 'kashiwa_leaf', role: 'arm' },
        V: { name: 'leaf_vein', role: 'belt' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#d2aa99', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

  ],
};

export default batch;
