/**
 * Tokyo Nature & Seasons batch 4 — 20 Japanese garden, nature, and seasonal templates.
 * Stardew Valley quality: warm ambers, soft pinks, earthy greens.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'nature',
  exportNames: { templates: 'TOKYO_BATCH4_TEMPLATES', schemes: 'TOKYO_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SAKURA TREE ────────────────────────────────────────────
    {
      id: 'sakura_tree_tk_16',
      description: 'Cherry blossom tree with round pink canopy and brown trunk.',
      grid: [
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '..CCCCFFCCCCCC..',
        '..CCCCCCCCCFCC..',
        '.CCCCFCCCCCCCC..',
        '.CCCCCCCCFCCCCC.',
        '..CCCCCCCCCCCCC.',
        '..CCCCCCCCCCCC..',
        '...CCCCCCCCCC...',
        '......TTTT......',
        '......TTTT......',
        '......TTTT......',
        '.....TTTTTT.....',
        '.....TTTTTT.....',
        '....GGGGGGGG....',
        '................',
      ],
      chars: {
        C: { name: 'canopy', role: 'body' },
        F: { name: 'flowers', role: 'accessory' },
        T: { name: 'trunk', role: 'arm' },
        G: { name: 'grass_base', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 2. GINKGO TREE ────────────────────────────────────────────
    {
      id: 'ginkgo_tree_tk_16',
      description: 'Autumn ginkgo tree with golden fan-shaped leaf canopy.',
      grid: [
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '..LLLLHHLLLLLL..',
        '..LLLLLLLLLLLL..',
        '.LLLLHHLLLLLLL..',
        '.LLLLLLLLHHLLLL.',
        '..LLLLLLLLLLLL..',
        '...LLLLLLLLLL...',
        '......TTTT......',
        '......TTTT......',
        '......TTTT......',
        '......TTTT......',
        '.....TTTTTT.....',
        '....GGGGGGGG....',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'body' },
        H: { name: 'highlights', role: 'accessory' },
        T: { name: 'trunk', role: 'arm' },
        G: { name: 'fallen_leaves', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 3. PLUM BLOSSOM ───────────────────────────────────────────
    {
      id: 'plum_blossom_tk_16',
      description: 'Thick ume plum branch with large pink flower clusters and green buds.',
      grid: [
        '........PPPP....',
        '.......PPCCPP...',
        '......KPPPPPP...',
        '.....KKK.PPPP...',
        '....KKK.DD......',
        '...BBBBBBB......',
        '..BBBBBBB.......',
        '.BBB..PPPP......',
        'BBB..PPCCPP.....',
        'BBB..PPPPPDD....',
        '.BBBB.PPPP.DD...',
        '..BBBKK.........',
        '..PPPPBBBB......',
        '.PPCCPPBBB......',
        '.PPPPP..BBB.....',
        '..PPPP...BB.....',
      ],
      chars: {
        B: { name: 'branch', role: 'arm' },
        K: { name: 'bark_knots', role: 'belt' },
        P: { name: 'petals', role: 'body' },
        C: { name: 'stamen_center', role: 'accessory' },
        D: { name: 'leaf_buds', role: 'head' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#854c30' },
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. BAMBOO GROVE ───────────────────────────────────────────
    {
      id: 'bamboo_grove_tk_16',
      description: 'Dense bamboo grove with three thick stalks, node bands, and leafy canopy.',
      grid: [
        '..LL.LLLL.LL....',
        '.LLLLLLLLLLLLL..',
        '..LLL.LLLL.L....',
        '..SSS..SSS..SSS.',
        '..SSS..SSS..SSS.',
        '..NNN..NNN..NNN.',
        '..SSS..SSS..SSS.',
        '..SSS..SSS..SSS.',
        '..NNN..NNN..NNN.',
        '..SSS..SSS..SSS.',
        '..SSS..SSS..SSS.',
        '..NNN..NNN..NNN.',
        '..SSS..SSS..SSS.',
        '..SSS..SSS..SSS.',
        '................',
        '..GGGGGGGGGGGG..',
      ],
      chars: {
        L: { name: 'bamboo_leaves', role: 'head' },
        S: { name: 'bamboo_stalk', role: 'body' },
        N: { name: 'bamboo_node', role: 'belt' },
        G: { name: 'ground_base', role: 'leg' },
      },
      colors: {
        head: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body: { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        belt: { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
        leg:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. BONSAI PINE ────────────────────────────────────────────
    {
      id: 'bonsai_pine_tk_16',
      description: 'Bonsai pine tree in a ceramic pot with sculpted canopy.',
      grid: [
        '....LLLLLL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '...LLLLLLL......',
        '.......TT.......',
        '......TTT.......',
        '.....TTLLLLL....',
        '....TT.LLLLLL...',
        '...TT...LLLLL...',
        '....TTT.........',
        '.....TT.........',
        '...RRRRRRRR.....',
        '...PPPPPPPP.....',
        '...PPPPPPPP.....',
        '...PPPPPPPP.....',
        '....RRRRRR......',
      ],
      chars: {
        L: { name: 'pine_canopy', role: 'head' },
        T: { name: 'trunk', role: 'arm' },
        P: { name: 'pot_body', role: 'body' },
        R: { name: 'pot_rim', role: 'belt' },
      },
      colors: {
        head: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        belt: { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 6. KOI FISH ───────────────────────────────────────────────
    {
      id: 'koi_fish_tk_16',
      description: 'Koi fish swimming with orange and white pattern.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBB......',
        '...BBBBBBBBBB...',
        '..BBBOOBBBBBBB..',
        '.HHBBEBBBBBBWWB.',
        '.HBBBBBBBBBBWWB.',
        '..BBBOOBBBBBB...',
        '...BBBBBBBBBFF..',
        '....BBBBB..FFF..',
        '.....BBB....FF..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body_orange', role: 'body' },
        O: { name: 'white_patch', role: 'accessory' },
        E: { name: 'eye', role: 'eye' },
        H: { name: 'head_fin', role: 'head' },
        F: { name: 'tail_fin', role: 'arm' },
        W: { name: 'water_glint', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 7. TANUKI STATUE ──────────────────────────────────────────
    {
      id: 'tanuki_statue_tk_16',
      description: 'Round tanuki stone statue with hat and big belly.',
      grid: [
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHHH...',
        '...SSEESEESS....',
        '...SSSSSSSS.....',
        '...SSMSSSMSS....',
        '..SSBBBBBBSS....',
        '..SBBBBBBBBSS...',
        '..SBBBBBBBBS....',
        '..SBBBBBBBBSS...',
        '..SBBBAAABBBS...',
        '..SSBBBBBBBSS...',
        '...SSSSSSSSSS...',
        '...SSFFSSFFSS...',
        '...FFFFFFFFFF...',
        '................',
      ],
      chars: {
        H: { name: 'straw_hat', role: 'head' },
        S: { name: 'stone_body', role: 'body' },
        E: { name: 'eyes', role: 'eye' },
        M: { name: 'mouth_nose', role: 'accessory' },
        B: { name: 'belly', role: 'arm' },
        A: { name: 'sake_jug', role: 'belt' },
        F: { name: 'feet_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        accessory: { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        arm:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. STONE LANTERN ──────────────────────────────────────────
    {
      id: 'stone_lantern_tk_16',
      description: 'Toro stone garden lantern with tiered cap and light chamber.',
      grid: [
        '....RRRRRR......',
        '...RRRRRRRR.....',
        '....RRRRRR......',
        '....SSSSSS......',
        '...SLLLLLLS.....',
        '...SLLLLLLS.....',
        '...SLLLLLLS.....',
        '....SSSSSS......',
        '.....PPPP.......',
        '.....PPPP.......',
        '.....PPPP.......',
        '....SSSSSS......',
        '...SSSSSSSS.....',
        '....SSSSSS......',
        '....PPPPPP......',
        '...GGGGGGGG.....',
      ],
      chars: {
        R: { name: 'cap_roof', role: 'head' },
        S: { name: 'stone_body', role: 'body' },
        L: { name: 'light_chamber', role: 'accessory' },
        P: { name: 'pillar', role: 'arm' },
        G: { name: 'ground_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 9. ZEN ROCK GARDEN ────────────────────────────────────────
    {
      id: 'zen_rock_garden_tk_16',
      description: 'Miniature zen garden tray with three rocks on raked sand and moss.',
      grid: [
        '................',
        '................',
        '...FFFFFFFFFF...',
        '..FSSSSSSSSSSF..',
        '..FSSRRRSSSSSF..',
        '..FSRRRRSSBBSF..',
        '..FSSLLSSBBBSF..',
        '..FLLSSLLSSSSF..',
        '..FSSLLAAASSSF..',
        '..FLLAAAAASSFF..',
        '..FMMAAAAAASF...',
        '..FMMSSAAAASF...',
        '..FSSLLSSSSFF...',
        '...FFFFFFFFFF...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'tray_frame', role: 'belt' },
        S: { name: 'sand_base', role: 'body' },
        L: { name: 'rake_lines', role: 'accessory' },
        R: { name: 'small_rock', role: 'arm' },
        B: { name: 'medium_rock', role: 'head' },
        A: { name: 'large_rock', role: 'leg' },
        M: { name: 'moss_patch', role: 'boot' },
      },
      colors: {
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. LOTUS FLOWER ──────────────────────────────────────────
    {
      id: 'lotus_flower_tk_16',
      description: 'Lotus flower blooming on water with round lily pad.',
      grid: [
        '................',
        '......PPP.......',
        '.....PPPPP......',
        '....PPPCPPP.....',
        '...PPPCCCPPP....',
        '...PPPCCCPPP....',
        '....PPPPPPP.....',
        '...LLPPPPPLL....',
        '..LLLLLLLLLLLL..',
        '.LLLLLLLLLLLLLL.',
        '.LLLLLLLLLLLLLL.',
        '..LLLLLLLLLLLL..',
        '..WWWWWWWWWWWW..',
        '.WWWWWWWWWWWWWW.',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'petals', role: 'body' },
        C: { name: 'center', role: 'accessory' },
        L: { name: 'lily_pad', role: 'head' },
        W: { name: 'water', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 11. MAPLE LEAF PILE ───────────────────────────────────────
    {
      id: 'maple_leaf_pile_tk_16',
      description: 'Pile of colorful autumn maple leaves on the ground.',
      grid: [
        '................',
        '................',
        '................',
        '......RR........',
        '.....RRROO......',
        '....RRRROOO.....',
        '..RRRRROOOOYY...',
        '..RRRROOOOYYYY..',
        '.RRRRROOOOYYYYY.',
        '.RRROOOOYYYYYYY.',
        '.RRROOOYYYYYYYY.',
        '..RROOOOYYYYYYY.',
        '..RROOOOYYYYYY..',
        '...GGOOOOYYYY...',
        '..GGGGGGGGGGGG..',
        '................',
      ],
      chars: {
        R: { name: 'red_leaves', role: 'body' },
        O: { name: 'orange_leaves', role: 'accessory' },
        Y: { name: 'yellow_leaves', role: 'head' },
        G: { name: 'ground', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. WISTERIA TRELLIS ──────────────────────────────────────
    {
      id: 'wisteria_trellis_tk_16',
      description: 'Thick wooden trellis with hanging wisteria flower clusters and green leaves.',
      grid: [
        '.TTTTTTTTTTTTTT.',
        '.TBBTTBBTTBBTT..',
        '.TTTTTTTTTTTTTT.',
        '.LLPPPLLLPPPLL..',
        '.LLPPPLLLPPPLL..',
        '..LPPPL.LPPPL...',
        '..LFFFL.LFFFL...',
        '..LFFFL.LFFFL...',
        '..LFFFL..FFFL...',
        '...FFF...FFF....',
        '...FFF...FFF....',
        '...FFF...FFF....',
        '...FF.....FF....',
        '...FF.....FF....',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'trellis_wood', role: 'arm' },
        B: { name: 'bark_knots', role: 'belt' },
        L: { name: 'green_leaves', role: 'head' },
        P: { name: 'pink_flowers', role: 'accessory' },
        F: { name: 'purple_flowers', role: 'body' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#854c30' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 13. MOSS STONE ────────────────────────────────────────────
    {
      id: 'moss_stone_tk_16',
      description: 'Moss-covered garden stone, rounded with green patches.',
      grid: [
        '................',
        '................',
        '................',
        '......SSSS......',
        '....SSSSSSSS....',
        '...SMMSSSSMMS...',
        '..SMMMSSSSMMS...',
        '..SSSSSSSSSSSS..',
        '.SSSSSSSSSSSSS..',
        '.SSMMSSSSMMSSSS.',
        '.SSMMSSSSMMSSS..',
        '..SSSSSSSSSSS...',
        '...SSSSSSSSS....',
        '....GGGGGGGG....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stone_surface', role: 'body' },
        M: { name: 'moss_patches', role: 'accessory' },
        G: { name: 'ground_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. RAIN PUDDLE ───────────────────────────────────────────
    {
      id: 'rain_puddle_tk_16',
      description: 'Red umbrella seen from above with rain splashes on wet ground.',
      grid: [
        '................',
        'WW............WW',
        '....UUUUUU......',
        '...UURRUURRUU...',
        '..UURRUURRUURR..',
        '..UUUUUUUUUUUU..',
        '..UURRUURRUURR..',
        '..UUUUHHHUUUU...',
        '..UURRUURRUURR..',
        '..UUUUUUUUUUUU..',
        '...UURRUURRUU...',
        '....UUUUUU......',
        'WW....PP......WW',
        '......PP........',
        '..WW........WW..',
        '................',
      ],
      chars: {
        U: { name: 'umbrella_canopy', role: 'body' },
        R: { name: 'umbrella_ribs', role: 'accessory' },
        H: { name: 'handle_tip', role: 'belt' },
        P: { name: 'handle_shaft', role: 'arm' },
        W: { name: 'rain_splash', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 15. SNOW LANTERN ──────────────────────────────────────────
    {
      id: 'snow_lantern_tk_16',
      description: 'Snow-capped stone lantern in winter garden.',
      grid: [
        '...NNNNNNNN.....',
        '..NNNNNNNNNN....',
        '...NNNNNNNN.....',
        '....RRRRRR......',
        '...RRRRRRRR.....',
        '....RRRRRR......',
        '....SLLLLS......',
        '....SLLLLS......',
        '....SLLLLS......',
        '....SSSSSS......',
        '.....PPPP.......',
        '.....PPPP.......',
        '....SSSSSS......',
        '...SSSSSSSS.....',
        '..GGNNNNNNGG....',
        '..GGGGGGGGGG....',
      ],
      chars: {
        N: { name: 'snow_cap', role: 'head' },
        R: { name: 'roof_stone', role: 'belt' },
        S: { name: 'stone_body', role: 'body' },
        L: { name: 'light_glow', role: 'accessory' },
        P: { name: 'pillar', role: 'arm' },
        G: { name: 'ground_snow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 16. IRIS CLUSTER ──────────────────────────────────────────
    {
      id: 'iris_cluster_tk_16',
      description: 'Single large Japanese iris with broad petals, thick stem, and two sword-like leaves.',
      grid: [
        '......PPP.......',
        '....PPPPPPP.....',
        '...PPPHHHPPP....',
        '..PPHHCCCHHPP...',
        '..PPPPPCPPPPP...',
        '..PPPPPPPPPPP...',
        '...PPPPPPPPP....',
        '....PPPPPPP.....',
        '......SSS.......',
        '......SSS.......',
        '..LLLSSSLLL.....',
        '..LLLLSLLLLL....',
        '...LLLSLLLLL....',
        '....LLSSSLLL....',
        '.....SSSS.LL....',
        '.....GGG........',
      ],
      chars: {
        P: { name: 'iris_petals', role: 'body' },
        H: { name: 'petal_veins', role: 'accessory' },
        C: { name: 'stamen_center', role: 'belt' },
        S: { name: 'stem', role: 'arm' },
        L: { name: 'sword_leaves', role: 'head' },
        G: { name: 'ground', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#8595a1' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. PINE CONE ─────────────────────────────────────────────
    {
      id: 'pine_cone_tk_16',
      description: 'Pine cone with layered chevron scales, stem cap, and branch segment.',
      grid: [
        '...NNNN.........',
        '..NNNNNNN.......',
        '...NNNNN........',
        '......CC........',
        '.....CCCC.......',
        '....OOIIOO......',
        '...OOIIIIOOO....',
        '...OOOIIIOOO....',
        '..OOOOIIOOOO....',
        '..OOIIIIIOOOO...',
        '..OOOOIIIIOOO...',
        '..OOOIIIIIOOO...',
        '...OOIIIIOO.....',
        '...OOOIIOOO.....',
        '....OOOOOO......',
        '.....OOOO.......',
      ],
      chars: {
        N: { name: 'pine_needles', role: 'head' },
        C: { name: 'stem_cap', role: 'belt' },
        O: { name: 'outer_scales', role: 'body' },
        I: { name: 'inner_scales', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 18. CAMELLIA FLOWER ───────────────────────────────────────
    {
      id: 'camellia_flower_tk_16',
      description: 'Tsubaki camellia bloom with glossy red petals and dark leaves.',
      grid: [
        '................',
        '................',
        '.....PPPPPP.....',
        '....PPPPPPPP....',
        '...PPPPCCPPPP...',
        '..PPPPCCCCPPPP..',
        '..PPPPCCCCPPPP..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '..LLPPPPPPPLL...',
        '.LLLLLLLLLLLLL..',
        '.LLLLLLLLLLLLL..',
        '..LLLLLLLLLLL...',
        '...LLLLLLLLL....',
        '................',
      ],
      chars: {
        P: { name: 'petals', role: 'body' },
        C: { name: 'stamen_center', role: 'accessory' },
        L: { name: 'leaves', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 19. STEPPING STONES ───────────────────────────────────────
    {
      id: 'stepping_stones_tk_16',
      description: 'Large decorative garden stepping stone with moss and small plant in crack.',
      grid: [
        '................',
        '................',
        '...EEEEEEEEE....',
        '...ESSSSSSSSSE..',
        '..ESSSSSSSSSSE..',
        '..ESSSCCCSSSE...',
        '..ESSSCCCSSSE...',
        '..ESSSSPPSSSE...',
        '..ESSSPPPSSSE...',
        '..ESSMMPPSSE....',
        '...ESSMMSSSE....',
        '...EESSSSEE.....',
        '....EEEEEE......',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stone_surface', role: 'body' },
        E: { name: 'stone_edge', role: 'arm' },
        C: { name: 'crack_line', role: 'belt' },
        M: { name: 'moss_growth', role: 'accessory' },
        P: { name: 'plant_sprout', role: 'head' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        arm:       { shadow: '#442434', base: '#4e4a4e', highlight: '#757161' },
        belt:      { shadow: '#442434', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 20. SHIMENAWA ROPE ────────────────────────────────────────
    {
      id: 'shimenawa_rope_tk_16',
      description: 'Sacred straw rope decoration with zigzag paper streamers.',
      grid: [
        '................',
        '.RRRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRR..',
        '..RRBBRRBBRRBB..',
        '...RBBRRBBRRBB..',
        '..RRRRRRRRRRRRR.',
        '.RRRRRRRRRRRRR..',
        '..ZZ..ZZ..ZZ....',
        '..ZZ..ZZ..ZZ....',
        '..ZZ..ZZ..ZZ....',
        '...Z..ZZ..ZZ....',
        '...Z...Z...Z....',
        '...Z...Z...Z....',
        '...T...T...T....',
        '...T...T...T....',
        '................',
      ],
      chars: {
        R: { name: 'straw_rope', role: 'body' },
        B: { name: 'rope_bulge', role: 'arm' },
        Z: { name: 'zigzag_paper', role: 'head' },
        T: { name: 'paper_tails', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
