/**
 * Tokyo batch 6 — 20 Japanese seasonal events & festival props.
 * Covers: kadomatsu, kagami mochi, otoshidama, daruma doll, omamori charm,
 *         ema board, furin windchime, tanabata wish, hanabi burst, uchiwa fan,
 *         happi coat, mikoshi shrine, taiko drum, koinobori, hina doll,
 *         teru teru bozu, christmas kfc bucket, temple bell, setsubun mask,
 *         chitose-ame bag.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: { templates: 'TOKYO_BATCH6_TEMPLATES', schemes: 'TOKYO_BATCH6_COLOR_SCHEMES' },
  templates: [

    // --- 1. KADOMATSU ---------------------------------------------------
    {
      id: 'kadomatsu_tk_16',
      description: 'New Year bamboo and pine decoration with three cut bamboo stalks and pine sprigs.',
      grid: [
        '......GBG.......',
        '.....GBBBG......',
        '....GGBGBGG.....',
        '...GGGBGBGGG....',
        '..GGGGBGBGGGG...',
        '..GGGGBGBGGGG...',
        '...GGGBGBGGG....',
        '...PPBBBBBPP....',
        '...PPBBBBBPP....',
        '...PPBPBPBPP....',
        '...PPBPBPBPP....',
        '...WWWWWWWWW....',
        '...WWWWWWWWW....',
        '..WWWWWWWWWWW...',
        '..TTTTTTTTTTT...',
        '................',
      ],
      chars: {
        B: { name: 'bamboo_stalks', role: 'body' },
        G: { name: 'pine_sprigs', role: 'accessory' },
        P: { name: 'bamboo_base', role: 'arm' },
        W: { name: 'straw_wrap', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 2. KAGAMI MOCHI ------------------------------------------------
    {
      id: 'kagami_mochi_tk_16',
      description: 'Stacked mirror mochi with daidai orange on top and wooden stand.',
      grid: [
        '................',
        '......LLL.......',
        '.....LOOOLL.....',
        '.....OOOOO......',
        '......OOO.......',
        '....MMMMMMM.....',
        '...MMMEEMMMM....',
        '...MMMMMMMMMM...',
        '....MMMMMMMM....',
        '...BBBBBBBBBB...',
        '..BBBBBEBBBBBB..',
        '..BBBBBBBBBBBBB.',
        '...BBBBBBBBBBB..',
        '..WWWWWWWWWWWWW.',
        '..TTTTTTTTTTTTT.',
        '................',
      ],
      chars: {
        L: { name: 'leaf_top', role: 'accessory' },
        O: { name: 'orange_daidai', role: 'head' },
        M: { name: 'top_mochi', role: 'body' },
        E: { name: 'mochi_shine', role: 'eye' },
        B: { name: 'bottom_mochi', role: 'arm' },
        W: { name: 'wooden_stand', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 3. OTOSHIDAMA --------------------------------------------------
    {
      id: 'otoshidama_tk_16',
      description: 'New Year money envelope with gold seal and decorative pattern.',
      grid: [
        '................',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...RRRRGGRRRRR..',
        '...RRRGGGGRRR...',
        '...RRRRGGRRRRR..',
        '...RRRRRRRRRR...',
        '...RRRPPPPRRR...',
        '...RRRPPPPRRR...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '...TTTTTTTTTT...',
        '................',
      ],
      chars: {
        R: { name: 'envelope_body', role: 'body' },
        G: { name: 'gold_seal', role: 'accessory' },
        P: { name: 'pattern_motif', role: 'head' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 4. DARUMA DOLL -------------------------------------------------
    {
      id: 'daruma_doll_tk_16',
      description: 'Round red Daruma wishing doll with solid gold trim band, contiguous face, and 2x2 eye whites.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '....RRGGGGRR....',
        '...RGFFFFFFGR...',
        '...RGFEEFEEGR...',
        '...RGFEEFEEGR...',
        '...RGFFFFFFGR...',
        '...RRGFDDFGRR...',
        '....RRGGGGRR....',
        '...RRRRRRRRRR...',
        '..RRRRDDDDRRRR..',
        '..RRRRDDDDRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        R: { name: 'red_body', role: 'body' },
        G: { name: 'gold_trim', role: 'accessory' },
        F: { name: 'face_skin', role: 'head' },
        E: { name: 'eye_whites', role: 'eye' },
        D: { name: 'belly_kanji', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 5. OMAMORI CHARM -----------------------------------------------
    {
      id: 'omamori_charm_tk_16',
      description: 'Shrine protective charm bag with tassel and kanji pattern.',
      grid: [
        '................',
        '.......SS.......',
        '......SSSS......',
        '.......SS.......',
        '.....GGGGGG.....',
        '....GRRRRRRG....',
        '....RRRRRRRR....',
        '....RRRPPRRR....',
        '....RRRPPRRR....',
        '....RRRPPRRR....',
        '....RRRRRRRR....',
        '....RRRRRRRR....',
        '.....RRRRRR.....',
        '......TTTT......',
        '.......TT.......',
        '................',
      ],
      chars: {
        S: { name: 'knot_string', role: 'accessory' },
        G: { name: 'gold_border', role: 'belt' },
        R: { name: 'charm_fabric', role: 'body' },
        P: { name: 'kanji_text', role: 'head' },
        T: { name: 'tassel_fringe', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // --- 6. EMA BOARD ---------------------------------------------------
    {
      id: 'ema_board_tk_16',
      description: 'Wooden prayer plaque with peaked roof shape and wish text.',
      grid: [
        '................',
        '......SSS.......',
        '.......S........',
        '......RRR.......',
        '.....RRRRR......',
        '....RRRRRRR.....',
        '...RRRRRRRRR....',
        '..WWWWWWWWWWW...',
        '..WWWWWWWWWWW...',
        '..WWWPPPPWWWW...',
        '..WWWPPPPWWWW...',
        '..WWWPPPPWWWW...',
        '..WWWWWWWWWWW...',
        '..WWWWWWWWWWW...',
        '..TTTTTTTTTTT...',
        '................',
      ],
      chars: {
        S: { name: 'hanging_string', role: 'accessory' },
        R: { name: 'roof_peak', role: 'head' },
        W: { name: 'wood_board', role: 'body' },
        P: { name: 'wish_text', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 7. FURIN WINDCHIME ---------------------------------------------
    {
      id: 'furin_windchime_tk_16',
      description: 'Glass wind chime with painted flowers and dangling tanzaku paper strip.',
      grid: [
        '......SS........',
        '.......S........',
        '.....GGGG.......',
        '....GGGGGG......',
        '...GGGFFGGG.....',
        '...GGFFFFGG.....',
        '...GGFFGGGG.....',
        '....GGGGGG......',
        '.....GGGG.......',
        '......CC........',
        '......CC........',
        '.....PPPP.......',
        '.....PPPP.......',
        '.....PPPP.......',
        '.....PPPP.......',
        '......PP........',
      ],
      chars: {
        S: { name: 'hanging_hook', role: 'accessory' },
        G: { name: 'glass_bell', role: 'body' },
        F: { name: 'painted_flower', role: 'head' },
        C: { name: 'clapper_string', role: 'belt' },
        P: { name: 'tanzaku_strip', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
      },
    },

    // --- 8. TANABATA WISH -----------------------------------------------
    {
      id: 'tanabata_wish_tk_16',
      description: 'Tanabata wish tag tied to bamboo branch with colorful paper strip.',
      grid: [
        '..B.............',
        '..BB............',
        '..BGBB..........',
        '..BGGGB.........',
        '..BBBGBB........',
        '...BBBGB........',
        '....BSSB........',
        '....SSSS........',
        '...PPPPPP.......',
        '...PPTTPP.......',
        '...PPTTPP.......',
        '...PPTTPP.......',
        '...PPPPPP.......',
        '....PPPP........',
        '.....PP.........',
        '................',
      ],
      chars: {
        B: { name: 'bamboo_branch', role: 'accessory' },
        G: { name: 'bamboo_leaves', role: 'arm' },
        S: { name: 'tie_string', role: 'belt' },
        P: { name: 'wish_paper', role: 'body' },
        T: { name: 'kanji_writing', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // --- 9. HANABI BURST ------------------------------------------------
    {
      id: 'hanabi_burst_tk_16',
      description: 'Fireworks cross-burst with bright center, thick radiating arms, and spark tips.',
      grid: [
        '................',
        '......KKKK......',
        '......SSSS......',
        '......SSSS......',
        '......IIII......',
        '......IIII......',
        'KKSSIICCCCIISSKK',
        'KKSSIICEECIISSKK',
        'KKSSIICEECIISSKK',
        'KKSSIICCCCIISSKK',
        '......IIII......',
        '......IIII......',
        '......SSSS......',
        '......SSSS......',
        '......KKKK......',
        '................',
      ],
      chars: {
        E: { name: 'bright_center', role: 'eye' },
        C: { name: 'core_glow', role: 'head' },
        I: { name: 'inner_burst', role: 'body' },
        S: { name: 'outer_streaks', role: 'accessory' },
        K: { name: 'spark_tips', role: 'arm' },
      },
      colors: {
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // --- 10. UCHIWA FAN -------------------------------------------------
    {
      id: 'uchiwa_fan_tk_16',
      description: 'Round festival fan with decorative border rim, wave pattern, center motif, and bamboo handle.',
      grid: [
        '................',
        '......OOOO......',
        '....OOFFFFOO....',
        '...OOFFFFFFOO...',
        '..OOFPPFFPPFOO..',
        '..OOFFPDDPFFOO..',
        '..OOFFPDDPFFOO..',
        '..OOFPPFFPPFOO..',
        '...OOFFFFFFOO...',
        '....OOFFFFOO....',
        '......OOOO......',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '................',
      ],
      chars: {
        O: { name: 'border_rim', role: 'accessory' },
        F: { name: 'fan_face', role: 'body' },
        P: { name: 'wave_pattern', role: 'head' },
        D: { name: 'center_motif', role: 'arm' },
        H: { name: 'bamboo_handle', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 11. HAPPI COAT -------------------------------------------------
    {
      id: 'happi_coat_tk_16',
      description: 'Festival happi coat laid flat with bold back design and sash.',
      grid: [
        '................',
        '..SSBBBBBBBSS...',
        '..SSBBBBBBBSS...',
        '..SSBBBPBBBSS...',
        '..SSBBBPBBBSS...',
        '..SSBPPPPPBSS...',
        '..SSBBBPBBBSS...',
        '..SSBBBBBBBSS...',
        '..SSGGGGGGGSS...',
        '..SSBBBBBBBSS...',
        '..SSBBBBBBBSS...',
        '..SSBBBBBBBSS...',
        '..SSBBBBBBBSS...',
        '..SSBBBBBBBSS...',
        '..TTTTTTTTTTT...',
        '................',
      ],
      chars: {
        B: { name: 'coat_fabric', role: 'body' },
        S: { name: 'coat_sleeves', role: 'arm' },
        P: { name: 'back_design', role: 'head' },
        G: { name: 'sash_belt', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:  { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // --- 12. MIKOSHI SHRINE ---------------------------------------------
    {
      id: 'mikoshi_shrine_tk_16',
      description: 'Simplified portable festival shrine with golden phoenix and red lacquer.',
      grid: [
        '.....GGG........',
        '....GGGGG.......',
        '...RRRRRRR......',
        '..RRRRRRRRR.....',
        '.RRRRRRRRRRR....',
        '..RRRRRRRRRRRR..',
        '..RBBBBBBBBBR...',
        '..RBBGGGGBBBR...',
        '..RBBBBBBBBBR...',
        '..RBBBBBBBBBR...',
        '..RRRRRRRRRRRR..',
        '..RDDDDDDDDDDR..',
        '..DDDDDDDDDDDD..',
        '.PPPPPPPPPPPPPP.',
        '.PPPP......PPPP.',
        '................',
      ],
      chars: {
        G: { name: 'golden_roof', role: 'accessory' },
        R: { name: 'red_lacquer', role: 'body' },
        B: { name: 'shrine_interior', role: 'head' },
        D: { name: 'base_platform', role: 'belt' },
        P: { name: 'carrying_poles', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 13. TAIKO DRUM -------------------------------------------------
    {
      id: 'taiko_drum_tk_16',
      description: 'Festival taiko drum on stand with tacked leather head and rope lacing.',
      grid: [
        '................',
        '................',
        '....TTTTTTTT....',
        '...TTTTTTTTTT...',
        '..TTTTHHTTTTTT..',
        '..TTTTTTTTTTT...',
        '..RRBBBBBBBRR...',
        '..RRBBBBBBBRR...',
        '..RRBBHBHBBRR...',
        '..RRBBBBBBBRR...',
        '..RRBBBBBBBRR...',
        '...LLLLLLLLL....',
        '...LLLLLLLLL....',
        '..SS.......SS...',
        '..SS.......SS...',
        '................',
      ],
      chars: {
        T: { name: 'drum_head', role: 'head' },
        H: { name: 'head_tacks', role: 'eye' },
        R: { name: 'rope_lacing', role: 'accessory' },
        B: { name: 'drum_body', role: 'body' },
        L: { name: 'drum_rim', role: 'belt' },
        S: { name: 'stand_legs', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // --- 14. KOINOBORI ---------------------------------------------------
    {
      id: 'koinobori_tk_16',
      description: 'Carp streamer flag blowing in wind on a pole for Childrens Day.',
      grid: [
        '.P..............',
        '.P..............',
        '.PGGGG..........',
        '.PRRRRRRR.......',
        '.PRREERRRRR.....',
        '.PRRRRRRRRRR....',
        '.PRRRSSRRRRSR...',
        '.PRRRRRRRRRR....',
        '.P.RRRRRRRR.....',
        '.P..BBBBBBB.....',
        '.P.BBBEEBBBB....',
        '.P.BBBBBBBBBBB..',
        '.P.BBBSSBBBSBB..',
        '.P.BBBBBBBBBB...',
        '.P..BBBBBBB.....',
        '.P..............',
      ],
      chars: {
        P: { name: 'pole', role: 'belt' },
        G: { name: 'golden_spinner', role: 'accessory' },
        R: { name: 'red_carp', role: 'body' },
        B: { name: 'blue_carp', role: 'arm' },
        E: { name: 'fish_eye', role: 'eye' },
        S: { name: 'fish_scales', role: 'head' },
      },
      colors: {
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // --- 15. HINA DOLL --------------------------------------------------
    {
      id: 'hina_doll_tk_16',
      description: 'Hina matsuri emperor and empress doll pair side by side on red platform.',
      grid: [
        '................',
        '...HH....HH.....',
        '...HH....HH.....',
        '..FFFF..FFFF....',
        '..FBBF..FRRRF...',
        '..FBBF..FRRRF...',
        '..FBBF..FRRRF...',
        '.FBBBBFFRRRRRF..',
        '.FBBBBFFRRRRRF..',
        '.FBBBBFFRRRRRF..',
        '..FBBBFFRRRRF...',
        '..FBBF..FRRF....',
        '.PPPPPPPPPPPP...',
        '.PPPPPPPPPPPP...',
        '.TTTTTTTTTTTT...',
        '................',
      ],
      chars: {
        H: { name: 'headpieces', role: 'head' },
        F: { name: 'face_details', role: 'eye' },
        B: { name: 'emperor_robe', role: 'body' },
        R: { name: 'empress_robe', role: 'arm' },
        P: { name: 'red_platform', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 16. TERU TERU BOZU ---------------------------------------------
    {
      id: 'teru_teru_tk_16',
      description: 'Teru teru bozu rain charm doll made of white cloth with drawn face.',
      grid: [
        '................',
        '.......SS.......',
        '......SSSS......',
        '.......SS.......',
        '.....WWWWWW.....',
        '....WWWWWWWW....',
        '....WWEWWEWW....',
        '....WWWWWWWW....',
        '....WWWMMWWW....',
        '.....WWWWWW.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBB....',
        '....BBB.BBB.....',
        '................',
      ],
      chars: {
        S: { name: 'hanging_string', role: 'accessory' },
        W: { name: 'cloth_head', role: 'body' },
        E: { name: 'drawn_eyes', role: 'eye' },
        M: { name: 'drawn_mouth', role: 'head' },
        B: { name: 'cloth_body', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#8595a1', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // --- 17. CHRISTMAS KFC BUCKET ---------------------------------------
    {
      id: 'christmas_kfc_tk_16',
      description: 'KFC bucket with fried chicken for Tokyo Christmas tradition with festive ribbon.',
      grid: [
        '................',
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '...GRRRRRRRG....',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RCCCCCCCCCCRR.',
        '..RCCCCCCCCCCR..',
        '..RCCCCCCCCCCRR.',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        G: { name: 'chicken_tops', role: 'head' },
        R: { name: 'red_bucket', role: 'body' },
        C: { name: 'white_stripe', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 18. NEW YEAR BELL ----------------------------------------------
    {
      id: 'new_year_bell_tk_16',
      description: 'Temple bell (joya no kane) hanging from wooden frame for New Year.',
      grid: [
        '..WWWWWWWWWWW...',
        '..WWWWWWWWWWW...',
        '...WWWRRWWWW....',
        '.....RRRR.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBHBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBHBBBBB....',
        '..BBBBBBBBBB....',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..TTTTTTTTTTT...',
        '................',
      ],
      chars: {
        W: { name: 'wooden_frame', role: 'accessory' },
        R: { name: 'rope_ties', role: 'arm' },
        B: { name: 'bronze_bell', role: 'body' },
        H: { name: 'bell_studs', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // --- 19. SETSUBUN MASK ----------------------------------------------
    {
      id: 'setsubun_mask_tk_16',
      description: 'Oni demon mask for Setsubun bean-throwing with horns and fangs.',
      grid: [
        '................',
        '...HH.....HH....',
        '...HHH...HHH....',
        '....HHRRRRHH....',
        '...RRRRRRRR.....',
        '..RRRRRRRRRR....',
        '..RREERREERR....',
        '..RRRRRRRRRR....',
        '..RRRNRRRNRRR...',
        '..RRRRRRRRRR....',
        '..RRFFFFFFFF....',
        '...RRRRRRRRRR...',
        '....RRRRRRRRR...',
        '.....RRRRRR.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'horns', role: 'accessory' },
        R: { name: 'red_face', role: 'body' },
        E: { name: 'angry_eyes', role: 'eye' },
        N: { name: 'nose_dots', role: 'head' },
        F: { name: 'fanged_mouth', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // --- 20. SHICHI-GO-SAN CHITOSE-AME BAG ------------------------------
    {
      id: 'shichi_go_san_tk_16',
      description: 'Chitose-ame candy bag with crane and turtle motif for Shichi-Go-San festival.',
      grid: [
        '................',
        '....CCCC........',
        '....CCCC........',
        '....CCCC........',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '..RRRRRRRRRR....',
        '..RRRPPPRRRRR...',
        '..RRRPPPRRRRR...',
        '..RRRPPPRRRRR...',
        '..RRRRRRRRRR....',
        '..RRRRRRRRRR....',
        '..RRRRRRRRRR....',
        '...RRRRRRRRR....',
        '...TTTTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'candy_sticks', role: 'head' },
        R: { name: 'bag_body', role: 'body' },
        P: { name: 'crane_motif', role: 'accessory' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
