/**
 * Tokyo batch 5 — 20 pop culture, otaku & entertainment item templates.
 * Covers: manga volume, anime DVD case, figurine box, gunpla box,
 *         trading card, idol lightstick, concert ticket, cosplay wig,
 *         game cartridge, handheld console, arcade token, gacha capsule,
 *         plushie bear, strap charm, purikura strip, lucky bag,
 *         cd album, anime poster roll, keychain acrylic, nendoroid figure.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'items',
  exportNames: { templates: 'TOKYO_BATCH5_TEMPLATES', schemes: 'TOKYO_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ─── 1. MANGA VOLUME ─────────────────────────────────────────
    {
      id: 'manga_volume_tk_16',
      description: 'Manga tankobon volume with visible spine, cover art area, and title band.',
      grid: [
        '................',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBCCCCCCBB..',
        '..SSBBTTTTTTBB..',
        '..SSBBTTTTTTBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..SSBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
      ],
      chars: {
        S: { name: 'spine', role: 'arm' },
        B: { name: 'cover', role: 'body' },
        C: { name: 'cover_art', role: 'head' },
        T: { name: 'title_band', role: 'eye' },
        G: { name: 'page_edge', role: 'leg' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        leg:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. GASHAPON MACHINE ───────────────────────────────────────
    {
      id: 'gashapon_machine_tk_16',
      description: 'Gashapon capsule vending machine with glass dome showing colorful capsules, coin slot, turn knob, and dispenser chute.',
      grid: [
        '................',
        '................',
        '...MMMMMMMMMM...',
        '...MGGGGGGGGM...',
        '...MGCCCCCCGM...',
        '...MGCCCCCCGM...',
        '...MGCCCCCCGM...',
        '...MGGGGGGGGM...',
        '...MMMMMMMMMM...',
        '...MDDMMMMKMM...',
        '...MMMMMMMMMM...',
        '...MMEEEEEEMM...',
        '...MMMMMMMMMM...',
        '...MMMM..MMMM...',
        '................',
        '................',
      ],
      chars: {
        M: { name: 'machine_body', role: 'body' },
        G: { name: 'glass_dome', role: 'head' },
        C: { name: 'capsules_inside', role: 'eye' },
        D: { name: 'coin_slot', role: 'arm' },
        K: { name: 'turn_knob', role: 'accessory' },
        E: { name: 'dispenser_chute', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. FIGURINE BOX ─────────────────────────────────────────
    {
      id: 'figurine_box_tk_16',
      description: 'Collectible figure in display box with transparent window and printed backing.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBWWWWWWWWBB..',
        '..BBWWWWWWWWBB..',
        '..BBWWFFWWWWBB..',
        '..BBWWFFWWWWBB..',
        '..BBWFFFFWWWBB..',
        '..BBWWFFWWWWBB..',
        '..BBWWFFWWWWBB..',
        '..BBWWWWWWWWBB..',
        '..BBBBBBBBBBBB..',
        '..BBTTTTTTTTBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '................',
      ],
      chars: {
        B: { name: 'box_frame', role: 'body' },
        W: { name: 'window_clear', role: 'eye' },
        F: { name: 'figure_silhouette', role: 'head' },
        T: { name: 'brand_label', role: 'arm' },
        G: { name: 'box_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 4. GUNPLA BOX ───────────────────────────────────────────
    {
      id: 'gunpla_box_tk_16',
      description: 'Gundam model kit box with mecha art on front and grade stripe.',
      grid: [
        '................',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.BBCCCCCCCCCCB..',
        '.BBCMMCCCCMCCB..',
        '.BBCMMMMMMMMCB..',
        '.BBCMMMMMMMCCB..',
        '.BBCMMMMMMMMCB..',
        '.BBCCCCCCCCCCB..',
        '.BBSSSSSSSSSSB..',
        '.BBTTTTTTTTTTB..',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '.GGGGGGGGGGGGG..',
        '................',
      ],
      chars: {
        B: { name: 'box_body', role: 'body' },
        C: { name: 'art_background', role: 'head' },
        M: { name: 'mecha_art', role: 'arm' },
        S: { name: 'grade_stripe', role: 'eye' },
        T: { name: 'title_bar', role: 'accessory' },
        G: { name: 'box_bottom', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#140c1c', base: '#30346d', highlight: '#597dce' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#30346d', highlight: '#4e4a4e' },
      },
    },

    // ─── 5. TRADING CARD ─────────────────────────────────────────
    {
      id: 'trading_card_tk_16',
      description: 'Trading card with character art area, name plate, and holographic border.',
      grid: [
        '................',
        '...FFFFFFFFFF...',
        '...FBBBBBBBBF...',
        '...FBCCCCCCBF...',
        '...FBCCCCCCBF...',
        '...FBCCAACCBF...',
        '...FBCCAACCBF...',
        '...FBCCCCCCBF...',
        '...FBCCCCCCBF...',
        '...FBBBBBBBBF...',
        '...FBTTTTTTBF...',
        '...FBTTTTTTBF...',
        '...FBBBBBBBBF...',
        '...FFFFFFFFFF...',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'holo_border', role: 'accessory' },
        B: { name: 'card_frame', role: 'body' },
        C: { name: 'character_art', role: 'head' },
        A: { name: 'art_detail', role: 'eye' },
        T: { name: 'name_plate', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 6. IDOL LIGHTSTICK ──────────────────────────────────────
    {
      id: 'idol_lightstick_tk_16',
      description: 'Concert idol penlight with large glowing crystal dome, star emblem center, connector ring, and wide grip handle.',
      grid: [
        '....GGGGGGGG....',
        '...GGGGGGGGGG...',
        '..GGLLLLLLLLGG..',
        '..GGLLLLLLLLGG..',
        '..GGLLSSSSLLGG..',
        '..GGLLSSSSLLGG..',
        '..GGLLLLLLLLGG..',
        '...GGGGGGGGGG...',
        '....GGGGGGGG....',
        '......RRRR......',
        '......HHHH......',
        '......HHHH......',
        '......HHHH......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '................',
      ],
      chars: {
        G: { name: 'glow_shell', role: 'head' },
        L: { name: 'light_core', role: 'eye' },
        S: { name: 'star_emblem', role: 'accessory' },
        R: { name: 'ring_connector', role: 'arm' },
        H: { name: 'handle_shaft', role: 'body' },
        B: { name: 'grip_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. CONCERT TICKET ───────────────────────────────────────
    {
      id: 'concert_ticket_tk_16',
      description: 'Live concert ticket with perforated tear line and event logo.',
      grid: [
        '................',
        '................',
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBCCCCCCBBTTBB.',
        '.BBCCLLCCBBTTBB.',
        '.BBCCLLCCBBTTBB.',
        '.BBCCCCCCBBTTBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBEEEEEEBBBEBB.',
        '.BBBBBBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'ticket_body', role: 'body' },
        C: { name: 'event_area', role: 'head' },
        L: { name: 'logo_mark', role: 'eye' },
        T: { name: 'tear_perf', role: 'arm' },
        E: { name: 'text_lines', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 8. COSPLAY WIG ──────────────────────────────────────────
    {
      id: 'cosplay_wig_tk_16',
      description: 'Symmetrical spiky cosplay wig on a centered mannequin head stand with balanced left-right hair and visible face.',
      grid: [
        '...HH......HH...',
        '..HHHH....HHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHFFFFHHHH..',
        '..HHHEEFFEEHHH..',
        '..HHHEEFFEEHHH..',
        '...HHHHFFHHHH...',
        '....HHFFFFHH....',
        '.....HHHHHH.....',
        '......SSSS......',
        '......SSSS......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '................',
      ],
      chars: {
        H: { name: 'wig_hair', role: 'head' },
        F: { name: 'face_skin', role: 'arm' },
        E: { name: 'mannequin_eyes', role: 'eye' },
        S: { name: 'neck_post', role: 'accessory' },
        B: { name: 'stand_base', role: 'body' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. GAME CARTRIDGE ───────────────────────────────────────
    {
      id: 'game_cartridge_tk_16',
      description: 'Retro game cartridge with label sticker and connector pins.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBLLLLLLLLBB..',
        '..BBLLLLLLLLBB..',
        '..BBLLCCLLLLBB..',
        '..BBLLCCLLLLBB..',
        '..BBLLLLLLLLBB..',
        '..BBLLLLLLLLBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...PPPPPPPPPP...',
        '...PPPPPPPPPP...',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cart_shell', role: 'body' },
        L: { name: 'label_area', role: 'head' },
        C: { name: 'label_art', role: 'eye' },
        P: { name: 'connector_pins', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 10. HANDHELD CONSOLE ────────────────────────────────────
    {
      id: 'handheld_console_tk_16',
      description: 'Handheld gaming console with backlit screen, solid d-pad, colored action buttons, and speaker grille. No transparent holes inside body.',
      grid: [
        '................',
        '...BBBBBBBBBB...',
        '...BSSSSSSSSB...',
        '...BSSSSSSSSB...',
        '...BSSSSSSSSB...',
        '...BSSSSSSSSB...',
        '...BBBBBBBBBB...',
        '...BDDBBBAABB...',
        '...BDDBBBAABB...',
        '...BBBBBBBBBB...',
        '...BBTTTTTTBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'console_body', role: 'body' },
        S: { name: 'screen_display', role: 'head' },
        D: { name: 'dpad_cross', role: 'arm' },
        A: { name: 'action_buttons', role: 'eye' },
        T: { name: 'speaker_grille', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 11. ARCADE TOKEN ────────────────────────────────────────
    {
      id: 'arcade_token_tk_16',
      description: 'Perfectly symmetric arcade medal coin with ridged edge, text ring, polished face, star emblem, and center jewel.',
      grid: [
        '................',
        '................',
        '......EEEE......',
        '...EEERRRREEE...',
        '..EERRFFFFRREE..',
        '.ERRFFFSSFFFRRE.',
        '.ERRFFSSSSFFRRE.',
        '.ERRFSSCCSSFRRE.',
        '.ERRFSSCCSSFRRE.',
        '.ERRFFSSSSFFRRE.',
        '.ERRFFFSSFFFRRE.',
        '..EERRFFFFRREE..',
        '...EEERRRREEE...',
        '......EEEE......',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'coin_edge', role: 'boot' },
        R: { name: 'text_ring', role: 'arm' },
        F: { name: 'coin_face', role: 'body' },
        S: { name: 'star_emblem', role: 'head' },
        C: { name: 'center_jewel', role: 'eye' },
      },
      colors: {
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 12. GACHA CAPSULE ───────────────────────────────────────
    {
      id: 'gacha_capsule_tk_16',
      description: 'Gacha toy capsule cracked open with small toy visible inside.',
      grid: [
        '................',
        '......TTTT......',
        '.....TTTTTT.....',
        '....TTTTTTTT....',
        '....TTTTTTTT....',
        '.....TTTTTT.....',
        '....TTTTTTTT....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBFFBBBB...',
        '...BBBBFFBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'top_shell', role: 'head' },
        B: { name: 'bottom_shell', role: 'body' },
        F: { name: 'toy_inside', role: 'eye' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 13. PLUSHIE BEAR ────────────────────────────────────────
    {
      id: 'plushie_bear_tk_16',
      description: 'Cute plush teddy bear with round ears, button eyes, and bow tie.',
      grid: [
        '....HH....HH....',
        '...HHHH..HHHH...',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '...HHEEHHEEHHH..',
        '...HHHHNNHHHH...',
        '....HHHHHHHH....',
        '.....HBBBBH.....',
        '...AAHBBBBHAA...',
        '...AAAHHHHAAA...',
        '...AAAHHHHAAA...',
        '....AAAAAAAAA...',
        '....LLLL.LLLL...',
        '....LLL...LLL...',
        '................',
      ],
      chars: {
        H: { name: 'head_fur', role: 'head' },
        E: { name: 'button_eyes', role: 'eye' },
        N: { name: 'nose_snout', role: 'accessory' },
        B: { name: 'bow_tie', role: 'belt' },
        A: { name: 'body_fur', role: 'body' },
        L: { name: 'legs_feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. STRAP CHARM ─────────────────────────────────────────
    {
      id: 'strap_charm_tk_16',
      description: 'Large kawaii mascot phone charm laying flat with small metal loop and connector ring, cute face with eyes and mouth on round body.',
      grid: [
        '.......LL.......',
        '......LCCL......',
        '.......LL.......',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBDDDDDDBB...',
        '...BBDDAADDBB...',
        '...BBDDAADDBB...',
        '...BBDDDDDDBB...',
        '...BBDDFFDDBB...',
        '...BBDDDDDDBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'metal_loop', role: 'arm' },
        C: { name: 'connector_ring', role: 'accessory' },
        B: { name: 'charm_body', role: 'body' },
        D: { name: 'design_surface', role: 'head' },
        A: { name: 'eye_detail', role: 'eye' },
        F: { name: 'mouth_detail', role: 'belt' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 15. PURIKURA STRIP ──────────────────────────────────────
    {
      id: 'purikura_strip_tk_16',
      description: 'Photo booth strip with three cute decorated photo frames stacked vertically.',
      grid: [
        '................',
        '....BBBBBBBB....',
        '....BPPPPPPB....',
        '....BPPFFPPB....',
        '....BPPFFPPB....',
        '....BPPPPPPB....',
        '....BBBBBBBB....',
        '....BPPPPPPB....',
        '....BPPFFPPB....',
        '....BPPFFPPB....',
        '....BPPPPPPB....',
        '....BBBBBBBB....',
        '....BSSSSSSB....',
        '....BSSSSSSB....',
        '....BBBBBBBB....',
        '................',
      ],
      chars: {
        B: { name: 'strip_border', role: 'body' },
        P: { name: 'photo_area', role: 'head' },
        F: { name: 'face_spot', role: 'eye' },
        S: { name: 'sticker_deco', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. LUCKY BAG ───────────────────────────────────────────
    {
      id: 'lucky_bag_tk_16',
      description: 'Fukubukuro lucky bag with festive ribbon tie and kanji-style decoration.',
      grid: [
        '................',
        '....TTTTTTTT....',
        '....TTTTTTTT....',
        '......RRRR......',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '...BBBBBBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBDDDDBBBB..',
        '..BBBBDDDDBBBB..',
        '..BBBBDDDDBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....GGGGGGGG....',
        '................',
      ],
      chars: {
        T: { name: 'bag_top_ruffle', role: 'head' },
        R: { name: 'ribbon_tie', role: 'eye' },
        B: { name: 'bag_body', role: 'body' },
        D: { name: 'lucky_kanji', role: 'accessory' },
        G: { name: 'bag_bottom', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 17. CD ALBUM ────────────────────────────────────────────
    {
      id: 'cd_album_tk_16',
      description: 'Music CD album case with jewel case cover art and disc visible on side.',
      grid: [
        '................',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBCCCCCCCCBB..',
        '..BBCCCCCCCCBB..',
        '..BBCCCAACCCBB..',
        '..BBCCCAACCCBB..',
        '..BBCCCCCCCCBB..',
        '..BBCCCCCCCCBB..',
        '..BBBBBBBBBBBB..',
        '..BBTTTTTTTDBB..',
        '..BBTTTTTTTDBB..',
        '..BBBBBBBBDDBB..',
        '..BBBBBBBBBBBB..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'jewel_case', role: 'body' },
        C: { name: 'cover_art', role: 'head' },
        A: { name: 'art_center', role: 'eye' },
        T: { name: 'title_area', role: 'arm' },
        D: { name: 'disc_edge', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. ANIME WALL POSTER ────────────────────────────────────
    {
      id: 'anime_wall_poster_tk_16',
      description: 'Flat anime wall poster with wooden frame, printed character artwork, highlight detail, title text area, and thumbtack pin at top center.',
      grid: [
        '................',
        '.......PP.......',
        '...FFFFFFFFFF...',
        '...FBBBBBBBBF...',
        '...FBCCCCCCBF...',
        '...FBCCCCCCBF...',
        '...FBCCAACCBF...',
        '...FBCCAACCBF...',
        '...FBCCCCCCBF...',
        '...FBBBBBBBBF...',
        '...FBTTTTTTBF...',
        '...FBBBBBBBBF...',
        '...FFFFFFFFFF...',
        '................',
        '................',
        '................',
      ],
      chars: {
        P: { name: 'thumbtack_pin', role: 'accessory' },
        F: { name: 'poster_frame', role: 'body' },
        B: { name: 'poster_background', role: 'arm' },
        C: { name: 'character_artwork', role: 'head' },
        A: { name: 'art_highlight', role: 'eye' },
        T: { name: 'title_text', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 19. KEYCHAIN ACRYLIC ────────────────────────────────────
    {
      id: 'keychain_acrylic_tk_16',
      description: 'Acrylic keychain charm with metal ring, clear border, and printed character.',
      grid: [
        '................',
        '.....MMM........',
        '....MMMMM.......',
        '....MMM.M.......',
        '.....CCC........',
        '....CCCCC.......',
        '...CCCCCCC......',
        '..CCCCCCCCCC....',
        '..CCBBBBBBCC....',
        '..CCBBFFBBCC....',
        '..CCBBFFBBCC....',
        '..CCBBBBBBCC....',
        '..CCCCCCCCCC....',
        '...CCCCCCCC.....',
        '....CCCCCC......',
        '................',
      ],
      chars: {
        M: { name: 'metal_ring', role: 'arm' },
        C: { name: 'acrylic_clear', role: 'body' },
        B: { name: 'character_print', role: 'head' },
        F: { name: 'face_detail', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 20. NENDOROID FIGURE ────────────────────────────────────
    {
      id: 'nendoroid_fig_tk_16',
      description: 'Chibi nendoroid figure on round display stand with oversized head.',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '..HHHEEHHEEHH...',
        '..HHHHHNNHHHH...',
        '..HHHHHHHHHH....',
        '...HHHHHHHH.....',
        '.....BBBB.......',
        '....AABBBBAA....',
        '....AABBBBAA....',
        '.....BBBB.......',
        '.....LLLL.......',
        '.....LLLL.......',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
      ],
      chars: {
        H: { name: 'chibi_hair', role: 'head' },
        E: { name: 'big_eyes', role: 'eye' },
        N: { name: 'tiny_mouth', role: 'accessory' },
        B: { name: 'body_torso', role: 'body' },
        A: { name: 'arms', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        S: { name: 'display_stand', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        accessory: { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

  ],
};

export default batch;
