/**
 * Veggies batch 2 — 20 leafy green & cruciferous vegetable templates
 * for farming simulator pixel art packs.
 * Covers: lettuce, cabbage, broccoli, cauliflower, spinach, kale,
 *         celery, bok choy, artichoke, asparagus, brussels sprout,
 *         swiss chard, arugula, collard greens, endive, fennel,
 *         watercress, radicchio, kohlrabi, romanesco.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'VEGGIES_BATCH2_TEMPLATES', schemes: 'VEGGIES_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. LETTUCE HEAD ────────────────────────────────────────
    {
      id: 'lettuce_head_16',
      description: 'Round head of iceberg lettuce with layered pale green leaves.',
      grid: [
        '................',
        '................',
        '......LLLL......',
        '.....LLLLLL.....',
        '....LLBBBBLL....',
        '...LLBBBBBBLL...',
        '...LBBBBHBBBL...',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '...LBBBBBBBBLL..',
        '...LLBBBBBBLL...',
        '....LLBBBBLL....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'outer_leaf', role: 'accessory' },
        B: { name: 'inner_leaf', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 2. CABBAGE ─────────────────────────────────────────────
    {
      id: 'cabbage_farm_16',
      description: 'Green cabbage head with purple-tinged outer leaves and lighter core.',
      grid: [
        '................',
        '................',
        '......LLLL......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLBBBBBBLL...',
        '...LBBBBHBBBL...',
        '..LLBBBBBBBBL...',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '...LLBBBBBBLL...',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'outer_leaf', role: 'accessory' },
        B: { name: 'inner_core', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#346524', highlight: '#346524' },
      },
    },

    // ─── 3. BROCCOLI ────────────────────────────────────────────
    {
      id: 'broccoli_farm_16',
      description: 'Green broccoli crown with floret texture and thick pale stem.',
      grid: [
        '................',
        '.....FFFFFF.....',
        '....FFFFFFFF....',
        '...FFXFFXFFFF...',
        '...FFFFFHFFFF...',
        '..FFFXFFFFXFFF..',
        '..FFFFFFFFFFFFFF',
        '...FFFFFFFFFFFF.',
        '....FFFFFFFFFF..',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        F: { name: 'floret', role: 'body' },
        X: { name: 'floret_gap', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        S: { name: 'stem', role: 'arm' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
      },
    },

    // ─── 4. CAULIFLOWER ─────────────────────────────────────────
    {
      id: 'cauliflower_farm_16',
      description: 'White cauliflower head surrounded by green wrapper leaves.',
      grid: [
        '................',
        '......LLLL......',
        '.....L....L.....',
        '....L.BBBB.L....',
        '...LLBBBBBBLL...',
        '...LBBXBBXBBL...',
        '..LLBBBBHBBBLL..',
        '..LLBXBBBBXBLL..',
        '..LLBBBBBBBBLL..',
        '...LBBXBBXBBL...',
        '...LLBBBBBBLL...',
        '....LLBBBBLL....',
        '.....LLLLLL.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'wrapper_leaf', role: 'accessory' },
        B: { name: 'curd', role: 'body' },
        X: { name: 'curd_gap', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 5. SPINACH BUNCH ───────────────────────────────────────
    {
      id: 'spinach_bunch_16',
      description: 'Bunch of dark green spinach leaves with thin stems.',
      grid: [
        '...LLL...LLL....',
        '..LLLLL.LLLLL...',
        '.LLLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '...LLLLLLLLLL...',
        '..LLLLL.LLLLL...',
        '.LLLLL...LLLLL..',
        '..LLLL...LLLL...',
        '...LLL...LLL....',
        '....SS...SS.....',
        '....SS...SS.....',
        '.....SS.SS......',
        '.....SSSSS......',
        '......SSS.......',
        '......SSS.......',
        '.......A........',
      ],
      chars: {
        L: { name: 'leaf', role: 'body' },
        S: { name: 'stem', role: 'arm' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 6. KALE LEAF ───────────────────────────────────────────
    {
      id: 'kale_leaf_16',
      description: 'Single curly kale leaf with ruffled edges and visible midrib.',
      grid: [
        '................',
        '..LLL....LLL....',
        '.LLLLL..LLLLL...',
        '.LLLLLLLLLLLL...',
        '..LLLBBBLLLLL...',
        '.LLLLBBBLLLLL...',
        '.LLLBBHBBLLLL...',
        '..LLBBBBBLLL....',
        '...LLBBBLLL.....',
        '....LBBBLLL.....',
        '.....SBBL.......',
        '......SSS.......',
        '......SSS.......',
        '.......SS.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf_edge', role: 'body' },
        B: { name: 'midrib', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        S: { name: 'stem', role: 'accessory' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#346524' },
      },
    },

    // ─── 7. CELERY STALK ────────────────────────────────────────
    {
      id: 'celery_stalk_16',
      description: 'Bundle of green celery stalks with leafy top.',
      grid: [
        '....LL..LL......',
        '...LLLLLLLL.....',
        '..LLLLLLLLL.....',
        '...LLLLLLLL.....',
        '....SSSSSS......',
        '....SHSSHS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '.....AAAA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'stalk', role: 'body' },
        H: { name: 'rib_shine', role: 'eye' },
        A: { name: 'base_cut', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 8. BOK CHOY ────────────────────────────────────────────
    {
      id: 'bok_choy_farm_16',
      description: 'Bok choy with white thick stems and dark green leaves.',
      grid: [
        '................',
        '...LLL..LLL.....',
        '..LLLL..LLLL....',
        '..LLLL..LLLL....',
        '..LLLLLLLLLL....',
        '...LLLLLLLL.....',
        '...LLSSSSLL.....',
        '....SSHSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '....SSSSSS......',
        '.....SSSS.......',
        '.....AAAA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'white_stem', role: 'body' },
        H: { name: 'stem_shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 9. ARTICHOKE ───────────────────────────────────────────
    {
      id: 'artichoke_farm_16',
      description: 'Green artichoke with layered overlapping scale-like leaves.',
      grid: [
        '................',
        '.......TT.......',
        '......TTTT......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLHLLLL...',
        '...LLLLLLLLLL...',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '...LLBBBBBBLL...',
        '...LLBBBBBBLL...',
        '....SSSSSSSS....',
        '.....SSSSSS.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        T: { name: 'tip_leaf', role: 'head' },
        L: { name: 'outer_scale', role: 'body' },
        B: { name: 'inner_scale', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        S: { name: 'stem', role: 'accessory' },
        A: { name: 'base_cut', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 10. ASPARAGUS BUNCH ────────────────────────────────────
    {
      id: 'asparagus_bunch_16',
      description: 'Bundle of green asparagus spears with pointed tips.',
      grid: [
        '....T..T..T.....',
        '...TT.TT.TT.....',
        '...TT.TT.TT.....',
        '...SS.SS.SS.....',
        '...SS.SS.SS.....',
        '...SSSSSSSS.....',
        '...SHSSSHSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '...SSSSSSSS.....',
        '....AAAAAA......',
        '................',
      ],
      chars: {
        T: { name: 'spear_tip', role: 'head' },
        S: { name: 'stalk', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'cut_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 11. BRUSSELS SPROUT ────────────────────────────────────
    {
      id: 'brussels_sprout_16',
      description: 'Small round brussels sprout with tightly wrapped leaves.',
      grid: [
        '................',
        '................',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '...LLBBBBBBLL...',
        '..LLLBBHBBBLL...',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '...LLBBBBBBLL...',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'outer_leaf', role: 'accessory' },
        B: { name: 'inner_leaf', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 12. SWISS CHARD ────────────────────────────────────────
    {
      id: 'swiss_chard_16',
      description: 'Colorful swiss chard leaf with bright red stems and dark green leaf.',
      grid: [
        '..LLLL...LLLL...',
        '.LLLLLL.LLLLLL..',
        '.LLLLLLLLLLLLL..',
        '.LLLLLLRLLLLLL..',
        '..LLLLLRLLLLLL..',
        '..LLLLRRRLLLLL..',
        '...LLLLRRLLLL...',
        '....LLLRRLLLL...',
        '.....LLRRLLL....',
        '......LRRLL.....',
        '......RRR.......',
        '......RRR.......',
        '......RRR.......',
        '.......RR.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'body' },
        R: { name: 'red_stem', role: 'arm' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 13. ARUGULA ────────────────────────────────────────────
    {
      id: 'arugula_farm_16',
      description: 'Spiky arugula leaves with jagged edges and thin stems.',
      grid: [
        '.L..L...L..L....',
        'LLL.LLL.LLL.LL..',
        'LLLLLLLLLLLLLLL.',
        '.LLLLL.LLLLLLL..',
        '.LLLL..LLLLLL...',
        '..LLL...LLLLL...',
        '..LLL..LLLL.....',
        '...LLLLLLLL.....',
        '....LSSSLL......',
        '....SSHSSS......',
        '....SSSSSS......',
        '.....SSSS.......',
        '.....SSSS.......',
        '......SS........',
        '......AA........',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'body' },
        S: { name: 'stem', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
      },
    },

    // ─── 14. COLLARD GREENS ─────────────────────────────────────
    {
      id: 'collard_greens_16',
      description: 'Large flat collard green leaves with thick central vein.',
      grid: [
        '................',
        '.LLLLLLLLLLLLL..',
        'LLLLLLLLLLLLLLLL',
        'LLLLLLRLLLLLLLL.',
        '.LLLLLRLLLLLLLL.',
        '.LLLLRRRLLLLLLL.',
        '..LLLLRRLLLLL...',
        '...LLLRRLLLL....',
        '....LLRRLLLL....',
        '.....LRRLLL.....',
        '......RR........',
        '......RR........',
        '......RR........',
        '......RR........',
        '.......A........',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'body' },
        R: { name: 'central_vein', role: 'arm' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 15. ENDIVE ─────────────────────────────────────────────
    {
      id: 'endive_farm_16',
      description: 'Pale green endive head with tightly packed elongated leaves.',
      grid: [
        '................',
        '......LLLL......',
        '.....L.LL.L.....',
        '....LL.LL.LL....',
        '....LLBBBBLL....',
        '...LLBBBBBBLL...',
        '...LLBBHBBBLL...',
        '...LLBBBBBBLL...',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '..LLBBBBBBBBLL..',
        '...LLBBBBBBLL...',
        '....LLBBBBLL....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'outer_leaf', role: 'accessory' },
        B: { name: 'inner_leaf', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#dad45e' },
      },
    },

    // ─── 16. FENNEL BULB ────────────────────────────────────────
    {
      id: 'fennel_bulb_16',
      description: 'White fennel bulb with feathery green fronds on top.',
      grid: [
        '..FF..FF..FF....',
        '..FFFFFFFFFF....',
        '...FFFFFFFF.....',
        '....FFFFFF......',
        '.....SSSS.......',
        '.....SSSS.......',
        '....BBBBBB......',
        '...BBBHBBBB.....',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....AAAA.......',
        '................',
      ],
      chars: {
        F: { name: 'fronds', role: 'accessory' },
        S: { name: 'stalk', role: 'arm' },
        B: { name: 'bulb', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_root', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 17. WATERCRESS ─────────────────────────────────────────
    {
      id: 'watercress_farm_16',
      description: 'Small dark green watercress sprigs with round leaves.',
      grid: [
        '.LL..LL..LL.LL..',
        'LLLL.LLLLLLLLLL.',
        'LLLL.LLLLLLLLLLL',
        '.LL..LLLL.LLLLL.',
        '..SS.SS.SS.LL...',
        '..SS.SS.SS.SS...',
        '...SSSSSSSSSS...',
        '...SSSSHSSSS....',
        '....SSSSSSSS....',
        '....SSSSSS......',
        '.....SSSSS......',
        '.....SSSS.......',
        '.....SSSS.......',
        '......SS........',
        '......AA........',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'body' },
        S: { name: 'stem', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'stem_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 18. RADICCHIO ──────────────────────────────────────────
    {
      id: 'radicchio_farm_16',
      description: 'Red-purple radicchio head with white veins and compact shape.',
      grid: [
        '................',
        '................',
        '......LLLL......',
        '.....LLLLLL.....',
        '....LLLLLLLL....',
        '...LLBBBBBBLL...',
        '...LBBVBBVBBL...',
        '..LLBBVHBVBBLL..',
        '..LLBBVBBVBBLL..',
        '..LLBBVBBVBBLL..',
        '...LLBBBBBBLL...',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'outer_leaf', role: 'accessory' },
        B: { name: 'inner_leaf', role: 'body' },
        V: { name: 'white_vein', role: 'arm' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d2aa99' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 19. KOHLRABI ───────────────────────────────────────────
    {
      id: 'kohlrabi_farm_16',
      description: 'Pale green kohlrabi bulb with protruding leaf stems.',
      grid: [
        '.LLL....LLL.....',
        '..LL....LL......',
        '...SS..SS.......',
        '....SSSS........',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBHBBBBB...',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '....RRRRRR......',
        '.....RRRR.......',
        '......RR........',
        '......AA........',
        '................',
      ],
      chars: {
        L: { name: 'leaf', role: 'accessory' },
        S: { name: 'leaf_stem', role: 'arm' },
        B: { name: 'bulb', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'root', role: 'head' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 20. ROMANESCO ──────────────────────────────────────────
    {
      id: 'romanesco_farm_16',
      description: 'Green romanesco with fractal spiral pattern and wrapper leaves.',
      grid: [
        '................',
        '......LLLL......',
        '.....L.TT.L.....',
        '....LLTTTTLL....',
        '...LLBTTTTBLL...',
        '...LBTBTBTBBL...',
        '..LLBBBTBBBBLL..',
        '..LLBBHBBTBBLL..',
        '..LLBBTBBBBBLL..',
        '...LBBBBBTBBL...',
        '...LLBBBBBBLL...',
        '....LLBBBBLL....',
        '.....LLLLLL.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'wrapper_leaf', role: 'accessory' },
        B: { name: 'floret', role: 'body' },
        T: { name: 'spiral_tip', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
      },
    },

  ],
};

export default batch;
