/**
 * Veggies batch 3 — 20 vine & garden vegetable templates for farming simulator bundles.
 * Covers: tomato, bell pepper, hot pepper, cucumber, zucchini, eggplant,
 *         corn cob, pumpkin, butternut squash, acorn squash, pea pod,
 *         green bean, okra, avocado half, mushroom, chili pepper,
 *         yellow squash, snap pea, string bean, patty pan squash.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'VEGGIES_BATCH3_TEMPLATES', schemes: 'VEGGIES_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TOMATO ────────────────────────────────────────────
    {
      id: 'tomato_farm_16',
      description: 'Wide oblate red tomato with green calyx and visible rib grooves.',
      grid: [
        '................',
        '.....LLLLLL.....',
        '....LL.SS.LL....',
        '.....LLLLLL.....',
        '....BBXBBXBB....',
        '...BBXBBHBBXBB..',
        '..BBBXBBBBXBBBB.',
        '..BBBXBBBBXBBBB.',
        '..BBBXBBBBXBBBB.',
        '...BBXBBBBXBBB..',
        '....BBXBBXBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'calyx', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'rib_groove', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d04648' },
      },
    },

    // ─── 2. BELL PEPPER ───────────────────────────────────────
    {
      id: 'bell_pepper_16',
      description: 'Green bell pepper with short stem, blocky shape with lobes.',
      grid: [
        '................',
        '.......SS.......',
        '......SSSS......',
        '......BBBB......',
        '.....B.BB.B.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '...BBBHBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 3. HOT PEPPER ────────────────────────────────────────
    {
      id: 'hot_pepper_farm_16',
      description: 'Curved red chili pepper with green stem cap.',
      grid: [
        '................',
        '................',
        '.....LLLL.......',
        '......SSSS......',
        '.......BBBB.....',
        '......BBBBBB....',
        '.....BBBHBBBB...',
        '....BBBBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBBB...',
        '......BBBBBBB...',
        '.......BBBBBB...',
        '........BBBBB...',
        '.........ABBB...',
        '..........AA....',
        '................',
      ],
      chars: {
        L: { name: 'leaf_cap', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#442434', highlight: '#d04648' },
      },
    },

    // ─── 4. CUCUMBER ──────────────────────────────────────────
    {
      id: 'cucumber_farm_16',
      description: 'Green cucumber with bumpy skin texture and lighter stripes.',
      grid: [
        '................',
        '................',
        '.......SSS......',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '.....BXBHBXB....',
        '....BBBBBBBBBB..',
        '....BXBBBBBXBB..',
        '....BBBBBBBBBB..',
        '....BXBBBBBXBB..',
        '....BBBBBBBBBB..',
        '.....BXBBBXBB...',
        '.....BBBBBBB....',
        '......AAAAA.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_end', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'bump', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'blossom_end', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
      },
    },

    // ─── 5. ZUCCHINI ──────────────────────────────────────────
    {
      id: 'zucchini_farm_16',
      description: 'Dark green zucchini with subtle lighter streaks.',
      grid: [
        '................',
        '................',
        '......SSS.......',
        '.....BBBBBB.....',
        '....BBBBBBBBB...',
        '....BBBHBBBBBB..',
        '....BXBBBBXBBB..',
        '...BBBBBBBBBBB..',
        '...BBBXBBBBXBB..',
        '...BBBBBBBBBBB..',
        '....BXBBBBXBBB..',
        '....BBBBBBBBBB..',
        '.....BBBBBBB....',
        '......AAAAA.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_end', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'streak', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'blossom_end', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#6daa2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 6. EGGPLANT ──────────────────────────────────────────
    {
      id: 'eggplant_farm_16',
      description: 'Tall elongated purple eggplant teardrop with green calyx.',
      grid: [
        '................',
        '.....LLLLLL.....',
        '......SSSS......',
        '.......BB.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBHBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        L: { name: 'calyx', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#597dce' },
        eye:       { shadow: '#597dce', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 7. CORN COB ──────────────────────────────────────────
    {
      id: 'corn_cob_16',
      description: 'Yellow corn on the cob with green husk leaves pulled back.',
      grid: [
        '....LLLL........',
        '...LLL.LL.......',
        '....LLLLLL......',
        '.....LBBBL......',
        '.....LBBBL......',
        '.....BXBXB......',
        '....BBXBXBB.....',
        '....BBHBXBB.....',
        '....BBXBXBB.....',
        '....BBXBXBB.....',
        '....BBXBXBB.....',
        '.....BXBXB......',
        '.....BBBBB......',
        '......AAA.......',
        '.......A........',
        '................',
      ],
      chars: {
        L: { name: 'husk_leaf', role: 'accessory' },
        B: { name: 'kernel', role: 'body' },
        X: { name: 'kernel_row', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'cob_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 8. PUMPKIN ───────────────────────────────────────────
    {
      id: 'pumpkin_farm_16',
      description: 'Round orange pumpkin with green stem and visible ribbing.',
      grid: [
        '................',
        '.......SS.......',
        '......SSSS......',
        '.....BBBBBB.....',
        '....BXBBBBXB....',
        '...BBXBBHBBXBB..',
        '...BBXBBBBBBXB..',
        '..BBBXBBBBBBXBB.',
        '..BBBXBBBBBBXBB.',
        '..BBBXBBBBBBXBB.',
        '...BBXBBBBBBXB..',
        '...BBXBBBBBBXB..',
        '....BXBBBBXB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'rib_groove', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 9. BUTTERNUT SQUASH ──────────────────────────────────
    {
      id: 'butternut_squash_16',
      description: 'Butternut squash with thin 2px neck and bulbous base.',
      grid: [
        '................',
        '.......SS.......',
        '.......BB.......',
        '.......BB.......',
        '.......BB.......',
        '......BHBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBXBBXBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'speckle', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. ACORN SQUASH ─────────────────────────────────────
    {
      id: 'acorn_squash_16',
      description: 'Dark green acorn squash with pronounced vertical ridges.',
      grid: [
        '................',
        '.......SS.......',
        '......SSSS......',
        '......BBBB......',
        '.....BXBBXB.....',
        '....BBXBBXBB....',
        '....BXBHBBXB....',
        '...BBXBBBBXBB...',
        '...BBXBBBBXBB...',
        '...BBXBBBBXBB...',
        '....BXBBBBXB....',
        '....BBXBBXBB....',
        '.....BXBBXB.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'ridge', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#6daa2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#346524' },
      },
    },

    // ─── 11. PEA POD ──────────────────────────────────────────
    {
      id: 'pea_pod_farm_16',
      description: 'Green pea pod split open showing round peas inside.',
      grid: [
        '................',
        '................',
        '................',
        '.......SS.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBPPPBB....',
        '...BBBPPPPBBB...',
        '...BBPPHPPBBB...',
        '...BBBPPPPBBB...',
        '....BBBPPPBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem', role: 'arm' },
        B: { name: 'pod_shell', role: 'body' },
        P: { name: 'peas', role: 'head' },
        H: { name: 'pea_shine', role: 'eye' },
        A: { name: 'pod_tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 12. GREEN BEAN ───────────────────────────────────────
    {
      id: 'green_bean_farm_16',
      description: 'Long green bean with slight curve and bumpy seed shapes.',
      grid: [
        '................',
        '................',
        '................',
        '.........SS.....',
        '........BBBB....',
        '.......BBBBB....',
        '......BXBHXB....',
        '.....BBBBBBB....',
        '....BBXBBBXBB...',
        '....BBBBBBBBB...',
        '...BBXBBBBBXB...',
        '...BBBBBBBBB....',
        '....BXBBBXB.....',
        '.....AAAA.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_end', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'seed_bump', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 13. OKRA ─────────────────────────────────────────────
    {
      id: 'okra_farm_16',
      description: 'Green okra pod with ridged surface and pointed tip.',
      grid: [
        '................',
        '.......SSS......',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '.....BXBHBXB....',
        '.....BBBBBBB....',
        '....BBXBBBXBB...',
        '....BBBBBBBBB...',
        '....BBXBBBXBB...',
        '....BBBBBBBBB...',
        '.....BXBBBXB....',
        '.....BBBBBBB....',
        '......BXBXB.....',
        '.......AAA......',
        '........A.......',
        '................',
      ],
      chars: {
        S: { name: 'stem_cap', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'ridge', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 14. AVOCADO HALF ─────────────────────────────────────
    {
      id: 'avocado_half_farm_16',
      description: 'Pear-shaped avocado half showing green flesh and large brown pit.',
      grid: [
        '................',
        '................',
        '.......FFFF.....',
        '......FFFFFF....',
        '.....FFBBBBFF...',
        '....FFBBBBBBFF..',
        '...FFBBBBBBBBFF.',
        '...FFBBPPPBBBFF.',
        '..FFBBBPHPPBBFF.',
        '..FFBBPPPPBBBFF.',
        '..FFBBBBBBBBFF..',
        '...FFBBBBBBFF...',
        '....FFFFFFFF....',
        '.....FFFFFF.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'dark_skin', role: 'arm' },
        B: { name: 'green_flesh', role: 'body' },
        P: { name: 'pit', role: 'head' },
        H: { name: 'pit_shine', role: 'eye' },
      },
      colors: {
        arm:       { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 15. MUSHROOM ─────────────────────────────────────────
    {
      id: 'mushroom_farm_16',
      description: 'Brown mushroom cap with white spots and thick white stem.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBXBBBB....',
        '...BBBHBBBXBB...',
        '...BBBBXBBBBB...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '....SSSSSSSS....',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '.....SSSSSS.....',
        '......SSSS......',
        '......AAAA......',
        '................',
      ],
      chars: {
        B: { name: 'cap', role: 'body' },
        X: { name: 'cap_spot', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        S: { name: 'stipe', role: 'arm' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 16. CHILI PEPPER ─────────────────────────────────────
    {
      id: 'chili_pepper_16',
      description: 'Small red-orange chili pepper with curved tip.',
      grid: [
        '................',
        '................',
        '.....LLLL.......',
        '......SSSS......',
        '.....BBBBBBB....',
        '....BBBBBBBB....',
        '....BBBHBBBBB...',
        '....BBBBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '......BBBBBB....',
        '.......BBBBB....',
        '........ABBB....',
        '.........AA.....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf_cap', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. YELLOW SQUASH ────────────────────────────────────
    {
      id: 'yellow_squash_16',
      description: 'Yellow crookneck squash with curved neck and bumpy base.',
      grid: [
        '................',
        '................',
        '....SSS.........',
        '...BBBB.........',
        '....BBBB........',
        '.....BBBB.......',
        '......BHBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBXBBBB....',
        '...BBBXBBXBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        S: { name: 'stem_nub', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'bump', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 18. SNAP PEA ─────────────────────────────────────────
    {
      id: 'snap_pea_farm_16',
      description: 'Plump green snap pea with visible pea bumps inside.',
      grid: [
        '................',
        '................',
        '................',
        '........SS......',
        '.......BBBB.....',
        '......BBBBBB....',
        '.....BBBHBBBB...',
        '....BBBPBPBBBB..',
        '....BBPBPBPBBB..',
        '....BBBPBPBBBB..',
        '.....BBBBBBB....',
        '......BBBBBB....',
        '.......AAAA.....',
        '........AA......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_curl', role: 'arm' },
        B: { name: 'pod_skin', role: 'body' },
        P: { name: 'pea_bump', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 19. STRING BEAN ──────────────────────────────────────
    {
      id: 'string_bean_16',
      description: 'Thin green string bean with gentle curve.',
      grid: [
        '................',
        '................',
        '.........SSS....',
        '........BBBBB...',
        '.......BBBBBBB..',
        '......BBBHBBBB..',
        '.....BBBBBBBBB..',
        '....BBBBBBBBB...',
        '...BBBBBBBBB....',
        '...BBBHBBBBB....',
        '..BBBBBBBBB.....',
        '..BBBBBBB.......',
        '...ABBBB........',
        '....AAA.........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'stem_end', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'tip', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#346524', base: '#346524', highlight: '#6daa2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 20. PATTY PAN SQUASH ─────────────────────────────────
    {
      id: 'patty_pan_squash_16',
      description: 'Scalloped-edge patty pan squash seen from above, pale yellow.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBHBBBBB...',
        '..BBBBBBBBBBB...',
        '.BBBBBBBBBBBBBB.',
        '.BBBXBBBBBXBBBB.',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBB...',
        '...BBBXBBXBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
      ],
      chars: {
        B: { name: 'skin', role: 'body' },
        X: { name: 'scallop_crease', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
