/**
 * Veggies batch 1 — 20 root vegetable & allium templates for farming simulator bundles.
 * Covers: carrot, potato, turnip, beet, radish, onion, garlic bulb,
 *         sweet potato, ginger root, parsnip, yam, rutabaga,
 *         daikon, jicama, shallot, leek, green onion,
 *         horseradish, celeriac, taro root.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'VEGGIES_BATCH1_TEMPLATES', schemes: 'VEGGIES_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. CARROT ────────────────────────────────────────────
    {
      id: 'carrot_farm_16',
      description: 'Orange carrot with green leafy top and tapered root.',
      grid: [
        '......LLLLLL....',
        '.....LL.LL.LL...',
        '......LLLLLL....',
        '.......SSSS.....',
        '......BBBBBB....',
        '......BBBBBB....',
        '.....BBBHBBBB...',
        '.....BBBBBBBB...',
        '.....BBBBBBBB...',
        '......BBBBBB....',
        '......BXBBBB....',
        '.......BBBB.....',
        '.......BXBB.....',
        '........BB......',
        '........AB......',
        '.........A......',
      ],
      chars: {
        L: { name: 'leaf_top', role: 'accessory' },
        S: { name: 'stem_crown', role: 'arm' },
        B: { name: 'root_body', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        X: { name: 'groove', role: 'head' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 2. POTATO ────────────────────────────────────────────
    {
      id: 'potato_farm_16',
      description: 'Brown rustic potato with darker eyes and dirt spots.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBXBBBBBB...',
        '...BBBBBHBBBBB..',
        '..BBBXBBBBBBBB..',
        '..BBBBBBBBXBBB..',
        '..BBBBBBBBBBB...',
        '..BBBBXBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBABB....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'skin', role: 'body' },
        X: { name: 'eye_spot', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'dirt_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 3. TURNIP ────────────────────────────────────────────
    {
      id: 'turnip_farm_16',
      description: 'White and purple turnip with bushy green leaves on top.',
      grid: [
        '.....LLLLLL.....',
        '....LL.LL.LL....',
        '.....LLLLLL.....',
        '......SSSS......',
        '.....PPPPPP.....',
        '....PPPPPPPP....',
        '....PPPPHPPP....',
        '...PPPPPPPPPP...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        P: { name: 'purple_top', role: 'head' },
        B: { name: 'white_body', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        head:      { shadow: '#442434', base: '#597dce', highlight: '#8595a1' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. BEET ──────────────────────────────────────────────
    {
      id: 'beet_farm_16',
      description: 'Wide squat dark red beet with concentric ring lines and leaves.',
      grid: [
        '....LLLLLLLL....',
        '...LL..LL..LL...',
        '....SSSSSSSS....',
        '.....SSSSSS.....',
        '....BBBBBBBB....',
        '...BBXBHBBXBB...',
        '..BBBXBBBBXBBB..',
        '..BBBBXBBXBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBXBBBBXBBB..',
        '...BBXBBBBXBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        B: { name: 'beet_flesh', role: 'body' },
        X: { name: 'ring_line', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tail', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d04648' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
        head:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        eye:       { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
      },
    },

    // ─── 5. RADISH ────────────────────────────────────────────
    {
      id: 'radish_farm_16',
      description: 'Small red and white radish with green leaves.',
      grid: [
        '................',
        '.....LLLLLL.....',
        '....LL.LL.LL....',
        '.....LLLLLL.....',
        '......SSSS......',
        '.....RRRRRR.....',
        '....RRRRHRRR....',
        '....RRRRRRRR....',
        '...RRRRRRRRRR...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        R: { name: 'red_top', role: 'head' },
        B: { name: 'white_bottom', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 6. ONION ─────────────────────────────────────────────
    {
      id: 'onion_farm_16',
      description: 'Golden-brown onion with papery skin layers and dried top.',
      grid: [
        '................',
        '.......SS.......',
        '.......SS.......',
        '......SSSS......',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '...BBXBBBBXBB...',
        '...BBBBBBBBBB...',
        '...BBXBBBBXBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '.......RR.......',
        '................',
      ],
      chars: {
        S: { name: 'dried_top', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'paper_line', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
        R: { name: 'roots', role: 'accessory' },
      },
      colors: {
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 7. GARLIC BULB ───────────────────────────────────────
    {
      id: 'garlic_bulb_16',
      description: 'White garlic bulb with visible clove segments and papery top.',
      grid: [
        '................',
        '.......SS.......',
        '.......SS.......',
        '......SSSS......',
        '......BBBB......',
        '.....BXBBXB.....',
        '....BBXBBXBB....',
        '....BBXHBXBB....',
        '...BBBXBBXBBB...',
        '...BBBXBBXBBB...',
        '...BBBXBBXBBB...',
        '....BBBBBBBB....',
        '.....AAAAAA.....',
        '......AAAA......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'papery_top', role: 'arm' },
        B: { name: 'clove_skin', role: 'body' },
        X: { name: 'clove_seam', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_plate', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. SWEET POTATO ──────────────────────────────────────
    {
      id: 'sweet_potato_16',
      description: 'Orange-brown sweet potato with tapered ends and warm flesh.',
      grid: [
        '................',
        '................',
        '................',
        '.......BBB......',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '....BBBHBBBBB...',
        '...BBBBBBBBBBB..',
        '...BBXBBBBXBBBB.',
        '...BBBBBBBBBBB..',
        '....BBBBBBBBB...',
        '.....BBBBBBB....',
        '......AABBB.....',
        '.......AAA......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'skin', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        X: { name: 'dimple', role: 'head' },
        A: { name: 'tip_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 9. GINGER ROOT ──────────────────────────────────────
    {
      id: 'ginger_root_16',
      description: 'Knobby beige ginger root with branching segments.',
      grid: [
        '................',
        '................',
        '....BBB.........',
        '...BBBBB........',
        '...BBHBB........',
        '...BBBBBBB......',
        '....BBBBBBB.....',
        '....XBBXBBBBB...',
        '.....BBBBBBBBB..',
        '......BBBBBHBB..',
        '.......BBBBBBB..',
        '........BBBBB...',
        '.........AAA....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'root_flesh', role: 'body' },
        X: { name: 'knob_joint', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'cut_end', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 10. PARSNIP ──────────────────────────────────────────
    {
      id: 'parsnip_farm_16',
      description: 'Pale cream parsnip with green leafy top, tapered root.',
      grid: [
        '......LLLLLL....',
        '.....LL.LL.LL...',
        '......LLLLLL....',
        '.......SSSS.....',
        '......BBBBBB....',
        '.....BBBBBBBB...',
        '.....BBBHBBBB...',
        '.....BBBBBBBB...',
        '......BBBBBB....',
        '......BXBBBB....',
        '.......BBBB.....',
        '.......BXBB.....',
        '........BB......',
        '........AB......',
        '.........A......',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem_crown', role: 'arm' },
        B: { name: 'root_body', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        X: { name: 'groove', role: 'head' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#d2aa99' },
      },
    },

    // ─── 11. YAM ──────────────────────────────────────────────
    {
      id: 'yam_farm_16',
      description: 'Brown and purple yam with rough textured skin.',
      grid: [
        '................',
        '................',
        '................',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '....BBBBBBBBB...',
        '...BBBXBHBBBB...',
        '...BBBBBBBBBBB..',
        '..BBBXBBBBBXBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBXBBBB..',
        '...BBBBBBBBB....',
        '....AAABBBB.....',
        '.....AAAA.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'skin', role: 'body' },
        X: { name: 'rough_patch', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'dark_end', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#597dce' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 12. RUTABAGA ─────────────────────────────────────────
    {
      id: 'rutabaga_farm_16',
      description: 'Yellow and purple rutabaga with leafy green top.',
      grid: [
        '.....LLLLLL.....',
        '....LL.LL.LL....',
        '.....LLLLLL.....',
        '......SSSS......',
        '.....PPPPPP.....',
        '....PPPPPPPP....',
        '....PPPHPPPP....',
        '...PPPPPPPPPP...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem', role: 'arm' },
        P: { name: 'purple_crown', role: 'head' },
        B: { name: 'yellow_body', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        head:      { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. DAIKON ───────────────────────────────────────────
    {
      id: 'daikon_farm_16',
      description: 'Long white daikon radish with green leafy crown.',
      grid: [
        '....LLLLLLLL....',
        '...LL..LL..LL...',
        '....LLLLLLLL....',
        '.....SSSSSS.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....BBBHBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......BBBB......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaves', role: 'accessory' },
        S: { name: 'stem_crown', role: 'arm' },
        B: { name: 'white_root', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 14. JICAMA ───────────────────────────────────────────
    {
      id: 'jicama_farm_16',
      description: 'Brown-skinned jicama with white interior showing at cut face.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBWWW.....',
        '....BBBWWWWW....',
        '....BBBWWHWW....',
        '...BBBBWWWWWW...',
        '...BBBWWWWWWW...',
        '...BBBWWWWWWW...',
        '...BBBBWWWWWW...',
        '....BBBWWWWW....',
        '.....BBBBWW.....',
        '......AAAA......',
        '.......AA.......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'brown_skin', role: 'body' },
        W: { name: 'white_flesh', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 15. SHALLOT ──────────────────────────────────────────
    {
      id: 'shallot_farm_16',
      description: 'Small copper-brown shallot with elongated shape and papery tip.',
      grid: [
        '................',
        '................',
        '.......SS.......',
        '.......SS.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBHBB.....',
        '....BBBBBBBB....',
        '....BBXBBXBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......AAAA......',
        '.......RR.......',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'papery_tip', role: 'arm' },
        B: { name: 'skin', role: 'body' },
        X: { name: 'paper_line', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
        R: { name: 'roots', role: 'accessory' },
      },
      colors: {
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 16. LEEK ─────────────────────────────────────────────
    {
      id: 'leek_farm_16',
      description: 'Long green and white leek stalk with fan-shaped leaf top.',
      grid: [
        '..LLLL...LLLL...',
        '...LLLL.LLLL....',
        '....LLLLLLLL....',
        '.....LLLLLL.....',
        '.....GGGGGG.....',
        '.....GGHGGG.....',
        '.....GGGGGG.....',
        '......GGGG......',
        '......BBBB......',
        '......BBBB......',
        '......BBBB......',
        '......BBHB......',
        '......BBBB......',
        '......BBBB......',
        '.......AA.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf_fan', role: 'accessory' },
        G: { name: 'green_stalk', role: 'head' },
        B: { name: 'white_stalk', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 17. GREEN ONION ──────────────────────────────────────
    {
      id: 'green_onion_16',
      description: 'Bundle of green scallions with white bulb bases.',
      grid: [
        '..LL..LL..LL....',
        '..LLLLLLLLLL....',
        '...GGGGGGGG.....',
        '...GGGGGGGG.....',
        '...GGHGGGGG.....',
        '....GGGGGG......',
        '....GGGGGG......',
        '....GGGGGG......',
        '....GGGGGG......',
        '.....BBBB.......',
        '.....BBBB.......',
        '.....BBBHB......',
        '.....BBBB.......',
        '......BB........',
        '......RR........',
        '................',
      ],
      chars: {
        L: { name: 'leaf_tips', role: 'accessory' },
        G: { name: 'green_stalk', role: 'head' },
        B: { name: 'white_bulb', role: 'body' },
        H: { name: 'shine', role: 'eye' },
        R: { name: 'roots', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 18. HORSERADISH ──────────────────────────────────────
    {
      id: 'horseradish_16',
      description: 'Thick beige horseradish root with rough bumpy skin.',
      grid: [
        '................',
        '.....LLL........',
        '....LLLLL.......',
        '.....SSS........',
        '....BBBBB.......',
        '...BBBBBBB......',
        '...BBBHBBBB.....',
        '...BBBBBBBB.....',
        '...BXBBBBXBB....',
        '....BBBBBBBBB...',
        '....BBBBBBBBB...',
        '.....BXBBBBB....',
        '......BBBBB.....',
        '.......AAA......',
        '........A.......',
        '................',
      ],
      chars: {
        L: { name: 'leaf_sprout', role: 'accessory' },
        S: { name: 'stem_top', role: 'arm' },
        B: { name: 'root_flesh', role: 'body' },
        X: { name: 'bump', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'root_tip', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#854c30', base: '#d2aa99', highlight: '#d2aa99' },
      },
    },

    // ─── 19. CELERIAC ─────────────────────────────────────────
    {
      id: 'celeriac_16',
      description: 'Knobby beige celery root with small leaf stalks on top.',
      grid: [
        '....LL..LL......',
        '....LLLLLL......',
        '.....SSSS.......',
        '....BBBBBB......',
        '...BXBBBBXB.....',
        '...BBBBHBBBB....',
        '..BXBBBBBBBXB...',
        '..BBBBBBBBBBBB..',
        '..BBBXBBBBXBBB..',
        '..BBBBBBBBBBBB..',
        '..BXBBBBBBBBXB..',
        '...BBBBBBBBBB...',
        '....AAAAAAAA....',
        '.....RRRRRR.....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'leaf_stalk', role: 'accessory' },
        S: { name: 'stem_base', role: 'arm' },
        B: { name: 'root_body', role: 'body' },
        X: { name: 'knob', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
        R: { name: 'roots', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#6daa2c' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#854c30' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 20. TARO ROOT ────────────────────────────────────────
    {
      id: 'taro_root_16',
      description: 'Brown hairy taro root with purple hint and rough texture.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBHBBBB....',
        '...BBXBBBBXBB...',
        '...BBBBBBBBBB...',
        '..BBBXBBBBXBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBXBBBB..',
        '...BBBBBBBBBB...',
        '....AAAAAAAA....',
        '.....RRRRRR.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'skin', role: 'body' },
        X: { name: 'hair_tuft', role: 'head' },
        H: { name: 'shine', role: 'eye' },
        A: { name: 'base_shadow', role: 'boot' },
        R: { name: 'root_fibers', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#30346d', base: '#442434', highlight: '#597dce' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#442434' },
      },
    },

  ],
};

export default batch;
