/**
 * Vehicle batch 4 — 17 new vehicles: fantasy mounts, sci-fi, utility.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'vehicles',
  exportNames: { templates: 'VEHICLE_BATCH4_TEMPLATES', schemes: 'VEHICLE_BATCH4_COLOR_SCHEMES' },
  templates: [

    {
      id: 'griffin_mount_16',
      description: 'Mythical griffin flying mount.',
      grid: [
        '................',
        '.....HHH........',
        '....HHHHH.......',
        '....HHEEH.......',
        '....HHHHH.......',
        '...BBBBBBB......',
        '..AABBBBBBBA....',
        '..AABBBBBBBA....',
        '..AABBBBBBB.....',
        '...BBBBBBB......',
        '...BBBB.BBB.....',
        '...GG.G.G.GG....',
        '...GG.G.G.GG....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'wings', role: 'accessory' },
        G: { name: 'claws', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'war_mech_16',
      description: 'Bipedal combat mech suit.',
      grid: [
        '................',
        '.....HHHHHH.....',
        '.....HEEEEH.....',
        '.....HHHHHH.....',
        '....BBBBBBBB....',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBB....',
        '....BBBBBBBB....',
        '....GGG.GGG.....',
        '....GGG.GGG.....',
        '...GGG...GGG....',
        '..GGGG...GGGG...',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cockpit', role: 'head' },
        E: { name: 'visor', role: 'eye' },
        B: { name: 'torso', role: 'body' },
        A: { name: 'arms', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'giant_turtle_mount_16',
      description: 'Rideable giant sea turtle.',
      grid: [
        '................',
        '................',
        '...HHH..........',
        '..HHEEH.........',
        '..HHHHH.........',
        '..BBBBBBBBB.....',
        '.BBEEEEEEEBB....',
        '.BBEEEEEEEBB....',
        '.BBBBBBBBBBB....',
        '..BBBBBBBBB.....',
        '..GG.....GG.....',
        '..GGG...GGG.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'shell_pattern', role: 'eye' },
        B: { name: 'shell', role: 'body' },
        G: { name: 'flippers', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        leg:   { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
      },
    },

    {
      id: 'hover_tank_16',
      description: 'Futuristic hovering battle tank.',
      grid: [
        '................',
        '................',
        '...AAAAAAA......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBEEEEEBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '...HHHHHHHH.....',
        '..HHHHHHHHHHH...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'cannon', role: 'accessory' },
        B: { name: 'hull', role: 'body' },
        E: { name: 'viewport', role: 'eye' },
        H: { name: 'hover_pad', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'paraglider_16',
      description: 'Hang glider / paraglider wing.',
      grid: [
        '................',
        '.HHHHHHHHHHHHHH.',
        '..HHHHHHHHHHH...',
        '...HHHHHHHHH....',
        '....EEEEEEE.....',
        '.....EEEEE......',
        '......BBB.......',
        '......BBB.......',
        '......BBB.......',
        '......GGG.......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'canopy', role: 'head' },
        E: { name: 'lines', role: 'eye' },
        B: { name: 'harness', role: 'body' },
        G: { name: 'pilot', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'cargo_ship_16',
      description: 'Large cargo container ship.',
      grid: [
        '................',
        '................',
        '................',
        '.......HH.......',
        '.......HH.......',
        '.......HH.......',
        '..AAABBBBBBBB...',
        '..AAABBBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'hull', role: 'body' },
        H: { name: 'mast', role: 'head' },
        A: { name: 'containers', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'magic_broom_16',
      description: 'Witch/wizard flying broomstick with sparkles.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..AA............',
        '..AABBBBBBBB....',
        '....BBBBBBBHHH..',
        '....BBBBBBBHHH..',
        '..AABBBBBBBB....',
        '..AA............',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'sparkles', role: 'accessory' },
        B: { name: 'handle', role: 'body' },
        H: { name: 'bristles', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'hover_scooter_16',
      description: 'Futuristic hover scooter / space vespa.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHH.......',
        '....HHBBHH......',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '...BBBBBBBBB....',
        '..EEEE...EEEE...',
        '..EEEE...EEEE...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'windshield', role: 'head' },
        B: { name: 'body', role: 'body' },
        E: { name: 'hover_pads', role: 'eye' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'war_galleon_16',
      description: 'Armored war galleon with cannons.',
      grid: [
        '................',
        '.......HH.......',
        '.......HH.......',
        '...AAAHHHAA.....',
        '...AAAHHHAA.....',
        '.....BBBBB......',
        '..AABBBBBBBAA...',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'mast', role: 'head' },
        A: { name: 'sails', role: 'accessory' },
        B: { name: 'hull', role: 'body' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'monster_truck_16',
      description: 'Huge monster truck with oversized wheels.',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '.....HHEEHH.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '.GGGGG...GGGGG..',
        '.GGGGG...GGGGG..',
        '.GGGGG...GGGGG..',
        '.GGGGG...GGGGG..',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'dragon_boat_16',
      description: 'Ornate dragon boat with dragon head prow.',
      grid: [
        '................',
        '................',
        '...HH...........',
        '..HHHH..........',
        '..HEEH..........',
        '...HHBBBBBBB....',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBA.',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dragon_head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'hull', role: 'body' },
        A: { name: 'tail', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'space_pod_16',
      description: 'Small single-person escape pod / shuttle pod.',
      grid: [
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHEEEEHH....',
        '....HHEEEEHH....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '...GGGG..GGGG...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'canopy', role: 'head' },
        E: { name: 'viewport', role: 'eye' },
        B: { name: 'hull', role: 'body' },
        G: { name: 'thrusters', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#30346d', base: '#6dc2ca', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        leg:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'ox_cart_16',
      description: 'Medieval ox-drawn wooden cart.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHH...........',
        '..HHHHH.........',
        '..HEEH.BBBBBBB..',
        '..HHHHBBBBBBBB..',
        '.......BBBBBBB..',
        '.......BGBBBGB..',
        '.......GGGBGGG..',
        '.......GGG.GGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'ox', role: 'head' },
        E: { name: 'ox_eyes', role: 'eye' },
        B: { name: 'cart', role: 'body' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'snowplow_16',
      description: 'Snow plow truck for clearing roads.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHH.......',
        '....HHEEHH......',
        '..AABBEEBBBBB...',
        '..AABBBBBBBBBB..',
        '..AABBBBBBBBBB..',
        '..AABGBBBBBBGB..',
        '....GGGBB.BGGG..',
        '....GGG....GGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'plow', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'magic_carpet_deluxe_16',
      description: 'Ornate flying carpet with tassels.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.BBBBBBBBBBBBBB.',
        '.BEEEEEEEEEEBB..',
        '.BEEHEHHEHEEBB..',
        '.BEEHEHHEHEEBB..',
        '.BEEEEEEEEEEBB..',
        '.BBBBBBBBBBBBBB.',
        '.HH.HH....HH.HH.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'border', role: 'body' },
        E: { name: 'pattern', role: 'eye' },
        H: { name: 'tassels', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'mechabird_mount_16',
      description: 'Steampunk mechanical bird mount.',
      grid: [
        '................',
        '.....HHHH.......',
        '....HHHHH.......',
        '....HHEEH.......',
        '....HHHHH.......',
        '...BBBBBBB......',
        '..AABBBBBBBA....',
        '..AABBBBBBBA....',
        '...BBBBBBB......',
        '...BBB.BBB......',
        '...GG...GG......',
        '...GG...GG......',
        '..GGG..GGG......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'wings', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'sand_worm_mount_16',
      description: 'Giant desert sand worm mount.',
      grid: [
        '................',
        '................',
        '..HHHH..........',
        '.HHHHHH.........',
        '.HEEHHH.........',
        '.HHHHHH.........',
        '..BBBBBB........',
        '...BBBBBBB......',
        '....BBBBBBB.....',
        '.....BBBBBBB....',
        '......BBBBBBB...',
        '.......BBBBB....',
        '........GGGGG...',
        '.........GGG....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        G: { name: 'tail', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:   { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
