/**
 * Vehicles batch 1 — 20 vehicle/mount templates.
 * Diverse: fantasy carts, sci-fi ships, mounts, modern vehicles.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'vehicles',
  exportNames: { templates: 'VEHICLE_BATCH1_TEMPLATES', schemes: 'VEHICLE_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. HORSE — classic RPG mount ─────────────────────────────
    {
      id: 'horse_mount_16',
      description: 'Saddled riding horse in profile, mane flowing.',
      grid: [
        '................',
        '....HHH.........',
        '...HHHH.........',
        '...HEHH.........',
        '...HFHH.........',
        '...XHBB.........',
        '..XXBBBB........',
        '..XBBBBB........',
        '..SBBBBBB.......',
        '...BBBBBB.......',
        '...BBBBBBT......',
        '...L..L.L.T.....',
        '..LL..L.LL.T....',
        '..TT..T.TT......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'muzzle', role: 'face' },
        X: { name: 'mane', role: 'hair' },
        B: { name: 'body', role: 'body' },
        S: { name: 'saddle', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'hooves_tail', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        face:      { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        hair:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. MINE CART — dungeon/platformer ────────────────────────
    {
      id: 'mine_cart_16',
      description: 'Wooden mine cart on rails with metal wheels.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '..HBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HHBBBBBBHH....',
        '..HHHHHHHHHH....',
        '...XHHHHHX......',
        '...WW....WW.....',
        '..WWWW..WWWW....',
        '..WWWW..WWWW....',
        'RRRRRRRRRRRRRRR.',
      ],
      chars: {
        B: { name: 'cargo', role: 'body' },
        H: { name: 'wood_frame', role: 'head' },
        X: { name: 'bolts', role: 'accessory' },
        W: { name: 'wheels', role: 'leg' },
        R: { name: 'rails', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 3. SPACESHIP — sci-fi fighter ────────────────────────────
    {
      id: 'spaceship_fighter_16',
      description: 'Small sci-fi fighter ship with angular wings, thruster glow.',
      grid: [
        '................',
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....HHEEHH.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '..WWBBBBBBBBWW..',
        '.WWWBBBBBBBBWWW.',
        'WWWWBBXXBBBBWWWW',
        '.WWWBBBBBBBBWWW.',
        '..WWBBBBBBBBWW..',
        '....AABBBBAA....',
        '.....AAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cockpit', role: 'head' },
        E: { name: 'windows', role: 'eye' },
        B: { name: 'hull', role: 'body' },
        W: { name: 'wings', role: 'arm' },
        X: { name: 'weapons', role: 'accessory' },
        A: { name: 'thrusters', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        boot:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 4. PIRATE SHIP — adventure/RPG ───────────────────────────
    {
      id: 'pirate_ship_16',
      description: 'Small pirate galleon with sails, skull flag, wooden hull.',
      grid: [
        '......X.........',
        '......X.........',
        '.....SXS........',
        '....SSSSS.......',
        '...SSSSSSS......',
        '...SSSSSSS......',
        '....SSSSS.......',
        '..HHHHHHHHHH....',
        '.HHHHHHHHHHH....',
        '.HBBBBBBBBBH....',
        '..HBBBBBBBBH....',
        '..HHBBBBBBHH....',
        '...HHHHHHHH.....',
        '....WWWWWW......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'mast_flag', role: 'accessory' },
        S: { name: 'sails', role: 'arm' },
        H: { name: 'hull', role: 'head' },
        B: { name: 'hull_body', role: 'body' },
        W: { name: 'waterline', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 5. DRAGON MOUNT — fantasy flying mount ───────────────────
    {
      id: 'dragon_mount_16',
      description: 'Rideable dragon with saddle, smaller than boss variant.',
      grid: [
        '...HHH..........',
        '..HHHH..........',
        '..HEHH..........',
        '..HHFH..........',
        'WWXHBB..........',
        '.WWBBBB.........',
        '..WBBBB.........',
        '..SBBBBBT.......',
        '...BBBBBB.T.....',
        '...BBBBB..T.....',
        '...L..L.........',
        '..LL..LL........',
        '..TT..TT........',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'snout', role: 'face' },
        X: { name: 'horn', role: 'hair' },
        B: { name: 'body', role: 'body' },
        W: { name: 'wing', role: 'arm' },
        S: { name: 'saddle', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'claws_tail', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hair:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#346524', highlight: '#6daa2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 6. HOVER BIKE — sci-fi vehicle ───────────────────────────
    {
      id: 'hover_bike_16',
      description: 'Futuristic hover bike with glowing repulsors.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '....HHEHHHH.....',
        '...BBBBBBBBB....',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...AABBBBBAA....',
        '....AA...AA.....',
        '....GG...GG.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'windshield', role: 'head' },
        E: { name: 'display', role: 'eye' },
        B: { name: 'chassis', role: 'body' },
        A: { name: 'fins', role: 'arm' },
        G: { name: 'repulsors', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
      },
    },

    // ─── 7. WOODEN RAFT — survival/adventure ──────────────────────
    {
      id: 'wooden_raft_16',
      description: 'Simple wooden log raft with small sail and crate.',
      grid: [
        '................',
        '................',
        '................',
        '......X.........',
        '......X.........',
        '.....SXS........',
        '....SSSSS.......',
        '....SSSSS.......',
        '.....SSS........',
        '...AAHHHHHH.....',
        '..HHHHHHHHHH....',
        '..HBBBBBBBBH....',
        '..HHBBBBBBHH....',
        '...HHHHHHHH.....',
        '....WWWWWW......',
        '................',
      ],
      chars: {
        X: { name: 'mast', role: 'accessory' },
        S: { name: 'sail', role: 'arm' },
        A: { name: 'crate', role: 'belt' },
        H: { name: 'logs', role: 'head' },
        B: { name: 'deck', role: 'body' },
        W: { name: 'water', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 8. TANK — modern/action ──────────────────────────────────
    {
      id: 'tank_16',
      description: 'Military tank with turret cannon and treads.',
      grid: [
        '................',
        '................',
        '................',
        '........XXXX....',
        '.....HHHXXXX....',
        '....HHHHHHH.....',
        '...HHHHHHHH.....',
        '..BBBBBBBBBB....',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '.BWWWWWWWWWWB...',
        '.WWWWWWWWWWWW...',
        '.WTWTWTWTWTWW...',
        '.WWWWWWWWWWWW...',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'cannon', role: 'arm' },
        H: { name: 'turret', role: 'head' },
        B: { name: 'hull', role: 'body' },
        W: { name: 'treads', role: 'leg' },
        T: { name: 'wheels', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#346524', base: '#4e4a4e', highlight: '#757161' },
        body:      { shadow: '#346524', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 9. BROOMSTICK — witch/wizard mount ──────────────────────
    {
      id: 'broomstick_16',
      description: 'Flying witch broomstick with bristles and a glow trail.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        'HHHHHHHHBBBBBB..',
        '........BBBBBB..',
        '.......XBBBBBBX.',
        '......XXBBBBBBXX',
        '.....XXXBBXXXXXX',
        '........XXXXXXXX',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'handle', role: 'body' },
        B: { name: 'shaft', role: 'head' },
        X: { name: 'bristles', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. AIRSHIP — steampunk ──────────────────────────────────
    {
      id: 'airship_16',
      description: 'Steampunk airship with balloon, gondola, propeller.',
      grid: [
        '....BBBBBB......',
        '..BBBBBBBBBB....',
        '.BBBBBBBBBBBB...',
        '.BBBBBBBBBBBB...',
        '..BBBBBBBBBB....',
        '...RRRRRRRR.....',
        '...RRRRRRRR.....',
        '....HHHHHH......',
        '...HHHHHHHHH....',
        '...HHEEHHHH.....',
        '...HHHHHHHHH....',
        '....HHHHHH......',
        '...XX....XX.....',
        '..XX......XX....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'balloon', role: 'body' },
        R: { name: 'rigging', role: 'belt' },
        H: { name: 'gondola', role: 'head' },
        E: { name: 'windows', role: 'eye' },
        X: { name: 'propellers', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 11. MECH WALKER — sci-fi bipedal ─────────────────────────
    {
      id: 'mech_walker_16',
      description: 'Small bipedal mech with cockpit and arm cannons.',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHHHHHH......',
        '...HHEEHHHH.....',
        '...HHHHHHHH.....',
        '..XBBBBBBBBX....',
        '.XX.BBBBBB.XX...',
        '.X..BBAAABB.X...',
        '....BBBBBBB.....',
        '.....BBBBB......',
        '....LL..LL......',
        '...LL....LL.....',
        '..LL......LL....',
        '.TTT......TTT...',
        'TTTT......TTTT..',
        '................',
      ],
      chars: {
        H: { name: 'cockpit', role: 'head' },
        E: { name: 'viewport', role: 'eye' },
        B: { name: 'chassis', role: 'body' },
        A: { name: 'core', role: 'accessory' },
        X: { name: 'cannons', role: 'arm' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'feet', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 12. CANOE — adventure/survival ───────────────────────────
    {
      id: 'canoe_16',
      description: 'Simple canoe with paddle, seen from above/side.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '....X...........',
        '...XH...........',
        '..XHHHHHHHHH....',
        '.XHHHBBBBHHHHH..',
        '..HHHBBBBHHHH...',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '.....HHHH.......',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'paddle', role: 'accessory' },
        H: { name: 'hull', role: 'head' },
        B: { name: 'seat_area', role: 'body' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 13. MAGIC CARPET — Arabian fantasy ──────────────────────
    {
      id: 'magic_carpet_16',
      description: 'Flying magic carpet with tassels and ornate patterns.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '.XBBBBBBBBBBX...',
        'XHBBBBBBBBBBHX..',
        '.XBBXBBBBXBBX...',
        'XHBBBBBBBBBBHX..',
        '.XBBBBBBBBBBX...',
        '..TTTTTTTTTT....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'fabric', role: 'body' },
        H: { name: 'border', role: 'head' },
        X: { name: 'pattern', role: 'accessory' },
        T: { name: 'tassels', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 14. SLED — winter/holiday ────────────────────────────────
    {
      id: 'sled_16',
      description: 'Wooden sled with curved runners and cargo space.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '.HBBBBBBBBBBH...',
        '.HBBBBBBBBBBH...',
        '.HHBBBBBBBBHH...',
        '..HHHHHHHHHH....',
        '.RRHHHHHHHHRR...',
        'RR..........RR..',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cargo_bed', role: 'body' },
        H: { name: 'frame', role: 'head' },
        R: { name: 'runners', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 15. ROCKET — sci-fi/platformer ──────────────────────────
    {
      id: 'rocket_16',
      description: 'Small rocket ship with nose cone, porthole, fins.',
      grid: [
        '......HH........',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HHHHHH......',
        '....BBBBBB......',
        '....BBEEBB......',
        '....BBBBBB......',
        '....BBBBBB......',
        '...XBBBBBBX.....',
        '..XXBBBBBBXX....',
        '.XX.BBBBBB.XX...',
        '....BBBBBB......',
        '....AAAAAA......',
        '...AAAAAAAA.....',
        '....GGGGGG......',
        '................',
      ],
      chars: {
        H: { name: 'nose_cone', role: 'head' },
        B: { name: 'fuselage', role: 'body' },
        E: { name: 'porthole', role: 'eye' },
        X: { name: 'fins', role: 'arm' },
        A: { name: 'engine', role: 'leg' },
        G: { name: 'flame', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. BICYCLE — sim/adventure ──────────────────────────────
    {
      id: 'bicycle_16',
      description: 'Simple bicycle with two wheels, frame, handlebars.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '........H.......',
        '.......HH.......',
        '......HBH.......',
        '.....HBBH.......',
        '....HBBBH.......',
        '...HHHSHHHH.....',
        '..WW.....WW.....',
        '.WWWW...WWWW....',
        '.WXXW...WXXW....',
        '.WWWW...WWWW....',
        '..WW.....WW.....',
        '................',
      ],
      chars: {
        H: { name: 'frame', role: 'body' },
        B: { name: 'crossbar', role: 'head' },
        S: { name: 'seat', role: 'accessory' },
        W: { name: 'wheels', role: 'leg' },
        X: { name: 'spokes', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 17. WAR CHARIOT — ancient/fantasy ────────────────────────
    {
      id: 'war_chariot_16',
      description: 'Ancient war chariot with bladed wheels and shield front.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..HHHHH.........',
        '.HHHHHH.........',
        '.HEEHHH.........',
        '.HHHHHHBBBBBB...',
        '.HHHHHHBBBBBB...',
        '..HHHHBBBBBBB...',
        '...XHBBBBBB.....',
        '..XWWWX..XWWWX..',
        '.XWWWWX..XWWWWX.',
        '..XWWWX..XWWWX..',
        '................',
      ],
      chars: {
        H: { name: 'shield_front', role: 'head' },
        E: { name: 'emblem', role: 'eye' },
        B: { name: 'platform', role: 'body' },
        W: { name: 'wheels', role: 'leg' },
        X: { name: 'blades', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 18. SUBMARINE — underwater/adventure ─────────────────────
    {
      id: 'submarine_16',
      description: 'Small submarine with periscope, porthole, propeller.',
      grid: [
        '........X.......',
        '........X.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHH.....',
        '...HBBBBBBBH....',
        '..HBBBBEBBBBH...',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBH...',
        '...HBBBBBBBH....',
        '....HHHHHHHH....',
        '.....HHHHHHPP...',
        '......HHHHPP....',
        '................',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'periscope', role: 'accessory' },
        H: { name: 'hull', role: 'head' },
        B: { name: 'body', role: 'body' },
        E: { name: 'porthole', role: 'eye' },
        P: { name: 'propeller', role: 'arm' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        arm:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 19. WOLF MOUNT — fantasy mount ──────────────────────────
    {
      id: 'wolf_mount_16',
      description: 'Large saddled dire wolf mount, side profile.',
      grid: [
        '................',
        '...XHHH.........',
        '..XXHHHH........',
        '...HHEHH........',
        '...HHFHH........',
        '....HBBB........',
        '...SBBBB........',
        '..SSBBBB........',
        '...BBBBBBT......',
        '...BBBBBB.T.....',
        '...L..L....T....',
        '..LL..LL........',
        '..LL..LL........',
        '..TT..TT........',
        '................',
        '................',
      ],
      chars: {
        X: { name: 'ears', role: 'hair' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eye', role: 'eye' },
        F: { name: 'snout', role: 'face' },
        B: { name: 'body', role: 'body' },
        S: { name: 'saddle', role: 'accessory' },
        L: { name: 'legs', role: 'leg' },
        T: { name: 'paws_tail', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        face:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 20. FLYING SAUCER — sci-fi/retro ────────────────────────
    {
      id: 'flying_saucer_16',
      description: 'Classic flying saucer UFO with dome and lights.',
      grid: [
        '................',
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHEEHHHH....',
        '....HHHHHHH.....',
        '..BBBBBBBBBBBB..',
        '.BBBBBBBBBBBBBB.',
        'BXBBXBBBBXBBXBBB',
        '.BBBBBBBBBBBBBB.',
        '..BBBBBBBBBBBB..',
        '....AAAAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'dome', role: 'head' },
        E: { name: 'windows', role: 'eye' },
        B: { name: 'disc', role: 'body' },
        X: { name: 'lights', role: 'accessory' },
        A: { name: 'beam', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        accessory: { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
