/**
 * Vehicle batch 3 — 17 new vehicles: land, sea, air, fantasy.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'vehicles',
  exportNames: { templates: 'VEHICLE_BATCH3_TEMPLATES', schemes: 'VEHICLE_BATCH3_COLOR_SCHEMES' },
  templates: [

    {
      id: 'hot_air_balloon_16',
      description: 'Colorful hot air balloon with basket.',
      grid: [
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHEEHHEEHHHH..',
        '..HHEEHHEEHHHH..',
        '..HHEEHHEEHHHH..',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '.....EEEEEE.....',
        '......EEEE......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'envelope', role: 'head' },
        E: { name: 'ropes', role: 'eye' },
        B: { name: 'basket', role: 'body' },
      },
      colors: {
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'rowboat_16',
      description: 'Simple wooden rowboat with oars.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..HH......HH....',
        '..HH......HH....',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBB...',
        '..BEEEEEEEBB....',
        '...BEEEEEEB.....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'hull', role: 'body' },
        E: { name: 'interior', role: 'eye' },
        H: { name: 'oars', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'pickup_truck_16',
      description: 'Rugged pickup truck with open bed.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHH.......',
        '....HHEEHHBBB...',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'fire_truck_16',
      description: 'Emergency fire truck with ladder.',
      grid: [
        '................',
        '................',
        '..AAAAAAAAAA....',
        '..AAAAAAAAAA....',
        '.....HHHH.......',
        '....HHEEHHBBB...',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'ladder', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'ambulance_16',
      description: 'Emergency ambulance vehicle.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHH.......',
        '....HHEEHHBBB...',
        '..BBBBEEBBBBB...',
        '..BBBBBABBBBBB..',
        '..BBBBBABBBBBB..',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'cross', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'police_car_16',
      description: 'Black and white police cruiser.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....AAHH.......',
        '....HHEEHH......',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'lights', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#4e4a4e', highlight: '#8b8e8a' },
        head:      { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'tractor_16',
      description: 'Farm tractor with big rear wheels.',
      grid: [
        '................',
        '................',
        '................',
        '......HHHH......',
        '.....HHBBHH.....',
        '.....HEEBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBB.....',
        '...GGGBBBBGG....',
        '..GGGGGBBGGGG...',
        '..GGGGG..GGGG...',
        '..GGGGG..GGGG...',
        '...GGG....GG....',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:  { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'school_bus_16',
      description: 'Classic yellow school bus.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHEEHHEEHHHH..',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '..BBBBBBBBBBBBB.',
        '..BGBBBB..BBGB..',
        '..GGGBB...BGGG..',
        '..GGG......GGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'roof', role: 'head' },
        E: { name: 'windows', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'race_car_16',
      description: 'Low-profile racing car with spoiler.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '......HHHH......',
        '.....HHEEHH.....',
        '..BBBBBEEBBBAB..',
        '..BBBBBBBBBBAB..',
        '..BGBBBBBBBBGB..',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'spoiler', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'helicopter_16',
      description: 'Military/civilian helicopter with rotor.',
      grid: [
        '..HHHHHHHHHHHH..',
        '.......HH.......',
        '......BBBB......',
        '.....BBEEBB.....',
        '....BBBEEBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBBA...',
        '.....BBBBBAA....',
        '......BBBA......',
        '.......GG.......',
        '....GGGGGGGG....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'rotor', role: 'head' },
        B: { name: 'fuselage', role: 'body' },
        E: { name: 'cockpit', role: 'eye' },
        A: { name: 'tail', role: 'accessory' },
        G: { name: 'skids', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'biplane_16',
      description: 'Classic WWI-era biplane with double wings.',
      grid: [
        '................',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '......BBBB......',
        '......BBBB......',
        '...EEEBBBBAA....',
        '......BBBB......',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHHH...',
        '.......GG.......',
        '......GGGG......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wings', role: 'head' },
        B: { name: 'fuselage', role: 'body' },
        E: { name: 'propeller', role: 'eye' },
        A: { name: 'tail', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'sailboat_16',
      description: 'Small sailboat with triangular sail.',
      grid: [
        '.......H........',
        '......HHH.......',
        '.....HHHH.......',
        '....HHHHH.......',
        '...HHHHHH.......',
        '..HHHHHHH.......',
        '...EEEEE........',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '.....BBBBB......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'sail', role: 'head' },
        E: { name: 'mast', role: 'eye' },
        B: { name: 'hull', role: 'body' },
      },
      colors: {
        head:  { shadow: '#8b8e8a', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'unicycle_16',
      description: 'Circus unicycle with single wheel.',
      grid: [
        '................',
        '................',
        '......HH........',
        '.....HHHH.......',
        '......HH........',
        '......BB........',
        '......BB........',
        '......BB........',
        '......BB........',
        '.....GGGG.......',
        '....GGGGGG......',
        '...GG....GG.....',
        '...GG....GG.....',
        '....GGGGGG......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'seat', role: 'head' },
        B: { name: 'frame', role: 'body' },
        G: { name: 'wheel', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        body:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'ice_cream_truck_16',
      description: 'Colorful ice cream truck with serving window.',
      grid: [
        '................',
        '................',
        '................',
        '.....AAAA.......',
        '.....HHHH.......',
        '....HHEEHHHHHH..',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'cone_sign', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'steam_locomotive_16',
      description: 'Steam-powered locomotive engine.',
      grid: [
        '................',
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '..AAABBBBBB.....',
        '..AAABBBBBB.....',
        '..EEEBBBBBB.....',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..GGGGGGGGGGG...',
        '..GGGGGGGGGGG...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'boiler', role: 'body' },
        H: { name: 'chimney', role: 'head' },
        E: { name: 'cabin', role: 'eye' },
        A: { name: 'cowcatcher', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#8b8e8a' },
        head:      { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'jet_fighter_16',
      description: 'Military jet fighter aircraft.',
      grid: [
        '......HH........',
        '......HH........',
        '.....BBBB.......',
        '.....BBBB.......',
        '..EEEBBBBE......',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBBBBBBA....',
        '...BBBBBBBBA....',
        '....BBBBBB......',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'nose', role: 'head' },
        B: { name: 'fuselage', role: 'body' },
        E: { name: 'wings', role: 'eye' },
        A: { name: 'tail_fins', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:      { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        eye:       { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    {
      id: 'dump_truck_16',
      description: 'Construction dump truck with raised bed.',
      grid: [
        '................',
        '................',
        '....AAAAAAA.....',
        '....AAAAAAA.....',
        '....AAHHHAA.....',
        '....HHEEHH......',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        H: { name: 'cabin', role: 'head' },
        E: { name: 'window', role: 'eye' },
        A: { name: 'dump_bed', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

  ],
};

export default batch;
