/**
 * Vehicle batch 5 — 17 new vehicles to reach 100 total.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'vehicles',
  exportNames: { templates: 'VEHICLE_BATCH5_TEMPLATES', schemes: 'VEHICLE_BATCH5_COLOR_SCHEMES' },
  templates: [

    {
      id: 'delivery_van_16',
      description: 'Box delivery van / courier vehicle.',
      grid: [
        '................',
        '................',
        '................',
        '.....HHHHHHHH...',
        '....HHEEHHHHH...',
        '..BBBBEEBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '..BGBBBBBBBGB...',
        '..GGGBB..BGGG...',
        '..GGG.....GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'roof', role: 'head' },
        E: { name: 'window', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        head:  { shadow: '#442434', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'sand_crawler_16',
      description: 'Desert sand crawler / dune buggy.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....HHHH.......',
        '....HHBBHH......',
        '..BBBBBBBBBB....',
        '..BBEEEEEEBB....',
        '..BBBBBBBBBB....',
        '.GGGGBB..BGGGG..',
        '.GGGGBB..BGGGG..',
        '.GGGG.....GGGG..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'chassis', role: 'body' },
        H: { name: 'rollcage', role: 'head' },
        E: { name: 'cargo', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'canoe_war_16',
      description: 'War canoe with shields and paddles.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '..HH..HH..HH....',
        '.BBBBBBBBBBBBB..',
        '.BBEEEEEEEEBBB..',
        '.BBBBBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'hull', role: 'body' },
        E: { name: 'interior', role: 'eye' },
        H: { name: 'shields', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'spider_mount_16',
      description: 'Giant rideable spider mount.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '....HHHEEH......',
        '....HHHHHH......',
        '.GG.BBBBBB.GG...',
        '..GGBBBBBBGG....',
        '..GGBBBBBBGG....',
        '.GG.BBBBBB.GG...',
        'GG..BBBBBB..GG..',
        '....GG..GG......',
        '...GG....GG.....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        eye:   { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        body:  { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'treant_mount_16',
      description: 'Living tree creature mount / ent.',
      grid: [
        '....AAAAAAA.....',
        '...AAAAAAAAA....',
        '...AAAAAAAAA....',
        '....HHHHHH......',
        '....HEEHEH......',
        '....HHHHHH......',
        '...BBBBBBBB.....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '...GG....GG.....',
        '..GGG...GGG.....',
        '..GGGG.GGGG.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'canopy', role: 'accessory' },
        H: { name: 'face', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'trunk', role: 'body' },
        G: { name: 'roots', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#346524', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    {
      id: 'propeller_plane_16',
      description: 'Single-engine propeller airplane.',
      grid: [
        '......HH........',
        '......HH........',
        '......BB........',
        '.....BBBB.......',
        '..EEEBBBBEEE....',
        '..EEEBBBBEEE....',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '...AAA.AAA......',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'propeller', role: 'head' },
        B: { name: 'fuselage', role: 'body' },
        E: { name: 'wings', role: 'eye' },
        A: { name: 'tail', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    {
      id: 'go_kart_16',
      description: 'Small racing go-kart.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '......HHH.......',
        '.....HHEEH......',
        '..GBBBBBBBBBG...',
        '..GBBBBBBBBGGG..',
        '..GGBB....GGG...',
        '..GG.......GG...',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        H: { name: 'seat', role: 'head' },
        E: { name: 'helmet', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:   { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'cloud_mount_16',
      description: 'Rideable magical cloud.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '......AAAA......',
        '.....AAAAAA.....',
        '....HHHHHHHH....',
        '..HHHHHHHHHHHH..',
        '.HHHHHHHHHHHHHH.',
        '.HHHHHHHHHHHHHH.',
        '..HHHHHHHHHHHH..',
        '....HHHHHHHH....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cloud', role: 'head' },
        A: { name: 'sparkles', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    {
      id: 'tank_heavy_16',
      description: 'Heavy armored battle tank.',
      grid: [
        '................',
        '................',
        '..AAAAAAAAAA....',
        '....BBBBBBBB....',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBEEEEEEEEBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'cannon', role: 'accessory' },
        B: { name: 'turret', role: 'body' },
        E: { name: 'viewport', role: 'eye' },
        G: { name: 'treads', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#8bef88' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:       { shadow: '#442434', base: '#4e4a4e', highlight: '#595652' },
      },
    },

    {
      id: 'battle_chariot_16',
      description: 'Ancient battle chariot with scythe wheels.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHH...........',
        '..HHHH.BBBBB....',
        '..HEEH.BBBBB....',
        '..HHHHBBBBBBBB..',
        '.......BBBBBBB..',
        '..AA..BGBBBGB...',
        '..AA..GGGBGGG...',
        '......GGG.GGG...',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'horses', role: 'head' },
        E: { name: 'horse_eye', role: 'eye' },
        B: { name: 'chariot', role: 'body' },
        A: { name: 'weapon', role: 'accessory' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        accessory: { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'airboat_16',
      description: 'Swamp airboat with large fan.',
      grid: [
        '................',
        '................',
        '................',
        '...........HH...',
        '..........HHHH..',
        '..........HHHH..',
        '...........HH...',
        '.BBBBBBBBBBBBB..',
        '.BBEEEEEEEEBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'hull', role: 'body' },
        E: { name: 'deck', role: 'eye' },
        H: { name: 'fan', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#595652', highlight: '#8b8e8a' },
        eye:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:  { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

    {
      id: 'magic_surfboard_16',
      description: 'Enchanted flying surfboard with runes.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
        '..HBBBBBBBBBBH..',
        '..BBBEEEEEEEBB..',
        '..BBBEEEEEEEBB..',
        '..HBBBBBBBBBBH..',
        '................',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'board', role: 'body' },
        E: { name: 'runes', role: 'eye' },
        H: { name: 'glow', role: 'head' },
      },
      colors: {
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:   { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'siege_tower_16',
      description: 'Medieval siege tower on wheels.',
      grid: [
        '..HHHHHHHHHH....',
        '..HHHHHHHHHH....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BBEEBBEEBB....',
        '..BBBBBBBBBB....',
        '..BGBBBBBBGB....',
        '..GGGBBBBGGG....',
        '..GGG....GGG....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'battlement', role: 'head' },
        B: { name: 'structure', role: 'body' },
        E: { name: 'windows', role: 'eye' },
        G: { name: 'wheels', role: 'leg' },
      },
      colors: {
        head:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        eye:   { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        leg:   { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    {
      id: 'camel_mount_16',
      description: 'Desert camel mount with saddle.',
      grid: [
        '................',
        '......HHH.......',
        '.....HHHH.......',
        '.....HEEH.......',
        '.....HHHH.......',
        '....BABBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BBBBBBB......',
        '...BB...BB......',
        '...GG...GG......',
        '...GG...GG......',
        '..GGG..GGG......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body', role: 'body' },
        A: { name: 'hump', role: 'accessory' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    {
      id: 'ghost_ship_16',
      description: 'Haunted ghost pirate ship.',
      grid: [
        '.......HH.......',
        '.......HH.......',
        '...AAAHHHAA.....',
        '...AAAHHHAA.....',
        '.....BBBBB......',
        '..BBBBBBBBBBB...',
        '.BBBBBBBBBBBBB..',
        '.BBBBBBBBBBBBB..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '................',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'mast', role: 'head' },
        A: { name: 'sails', role: 'accessory' },
        B: { name: 'hull', role: 'body' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#30346d', base: '#595652', highlight: '#8b8e8a' },
        body:      { shadow: '#30346d', base: '#442434', highlight: '#595652' },
      },
    },

    {
      id: 'sky_whale_mount_16',
      description: 'Giant flying sky whale mount.',
      grid: [
        '................',
        '................',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '..BBEBBBBBBBB...',
        '..BBBBBBBBBBB...',
        '.AABBBBBBBBBBA..',
        '.AABBBBBBBBBBA..',
        '..BBBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBHH...',
        '............HH..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'body', role: 'body' },
        E: { name: 'eye', role: 'eye' },
        A: { name: 'fins', role: 'accessory' },
        H: { name: 'tail', role: 'head' },
      },
      colors: {
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#30346d', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    {
      id: 'war_elephant_armored_16',
      description: 'Armored war elephant with tower.',
      grid: [
        '....AAAA........',
        '....AAAA........',
        '...HHHHHH.......',
        '..HHEEHHHH......',
        '..HHHHHHHH......',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BBBBBBBBB.....',
        '..BB..B..BB.....',
        '..GG..G..GG.....',
        '..GG.....GG.....',
        '..GG.....GG.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        A: { name: 'tower', role: 'accessory' },
        H: { name: 'head', role: 'head' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'body_armor', role: 'body' },
        G: { name: 'legs', role: 'leg' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
        head:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        eye:       { shadow: '#30346d', base: '#4e4a4e', highlight: '#595652' },
        body:      { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
        leg:       { shadow: '#595652', base: '#8b8e8a', highlight: '#d2aa99' },
      },
    },

  ],
};

export default batch;
