/**
 * Yatai batch 4 — 20 equipment & stall item templates.
 * Category: food (Japanese street food equipment).
 * Wood browns for carts/boards, steel grays for metal, red/white for lanterns,
 * bamboo tones for steamers, ceramic for bowls/teapots.
 * All 16x16, DB16 palette only.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'YATAI_BATCH4_TEMPLATES', schemes: 'YATAI_BATCH4_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TAKEOUT BAG ────────────────────────────────────────────
    // Paper takeout bag with twisted handles, stamp logo, and folded top
    {
      id: 'takeout_bag_yt_16',
      description: 'Paper takeout bag with twisted handles, red stamp logo, and folded top crease.',
      grid: [
        '................',
        '..HH........HH..',
        '..HBBBBBBBBBBH..',
        '..HBBBBBBBBBBH..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBSSBBBBBB..',
        '..BBBBSSBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..DDDDDDDDDDDD..',
        '..DDDDDDDDDDDD..',
        '...TTTTTTTTTT...',
        '................',
      ],
      chars: {
        H: { name: 'twisted_handle', role: 'arm' },
        B: { name: 'bag_body', role: 'body' },
        S: { name: 'stamp_logo', role: 'head' },
        D: { name: 'bag_bottom_fold', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 2. YATAI COUNTER ─────────────────────────────────────────
    {
      id: 'yatai_counter_yt_16',
      description: 'Counter serving surface section with wood grain and edge trim.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBEEBBEEBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBEEBBBBEEBBH.',
        '.HBBBBBBBBBBBBH.',
        '.AAAAAAAAAAAAAA.',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'edge_trim', role: 'head' },
        B: { name: 'wood_surface', role: 'body' },
        E: { name: 'wood_grain', role: 'eye' },
        A: { name: 'front_apron', role: 'arm' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. NOREN CURTAIN ─────────────────────────────────────────
    {
      id: 'noren_curtain_yt_16',
      description: 'Traditional fabric half-curtain divider with kanji-like pattern.',
      grid: [
        '.HHHHHHHHHHHHHH.',
        '.HHHHHHHHHHHHHH.',
        '.BBBB.BBBB.BBBBB',
        '.BBBB.BBBB.BBBBB',
        '.BBBB.BBBB.BBBBB',
        '.BBEB.BEEB.BBBBB',
        '.BBEB.BEEB.BBBEB',
        '.BBBB.BBBB.BBBBB',
        '.BBBB.BBBB.BBBBB',
        '.BBEB.BBBB.BBBEB',
        '.BBBB.BEEB.BBBBB',
        '.BBBB.BBBB.BBBBB',
        '.AAAA.AAAA.AAAAA',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'curtain_rod', role: 'head' },
        B: { name: 'fabric_body', role: 'body' },
        E: { name: 'kanji_pattern', role: 'eye' },
        A: { name: 'fabric_hem', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 4. RED CHOCHIN ───────────────────────────────────────────
    {
      id: 'chochin_red_yt_16',
      description: 'Red paper lantern (chochin) with warm glow and tassel.',
      grid: [
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....AAAAAA.....',
        '....AABBBBAA....',
        '...AABBBBBBAA...',
        '...ABBBBBBBBBA..',
        '...ABBBEEBBBBA..',
        '...ABBBEEBBBBA..',
        '...ABBBBBBBBBA..',
        '...AABBBBBBAA...',
        '....AABBBBAA....',
        '.....AAAAAA.....',
        '......GGGG......',
        '.......GG.......',
        '................',
      ],
      chars: {
        H: { name: 'top_ring', role: 'head' },
        A: { name: 'paper_ribs', role: 'arm' },
        B: { name: 'paper_body', role: 'body' },
        E: { name: 'inner_glow', role: 'eye' },
        G: { name: 'tassel', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 5. WHITE CHOCHIN ─────────────────────────────────────────
    {
      id: 'chochin_white_yt_16',
      description: 'White paper lantern with soft inner glow.',
      grid: [
        '................',
        '.......HH.......',
        '......HHHH......',
        '.....AAAAAA.....',
        '....AABBBBAA....',
        '...AABBBBBBAA...',
        '...ABBBBBBBBBA..',
        '...ABBBEEBBBBA..',
        '...ABBBEEBBBBA..',
        '...ABBBBBBBBBA..',
        '...AABBBBBBAA...',
        '....AABBBBAA....',
        '.....AAAAAA.....',
        '......GGGG......',
        '.......GG.......',
        '................',
      ],
      chars: {
        H: { name: 'top_ring', role: 'head' },
        A: { name: 'paper_ribs', role: 'arm' },
        B: { name: 'paper_body', role: 'body' },
        E: { name: 'inner_glow', role: 'eye' },
        G: { name: 'tassel', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. TAKOYAKI GRILL ────────────────────────────────────────
    {
      id: 'takoyaki_grill_yt_16',
      description: 'Takoyaki griddle plate with round holes for octopus balls.',
      grid: [
        '................',
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HBBBBBBBBBBBBH.',
        '.HBB.BB.BB.BBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBB.BB.BB.BBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBB.BB.BB.BBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HHHHHHHHHHHHHH.',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'grill_frame', role: 'head' },
        B: { name: 'cast_iron', role: 'body' },
        G: { name: 'grill_base', role: 'leg' },
      },
      colors: {
        head: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 7. YAKITORI GRILL ────────────────────────────────────────
    {
      id: 'yakitori_grill_yt_16',
      description: 'Charcoal yakitori grill with wire grate and glowing coals.',
      grid: [
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '..HB.B.B.B.BBH..',
        '..HBBBBBBBBBBH..',
        '..HB.B.B.B.BBH..',
        '..HHHHHHHHHHHH..',
        '..BBBBBBBBBBBB..',
        '..BBEEBBEEBBBB..',
        '..BEEBBEEBBEEB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GG........GG..',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'grill_frame', role: 'head' },
        B: { name: 'grill_body', role: 'body' },
        E: { name: 'hot_coals', role: 'eye' },
        G: { name: 'grill_legs', role: 'leg' },
      },
      colors: {
        head: { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 8. FRYER BASKET ──────────────────────────────────────────
    {
      id: 'fryer_basket_yt_16',
      description: 'Deep fryer wire mesh basket with hook handle.',
      grid: [
        '................',
        '......HH........',
        '......HH........',
        '......HH........',
        '.....HHHH.......',
        '....AAAAAA......',
        '...ABBBBBBA.....',
        '...AB.B.BBA.....',
        '...ABBBBBBA.....',
        '...AB.B.BBA.....',
        '...ABBBBBBA.....',
        '...AB.B.BBA.....',
        '...ABBBBBBA.....',
        '...AAAAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'hook_handle', role: 'head' },
        A: { name: 'basket_frame', role: 'arm' },
        B: { name: 'wire_mesh', role: 'body' },
      },
      colors: {
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 9. BAMBOO STEAMER ────────────────────────────────────────
    {
      id: 'bamboo_steamer_yt_16',
      description: 'Bamboo steamer stack with two tiers and rising steam wisps.',
      grid: [
        '....EE...EE.....',
        '.....EE.EE......',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AAAAAAAAAAAAA.',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AABBBBBBBBAA..',
        '..AAAAAAAAAAAAA.',
        '................',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'steam_wisps', role: 'eye' },
        H: { name: 'lid_top', role: 'head' },
        A: { name: 'bamboo_frame', role: 'arm' },
        B: { name: 'bamboo_slats', role: 'body' },
      },
      colors: {
        eye:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 10. RICE COOKER ──────────────────────────────────────────
    {
      id: 'rice_cooker_yt_16',
      description: 'Electric rice cooker with rounded body, lid button, and steam vent.',
      grid: [
        '................',
        '.....EE.EE......',
        '......EE........',
        '....HHHHHHHH....',
        '...HHAAAAHHHH...',
        '...HHHHHHHHHH...',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..GGGGGGGGGGGG..',
        '..GGGGGGGGGGGG..',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'steam_vent', role: 'eye' },
        H: { name: 'lid_dome', role: 'head' },
        A: { name: 'lid_button', role: 'accessory' },
        B: { name: 'cooker_body', role: 'body' },
        G: { name: 'cooker_base', role: 'leg' },
      },
      colors: {
        eye:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:       { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 11. SANTOKU KNIFE ────────────────────────────────────────
    {
      id: 'santoku_knife_yt_16',
      description: 'Japanese santoku knife with wide blade and dark wood handle.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..HHH...........',
        '..HHH...........',
        '..HHHA..........',
        '...AABBBBBBBBB..',
        '...AABBBBBBBBB..',
        '....EEBBBBBBB...',
        '.....EEBBBBB....',
        '......EEBBB.....',
        '.......EEB......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wood_handle', role: 'head' },
        A: { name: 'bolster', role: 'arm' },
        B: { name: 'blade_flat', role: 'body' },
        E: { name: 'blade_edge', role: 'eye' },
      },
      colors: {
        head: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
        eye:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 12. WOK PAN ──────────────────────────────────────────────
    {
      id: 'wok_pan_yt_16',
      description: 'Round-bottom wok with long handle and oily sheen.',
      grid: [
        '................',
        '................',
        '................',
        '..HHH...........',
        '..HHH...........',
        '..HHAA..........',
        '....AABBBBBBB...',
        '...ABBBBBBBBBBA.',
        '..ABBBBBBBBBBBBA',
        '..ABBBEEEEBBBBA.',
        '...ABBBBBBBBBBA.',
        '....AABBBBBBAA..',
        '.....AAAAAAA....',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'wood_handle', role: 'head' },
        A: { name: 'wok_rim', role: 'arm' },
        B: { name: 'wok_surface', role: 'body' },
        E: { name: 'oil_sheen', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:  { shadow: '#757161', base: '#8595a1', highlight: '#deeed6' },
      },
    },

    // ─── 13. RAMEN POT ────────────────────────────────────────────
    {
      id: 'ramen_pot_yt_16',
      description: 'Large cooking pot with handles and bubbling broth surface.',
      grid: [
        '................',
        '.....EE..EE.....',
        '......EEEE......',
        '..HHHHHHHHHHHH..',
        '.AABBBBBBBBBBAA.',
        '.AABBBBBBBBBBAA.',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '...GGGGGGGGGG...',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'steam_bubbles', role: 'eye' },
        H: { name: 'pot_rim', role: 'head' },
        A: { name: 'side_handles', role: 'arm' },
        B: { name: 'pot_body', role: 'body' },
        G: { name: 'pot_base', role: 'leg' },
      },
      colors: {
        eye:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head: { shadow: '#4e4a4e', base: '#8595a1', highlight: '#deeed6' },
        arm:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        leg:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 14. GAS BURNER ───────────────────────────────────────────
    {
      id: 'gas_burner_yt_16',
      description: 'Portable gas burner stove with flame ring and control knob.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HH..........HH.',
        '.HH..EEEEEE..HH.',
        '.HH.EEEFFFEE.HH.',
        '.HH.EEEFFFEE.HH.',
        '.HH..EEEEEE..HH.',
        '.HH..........HH.',
        '.HHHHHHHHHHHHHH.',
        '.BBBBBBBBBBBBBB.',
        '.BBAABBBBBBBBBB.',
        '.BBBBBBBBBBBBBB.',
        '................',
      ],
      chars: {
        H: { name: 'burner_grate', role: 'head' },
        E: { name: 'flame_ring', role: 'eye' },
        F: { name: 'flame_core', role: 'hand' },
        B: { name: 'stove_body', role: 'body' },
        A: { name: 'control_knob', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        hand:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 15. CUTTING BOARD ────────────────────────────────────────
    {
      id: 'cutting_board_yt_16',
      description: 'Wooden hinoki cutting board with grain lines and juice groove.',
      grid: [
        '................',
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBEBBBBBBBEBBH',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBEBBBBBBBEBBH',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '.HBBEBBBBBBBEBBH',
        '.HBBBBBBBBBBBBH.',
        '.AAAAAAAAAAAAAAA',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'board_edge', role: 'head' },
        B: { name: 'wood_surface', role: 'body' },
        E: { name: 'grain_lines', role: 'eye' },
        A: { name: 'bottom_edge', role: 'arm' },
      },
      colors: {
        head: { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 16. SERVING TRAY ─────────────────────────────────────────
    {
      id: 'serving_tray_yt_16',
      description: 'Lacquered serving tray with raised rim and reflective surface.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '.HHHHHHHHHHHHHH.',
        '.HAAAAAAAAAAAAAH',
        '.HABBBBBBBBBBAAH',
        '.HABBBBBBBBBBAAH',
        '.HABBBBBBBBBBAAH',
        '.HABBBBBBBBBBAAH',
        '.HAAAAAAAAAAAAAH',
        '.HHHHHHHHHHHHHH.',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'tray_rim', role: 'head' },
        A: { name: 'inner_rim', role: 'arm' },
        B: { name: 'tray_surface', role: 'body' },
      },
      colors: {
        head: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:  { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 17. DONBURI BOWL ─────────────────────────────────────────
    {
      id: 'donburi_bowl_yt_16',
      description: 'Empty donburi ceramic bowl with blue pattern band.',
      grid: [
        '................',
        '................',
        '................',
        '..HHHHHHHHHHHH..',
        '.HBBBBBBBBBBBBH.',
        '.HBBBBBBBBBBBBH.',
        '..HBBBBBBBBBBH..',
        '..HBEEEEEEEEBH..',
        '..HBEEEEEEEEBH..',
        '...HBBBBBBBBH...',
        '...HBBBBBBBBH...',
        '....HBBBBBBH....',
        '.....GGGGGG.....',
        '......GGGG......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'bowl_rim', role: 'head' },
        B: { name: 'ceramic_body', role: 'body' },
        E: { name: 'blue_pattern', role: 'eye' },
        G: { name: 'bowl_foot', role: 'leg' },
      },
      colors: {
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        leg:  { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 18. KYUSU TEAPOT ─────────────────────────────────────────
    {
      id: 'kyusu_teapot_yt_16',
      description: 'Side-handle kyusu teapot with textured ceramic body.',
      grid: [
        '................',
        '................',
        '......HHH.......',
        '.....HHHHH......',
        '....BBBBBBB.....',
        '...BBBBBBBBB....',
        '..EBBBBBBBBBA...',
        '..EBBBBBBBBBBA..',
        '..EBBBBBBBBBA...',
        '...BBBBBBBBB....',
        '....BBBBBBB.....',
        '.....GGGGG......',
        '......GGG.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'lid_knob', role: 'head' },
        B: { name: 'pot_body', role: 'body' },
        E: { name: 'spout', role: 'eye' },
        A: { name: 'side_handle', role: 'arm' },
        G: { name: 'pot_base', role: 'leg' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        leg:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 19. CHOPSTICKS REST ──────────────────────────────────────
    {
      id: 'chopsticks_rest_yt_16',
      description: 'Chopsticks resting on a ceramic hashioki rest.',
      grid: [
        '................',
        '................',
        '................',
        '..HH............',
        '...HH...........',
        '....HH..........',
        '....AHH.........',
        '.....AHHA.......',
        '......AHHA......',
        '.......AHH......',
        '........AH......',
        '..BBBBBBBBBBB...',
        '..BEEEEEEEEBB...',
        '..BBBBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'chopstick_wood', role: 'head' },
        A: { name: 'chopstick_tip', role: 'arm' },
        B: { name: 'rest_ceramic', role: 'body' },
        E: { name: 'rest_pattern', role: 'eye' },
      },
      colors: {
        head: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        eye:  { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 20. RAMEN SPOON ──────────────────────────────────────────
    {
      id: 'ramen_spoon_yt_16',
      description: 'Ceramic ramen spoon with flat bottom and short handle.',
      grid: [
        '................',
        '................',
        '..HHH...........',
        '..HHHH..........',
        '...HHHA.........',
        '....AABB........',
        '.....ABBBB......',
        '.....ABBBBB.....',
        '......BBBBB.....',
        '......BBBBBB....',
        '......BBBBBB....',
        '.......BBBBB....',
        '........BBBB....',
        '.........BB.....',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'spoon_handle', role: 'head' },
        A: { name: 'handle_neck', role: 'arm' },
        B: { name: 'spoon_bowl', role: 'body' },
      },
      colors: {
        head: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        arm:  { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body: { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
