/**
 * Yatai batch 5 — 20 atmosphere & decoration templates.
 * Covers: maneki neko, daruma doll, furin chime, mini torii, bamboo fence,
 *         ishi doro lantern, sakura branch, matsuri banner, ema plaque,
 *         omamori charm, sensu fan, wagasa umbrella, oke bucket, menu board,
 *         koban coin, tanuki statue, koinobori streamer, shamisen, geta sandals,
 *         tea set.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'YATAI_BATCH5_TEMPLATES', schemes: 'YATAI_BATCH5_COLOR_SCHEMES' },
  templates: [

    // ─── 1. MANEKI NEKO (Lucky Beckoning Cat) ─────────────────────
    {
      id: 'maneki_neko_yt_16',
      description: 'Lucky beckoning cat with raised paw, red collar and gold bell.',
      grid: [
        '................',
        '..EHH....HHE....',
        '..EHHHHHHHHE....',
        '..HHFHHHHFHH....',
        '..HHNHHHNHH.....',
        '..HHHHHHHHH.....',
        '...HHHMMHH.AA...',
        '...HCCCCH..AH...',
        '...HCBCCH..AH...',
        '...HCCCCH.AH....',
        '...HHHHHHAH.....',
        '...HHHHHAH......',
        '...HHHHHH.......',
        '...LLHHLL.......',
        '...LL..LL.......',
        '................',
      ],
      chars: {
        H: { name: 'white_fur', role: 'body' },
        E: { name: 'ear_tips', role: 'head' },
        F: { name: 'face_mark', role: 'hair' },
        N: { name: 'eyes_nose', role: 'eye' },
        C: { name: 'collar', role: 'belt' },
        B: { name: 'bell', role: 'accessory' },
        A: { name: 'raised_arm', role: 'arm' },
        M: { name: 'mouth', role: 'hand' },
        L: { name: 'paws', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        hair:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        hand:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. DARUMA DOLL ───────────────────────────────────────────
    {
      id: 'daruma_doll_yt_16',
      description: 'Red daruma wish doll, round body with one eye filled in.',
      grid: [
        '................',
        '................',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '...GGFFFFFFGG...',
        '...GFFFEFFGFG...',
        '..GGGFFFFFFGGG..',
        '..GRRRRRRRRRRG..',
        '..RRRRRRRRRRR...',
        '..RRRRBBRRRRR...',
        '..RRRRRRRRRRR...',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '....RRRRRRRR....',
        '......DDDD......',
        '................',
      ],
      chars: {
        G: { name: 'gold_trim', role: 'accessory' },
        F: { name: 'face_area', role: 'head' },
        E: { name: 'eye_dot', role: 'eye' },
        R: { name: 'red_body', role: 'body' },
        B: { name: 'belly_kanji', role: 'belt' },
        D: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 3. FURIN CHIME (Wind Chime) ──────────────────────────────
    {
      id: 'furin_chime_yt_16',
      description: 'Glass wind chime with clapper and paper strip hanging below.',
      grid: [
        '................',
        '.......SS.......',
        '.......SS.......',
        '......GGGG......',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '....GGDDGGGG....',
        '....GGGGGGGG....',
        '.....GGGGGG.....',
        '.......CC.......',
        '.......CC.......',
        '......PPPP......',
        '......PFPP......',
        '......PPPP......',
        '......PPPP......',
        '.......PP.......',
      ],
      chars: {
        S: { name: 'string_hook', role: 'accessory' },
        G: { name: 'glass_bell', role: 'body' },
        D: { name: 'painted_design', role: 'head' },
        C: { name: 'clapper', role: 'belt' },
        P: { name: 'paper_strip', role: 'arm' },
        F: { name: 'strip_kanji', role: 'eye' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
      },
    },

    // ─── 4. MINI TORII GATE ───────────────────────────────────────
    {
      id: 'mini_torii_yt_16',
      description: 'Small red torii gate decoration, two pillars with crossbeams.',
      grid: [
        '................',
        '................',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '...RRRRRRRRRR...',
        '....RR....RR....',
        '...RRRR..RRRR...',
        '...RRRR..RRRR...',
        '....PP....PP....',
        '....PP....PP....',
        '....PP....PP....',
        '....PP....PP....',
        '....PP....PP....',
        '....PP....PP....',
        '...BBBB..BBBB...',
        '................',
      ],
      chars: {
        R: { name: 'red_beams', role: 'body' },
        P: { name: 'pillars', role: 'head' },
        B: { name: 'pillar_base', role: 'boot' },
      },
      colors: {
        body: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 5. BAMBOO FENCE ──────────────────────────────────────────
    {
      id: 'bamboo_fence_yt_16',
      description: 'Bamboo fence section with vertical poles and horizontal ties.',
      grid: [
        '................',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '.TTTTTTTTTTTTTT.',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '.TTTTTTTTTTTTTT.',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '..BB..BB..BB.B..',
        '................',
      ],
      chars: {
        B: { name: 'bamboo_poles', role: 'body' },
        T: { name: 'rope_ties', role: 'belt' },
      },
      colors: {
        body: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. ISHI DORO (Stone Lantern) ─────────────────────────────
    {
      id: 'ishi_doro_yt_16',
      description: 'Stone garden lantern with cap, fire box and pedestal.',
      grid: [
        '................',
        '......AAAA......',
        '.....AAAAAA.....',
        '....CCCCCCCC....',
        '...CCCCCCCCCC...',
        '....SSFFHFSS....',
        '....SSFFHFSS....',
        '....SSFFFFFFS...',
        '....SSFFFFFFS...',
        '.....SSSSSSSS...',
        '......PPPP......',
        '......PPPP......',
        '.....PPPPPP.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '................',
      ],
      chars: {
        A: { name: 'cap_finial', role: 'head' },
        C: { name: 'roof_cap', role: 'hair' },
        S: { name: 'stone_frame', role: 'body' },
        F: { name: 'fire_box', role: 'accessory' },
        H: { name: 'fire_glow', role: 'eye' },
        P: { name: 'pedestal', role: 'leg' },
        B: { name: 'base_stone', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        hair:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        leg:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#d2aa99' },
      },
    },

    // ─── 7. SAKURA BRANCH ─────────────────────────────────────────
    {
      id: 'sakura_branch_yt_16',
      description: 'Cherry blossom branch with pink flowers and dark bark.',
      grid: [
        '................',
        '..FF............',
        '.FCFF...FF......',
        '.FFF...FCFF.....',
        '..BB..FFFF......',
        '...BBBB.FF......',
        '....BBBBB.......',
        '.....BBBB..FF...',
        '......BBB.FCFF..',
        '.......BBBFFFF..',
        '........BBB.FF..',
        '.........BBB....',
        '..........BB....',
        '...........BB...',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'branch_bark', role: 'body' },
        F: { name: 'blossom_petals', role: 'head' },
        C: { name: 'flower_center', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
      },
    },

    // ─── 8. MATSURI BANNER ────────────────────────────────────────
    {
      id: 'matsuri_banner_yt_16',
      description: 'Festival banner on a pole, fabric with kanji lettering.',
      grid: [
        '..PP............',
        '..PPFFFFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFKKFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFKKFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFKKFFFFFFFF.',
        '..PPFFFFFFFFFFF.',
        '..PPFFFFFFFTTFF.',
        '..PP............',
        '..PP............',
        '..PP............',
        '..BB............',
      ],
      chars: {
        P: { name: 'pole', role: 'body' },
        F: { name: 'banner_fabric', role: 'head' },
        K: { name: 'kanji_text', role: 'eye' },
        T: { name: 'crest_emblem', role: 'accessory' },
        B: { name: 'pole_base', role: 'boot' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. EMA PLAQUE ────────────────────────────────────────────
    {
      id: 'ema_plaque_yt_16',
      description: 'Wooden wish plaque with pentagonal shape and hanging string.',
      grid: [
        '................',
        '......SS........',
        '......SS........',
        '.......HH.......',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...WWWWWWWWWW...',
        '...WWWWWWWWWW...',
        '...WWKKWWWWWW...',
        '...WWWWWWWWWW...',
        '...WWKKWWWWWW...',
        '...WWWWWWWWWW...',
        '...BBBBBBBBBB...',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'hanging_string', role: 'accessory' },
        H: { name: 'roof_shape', role: 'head' },
        W: { name: 'wood_body', role: 'body' },
        K: { name: 'written_wish', role: 'eye' },
        B: { name: 'bottom_edge', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#4e4a4e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 10. OMAMORI CHARM ────────────────────────────────────────
    {
      id: 'omamori_yt_16',
      description: 'Protection charm amulet, small embroidered fabric pouch with tassel.',
      grid: [
        '................',
        '......SS........',
        '......SS........',
        '.....GGGG.......',
        '....FFFFFF......',
        '....FFFFFF......',
        '....FFKKFF......',
        '....FFFFFF......',
        '....FFFFFF......',
        '....FFKKFF......',
        '....FFFFFF......',
        '....FFFFFF......',
        '.....FFFF.......',
        '......TT........',
        '.....TTTT.......',
        '................',
      ],
      chars: {
        S: { name: 'loop_string', role: 'accessory' },
        G: { name: 'gold_knot', role: 'head' },
        F: { name: 'fabric_body', role: 'body' },
        K: { name: 'kanji_embroidery', role: 'eye' },
        T: { name: 'tassel', role: 'belt' },
      },
      colors: {
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 11. SENSU FAN (Folding Fan) ──────────────────────────────
    {
      id: 'sensu_fan_yt_16',
      description: 'Partially open folding fan with decorative pattern and bamboo ribs.',
      grid: [
        '................',
        '................',
        '...FFFFF........',
        '..FFFFFFFF......',
        '..FFFFFFFFFFF...',
        '.FFFFFFFFFFFF...',
        '.FFDFFFFFFFFFFF.',
        '.FFFFFFDFFFFFFF.',
        '.FFFFFFFFFFF.FF.',
        '..RRRRRRRRR..R..',
        '..FFFFFFFFFF.F..',
        '...RRRRRRRRRRR..',
        '............HH..',
        '.............HH.',
        '..............H.',
        '................',
      ],
      chars: {
        F: { name: 'fan_paper', role: 'body' },
        D: { name: 'fan_design', role: 'head' },
        R: { name: 'bamboo_ribs', role: 'accessory' },
        H: { name: 'handle', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        belt:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 12. WAGASA UMBRELLA (Top View) ───────────────────────────
    {
      id: 'wagasa_yt_16',
      description: 'Paper umbrella seen from above, circular with radiating ribs.',
      grid: [
        '................',
        '....PPPPPPPP....',
        '...PPPPPPPPPP...',
        '..PPPRPPPPRPPP..',
        '..PPPPPPPPPPPP..',
        '.PPPRPPPPPPRPPP.',
        '.PPPPPPPPPPPPP..',
        '.PPPPPPHHPPPPPP.',
        '.PPPPPPHHPPPPPP.',
        '.PPPPPPPPPPPPP..',
        '.PPPRPPPPPPRPPP.',
        '..PPPPPPPPPPPP..',
        '..PPPRPPPPRPPP..',
        '...PPPPPPPPPP...',
        '....PPPPPPPP....',
        '................',
      ],
      chars: {
        P: { name: 'paper_panels', role: 'body' },
        R: { name: 'bamboo_ribs', role: 'accessory' },
        H: { name: 'center_hub', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. OKE BUCKET ───────────────────────────────────────────
    {
      id: 'oke_bucket_yt_16',
      description: 'Wooden bucket with metal bands and rope handle.',
      grid: [
        '................',
        '................',
        '...RR......RR...',
        '....RR....RR....',
        '.....RRRRRR.....',
        '....WWWWWWWW....',
        '...WWWWWWWWWW...',
        '...MMMMMMMMMMM..',
        '...WWWWWWWWWWW..',
        '...WWWWWWWWWWW..',
        '...MMMMMMMMMMM..',
        '...WWWWWWWWWWW..',
        '....WWWWWWWWW...',
        '....BBBBBBBB....',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rope_handle', role: 'accessory' },
        W: { name: 'wood_staves', role: 'body' },
        M: { name: 'metal_bands', role: 'belt' },
        B: { name: 'bottom_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 14. MENU BOARD ───────────────────────────────────────────
    {
      id: 'menu_board_yt_16',
      description: 'Chalk menu board with wooden frame and written items.',
      grid: [
        '................',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..FFBBBBBBBBFF..',
        '..FFBBTTBBBBFF..',
        '..FFBBBBBBBBFF..',
        '..FFBBTTTTBBFF..',
        '..FFBBBBBBBBFF..',
        '..FFBBTTBBBBFF..',
        '..FFBBBBBBBBFF..',
        '..FFBBTTTTBBFF..',
        '..FFBBBBBBBBFF..',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '......CC........',
        '................',
      ],
      chars: {
        F: { name: 'wood_frame', role: 'body' },
        B: { name: 'chalkboard', role: 'head' },
        T: { name: 'chalk_text', role: 'eye' },
        C: { name: 'chalk_piece', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#140c1c', base: '#346524', highlight: '#4e4a4e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 15. KOBAN COIN ───────────────────────────────────────────
    {
      id: 'koban_coin_yt_16',
      description: 'Oval gold koban coin with stamped markings.',
      grid: [
        '................',
        '................',
        '................',
        '.....SSSSSS.....',
        '....SSGGGGSS....',
        '...SGGGGGGGSS...',
        '...SGGGGGGGGS...',
        '...SGGGKKGGGS...',
        '...SGGGKKGGGS...',
        '...SGGGGGGGGS...',
        '...SGGGGGGGSS...',
        '....SSGGGGSS....',
        '.....SSSSSS.....',
        '................',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'coin_edge', role: 'body' },
        G: { name: 'gold_face', role: 'head' },
        K: { name: 'stamp_mark', role: 'eye' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:  { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. TANUKI STATUE ────────────────────────────────────────
    {
      id: 'tanuki_statue_yt_16',
      description: 'Tanuki raccoon dog statue with straw hat and big belly.',
      grid: [
        '................',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '...HHHHHHHH.....',
        '....FFFFFF......',
        '...FFFEFFFF.....',
        '...FFFFFFFAA....',
        '...FFBBBBFFA....',
        '...FFBBBBFF.....',
        '...FFFFFFFF.....',
        '...FFFFFFFF.....',
        '...FFLLLLFF.....',
        '...FFLLLLFF.....',
        '....LLLLLL......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'straw_hat', role: 'hair' },
        F: { name: 'fur_body', role: 'body' },
        E: { name: 'eyes', role: 'eye' },
        B: { name: 'belly_patch', role: 'head' },
        A: { name: 'sake_bottle', role: 'accessory' },
        L: { name: 'legs_base', role: 'boot' },
      },
      colors: {
        hair:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. KOINOBORI (Carp Streamer) ────────────────────────────
    {
      id: 'koinobori_yt_16',
      description: 'Carp wind sock streamer on a pole, fish body with open mouth.',
      grid: [
        'PP..............',
        'PP..............',
        'PP.EEHHHHHHH....',
        'PP.EHHHHHHHHHT..',
        'PP.EEBBBBBBBBTT.',
        'PP.EBBBBBBBBBBTT',
        'PP..BBBBBBBBBBT.',
        'PP..BBBBBBBBBBT.',
        'PP.FBBBBBBBBBTT.',
        'PP.FFBBBBBBBBTT.',
        'PP.FFHHHHHHHHHT.',
        'PP.FHHHHHHHH....',
        'PP..............',
        'PP..............',
        'PP..............',
        'GG..............',
      ],
      chars: {
        P: { name: 'pole', role: 'accessory' },
        H: { name: 'fish_head', role: 'head' },
        E: { name: 'eye_mouth', role: 'eye' },
        B: { name: 'fish_body', role: 'body' },
        T: { name: 'tail_fin', role: 'arm' },
        F: { name: 'lower_fin', role: 'belt' },
        G: { name: 'pole_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        belt:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 18. SHAMISEN ─────────────────────────────────────────────
    {
      id: 'shamisen_yt_16',
      description: 'Three-stringed traditional instrument with long neck and square body.',
      grid: [
        '.HH.............',
        '..HH............',
        '..NHH...........',
        '..NSH...........',
        '...NSH..........',
        '...NSH..........',
        '...NSH..........',
        '....NSH.........',
        '....NSH.........',
        '....NSBB........',
        '...NSBBBBB......',
        '...SSBBBBBBB....',
        '...SSBBBBBBBB...',
        '....SSBBBBBB....',
        '.....SSBBBBB....',
        '......SSS.......',
      ],
      chars: {
        H: { name: 'tuning_pegs', role: 'head' },
        N: { name: 'neck_wood', role: 'body' },
        S: { name: 'strings', role: 'accessory' },
        B: { name: 'body_resonator', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d2aa99' },
      },
    },

    // ─── 19. GETA SANDALS (Top View) ──────────────────────────────
    {
      id: 'geta_sandals_yt_16',
      description: 'Pair of wooden geta clogs seen from above with fabric straps.',
      grid: [
        '................',
        '................',
        '................',
        '..WWWWW.WWWWW...',
        '..WWWWW.WWWWW...',
        '..WSWWW.WSWWW...',
        '..SSSWW.SSSWW...',
        '..WWSWW.WWSWW...',
        '..WWWWW.WWWWW...',
        '..WWWWW.WWWWW...',
        '..WWWWW.WWWWW...',
        '..BBBBB.BBBBB...',
        '..WWWWW.WWWWW...',
        '................',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'wood_platform', role: 'body' },
        S: { name: 'fabric_strap', role: 'head' },
        B: { name: 'base_teeth', role: 'boot' },
      },
      colors: {
        body: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. TEA SET ──────────────────────────────────────────────
    {
      id: 'tea_set_yt_16',
      description: 'Tea ceremony set with teapot and cup on a wooden tray.',
      grid: [
        '................',
        '................',
        '................',
        '......LL........',
        '.....PPPP.......',
        '....PPPPPP......',
        '...HPPPPPP......',
        '...HPPPPPPS.....',
        '....PPPPPP......',
        '.....PPPP.......',
        '..TTTTTTTTTTTT..',
        '..TTTTCCTTTTT...',
        '..TTTTCCTTTTT...',
        '..TTTTCCTTTTTT..',
        '..BBBBBBBBBBBB..',
        '................',
      ],
      chars: {
        L: { name: 'pot_lid_knob', role: 'accessory' },
        P: { name: 'teapot', role: 'body' },
        H: { name: 'pot_handle', role: 'arm' },
        S: { name: 'pot_spout', role: 'hand' },
        T: { name: 'tray_surface', role: 'head' },
        C: { name: 'tea_cup', role: 'belt' },
        B: { name: 'tray_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#6dc2ca' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        hand:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

  ],
};

export default batch;
