/**
 * Yatai batch 3 — 20 Japanese street food DRINKS & CONDIMENTS templates.
 * Covers: sake tokkuri, sake ochoko, beer mug, ramune bottle, yunomi tea,
 *         matcha bowl, soy sauce, tonkatsu sauce, kewpie mayo, chili oil,
 *         wasabi paste, pickled ginger, rice vinegar, mirin bottle,
 *         dashi stock pot, senbei, amazake cup, calpis bottle,
 *         oolong tea glass, barley tea pitcher.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'YATAI_BATCH3_TEMPLATES', schemes: 'YATAI_BATCH3_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SAKE TOKKURI ──────────────────────────────────────────
    {
      id: 'sake_tokkuri_yt_16',
      description: 'Traditional ceramic sake tokkuri bottle with narrow neck and round body.',
      grid: [
        '................',
        '......NNNN......',
        '.....NNNNNN.....',
        '......NNNN......',
        '......NNNN......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBBEBBBBBB..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '....SSSSSSSS....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        N: { name: 'neck', role: 'head' },
        B: { name: 'body_ceramic', role: 'body' },
        E: { name: 'glaze_shine', role: 'eye' },
        S: { name: 'base_rim', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        eye:   { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:   { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
        boot:  { shadow: '#140c1c', base: '#140c1c', highlight: '#4e4a4e' },
      },
    },

    // ─── 2. SAKE OCHOKO ───────────────────────────────────────────
    {
      id: 'sake_ochoko_yt_16',
      description: 'Small ceramic sake cup (ochoko) filled with clear sake.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '................',
        '......LLLL......',
        '.....LLLLLL.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBSBBBB....',
        '....CCCCCCCC....',
        '....CCCCCCCC....',
        '.....CCCCCC.....',
        '......TTTT......',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'sake_liquid', role: 'head' },
        B: { name: 'cup_inner', role: 'body' },
        S: { name: 'liquid_shine', role: 'eye' },
        C: { name: 'cup_outer', role: 'arm' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:   { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:  { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 3. BEER MUG ──────────────────────────────────────────────
    {
      id: 'beer_mug_yt_16',
      description: 'Draft beer mug with golden beer and thick foam head.',
      grid: [
        '................',
        '....FFFFFFFF....',
        '...FFFFFFFFFF...',
        '...FFFFFFFFFF...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBBM..',
        '...BBBBEBBBBM...',
        '...BBBBBBBBBBM..',
        '...BBBBBBBBBBM..',
        '...BBBBBBBBBM...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...GGGGGGGGGG...',
        '....GGGGGGGG....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        F: { name: 'foam_head', role: 'head' },
        B: { name: 'beer_body', role: 'body' },
        E: { name: 'beer_shine', role: 'eye' },
        M: { name: 'mug_handle', role: 'accessory' },
        G: { name: 'glass_base', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. RAMUNE BOTTLE ─────────────────────────────────────────
    {
      id: 'ramune_bottle_yt_16',
      description: 'Marble soda bottle with distinctive pinched waist and glass marble.',
      grid: [
        '......NNNN......',
        '.....NNNNNN.....',
        '......NNNN......',
        '......MMNN......',
        '.....NNNNNN.....',
        '....NNNNNNNN....',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBSBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        N: { name: 'neck_glass', role: 'head' },
        M: { name: 'marble', role: 'eye' },
        B: { name: 'bottle_body', role: 'body' },
        S: { name: 'liquid_shine', role: 'accessory' },
        T: { name: 'bottle_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        accessory: { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
      },
    },

    // ─── 5. YUNOMI TEA ────────────────────────────────────────────
    {
      id: 'yunomi_tea_yt_16',
      description: 'Green tea in traditional yunomi cup with painted band.',
      grid: [
        '................',
        '................',
        '................',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '...LLSLLLLLLL...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...DDDDDDDDDD...',
        '...DDDDDDDDDD...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        L: { name: 'tea_liquid', role: 'head' },
        S: { name: 'tea_shine', role: 'eye' },
        B: { name: 'cup_ceramic', role: 'body' },
        D: { name: 'painted_band', role: 'accessory' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 6. MATCHA BOWL ───────────────────────────────────────────
    {
      id: 'matcha_bowl_yt_16',
      description: 'Matcha tea in wide chawan bowl with frothy surface.',
      grid: [
        '................',
        '................',
        '................',
        '..FFFFFFFFFFFF..',
        '..FFFFFFFFFFFF..',
        '..FFFSFFFSFFF...',
        '..LLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        F: { name: 'matcha_froth', role: 'head' },
        S: { name: 'froth_bubble', role: 'eye' },
        L: { name: 'matcha_liquid', role: 'accessory' },
        B: { name: 'bowl_ceramic', role: 'body' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#6daa2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 7. SOY SAUCE BOTTLE ──────────────────────────────────────
    {
      id: 'soy_sauce_yt_16',
      description: 'Shoyu dispensing bottle with narrow spout and red cap.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '......NNNN......',
        '......NNNN......',
        '.....NNNNNN.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBSBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....LLLLLLLL....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'red_cap', role: 'accessory' },
        N: { name: 'bottle_neck', role: 'head' },
        B: { name: 'soy_body', role: 'body' },
        S: { name: 'label_mark', role: 'eye' },
        L: { name: 'bottle_base', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 8. TONKATSU SAUCE BOTTLE ─────────────────────────────────
    {
      id: 'tonkatsu_sauce_yt_16',
      description: 'Brown tonkatsu sauce bottle with yellow label band.',
      grid: [
        '................',
        '......CCCC......',
        '......NNNN......',
        '......NNNN......',
        '.....NNNNNN.....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....LLLLLLLL....',
        '....LLLLLLLL....',
        '....LLLLLLLL....',
        '....BBBBBBBB....',
        '....BBBSBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'accessory' },
        N: { name: 'bottle_neck', role: 'head' },
        B: { name: 'sauce_body', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        S: { name: 'sauce_shine', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
      },
    },

    // ─── 9. KEWPIE MAYO ──────────────────────────────────────────
    {
      id: 'kewpie_mayo_yt_16',
      description: 'Kewpie mayonnaise squeeze bottle with red net pattern and star tip.',
      grid: [
        '................',
        '.......NN.......',
        '......NNNN......',
        '......CCCC......',
        '.....CCCCCC.....',
        '....RBBBBBBR....',
        '....RBBBBBBR....',
        '....RBBSBBBBR...',
        '....RBBBBBBR....',
        '....RBBBBBBR....',
        '....RBBBBBBR....',
        '....RBBBBBBR....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
      ],
      chars: {
        N: { name: 'squeeze_tip', role: 'head' },
        C: { name: 'cap_ring', role: 'accessory' },
        R: { name: 'red_net', role: 'arm' },
        B: { name: 'mayo_body', role: 'body' },
        S: { name: 'label_shine', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#d2aa99' },
      },
    },

    // ─── 10. CHILI OIL JAR ────────────────────────────────────────
    {
      id: 'chili_oil_yt_16',
      description: 'Rayu chili oil jar with red oil and chili flakes visible.',
      grid: [
        '................',
        '................',
        '.....CCCCCC.....',
        '....CCCCCCCC....',
        '....LLLLLLLL....',
        '....LLLLLLLL....',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '...BBBFBBFBBB...',
        '...BBBBBBBBBB...',
        '...BBFBBBBFBB...',
        '...BBBBBBBBBB...',
        '...GGGGGGGGGG...',
        '....GGGGGGGG....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'jar_lid', role: 'head' },
        L: { name: 'lid_band', role: 'accessory' },
        B: { name: 'chili_oil', role: 'body' },
        F: { name: 'chili_flake', role: 'eye' },
        G: { name: 'jar_glass', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        eye:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 11. WASABI PASTE TUBE ────────────────────────────────────
    {
      id: 'wasabi_paste_yt_16',
      description: 'Wasabi paste tube with green body and white cap.',
      grid: [
        '................',
        '................',
        '.CC.............',
        '.CCC............',
        '..CCNN..........',
        '...NNNNN........',
        '....BBBBBBB.....',
        '....BBBBBBBBB...',
        '....BBBBBBBBBB..',
        '....BBBSBBBBBBB.',
        '....BBBBBBBBBB..',
        '....BBBBBBBBB...',
        '....BBBBBBB.....',
        '.....TTTTT......',
        '................',
        '................',
      ],
      chars: {
        C: { name: 'tube_cap', role: 'head' },
        N: { name: 'tube_neck', role: 'accessory' },
        B: { name: 'tube_body', role: 'body' },
        S: { name: 'label_shine', role: 'eye' },
        T: { name: 'tube_crimp', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 12. PICKLED GINGER ───────────────────────────────────────
    {
      id: 'pickled_ginger_yt_16',
      description: 'Gari pickled ginger pile on a small ceramic plate.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....GGGGGG.....',
        '....GGGGGGGG....',
        '...GGGSGGGSGGG..',
        '...GGGGGGGGGG...',
        '..GGGGGGGGGGGGG.',
        '..GGGSGGGGSGGG..',
        '..GGGGGGGGGGG...',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        G: { name: 'ginger_slice', role: 'head' },
        S: { name: 'ginger_fold', role: 'eye' },
        P: { name: 'plate', role: 'body' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        eye:   { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body:  { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        boot:  { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. RICE VINEGAR BOTTLE ──────────────────────────────────
    {
      id: 'rice_vinegar_yt_16',
      description: 'Rice vinegar bottle with pale yellow liquid and label.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '......NNNN......',
        '......NNNN......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....LLLLLLLL....',
        '....LLLLLLLL....',
        '....LLSLLLLL....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....AAAAAAAA....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'accessory' },
        N: { name: 'bottle_neck', role: 'head' },
        B: { name: 'vinegar_body', role: 'body' },
        L: { name: 'label_band', role: 'arm' },
        S: { name: 'label_mark', role: 'eye' },
        A: { name: 'bottle_base', role: 'belt' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        belt:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 14. MIRIN BOTTLE ─────────────────────────────────────────
    {
      id: 'mirin_bottle_yt_16',
      description: 'Mirin cooking wine bottle with amber liquid and traditional label.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '......NNNN......',
        '......NNNN......',
        '.....NNNNNN.....',
        '....BBBBBBBB....',
        '....LLLLLLLL....',
        '....LLLLLLLL....',
        '....LLSLLLLL....',
        '....LLLLLLLL....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'head' },
        N: { name: 'bottle_neck', role: 'accessory' },
        B: { name: 'mirin_body', role: 'body' },
        L: { name: 'label_area', role: 'arm' },
        S: { name: 'kanji_mark', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 15. DASHI STOCK POT ──────────────────────────────────────
    {
      id: 'dashi_stock_yt_16',
      description: 'Dashi stock pot with lid and steam rising, kelp visible inside.',
      grid: [
        '....XXXX........',
        '...XXXX.........',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..LLLLLLLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..LLLKLLKLLLL...',
        '..LLLLLLLLLLLL..',
        '..LLLLLKLLLLLL..',
        '..LLLLLLLLLLLL..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        X: { name: 'steam', role: 'accessory' },
        H: { name: 'pot_lid', role: 'head' },
        L: { name: 'dashi_liquid', role: 'body' },
        K: { name: 'kelp_piece', role: 'eye' },
        B: { name: 'pot_body', role: 'arm' },
        T: { name: 'pot_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
        boot:      { shadow: '#140c1c', base: '#4e4a4e', highlight: '#757161' },
      },
    },

    // ─── 16. SENBEI ───────────────────────────────────────────────
    {
      id: 'senbei_yt_16',
      description: 'Round rice cracker with soy sauce glaze and sesame seeds.',
      grid: [
        '................',
        '................',
        '................',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHHH...',
        '..HHHSHHHHSHHHH.',
        '..HHHHHHHHHHHH..',
        '..HHHHSHHHHSHHH.',
        '..HHHHHHHHHHHH..',
        '...HHHHHHHHHH...',
        '....BBBBBBBB....',
        '.....BBBBBB.....',
        '......TTTT......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'cracker_surface', role: 'head' },
        S: { name: 'sesame_seed', role: 'eye' },
        B: { name: 'cracker_edge', role: 'body' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:  { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        eye:   { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:  { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:  { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 17. AMAZAKE CUP ──────────────────────────────────────────
    {
      id: 'amazake_cup_yt_16',
      description: 'Sweet sake (amazake) in traditional cup with ginger garnish.',
      grid: [
        '................',
        '................',
        '......GG........',
        '.....GGG........',
        '....LLLLLLLL....',
        '...LLLLLLLLLL...',
        '...LLSLLLLLLL...',
        '...LLLLLLLLLL...',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'ginger_garnish', role: 'accessory' },
        L: { name: 'amazake_liquid', role: 'head' },
        S: { name: 'liquid_shine', role: 'eye' },
        B: { name: 'cup_ceramic', role: 'body' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 18. CALPIS BOTTLE ────────────────────────────────────────
    {
      id: 'calpis_bottle_yt_16',
      description: 'Calpis/Calpico bottle with blue polka dot label and white body.',
      grid: [
        '................',
        '.......CC.......',
        '......CCCC......',
        '......NNNN......',
        '......NNNN......',
        '.....BBBBBB.....',
        '....BBBBBBBB....',
        '....LLLDLLLL....',
        '....LLLLLLDL....',
        '....LDLLLLLL....',
        '....LLLLLDLL....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        C: { name: 'bottle_cap', role: 'head' },
        N: { name: 'bottle_neck', role: 'accessory' },
        B: { name: 'bottle_body', role: 'body' },
        L: { name: 'label_white', role: 'arm' },
        D: { name: 'polka_dot', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#30346d', base: '#597dce', highlight: '#6dc2ca' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#d2aa99' },
      },
    },

    // ─── 19. OOLONG TEA GLASS ─────────────────────────────────────
    {
      id: 'oolong_tea_yt_16',
      description: 'Oolong tea in tall glass with ice cubes visible.',
      grid: [
        '................',
        '................',
        '....GGGGGGGG....',
        '....GIIGGIIG....',
        '....GIIGGTTG....',
        '....GTTGGTTG....',
        '....GTTTTTTG....',
        '....GTTTTTTG....',
        '....GTTTTTTG....',
        '....GTTTTTTG....',
        '....GTTTTTTG....',
        '....GTTTTTTG....',
        '....GGGGGGGG....',
        '.....SSSSSS.....',
        '......BBBB......',
        '................',
      ],
      chars: {
        G: { name: 'glass_wall', role: 'accessory' },
        I: { name: 'ice_cube', role: 'eye' },
        T: { name: 'tea_liquid', role: 'body' },
        S: { name: 'glass_stem', role: 'arm' },
        B: { name: 'glass_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 20. BARLEY TEA PITCHER ───────────────────────────────────
    {
      id: 'barley_tea_yt_16',
      description: 'Mugicha barley tea pitcher with handle and amber liquid.',
      grid: [
        '................',
        '...HHHHHHHHHH...',
        '...HHHHHHHHHH...',
        '..LLLLLLLLLLLL..',
        '..LLSLLLLLLLLL..',
        '..LLLLLLLLLLLLP.',
        '..LLLLLLLLLLLLP.',
        '..LLLLLLLLLLLLP.',
        '..LLLLLLLLLLLLP.',
        '..LLLLLLLLLLLL..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        H: { name: 'pitcher_rim', role: 'head' },
        L: { name: 'tea_liquid', role: 'body' },
        S: { name: 'tea_shine', role: 'eye' },
        P: { name: 'pitcher_handle', role: 'accessory' },
        B: { name: 'pitcher_body', role: 'arm' },
        T: { name: 'pitcher_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        eye:       { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

  ],
};

export default batch;
