/**
 * Yatai batch 2 — 20 Japanese street food item templates.
 * Covers: takoyaki plate, yakitori skewer, okonomiyaki, taiyaki, dango,
 *         mochi, karaage, korokke, kakigori, nikuman,
 *         imagawayaki, crepe cone, yakiimo, ikayaki, kushikatsu,
 *         mitarashi dango, melon pan, anpan, dorayaki, corn dog.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'YATAI_BATCH2_TEMPLATES', schemes: 'YATAI_BATCH2_COLOR_SCHEMES' },
  templates: [

    // ─── 1. TAKOYAKI PLATE ─────────────────────────────────────
    {
      id: 'takoyaki_plate_yt_16',
      description: 'Plate of round takoyaki balls with brown sauce drizzle and bonito.',
      grid: [
        '................',
        '................',
        '................',
        '....BBSBBS......',
        '...BBBBBBB......',
        '...BBSBBS.BBSB..',
        '...BBBBBBBBBBB..',
        '....BSBBBBBSBB..',
        '....BBBBBBBBBBB.',
        '.....BSBBBSBBBB.',
        '.....BBBBBBBBBB.',
        '....AAAAAAAAAAAA',
        '...AAAHAAAHAAAA.',
        '...AAAAAAAAAA...',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'takoyaki_ball', role: 'body' },
        S: { name: 'sauce_drizzle', role: 'head' },
        A: { name: 'boat_tray', role: 'arm' },
        H: { name: 'tray_detail', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        accessory: { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 2. YAKITORI SKEWER ────────────────────────────────────
    {
      id: 'yakitori_skewer_yt_16',
      description: 'Chicken yakitori pieces on a bamboo skewer with char marks.',
      grid: [
        '................',
        '.......SS.......',
        '......SBBS......',
        '......SBBS......',
        '.......SS.......',
        '......HBBH......',
        '......HBBH......',
        '.......SS.......',
        '......SBBS......',
        '......SBBS......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        B: { name: 'chicken_meat', role: 'body' },
        S: { name: 'char_marks', role: 'head' },
        H: { name: 'scallion', role: 'accessory' },
        A: { name: 'bamboo_stick', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 3. OKONOMIYAKI ────────────────────────────────────────
    {
      id: 'okonomiyaki_yt_16',
      description: 'Round savory pancake with zigzag sauce and mayo drizzle.',
      grid: [
        '................',
        '................',
        '................',
        '....SSMMSS......',
        '...SBBBBBBS.....',
        '..SBBBBBBBBM....',
        '..MBBBBBBBBS....',
        '..SBBBBBBBBM....',
        '..MBBBBBBBBS....',
        '..SBBBBBBBBM....',
        '...SBBBBBBS.....',
        '...AAAAAAA......',
        '....AAAAA.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pancake_body', role: 'body' },
        S: { name: 'brown_sauce', role: 'head' },
        M: { name: 'mayo_drizzle', role: 'arm' },
        A: { name: 'plate_base', role: 'belt' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 4. TAIYAKI ────────────────────────────────────────────
    {
      id: 'taiyaki_yt_16',
      description: 'Fish-shaped pastry in side view with visible tail fin.',
      grid: [
        '................',
        '................',
        '................',
        '............BB..',
        '...BBBBBBBBBBB..',
        '..BBHBBBBBBBBBB.',
        '..BEBBBBBBBBBB..',
        '.BBBSBBBBSBBBB..',
        '.BBBBBBBBBBBBBB.',
        '..BBBSBBBBSBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBBB..',
        '............BB..',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'batter_body', role: 'body' },
        H: { name: 'head_detail', role: 'head' },
        E: { name: 'fish_eye', role: 'eye' },
        S: { name: 'scale_pattern', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 5. DANGO STICK ────────────────────────────────────────
    {
      id: 'dango_stick_yt_16',
      description: 'Three-color dango on stick: pink, white, green from top to bottom.',
      grid: [
        '................',
        '................',
        '.....HHHH.......',
        '....HHHHHH......',
        '....HHHHHH......',
        '.....HHHH.......',
        '.....BBBB.......',
        '....BBBBBB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....AAAA.......',
        '....AAAAAA......',
        '....AAAAAA......',
        '.....SSSS.......',
        '......SS........',
        '......SS........',
      ],
      chars: {
        H: { name: 'pink_dango', role: 'head' },
        B: { name: 'white_dango', role: 'body' },
        A: { name: 'green_dango', role: 'arm' },
        S: { name: 'bamboo_stick', role: 'accessory' },
      },
      colors: {
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 6. MOCHI ──────────────────────────────────────────────
    {
      id: 'mochi_yt_16',
      description: 'Round mochi rice cake with soft dusted surface.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....BBBB.......',
        '....BBBBBH......',
        '...BBBBBBBH.....',
        '...BBBBBBBH.....',
        '...BBBBBBBH.....',
        '...BBBBBBBH.....',
        '....BBBBBB......',
        '....AAAAAA......',
        '.....AAAA.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'mochi_body', role: 'body' },
        H: { name: 'mochi_highlight', role: 'head' },
        A: { name: 'mochi_base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 7. KARAAGE ────────────────────────────────────────────
    {
      id: 'karaage_yt_16',
      description: 'Fried chicken pieces on a small paper-lined plate.',
      grid: [
        '................',
        '................',
        '................',
        '....BBB.BB......',
        '...BBBBBBB......',
        '..BBBSHBBBS.....',
        '..BBBBBBBBB.....',
        '..BBBSBBBSB.....',
        '..BBBBBBBBB.....',
        '...BBBBBBB......',
        '..AAAAAAAAA.....',
        '..AHAAAHAAAH....',
        '..AAAAAAAAAA....',
        '...AAAAAAAA.....',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'fried_chicken', role: 'body' },
        S: { name: 'crispy_crust', role: 'head' },
        A: { name: 'paper_plate', role: 'arm' },
        H: { name: 'paper_fold', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 8. KOROKKE ────────────────────────────────────────────
    {
      id: 'korokke_yt_16',
      description: 'Oval Japanese croquette with golden fried crust and creamy inside.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....BBBB.......',
        '....BBBBBB......',
        '...BBBBBBBB.....',
        '...BHAAAHBB.....',
        '...BHAAAHBB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....BBBB.......',
        '....SSSSSS......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'fried_crust', role: 'body' },
        A: { name: 'creamy_inside', role: 'arm' },
        H: { name: 'crust_edge', role: 'head' },
        S: { name: 'sauce_pool', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 9. KAKIGORI ───────────────────────────────────────────
    {
      id: 'kakigori_yt_16',
      description: 'Shaved ice tower with colorful syrup drizzle in a cup.',
      grid: [
        '................',
        '......HH........',
        '.....HBBH.......',
        '....HBBBBH......',
        '...HBBBBBSH.....',
        '...BBBSBBBH.....',
        '..HBBBBBBBBH....',
        '..BBBSBBBSBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBBS....',
        '...AAAAAAAA.....',
        '...AAAAAAAA.....',
        '...AAAAAAAA.....',
        '....AAAAAA......',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'shaved_ice', role: 'body' },
        H: { name: 'ice_highlight', role: 'head' },
        S: { name: 'syrup_drizzle', role: 'accessory' },
        A: { name: 'cup_base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#597dce', base: '#6dc2ca', highlight: '#deeed6' },
        head:      { shadow: '#6dc2ca', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        arm:       { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 10. NIKUMAN ───────────────────────────────────────────
    {
      id: 'nikuman_yt_16',
      description: 'Round steamed meat bun with pleated top and soft white surface.',
      grid: [
        '................',
        '................',
        '................',
        '......HH........',
        '.....HHHH.......',
        '....HHHHHH......',
        '...BBBBBBBB.....',
        '...BBBHBBBB.....',
        '..BBBBHHBBBB....',
        '..BBBBBBBBBB....',
        '..BBBBBBBBBB....',
        '...BBBBBBBB.....',
        '...AAAAAAAA.....',
        '....AAAAAA......',
        '................',
        '................',
      ],
      chars: {
        H: { name: 'pleated_top', role: 'head' },
        B: { name: 'bun_body', role: 'body' },
        A: { name: 'bun_base', role: 'arm' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 11. IMAGAWAYAKI ───────────────────────────────────────
    {
      id: 'imagawayaki_yt_16',
      description: 'Round filled pastry with cross pattern stamped on top.',
      grid: [
        '................',
        '................',
        '................',
        '.....BBBB.......',
        '....BBBHBB......',
        '...BBBHBBBB.....',
        '...BHHHHHHB.....',
        '...BBBHBBBB.....',
        '...BBBHBBBB.....',
        '...AAAAAAAAA....',
        '...AASAASAAA....',
        '....AAAAAAA.....',
        '.....AAAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pastry_top', role: 'body' },
        H: { name: 'cross_pattern', role: 'head' },
        A: { name: 'pastry_side', role: 'arm' },
        S: { name: 'filling_peek', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
      },
    },

    // ─── 12. CREPE CONE ────────────────────────────────────────
    {
      id: 'crepe_cone_yt_16',
      description: 'Harajuku crepe cone with whipped cream and fruit toppings.',
      grid: [
        '................',
        '.....SSS........',
        '....SAAAS.......',
        '....SAHAS.......',
        '...SAAHAAS......',
        '...SAAAAAS......',
        '...BBBBBBB......',
        '....BBBBB.......',
        '....BBBBB.......',
        '.....BBBB.......',
        '.....BBB........',
        '......BB........',
        '......BB........',
        '.......B........',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'whipped_cream', role: 'head' },
        A: { name: 'fruit_topping', role: 'accessory' },
        H: { name: 'strawberry', role: 'arm' },
        B: { name: 'crepe_cone', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 13. YAKIIMO ───────────────────────────────────────────
    {
      id: 'yakiimo_yt_16',
      description: 'Roasted sweet potato cut open to show bright orange flesh.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '..BBB...........',
        '.BBBBBBB........',
        '.BBAAABBBB......',
        '.BAAAAABBBB.....',
        '.BAAHAABBBBB....',
        '.BAAAAABBBB.....',
        '.BBAAABBBB......',
        '.BBBBBBB........',
        '..BBB...........',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'potato_skin', role: 'body' },
        A: { name: 'orange_flesh', role: 'arm' },
        H: { name: 'flesh_highlight', role: 'head' },
      },
      colors: {
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#dad45e', base: '#deeed6', highlight: '#deeed6' },
      },
    },

    // ─── 14. IKAYAKI ───────────────────────────────────────────
    {
      id: 'ikayaki_yt_16',
      description: 'Grilled whole squid on stick with tentacles spread below.',
      grid: [
        '................',
        '.......BB.......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BHEHBB.....',
        '.....BBBBBB.....',
        '.....SSBBSS.....',
        '......SBBS......',
        '......BBBB......',
        '.....BB..BB.....',
        '....BB....BB....',
        '....BB....BB....',
        '.....B....B.....',
        '.......AA.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        B: { name: 'squid_body', role: 'body' },
        H: { name: 'squid_head', role: 'head' },
        E: { name: 'squid_eye', role: 'eye' },
        S: { name: 'char_marks', role: 'accessory' },
        A: { name: 'bamboo_stick', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#140c1c', highlight: '#442434' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 15. KUSHIKATSU ────────────────────────────────────────
    {
      id: 'kushikatsu_yt_16',
      description: 'Deep-fried breaded item on bamboo skewer with golden crust.',
      grid: [
        '................',
        '................',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BHHHBB.....',
        '....BBHHHHBB....',
        '....BBHHHHBB....',
        '....BBHHHHBB....',
        '.....BHHHBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        B: { name: 'fried_crust', role: 'body' },
        H: { name: 'inner_filling', role: 'head' },
        A: { name: 'bamboo_stick', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 16. MITARASHI DANGO ───────────────────────────────────
    {
      id: 'mitarashi_yt_16',
      description: 'Glazed dango balls on stick with dark sweet soy glaze.',
      grid: [
        '................',
        '................',
        '.....BBBB.......',
        '....BSBBSB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....BSBBSB......',
        '....BBBBBB......',
        '.....BBBB.......',
        '.....BBBB.......',
        '....BSBBSB......',
        '....BBBBBB......',
        '.....AAAA.......',
        '......AA........',
        '......AA........',
      ],
      chars: {
        B: { name: 'dango_ball', role: 'body' },
        S: { name: 'glaze_drip', role: 'head' },
        A: { name: 'bamboo_stick', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

    // ─── 17. MELON PAN ─────────────────────────────────────────
    {
      id: 'melon_pan_yt_16',
      description: 'Round melon bread with cookie crust grid pattern on top.',
      grid: [
        '................',
        '................',
        '................',
        '.....HBHB.......',
        '....BHBHBH......',
        '...HBHBHBHB.....',
        '...BHBHBHBH.....',
        '...HBHBHBHB.....',
        '...BHBHBHBH.....',
        '...AAAAAAAAA....',
        '...AAAAAAAAA....',
        '....AAAAAAA.....',
        '.....AAAAA......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'cookie_grid', role: 'body' },
        H: { name: 'grid_groove', role: 'head' },
        A: { name: 'bread_base', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        head:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
      },
    },

    // ─── 18. ANPAN ─────────────────────────────────────────────
    {
      id: 'anpan_yt_16',
      description: 'Round red bean paste bread with sesame seed accent on top.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '.....BBBB.......',
        '....BBBSBB......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '...BBAAAAAB.....',
        '...BBAAAAAB.....',
        '...BBBBBBBB.....',
        '....BBBBBB......',
        '.....HHHH.......',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'bread_body', role: 'body' },
        A: { name: 'bean_paste', role: 'arm' },
        S: { name: 'sesame_seed', role: 'accessory' },
        H: { name: 'bread_shadow', role: 'head' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 19. DORAYAKI ──────────────────────────────────────────
    {
      id: 'dorayaki_yt_16',
      description: 'Two-pancake sandwich with red bean filling visible at the side.',
      grid: [
        '................',
        '................',
        '................',
        '................',
        '....HHHHHH......',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '..AAAAAAAAA.....',
        '..AAAAAAAAA.....',
        '...BBBBBBBB.....',
        '...BBBBBBBB.....',
        '....SSSSSS......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        B: { name: 'pancake_disc', role: 'body' },
        H: { name: 'top_highlight', role: 'head' },
        A: { name: 'bean_filling', role: 'arm' },
        S: { name: 'bottom_shadow', role: 'accessory' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. CORN DOG ──────────────────────────────────────────
    {
      id: 'corn_dog_yt_16',
      description: 'Japanese-style corn dog on stick with golden batter coating.',
      grid: [
        '................',
        '.......HH.......',
        '......BBBB......',
        '......BBBB......',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '.....BBBBBB.....',
        '......BBBB......',
        '......SBBS......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '.......AA.......',
        '................',
      ],
      chars: {
        B: { name: 'batter_coat', role: 'body' },
        H: { name: 'ketchup_top', role: 'head' },
        S: { name: 'mustard_drip', role: 'accessory' },
        A: { name: 'wooden_stick', role: 'arm' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#dad45e', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
      },
    },

  ],
};

export default batch;
