/**
 * Yatai batch 1 — 20 Japanese street food templates (ramen & noodle dishes).
 * Covers: shoyu ramen, miso ramen, tonkotsu ramen, spicy ramen,
 *         kitsune udon, zaru soba, yakisoba plate, tsukemen,
 *         ajitama egg, chashu slice, naruto swirl, gyoza plate,
 *         tempura prawn, onigiri nori, rice bowl, miso soup,
 *         edamame bowl, tofu block, noodle cup, bao bun.
 */
import type { BatchDefinition } from '../templateGenerator.js';

const batch: BatchDefinition = {
  category: 'food',
  exportNames: { templates: 'YATAI_BATCH1_TEMPLATES', schemes: 'YATAI_BATCH1_COLOR_SCHEMES' },
  templates: [

    // ─── 1. SHOYU RAMEN ───────────────────────────────────────────
    // 3/4 view: elliptical rim, broth interior, bowl wall taper
    {
      id: 'ramen_shoyu_16',
      description: 'Shoyu ramen in ceramic bowl — dark soy broth, pale noodles, halved egg, nori strip.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '...RRBBBBBBRR...',
        '..RBBBBBBBBBBR..',
        '..RBNNNNNNNNBR..',
        '..RBEENNNNNNBR..',
        '..RBEENNNNGGBR..',
        '..RBNNNNNNNNBR..',
        '...RRRRRRRRRR...',
        '....RWWWWWWR....',
        '.....RWWWWR.....',
        '......RRRR......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bowl_rim', role: 'body' },
        B: { name: 'shoyu_broth', role: 'arm' },
        N: { name: 'noodles', role: 'head' },
        E: { name: 'egg_half', role: 'eye' },
        G: { name: 'nori_strip', role: 'belt' },
        W: { name: 'bowl_wall', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 2. MISO RAMEN ────────────────────────────────────────────
    // 3/4 view: curved elliptical rim, amber broth, corn, butter
    {
      id: 'ramen_miso_16',
      description: 'Miso ramen in ceramic bowl — amber broth, noodles, corn kernels, butter pat.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '...RRBBBBBBRR...',
        '..RBBBBBBBBBBR..',
        '..RBNNNNNNNNBR..',
        '..RBNCCCNNNPBR..',
        '..RBNCCCNNNNBR..',
        '..RBNNNNNNNNBR..',
        '...RRRRRRRRRR...',
        '....RWWWWWWR....',
        '.....RWWWWR.....',
        '......RRRR......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bowl_rim', role: 'body' },
        B: { name: 'miso_broth', role: 'arm' },
        N: { name: 'noodles', role: 'head' },
        C: { name: 'corn_kernels', role: 'eye' },
        P: { name: 'butter_pat', role: 'belt' },
        W: { name: 'bowl_wall', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        belt:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 3. TONKOTSU RAMEN ────────────────────────────────────────
    // 3/4 view: curved rim, creamy white broth, chashu, scallion
    {
      id: 'ramen_tonkotsu_16',
      description: 'Tonkotsu ramen in ceramic bowl — creamy white broth, chashu pork slices, scallion.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '...RRBBBBBBRR...',
        '..RBBBBBBBBBBR..',
        '..RBNNNNNNNNBR..',
        '..RBMMNNNNNNBR..',
        '..RBMMNNNNGGBR..',
        '..RBNNNNNNNNBR..',
        '...RRRRRRRRRR...',
        '....RWWWWWWR....',
        '.....RWWWWR.....',
        '......RRRR......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bowl_rim', role: 'body' },
        B: { name: 'tonkotsu_broth', role: 'arm' },
        N: { name: 'noodles', role: 'head' },
        M: { name: 'chashu_pork', role: 'eye' },
        G: { name: 'scallion_bits', role: 'belt' },
        W: { name: 'bowl_wall', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 4. SPICY RAMEN ───────────────────────────────────────────
    // 3/4 view: curved rim, red chili broth, chili pepper, oil
    {
      id: 'ramen_spicy_16',
      description: 'Spicy ramen in ceramic bowl — red chili broth, noodles, chili pepper, chili oil.',
      grid: [
        '................',
        '.....RRRRRR.....',
        '...RRBBBBBBRR...',
        '..RBBBBBBBBBBR..',
        '..RBNNNNNNNNBR..',
        '..RBNNHHNNOOBR..',
        '..RBNNHHNNNNBR..',
        '..RBNNNNNNNNBR..',
        '...RRRRRRRRRR...',
        '....RWWWWWWR....',
        '.....RWWWWR.....',
        '......RRRR......',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'bowl_rim', role: 'body' },
        B: { name: 'spicy_broth', role: 'arm' },
        N: { name: 'noodles', role: 'head' },
        H: { name: 'chili_pepper', role: 'eye' },
        O: { name: 'chili_oil', role: 'belt' },
        W: { name: 'bowl_wall', role: 'leg' },
      },
      colors: {
        body:      { shadow: '#854c30', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        eye:       { shadow: '#140c1c', base: '#442434', highlight: '#d04648' },
        belt:      { shadow: '#d04648', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#4e4a4e', base: '#8595a1', highlight: '#d2aa99' },
      },
    },

    // ─── 5. KITSUNE UDON ──────────────────────────────────────────
    {
      id: 'udon_kitsune_16',
      description: 'Kitsune udon bowl with thick white noodles and golden fried tofu.',
      grid: [
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '..BBBBBBBBBBBB..',
        '..BNNNNNNNNNNB..',
        '..BNNNNFFNNNNB..',
        '..BNNNFFFFNNNB..',
        '..BNNNFFFFNNNB..',
        '..BNNNNFFNNNNB..',
        '..BNNNNNNNNNNB..',
        '..BBBBBBBBBBBB..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        B: { name: 'dashi_broth', role: 'body' },
        N: { name: 'udon_noodles', role: 'head' },
        F: { name: 'fried_tofu', role: 'arm' },
        W: { name: 'bowl_side', role: 'leg' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 6. ZARU SOBA ─────────────────────────────────────────────
    {
      id: 'soba_zaru_16',
      description: 'Cold soba noodles coiled on bamboo mat with nori garnish on top.',
      grid: [
        '................',
        '................',
        '....GGGG........',
        '....GGGG........',
        '...NNNNNNNNNN...',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..MHMHMHMHMHMH..',
        '..HMHMHMHMHMHM..',
        '..MHMHMHMHMHMH..',
        '...TTTTTTTTTT...',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'nori_garnish', role: 'belt' },
        N: { name: 'soba_noodles', role: 'head' },
        M: { name: 'bamboo_mat_a', role: 'body' },
        H: { name: 'bamboo_mat_b', role: 'arm' },
        T: { name: 'tray_base', role: 'boot' },
      },
      colors: {
        belt:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        head:      { shadow: '#757161', base: '#8595a1', highlight: '#d2aa99' },
        body:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 7. YAKISOBA PLATE ────────────────────────────────────────
    {
      id: 'yakisoba_plate_16',
      description: 'Fried yakisoba noodles on a plate with pickled ginger and aonori flakes.',
      grid: [
        '................',
        '................',
        '....GGGG........',
        '...NNNNNNNNNN...',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNNFNNNFNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNNNNNNNNNNN..',
        '..NNFNNNNNNFNN..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'pickled_ginger', role: 'accessory' },
        N: { name: 'yakisoba_noodles', role: 'head' },
        F: { name: 'aonori_flakes', role: 'belt' },
        P: { name: 'plate_surface', role: 'body' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 8. TSUKEMEN ──────────────────────────────────────────────
    {
      id: 'tsukemen_16',
      description: 'Dipping ramen: thick noodles on one side, rich dipping sauce on the other.',
      grid: [
        '................',
        '................',
        '.NNNNNNN........',
        '.NNNNNNN..DDDD..',
        '.NNNNNNN.DDDDDD.',
        '.NNNNNNN.DDDDDD.',
        '.NNNNNNN.DDDDDD.',
        '.NNNNNNN.DDDDDD.',
        '.PPPPPPPP.BBBB..',
        '.PPPPPPPP..BB...',
        '..PPPPPP........',
        '...TTTT...TTTT..',
        '................',
        '................',
        '................',
        '................',
      ],
      chars: {
        N: { name: 'thick_noodles', role: 'head' },
        D: { name: 'dipping_sauce', role: 'body' },
        P: { name: 'noodle_plate', role: 'arm' },
        B: { name: 'sauce_bowl', role: 'leg' },
        T: { name: 'base_shadows', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        arm:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 9. AJITAMA EGG ───────────────────────────────────────────
    {
      id: 'ramen_egg_16',
      description: 'Ajitama marinated egg half with jammy golden yolk visible, dark marinade stain.',
      grid: [
        '................',
        '................',
        '......HHHH......',
        '.....HHHHHH.....',
        '....HHHHHHHH....',
        '...HHHHHHHHH....',
        '...HHWWWWWHH....',
        '..HHWWWWWWWHH...',
        '..HHWWYYWWWHH...',
        '..HHWWYYWWWHH...',
        '..HHWWWWWWWHH...',
        '...HHWWWWWHH....',
        '...HHHHHHHH.....',
        '....HHHHHH......',
        '.....TTTT.......',
        '................',
      ],
      chars: {
        H: { name: 'marinade_shell', role: 'head' },
        W: { name: 'egg_white', role: 'body' },
        Y: { name: 'jammy_yolk', role: 'eye' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#dad45e', highlight: '#dad45e' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#854c30' },
      },
    },

    // ─── 10. CHASHU SLICE ─────────────────────────────────────────
    {
      id: 'chashu_slice_16',
      description: 'Rolled pork belly chashu slice with visible spiral layers and caramelized glaze.',
      grid: [
        '................',
        '................',
        '.....GGGGG......',
        '....GGGGGGG.....',
        '...GMMMMMMGG....',
        '..GMMMMMMMMG....',
        '..GMMPPPPMMMG...',
        '..GMMPFFFPMMMG..',
        '..GMMPFFFPMMMG..',
        '..GMMPPPPMMMG...',
        '..GMMMMMMMMG....',
        '...GMMMMMMGG....',
        '....GGGGGGG.....',
        '.....TTTTT......',
        '................',
        '................',
      ],
      chars: {
        G: { name: 'caramel_glaze', role: 'accessory' },
        M: { name: 'pork_meat', role: 'head' },
        P: { name: 'fat_layer', role: 'body' },
        F: { name: 'inner_core', role: 'arm' },
        T: { name: 'base_shadow', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        head:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        body:      { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        arm:       { shadow: '#854c30', base: '#d27d2c', highlight: '#d2aa99' },
        boot:      { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
      },
    },

    // ─── 11. NARUTO SWIRL ─────────────────────────────────────────
    {
      id: 'naruto_swirl_16',
      description: 'Narutomaki fishcake disc with pink spiral pattern on white base.',
      grid: [
        '................',
        '................',
        '.....WWWWWW.....',
        '....WWWWWWWW....',
        '...WWWPPPPWWW...',
        '..WWWPPWWWPWWW..',
        '..WWWPWWWWWWWW..',
        '..WWWPWWPPWWWW..',
        '..WWWWWPPWPWWW..',
        '..WWWWWWWWPWWW..',
        '..WWWPWWWPPWWW..',
        '...WWWPPPPWWW...',
        '....WWWWWWWW....',
        '.....WWWWWW.....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'fishcake_white', role: 'head' },
        P: { name: 'pink_spiral', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 12. GYOZA PLATE ──────────────────────────────────────────
    {
      id: 'gyoza_plate_16',
      description: 'Row of five pan-fried gyoza dumplings on a plate with golden crispy bottoms.',
      grid: [
        '................',
        '................',
        '................',
        '.WWWWWWWWWWWWW..',
        '.WFWWFWWFWWFWW..',
        '.WWFWWFWWFWWFW..',
        '.HHHHHHHHHHHHHH.',
        '.HBHBHBHBHBHBHH.',
        '.HHHHHHHHHHHHHH.',
        '.CCCCCCCCCCCCCC.',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
        '................',
      ],
      chars: {
        W: { name: 'wrapper_top', role: 'head' },
        F: { name: 'fold_crease', role: 'eye' },
        H: { name: 'crispy_bottom', role: 'body' },
        B: { name: 'char_marks', role: 'arm' },
        C: { name: 'oil_drip', role: 'accessory' },
        P: { name: 'plate_surface', role: 'leg' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#d27d2c', base: '#d2aa99', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        accessory: { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        leg:       { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 13. TEMPURA PRAWN ────────────────────────────────────────
    {
      id: 'tempura_prawn_16',
      description: 'Crispy tempura battered prawn with golden coat and exposed pink tail.',
      grid: [
        '................',
        '.........TTT....',
        '........TTTTT...',
        '.......TTTTT....',
        '......BBBBB.....',
        '.....BBBBBBB....',
        '....BBBHBBBBBB..',
        '...BBBBHBBBBBB..',
        '...BBBHHBBBBBB..',
        '...BBHHHBBBBBB..',
        '....BHHHHBBBBB..',
        '.....BHHHBBBB...',
        '......BHHBB.....',
        '.......BBB......',
        '................',
        '................',
      ],
      chars: {
        T: { name: 'prawn_tail', role: 'accessory' },
        B: { name: 'batter_coat', role: 'body' },
        H: { name: 'prawn_flesh', role: 'head' },
      },
      colors: {
        accessory: { shadow: '#d04648', base: '#d27d2c', highlight: '#d2aa99' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d04648', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

    // ─── 14. ONIGIRI NORI ─────────────────────────────────────────
    {
      id: 'onigiri_nori_16',
      description: 'Triangle rice ball wrapped in nori seaweed with a visible umeboshi filling.',
      grid: [
        '................',
        '.......RR.......',
        '......RRRR......',
        '.....RRRRRR.....',
        '....RRRRRRRR....',
        '....RRRRURRR....',
        '...RRRRRRRRRR...',
        '...RRRRRRRRRR...',
        '..RRRRRRRRRRRR..',
        '..RRNNNNNNNNRR..',
        '..RRNNNNNNNNRR..',
        '..RRNNNNNNNNRR..',
        '..RRNNNNNNNNRR..',
        '...NNNNNNNNNN...',
        '................',
        '................',
      ],
      chars: {
        R: { name: 'rice_surface', role: 'head' },
        U: { name: 'umeboshi', role: 'eye' },
        N: { name: 'nori_wrap', role: 'body' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        body:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
      },
    },

    // ─── 15. RICE BOWL ────────────────────────────────────────────
    {
      id: 'rice_bowl_yt_16',
      description: 'Bowl of fluffy white rice with subtle grain texture and steam wisps.',
      grid: [
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..RRRRRRRRRRRR..',
        '..BBBBBBBBBBBB..',
        '..BPPPPPPPPPPB..',
        '..BPPPPPPPPPPB..',
        '...BPPPPPPPPB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        R: { name: 'rice_mound', role: 'head' },
        B: { name: 'bowl_rim', role: 'body' },
        P: { name: 'bowl_pattern', role: 'arm' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
        arm:       { shadow: '#597dce', base: '#8595a1', highlight: '#d2aa99' },
        boot:      { shadow: '#30346d', base: '#597dce', highlight: '#8595a1' },
      },
    },

    // ─── 16. MISO SOUP ────────────────────────────────────────────
    {
      id: 'miso_soup_yt_16',
      description: 'Miso soup bowl with tofu cubes and wakame seaweed floating in golden broth.',
      grid: [
        '................',
        '....SSSSSSSS....',
        '...SSSSSSSSSS...',
        '..BBBBBBBBBBBB..',
        '..BBBTTBBBBBBB..',
        '..BBBTTBGGGBBB..',
        '..BBBBBGGGBBBB..',
        '..BBTTBBBTTBBB..',
        '..BBTTBBBTTBBB..',
        '..BBBBBBBBBBBB..',
        '..WWWWWWWWWWWW..',
        '...WWWWWWWWWW...',
        '....WWWWWWWW....',
        '.....FFFFFF.....',
        '................',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        B: { name: 'miso_broth', role: 'body' },
        T: { name: 'tofu_cubes', role: 'head' },
        G: { name: 'wakame_seaweed', role: 'belt' },
        W: { name: 'bowl_side', role: 'arm' },
        F: { name: 'bowl_foot', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#854c30', base: '#d27d2c', highlight: '#dad45e' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        belt:      { shadow: '#140c1c', base: '#346524', highlight: '#6daa2c' },
        arm:       { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 17. EDAMAME BOWL ─────────────────────────────────────────
    {
      id: 'edamame_yt_16',
      description: 'Bowl of bright green edamame pods with salt crystals sprinkled on top.',
      grid: [
        '................',
        '................',
        '..EEEEEEEEEEEE..',
        '..ESEESEESEESE..',
        '..EEEEEEEEEEEE..',
        '..ESEEESEEEESE..',
        '..EEEEEEEEEEEE..',
        '..EESEEEESEEEE..',
        '..EEEEEEEEEEEE..',
        '..BBBBBBBBBBBB..',
        '..BBBBBBBBBBBB..',
        '...BBBBBBBBBB...',
        '....BBBBBBBB....',
        '.....TTTTTT.....',
        '................',
        '................',
      ],
      chars: {
        E: { name: 'edamame_pods', role: 'head' },
        S: { name: 'salt_crystals', role: 'eye' },
        B: { name: 'bowl_body', role: 'body' },
        T: { name: 'bowl_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        eye:       { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 18. TOFU BLOCK ───────────────────────────────────────────
    {
      id: 'tofu_block_yt_16',
      description: 'Block of silken tofu on a ceramic plate with soy sauce drizzle.',
      grid: [
        '................',
        '................',
        '................',
        '...HHHHHHHHHH...',
        '..HHHHHHHHHHHH..',
        '..HHHEHHHHEHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHHHHHHHHHH..',
        '..HHHEHHHHEHHH..',
        '..HHHHHHHHHHHH..',
        '..DDDDDDDDDDDD..',
        '..PPPPPPPPPPPP..',
        '..PPPPPPPPPPPP..',
        '...PPPPPPPPPP...',
        '....TTTTTTTT....',
        '................',
      ],
      chars: {
        H: { name: 'tofu_body', role: 'head' },
        E: { name: 'tofu_shine', role: 'eye' },
        D: { name: 'soy_drizzle', role: 'accessory' },
        P: { name: 'plate_surface', role: 'body' },
        T: { name: 'plate_base', role: 'boot' },
      },
      colors: {
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        eye:       { shadow: '#deeed6', base: '#deeed6', highlight: '#deeed6' },
        accessory: { shadow: '#140c1c', base: '#442434', highlight: '#854c30' },
        body:      { shadow: '#757161', base: '#d2aa99', highlight: '#deeed6' },
        boot:      { shadow: '#4e4a4e', base: '#757161', highlight: '#8595a1' },
      },
    },

    // ─── 19. NOODLE CUP ───────────────────────────────────────────
    {
      id: 'noodle_cup_yt_16',
      description: 'Instant ramen cup noodle container with peeled-back lid and noodles visible.',
      grid: [
        '...LLLLLLLL.....',
        '..LLLLLLLLLL....',
        '..LLLLLLLLL.....',
        '...NNNNNNNNNN...',
        '...NNNNNNNNNN...',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CLCCCCCCCLCC..',
        '..CCCCCCCCCCCC..',
        '..CCCCCCCCCCCC..',
        '..CLCCCCCCCLCC..',
        '..CCCCCCCCCCCC..',
        '...CCCCCCCCCC...',
        '....CCCCCCCC....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        L: { name: 'peeled_lid', role: 'accessory' },
        N: { name: 'noodles_inside', role: 'head' },
        C: { name: 'cup_body', role: 'body' },
        T: { name: 'cup_base', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
        head:      { shadow: '#d27d2c', base: '#dad45e', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#d04648', highlight: '#d27d2c' },
        boot:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
      },
    },

    // ─── 20. BAO BUN ──────────────────────────────────────────────
    {
      id: 'bao_bun_yt_16',
      description: 'Steamed bao bun half-open with savory pork filling and scallion bits visible.',
      grid: [
        '................',
        '....SSSSSS......',
        '...SSSSSSSS.....',
        '....HHHHHH......',
        '...HHHHHHHH.....',
        '..HHHHHHHHHH....',
        '..HHHHHHHHHHH...',
        '..HHHHHHHHHH....',
        '..HHHFFFFFFHH...',
        '..HHHFFFFFFHH...',
        '..HHFFFGGFFFHH..',
        '..HHHFFFFFFHH...',
        '...HHHHHHHHHH...',
        '....HHHHHHHH....',
        '.....TTTTTT.....',
        '................',
      ],
      chars: {
        S: { name: 'steam_wisps', role: 'accessory' },
        H: { name: 'bun_dough', role: 'head' },
        F: { name: 'pork_filling', role: 'body' },
        G: { name: 'scallion_bits', role: 'belt' },
        T: { name: 'base_fold', role: 'boot' },
      },
      colors: {
        accessory: { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        head:      { shadow: '#d2aa99', base: '#deeed6', highlight: '#deeed6' },
        body:      { shadow: '#442434', base: '#854c30', highlight: '#d27d2c' },
        belt:      { shadow: '#346524', base: '#6daa2c', highlight: '#dad45e' },
        boot:      { shadow: '#8595a1', base: '#d2aa99', highlight: '#deeed6' },
      },
    },

  ],
};

export default batch;
