import {
  getProject, addLayer as addLayerToProject, getLayer, pushUndo,
  type McpProject, type McpLayer, type UndoEntry,
} from '../project.js';
import { PixelBuffer, type RGBA } from '../lib/pixelBuffer.js';
import { hexToRgba, rgbaToHex, rgbaEqual } from '../lib/colorUtils.js';
import {
  TEMPLATES, COLOR_SCHEMES,
  type SpriteTemplate, type ColorScheme,
} from '../templates/humanoid16.js';
import {
  GAME_TEMPLATES, GAME_COLOR_SCHEMES,
} from '../templates/gameStyles.js';
import {
  CREATURE_TEMPLATES, CREATURE_COLOR_SCHEMES,
} from '../templates/creatures.js';
import {
  ITEM_TEMPLATES, ITEM_COLOR_SCHEMES,
} from '../templates/items.js';
import {
  ITEM_VARIETY_TEMPLATES, ITEM_VARIETY_COLOR_SCHEMES,
} from '../templates/itemsVariety.js';
import {
  ENVIRONMENT_TEMPLATES, ENVIRONMENT_COLOR_SCHEMES,
} from '../templates/environment.js';
import {
  UI_TEMPLATES, UI_COLOR_SCHEMES,
} from '../templates/uiElements.js';
import {
  COZY_SHOP_UI_TEMPLATES, COZY_SHOP_UI_COLOR_SCHEMES,
} from '../templates/uiCozyShop.js';
import {
  EFFECT_TEMPLATES, EFFECT_COLOR_SCHEMES,
} from '../templates/effects.js';
import {
  DUNGEON_TEMPLATES, DUNGEON_COLOR_SCHEMES,
} from '../templates/dungeon.js';
import {
  EQUIPMENT_TEMPLATES, EQUIPMENT_COLOR_SCHEMES,
} from '../templates/equipment.js';
import {
  FURNITURE_TEMPLATES, FURNITURE_COLOR_SCHEMES,
} from '../templates/furniture.js';
import {
  RPG_UI_TEMPLATES, RPG_UI_COLOR_SCHEMES,
} from '../templates/rpgUI.js';
import {
  RPG_UI_VARIETY_TEMPLATES, RPG_UI_VARIETY_COLOR_SCHEMES,
} from '../templates/rpgUIVariety.js';
import {
  NATURE_TEMPLATES, NATURE_COLOR_SCHEMES,
} from '../templates/nature.js';
import {
  ENEMY_TEMPLATES, ENEMY_COLOR_SCHEMES,
} from '../templates/enemies.js';
import {
  BOSS_TEMPLATES, BOSS_COLOR_SCHEMES,
} from '../templates/bosses.js';
import {
  NPC_TEMPLATES, NPC_COLOR_SCHEMES,
} from '../templates/npcs.js';
import {
  FOOD_TEMPLATES, FOOD_COLOR_SCHEMES,
} from '../templates/food.js';
import {
  BIOME_TEMPLATES, BIOME_COLOR_SCHEMES,
} from '../templates/biomes.js';
import {
  VEHICLE_TEMPLATES, VEHICLE_COLOR_SCHEMES,
} from '../templates/vehicles.js';
import {
  CHARACTER_VARIANT_TEMPLATES, CHARACTER_VARIANT_COLOR_SCHEMES,
} from '../templates/characterVariants.js';
import {
  PROP_TEMPLATES, PROP_COLOR_SCHEMES,
} from '../templates/props.js';
import {
  ANIMATION_16_TEMPLATES, ANIMATION_16_COLOR_SCHEMES,
} from '../templates/animations16.js';
import {
  COLOR_VARIANT_SCHEMES,
} from '../templates/colorVariants.js';
import {
  PLANT_TEMPLATES, PLANT_COLOR_SCHEMES,
} from '../templates/plants.js';
import {
  PLANT_BATCH1_TEMPLATES, PLANT_BATCH1_COLOR_SCHEMES,
} from '../templates/plantsVariety.js';
import {
  BUILDING_TEMPLATES, BUILDING_COLOR_SCHEMES,
} from '../templates/buildings.js';
import {
  CREATURE_BATCH1_TEMPLATES, CREATURE_BATCH1_COLOR_SCHEMES,
} from '../templates/creaturesVariety.js';
import {
  ENEMY_BATCH1_TEMPLATES, ENEMY_BATCH1_COLOR_SCHEMES,
} from '../templates/enemiesVariety.js';
import {
  BUILDING_BATCH1_TEMPLATES, BUILDING_BATCH1_COLOR_SCHEMES,
} from '../templates/buildingsVariety.js';
import {
  EFFECT_BATCH1_TEMPLATES, EFFECT_BATCH1_COLOR_SCHEMES,
} from '../templates/effectsVariety.js';
import {
  FOOD_BATCH1_TEMPLATES, FOOD_BATCH1_COLOR_SCHEMES,
} from '../templates/foodVariety.js';
import {
  BOSS_BATCH1_TEMPLATES, BOSS_BATCH1_COLOR_SCHEMES,
} from '../templates/bossesVariety.js';
import {
  VEHICLE_BATCH1_TEMPLATES, VEHICLE_BATCH1_COLOR_SCHEMES,
} from '../templates/vehiclesVariety.js';
import {
  CHARACTER_BATCH1_TEMPLATES, CHARACTER_BATCH1_COLOR_SCHEMES,
} from '../templates/charactersVariety.js';
import {
  FURNITURE_BATCH1_TEMPLATES, FURNITURE_BATCH1_COLOR_SCHEMES,
} from '../templates/furnitureVariety.js';
import {
  UI_VARIETY_TEMPLATES, UI_VARIETY_COLOR_SCHEMES,
} from '../templates/uiVariety.js';
import {
  CREATURE_BATCH2_TEMPLATES, CREATURE_BATCH2_COLOR_SCHEMES,
} from '../templates/creaturesVariety2.js';
import {
  EFFECT_BATCH2_TEMPLATES, EFFECT_BATCH2_COLOR_SCHEMES,
} from '../templates/effectsVariety2.js';
import {
  BUILDING_BATCH2_TEMPLATES, BUILDING_BATCH2_COLOR_SCHEMES,
} from '../templates/buildingsVariety2.js';
import {
  FOOD_BATCH2_TEMPLATES, FOOD_BATCH2_COLOR_SCHEMES,
} from '../templates/foodVariety2.js';
import {
  BIOME_VARIETY_TEMPLATES, BIOME_VARIETY_COLOR_SCHEMES,
} from '../templates/biomesVariety.js';
import {
  ENVIRONMENT_VARIETY_TEMPLATES, ENVIRONMENT_VARIETY_COLOR_SCHEMES,
} from '../templates/environmentVariety.js';
import {
  NATURE_VARIETY_TEMPLATES, NATURE_VARIETY_COLOR_SCHEMES,
} from '../templates/natureVariety.js';
import {
  CREATURE_BATCH3_TEMPLATES, CREATURE_BATCH3_COLOR_SCHEMES,
} from '../templates/creaturesVariety3.js';
import {
  ENEMY_BATCH2_TEMPLATES, ENEMY_BATCH2_COLOR_SCHEMES,
} from '../templates/enemiesVariety2.js';
import {
  ENEMY_BATCH3_TEMPLATES, ENEMY_BATCH3_COLOR_SCHEMES,
} from '../templates/enemiesVariety3.js';
import {
  BOSS_BATCH2_TEMPLATES, BOSS_BATCH2_COLOR_SCHEMES,
} from '../templates/bossesVariety2.js';
import {
  BOSS_BATCH3_TEMPLATES, BOSS_BATCH3_COLOR_SCHEMES,
} from '../templates/bossesVariety3.js';
import {
  VEHICLE_BATCH2_TEMPLATES, VEHICLE_BATCH2_COLOR_SCHEMES,
} from '../templates/vehiclesVariety2.js';
import {
  EQUIPMENT_VARIETY_TEMPLATES, EQUIPMENT_VARIETY_COLOR_SCHEMES,
} from '../templates/equipmentVariety.js';
import {
  FOOD_BATCH3_TEMPLATES, FOOD_BATCH3_COLOR_SCHEMES,
} from '../templates/foodVariety3.js';
import {
  FURNITURE_BATCH2_TEMPLATES, FURNITURE_BATCH2_COLOR_SCHEMES,
} from '../templates/furnitureVariety2.js';
import {
  EFFECT_BATCH3_TEMPLATES, EFFECT_BATCH3_COLOR_SCHEMES,
} from '../templates/effectsVariety3.js';
import {
  BUILDING_BATCH3_TEMPLATES, BUILDING_BATCH3_COLOR_SCHEMES,
} from '../templates/buildingsVariety3.js';
import {
  MODERN_TECH_TEMPLATES, MODERN_TECH_COLOR_SCHEMES,
} from '../templates/modernTech.js';
import {
  RETRO_TECH_TEMPLATES, RETRO_TECH_COLOR_SCHEMES,
} from '../templates/retroTech.js';
import {
  ITEM_BATCH2_TEMPLATES, ITEM_BATCH2_COLOR_SCHEMES,
} from '../templates/itemsVariety2.js';
import {
  EQUIPMENT_BATCH2_TEMPLATES, EQUIPMENT_BATCH2_COLOR_SCHEMES,
} from '../templates/equipmentVariety2.js';
import {
  WEAPONS_CLASSIC_TEMPLATES, WEAPONS_CLASSIC_COLOR_SCHEMES,
} from '../templates/weaponsClassic.js';
import {
  CHARACTER_BATCH2_TEMPLATES, CHARACTER_BATCH2_COLOR_SCHEMES,
} from '../templates/charactersVariety2.js';
import {
  CHARACTER_BATCH3_TEMPLATES, CHARACTER_BATCH3_COLOR_SCHEMES,
} from '../templates/charactersVariety3.js';
import {
  GAME_INSPIRED_BATCH1_TEMPLATES, GAME_INSPIRED_BATCH1_COLOR_SCHEMES,
} from '../templates/gameInspiredVariety.js';
import {
  CHAR_VARIANT_BATCH1_TEMPLATES, CHAR_VARIANT_BATCH1_COLOR_SCHEMES,
} from '../templates/charVariantsNew.js';
import {
  MODERN_TECH_BATCH1_TEMPLATES, MODERN_TECH_BATCH1_COLOR_SCHEMES,
} from '../templates/modernTechVariety.js';
import {
  MODERN_TECH_BATCH2_TEMPLATES, MODERN_TECH_BATCH2_COLOR_SCHEMES,
} from '../templates/modernTechVariety2.js';
import {
  MODERN_TECH_BATCH3_TEMPLATES, MODERN_TECH_BATCH3_COLOR_SCHEMES,
} from '../templates/modernTechVariety3.js';
import {
  MODERN_TECH_BATCH4_TEMPLATES, MODERN_TECH_BATCH4_COLOR_SCHEMES,
} from '../templates/modernTechVariety4.js';
import {
  EFFECT_BATCH4_TEMPLATES, EFFECT_BATCH4_COLOR_SCHEMES,
} from '../templates/effectsVariety4.js';
import {
  EFFECT_BATCH5_TEMPLATES, EFFECT_BATCH5_COLOR_SCHEMES,
} from '../templates/effectsVariety5.js';
import {
  RETRO_TECH_BATCH1_TEMPLATES, RETRO_TECH_BATCH1_COLOR_SCHEMES,
} from '../templates/retroTechVariety.js';
import {
  RETRO_TECH_BATCH2_TEMPLATES, RETRO_TECH_BATCH2_COLOR_SCHEMES,
} from '../templates/retroTechVariety2.js';
import {
  RETRO_TECH_BATCH3_TEMPLATES, RETRO_TECH_BATCH3_COLOR_SCHEMES,
} from '../templates/retroTechVariety3.js';
import {
  RETRO_TECH_BATCH4_TEMPLATES, RETRO_TECH_BATCH4_COLOR_SCHEMES,
} from '../templates/retroTechVariety4.js';
import {
  VEHICLE_BATCH3_TEMPLATES, VEHICLE_BATCH3_COLOR_SCHEMES,
} from '../templates/vehiclesVariety3.js';
import {
  VEHICLE_BATCH4_TEMPLATES, VEHICLE_BATCH4_COLOR_SCHEMES,
} from '../templates/vehiclesVariety4.js';
import {
  VEHICLE_BATCH5_TEMPLATES, VEHICLE_BATCH5_COLOR_SCHEMES,
} from '../templates/vehiclesVariety5.js';
import {
  DUNGEON_BATCH1_TEMPLATES, DUNGEON_BATCH1_COLOR_SCHEMES,
} from '../templates/dungeonVariety.js';
import {
  DUNGEON_TILES_BATCH1_TEMPLATES, DUNGEON_TILES_BATCH1_COLOR_SCHEMES,
} from '../templates/dungeonTilesVariety.js';
import {
  DUNGEON_TILES_BATCH2_TEMPLATES, DUNGEON_TILES_BATCH2_COLOR_SCHEMES,
} from '../templates/dungeonTilesVariety2.js';
import {
  DUNGEON_TILES_BATCH3_TEMPLATES, DUNGEON_TILES_BATCH3_COLOR_SCHEMES,
} from '../templates/dungeonTilesVariety3.js';
import {
  DUNGEON_TILES_BATCH4_TEMPLATES, DUNGEON_TILES_BATCH4_COLOR_SCHEMES,
} from '../templates/dungeonTilesVariety4.js';
import {
  DUNGEON_TILES_BATCH5_TEMPLATES, DUNGEON_TILES_BATCH5_COLOR_SCHEMES,
} from '../templates/dungeonTilesVariety5.js';
import {
  FURNITURE_BATCH3_TEMPLATES, FURNITURE_BATCH3_COLOR_SCHEMES,
} from '../templates/furnitureVariety3.js';
import {
  EFFECT_BATCH6_TEMPLATES, EFFECT_BATCH6_COLOR_SCHEMES,
} from '../templates/effectsVariety6.js';
import {
  UI_BARS_TEMPLATES, UI_BARS_COLOR_SCHEMES,
} from '../templates/uiBarsVariety.js';
import {
  COZY_BATCH1_TEMPLATES, COZY_BATCH1_COLOR_SCHEMES,
} from '../templates/cozyVariety.js';
import {
  FOOD_BATCH4_TEMPLATES, FOOD_BATCH4_COLOR_SCHEMES,
} from '../templates/foodVariety4.js';
import {
  COZY_BATCH2_TEMPLATES, COZY_BATCH2_COLOR_SCHEMES,
} from '../templates/cozyVariety2.js';
import {
  FOOD_BATCH5_TEMPLATES, FOOD_BATCH5_COLOR_SCHEMES,
} from '../templates/foodVariety5.js';
import {
  COZY_BATCH3_TEMPLATES, COZY_BATCH3_COLOR_SCHEMES,
} from '../templates/cozyVariety3.js';
import {
  DUNGEON_BATCH2_TEMPLATES, DUNGEON_BATCH2_COLOR_SCHEMES,
} from '../templates/dungeonVariety2.js';
import {
  COZY_BATCH4_TEMPLATES, COZY_BATCH4_COLOR_SCHEMES,
} from '../templates/cozyVariety4.js';
import {
  LIBRARY_BATCH1_TEMPLATES, LIBRARY_BATCH1_COLOR_SCHEMES,
} from '../templates/libraryVariety.js';
import {
  LIBRARY_BATCH2_TEMPLATES, LIBRARY_BATCH2_COLOR_SCHEMES,
} from '../templates/libraryVariety2.js';
import {
  LIBRARY_BATCH3_TEMPLATES, LIBRARY_BATCH3_COLOR_SCHEMES,
} from '../templates/libraryVariety3.js';
import {
  LIBRARY_BATCH4_TEMPLATES, LIBRARY_BATCH4_COLOR_SCHEMES,
} from '../templates/libraryVariety4.js';
import {
  LIBRARY_BATCH5_TEMPLATES, LIBRARY_BATCH5_COLOR_SCHEMES,
} from '../templates/libraryVariety5.js';
import {
  LOFI_BATCH1_TEMPLATES, LOFI_BATCH1_COLOR_SCHEMES,
} from '../templates/lofiStudyVariety.js';
import {
  LOFI_BATCH2_TEMPLATES, LOFI_BATCH2_COLOR_SCHEMES,
} from '../templates/lofiStudyVariety2.js';
import {
  LOFI_BATCH3_TEMPLATES, LOFI_BATCH3_COLOR_SCHEMES,
} from '../templates/lofiStudyVariety3.js';
import {
  MUSIC_BATCH1_TEMPLATES, MUSIC_BATCH1_COLOR_SCHEMES,
} from '../templates/musicVariety.js';
import {
  CRAFTING_BATCH1_TEMPLATES, CRAFTING_BATCH1_COLOR_SCHEMES,
} from '../templates/craftingVariety.js';
import {
  MUSIC_BATCH2_TEMPLATES, MUSIC_BATCH2_COLOR_SCHEMES,
} from '../templates/musicVariety2.js';
import {
  MUSIC_BATCH3_TEMPLATES, MUSIC_BATCH3_COLOR_SCHEMES,
} from '../templates/musicVariety3.js';
import {
  MUSIC_BATCH4_TEMPLATES, MUSIC_BATCH4_COLOR_SCHEMES,
} from '../templates/musicVariety4.js';
import {
  MUSIC_BATCH5_TEMPLATES, MUSIC_BATCH5_COLOR_SCHEMES,
} from '../templates/musicVariety5.js';
import {
  CRAFTING_BATCH2_TEMPLATES, CRAFTING_BATCH2_COLOR_SCHEMES,
} from '../templates/craftingVariety2.js';
import {
  CRAFTING_BATCH3_TEMPLATES, CRAFTING_BATCH3_COLOR_SCHEMES,
} from '../templates/craftingVariety3.js';
import {
  CRAFTING_BATCH4_TEMPLATES, CRAFTING_BATCH4_COLOR_SCHEMES,
} from '../templates/craftingVariety4.js';
import {
  CRAFTING_BATCH5_TEMPLATES, CRAFTING_BATCH5_COLOR_SCHEMES,
} from '../templates/craftingVariety5.js';
import {
  WEAPON_STAFF_BATCH1_TEMPLATES, WEAPON_STAFF_BATCH1_COLOR_SCHEMES,
} from '../templates/weaponStaffVariety.js';
import {
  WEAPON_STAFF_BATCH2_TEMPLATES, WEAPON_STAFF_BATCH2_COLOR_SCHEMES,
} from '../templates/weaponStaffVariety2.js';
import {
  WEAPON_STAFF_BATCH3_TEMPLATES, WEAPON_STAFF_BATCH3_COLOR_SCHEMES,
} from '../templates/weaponStaffVariety3.js';
import {
  WEAPON_STAFF_BATCH4_TEMPLATES, WEAPON_STAFF_BATCH4_COLOR_SCHEMES,
} from '../templates/weaponStaffVariety4.js';
import {
  WEAPON_STAFF_BATCH5_TEMPLATES, WEAPON_STAFF_BATCH5_COLOR_SCHEMES,
} from '../templates/weaponStaffVariety5.js';
import {
  ARMOR_HELMETS_TEMPLATES, ARMOR_HELMETS_COLOR_SCHEMES,
} from '../templates/armorHelmets.js';
import {
  ARMOR_CHEST_TEMPLATES, ARMOR_CHEST_COLOR_SCHEMES,
} from '../templates/armorChest.js';
import {
  ARMOR_ARMS_TEMPLATES, ARMOR_ARMS_COLOR_SCHEMES,
} from '../templates/armorArms.js';
import {
  ARMOR_LEGS_TEMPLATES, ARMOR_LEGS_COLOR_SCHEMES,
} from '../templates/armorLegs.js';
import {
  ARMOR_SHIELDS_TEMPLATES, ARMOR_SHIELDS_COLOR_SCHEMES,
} from '../templates/armorShields.js';
import {
  BUILDING_BATCH4_TEMPLATES, BUILDING_BATCH4_COLOR_SCHEMES,
} from '../templates/buildingsVariety4.js';
import {
  BUILDING_BATCH5_TEMPLATES, BUILDING_BATCH5_COLOR_SCHEMES,
} from '../templates/buildingsVariety5.js';
import {
  SUPER_UI_BATCH1_TEMPLATES, SUPER_UI_BATCH1_COLOR_SCHEMES,
} from '../templates/superUiVariety.js';
import {
  SUPER_UI_BATCH2_TEMPLATES, SUPER_UI_BATCH2_COLOR_SCHEMES,
} from '../templates/superUiVariety2.js';
import {
  SUPER_UI_BATCH3_TEMPLATES, SUPER_UI_BATCH3_COLOR_SCHEMES,
} from '../templates/superUiVariety3.js';
import {
  SUPER_UI_BATCH4_TEMPLATES, SUPER_UI_BATCH4_COLOR_SCHEMES,
} from '../templates/superUiVariety4.js';
import {
  SUPER_UI_BATCH5_TEMPLATES, SUPER_UI_BATCH5_COLOR_SCHEMES,
} from '../templates/superUiVariety5.js';
import {
  BAKERY_BATCH1_TEMPLATES, BAKERY_BATCH1_COLOR_SCHEMES,
} from '../templates/bakeryVariety.js';
import {
  BAKERY_BATCH2_TEMPLATES, BAKERY_BATCH2_COLOR_SCHEMES,
} from '../templates/bakeryVariety2.js';
import {
  BAKERY_BATCH3_TEMPLATES, BAKERY_BATCH3_COLOR_SCHEMES,
} from '../templates/bakeryVariety3.js';
import {
  BAKERY_BATCH4_TEMPLATES, BAKERY_BATCH4_COLOR_SCHEMES,
} from '../templates/bakeryVariety4.js';
import {
  BAKERY_BATCH5_TEMPLATES, BAKERY_BATCH5_COLOR_SCHEMES,
} from '../templates/bakeryVariety5.js';
import {
  FRUITS_BATCH1_TEMPLATES, FRUITS_BATCH1_COLOR_SCHEMES,
} from '../templates/fruitsVariety.js';
import {
  FRUITS_BATCH2_TEMPLATES, FRUITS_BATCH2_COLOR_SCHEMES,
} from '../templates/fruitsVariety2.js';
import {
  VEGGIES_BATCH1_TEMPLATES, VEGGIES_BATCH1_COLOR_SCHEMES,
} from '../templates/veggiesVariety.js';
import {
  VEGGIES_BATCH2_TEMPLATES, VEGGIES_BATCH2_COLOR_SCHEMES,
} from '../templates/veggiesVariety2.js';
import {
  VEGGIES_BATCH3_TEMPLATES, VEGGIES_BATCH3_COLOR_SCHEMES,
} from '../templates/veggiesVariety3.js';
import {
  YATAI_BATCH1_TEMPLATES, YATAI_BATCH1_COLOR_SCHEMES,
} from '../templates/yataiVariety.js';
import {
  YATAI_BATCH2_TEMPLATES, YATAI_BATCH2_COLOR_SCHEMES,
} from '../templates/yataiVariety2.js';
import {
  YATAI_BATCH3_TEMPLATES, YATAI_BATCH3_COLOR_SCHEMES,
} from '../templates/yataiVariety3.js';
import {
  YATAI_BATCH4_TEMPLATES, YATAI_BATCH4_COLOR_SCHEMES,
} from '../templates/yataiVariety4.js';
import {
  YATAI_BATCH5_TEMPLATES, YATAI_BATCH5_COLOR_SCHEMES,
} from '../templates/yataiVariety5.js';
import {
  MANGAKA_BATCH1_TEMPLATES, MANGAKA_BATCH1_COLOR_SCHEMES,
} from '../templates/mangakaVariety.js';
import {
  MANGAKA_BATCH2_TEMPLATES, MANGAKA_BATCH2_COLOR_SCHEMES,
} from '../templates/mangakaVariety2.js';
import {
  MANGAKA_BATCH3_TEMPLATES, MANGAKA_BATCH3_COLOR_SCHEMES,
} from '../templates/mangakaVariety3.js';
import {
  MANGAKA_BATCH4_TEMPLATES, MANGAKA_BATCH4_COLOR_SCHEMES,
} from '../templates/mangakaVariety4.js';
import {
  MANGAKA_BATCH5_TEMPLATES, MANGAKA_BATCH5_COLOR_SCHEMES,
} from '../templates/mangakaVariety5.js';
import {
  TOKYO_BATCH1_TEMPLATES, TOKYO_BATCH1_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety.js';
import {
  TOKYO_BATCH2_TEMPLATES, TOKYO_BATCH2_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety2.js';
import {
  TOKYO_BATCH3_TEMPLATES, TOKYO_BATCH3_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety3.js';
import {
  TOKYO_BATCH4_TEMPLATES, TOKYO_BATCH4_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety4.js';
import {
  TOKYO_BATCH5_TEMPLATES, TOKYO_BATCH5_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety5.js';
import {
  TOKYO_BATCH6_TEMPLATES, TOKYO_BATCH6_COLOR_SCHEMES,
} from '../templates/tokyoCityVariety6.js';
import {
  GUNS_BATCH1_TEMPLATES, GUNS_BATCH1_COLOR_SCHEMES,
} from '../templates/gunsVariety.js';
import {
  GUNS_BATCH2_TEMPLATES, GUNS_BATCH2_COLOR_SCHEMES,
} from '../templates/gunsVariety2.js';
import {
  GUNS_BATCH3_TEMPLATES, GUNS_BATCH3_COLOR_SCHEMES,
} from '../templates/gunsVariety3.js';
import {
  GUNS_BATCH4_TEMPLATES, GUNS_BATCH4_COLOR_SCHEMES,
} from '../templates/gunsVariety4.js';
import {
  GUNS_BATCH5_TEMPLATES, GUNS_BATCH5_COLOR_SCHEMES,
} from '../templates/gunsVariety5.js';
import {
  LIBERAL_ARTS_BATCH1_TEMPLATES, LIBERAL_ARTS_BATCH1_COLOR_SCHEMES,
} from '../templates/liberalArtsVariety.js';
import {
  LIBERAL_ARTS_BATCH2_TEMPLATES, LIBERAL_ARTS_BATCH2_COLOR_SCHEMES,
} from '../templates/liberalArtsVariety2.js';
import {
  LIBERAL_ARTS_BATCH3_TEMPLATES, LIBERAL_ARTS_BATCH3_COLOR_SCHEMES,
} from '../templates/liberalArtsVariety3.js';
import {
  LIBERAL_ARTS_BATCH4_TEMPLATES, LIBERAL_ARTS_BATCH4_COLOR_SCHEMES,
} from '../templates/liberalArtsVariety4.js';
import {
  LIBERAL_ARTS_BATCH5_TEMPLATES, LIBERAL_ARTS_BATCH5_COLOR_SCHEMES,
} from '../templates/liberalArtsVariety5.js';
import {
  PRO_SHOWCASE_TEMPLATES, PRO_SHOWCASE_COLOR_SCHEMES,
} from '../templates/_proShowcase.js';
import {
  PRO_PROPS_TEMPLATES, PRO_PROPS_COLOR_SCHEMES,
} from '../templates/_proProps.js';
import {
  RPG_TEST_TEMPLATES, RPG_TEST_COLOR_SCHEMES,
} from '../templates/_rpgTest.js';
import {
  ROGUELIKE_SWORDS_32_TEMPLATES, ROGUELIKE_SWORDS_32_COLOR_SCHEMES,
} from '../templates/roguelikeWeapons32.js';
import {
  DUNGEON_STORAGE_32_TEMPLATES, DUNGEON_STORAGE_32_COLOR_SCHEMES,
} from '../templates/dungeonStorage32.js';
import {
  DUNGEON_LIGHTS_32_TEMPLATES, DUNGEON_LIGHTS_32_COLOR_SCHEMES,
} from '../templates/dungeonLights32.js';
import {
  DUNGEON_PICKUPS_32_TEMPLATES, DUNGEON_PICKUPS_32_COLOR_SCHEMES,
} from '../templates/dungeonPickups32.js';
import {
  DUNGEON_INTERACTIVE_32_TEMPLATES, DUNGEON_INTERACTIVE_32_COLOR_SCHEMES,
} from '../templates/dungeonInteractive32.js';
import {
  DUNGEON_DECOR_32_TEMPLATES, DUNGEON_DECOR_32_COLOR_SCHEMES,
} from '../templates/dungeonDecor32.js';
import {
  COZY_POTIONS_32_TEMPLATES, COZY_POTIONS_32_COLOR_SCHEMES,
} from '../templates/cozyPotions32.js';
import {
  COZY_BOOKS_32_TEMPLATES, COZY_BOOKS_32_COLOR_SCHEMES,
} from '../templates/cozyBooks32.js';
import {
  COZY_COFFEE_32_TEMPLATES, COZY_COFFEE_32_COLOR_SCHEMES,
} from '../templates/cozyCoffee32.js';
import {
  COZY_RAMEN_32_TEMPLATES, COZY_RAMEN_32_COLOR_SCHEMES,
} from '../templates/cozyRamen32.js';
import {
  COZY_FOOD_32_TEMPLATES, COZY_FOOD_32_COLOR_SCHEMES,
} from '../templates/cozyFood32.js';
import {
  ROGUELIKE_SHIELDS_32_TEMPLATES, ROGUELIKE_SHIELDS_32_COLOR_SCHEMES,
} from '../templates/roguelikeShields32.js';
import {
  ROGUELIKE_BOWS_32_TEMPLATES, ROGUELIKE_BOWS_32_COLOR_SCHEMES,
} from '../templates/roguelikeBows32.js';
import {
  ROGUELIKE_STAFFS_32_TEMPLATES, ROGUELIKE_STAFFS_32_COLOR_SCHEMES,
} from '../templates/roguelikeStaffs32.js';
import {
  ROGUELIKE_EXOTIC_32_TEMPLATES, ROGUELIKE_EXOTIC_32_COLOR_SCHEMES,
} from '../templates/roguelikeExotic32.js';
import {
  RPG_BARS_32_TEMPLATES, RPG_BARS_32_COLOR_SCHEMES,
} from '../templates/rpgBars32.js';
import {
  RPG_STATUS_32_TEMPLATES, RPG_STATUS_32_COLOR_SCHEMES,
} from '../templates/rpgStatus32.js';
import {
  RPG_SLOTS_32_TEMPLATES, RPG_SLOTS_32_COLOR_SCHEMES,
} from '../templates/rpgSlots32.js';
import {
  RPG_BUTTONS_32_TEMPLATES, RPG_BUTTONS_32_COLOR_SCHEMES,
} from '../templates/rpgButtons32.js';
import {
  RPG_HUD_32_TEMPLATES, RPG_HUD_32_COLOR_SCHEMES,
} from '../templates/rpgHud32.js';
import {
  LIBERAL_ARTS_32_BATCH1_TEMPLATES, LIBERAL_ARTS_32_BATCH1_COLOR_SCHEMES,
} from '../templates/liberalArts32.js';
import {
  LIBERAL_ARTS_32_BATCH2_TEMPLATES, LIBERAL_ARTS_32_BATCH2_COLOR_SCHEMES,
} from '../templates/liberalArts32v2.js';
import {
  LIBERAL_ARTS_32_BATCH3_TEMPLATES, LIBERAL_ARTS_32_BATCH3_COLOR_SCHEMES,
} from '../templates/liberalArts32v3.js';
import {
  LIBERAL_ARTS_32_BATCH4_TEMPLATES, LIBERAL_ARTS_32_BATCH4_COLOR_SCHEMES,
} from '../templates/liberalArts32v4.js';
import {
  LIBERAL_ARTS_32_BATCH5_TEMPLATES, LIBERAL_ARTS_32_BATCH5_COLOR_SCHEMES,
} from '../templates/liberalArts32v5.js';
import {
  GAME_ICONS_32_BATCH1_TEMPLATES, GAME_ICONS_32_BATCH1_COLOR_SCHEMES,
} from '../templates/gameIcons32.js';
import {
  GAME_ICONS_32_BATCH2_TEMPLATES, GAME_ICONS_32_BATCH2_COLOR_SCHEMES,
} from '../templates/gameIcons32v2.js';
import {
  GAME_ICONS_32_BATCH3_TEMPLATES, GAME_ICONS_32_BATCH3_COLOR_SCHEMES,
} from '../templates/gameIcons32v3.js';
import {
  GAME_ICONS_32_BATCH4_TEMPLATES, GAME_ICONS_32_BATCH4_COLOR_SCHEMES,
} from '../templates/gameIcons32v4.js';
import {
  GAME_ICONS_32_BATCH5_TEMPLATES, GAME_ICONS_32_BATCH5_COLOR_SCHEMES,
} from '../templates/gameIcons32v5.js';
import {
  RETRO_COMPUTING_32_BATCH1_TEMPLATES, RETRO_COMPUTING_32_BATCH1_COLOR_SCHEMES,
} from '../templates/retroComputing32.js';
import {
  RETRO_COMPUTING_32_BATCH2_TEMPLATES, RETRO_COMPUTING_32_BATCH2_COLOR_SCHEMES,
} from '../templates/retroComputing32v2.js';
import {
  RETRO_COMPUTING_32_BATCH3_TEMPLATES, RETRO_COMPUTING_32_BATCH3_COLOR_SCHEMES,
} from '../templates/retroComputing32v3.js';
import {
  RETRO_COMPUTING_32_BATCH4_TEMPLATES, RETRO_COMPUTING_32_BATCH4_COLOR_SCHEMES,
} from '../templates/retroComputing32v4.js';
import {
  RETRO_COMPUTING_32_BATCH5_TEMPLATES, RETRO_COMPUTING_32_BATCH5_COLOR_SCHEMES,
} from '../templates/retroComputing32v5.js';
import {
  RETRO_COMPUTING_32_FIX_TEMPLATES, RETRO_COMPUTING_32_FIX_COLOR_SCHEMES,
} from '../templates/retroComputingFix32.js';
import {
  DUNGEON_CREATURES_32_BATCH1_TEMPLATES, DUNGEON_CREATURES_32_BATCH1_COLOR_SCHEMES,
} from '../templates/dungeonCreatures32.js';
import {
  DUNGEON_CREATURES_32_BATCH2_TEMPLATES, DUNGEON_CREATURES_32_BATCH2_COLOR_SCHEMES,
} from '../templates/dungeonCreatures32v2.js';
import {
  DUNGEON_CREATURES_32_BATCH3_TEMPLATES, DUNGEON_CREATURES_32_BATCH3_COLOR_SCHEMES,
} from '../templates/dungeonCreatures32v3.js';
import {
  DUNGEON_CREATURES_32_BATCH4_TEMPLATES, DUNGEON_CREATURES_32_BATCH4_COLOR_SCHEMES,
} from '../templates/dungeonCreatures32v4.js';
import {
  DUNGEON_CREATURES_32_BATCH5_TEMPLATES, DUNGEON_CREATURES_32_BATCH5_COLOR_SCHEMES,
} from '../templates/dungeonCreatures32v5.js';
import {
  EDITOR_ICONS_BATCH1_TEMPLATES, EDITOR_ICONS_BATCH1_COLOR_SCHEMES,
} from '../templates/editorIcons32.js';
import {
  EDITOR_ICONS_BATCH2_TEMPLATES, EDITOR_ICONS_BATCH2_COLOR_SCHEMES,
} from '../templates/editorIcons32v2.js';

// Merged registries (all template sources — 16x16 only, ~295+ templates)
const ALL_TEMPLATES: Record<string, SpriteTemplate> = {
  ...TEMPLATES, ...GAME_TEMPLATES,
  ...CREATURE_TEMPLATES, ...ITEM_TEMPLATES, ...ITEM_VARIETY_TEMPLATES,
  ...ENVIRONMENT_TEMPLATES, ...UI_TEMPLATES, ...COZY_SHOP_UI_TEMPLATES, ...EFFECT_TEMPLATES,
  ...DUNGEON_TEMPLATES, ...EQUIPMENT_TEMPLATES, ...FURNITURE_TEMPLATES,
  ...RPG_UI_TEMPLATES, ...RPG_UI_VARIETY_TEMPLATES, ...NATURE_TEMPLATES,
  ...ENEMY_TEMPLATES, ...BOSS_TEMPLATES,
  ...NPC_TEMPLATES, ...FOOD_TEMPLATES, ...BIOME_TEMPLATES,
  ...VEHICLE_TEMPLATES,
  ...CHARACTER_VARIANT_TEMPLATES,
  ...PROP_TEMPLATES,
  ...ANIMATION_16_TEMPLATES,
  ...PLANT_TEMPLATES,
  ...PLANT_BATCH1_TEMPLATES,
  ...BUILDING_TEMPLATES,
  ...CREATURE_BATCH1_TEMPLATES,
  ...ENEMY_BATCH1_TEMPLATES,
  ...BUILDING_BATCH1_TEMPLATES,
  ...EFFECT_BATCH1_TEMPLATES,
  ...FOOD_BATCH1_TEMPLATES,
  ...BOSS_BATCH1_TEMPLATES,
  ...VEHICLE_BATCH1_TEMPLATES,
  ...CHARACTER_BATCH1_TEMPLATES,
  ...FURNITURE_BATCH1_TEMPLATES,
  ...UI_VARIETY_TEMPLATES,
  ...CREATURE_BATCH2_TEMPLATES,
  ...EFFECT_BATCH2_TEMPLATES,
  ...BUILDING_BATCH2_TEMPLATES,
  ...FOOD_BATCH2_TEMPLATES,
  ...BIOME_VARIETY_TEMPLATES,
  ...ENVIRONMENT_VARIETY_TEMPLATES,
  ...NATURE_VARIETY_TEMPLATES,
  ...CREATURE_BATCH3_TEMPLATES,
  ...ENEMY_BATCH2_TEMPLATES,
  ...ENEMY_BATCH3_TEMPLATES,
  ...BOSS_BATCH2_TEMPLATES,
  ...VEHICLE_BATCH2_TEMPLATES,
  ...EQUIPMENT_VARIETY_TEMPLATES,
  ...FOOD_BATCH3_TEMPLATES,
  ...FURNITURE_BATCH2_TEMPLATES,
  ...EFFECT_BATCH3_TEMPLATES,
  ...BUILDING_BATCH3_TEMPLATES,
  ...MODERN_TECH_TEMPLATES,
  ...RETRO_TECH_TEMPLATES,
  ...ITEM_BATCH2_TEMPLATES,
  ...EQUIPMENT_BATCH2_TEMPLATES,
  ...WEAPONS_CLASSIC_TEMPLATES,
  ...CHARACTER_BATCH2_TEMPLATES,
  ...CHARACTER_BATCH3_TEMPLATES,
  ...GAME_INSPIRED_BATCH1_TEMPLATES,
  ...CHAR_VARIANT_BATCH1_TEMPLATES,
  ...MODERN_TECH_BATCH1_TEMPLATES,
  ...MODERN_TECH_BATCH2_TEMPLATES,
  ...MODERN_TECH_BATCH3_TEMPLATES,
  ...MODERN_TECH_BATCH4_TEMPLATES,
  ...EFFECT_BATCH4_TEMPLATES,
  ...EFFECT_BATCH5_TEMPLATES,
  ...RETRO_TECH_BATCH1_TEMPLATES,
  ...RETRO_TECH_BATCH2_TEMPLATES,
  ...RETRO_TECH_BATCH3_TEMPLATES,
  ...RETRO_TECH_BATCH4_TEMPLATES,
  ...VEHICLE_BATCH3_TEMPLATES,
  ...VEHICLE_BATCH4_TEMPLATES,
  ...VEHICLE_BATCH5_TEMPLATES,
  ...DUNGEON_BATCH1_TEMPLATES,
  ...FURNITURE_BATCH3_TEMPLATES,
  ...EFFECT_BATCH6_TEMPLATES,
  ...UI_BARS_TEMPLATES,
  ...COZY_BATCH1_TEMPLATES,
  ...FOOD_BATCH4_TEMPLATES,
  ...COZY_BATCH2_TEMPLATES,
  ...COZY_BATCH3_TEMPLATES,
  ...FOOD_BATCH5_TEMPLATES,
  ...DUNGEON_BATCH2_TEMPLATES,
  ...DUNGEON_TILES_BATCH1_TEMPLATES,
  ...DUNGEON_TILES_BATCH2_TEMPLATES,
  ...DUNGEON_TILES_BATCH3_TEMPLATES,
  ...DUNGEON_TILES_BATCH4_TEMPLATES,
  ...DUNGEON_TILES_BATCH5_TEMPLATES,
  ...COZY_BATCH4_TEMPLATES,
  ...LIBRARY_BATCH1_TEMPLATES,
  ...LIBRARY_BATCH2_TEMPLATES,
  ...LIBRARY_BATCH3_TEMPLATES,
  ...LIBRARY_BATCH4_TEMPLATES,
  ...LIBRARY_BATCH5_TEMPLATES,
  ...LOFI_BATCH1_TEMPLATES,
  ...LOFI_BATCH2_TEMPLATES,
  ...LOFI_BATCH3_TEMPLATES,
  ...MUSIC_BATCH1_TEMPLATES,
  ...MUSIC_BATCH2_TEMPLATES,
  ...MUSIC_BATCH3_TEMPLATES,
  ...MUSIC_BATCH4_TEMPLATES,
  ...MUSIC_BATCH5_TEMPLATES,
  ...CRAFTING_BATCH1_TEMPLATES,
  ...CRAFTING_BATCH2_TEMPLATES,
  ...CRAFTING_BATCH3_TEMPLATES,
  ...CRAFTING_BATCH4_TEMPLATES,
  ...CRAFTING_BATCH5_TEMPLATES,
  ...WEAPON_STAFF_BATCH1_TEMPLATES,
  ...WEAPON_STAFF_BATCH2_TEMPLATES,
  ...WEAPON_STAFF_BATCH3_TEMPLATES,
  ...WEAPON_STAFF_BATCH4_TEMPLATES,
  ...WEAPON_STAFF_BATCH5_TEMPLATES,
  ...ARMOR_HELMETS_TEMPLATES,
  ...ARMOR_CHEST_TEMPLATES,
  ...ARMOR_ARMS_TEMPLATES,
  ...ARMOR_LEGS_TEMPLATES,
  ...ARMOR_SHIELDS_TEMPLATES,
  ...BUILDING_BATCH4_TEMPLATES,
  ...BUILDING_BATCH5_TEMPLATES,
  ...SUPER_UI_BATCH1_TEMPLATES,
  ...SUPER_UI_BATCH2_TEMPLATES,
  ...SUPER_UI_BATCH3_TEMPLATES,
  ...SUPER_UI_BATCH4_TEMPLATES,
  ...SUPER_UI_BATCH5_TEMPLATES,
  ...BAKERY_BATCH1_TEMPLATES,
  ...BAKERY_BATCH2_TEMPLATES,
  ...BAKERY_BATCH3_TEMPLATES,
  ...BAKERY_BATCH4_TEMPLATES,
  ...BAKERY_BATCH5_TEMPLATES,
  ...FRUITS_BATCH1_TEMPLATES,
  ...FRUITS_BATCH2_TEMPLATES,
  ...VEGGIES_BATCH1_TEMPLATES,
  ...VEGGIES_BATCH2_TEMPLATES,
  ...VEGGIES_BATCH3_TEMPLATES,
  ...YATAI_BATCH1_TEMPLATES,
  ...YATAI_BATCH2_TEMPLATES,
  ...YATAI_BATCH3_TEMPLATES,
  ...YATAI_BATCH4_TEMPLATES,
  ...YATAI_BATCH5_TEMPLATES,
  ...MANGAKA_BATCH1_TEMPLATES,
  ...MANGAKA_BATCH2_TEMPLATES,
  ...MANGAKA_BATCH3_TEMPLATES,
  ...MANGAKA_BATCH4_TEMPLATES,
  ...MANGAKA_BATCH5_TEMPLATES,
  ...TOKYO_BATCH1_TEMPLATES,
  ...TOKYO_BATCH2_TEMPLATES,
  ...TOKYO_BATCH3_TEMPLATES,
  ...TOKYO_BATCH4_TEMPLATES,
  ...TOKYO_BATCH5_TEMPLATES,
  ...TOKYO_BATCH6_TEMPLATES,
  ...GUNS_BATCH1_TEMPLATES,
  ...GUNS_BATCH2_TEMPLATES,
  ...GUNS_BATCH3_TEMPLATES,
  ...GUNS_BATCH4_TEMPLATES,
  ...GUNS_BATCH5_TEMPLATES,
  ...LIBERAL_ARTS_BATCH1_TEMPLATES,
  ...LIBERAL_ARTS_BATCH2_TEMPLATES,
  ...LIBERAL_ARTS_BATCH3_TEMPLATES,
  ...LIBERAL_ARTS_BATCH4_TEMPLATES,
  ...LIBERAL_ARTS_BATCH5_TEMPLATES,
  ...PRO_SHOWCASE_TEMPLATES,
  ...PRO_PROPS_TEMPLATES,
  ...RPG_TEST_TEMPLATES,
  ...ROGUELIKE_SWORDS_32_TEMPLATES,
  ...ROGUELIKE_SHIELDS_32_TEMPLATES,
  ...ROGUELIKE_BOWS_32_TEMPLATES,
  ...ROGUELIKE_STAFFS_32_TEMPLATES,
  ...ROGUELIKE_EXOTIC_32_TEMPLATES,
  ...DUNGEON_STORAGE_32_TEMPLATES,
  ...DUNGEON_LIGHTS_32_TEMPLATES,
  ...DUNGEON_PICKUPS_32_TEMPLATES,
  ...DUNGEON_INTERACTIVE_32_TEMPLATES,
  ...DUNGEON_DECOR_32_TEMPLATES,
  ...COZY_POTIONS_32_TEMPLATES,
  ...COZY_BOOKS_32_TEMPLATES,
  ...COZY_COFFEE_32_TEMPLATES,
  ...COZY_RAMEN_32_TEMPLATES,
  ...COZY_FOOD_32_TEMPLATES,
  ...RPG_BARS_32_TEMPLATES,
  ...RPG_STATUS_32_TEMPLATES,
  ...RPG_SLOTS_32_TEMPLATES,
  ...RPG_BUTTONS_32_TEMPLATES,
  ...RPG_HUD_32_TEMPLATES,
  ...LIBERAL_ARTS_32_BATCH1_TEMPLATES,
  ...LIBERAL_ARTS_32_BATCH2_TEMPLATES,
  ...LIBERAL_ARTS_32_BATCH3_TEMPLATES,
  ...LIBERAL_ARTS_32_BATCH4_TEMPLATES,
  ...LIBERAL_ARTS_32_BATCH5_TEMPLATES,
  ...GAME_ICONS_32_BATCH1_TEMPLATES,
  ...GAME_ICONS_32_BATCH2_TEMPLATES,
  ...GAME_ICONS_32_BATCH3_TEMPLATES,
  ...GAME_ICONS_32_BATCH4_TEMPLATES,
  ...GAME_ICONS_32_BATCH5_TEMPLATES,
  ...RETRO_COMPUTING_32_BATCH1_TEMPLATES,
  ...RETRO_COMPUTING_32_BATCH2_TEMPLATES,
  ...RETRO_COMPUTING_32_BATCH3_TEMPLATES,
  ...RETRO_COMPUTING_32_BATCH4_TEMPLATES,
  ...RETRO_COMPUTING_32_BATCH5_TEMPLATES,
  ...RETRO_COMPUTING_32_FIX_TEMPLATES,
  ...DUNGEON_CREATURES_32_BATCH1_TEMPLATES,
  ...DUNGEON_CREATURES_32_BATCH2_TEMPLATES,
  ...DUNGEON_CREATURES_32_BATCH3_TEMPLATES,
  ...DUNGEON_CREATURES_32_BATCH4_TEMPLATES,
  ...DUNGEON_CREATURES_32_BATCH5_TEMPLATES,
  ...EDITOR_ICONS_BATCH1_TEMPLATES,
  ...EDITOR_ICONS_BATCH2_TEMPLATES,
};
const ALL_SCHEMES: Record<string, ColorScheme> = {
  ...COLOR_SCHEMES, ...GAME_COLOR_SCHEMES,
  ...CREATURE_COLOR_SCHEMES, ...ITEM_COLOR_SCHEMES, ...ITEM_VARIETY_COLOR_SCHEMES,
  ...ENVIRONMENT_COLOR_SCHEMES, ...UI_COLOR_SCHEMES, ...COZY_SHOP_UI_COLOR_SCHEMES, ...EFFECT_COLOR_SCHEMES,
  ...DUNGEON_COLOR_SCHEMES, ...EQUIPMENT_COLOR_SCHEMES, ...FURNITURE_COLOR_SCHEMES,
  ...RPG_UI_COLOR_SCHEMES, ...RPG_UI_VARIETY_COLOR_SCHEMES, ...NATURE_COLOR_SCHEMES,
  ...ENEMY_COLOR_SCHEMES, ...BOSS_COLOR_SCHEMES,
  ...NPC_COLOR_SCHEMES, ...FOOD_COLOR_SCHEMES, ...BIOME_COLOR_SCHEMES,
  ...VEHICLE_COLOR_SCHEMES,
  ...CHARACTER_VARIANT_COLOR_SCHEMES,
  ...PROP_COLOR_SCHEMES,
  ...ANIMATION_16_COLOR_SCHEMES,
  ...PLANT_COLOR_SCHEMES,
  ...PLANT_BATCH1_COLOR_SCHEMES,
  ...BUILDING_COLOR_SCHEMES,
  ...COLOR_VARIANT_SCHEMES,
  ...CREATURE_BATCH1_COLOR_SCHEMES,
  ...ENEMY_BATCH1_COLOR_SCHEMES,
  ...BUILDING_BATCH1_COLOR_SCHEMES,
  ...EFFECT_BATCH1_COLOR_SCHEMES,
  ...FOOD_BATCH1_COLOR_SCHEMES,
  ...BOSS_BATCH1_COLOR_SCHEMES,
  ...VEHICLE_BATCH1_COLOR_SCHEMES,
  ...CHARACTER_BATCH1_COLOR_SCHEMES,
  ...FURNITURE_BATCH1_COLOR_SCHEMES,
  ...UI_VARIETY_COLOR_SCHEMES,
  ...CREATURE_BATCH2_COLOR_SCHEMES,
  ...EFFECT_BATCH2_COLOR_SCHEMES,
  ...BUILDING_BATCH2_COLOR_SCHEMES,
  ...FOOD_BATCH2_COLOR_SCHEMES,
  ...BIOME_VARIETY_COLOR_SCHEMES,
  ...ENVIRONMENT_VARIETY_COLOR_SCHEMES,
  ...NATURE_VARIETY_COLOR_SCHEMES,
  ...CREATURE_BATCH3_COLOR_SCHEMES,
  ...ENEMY_BATCH2_COLOR_SCHEMES,
  ...ENEMY_BATCH3_COLOR_SCHEMES,
  ...BOSS_BATCH2_COLOR_SCHEMES,
  ...VEHICLE_BATCH2_COLOR_SCHEMES,
  ...EQUIPMENT_VARIETY_COLOR_SCHEMES,
  ...FOOD_BATCH3_COLOR_SCHEMES,
  ...FURNITURE_BATCH2_COLOR_SCHEMES,
  ...EFFECT_BATCH3_COLOR_SCHEMES,
  ...BUILDING_BATCH3_COLOR_SCHEMES,
  ...MODERN_TECH_COLOR_SCHEMES,
  ...RETRO_TECH_COLOR_SCHEMES,
  ...ITEM_BATCH2_COLOR_SCHEMES,
  ...EQUIPMENT_BATCH2_COLOR_SCHEMES,
  ...WEAPONS_CLASSIC_COLOR_SCHEMES,
  ...CHARACTER_BATCH2_COLOR_SCHEMES,
  ...CHARACTER_BATCH3_COLOR_SCHEMES,
  ...GAME_INSPIRED_BATCH1_COLOR_SCHEMES,
  ...CHAR_VARIANT_BATCH1_COLOR_SCHEMES,
  ...MODERN_TECH_BATCH1_COLOR_SCHEMES,
  ...MODERN_TECH_BATCH2_COLOR_SCHEMES,
  ...MODERN_TECH_BATCH3_COLOR_SCHEMES,
  ...MODERN_TECH_BATCH4_COLOR_SCHEMES,
  ...EFFECT_BATCH4_COLOR_SCHEMES,
  ...EFFECT_BATCH5_COLOR_SCHEMES,
  ...RETRO_TECH_BATCH1_COLOR_SCHEMES,
  ...RETRO_TECH_BATCH2_COLOR_SCHEMES,
  ...RETRO_TECH_BATCH3_COLOR_SCHEMES,
  ...RETRO_TECH_BATCH4_COLOR_SCHEMES,
  ...VEHICLE_BATCH3_COLOR_SCHEMES,
  ...VEHICLE_BATCH4_COLOR_SCHEMES,
  ...VEHICLE_BATCH5_COLOR_SCHEMES,
  ...DUNGEON_BATCH1_COLOR_SCHEMES,
  ...FURNITURE_BATCH3_COLOR_SCHEMES,
  ...EFFECT_BATCH6_COLOR_SCHEMES,
  ...UI_BARS_COLOR_SCHEMES,
  ...COZY_BATCH1_COLOR_SCHEMES,
  ...FOOD_BATCH4_COLOR_SCHEMES,
  ...COZY_BATCH2_COLOR_SCHEMES,
  ...COZY_BATCH3_COLOR_SCHEMES,
  ...FOOD_BATCH5_COLOR_SCHEMES,
  ...DUNGEON_BATCH2_COLOR_SCHEMES,
  ...DUNGEON_TILES_BATCH1_COLOR_SCHEMES,
  ...DUNGEON_TILES_BATCH2_COLOR_SCHEMES,
  ...DUNGEON_TILES_BATCH3_COLOR_SCHEMES,
  ...DUNGEON_TILES_BATCH4_COLOR_SCHEMES,
  ...DUNGEON_TILES_BATCH5_COLOR_SCHEMES,
  ...COZY_BATCH4_COLOR_SCHEMES,
  ...LIBRARY_BATCH1_COLOR_SCHEMES,
  ...LIBRARY_BATCH2_COLOR_SCHEMES,
  ...LIBRARY_BATCH3_COLOR_SCHEMES,
  ...LIBRARY_BATCH4_COLOR_SCHEMES,
  ...LIBRARY_BATCH5_COLOR_SCHEMES,
  ...LOFI_BATCH1_COLOR_SCHEMES,
  ...LOFI_BATCH2_COLOR_SCHEMES,
  ...LOFI_BATCH3_COLOR_SCHEMES,
  ...MUSIC_BATCH1_COLOR_SCHEMES,
  ...MUSIC_BATCH2_COLOR_SCHEMES,
  ...MUSIC_BATCH3_COLOR_SCHEMES,
  ...MUSIC_BATCH4_COLOR_SCHEMES,
  ...MUSIC_BATCH5_COLOR_SCHEMES,
  ...CRAFTING_BATCH1_COLOR_SCHEMES,
  ...CRAFTING_BATCH2_COLOR_SCHEMES,
  ...CRAFTING_BATCH3_COLOR_SCHEMES,
  ...CRAFTING_BATCH4_COLOR_SCHEMES,
  ...CRAFTING_BATCH5_COLOR_SCHEMES,
  ...WEAPON_STAFF_BATCH1_COLOR_SCHEMES,
  ...WEAPON_STAFF_BATCH2_COLOR_SCHEMES,
  ...WEAPON_STAFF_BATCH3_COLOR_SCHEMES,
  ...WEAPON_STAFF_BATCH4_COLOR_SCHEMES,
  ...WEAPON_STAFF_BATCH5_COLOR_SCHEMES,
  ...ARMOR_HELMETS_COLOR_SCHEMES,
  ...ARMOR_CHEST_COLOR_SCHEMES,
  ...ARMOR_ARMS_COLOR_SCHEMES,
  ...ARMOR_LEGS_COLOR_SCHEMES,
  ...ARMOR_SHIELDS_COLOR_SCHEMES,
  ...BUILDING_BATCH4_COLOR_SCHEMES,
  ...BUILDING_BATCH5_COLOR_SCHEMES,
  ...SUPER_UI_BATCH1_COLOR_SCHEMES,
  ...SUPER_UI_BATCH2_COLOR_SCHEMES,
  ...SUPER_UI_BATCH3_COLOR_SCHEMES,
  ...SUPER_UI_BATCH4_COLOR_SCHEMES,
  ...SUPER_UI_BATCH5_COLOR_SCHEMES,
  ...BAKERY_BATCH1_COLOR_SCHEMES,
  ...BAKERY_BATCH2_COLOR_SCHEMES,
  ...BAKERY_BATCH3_COLOR_SCHEMES,
  ...BAKERY_BATCH4_COLOR_SCHEMES,
  ...BAKERY_BATCH5_COLOR_SCHEMES,
  ...FRUITS_BATCH1_COLOR_SCHEMES,
  ...FRUITS_BATCH2_COLOR_SCHEMES,
  ...VEGGIES_BATCH1_COLOR_SCHEMES,
  ...VEGGIES_BATCH2_COLOR_SCHEMES,
  ...VEGGIES_BATCH3_COLOR_SCHEMES,
  ...YATAI_BATCH1_COLOR_SCHEMES,
  ...YATAI_BATCH2_COLOR_SCHEMES,
  ...YATAI_BATCH3_COLOR_SCHEMES,
  ...YATAI_BATCH4_COLOR_SCHEMES,
  ...YATAI_BATCH5_COLOR_SCHEMES,
  ...MANGAKA_BATCH1_COLOR_SCHEMES,
  ...MANGAKA_BATCH2_COLOR_SCHEMES,
  ...MANGAKA_BATCH3_COLOR_SCHEMES,
  ...MANGAKA_BATCH4_COLOR_SCHEMES,
  ...MANGAKA_BATCH5_COLOR_SCHEMES,
  ...TOKYO_BATCH1_COLOR_SCHEMES,
  ...TOKYO_BATCH2_COLOR_SCHEMES,
  ...TOKYO_BATCH3_COLOR_SCHEMES,
  ...TOKYO_BATCH4_COLOR_SCHEMES,
  ...TOKYO_BATCH5_COLOR_SCHEMES,
  ...TOKYO_BATCH6_COLOR_SCHEMES,
  ...GUNS_BATCH1_COLOR_SCHEMES,
  ...GUNS_BATCH2_COLOR_SCHEMES,
  ...GUNS_BATCH3_COLOR_SCHEMES,
  ...GUNS_BATCH4_COLOR_SCHEMES,
  ...GUNS_BATCH5_COLOR_SCHEMES,
  ...LIBERAL_ARTS_BATCH1_COLOR_SCHEMES,
  ...LIBERAL_ARTS_BATCH2_COLOR_SCHEMES,
  ...LIBERAL_ARTS_BATCH3_COLOR_SCHEMES,
  ...LIBERAL_ARTS_BATCH4_COLOR_SCHEMES,
  ...LIBERAL_ARTS_BATCH5_COLOR_SCHEMES,
  ...PRO_SHOWCASE_COLOR_SCHEMES,
  ...PRO_PROPS_COLOR_SCHEMES,
  ...RPG_TEST_COLOR_SCHEMES,
  ...ROGUELIKE_SWORDS_32_COLOR_SCHEMES,
  ...ROGUELIKE_SHIELDS_32_COLOR_SCHEMES,
  ...ROGUELIKE_BOWS_32_COLOR_SCHEMES,
  ...ROGUELIKE_STAFFS_32_COLOR_SCHEMES,
  ...ROGUELIKE_EXOTIC_32_COLOR_SCHEMES,
  ...DUNGEON_STORAGE_32_COLOR_SCHEMES,
  ...DUNGEON_LIGHTS_32_COLOR_SCHEMES,
  ...DUNGEON_PICKUPS_32_COLOR_SCHEMES,
  ...DUNGEON_INTERACTIVE_32_COLOR_SCHEMES,
  ...DUNGEON_DECOR_32_COLOR_SCHEMES,
  ...COZY_POTIONS_32_COLOR_SCHEMES,
  ...COZY_BOOKS_32_COLOR_SCHEMES,
  ...COZY_COFFEE_32_COLOR_SCHEMES,
  ...COZY_RAMEN_32_COLOR_SCHEMES,
  ...COZY_FOOD_32_COLOR_SCHEMES,
  ...RPG_BARS_32_COLOR_SCHEMES,
  ...RPG_STATUS_32_COLOR_SCHEMES,
  ...RPG_SLOTS_32_COLOR_SCHEMES,
  ...RPG_BUTTONS_32_COLOR_SCHEMES,
  ...RPG_HUD_32_COLOR_SCHEMES,
  ...LIBERAL_ARTS_32_BATCH1_COLOR_SCHEMES,
  ...LIBERAL_ARTS_32_BATCH2_COLOR_SCHEMES,
  ...LIBERAL_ARTS_32_BATCH3_COLOR_SCHEMES,
  ...LIBERAL_ARTS_32_BATCH4_COLOR_SCHEMES,
  ...LIBERAL_ARTS_32_BATCH5_COLOR_SCHEMES,
  ...GAME_ICONS_32_BATCH1_COLOR_SCHEMES,
  ...GAME_ICONS_32_BATCH2_COLOR_SCHEMES,
  ...GAME_ICONS_32_BATCH3_COLOR_SCHEMES,
  ...GAME_ICONS_32_BATCH4_COLOR_SCHEMES,
  ...GAME_ICONS_32_BATCH5_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_BATCH1_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_BATCH2_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_BATCH3_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_BATCH4_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_BATCH5_COLOR_SCHEMES,
  ...RETRO_COMPUTING_32_FIX_COLOR_SCHEMES,
  ...DUNGEON_CREATURES_32_BATCH1_COLOR_SCHEMES,
  ...DUNGEON_CREATURES_32_BATCH2_COLOR_SCHEMES,
  ...DUNGEON_CREATURES_32_BATCH3_COLOR_SCHEMES,
  ...DUNGEON_CREATURES_32_BATCH4_COLOR_SCHEMES,
  ...DUNGEON_CREATURES_32_BATCH5_COLOR_SCHEMES,
  ...EDITOR_ICONS_BATCH1_COLOR_SCHEMES,
  ...EDITOR_ICONS_BATCH2_COLOR_SCHEMES,
};

// ─── DB16 palette for color snapping ─────────────────────────
// All auto-generated colors (outline, shading fallback) are snapped to the
// nearest DB16 color so validate_sprite_quality palette checks pass 100%.
const DB16_RGBA: RGBA[] = [
  { r: 20,  g: 12,  b: 28,  a: 255 }, // #140c1c
  { r: 68,  g: 36,  b: 52,  a: 255 }, // #442434
  { r: 48,  g: 52,  b: 109, a: 255 }, // #30346d
  { r: 78,  g: 74,  b: 78,  a: 255 }, // #4e4a4e
  { r: 133, g: 76,  b: 48,  a: 255 }, // #854c30
  { r: 52,  g: 101, b: 36,  a: 255 }, // #346524
  { r: 208, g: 70,  b: 72,  a: 255 }, // #d04648
  { r: 117, g: 113, b: 97,  a: 255 }, // #757161
  { r: 89,  g: 125, b: 206, a: 255 }, // #597dce
  { r: 210, g: 125, b: 44,  a: 255 }, // #d27d2c
  { r: 133, g: 149, b: 161, a: 255 }, // #8595a1
  { r: 109, g: 170, b: 44,  a: 255 }, // #6daa2c
  { r: 210, g: 170, b: 153, a: 255 }, // #d2aa99
  { r: 109, g: 194, b: 202, a: 255 }, // #6dc2ca
  { r: 218, g: 212, b: 94,  a: 255 }, // #dad45e
  { r: 222, g: 238, b: 214, a: 255 }, // #deeed6
];

/** Snap an arbitrary RGBA color to the nearest DB16 color by Euclidean RGB distance. */
function snapToDb16(color: RGBA): RGBA {
  let bestDist = Infinity;
  let best: RGBA = DB16_RGBA[0];
  for (const db of DB16_RGBA) {
    const dr = color.r - db.r;
    const dg = color.g - db.g;
    const db_ = color.b - db.b;
    const dist = dr * dr + dg * dg + db_ * db_;
    if (dist < bestDist) {
      bestDist = dist;
      best = db;
    }
  }
  return { ...best, a: color.a };
}

// ─── Stardew/Earthbound-quality hue-shifting ─────────────────
// Shadows shift COOL (toward blue/purple), highlights shift WARM (toward yellow/amber).
// Saturation peaks at midtones and drops at extremes.
// NEVER produces pure black (#000000) or pure white (#ffffff) -
// always retains color character (Stardew Valley principle).

function clamp(v: number): number { return Math.max(0, Math.min(255, Math.round(v))); }

function hueShiftShadow(base: RGBA, intensity: number): RGBA {
  // Shift toward cooler (more blue, less red) + darken
  // Floor at 12 per channel to avoid pure black
  return {
    r: Math.max(12, clamp(base.r * (1 - intensity * 1.25))),
    g: Math.max(12, clamp(base.g * (1 - intensity * 1.05))),
    b: Math.max(18, clamp(base.b * (1 - intensity * 0.55))),  // blue preserved more
    a: base.a,
  };
}

function hueShiftHighlight(base: RGBA, intensity: number): RGBA {
  // Shift toward warmer (more red/yellow) + brighten
  // Cap at 245 per channel to avoid pure white
  return {
    r: Math.min(245, clamp(base.r + (255 - base.r) * intensity * 1.2)),
    g: Math.min(240, clamp(base.g + (255 - base.g) * intensity * 1.05)),
    b: Math.min(230, clamp(base.b + (255 - base.b) * intensity * 0.7)),  // blue capped lower = warmer
    a: base.a,
  };
}

// Bounce/reflected light: a subtle warm glow on shadow edges
// prevents dead-flat shadows (professional pixel art technique)
function bounceLight(shadow: RGBA, intensity: number): RGBA {
  return {
    r: clamp(shadow.r + 18 * intensity),
    g: clamp(shadow.g + 12 * intensity),
    b: clamp(shadow.b + 8 * intensity),
    a: shadow.a,
  };
}

// ─── Auto outline with selective coloring (selout) ────────────
// Stardew/Earthbound-quality selective outline:
// - NEVER uses pure black - always colored dark version of adjacent surface
// - Light-facing edges (top/left): softer darkening (factor 0.50)
// - Shadow-facing edges (bottom/right): stronger darkening (factor 0.28)
// - Cool hue shift on shadow-facing outlines for depth
// - Minimum brightness floor prevents outlines from becoming invisible
function generateOutline(
  sourceBuffer: PixelBuffer,
  outlineBuffer: PixelBuffer,
  w: number, h: number,
  _darkColor: RGBA,  // kept for API compat, selout overrides
  _midColor: RGBA,
  selout: boolean = true
): number {
  const dirs: [number, number][] = [[-1, 0], [1, 0], [0, -1], [0, 1]];
  let count = 0;

  const brightness = (c: RGBA): number => c.r * 0.299 + c.g * 0.587 + c.b * 0.114;

  // Darken with cool hue-shift (shadow outlines lean blue/purple)
  const darkenCool = (c: RGBA, factor: number): RGBA => ({
    r: Math.max(10, clamp(c.r * factor * 0.92)),       // red darkens more
    g: Math.max(10, clamp(c.g * factor * 0.96)),
    b: Math.max(16, clamp(c.b * factor * 1.08 + 4)),   // blue preserved + slight boost
    a: 255,
  });

  // Darken with warm retention (light-facing outlines keep surface warmth)
  const darkenWarm = (c: RGBA, factor: number): RGBA => ({
    r: Math.max(12, clamp(c.r * factor * 1.05)),       // red preserved slightly
    g: Math.max(10, clamp(c.g * factor)),
    b: Math.max(10, clamp(c.b * factor * 0.90)),       // blue darkens more
    a: 255,
  });

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (sourceBuffer.getPixel(x, y).a > 0) continue;

      // Find the brightest adjacent filled pixel
      let hasNeighbor = false;
      let brightestNeighbor: RGBA | null = null;
      let brightestLum = -1;

      for (const [dx, dy] of dirs) {
        const nx = x + dx, ny = y + dy;
        if (nx < 0 || nx >= w || ny < 0 || ny >= h) continue;
        const neighbor = sourceBuffer.getPixel(nx, ny);
        if (neighbor.a > 0) {
          hasNeighbor = true;
          const lum = brightness(neighbor);
          if (lum > brightestLum) {
            brightestLum = lum;
            brightestNeighbor = neighbor;
          }
        }
      }
      if (!hasNeighbor) continue;

      // Edge orientation: light from top-left
      const below = y + 1 < h ? sourceBuffer.getPixel(x, y + 1) : { a: 0 } as RGBA;
      const right = x + 1 < w ? sourceBuffer.getPixel(x + 1, y) : { a: 0 } as RGBA;
      const above = y - 1 >= 0 ? sourceBuffer.getPixel(x, y - 1) : { a: 0 } as RGBA;
      const left  = x - 1 >= 0 ? sourceBuffer.getPixel(x - 1, y) : { a: 0 } as RGBA;

      const isLightFacing = (below.a > 0 || right.a > 0) && (above.a === 0 || left.a === 0);

      let outlineColor: RGBA;
      if (selout && brightestNeighbor) {
        if (isLightFacing) {
          // Light-facing: warmer, softer outline — snap to DB16
          outlineColor = snapToDb16(darkenWarm(brightestNeighbor, 0.50));
        } else {
          // Shadow-facing: cooler, darker outline — snap to DB16
          outlineColor = snapToDb16(darkenCool(brightestNeighbor, 0.28));
        }
      } else {
        // Fallback: still use colored darks (never pure black)
        outlineColor = isLightFacing
          ? { r: 68, g: 36, b: 52, a: 255 }   // DB16 dark maroon #442434
          : { r: 20, g: 12, b: 28, a: 255 };   // DB16 near-black #140c1c
      }

      outlineBuffer.setPixel(x, y, outlineColor);
      count++;
    }
  }
  return count;
}

// ─── Auto directional shading (fallback for templates without color scheme) ──
// Uses Big-Medium-Small principle with improved thresholds:
//   Shadow  → bottom-right ~30% (threshold 0.68)
//   Highlight → top-left ~15% (threshold 0.85)
// With bounce light at 32x32+ for shadow edge quality.
function generateDirectionalShading(
  sourceBuffer: PixelBuffer,
  targetBuffer: PixelBuffer,
  w: number, h: number,
  intensity: number,
  mode: 'shadow' | 'highlight'
): number {
  const filledPixels: Array<{ x: number; y: number; color: RGBA }> = [];
  let minX = w, minY = h, maxX = 0, maxY = 0;

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const pixel = sourceBuffer.getPixel(x, y);
      if (pixel.a === 0) continue;
      filledPixels.push({ x, y, color: pixel });
      if (x < minX) minX = x;
      if (x > maxX) maxX = x;
      if (y < minY) minY = y;
      if (y > maxY) maxY = y;
    }
  }

  if (filledPixels.length === 0) return 0;

  const bboxW = maxX - minX || 1;
  const bboxH = maxY - minY || 1;

  let count = 0;
  const shadedPixels: Array<{ x: number; y: number; color: RGBA }> = [];

  for (const { x, y, color } of filledPixels) {
    const nx = (x - minX) / bboxW;
    const ny = (y - minY) / bboxH;

    if (mode === 'shadow') {
      const score = nx * 0.5 + ny * 0.5;
      if (score <= 0.68) continue;
      const shadedColor = snapToDb16(hueShiftShadow(color, intensity));
      targetBuffer.setPixel(x, y, shadedColor);
      shadedPixels.push({ x, y, color: shadedColor });
      count++;
    } else {
      const score = 1.0 - (nx * 0.5 + ny * 0.5);
      if (score <= 0.85) continue;
      targetBuffer.setPixel(x, y, snapToDb16(hueShiftHighlight(color, intensity)));
      count++;
    }
  }

  // Bounce light pass for shadow mode at 32x32+
  if (mode === 'shadow' && w >= 32) {
    const shadedSet = new Set(shadedPixels.map(p => `${p.x},${p.y}`));
    for (const { x, y, color } of shadedPixels) {
      const abovePixel = y > 0 ? sourceBuffer.getPixel(x, y - 1) : { a: 0 } as RGBA;
      const leftPixel = x > 0 ? sourceBuffer.getPixel(x - 1, y) : { a: 0 } as RGBA;
      const bordersLit =
        (abovePixel.a > 0 && !shadedSet.has(`${x},${y - 1}`)) ||
        (leftPixel.a > 0 && !shadedSet.has(`${x - 1},${y}`));
      if (bordersLit) {
        targetBuffer.setPixel(x, y, snapToDb16(bounceLight(color, 0.6)));
      }
    }
  }

  return count;
}

// ─── Material contrast hierarchy ─────────────────────────────
// Professional pixel art uses different shading intensity per material.
// Metal = HIGH contrast (sharp specular), Cloth = LOW contrast (soft diffuse).
const MATERIAL_CONTRAST: Record<string, { shadowThreshold: number; highlightThreshold: number }> = {
  head:      { shadowThreshold: 0.65, highlightThreshold: 0.82 },  // metal/helmet: high contrast
  face:      { shadowThreshold: 0.75, highlightThreshold: 0.90 },  // skin: low contrast, soft
  eye:       { shadowThreshold: 0.95, highlightThreshold: 0.95 },  // eyes: almost no auto-shade
  body:      { shadowThreshold: 0.68, highlightThreshold: 0.84 },  // armor/cloth: medium
  arm:       { shadowThreshold: 0.68, highlightThreshold: 0.84 },
  hand:      { shadowThreshold: 0.72, highlightThreshold: 0.88 },  // skin: low-med
  belt:      { shadowThreshold: 0.70, highlightThreshold: 0.86 },  // leather: medium
  leg:       { shadowThreshold: 0.68, highlightThreshold: 0.84 },
  boot:      { shadowThreshold: 0.70, highlightThreshold: 0.86 },  // leather
  accessory: { shadowThreshold: 0.65, highlightThreshold: 0.82 },  // metal/accent: high
  hair:      { shadowThreshold: 0.72, highlightThreshold: 0.87 },  // hair: medium-low
};
const DEFAULT_CONTRAST = { shadowThreshold: 0.70, highlightThreshold: 0.85 };

// ─── Material-aware shading using palette colors ─────────────
// Upgraded with:
// - Per-material contrast hierarchy (metal vs cloth vs skin)
// - Bounce light on shadow edge pixels (prevents dead flat shadows)
// - Big-Medium-Small ratio: base ~55%, shadow ~30%, highlight ~15%
// - Each role group gets its own bounding box for local cel-shading
function generateMaterialShading(
  sourceBuffer: PixelBuffer,
  targetBuffer: PixelBuffer,
  w: number, h: number,
  pixelRoleMap: Map<string, string>,
  scheme: ColorScheme,
  mode: 'shadow' | 'highlight'
): number {
  interface RolePixel { x: number; y: number; color: RGBA; role: string | undefined }
  interface RoleBBox { minX: number; minY: number; maxX: number; maxY: number }

  const roleGroups = new Map<string, RolePixel[]>();
  const roleBBoxes = new Map<string, RoleBBox>();
  const noRolePixels: RolePixel[] = [];
  let gMinX = w, gMinY = h, gMaxX = 0, gMaxY = 0;
  let hasNoRole = false;

  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const pixel = sourceBuffer.getPixel(x, y);
      if (pixel.a === 0) continue;

      const role = pixelRoleMap.get(`${x},${y}`);
      const entry: RolePixel = { x, y, color: pixel, role };

      if (role) {
        let group = roleGroups.get(role);
        if (!group) {
          group = [];
          roleGroups.set(role, group);
          roleBBoxes.set(role, { minX: x, minY: y, maxX: x, maxY: y });
        }
        group.push(entry);
        const bbox = roleBBoxes.get(role)!;
        if (x < bbox.minX) bbox.minX = x;
        if (x > bbox.maxX) bbox.maxX = x;
        if (y < bbox.minY) bbox.minY = y;
        if (y > bbox.maxY) bbox.maxY = y;
      } else {
        noRolePixels.push(entry);
        hasNoRole = true;
        if (x < gMinX) gMinX = x;
        if (x > gMaxX) gMaxX = x;
        if (y < gMinY) gMinY = y;
        if (y > gMaxY) gMaxY = y;
      }
    }
  }

  let count = 0;

  // Build filled-pixel set for edge detection
  const filledSet = new Set<string>();
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      if (sourceBuffer.getPixel(x, y).a > 0) filledSet.add(`${x},${y}`);
    }
  }

  // Track shaded positions for bounce light pass
  const shadedPositions: Array<{ x: number; y: number; color: RGBA }> = [];

  const shadePixel = (px: RolePixel, bbox: RoleBBox): boolean => {
    const bboxW = bbox.maxX - bbox.minX || 1;
    const bboxH = bbox.maxY - bbox.minY || 1;
    const nx = (px.x - bbox.minX) / bboxW;
    const ny = (px.y - bbox.minY) / bboxH;

    // Per-material thresholds
    const contrast = px.role ? (MATERIAL_CONTRAST[px.role] ?? DEFAULT_CONTRAST) : DEFAULT_CONTRAST;

    // Edge-detection bonus: pixels on right/bottom edges get shadow boost,
    // pixels on left/top edges get highlight boost
    let edgeBonus = 0;
    const rightEmpty = !filledSet.has(`${px.x + 1},${px.y}`);
    const bottomEmpty = !filledSet.has(`${px.x},${px.y + 1}`);
    const leftEmpty = !filledSet.has(`${px.x - 1},${px.y}`);
    const topEmpty = !filledSet.has(`${px.x},${px.y - 1}`);

    if (mode === 'shadow') {
      if (rightEmpty || bottomEmpty) edgeBonus = 0.15;
    } else {
      if (leftEmpty || topEmpty) edgeBonus = 0.15;
    }

    if (mode === 'shadow') {
      const score = nx * 0.5 + ny * 0.5 + edgeBonus;
      if (score <= contrast.shadowThreshold) return false;
    } else {
      const score = 1.0 - (nx * 0.5 + ny * 0.5) + edgeBonus;
      if (score <= contrast.highlightThreshold) return false;
    }

    const mat = px.role ? scheme.mapping[px.role] : null;
    let color: RGBA;
    if (mat) {
      color = hexToRgba(mode === 'shadow' ? mat.shadow : mat.highlight);
    } else {
      // Fallback: snap computed hue-shift to DB16
      color = mode === 'shadow'
        ? snapToDb16(hueShiftShadow(px.color, 0.35))
        : snapToDb16(hueShiftHighlight(px.color, 0.28));
    }

    targetBuffer.setPixel(px.x, px.y, color);
    if (mode === 'shadow') {
      shadedPositions.push({ x: px.x, y: px.y, color });
    }
    return true;
  };

  // Process each role group
  for (const [, group] of roleGroups) {
    const role = group[0].role!;
    const bbox = roleBBoxes.get(role)!;
    for (const px of group) {
      if (shadePixel(px, bbox)) count++;
    }
  }

  if (hasNoRole) {
    const gBBox: RoleBBox = { minX: gMinX, minY: gMinY, maxX: gMaxX, maxY: gMaxY };
    for (const px of noRolePixels) {
      if (shadePixel(px, gBBox)) count++;
    }
  }

  // Bounce light pass: on shadow edge pixels facing the light source,
  // apply a subtle warm glow to prevent dead-flat shadow regions.
  // Only applies at 32x32+ where there's enough space for the subtlety.
  if (mode === 'shadow' && w >= 32) {
    const shadedSet = new Set(shadedPositions.map(p => `${p.x},${p.y}`));
    for (const { x, y, color } of shadedPositions) {
      // Check if this shadow pixel borders a non-shaded pixel on the light side
      const aboveKey = `${x},${y - 1}`;
      const leftKey = `${x - 1},${y}`;
      const abovePixel = y > 0 ? sourceBuffer.getPixel(x, y - 1) : { a: 0 } as RGBA;
      const leftPixel = x > 0 ? sourceBuffer.getPixel(x - 1, y) : { a: 0 } as RGBA;

      const bordersLitAbove = abovePixel.a > 0 && !shadedSet.has(aboveKey);
      const bordersLitLeft = leftPixel.a > 0 && !shadedSet.has(leftKey);

      if (bordersLitAbove || bordersLitLeft) {
        targetBuffer.setPixel(x, y, snapToDb16(bounceLight(color, 0.6)));
      }
    }
  }

  return count;
}

// ═══════════════════════════════════════════════════════════════
// draw_template tool handler
// ═══════════════════════════════════════════════════════════════
export interface DrawTemplateArgs {
  projectId: string;
  template: string;
  colorScheme?: string;
  colors?: Record<string, string>; // role → hex color override for base color
  autoOutline?: boolean;
  autoShade?: boolean;
  autoHighlight?: boolean;
}

export function handleDrawTemplate(args: DrawTemplateArgs) {
  const project = getProject(args.projectId);
  if (!project) {
    return { content: [{ type: 'text' as const, text: `Error: Project not found` }], isError: true };
  }

  const template = ALL_TEMPLATES[args.template];
  if (!template) {
    const available = Object.keys(ALL_TEMPLATES).join(', ');
    return {
      content: [{
        type: 'text' as const,
        text: `Error: Template "${args.template}" not found. Available: ${available}`,
      }],
      isError: true,
    };
  }

  if (project.width < template.width || project.height < template.height) {
    return {
      content: [{
        type: 'text' as const,
        text: `Error: Project ${project.width}x${project.height} too small for template ${template.width}x${template.height}`,
      }],
      isError: true,
    };
  }

  // Resolve color scheme
  let scheme: ColorScheme | null = null;
  if (args.colorScheme) {
    scheme = ALL_SCHEMES[args.colorScheme] ?? null;
  }
  // Auto-detect color scheme from template name
  if (!scheme) {
    const defaultScheme = args.template.replace(/_\d+$/, '_default');
    scheme = ALL_SCHEMES[defaultScheme] ?? null;
  }
  // Fallback: strip animation suffix (e.g. knight_walk_1 → knight_default)
  if (!scheme) {
    const baseScheme = args.template.replace(/_(walk|idle|attack|hurt)_\d+$/, '_default');
    scheme = ALL_SCHEMES[baseScheme] ?? null;
  }
  // Fallback: try appending _default directly (for keys without _16 suffix, e.g. laptop → laptop_default)
  if (!scheme) {
    scheme = ALL_SCHEMES[args.template + '_default'] ?? null;
  }
  // Fallback: try color variant name directly (e.g. knight_fire)
  if (!scheme) {
    scheme = ALL_SCHEMES[args.template] ?? null;
  }

  // Setup layers: base_color (bottom), shading, highlights, outline (top)
  // Clear existing layers and create fresh ones
  const baseLayer = project.layers[0];
  baseLayer.name = 'base_color';
  baseLayer.buffer.clear();

  // Find or create other layers
  let shadingLayer = project.layers.find(l => l.name === 'shading');
  let highlightLayer = project.layers.find(l => l.name === 'highlights');
  let outlineLayer = project.layers.find(l => l.name === 'outline');

  if (!shadingLayer) shadingLayer = addLayerToProject(project, 'shading');
  else shadingLayer.buffer.clear();
  if (!highlightLayer) highlightLayer = addLayerToProject(project, 'highlights');
  else highlightLayer.buffer.clear();
  if (!outlineLayer) outlineLayer = addLayerToProject(project, 'outline');
  else outlineLayer.buffer.clear();

  // Build pixel → role map for material-aware shading
  const pixelRoleMap = new Map<string, string>();

  // Track which roles have baked tone regions — skip auto-shade for these
  const bakedToneRoles = new Set<string>();
  for (const region of template.regions) {
    if (region.tone) bakedToneRoles.add(region.role);
  }

  // Draw base colors from template regions
  let pixelCount = 0;
  for (const region of template.regions) {
    let color: RGBA;

    // Priority: args.colors override → tone-aware scheme → scheme base → fallback gray
    if (args.colors && args.colors[region.role]) {
      color = hexToRgba(args.colors[region.role]);
    } else if (scheme && scheme.mapping[region.role]) {
      // Use the tone field to pick shadow/base/highlight from scheme
      const triad = scheme.mapping[region.role];
      if (region.tone === 'shadow') {
        color = hexToRgba(triad.shadow);
      } else if (region.tone === 'highlight') {
        color = hexToRgba(triad.highlight);
      } else {
        color = hexToRgba(triad.base);
      }
    } else {
      color = { r: 128, g: 128, b: 128, a: 255 };
    }

    for (const [x, y] of region.pixels) {
      baseLayer.buffer.setPixel(x, y, color);
      pixelRoleMap.set(`${x},${y}`, region.role);
      pixelCount++;
    }
  }

  // Eye highlight - place a bright dot on EACH eye to make characters look alive.
  // For small eye regions (2 pixels = typical 16x16), highlight ALL pixels since
  // each eye is only 1px and needs the highlight to be visible at all.
  // For larger eye regions (4+ pixels = typical 32x32), split into left/right
  // eye groups by x-coordinate gap and highlight the upper-left pixel of each
  // group, simulating top-left light reflection on each eye.
  const eyeHighlight = hexToRgba('#deeed6');
  const eyeBaseHex = (args.colors && args.colors.eye)
    ? args.colors.eye
    : (scheme && scheme.mapping.eye ? scheme.mapping.eye.base : null);
  let allowEyeHighlight = true;
  if (eyeBaseHex) {
    const eyeBase = hexToRgba(eyeBaseHex);
    const eyeLuma = eyeBase.r * 0.299 + eyeBase.g * 0.587 + eyeBase.b * 0.114;
    // Keep naturally dark eyes (e.g. humanoids) dark.
    // Bright/glowing eyes still receive the sparkle pass.
    allowEyeHighlight = eyeLuma > 42;
  }
  for (const region of template.regions) {
    if (!allowEyeHighlight) continue;
    if (region.role === 'eye' && region.name.includes('eye') && region.pixels.length >= 2) {
      const sorted = [...region.pixels].sort((a, b) => a[0] - b[0] || a[1] - b[1]);

      if (sorted.length <= 3) {
        // Small eyes (16x16): highlight ALL eye pixels — each is a separate 1px eye
        for (const [px, py] of sorted) {
          highlightLayer.buffer.setPixel(px, py, eyeHighlight);
        }
      } else {
        // Larger eyes (32x32): split into left/right groups by x-gap, highlight upper-left of each
        const groups: Array<Array<[number, number]>> = [[sorted[0]]];
        for (let i = 1; i < sorted.length; i++) {
          if (sorted[i][0] - sorted[i - 1][0] > 1) {
            groups.push([sorted[i]]);
          } else {
            groups[groups.length - 1].push(sorted[i]);
          }
        }
        for (const group of groups) {
          highlightLayer.buffer.setPixel(group[0][0], group[0][1], eyeHighlight);
        }
      }
    }
  }

  // Auto-outline
  const doOutline = args.autoOutline !== false; // default true
  let outlineCount = 0;
  if (doOutline) {
    const darkOutline = hexToRgba('#140c1c');
    const midOutline = hexToRgba('#442434');
    outlineCount = generateOutline(
      baseLayer.buffer, outlineLayer.buffer,
      project.width, project.height,
      darkOutline, midOutline
    );
  }

  // Auto-shade - use material-aware when scheme is available
  // Skip roles that have baked tone regions (already shaded in base layer)
  const doShade = args.autoShade !== false; // default true
  let shadeCount = 0;
  if (doShade) {
    if (bakedToneRoles.size > 0) {
      // Filter out baked roles from the role map so auto-shade skips them
      const filteredRoleMap = new Map<string, string>();
      for (const [key, role] of pixelRoleMap) {
        if (!bakedToneRoles.has(role)) filteredRoleMap.set(key, role);
      }
      if (scheme) {
        shadeCount = generateMaterialShading(
          baseLayer.buffer, shadingLayer.buffer,
          project.width, project.height,
          filteredRoleMap, scheme, 'shadow'
        );
      } else if (filteredRoleMap.size > 0) {
        shadeCount = generateDirectionalShading(
          baseLayer.buffer, shadingLayer.buffer,
          project.width, project.height,
          0.35, 'shadow'
        );
      }
    } else {
      if (scheme) {
        shadeCount = generateMaterialShading(
          baseLayer.buffer, shadingLayer.buffer,
          project.width, project.height,
          pixelRoleMap, scheme, 'shadow'
        );
      } else {
        shadeCount = generateDirectionalShading(
          baseLayer.buffer, shadingLayer.buffer,
          project.width, project.height,
          0.35, 'shadow'
        );
      }
    }
  }

  // Auto-highlight - use material-aware when scheme is available
  const doHighlight = args.autoHighlight !== false; // default true
  let highlightCount = 0;
  if (doHighlight) {
    if (bakedToneRoles.size > 0) {
      const filteredRoleMap = new Map<string, string>();
      for (const [key, role] of pixelRoleMap) {
        if (!bakedToneRoles.has(role)) filteredRoleMap.set(key, role);
      }
      if (scheme) {
        highlightCount = generateMaterialShading(
          baseLayer.buffer, highlightLayer.buffer,
          project.width, project.height,
          filteredRoleMap, scheme, 'highlight'
        );
      } else if (filteredRoleMap.size > 0) {
        highlightCount = generateDirectionalShading(
          baseLayer.buffer, highlightLayer.buffer,
          project.width, project.height,
          0.28, 'highlight'
        );
      }
    } else {
      if (scheme) {
        highlightCount = generateMaterialShading(
          baseLayer.buffer, highlightLayer.buffer,
          project.width, project.height,
          pixelRoleMap, scheme, 'highlight'
        );
      } else {
        highlightCount = generateDirectionalShading(
          baseLayer.buffer, highlightLayer.buffer,
          project.width, project.height,
          0.28, 'highlight'
        );
      }
    }
  }

  project.updatedAt = Date.now();

  const layerInfo = project.layers.map(l => ({ id: l.id, name: l.name }));

  return {
    content: [{
      type: 'text' as const,
      text: JSON.stringify({
        template: template.name,
        description: template.description,
        pixelsDrawn: pixelCount,
        outlinePixels: outlineCount,
        shadowPixels: shadeCount,
        highlightPixels: highlightCount,
        layers: layerInfo,
        hint: 'Use get_preview to see the result. Customize with set_pixels, replace_color, or set_palette. Eyes and details can be refined manually.',
      }, null, 2),
    }],
  };
}

// ═══════════════════════════════════════════════════════════════
// list_templates tool handler
// ═══════════════════════════════════════════════════════════════
export function handleListTemplates() {
  const templates = Object.entries(ALL_TEMPLATES).map(([key, t]) => ({
    id: key,
    name: t.name,
    size: `${t.width}x${t.height}`,
    description: t.description,
    regions: t.regions.map(r => r.name),
  }));

  const schemes = Object.entries(ALL_SCHEMES).map(([key, s]) => ({
    id: key,
    roles: Object.keys(s.mapping),
  }));

  return {
    content: [{
      type: 'text' as const,
      text: JSON.stringify({ templates, colorSchemes: schemes }, null, 2),
    }],
  };
}
